define([], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  var D={};D.n=void 0;D.o=!0;D.r=null;D.u=!1;D.ba=function(){return function(b){return b}};D.z=function(){return function(){}};D.B=function(b){return function(c){this[b]=c}};D.C=function(b){return function(){return this[b]}};D.ca=function(b){return function(){return b}};D.COMPILED=D.o;D.da=this==window?this:window;D.ea="";
if(!D.COMPILED){D.fa={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}};D.ga=function(){var b=D.da.document;return"undefined"!=typeof b&&"write"in b};D.ha=function(b){return(0,D.ga)()?(D.da.document.write('\x3cscript type\x3d"text/javascript" src\x3d"'+b+'"\x3e\x3c/script\x3e'),D.o):D.u};if(D.da.CLOSURE_BASE_PATH)D.ea=D.da.CLOSURE_BASE_PATH;else if((0,D.ga)())for(D.ia=D.da.document.getElementsByTagName("script"),D.ja=D.ia.length-1;0<=D.ja;--D.ja){D.ka=D.ia[D.ja].src;D.la=D.ka.lastIndexOf("?");
D.ma=-1==D.la?D.ka.length:D.la;if("base.js"==D.ka.substr(D.ma-7,7)){D.ea=D.ka.substr(0,D.ma-7);break}}if(!D.da.CLOSURE_NO_DEPS){D.oa=D.ea+"deps.js";D.qa=D.da.CLOSURE_IMPORT_SCRIPT||D.ha;!D.fa.written[D.oa]&&(0,D.qa)(D.oa)&&(D.fa.written[D.oa]=D.o)}}window.Math.floor(2147483648*window.Math.random()).toString(36);D.ta=function(b,c){var d=b.split("."),e=D.da;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)!d.length&&c!==D.n?e[f]=c:e=e[f]?e[f]:e[f]={}};
D.DVT_ADVANCED_CLOSURE=D.o;D.ua=function(b){this.z8=-1;this.mU=b;b=window.navigator&&window.navigator.userAgent?window.navigator.userAgent.toLowerCase():D.r;this.$Fa=this.v0(b);this.platform=this.w0(b)};D.hb=function(b){if(-1==b.z8){var c=window.document.createElement("div");c.style.cssText="width:100px;height:100px;overflow:scroll;position:absolute;top:-9999px;";window.document.body.appendChild(c);b.z8=c.offsetWidth-c.clientWidth;window.document.body.removeChild(c)}return b.z8};
D.ua.prototype.da=function(){if(this.Ana==D.n){var b=window.navigator.userAgent.toLowerCase();this.Ana=-1!=b.indexOf("mobile")||-1!=b.indexOf("android")?D.o:D.u}return this.Ana};D.Ba=function(b,c){var d,e;c!=D.r&&b!=D.r&&(d=b.className,e=(0,D.Wc)(d,c),-1==e&&(b.className=d?c+" "+d:c))};D.za=function(b,c){var d,e,f;c!=D.r&&b!=D.r&&(d=b.className,e=(0,D.Wc)(d,c),-1!=e&&(f=e+c.length,e=0==e?D.r:d.substring(0,e),d=f==d.length?D.r:d.substring(f+1),b.className=e==D.r?d==D.r?"":d:d==D.r?e:e+d))};
D.ya=function(b,c){return c!=D.r&&b!=D.r?-1!=(0,D.Wc)(b.className,c):D.u};D.Wc=function(b,c){var d,e,f,g,h,k;if(!b||!b.indexOf)return-1;if(c===b)return 0;d=c.length;e=b.length;f=b.indexOf(c);if(0<=f){g=0==f||" "==b.charAt(f-1);h=f+d;h=h==e||" "==b.charAt(h);if(g&&h)return f;k=b.lastIndexOf(c);if(k!=f)return g=b.charAt(k-1),h=k+d,h=h==e||" "==b.charAt(h),g&&h?k:b.indexOf(" "+c+" ")}return-1};D.Cc=function(b,c){return"Mac"===b.$Fa?c.metaKey:c.ctrlKey};
D.Ib=function(b,c){var d,e;if(b.mU.fb().isRTLMode()){if("gecko"==b.platform||"ie"==b.platform)return window.Math.abs(c.scrollLeft);d=(0,D.cb)(b.mU.kd.firstChild);e=(0,window.parseInt)(c.style.width,10);return window.Math.max(0,d-e-c.scrollLeft)}return c.scrollLeft};D.kb=function(b,c,d){var e;b.mU.fb().isRTLMode()?"gecko"===b.platform?c.scrollLeft=0-d:"ie"==b.platform?c.scrollLeft=d:(b=(0,D.cb)(b.mU.kd.firstChild),e=(0,window.parseInt)(c.style.width,10),c.scrollLeft=b-e-d):c.scrollLeft=d};
D.ua.prototype.v0=function(b){if(b){if(-1!=b.indexOf("win"))return"Windows";if(-1!=b.indexOf("mac"))return"Mac";if(-1!=b.indexOf("sunos"))return"Solaris"}return"Unknown"};D.ua.prototype.w0=function(b){if(b&&-1==b.indexOf("opera")){if(-1!=b.indexOf("trident")||-1!=b.indexOf("msie"))return"ie";if(-1!=b.indexOf("applewebkit")||-1!=b.indexOf("safari"))return"webkit";if(-1!=b.indexOf("gecko/"))return"gecko"}return"unknown"};
D.xa=(0,D.B)("options");D.Ga=function(b,c,d,e){return c!=D.r?(b=b.options[c],d!=D.r&&b!=D.r?(d=b[d],e!=D.r&&d!=D.r?d[e]:d):b):D.r};D.xa.prototype.evaluate=function(b,c){return"function"==typeof b?b.call(this,c):b};D.wd=function(b,c,d){var e,f,g;"row"==d||"column"==d?(e="header",f=d,g=c):"cell"==d&&(e="cell",f=c);return(0,D.Ga)(b,e,f,g)};D.xa.prototype.oa=function(b,c,d){return this.evaluate((0,D.wd)(this,b,c),d)};D.rb=function(b){return b!=D.r?b:D.u};
D.Hb=function(b){b=(0,D.Ga)(b,"bandingInterval","row");return b!=D.r?b:0};D.Aa=function(b){b=(0,D.Ga)(b,"bandingInterval","column");return b!=D.r?b:0};D.xa.prototype.$G=function(){return(0,D.Ga)(this,"emptyText")};D.Da=function(b){b=(0,D.Ga)(b,"gridlines","horizontal");return b!=D.r?b:"visible"};D.Ea=function(b){b=(0,D.Ga)(b,"gridlines","vertical");return b!=D.r?b:"visible"};D.$b=function(b){var c;c=(0,D.Ga)(b,"selectionMode");if(c==D.n)return"none";b=b.rj();c=c[b];return c!=D.r?c:"none"};
D.xa.prototype.rj=function(){var b;b=(0,D.Ga)(this,"selectionMode");if(b==D.n)return"cell";b=b.row;return b!=D.r&&"none"!=b?"row":"cell"};D.bc=function(b,c,d){return(0,D.rb)(b.oa("resizable",c,d))};D.xa.prototype.ks=function(b,c){return this.oa("style",b,c)};D.xa.prototype.xz=function(b,c){return this.oa("className",b,c)};D.ob=function(b,c){return(0,D.wd)(b,"renderer",c)};
D.va=function(){this.tW={column:{},row:{}}};D.va.prototype.Zj=function(b,c,d){this.tW[b][c]=d};D.va.prototype.vc=function(b,c){return this.tW[b].hasOwnProperty(c)?this.tW[b][c]:D.r};D.va.prototype.clear=function(){this.tW={column:{},row:{}}};
D.wa=function(){this.TIMEOUT=100;this.SO=20;this.VD=30;this.BH=[];this.AH=[];this.Xf=new D.ua(this);this.CH=D.u;this.$C=this.Uw=0;this.rN=new D.va;this.zV=this.LV=D.r;this.IH={};this.mN=this.tN=D.u;this.Pna=this.Qna=D.n;this.hD=this.sN=this.iD=this.HH=D.u;this.Oka={}};(0,D.ta)("DvtDataGrid",D.wa);D.wa.prototype.oe=function(b){this.gc=new D.xa(b)};D.wa.prototype.SetOptions=D.wa.prototype.oe;
D.wa.prototype.hsa=function(b){for(window.candidate in b)window.candidate in this.gc.options&&this.gc.options[window.candidate]!=b[window.candidate]&&(this.gc.options[window.candidate]=b[window.candidate]);for(window.candidate in b){a:{b=D.n;switch(window.candidate){case "bandingInterval":var c=b=D.n,d=D.n,e=D.n,f=D.n;b=this.nb.firstChild.childNodes;f=this.getMappedStyle("banded");for(d=1;d<b.length;d++){(0,D.ya)(b[d],f)&&(0,D.za)(b[d],f);c=b[d].childNodes;for(e=0;e<c.length;e+=1)(0,D.ya)(c[e],f)&&
(0,D.za)(c[e],f)}var g=f=e=d=c=b=D.n,h=D.n;b=(0,D.Aa)(this.gc);if(0<b){c=this.nb.firstChild.childNodes;f=this.getMappedStyle("banded");for(d=1;d<c.length;d+=1){h=c[d].childNodes;for(g=0;g<h.length;g+=1)e=this.Md+g,1===window.Math.floor(e/b)%2?(0,D.ya)(h[g],f)||(0,D.Ba)(h[g],f):(0,D.ya)(h[g],f)&&(0,D.za)(c[g],f)}}(0,D.Ca)(this);break;case "gridlines":var k=h=g=f=e=d=c=b=D.n,f=(0,D.Da)(this.gc),g=(0,D.Ea)(this.gc),h=this.nb.firstChild.childNodes,e=h.length,k=this.fb().isRTLMode()?"right":"left";for(b=
1;b<e;b+=1){d=h[b].childNodes;for(c=0;c<d.length-1;c+=1)"hidden"===g?"left"===k?d[c].style.borderRight="none":d[c].style.borderLeftStyle="none":"left"===k?d[c].style.borderRight="":d[c].style.borderLeftStyle="",d[c].style.borderBottomStyle="hidden"===f||b==e-1?"none":""}break;case "scrollPosition":(0,D.Fa)(this);break;case "selectionMode":break;case "emptyText":break;case "header":b=this.gc.options.header;g=f=e=d=c=D.n;this.fb().getMappedAttribute("key");g=D.u;for(f in b)if("column"==f||"row"==f){if(g)break;
"column"==f?this.Ld&&(e=this.Ld.firstChild.childNodes):this.tc&&1<this.tc.firstChild.childElementCount&&(e=this.tc.firstChild.childNodes);if(e)for(d in c=b[f],c){b:{var h=e,k=d,m=c[d],p=D.n,q=D.n,t=D.n;this.fb().getMappedAttribute("key");q=this.fb().getMappedAttribute(k);t=m;m.width?t=m.width:m.height&&(t=m.height);for(p=0;p<h.length;p++)if("disable"==t)h[p].setAttribute(q,"false");else if("enable"==t)h[p].setAttribute(q,"true");else{h=D.u;break b}h=D.o}if(!h){g=D.o;break}}}g&&this.refresh(this.Kf);
break;default:b=D.u;break a}b=D.o}if(!b){this.refresh(this.Kf);break}}};D.wa.prototype.UpdateOptions=D.wa.prototype.hsa;D.wa.prototype.Xra=(0,D.B)("ws");D.wa.prototype.SetResources=D.wa.prototype.Xra;D.wa.prototype.fb=(0,D.C)("ws");D.wa.prototype.getResources=D.wa.prototype.fb;D.wa.prototype.getMappedStyle=function(b){return this.fb().getMappedStyle(b)};
D.wa.prototype.Wra=function(b){b!=D.r&&(b.on("change",this.v7.bind(this),this),b.on("expand",this.Wma.bind(this),this),b.on("collapse",this.Vma.bind(this),this));this.Pc=b};D.wa.prototype.SetDataSource=D.wa.prototype.Wra;D.wa.prototype.JCa=(0,D.C)("Pc");D.wa.prototype.getDataSource=D.wa.prototype.JCa;D.wa.prototype.Vra=(0,D.B)("BV");D.wa.prototype.SetCreateContextCallback=D.wa.prototype.Vra;D.Ha=function(b){b=(0,D.Ga)(b.gc,"scrollPolicy");b==D.r&&(b="auto");return"scroll"!=b};
D.wa.prototype.V=function(){delete this.Rk;window.document.removeEventListener("mousemove",this.Mna,D.u);window.document.removeEventListener("mouseup",this.Nna,D.u);this.Pc!=D.r&&(this.Pc.off("change",this.v7),this.Pc.off("expand",this.Wma),this.Pc.off("collapse",this.Vma));this.Kf!=D.r&&this.S7&&this.Kf.removeEventListener("keydown",this.S7,D.u);delete this.IH;this.IH={}};D.wa.prototype.destroy=D.wa.prototype.V;D.wa.prototype.getWidth=function(){this.Vna==D.r&&(this.Vna=this.Kf.offsetWidth);return this.Vna};
D.wa.prototype.getHeight=function(){this.Ona==D.r&&(this.Ona=this.Kf.offsetHeight);return this.Ona};D.Ia=function(b){b=b.getWidth();return window.Math.round(1.5*b)};D.Ja=function(b){b=b.getHeight();return window.Math.round(1.5*b)};D.La=function(b,c){return"row"==c?(b.Tna==D.r&&(b.Tna=window.Math.round((0,D.Ja)(b)/(0,D.Ka)(b))),b.Tna):"column"==c?(b.Kna==D.r&&(b.Kna=window.Math.round((0,D.Ia)(b)/50)),b.Kna):0};
D.wa.prototype.$G=function(){var b;b=this.gc.$G();b==D.r&&(b=this.fb(),b=b.getTranslatedText("msgNoData"));return b};D.Ka=function(b){var c,d;b.Lna==D.r&&(c=window.document.createElement("div"),d=b.fb(),c.className=d.getMappedStyle("colheader")+" "+d.getMappedStyle("headercell"),c.style.visibilty="hidden",c.style.top="0px",c.style.visibilty="0px",c.style.height="auto",c.innerHTML="hq",b.Kf.appendChild(c),d=c.offsetHeight,b.Kf.removeChild(c),b.Lna=window.Math.max(d,30));return b.Lna};
D.Ma=function(b){var c;c=b.className;b=b.style.cssText;return 0<b.indexOf("width")||0<b.indexOf("height")?c.concat(b):c};D.Na=function(b,c,d,e){var f;f=b.rN.vc("row",e);if(f!=D.r)return f;f=b.BH[d-b.$C];if(f==D.r)e=(0,D.Ma)(c),f=b.IH[e],f==D.r&&(c.style.visibility="hidden",window.document.body.appendChild(c),f=c.offsetHeight,c.style.visibility="visible",b.IH[e]=f);else return f;0===f&&(f=(0,D.Ka)(b));0>d-b.$C?b.BH.unshift(f):b.BH[d-b.$C]=f;return f};
D.Pa=function(b,c,d,e){var f;f=b.rN.vc("column",e);if(f!=D.r)return f;f=b.AH[d-b.Uw];if(f==D.r)e=(0,D.Ma)(c),f=b.IH[e],f==D.r&&(""===c.style.width&&(0,D.Oa)(c,50),c.style.visibility="hidden",window.document.body.appendChild(c),f=c.offsetWidth,c.style.visibility="visible",b.IH[e]=f);else return f;0===f&&(f=50);0>d-b.Uw?b.AH.unshift(f):b.AH[d-b.Uw]=f;return f};D.Qa=function(b,c){var d=b.Kf.id;d==D.r&&(d="");return[d,c].join(":")};D.Sa=function(b){return b.Rk.row===D.u&&b.Rk.column===D.u};
D.Ta=function(b){return(0,D.Sa)(b)&&b.Rk.cells===D.u};D.Va=function(b,c){return(0,D.Ua)(b,"row")?c+1===b.Td&&b.HH:c+1===b.Pc.getCount("row")};D.Wa=function(b,c){return(0,D.Ua)(b,"column")?c+1===b.Wf&&b.sN:c+1===b.Pc.getCount("column")};D.wa.prototype.refresh=function(b){this.V();(0,D.Xa)(this);this.L(b)};D.wa.prototype.refresh=D.wa.prototype.refresh;
D.Xa=function(b){b.BH=[];b.AH=[];b.rN.clear();b.Uw=0;b.$C=0;b.tN=D.u;b.mN=D.u;b.Q7=D.r;b.yV=D.r;b.AV=D.r;b.KV=D.r;b.Em=D.n;b.ap=D.n;b.Ld=D.r;b.tc=D.r;b.nb=D.r;b.kd=D.r;b.Qna=D.n;b.Pna=D.n;b.HH=D.u;b.iD=D.u;b.sN=D.u;b.hD=D.u};
D.wa.prototype.L=function(b){this.nb!=D.r&&(this.V(),(0,D.Xa)(this));this.mLa=new window.Date;this.Rk={};this.Ng=this.Pk=this.cp=this.Qk=this.gD=this.Gu=this.vs=this.uj=this.vj=this.Ql=this.Lh=this.Jf=this.Fu=this.Fm=this.Wf=this.Td=this.Md=this.Lc=0;var c,d,e;this.Kf=b;this.Kf.className=this.getMappedStyle("datagrid");this.Kf.setAttribute("role","application");this.Kf.setAttribute("aria-describedby",(0,D.Qa)(this,"summary"));this.Mq=D.u;b.tabIndex=0;c=window.document.createElement("div");c.id=(0,D.Qa)(this,
"status");c.className=this.getMappedStyle("status");c.setAttribute("role","status");b.appendChild(c);this.GH=c;c=window.document.createElement("div");c.id=(0,D.Qa)(this,"summary");c.className=this.getMappedStyle("info");b.appendChild(c);this.DFa=c;c=window.document.createElement("div");c.id=(0,D.Qa)(this,"info");c.className=this.getMappedStyle("info");c.setAttribute("role","status");b.appendChild(c);this.CFa=c;c=window.document.createElement("div");c.id=(0,D.Qa)(this,"state");c.className=this.getMappedStyle("info");
b.appendChild(c);this.Una=c;if(this.Pc!=D.r){c=this.fb().isRTLMode();d=(0,D.Ya)(this,"column",this.getMappedStyle("colheader"));e=(0,D.Ya)(this,"row",this.getMappedStyle("rowheader"));var f=window.document.createElement("div");f.id=(0,D.Qa)(this,"scroller");f.className=this.getMappedStyle("scrollers");f.addEventListener?f.addEventListener("scroll",this.fna.bind(this),D.u):f.attachEvent("onscroll",this.fna.bind(this));var g=window.document.createElement("div");g.id=(0,D.Qa)(this,"databody");g.className=
this.getMappedStyle("databody");this.fetchCells(g,f,0,0);c&&(d.style.direction="rtl",g.style.direction="rtl",f.style.direction="rtl");b.appendChild(d);b.appendChild(e);b.appendChild(f);b.appendChild(g);this.Ld=d;this.tc=e;this.nb=g;this.kd=f;this.eD=D.u;this.ve=D.r;this.DV=D.u;this.S7=this.rEa.bind(this);this.Mna=this.zEa.bind(this);this.Nna=this.AEa.bind(this);this.Xf.da()?(g.addEventListener("touchstart",this.HEa.bind(this),D.u),g.addEventListener("touchmove",this.GEa.bind(this),D.u),g.addEventListener("touchend",
this.FEa.bind(this),D.u),g.addEventListener("touchcancel",this.oH.bind(this),D.u),d.addEventListener("touchstart",this.cna.bind(this),D.u),d.addEventListener("touchmove",this.bna.bind(this),D.u),d.addEventListener("touchend",this.ana.bind(this),D.u),d.addEventListener("touchcancel",this.gV.bind(this),D.u),e.addEventListener("touchstart",this.cna.bind(this),D.u),e.addEventListener("touchmove",this.bna.bind(this),D.u),e.addEventListener("touchend",this.ana.bind(this),D.u),e.addEventListener("touchcancel",
this.gV.bind(this),D.u)):(window.document.addEventListener("mousemove",this.Mna,D.u),window.document.addEventListener("mouseup",this.Nna,D.u),b.addEventListener("keydown",this.S7,D.u),g.addEventListener("mousewheel",this.xEa.bind(this),D.u),g.addEventListener("mousedown",this.sEa.bind(this),D.u),g.addEventListener("mousemove",this.tEa.bind(this),D.u),g.addEventListener("mouseup",this.wEa.bind(this),D.u),g.addEventListener("mouseout",this.uEa.bind(this),D.u),g.addEventListener("mouseover",this.vEa.bind(this),
D.u),e.addEventListener("mousedown",this.Yma.bind(this),D.u),d.addEventListener("mousedown",this.Yma.bind(this),D.u),e.addEventListener("mouseover",this.$ma.bind(this),D.u),d.addEventListener("mouseover",this.$ma.bind(this),D.u),e.addEventListener("mousemove",this.CEa.bind(this),D.u),e.addEventListener("mouseup",this.yEa.bind(this),D.u),e.addEventListener("mouseout",this.Zma.bind(this),D.u),d.addEventListener("mouseout",this.Zma.bind(this),D.u),e.addEventListener("click",this.Xma.bind(this),D.u),
d.addEventListener("click",this.Xma.bind(this),D.u),f.addEventListener("mousedown",this.DEa.bind(this),D.u),f.addEventListener("mouseup",this.EEa.bind(this),D.u));if((0,D.Ta)(this)&&!this.Mq){if((0,D.$a)(this),(0,D.Fa)(this),this.DH!=D.r){for(b=0;b<this.DH.length;b++)this.v7(this.DH[b]);this.DH.length=0}}else(0,D.Sa)(this)&&!this.Mq&&(0,D.ab)(this)}else c=this.$G(),b=window.document.createElement("div"),b.className=this.getMappedStyle("emptytext"),b.setAttribute("id",(0,D.Qa)(this,"empty")),b.innerHTML=
c,this.Kf.appendChild(b)};D.wa.prototype.render=D.wa.prototype.L;D.ab=function(b){var c,d,e,f,g,h,k;b.Ld==D.r||b.tc==D.r||(c=b.getWidth(),d=b.getHeight(),e=b.Ld,f=b.tc,g=(0,D.bb)(e),h=(0,D.cb)(f),k=b.fb().isRTLMode()?"right":"left",(0,D.eb)(f,0,k),(0,D.eb)(f,g,"top"),(0,D.fb)(f,d-g),(0,D.eb)(e,h,k),(0,D.Oa)(e,c-h),b.Xf.da()||(0,D.gb)(b))};
D.$a=function(b){var c,d,e,f,g,h,k,m,p,q,t,v,w,A,D$;b.nb!=D.r&&(b.nb.firstChild==D.r?(f=b.$G(),e=window.document.createElement("div"),e.className=b.getMappedStyle("emptytext"),(0,D.eb)(e,0,"top"),e.innerHTML=f,b.Kf.appendChild(e)):(b.Sna==D.r&&(b.Sna=(0,window.parseInt)(window.document.defaultView.getComputedStyle(b.Kf,D.r).getPropertyValue("border-top-width"),10)),e=b.Sna,c=b.getWidth()-2*e,d=b.getHeight()-2*e,e=b.Ld,f=b.tc,g=b.kd,h=b.nb,k=(0,D.bb)(e),m=(0,D.cb)(f),p=(0,D.cb)(h.firstChild),q=(0,D.bb)(h.firstChild),
d-=k,D$=c-m,c=window.Math.min(p,D$),t=window.Math.min(q,d),b.Xf.da(),A=(0,D.hb)(b.Xf),(v=(0,D.ib)(b,D$))?w=(0,D.jb)(b,d-A):(w=(0,D.jb)(b,d))&&(v=(0,D.ib)(b,D$-A)),b.Du=v,b.Eu=w,v&&(d-A>=t||(t=d-A)),w&&(D$-A>=c||(c=D$-A)),v=b.fb().isRTLMode()?"right":"left",(0,D.eb)(f,0,v),(0,D.eb)(f,k,"top"),(0,D.fb)(f,t),(0,D.eb)(e,m,v),(0,D.Oa)(e,c),(0,D.eb)(h,k,"top"),(0,D.eb)(h,m,v),(0,D.Oa)(h,c),(0,D.fb)(h,t),(0,D.eb)(g,k,"top"),(0,D.eb)(g,m,v),(0,D.Oa)(g,D$),(0,D.fb)(g,d),b.FFa=p-c,b.EFa=q-t,(0,D.gb)(b),b.Mq=
D.o))};
D.gb=function(b){var c,d,e,f,g,h,k,m;(0,D.hb)(b.Xf);k=(0,D.cb)(b.kd);m=(0,D.bb)(b.kd);c=(0,D.bb)(b.Ld);g=(0,D.cb)(b.Ld);d=(0,D.cb)(b.tc);h=(0,D.bb)(b.tc);f=b.fb().isRTLMode()?"right":"left";b.Q7!=D.r&&b.Kf.removeChild(b.Q7);b.KV!=D.r&&b.Kf.removeChild(b.KV);b.AV!=D.r&&b.Kf.removeChild(b.AV);b.yV!=D.r&&b.Kf.removeChild(b.yV);1!==b.tc.firstChild.childNodes.length&&(e=window.document.createElement("div"),e.id=(0,D.Qa)(b,"corner"),e.className=b.getMappedStyle("topcorner"),(0,D.Oa)(e,d),(0,D.fb)(e,c),
b.Kf.appendChild(e),b.Q7=e);b.Du?(e=window.document.createElement("div"),e.id=(0,D.Qa)(b,"rhSbSpacer"),e.className=b.getMappedStyle("rowheaderspacer"),(0,D.eb)(e,h+c,"top"),(0,D.eb)(e,0,f),(0,D.Oa)(e,d),(0,D.fb)(e,m-h),b.Kf.appendChild(e),b.KV=e):b.KV=D.r;b.Eu?(e=window.document.createElement("div"),e.id=(0,D.Qa)(b,"chSbSpacer"),e.className=b.getMappedStyle("colheaderspacer"),(0,D.eb)(e,d+g,f),(0,D.Oa)(e,k-g),(0,D.fb)(e,c),b.Kf.appendChild(e),b.AV=e):b.AV=D.r;b.Du&&b.Eu?(e=window.document.createElement("div"),
e.id=(0,D.Qa)(b,"bcorner"),e.className=b.getMappedStyle("bottomcorner"),(0,D.eb)(e,h+c,"top"),(0,D.eb)(e,d+g,f),(0,D.Oa)(e,k-g),(0,D.fb)(e,m-h),b.Kf.appendChild(e),b.yV=e):b.yV=D.r};
D.Fa=function(b){var c,d,e;e=d=0;c=(0,D.Ga)(b.gc,"scrollPosition");c=c==D.n?D.r:c.key!=D.n?"key":c.index!=D.n?"index":D.r;if(b.kd!=D.n){if(c!=D.r){d=b.gc;e=(0,D.Ga)(d,"scrollPosition","key","column");d=e!=D.r?e:(0,D.Ga)(d,"scrollPosition","index","column");e=b.gc;var f;f=(0,D.Ga)(e,"scrollPosition","key","row");e=f!=D.r?f:(0,D.Ga)(e,"scrollPosition","index","row");"key"===c&&(c=b.Pc.indexes({row:e,column:d}),d=-1===c.column?0:c.column,e=-1===c.row?0:c.row);d*=b.ap;e*=b.Em}(0,D.kb)(b.Xf,b.kd,d);b.kd.scrollTop=
e}};D.ib=function(b,c){var d;d=b.nb;return(0,D.cb)(d.firstChild)>(c==D.r?(0,D.cb)(d):c)?D.o:D.u};D.jb=function(b,c){var d;d=b.nb;return(0,D.bb)(d.firstChild)>(c==D.r?(0,D.bb)(d):c)?D.o:D.u};D.wa.prototype.Ura=function(b){b!=D.r&&b.message&&(this.Una.innerHTML=b.message)};D.wa.prototype.SetAccessibleContext=D.wa.prototype.Ura;D.lb=function(b){var c=b.fb().getTranslatedText("accessibleStateSelected");c!=D.r&&(b.Una.innerHTML=c)};
D.Ua=function(b,c){var d,e;d=b.Pc;return"row"===c?(b.pga===D.n&&(e=d.getCountPrecision("row"),d=d.getCount("row"),b.pga="estimate"===e||0>d?D.o:D.u),b.pga):"column"===c?(b.oga===D.n&&(e=d.getCountPrecision("column"),d=d.getCount("column"),b.oga="estimate"===e||0>d?D.o:D.u),b.oga):D.u};D.mb=function(b,c){return(0,D.Ua)(b,c)||(0,D.Ha)(b)};D.Ya=function(b,c,d){var e=window.document.createElement("div");e.id=(0,D.Qa)(b,c+"Header");e.className=d+" "+b.getMappedStyle("header");b.fetchHeaders(c,0,e);return e};
D.wa.prototype.fetchHeaders=function(b,c,d,e,f){var g,h;this.Rk[b]||(this.Rk[b]={start:c},e==D.n&&(e=(0,D.La)(this,b),(0,D.Ua)(this,b)||(g="row"==b?this.Lc:this.Md,h="row"==b?this.Td:this.Wf,c<g?e=window.Math.min(e,g):(g=this.Pc.getCount(b),0<=g&&(e=window.Math.min(e,window.Math.max(0,g-h)))))),b={axis:b,start:c,count:e,header:d},f=f!=D.r&&f.success!=D.r?f.success:this.bN,(0,D.nb)(this),this.Pc.fetchHeaders(b,{success:f,error:this.t7},{success:this,error:this}))};
D.wa.prototype.bN=function(b,c,d){var e,f,g;if(c.start==this.Rk[c.axis].start){e=c.axis;this.Rk[e]=D.u;f=c.header;c=c.start;g=this.Pc.getCount(e);if("column"===e)a:{var h,k,m,p,q,t,v,w,A,D$,K,G,M,O,T,Q;e=(0,D.Ka)(this);p=b.getCount();if(f.hasChildNodes()){if(0==p&&(0,D.Ua)(this,"column")){this.hD=D.o;break a}e=f.firstChild}else 0==p?((0,D.fb)(f,0),this.hD=D.o):(0,D.fb)(f,e),e=window.document.createElement("div"),e.className=this.getMappedStyle("row")+" "+(this.Xf.da()?this.getMappedStyle("scroller-mobile"):
this.getMappedStyle("scroller"));h=(0,D.ob)(this.gc,"column");k=0;m=c<this.vj?this.gD:this.cp;q=e.firstChild;t=this.getMappedStyle("headercell")+" "+this.getMappedStyle("colheadercell");v=this.fb().isRTLMode()?"right":"left";T=this.fb().getMappedAttribute("sortable");Q=this.fb().getMappedAttribute("resizable");for(w=0;w<p;w+=1){A=c<this.vj?c+p-1-w:c+w;O=window.document.createElement("div");O.id=(0,D.Qa)(this,"c"+A);e.appendChild(O);D$=b.getData(A);K=b.getMetadata(A);K=(0,D.pb)(this,"column",A,D$,
K,O);G=this.gc.ks("column",K);M=this.gc.xz("column",K);A===g-1&&("left"===v?O.style.borderRightStyle="none":O.style.borderLeftStyle="none");G!=D.r&&(O.style.cssText=G);O.className=M!=D.r?t+" "+M:t;this.zV==D.r&&""!=O.style.height&&(this.zV=(0,D.bb)(O),(0,D.fb)(f,this.zV));O.style.height="100%";c<this.vj?(A=(0,D.Pa)(this,O,c+p-1-w,K.key),this.Uw-=1):A=(0,D.Pa)(this,O,c+w,K.key);(0,D.Oa)(O,A);c<this.vj?(0,D.eb)(O,m-A,v):(0,D.eb)(O,m,v);(0,D.qb)(this,"column",K)&&O.setAttribute(Q,"true");h!=D.r?(D$=
h.call(this,K),D$!=D.r&&(D$.parentNode===D.r?O.appendChild(D$):D$.parentNode==D.r&&D$.toString&&O.appendChild(window.document.createTextNode(D$.toString())))):O.appendChild(window.document.createTextNode(D$.toString()));D$=K;M=G=D.n;G=this.Pc.getCapability("sort");M=(0,D.rb)(this.gc.oa("sortable","column",D$));if(("enable"===M||"auto"===M)&&("full"===G||"column"===G)){var V=M=G=D$=D.n,V=window.document.createElement("div");V.className=this.getMappedStyle("sortcontainer");D$=window.document.createElement("div");
G=this.getMappedStyle("icon")+" "+this.getMappedStyle("clickableicon");K.key===(this.In!=D.r?this.In.key:D.r)?(M=this.In!=D.r?this.In.direction:D.r,"ascending"===M?D$.className=this.getMappedStyle("sortascending")+" "+G+" "+this.getMappedStyle("default"):"descending"===M&&(D$.className=this.getMappedStyle("sortdescending")+" "+G+" "+this.getMappedStyle("default"))):(G+=" "+this.getMappedStyle("disabled"),D$.className=this.getMappedStyle("sortascending")+" "+G);V.appendChild(D$);K=V;O.appendChild(K);
O.setAttribute(T,"true")}m=c<this.vj?m-A:m+A;k+=A;c<this.vj?(e.insertBefore(O,q),q=O):e.appendChild(O)}c<this.vj?(this.vj-=p,this.gD-=k):(this.vs+=p,this.cp+=k);f.hasChildNodes()||f.appendChild(e);if(0<p&&(f=k/p,0==this.Jna||f!=this.Jna))this.Jna=f,(0,D.Oa)(e,g*f);!(0,D.Ua)(this,"column")&&((0,D.Ha)(this)&&this.vs>=g)&&(this.hD=D.o)}else if("row"===e)a:{var aa,na;(0,D.Ka)(this);m=b.getCount();if(f.hasChildNodes()){if(0==m&&(0,D.Ua)(this,"row")){this.iD=D.o;break a}e=f.firstChild;q=e.firstChild}else e=
window.document.createElement("div"),e.className=this.Xf.da()?this.getMappedStyle("scroller-mobile"):this.getMappedStyle("scroller"),0==m?((0,D.Oa)(f,0),(0,D.fb)(e,0),this.iD=D.o):(0,D.Oa)(f,50),q=window.document.createElement("div"),q.style.display="none",(0,D.Oa)(q,1),(0,D.fb)(q,0),e.appendChild(q);t=(0,D.ob)(this.gc,"row");(v=c>=this.uj?D.o:D.u)?w=this.Qk:d?(p=f.firstChild,h=p.childNodes[c-this.Ql+1],w=(0,window.parseInt)(h.style.top)):w=this.Gu;-1==g&&(g=this.uj+m);K=this.fb().getMappedAttribute("resizable");
k=0;O=window.document.createDocumentFragment();for(T=0;T<m;T+=1)D$=v?c+T:c+(m-1-T),Q=window.document.createElement("div"),Q.id=(0,D.Qa)(this,"r"+D$),A=window.document.createElement("div"),Q.appendChild(A),G=b.getData(D$),M=b.getMetadata(D$),M=(0,D.pb)(this,"row",D$,G,M,A),V=this.gc.ks("row",M),na=this.gc.xz("row",M),V!=D.r&&(Q.style.cssText=V),this.LV==D.r&&""!=Q.style.width&&(this.LV=(0,D.cb)(Q),(0,D.Oa)(f,this.LV)),Q.className=this.getMappedStyle("row"),V=(0,D.Na)(this,Q,c+T,M.key),(0,D.fb)(Q,V),
v||d?(Q.style.top=w+"px",w+=V):(w-=V,Q.style.top=w+"px"),aa=this.getMappedStyle("headercell")+" "+this.getMappedStyle("rowheadercell"),A.className=na!=D.r?aa+" "+na:aa,D$===g-1&&(A.style.borderBottomStyle="none"),(0,D.qb)(this,"row",M)&&A.setAttribute(K,"true"),t!=D.r?(D$=t.call(this,M),D$!=D.r&&(D$.parentNode===D.r?A.appendChild(D$):D$.parentNode==D.r&&D$.toString&&A.appendChild(window.document.createTextNode(D$.toString())))):A.appendChild(window.document.createTextNode(G.toString())),v?O.appendChild(Q):
O.insertBefore(Q,O.firstChild),k+=V;if(v)e.appendChild(O),0!=this.uj&&0!=m&&(b=e.childNodes[this.uj],b!=D.r&&(b.firstChild.style.borderBottomStyle="")),this.uj+=m,this.Qk+=k;else if(d){p.insertBefore(O,h);c<=this.Lc&&(this.Ql=c,this.Gu=window.Math.max(0,this.Gu-k),(0,D.fb)(q,window.Math.max(0,(0,D.bb)(q)-k)));this.uj=this.Td+m;this.Qk=window.Math.max(0,this.Qk+k);b=h;for(c=k;b;)b.style.top=(0,window.parseInt)(b.style.top)+c+"px",b=b.nextSibling}else(0,D.fb)(q,window.Math.max(0,(0,D.bb)(q)-k)),e.insertBefore(O,
q.nextSibling),this.Ql-=m,this.Gu=window.Math.max(0,this.Gu-k);d||f.appendChild(e);!(0,D.Ua)(this,"row")&&((0,D.Ha)(this)&&this.uj>=g)&&(this.iD=D.o)}(0,D.Ta)(this)?((0,D.sb)(this),!this.Mq&&!d&&((0,D.$a)(this),(0,D.Fa)(this))):(0,D.Sa)(this)&&(this.Mq||(0,D.ab)(this));this.Mq&&(0,D.tb)(this)}};D.wa.prototype.t7=function(b,c){this.Rk[c.axis]=D.u};
D.pb=function(b,c,d,e,f,g){var h={};h.axis=c;h.index=d;h.data=e;h.datagrid=b;h.parentElement=g;d=f.key;d!=D.r&&("row"===c?g.parentNode.setAttribute(b.fb().getMappedAttribute("key"),d):g.setAttribute(b.fb().getMappedAttribute("key"),d));for(var k in f)f.hasOwnProperty(k)&&(h[k]=f[k]);b.BV!=D.r&&b.BV.call(b,h);return h};
D.wa.prototype.fetchCells=function(b,c,d,e,f,g,h){var k;this.Rk.cells||(this.Rk.cells={row:d,column:e},f==D.r&&(f=(0,D.La)(this,"row"),(0,D.Ua)(this,"row")||(d<this.Lc?f=window.Math.min(f,this.Lc):(k=this.Pc.getCount("row"),0<=k&&(f=window.Math.min(f,window.Math.max(0,k-this.Td)))))),g==D.r&&(g=(0,D.La)(this,"column"),(0,D.Ua)(this,"column")||(e<this.Md?g=window.Math.min(g,this.Md):(k=this.Pc.getCount("column"),0<=k&&(g=window.Math.min(g,window.Math.max(0,k-this.Wf)))))),d={axis:"row",start:d,count:f},
b={axis:"column",start:e,count:g,databody:b,scroller:c},h=h!=D.r&&h.success!=D.r?h.success:this.r7,(0,D.nb)(this),this.Pc.fetchCells([d,b],{success:h,error:this.t7},{success:this,error:this}))};D.wa.prototype.G7=(0,D.ca)(D.u);
D.wa.prototype.r7=function(b,c,d){var e,f,g,h,k,m,p,q,t,v,w,A,D$,K,G;e=this.Pc.getCount("row");f=this.Pc.getCount("column");if(d===D.n){d=D.u;h=c[0].start;k=c[1].start;q=this.Rk.cells;g=q.row;q=q.column;if(!(g==h&&q==k))return;if(h=this.Fm==this.Jf&&this.Fu==this.Lh){var M;(0,window.isNaN)(this.Em)||(0,window.isNaN)(this.ap)?h=D.o:(g=c[0].start,h=b.getCount("row"),q=g+h,p=c[1].start,k=b.getCount("column"),g*=this.Em,q*=this.Em,t=this.ap*p,p=this.ap*(p+k),A=this.Ng,D$=this.Ng+(0,D.bb)(this.nb),m=this.Pk,
M=this.Pk+(0,D.cb)(this.nb),!(0,D.Ua)(this,"row")&&(this.Pc.getCount("row")==h&&q<D$)&&(q=D$),!(0,D.Ua)(this,"column")&&(this.Pc.getCount("column")==k&&p<M)&&(p=M),h=A>=g&&D$<=q&&m>=t&&M<=p);h=!h}if(h){this.Rk.cells=D.u;this.mN||(0,D.ub)(this,this.Pk,this.Ng);return}}(0,D.Ka)(this);g=c[0];h=g.start;k=b.getCount("row");m=0<k&&(h>=this.Td||h+k<=this.Lc);if(0==k&&(0,D.Ua)(this,"row")&&0<g.count||m&&(0,D.Ha)(this)&&!(0,D.Ua)(this,"row")&&this.Td+k>=e||k<g.count)this.HH=D.o;p=c[1];g=p.start;q=b.getCount("column");
t=0<q&&(g==this.Wf||g+q==this.Md);if(0==q&&(0,D.Ua)(this,"column")&&0<p.count||t&&(0,D.Ha)(this)&&!(0,D.Ua)(this,"column")&&this.Wf+q>=f||q<p.count)this.sN=D.o;c=this.nb;c==D.r&&(c=p.databody);A=this.kd;A==D.r&&(A=p.scroller);A.hasChildNodes()?p=A.firstChild:(p=window.document.createElement("div"),A.appendChild(p));c.hasChildNodes()?(A=c.firstChild,D$=A.firstChild):(A=window.document.createElement("div"),A.className=this.Xf.da()?this.getMappedStyle("scroller-mobile"):this.getMappedStyle("scroller"),
D$=window.document.createElement("div"),D$.style.display="none",(0,D.Oa)(D$,1),(0,D.fb)(D$,0),A.appendChild(D$));if(m||d)if((K=!d&&h>=this.Lc?D.o:D.u)?v=this.Jf:d?(w=A.childNodes[h-this.Lc+1],v=(0,window.parseInt)(w.style.top)):v=this.Fm,m=window.document.createDocumentFragment(),v=(0,D.vb)(this,m,K||d,v,h,k,g,t,b),b=v.totalRowHeight,G=v.avgWidth,v=b/k,K){A.appendChild(m);if(0!=this.Td&&0!=k&&(w=A.childNodes[this.Td],w!=D.r)){w=w.childNodes;for(K=0;K<w.length;K+=1)w[K].style.borderBottomStyle=""}this.Td+=
k;this.Jf+=b;c.hasChildNodes()||(c.appendChild(A),this.G7()&&(b=window.document.createElement("div"),window.bottomHotspot=window.document.createElement("div"),c.appendChild(b),c.appendChild(window.bottomHotspot)))}else d?(A.insertBefore(m,w),h<this.Lc&&(this.Lc=h,this.Fm=window.Math.max(0,this.Fm-b),(0,D.fb)(D$,window.Math.max(0,(0,D.bb)(D$)-b))),this.Td+=k,this.Jf+=b,(0,D.wb)(w,b)):(A.insertBefore(m,D$.nextSibling),this.Lc-=k,this.Fm=window.Math.max(0,this.Fm-b),(0,D.fb)(D$,window.Math.max(0,(0,D.bb)(D$)-
b)));else if(t&&(w=A.childNodes,k==w.length-1)){var O;G=(0,D.ob)(this.gc,"cell");D$=(0,D.Aa)(this.gc);m=(0,D.Da)(this.gc);M=(0,D.Ea)(this.gc);for(O=0;O<k;O+=1)K=w[O+1],K=(0,D.xb)(this,b,K,h+O,G,D.u,g,O==k-1,D$,m,M);G=K}b=-1!=f&&!(0,D.Ha)(this)?f*G:this.Lh;if(G!=D.n&&(0==this.ap||this.ap==D.n))this.ap=G,(0,D.Oa)(A,b),(0,D.Oa)(p,b);else if((-1==f||(0,D.Ha)(this))&&b>(0,D.cb)(A))(0,D.Oa)(A,b),(0,D.Oa)(p,b);b=-1!=e&&!(0,D.Ha)(this)?e*v:this.Jf;if(v!=D.n&&(0==this.Em||this.Em==D.n))this.Em=v,(0,D.fb)(A,
b),(0,D.fb)(p,b);else if((-1==e||(0,D.Ha)(this))&&b>(0,D.bb)(A)||e*v!=(0,D.bb)(A))(0,D.fb)(A,b),(0,D.fb)(p,b);t&&(g<this.Md?this.Md-=q:this.Wf+=q);this.Rk.cells=D.u;this.Mq&&(0,D.tb)(this);(0,D.Ta)(this)&&((0,D.sb)(this),this.Mq?(this.kd==D.r?d=D.u:(d=(0,D.bb)(this.kd),e=(0,D.cb)(this.kd),v=this.kd.firstChild,f=(0,D.bb)(v),v=(0,D.cb)(v),d=this.Jf>d&&e==v||this.Lh>e&&d==f?D.o:D.u),d&&(0,D.$a)(this)):((0,D.$a)(this),d||(0,D.Fa)(this)),this.Vw!=D.r&&((0,D.yb)(this,this.Vw),this.Ed!=D.r?"row"===this.Ed.axis?
(0,D.zb)(this,this.Vw.row):"column"===this.Ed.axis&&(0,D.Ab)(this,this.Vw.column):this.Vw==this.Se?(0,D.Bb)(this):(0,D.Db)(this,this.Vw),this.Vw=D.r),(0,D.Fb)(this)&&(this.nb==D.r&&(this.nb=c),(0,D.Gb)(this,h,h+k)),d=this.fb().getTranslatedText("accessibleSummaryExact",{rownum:this.Td,colnum:this.Wf}),this.Pc.getExpandedKeys&&(e=this.fb().getTranslatedText("accessibleSummaryExpanded",{num:this.Pc.getExpandedKeys().length}),d=d+". "+e),this.DFa.innerHTML=d)};
D.vb=function(b,c,d,e,f,g,h,k,m){var p,q,t,v,w,A,D$,K,G;p=(0,D.ob)(b.gc,"cell");q=(0,D.Aa)(b.gc);t=(0,D.Hb)(b.gc);v=(0,D.Da)(b.gc);w=(0,D.Ea)(b.gc);for(window.i=K=0;window.i<g;window.i+=1)G=d?f+window.i:f+(g-1-window.i),A=window.document.createElement("div"),A.className=1===window.Math.floor(G/t)%2?b.getMappedStyle("row")+" "+b.getMappedStyle("banded"):b.getMappedStyle("row"),D$=(0,D.xb)(b,m,A,G,p,D.o,h,window.i==g-1&&k,q,v,w),G=(0,D.Na)(b,A,G,b.Vh(A)),(0,D.fb)(A,G),K+=G,d?(A.style.top=e+"px",e+=
G,c.appendChild(A)):(e-=G,A.style.top=e+"px",c.insertBefore(A,c.firstChild));return{avgWidth:D$,totalRowHeight:K,top:e}};D.wb=function(b,c){for(;b;)b.style.top=(0,window.parseInt)(b.style.top)+c+"px",b=b.nextSibling};D.wa.prototype.Uma=(0,D.z)();
D.xb=function(b,c,d,e,f,g,h,k,m,p,q){var t,v,w,A,D$,K,G,M,O,T,Q,V,aa,na,sa;t=h>=b.Md;v=d.firstChild;D$=g||!t?b.Fu:b.Lh;sa=b.fb().getMappedAttribute("key");K=b.fb().isRTLMode()?"right":"left";G=0;M=c.getCount("column");for(V=0;V<M;V+=1){na=t||g?h+V:h+(M-1-V);w={row:e,column:na};O=c.getData(w);T=c.getMetadata(w);aa=window.document.createElement("div");aa.setAttribute("tabIndex",-1);Q=b;A=O;var ra=D.n,ra={};ra.parentElement=aa;ra.indexes=w;ra.data=A;ra.component=Q;ra.datasource=Q.Pc;w=D.n;for(w in T)T.hasOwnProperty(w)&&
(ra[w]=T[w]);Q.BV!=D.r&&Q.BV.call(Q,ra);Q=ra;d.hasAttribute(sa)||d.setAttribute(sa,Q.keys.row);w=b.gc.ks("cell",Q);w!=D.r&&(aa.style.cssText=w);if("hidden"===q||(0,D.Wa)(b,na))"left"===K?aa.style.borderRight="none":aa.style.borderLeftStyle="none";if("hidden"===p||(0,D.Va)(b,e))aa.style.borderBottomStyle="none";A=1===window.Math.floor(na/m)%2?b.getMappedStyle("cell")+" "+b.getMappedStyle("banded"):b.getMappedStyle("cell");w=b.gc.xz("cell",Q);aa.className=w!=D.r?A+" "+w:A;aa.style.height="100%";na=
(0,D.Pa)(b,aa,na,Q.keys.column);(0,D.Oa)(aa,na);t||g?(0,D.eb)(aa,D$,K):(0,D.eb)(aa,D$-na,K);b.Kf.appendChild(aa);f!=D.r?(O=f.call(b,Q),O!=D.r&&(O.parentNode===D.r?aa.appendChild(O):O.parentNode==D.r&&O.toString&&aa.appendChild(window.document.createTextNode(O.toString())))):(O==D.r&&(O=""),aa.appendChild(window.document.createTextNode(O.toString())));t||g?(d.appendChild(aa),D$+=na):(d.insertBefore(aa,v),v=aa,D$-=na);k&&(t||g?b.Lh+=na:b.Fu-=na,G+=na)}return k&&0<M?G/M:D.r};
D.wa.prototype.Uma=function(){this.Rk.cells=D.u};D.nb=function(b){var c;c=b.fb().getTranslatedText("msgFetchingData");"block"!=b.GH.style.display&&(b.GH.innerHTML=c,b.GH.style.display="block",c=b.getWidth()/2-b.GH.offsetWidth/2,b.GH.style.left=c+"px")};D.sb=function(b){b.GH.style.display="none"};D.wa.prototype.fna=function(b){var c;b||(b=window.event);c=b.target?b.target:b.srcElement;b=(0,D.Ib)(this.Xf,c);this.scrollTo(b,c.scrollTop)};
D.Jb=function(b,c,d){var e,f,g,h;0!=c&&0!=d&&(c>d?d=0:c=0);e=b.Pk-c;f=b.Ng-d;(0,D.kb)(b.Xf,b.kd,window.Math.max(0,window.Math.min((0,D.mb)(b,"column")?window.Number.MAX_VALUE:b.FFa,e)));b.kd.scrollTop=window.Math.max(0,window.Math.min((0,D.mb)(b,"row")?window.Number.MAX_VALUE:b.EFa,f));b.Xf.da()&&(h=b.kd.scrollTop,g=(0,D.Ib)(b.Xf,b.kd),0!=d&&f!=b.kd.scrollTop?(c=f-h,b.R7=0<c?window.Math.min(50,c):window.Math.max(-50,c)):0!=c&&e!=g&&(c=e-g,b.EV=0<c?window.Math.min(50,c):window.Math.max(-50,c)))};
D.wa.prototype.scrollTo=function(b,c){this.Pk=b;this.Ng=c;b+(0,D.Ia)(this)<this.Fu||b>this.Lh||c+(0,D.Ja)(this)<this.Fm||c>this.Jf?(0,D.ub)(this,b,c):(0,D.Kb)(this,b,c);var d;d=b+(0,D.cb)(this.nb);if(this.Jf<c+(0,D.bb)(this.nb)||this.Fm>c||this.Lh<d-2||this.Fu>b)this.tN=D.o;else{this.tN=D.u;(0,D.tb)(this);var e,f,g;d=this.kd.firstChild;e=(0,D.bb)(d);f=(0,D.cb)(d);g=this.nb.firstChild;if(this.Jf>e||this.Pc.getCount("row")==this.Td&&!(0,D.Ua)(this,"row")&&this.Jf<e)(0,D.fb)(d,this.Jf),(0,D.fb)(g,this.Jf);
if(this.Lh>f||this.Pc.getCount("column")==this.Wf&&!(0,D.Ua)(this,"column")&&this.Lh<f)(0,D.Oa)(d,this.Lh),(0,D.Oa)(g,this.Lh);this.aD!=D.r&&(this.aD.focus(),this.aD=D.r)}};
D.wa.prototype.Gua=function(){var b,c,d,e,f;b=this.Pk;c=this.Ng;d=this.nb.firstChild;e=this.Ld.firstChild;f=this.tc.firstChild;d.removeEventListener("webkitTransitionEnd",this.P7);this.fb().isRTLMode()?(d.style.webkitTransform="translate3d("+b+"px, "+-c+"px, 0)",e.style.webkitTransform="translate3d("+b+"px, 0, 0)"):(d.style.webkitTransform="translate3d("+-b+"px, "+-c+"px, 0)",e.style.webkitTransform="translate3d("+-b+"px, 0, 0)");f.style.webkitTransform="translate3d(0, "+-c+"px, 0)";this.R7=this.EV=
D.r};
D.tb=function(b){var c,d,e,f,g;c=b.Pk;d=b.Ng;e=b.nb.firstChild;f=b.Ld.firstChild;g=b.tc.firstChild;if(b.Xf.da()&&window.hasOwnProperty("WebKitCSSMatrix")&&(new window.WebKitCSSMatrix).hasOwnProperty("m11")){if(b.EV!=D.r||b.R7!=D.r)b.EV!=D.r?c+=b.EV:d+=b.R7,b.P7==D.r&&(b.P7=b.Gua.bind(b)),e.addEventListener("webkitTransitionEnd",b.P7);b.fb().isRTLMode()?(e.style.webkitTransform="translate3d("+c+"px, "+-d+"px, 0)",f.style.webkitTransform="translate3d("+c+"px, 0, 0)"):(e.style.webkitTransform="translate3d("+-c+
"px, "+-d+"px, 0)",f.style.webkitTransform="translate3d("+-c+"px, 0, 0)");g.style.webkitTransform="translate3d(0, "+-d+"px, 0)"}else b=b.fb().isRTLMode()?"right":"left",(0,D.eb)(e,-c,b),(0,D.eb)(e,-d,"top"),(0,D.eb)(f,-c,b),(0,D.eb)(g,-d,"top")};
D.ub=function(b,c,d){var e,f;d=window.Math.round(window.Math.max(0,d-b.getHeight()/2)/b.Em);c=window.Math.round(window.Math.max(0,c-b.getWidth()/2)/b.ap);e=d*b.Em;f=c*b.ap;b.Lc=d;b.Td=d;b.Ql=d;b.uj=d;b.Fm=e;b.Jf=e;b.Gu=e;b.Qk=e;b.Md=c;b.Wf=c;b.vj=c;b.vs=c;b.Fu=f;b.Lh=f;b.gD=f;b.cp=f;b.fetchHeaders("row",d,b.tc,D.n,{success:function(b,c){(0,D.Lb)(this,b,c,e)}});b.fetchHeaders("column",c,b.Ld,D.n,{success:function(b,c){this.Ld.firstChild.innerHTML="";this.bN(b,c)}});b.fetchCells(b.nb,b.kd,d,c,D.r,D.r,
{success:function(b,c){(0,D.Mb)(this,b,c,e)}})};D.Lb=function(b,c,d,e){var f=b.tc.firstChild;window.headerResizer=f.firstChild.cloneNode();f.innerHTML="";f.appendChild(window.headerResizer);(0,D.fb)(window.headerResizer,e);b.bN(c,d)};
D.Mb=function(b,c,d,e){window.databodyContent=b.nb.firstChild;window.databodyResizer=window.databodyContent.firstChild.cloneNode();window.databodyContent.innerHTML="";window.databodyContent.appendChild(window.databodyResizer);(0,D.fb)(window.databodyResizer,e);b.r7(c,d)};
D.Kb=function(b,c,d){var e,f,g;e=c+(0,D.cb)(b.nb);if(!b.hD&&(e>b.cp||e==b.cp&&(0,D.mb)(b,"column"))){if(b.fetchHeaders("column",b.vs,b.Ld),!(0,D.Ha)(b)&&b.vs-b.vj>b.SO){var h,k,m,p,q;g=b.Ld.firstChild;h=g.childNodes;for(m=k=f=0;m<h.length;m+=1)if(p=h[m],q=k,k=(0,D.Nb)(p,"left"),k>b.Pk-0){f=m-1;b.vj+=f;b.gD=q;break}for(h=0;h<f;h+=1)g.removeChild(g.firstChild),b.AH.splice(0,1);b.Uw+=f}}else if(c<b.gD&&(f=window.Math.max(0,b.vj-(0,D.La)(b,"column")),g=window.Math.max(0,b.vj-f),b.fetchHeaders("column",
f,b.Ld,g),!(0,D.Ha)(b)&&b.vs-b.vj>b.SO&&(g=b.Ld.firstChild,f=b.Pk+(0,D.Ia)(b)+0,!(b.cp<=f)))){h=g.lastChild;for(k=h.offsetWidth;b.cp+k>f;)g.removeChild(h),b.cp-=k,b.vs-=1,h=g.lastChild,k=h.offsetWidth}if(e>b.Lh||e==b.Lh&&(0,D.mb)(b,"column")&&!b.sN){if(b.fetchCells(b.nb,b.kd,b.Lc,b.Wf,b.Td-b.Lc),!(0,D.Ha)(b)&&b.Wf-b.Md>b.SO&&(c=b.nb.firstChild.childNodes,g=e=0,!(2>c.length))){f=c[1].childNodes;for(h=0;h<f.length;h+=1)if(k=f[h],m=g,g=(0,D.Nb)(k,"left"),g>b.Pk-0){e=h-1;b.Md+=e;b.Fu=m;break}for(g=1;g<
c.length;g+=1){f=c[g];for(h=0;h<e;h+=1)f.removeChild(f.firstChild)}}}else if(c<b.Fu&&(f=window.Math.max(0,b.Md-(0,D.La)(b,"column")),g=window.Math.max(0,b.Md-f),b.fetchCells(b.nb,b.kd,b.Lc,f,b.Td-b.Lc,g),!(0,D.Ha)(b)&&b.Wf-b.Md>b.SO&&(g=b.nb.firstChild.childNodes,c=b.Pk+(0,D.Ia)(b)+0,!(b.Lh<=c)))){e=g[1];f=e.lastChild;for(f=f.offsetWidth;b.Lh+f>c;){for(h=1;h<g.length;h+=1)k=g[h],k.removeChild(k.lastChild);b.Lh-=f;b.Wf-=1;f=e.lastChild;f=f.offsetWidth}}c=d+(0,D.bb)(b.nb);if(!b.iD&&(c>b.Qk||c==b.Qk&&
(0,D.mb)(b,"row"))){if(b.fetchHeaders("row",b.uj,b.tc),!(0,D.Ha)(b)&&b.uj-b.Ql>b.VD&&(e=b.tc.firstChild,g=e.firstChild,f=(0,D.bb)(g),!(f>=b.Ng-0))){h=g.nextSibling;for(k=h.offsetHeight;f+k<b.Ng-0;)e.removeChild(h),b.BH.splice(0,1),b.$C-=1,b.Gu+=k,b.Ql+=1,f+=k,h=g.nextSibling,k=h.offsetHeight;(0,D.fb)(g,f)}}else if(window.Math.max(0,d-0)<b.Gu){if(0==b.Ql)return;e=window.Math.max(0,b.Ql-(0,D.La)(b,"row"));g=window.Math.max(0,b.Ql-e);b.fetchHeaders("row",e,b.tc,g);if(!(0,D.Ha)(b)&&b.uj-b.Ql>b.VD&&(e=
b.tc.firstChild,g=b.Ng+(0,D.Ja)(b)+0,!(b.Qk<=g))){f=e.lastChild;for(h=f.offsetHeight;b.Qk+h>g;)e.removeChild(f),b.Qk-=h,b.uj-=1,f=e.lastChild,h=f.offsetHeight}}c>b.Jf||c==b.Jf&&(0,D.mb)(b,"row")&&!b.HH?(b.fetchCells(b.nb,b.kd,b.Td,b.Md,D.r,b.Wf-b.Md),!(0,D.Ha)(b)&&b.Td-b.Lc>b.VD&&(0,D.Ob)(b,b.nb)):window.Math.max(0,d-0)<b.Fm&&0!=b.Lc&&(c=window.Math.max(0,b.Lc-(0,D.La)(b,"row")),d=window.Math.max(0,b.Lc-c),b.fetchCells(b.nb,b.kd,c,b.Md,d,b.Wf-b.Md),!(0,D.Ha)(b)&&b.Td-b.Lc>b.VD&&(0,D.Pb)(b,b.nb))};
D.Ob=function(b,c){var d,e,f,g,h;d=c.firstChild;e=d.firstChild;f=(0,D.bb)(e);if(!(f>=b.Ng-0)){g=e.nextSibling;for(h=g.offsetHeight;f+h<b.Ng-0;){d.removeChild(g);b.Fm+=h;b.Lc+=1;f+=h;g=e.nextSibling;if(g==D.r)break;h=g.offsetHeight}(0,D.fb)(e,f)}};D.Pb=function(b,c){var d,e,f,g;d=c.firstChild;e=b.Ng+(0,D.Ja)(b)+0;if(!(b.Jf>e)){f=d.lastChild;for(g=f.offsetHeight;b.Jf+g>e;)d.removeChild(f),b.Jf-=g,b.Td-=1,f=d.lastChild,g=f.offsetHeight}};D.wa.prototype.DEa=function(){this.mN=D.o};
D.wa.prototype.EEa=function(){this.mN=D.u;(0,D.Ta)(this)&&this.tN&&(0,D.Kb)(this,this.Pk,this.Ng)};
D.wa.prototype.qEa=function(b,c,d){var e,f;e=b.target;f=(0,D.Qb)(this,e);c===this.ws.getMappedCommand("resizeHeight")?(0,D.Rb)(this)&&(e=f!=D.r?(0,D.Sb)(this,f,"row").firstChild:(0,D.Tb)(this,e),(0,D.Ub)(this,e,"resizeHeight",d)):c===this.ws.getMappedCommand("resizeWidth")?(0,D.Rb)(this)&&(e=f!=D.r?(0,D.Sb)(this,f,"column"):(0,D.Tb)(this,e),(0,D.Ub)(this,e,"resizeWidth",d)):c===this.ws.getMappedCommand("sortColAsc")||c===this.ws.getMappedCommand("sortColDsc")?(c=c===this.ws.getMappedCommand("sortColAsc")?
"ascending":"descending",f!=D.r?(e=(0,D.Sb)(this,f,"column"),(0,D.Vb)(this,e)&&e!=D.r&&(0,D.Wb)(this,b,e,c)):(0,D.Vb)(this,e)&&(0,D.Xb)(this,b,c)):c===this.ws.getMappedCommand("sortRowAsc")||c===this.ws.getMappedCommand("sortRowDsc")?(c=c===this.ws.getMappedCommand("sortRowAsc")?"ascending":"descending",f!=D.r?(e=(0,D.Sb)(this,f,"row"),(0,D.Vb)(this,e)&&e!=D.r&&(0,D.Wb)(this,b,e,c)):(0,D.Vb)(this,e)&&(0,D.Xb)(this,b,c)):c===this.ws.getMappedCommand("cut")?(0,D.Yb)(this,b):c===this.ws.getMappedCommand("paste")&&
(0,D.Zb)(this,b)};D.wa.prototype.handleContextMenuReturn=D.wa.prototype.qEa;D.Vb=function(b,c){var d=(0,D.Tb)(b,c);return d==D.r?D.u:"true"==d.getAttribute(b.fb().getMappedAttribute("sortable"))};D.Fb=function(b){return"none"!=(0,D.$b)(b.gc)};D.ac=function(b){return"multiple"==(0,D.$b)(b.gc)};D.Rb=function(b){var c=(0,D.bc)(b.gc,"row");b=(0,D.bc)(b.gc,"column");return"disable"!==c.width||"disable"!==c.height||"disable"!==b.width||"disable"!==b.height};
D.qb=function(b,c,d){var e=(0,D.bc)(b.gc,c,d);return"column"==c?"function"==typeof e.width?"enable"==e.width.call(b,d)?D.o:D.u:"enable"==e.width?D.o:D.u:"row"==c?"function"==typeof e.height?"enable"==e.height.call(b,d)?D.o:D.u:"enable"==e.height?D.o:D.u:D.u};D.E=D.wa.prototype;D.E.zEa=function(b){(0,D.Rb)(this)&&this.DV==D.u&&(0,D.cc)(this,b)};D.E.CEa=function(b){this.Cu&&(0,D.dc)(this,b)};
D.E.Yma=function(b){var c;if(((0,D.ya)(b.target,this.getMappedStyle("sortascending"))||(0,D.ya)(b.target,this.getMappedStyle("sortdescending")))&&(0,D.Vb)(this,b.target))b.preventDefault(),(0,D.Ba)(b.target,this.getMappedStyle("selected"));else{(0,D.Rb)(this)&&(0,D.ec)(this,b);c=(0,D.gc)(this,b.target);!this.eD&&(0,D.hc)(this,c)&&(this.Cu=D.o,this.bp=b.pageX,this.Pl=b.pageY);if(!this.eD){var d,e;c=(0,D.Tb)(this,b.target);c!=D.r&&(d=(0,D.ic)(this,c),e=(0,D.jc)(this,c));d!=D.r&&d!=D.n&&("row"===e?(0,D.zb)(this,
d):"column"===e&&(0,D.Ab)(this,d))}this.QLa===D.o&&b.preventDefault()}};D.E.AEa=function(b){this.Cu&&this.ue!=D.r?(0,D.kc)(this,D.u):(0,D.Rb)(this)&&(0,D.lc)(this,b);this.Cu=D.u};
D.E.$ma=function(b){(0,D.Ba)((0,D.Tb)(this,b.target),this.getMappedStyle("hover"));if((0,D.Vb)(this,b.target)){var c=(0,D.Tb)(this,b.target);c&&(0,D.mc)(this,c,D.u);((0,D.ya)(b.target,this.getMappedStyle("sortascending"))||(0,D.ya)(b.target,this.getMappedStyle("sortdescending")))&&(0,D.Ba)(b.target,this.getMappedStyle("hover"))}(0,D.nc)(this,(0,D.gc)(this,b.target),D.o)};
D.E.Zma=function(b){(0,D.za)((0,D.Tb)(this,b.target),this.getMappedStyle("hover"));if((0,D.Vb)(this,b.target)){var c=(0,D.Tb)(this,b.target);(c==D.r||b.relatedTarget==D.r||c!==(0,D.Tb)(this,b.relatedTarget))&&(0,D.mc)(this,c,D.o);if((0,D.ya)(b.target,this.getMappedStyle("sortascending"))||(0,D.ya)(b.target,this.getMappedStyle("sortdescending")))(0,D.za)(b.target,this.getMappedStyle("hover")),(0,D.za)(b.target,this.getMappedStyle("selected"))}(0,D.nc)(this,(0,D.gc)(this,b.target),D.o)};
D.E.yEa=function(b){this.Cu&&this.ue!=D.r&&(0,D.kc)(this,D.o);(0,D.nc)(this,(0,D.gc)(this,b.target),D.o)};D.E.Xma=function(b){if(((0,D.ya)(b.target,this.getMappedStyle("sortascending"))||(0,D.ya)(b.target,this.getMappedStyle("sortdescending")))&&(0,D.Vb)(this,b.target))(0,D.Xb)(this,b),b.preventDefault()};
D.E.sEa=function(b){(0,D.hc)(this,this.find(b.target,"row"))&&(this.Cu=D.o,this.bp=b.pageX,this.Pl=b.pageY);if((0,D.Fb)(this))(0,D.oc)(this,b),(0,D.ac)(this)&&(this.DV=D.o);else{var c,d;c=(0,D.Qb)(this,b.target);c!=D.r&&(d=this.createIndex(this.Hf(c.parentNode),this.An(c)));d!=D.r&&d!=D.n&&((0,D.pc)(this,-1),this.Ed=D.r,(0,D.yb)(this,d),this.pC(d),(0,D.qc)(this,b))}};
D.E.uEa=function(b){var c,d;this.Cu||(d=this.gc.rj(),c=(0,D.gc)(this,b.target),"cell"===d?(0,D.za)((0,D.Qb)(this,b.target),this.getMappedStyle("hover")):"row"===d&&(0,D.za)(c,this.getMappedStyle("hover")),(0,D.nc)(this,c))};D.E.vEa=function(b){var c,d;this.Cu||(d=this.gc.rj(),c=(0,D.gc)(this,b.target),"cell"===d?(0,D.Ba)((0,D.Qb)(this,b.target),this.getMappedStyle("hover")):"row"===d&&(0,D.Ba)(c,this.getMappedStyle("hover")),(0,D.nc)(this,c))};
D.E.tEa=function(b){if(this.Cu)(0,D.dc)(this,b);else if(this.DV){var c,d;c=(0,D.Qb)(this,b.target);d=this.Qm().slice(0);c!=D.r&&(c={row:this.Hf(c.parentNode),column:this.An(c)},(0,D.rc)(this,c));(0,D.sc)(this.Qm(),d)||this.Dl(b)}};D.E.wEa=function(b){this.DV=D.u;this.Cu&&this.ue!=D.r&&(0,D.kc)(this,D.o);(0,D.nc)(this,(0,D.gc)(this,b.target))};
D.E.rEa=function(b){var c;if(this.Se==D.r&&this.Ed==D.r)9===b.keyCode&&(c=this.createIndex(0,0),(0,D.Fb)(this)?this.OH(c):this.pC(c),b.preventDefault());else if(!(9===b.keyCode&&(!(0,D.Fb)(this)||"actionable"!=this.T7))){if(this.Ed!=D.r){if(this.Ed.elem!=window.document.activeElement)return;var d,e;c=D.u;if(this.Ed!=D.r)if(d=b.keyCode,(0,D.tc)(d)){c=d;var f,g=D.u;if((0,D.Ta)(this)){this.fb().isRTLMode()&&(37==c?c=39:39==c&&(c=37));d=this.Ed.axis;e=this.Ed.index;f=this.Ed.elem;switch(c){case 37:"column"===
d&&0<e&&((0,D.pc)(this,e-1,f.previousSibling),(0,D.uc)(this),g=D.o);break;case 39:if("row"===d)(0,D.pc)(this,-1),this.Ed=D.r,c=this.createIndex(e,0),(0,D.Fb)(this)?this.OH(c):this.pC(c),g=D.o;else if(!(e+1>=this.vs&&this.hD)&&((0,D.Ua)(this,"column")||e<this.Pc.getCount("column")))(0,D.pc)(this,e+1,f.nextSibling),(0,D.uc)(this),g=D.o;break;case 38:"row"===d&&0<e&&((0,D.pc)(this,e-1,f.previousSibling),(0,D.uc)(this),g=D.o);break;case 40:if("column"===d)(0,D.pc)(this,-1),this.Ed=D.r,c=this.createIndex(0,
e),(0,D.Fb)(this)?this.OH(c):this.pC(c),g=D.o;else if(!(e+1>=this.uj&&this.iD)&&((0,D.Ua)(this,"row")||e+1<this.Pc.getCount("row")))(0,D.pc)(this,e+1,f.nextSibling),(0,D.uc)(this),g=D.o}c=g}else c=D.o}else 32==d?(0,D.Fb)(this)&&(0,D.ac)(this)&&(d=this.Ed.axis,e=this.Ed.index,"row"===d?((0,D.vc)(this,e,b),c=D.o):"column"===d&&"cell"==this.gc.rj()&&((0,D.wc)(this,e,b),c=D.o)):13==d?(d=this.Ed.elem,"true"==d.getAttribute(this.fb().getMappedAttribute("sortable"))&&(c=d.getAttribute(this.fb().getMappedAttribute("sortDir")),
(0,D.Wb)(this,b,d,c==D.r||"descending"===c?"ascending":"descending"),c=D.o)):c=(0,D.xc)(this,b);else c=D.n}else{c=(0,D.yc)(this,this.createRange(this.Se));if(c==D.r||c[0]!=(0,D.Qb)(this,window.document.activeElement))return;c=(0,D.xc)(this,b);if(!c)if((0,D.Fb)(this))if(c=D.u,d=b.keyCode,"actionable"==this.T7){27==d&&((0,D.zc)(this,D.u),(0,D.Bb)(this),c=D.o);if(e=(0,D.tc)(d))e=(0,D.Qb)(this,b.target),e=!(0<(0,D.Bc)(e).length);if(e)(0,D.zc)(this,D.u),e=(0,D.Cc)(this.Xf,b),f=b.shiftKey,(0,D.lb)(this),
e||(c=(0,D.Dc)(this,d,f&&(0,D.ac)(this))),c&&(this.Dl(b),(!f||!(0,D.ac)(this))&&(0,D.qc)(this,b));else if(9===d||13===d)if(f=b.shiftKey,d=9===d?f?37:39:f?38:40,(0,D.lb)(this),c=(0,D.Dc)(this,d,D.u))this.Dl(b),(0,D.qc)(this,b)}else if(113==d||13==d)(0,D.zc)(this,D.o),d=(0,D.Qb)(this,b.target),d=(0,D.Bc)(d),0<d.length&&d[0].focus();else if((0,D.tc)(d)||36==d||35==d||33==d||34==d)e=(0,D.Cc)(this.Xf,b),f=b.shiftKey,(0,D.lb)(this),e||(c=(0,D.Dc)(this,d,f&&(0,D.ac)(this))),c&&(this.Dl(b),(!f||!(0,D.ac)(this))&&
(0,D.qc)(this,b));else if(b.shiftKey&&119==d)this.CH=!this.CH;else{if(32==d&&(e=(0,D.Cc)(this.Xf,b),f=b.shiftKey,"cell"==this.gc.rj()&&(0,D.ac)(this)&&(f&&!e||e)))e?(c=this.Se.column,(0,D.wc)(this,c,b)):(c=this.Se.row,(0,D.vc)(this,c,b)),c=D.o}else c=b.target,d=c.tagName,"INPUT"===d||"TEXTAREA"===d||"SELECT"===d||"BUTTON"===d||"A"===d||c.getAttribute("tabIndex")!=D.r&&0<=(0,window.parseInt)(c.getAttribute("tabIndex"))&&(0,D.Qb)(this,c)!=c?c=D.n:(c=b.keyCode,((0,D.tc)(c)||36==c||35==c||33==c||34==
c)&&!(0,D.Cc)(this.Xf,b)?((0,D.qc)(this,b),c=(0,D.Dc)(this,c,D.u)):c=D.u);d=(0,D.Qb)(this,b.target);d!=D.r&&(d=d.parentNode,d=this.Vh(d),this.fireEvent("keydown",{event:b,ui:{rowKey:d}}))}c===D.o&&b.preventDefault()}};
D.Ec=function(b,c){var d,e;if(c){d=(0,D.Ec)(b,c.offsetParent);e=c.parentNode;var f,g;e?(e=window.document.defaultView.getComputedStyle(e,D.r),e=e.getPropertyValue("-webkit-transform")||e.getPropertyValue("-moz-transform")||e.getPropertyValue("-ms-transform")||e.getPropertyValue("-o-transform")||e.getPropertyValue("transform"),f=e.substr(7,e.length-8).split(", "),e=(0,window.isNaN)((0,window.parseInt)(f[4],10))?0:(0,window.parseInt)(f[4],10),g=(0,window.isNaN)((0,window.parseInt)(f[5],10))?0:(0,window.parseInt)(f[5],
10),f=(0,window.isNaN)((0,window.parseInt)(f[6],10))?0:(0,window.parseInt)(f[6],10),e=[e,g,f]):e=[0,0,0];return[(0,window.parseInt)(d[0],10)+(0,window.parseInt)(c.offsetLeft,10)+e[0],(0,window.parseInt)(d[1],10)+(0,window.parseInt)(c.offsetTop,10)+e[1]]}return[0,0]};D.E=D.wa.prototype;D.E.xEa=function(b){var c;b.preventDefault();c=0;b.wheelDeltaX?(c=b.wheelDeltaX,b=b.wheelDeltaY):b=b.wheelDelta;(0,D.Jb)(this,c,b)};
D.E.HEa=function(b){b.preventDefault();1==b.touches.length?(this.Hu=b.touches[0].pageX,this.Iu=b.touches[0].pageY,this.bp=this.Hu,this.Pl=this.Iu,this.FH=this.Hu,this.Fz=this.Iu,this.EH=0,this.jD=D.o):this.oH()};D.E.GEa=function(b){var c;b.preventDefault();this.jD?(this.bp=b.touches[0].pageX,this.Pl=b.touches[0].pageY,b=this.bp-this.FH,c=this.Pl-this.Fz,10>window.Math.abs(b)&&10>window.Math.abs(c)?((0,D.Jb)(this,1.5*b,1.5*c),this.EH++):this.EH=0,this.FH=this.bp,this.Fz=this.Pl):this.oH()};
D.E.FEa=function(b){var c;b.preventDefault();if(this.jD){if((0,D.Fb)(this)&&this.bp==this.Hu&&this.Pl==this.Iu){(0,D.oc)(this,b);return}if(1<this.EH){this.oH();return}b=window.Math.round(window.Math.sqrt(window.Math.pow(this.bp-this.Hu,2)+window.Math.pow(this.Pl-this.Iu,2)));0<b&&(c=window.Math.round(180*window.Math.atan2(this.Pl-this.Iu,this.Hu-this.bp)/window.Math.PI),0>c&&(c=360-window.Math.abs(c)),this.LC(b,45>=c&&0<=c?"left":360>=c&&315<=c?"left":135<=c&&225>=c?"right":45<c&&135>c?"down":"up"))}this.oH()};
D.E.oH=function(){this.jD=D.u;this.Pl=this.bp=this.Fz=this.FH=this.Iu=this.Hu=this.EH=0};D.E.LC=function(b,c){b*=3.5;"down"==c?(0,D.Jb)(this,0,b):"up"==c?(0,D.Jb)(this,0,-b):"left"==c?(0,D.Jb)(this,-b,0):"right"==c&&(0,D.Jb)(this,b,0)};
D.E.cna=function(b){b.preventDefault();this.GFa=(new window.Date).getTime();1==b.touches.length?(this.Hu=b.touches[0].pageX,this.Iu=b.touches[0].pageY,this.bp=this.Hu,this.Pl=this.Iu,this.FH=this.Hu,this.Fz=this.Iu,this.EH=0,this.jD=D.o,(0,D.Rb)(this)&&((0,D.cc)(this,b),(0,D.ec)(this,b))):this.gV()};D.E.bna=function(b){b.preventDefault();this.jD?(this.bp=b.touches[0].pageX,this.Pl=b.touches[0].pageY,this.FH=this.bp,this.Fz=this.Pl,(0,D.Rb)(this)&&(0,D.cc)(this,b)):this.oH()};
D.E.ana=function(b){var c;b.preventDefault();c=(new window.Date).getTime()-this.GFa;this.jD&&(this.eD&&(0,D.Rb)(this)?(0,D.lc)(this,b):500>c?(0,D.Vb)(this,b.target)&&(0,D.Xb)(this,b):1E3>c&&(c=(0,D.Tb)(this,b.target),b=(0,D.ic)(this,c),c=(0,D.jc)(this,c),"row"===c?(0,D.zb)(this,b):"column"===c&&(0,D.Ab)(this,b)));this.gV()};D.E.gV=function(){this.jD=D.u;this.Pl=this.bp=this.Fz=this.FH=this.Iu=this.Hu=this.EH=0};D.E.fireEvent=function(b,c){var d;b==D.r||c==D.r||(d=this.Oka[b],d!=D.r&&d(c))};
D.E.addListener=function(b,c){this.Oka[b]=c};D.fb=function(b,c){b.style.height=c+"px"};D.bb=function(b){return(0,window.parseInt)(b.style.height,10)};D.Oa=function(b,c){b.style.width=c+"px"};D.cb=function(b){return(0,window.parseInt)(b.style.width,10)};D.eb=function(b,c,d){b.style[d]=c+"px"};D.Nb=function(b,c){return(0,window.parseInt)(b.style[c],10)};
D.Fc=function(b,c){var d,e;d=c.row;e=c.column;return-1===d&&-1===e?-1:-1===d?e<b.Md?1:e>b.Wf?2:3:-1===e?d<b.Lc?1:d>b.Td?2:3:e>=b.Md&&e<=b.Wf&&d>=b.Lc&&d<=b.Td?3:-1};
D.wa.prototype.v7=function(b){var c,d;if(this.Mq)if(c=b.operation,d=b.keys,"insert"===c)b=b.result,b!=D.r?(d={axis:"row",start:b.getStart("row"),count:b.getCount("row")},c={axis:"column",start:b.getStart("column"),count:b.getCount("column")},this.Qfa(b,[d,c])):(b=this.Pc.indexes(d),3===(0,D.Fc)(this,b)?d.row&&(this.fetchHeaders("row",b.row,this.tc,1,{success:this.Wwa}),this.fetchCells(this.nb,this.kd,b.row,this.Md,1,this.Wf-this.Md,{success:this.Qfa})):(d=b.row*this.Em,this.kd.scrollTop=d));else if("update"===
c)d=this.Pc.indexes(d),3===(0,D.Fc)(this,d)&&(d={axis:"row",start:d.row,count:1},b={axis:"column",start:this.Md,count:this.Wf-this.Md},(0,D.nb)(this),this.Pc.fetchCells([d,b],{success:this.Twa,error:this.t7},{success:this,error:this}));else if("delete"===c){b=d;var e,f,g,h;window.Array.isArray(b)||(b=(0,window.Array)(b));for(c=d=0;c<b.length;c++)e=b[c],e.row&&(f=e.row,g=(0,D.Gc)(this,f),g!=D.r?(e=(0,D.bb)(g),h=g.nextSibling,(0,D.wb)(h,0-e),g.parentNode.removeChild(g),g.style.display="none"):e=this.Em,
f=(0,D.Hc)(this,f),f!=D.r&&(e=(0,D.bb)(f),h=f.nextSibling,(0,D.wb)(h,0-e),f.parentNode.removeChild(f),f.style.display="none",this.uj-=1,this.Qk-=e),this.Td-=1,this.Jf-=e,d+=e);b=this.nb.firstChild;c=this.kd.firstChild;d=(0,D.bb)(b)-d;(0,D.fb)(b,d);(0,D.fb)(c,d);(0,D.$a)(this);this.HH=D.u;(0,D.Kb)(this,this.Pk,this.Ng);(0,D.Ca)(this)}else"refresh"===c?(0,D.ub)(this,this.Pk,this.Ng):"sync"===c&&(d=b.pageSize,this.Rk={},this.cp=this.gD=this.Lh=this.Fu=this.vs=this.vj=this.Wf=this.Md=this.Qk=this.Gu=
this.Jf=this.Fm=this.uj=this.Ql=this.Td=this.Lc=0,this.BH=[],this.AH=[],this.Uw=this.$C=0,this.mN=this.tN=D.u,this.Pna=this.Qna=this.ap=this.Em=D.n,this.hD=this.sN=this.iD=this.HH=D.u,this.qN=this.Se=this.MV=D.r,this.Mq?(this.fetchHeaders("row",0,this.tc,d,{success:function(b,c){(0,D.Lb)(this,b,c,0)}}),this.fetchHeaders("column",0,this.Ld,D.n,{success:function(b,c){this.Ld.firstChild.innerHTML="";this.bN(b,c)}}),this.fetchCells(this.nb,this.kd,0,0,d,D.r,{success:function(b,c){(0,D.Mb)(this,b,c,0)}}),
(0,D.Fa)(this)):(this.fetchHeaders("column",0,this.Ld),this.fetchHeaders("row",0,this.tc,d),this.fetchCells(this.nb,this.kd,0,0,d)));else this.DH==D.n&&(this.DH=[]),this.DH.push(b)};D.wa.prototype.Qfa=function(b,c){this.Mq=D.u;this.r7(b,c,this.Td>c[0].start);(0,D.Ic)(this,c[0].start);(0,D.Ha)(this)||(0,D.Jc)(this);(0,D.Ca)(this)};D.wa.prototype.Wwa=function(b,c){this.Mq=D.u;this.bN(b,c,this.uj>c.start);(0,D.Ic)(this,c.start);(0,D.Ha)(this)||(0,D.Jc)(this)};
D.Ic=function(b,c){var d,e,f;d=b.nb.firstChild.childNodes[c-b.Lc+1];d!=D.r&&(e=b.Ng,f=b.Ng+(0,D.bb)(b.nb),d=d.offsetTop,e-=d,0<e?(0,D.Jb)(b,0,e):(e=f-d,0>e&&(0,D.Jb)(b,0,e)))};D.Jc=function(b){var c,d;c=b.Ng;d=b.Ng+(0,D.bb)(b.nb);c>b.Fm?b.Td-b.Lc>b.VD&&(0,D.Ob)(b,b.nb):d<b.Jf&&b.Td-b.Lc>b.VD&&(0,D.Pb)(b,b.nb)};
D.wa.prototype.Twa=function(b,c){var d,e,f,g,h;d=c[0].start;e=this.nb.firstChild;f=(0,D.ob)(this.gc,"cell");g=(0,D.Aa)(this.gc);h=d-this.Lc;var k=e.childNodes[h+1],m=this.Md;k.style.left=this.getWidth()+"px";(0,window.setTimeout)(function(){k.innerHTML="";(0,D.xb)(this,b,k,h,f,D.o,m,D.u,g);(0,D.sb)(this);(0,window.setTimeout)(function(){k.style.left="0px"},250);(0,D.Fb)(this)&&(0,D.Gb)(this);(0,D.Bb)(this,D.u)}.bind(this),250)};
D.Gc=function(b,c){var d,e,f,g,h;if(b.nb==D.r)return D.r;d=b.nb.firstChild.childNodes;h=b.fb().getMappedAttribute("key");for(f=1;f<d.length;f++)if(e=d[f],g=e.getAttribute(h),g==c)return e;return D.r};D.Hc=function(b,c){var d,e,f,g,h;if(b.tc==D.r)return D.r;d=b.tc.firstChild.childNodes;h=b.fb().getMappedAttribute("key");for(f=1;f<d.length;f++)if(e=d[f],g=e.getAttribute(h),g==c)return e;return D.r};
D.Kc=function(b,c){var d,e,f,g,h;if(b.Ld==D.r)return D.r;d=b.Ld.firstChild.childNodes;h=b.fb().getMappedAttribute("key");for(f=0;f<d.length;f++)if(e=d[f],g=e.getAttribute(h),g==c)return e;return D.r};D.wa.prototype.setActive=function(b){var c;b!=D.r&&(c=this.Pc.keys({row:b.row,column:b.column}),b.rowKey=c.row,b.columnKey=c.column);this.qN=this.Se;this.Se=b};D.qc=function(b,c){b.fireEvent("active",{event:c,ui:{previousActiveKey:b.qN,activeKey:b.Se}})};
D.wa.prototype.pC=function(b){this.Se!=D.r&&(0,D.Lc)(this);this.setActive(b);(0,D.Bb)(this)};D.wa.prototype.Hf=function(b){for(var c=this.Lc;b.previousSibling;)c+=1,b=b.previousSibling;return c-1};D.wa.prototype.An=function(b){for(var c=this.Md;b.previousSibling;)c+=1,b=b.previousSibling;return c};D.ic=function(b,c){var d,e;d=(0,D.jc)(b,c);"row"===d?(e=b.Ql-1,c=c.parentNode):"column"===d&&(e=b.vj);for(;c.previousSibling;)e+=1,c=c.previousSibling;return e};
D.jc=function(b,c){return(0,D.ya)(c,b.getMappedStyle("colheadercell"))?"column":(0,D.ya)(c,b.getMappedStyle("rowheadercell"))?"row":D.r};D.Qb=function(b,c){return b.find(c,"cell")};D.wa.prototype.find=function(b,c,d){if(b==D.r||b==this.Kf)return D.r;d==D.n&&(d=this.getMappedStyle(c));return d==D.r?D.r:(0,D.ya)(b,d)?b:this.find(b.parentNode,c,d)};
D.Bb=function(b,c){var d,e;d=(0,D.Db)(b,b.Se,"active");d!=D.r&&(b.qN!=D.r&&b.Se!=D.r&&(b.qN.row===b.Se.row?e="row":b.qN.column===b.Se.column&&(e="column")),(0,D.Mc)(b,d,c===D.n||c===D.o?D.o:D.n,e))};D.Lc=function(b,c){var d,e;d=(0,D.Nc)(b,b.Se,D.o);c&&(e=b.getMappedStyle("selected"),e!=D.r&&(0,D.Db)(b,b.Se,e));d!=D.r&&(0,D.Oc)(d)};
D.Db=function(b,c,d){var e;e=b.createRange(c);e=(0,D.yc)(b,e);if(!(e==D.r||0==e.length))return d==D.n&&(d="selected"),e=e[0],d=b.getMappedStyle(d),d!=D.r&&((0,D.Ba)(e,d),c.row&&c.column&&(0,D.Mc)(b,e)),e};D.Nc=function(b,c,d){var e;c=b.createRange(c);c=(0,D.yc)(b,c);if(!(c==D.r||0==c.length)){c=c[0];e=b.getMappedStyle("active");e!=D.r&&(0,D.za)(c,e);if(d==D.n||!d)b=b.getMappedStyle("selected"),b!=D.r&&((0,D.za)(c,b),(0,D.Oc)(c));return c}};
D.Mc=function(b,c,d,e){c.setAttribute("id",(0,D.Qa)(b,"active"));c.setAttribute("tabIndex",0);var f,g,h;f="";b.tc!=D.r&&"row"!=e&&(g=c.parentNode,g=(0,D.Pc)(g),-1<g&&(h=b.tc.firstChild.childNodes,g<h.length&&(f=h[g].id)));b.Ld!=D.r&&"column"!=e&&(e=(0,D.Pc)(c),-1<e&&(g=b.Ld.firstChild.childNodes,e<g.length&&(f=""==f?g[e].id:[f,g[e].id].join(" "))));f=""==f?(0,D.Qa)(b,"active"):[f,(0,D.Qa)(b,"active")].join(" ");f=[f,(0,D.Qa)(b,"state")].join(" ");c.setAttribute("aria-labelledby",f);d!=D.n&&(b.aD==
D.r||b.aD!=c)&&c.focus()};D.Oc=function(b){b.setAttribute("tabIndex",-1);b.removeAttribute("id");b.removeAttribute("aria-labelledby")};D.Sb=function(b,c,d){if("row"===d){if(b.tc!=D.r&&(c=c.parentNode,c=(0,D.Pc)(c),-1<c&&(b=b.tc.firstChild.childNodes,c<b.length)))return b[c]}else if("column"===d&&b.Ld!=D.r&&(c=(0,D.Pc)(c),-1<c&&(b=b.Ld.firstChild.childNodes,c<b.length)))return b[c];return D.r};
D.Pc=function(b){var c,d,e,f;d=b.parentNode.childNodes;e=-1;for(f=0;f<d.length;f+=1){c=d[f];if(c===b)return e+1;"DIV"==c.nodeName&&e++}return e};
D.wa.prototype.createRange=function(b,c){var d,e,f,g,h,k,m,p,q,t;h=this.Pc.keys(b);c&&(k=this.Pc.keys(c),b.row<c.row||-1==c.row?(d=b.row,e=c.row,m=h.row,p=k.row):(d=c.row,e=b.row,m=k.row,p=h.row),!(0,window.isNaN)(b.column)&&!(0,window.isNaN)(c.column)?(b.column<c.column||-1==c.column?(f=b.column,g=c.column,q=h.column,t=k.column):(f=c.column,g=b.column,q=k.column,t=h.column),b={row:d,column:f},c={row:e,column:g}):(b={row:d},c={row:e}),h={row:m,column:q},k={row:p,column:t});return{startIndex:b,endIndex:c,
startKey:h,endKey:k}};D.Qc=function(b){return b.endIndex==D.r?b.startIndex:b.endIndex};
D.yc=function(b,c,d,e){var f,g,h,k,m;d==D.n&&(d=b.Lc);e==D.n&&(e=b.Td);f=c.startIndex;g=(0,D.Qc)(c);h=f.row;c=g.row;-1==c&&(c=window.Number.MAX_VALUE);if(e<h||c<d||!(0,window.isNaN)(f.column)&&!(0,window.isNaN)(g.column)&&(k=f.column,m=g.column,-1==m&&(m=window.Number.MAX_VALUE),b.Wf<k||m<b.Md))return D.r;d=[];e=b.nb.firstChild.childNodes;h=window.Math.max(0,h-b.Lc);c=window.Math.min(e.length-1,c-b.Lc+1);if(!(0,window.isNaN)(k)&&!(0,window.isNaN)(m)){k=window.Math.max(0,k-b.Md);m=m-b.Md+1;for(b=h;b<
c;b+=1){h=e[b+1].childNodes;for(f=k;f<window.Math.min(h.length,m);f+=1)g=h[f],d.push(g)}}else for(b=h;b<c;b+=1)k=e[b+1],d.push(k);return d};D.tc=function(b){return 38==b||40==b||37==b||39==b};D.wa.prototype.createIndex=function(b,c){return b!=D.r?c!=D.r?{row:b,column:c}:{row:b}:D.r};D.Rc=function(b){b.setAttribute("tabIndex",0);b.setAttribute("aria-labelledby",b.id);b.focus()};
D.pc=function(b,c,d,e){var f=b.getMappedStyle("active");if(b.Ed!=D.r&&b.Ed.elem!=D.r){"row"===b.Ed.axis?b.Ed.elem.firstChild!=D.r&&(0,D.za)(b.Ed.elem.firstChild,f):(0,D.za)(b.Ed.elem,f);var g=b.Ed.elem;g.setAttribute("tabIndex",-1);g.removeAttribute("aria-labelledby")}-1!=c&&(b.Ed==D.r&&(b.Ed={}),e!=D.n&&(b.Ed.axis=e),b.Ed.index=c,d!=D.r&&(b.Ed.elem=d,"row"===b.Ed.axis?b.Ed.elem.firstChild!=D.r&&(0,D.Ba)(b.Ed.elem.firstChild,f):(0,D.Ba)(b.Ed.elem,f),(0,D.Rc)(d)))};
D.uc=function(b){var c,d,e,f;c=b.Ed.axis;d=b.Ed.index;e=b.Ed.elem;"column"===c?f={row:0,column:d}:"row"===c&&(f={row:d,column:0});(0,D.yb)(b,f);b.aD!=D.r?(e.setAttribute("tabIndex",0),b.aD=e):e!=D.r&&(0,D.Rc)(e)};
D.Dc=function(b,c,d){var e,f,g,h,k;if(!(0,D.Ta)(b))return D.o;e=d?b.NV:b.Se;if(e!=D.r){b.fb().isRTLMode()&&(37==c?c=39:39==c&&(c=37));k=(0,D.Fb)(b)?b.OH.bind(b):b.pC.bind(b);h=D.u;f=e.row;g=e.column;switch(c){case 37:0<g?("row"==b.gc.rj()?(c=b.createIndex(b.Se.row,g-1),(0,D.yb)(b,c),b.pC(c)):(c=b.createIndex(f,g-1),(0,D.yb)(b,c),d?(0,D.rc)(b,c):k(c)),h=D.o):((0,D.zb)(b,f),b.tc!=D.r&&b.tc.firstChild&&(h=D.o));break;case 39:(0,D.Wa)(b,g)?d||(k(e),(0,D.yb)(b,e),(0,D.Wa)(b,g)||(h=D.o)):("row"==b.gc.rj()?
(c=b.createIndex(b.Se.row,g+1),(0,D.yb)(b,c),b.pC(c)):(c=b.createIndex(f,g+1),(0,D.yb)(b,c),d?(0,D.rc)(b,c):k(c)),h=D.o);break;case 38:0<f?(c=b.createIndex(f-1,g),(0,D.yb)(b,c),d?(0,D.rc)(b,c):k(c)):(0,D.Ab)(b,g);h=D.o;break;case 40:(0,D.Va)(b,f)?d||(k(e),(0,D.yb)(b,e),(0,D.Va)(b,f)||(h=D.o)):(c=b.createIndex(f+1,g),(0,D.yb)(b,c),d?(0,D.rc)(b,c):k(c),h=D.o);break;case 36:c=b.createIndex(f,0);k(c);(0,D.yb)(b,c);h=D.o;break;case 35:c=(0,D.Ua)(b,"column")?b.createIndex(f,window.Math.max(0,b.Wf-1)):b.createIndex(f,
window.Math.max(0,b.Pc.getCount("column")-1));k(c);(0,D.yb)(b,c);h=D.o;break;case 33:c=b.createIndex(0,g);k(c);(0,D.yb)(b,c);h=D.o;break;case 34:c=(0,D.Ua)(b,"column")?b.createIndex(window.Math.max(0,b.Td-1),g):b.createIndex(window.Math.max(0,b.Pc.getCount("row")-1),g),k(c),(0,D.yb)(b,c),h=D.o}d&&b.CH&&(b.CH=D.u);return h}};
D.Ab=function(b,c){var d,e;b.Ld!=D.r&&b.Ld.firstChild&&(d=c-b.vj,e=b.Ld.firstChild.childNodes,d<e.length&&(d=e[d],b.Se!=D.r&&((0,D.Lc)(b),b.setActive(D.r),(0,D.Fb)(b)&&(0,D.Sc)(b)),(0,D.pc)(b,c,d,"column")))};D.zb=function(b,c){var d,e;b.tc!=D.r&&b.tc.firstChild&&(d=c-b.Ql+1,e=b.tc.firstChild.childNodes,d<e.length&&(d=e[d],b.Se!=D.r&&((0,D.Lc)(b),b.setActive(D.r),(0,D.Fb)(b)&&(0,D.Sc)(b)),(0,D.pc)(b,c,d,"row")))};
D.yb=function(b,c){var d,e,f,g,h,k,m,p,q;d=c.row;e=c.column;g=f=0;d<b.Lc||d>=b.Td?(g=d<b.Lc?b.Em*d:b.Em*(d+1)-(0,D.bb)(b.nb),g=b.Ng-g,b.Vw=c):(h=b.nb.firstChild,k=h.childNodes[d-b.Lc+1],h=b.Ng,m=b.Ng+(0,D.bb)(b.nb),p=(0,window.parseInt)(k.style.top),k=(0,D.bb)(k),p+k>m?g=m-(p+k):p<h&&(g=h-p));!(0,window.isNaN)(e)&&b.Vw==D.r&&(e<b.Md||e>=b.Wf?(f=e<b.Md?b.ap*e:b.ap*(e+1)-(0,D.cb)(b.nb),f=b.Pk-f,b.Vw=c):(h=b.nb.firstChild,k=h.childNodes[d-b.Lc+1],q=k.childNodes[e-b.Md],d=(0,D.Nb)(q,"left"),e=q.offsetWidth,
h=b.Pk,m=b.Pk+(0,D.cb)(b.nb),d<h?f=h-d:d+e>m&&(f=m-(d+e))));if(0!=f||0!=g)q!=D.r&&(b.aD=q),(0,D.Jb)(b,f,g)};D.Tb=function(b,c,d){d==D.n&&(d=b.getMappedStyle("headercell"));if(d!=D.r){if((0,D.ya)(c,d))return c;if(c.parentNode)return(0,D.Tb)(b,c.parentNode,d)}return D.r};
D.Ca=function(b){var c,d,e,f,g;c=(0,D.Hb)(b.gc);if(0<c){d=b.nb.firstChild.childNodes;g=b.getMappedStyle("banded");for(e=1;e<d.length;e++)f=b.Lc+e-1,1===window.Math.floor(f/c)%2?(0,D.ya)(d[e],g)||(0,D.Ba)(d[e],g):(0,D.ya)(d[e],g)&&(0,D.za)(d[e],g)}};D.Tc=function(b,c,d){c=b.fb().getTranslatedText(c,d);c!=D.r&&(b.CFa.innerHTML=c)};D.wa.prototype.Wma=function(b){(0,D.Gc)(this,b.rowKey).setAttribute("aria-expanded",D.o);(0,D.Tc)(this,"accessibleRowExpanded")};
D.wa.prototype.Vma=function(b){(0,D.Gc)(this,b.rowKey).setAttribute("aria-expanded",D.u);(0,D.Tc)(this,"accessibleRowCollapsed")};D.wa.prototype.Vh=function(b){return b.getAttribute(this.fb().getMappedAttribute("key"))};
D.xc=function(b,c){if((0,D.hc)(b,(0,D.gc)(b,c.target))){if(88==c.keyCode&&(0,D.Cc)(b.Xf,c))return(0,D.Yb)(b,c);if(86==c.keyCode&&(0,D.Cc)(b.Xf,c))return(0,D.Zb)(b,c);if(27==c.keyCode&&b.us!=D.r)return(0,D.za)(b.us,b.getMappedStyle("cut")),b.us=D.r,b.bD!==D.r&&((0,D.za)(b.bD,b.getMappedStyle("cut")),b.bD=D.r),D.o}return D.u};
D.Yb=function(b,c){var d;b.us!=D.r&&(0,D.za)(b.us,b.getMappedStyle("cut"));d=b.Vh(b.find(c.target,"row"));b.us=(0,D.Gc)(b,d);b.bD=(0,D.Hc)(b,d);(0,D.Ba)(b.us,b.getMappedStyle("cut"));b.bD!==D.r&&(0,D.Ba)(b.bD,b.getMappedStyle("cut"));return D.o};D.Zb=function(b,c){var d;return b.us!=D.r?((0,D.za)(b.us,b.getMappedStyle("cut")),b.bD!==D.r&&(0,D.za)(b.bD,b.getMappedStyle("cut")),d=b.find(c.target,"row"),b.us!==d&&((0,D.Fb)(b)&&((0,D.Uc)(b),(0,D.Sc)(b)),b.Pc.move(b.Vh(b.us),b.Vh(d))),b.us=D.r,D.o):D.u};
D.dc=function(b,c){var d,e;b.ue==D.r&&(d=b.Vh(b.find(c.target,"row")),b.ue=(0,D.Gc)(b,d),b.Sk=(0,D.Hc)(b,d),(0,D.Ba)(b.ue,b.getMappedStyle("move")),b.oN=(0,D.Nb)(b.ue,"top"),b.cD=window.document.createElement("div"),(0,D.Ba)(b.cD,b.getMappedStyle("droptarget")),(0,D.fb)(b.cD,(0,D.bb)(b.ue)),(0,D.eb)(b.cD,b.oN,"top"),b.nb.firstChild.appendChild(b.cD),b.Sk!==D.r&&((0,D.Ba)(b.Sk,b.getMappedStyle("move")),b.dD=window.document.createElement("div"),(0,D.Ba)(b.dD,b.getMappedStyle("droptarget")),(0,D.fb)(b.dD,
(0,D.bb)(b.Sk)),(0,D.eb)(b.dD,b.oN,"top"),b.tc.firstChild.appendChild(b.dD)));b.Fz=b.Pl;b.Pl=c.pageY;d=b.Pl-b.Fz;e=(0,D.bb)(b.ue);(0,D.eb)(b.ue,(0,D.Nb)(b.ue,"top")+d,"top");b.Sk!==D.r&&(0,D.eb)(b.Sk,(0,D.Nb)(b.Sk,"top")+d,"top");b.ue.nextSibling!=D.r&&(0,D.Nb)(b.ue.nextSibling,"top")<(0,D.Nb)(b.ue,"top")+e/2?(0,D.Vc)(b,"nextSibling"):b.ue.previousSibling!=D.r&&(0,D.Nb)(b.ue.previousSibling,"top")>(0,D.Nb)(b.ue,"top")-e/2&&(0,D.Vc)(b,"previousSibling")};
D.Vc=function(b,c){var d,e,f,g;e=b.ue.parentNode;"nextSibling"==c?(d=b.oN+(0,D.bb)(b.ue[c]),f=b.oN):(d=(0,D.Nb)(b.ue[c],"top"),f=d+(0,D.bb)(b.ue));(0,D.eb)(b.cD,d,"top");(0,D.eb)(b.ue[c],f,"top");b.Sk!==D.r&&(g=b.Sk.parentNode,(0,D.eb)(b.dD,d,"top"),(0,D.eb)(b.Sk[c],f,"top"));b.oN=d;"nextSibling"===c?(e.insertBefore(b.ue,b.ue[c][c]),b.Sk!==D.r&&g.insertBefore(b.Sk,b.Sk[c][c])):(e.insertBefore(b.ue,b.ue[c]),b.Sk!==D.r&&g.insertBefore(b.Sk,b.Sk[c]))};
D.kc=function(b,c){b.cD.parentNode.removeChild(b.cD);b.ue.style.zIndex=0;b.Sk!==D.r&&(b.dD.parentNode.removeChild(b.dD),b.Sk.style.zIndex=0);b.setActive(D.r);(0,D.Fb)(b)&&((0,D.Uc)(b),(0,D.Sc)(b));c==D.o?b.Pc.move(b.Vh(b.ue),b.ue.nextSibling===D.r?D.r:b.Vh(b.ue.nextSibling)):b.Pc.move(b.Vh(b.ue),b.Vh(b.ue));b.ue=D.r;b.Cu=D.u};
D.hc=function(b,c){var d;c==D.r||(0,D.ya)(c.parentNode,b.getMappedStyle("colheader"))?d=D.u:(d=b.Pc.getCapability("move"),d="enable"===(0,D.rb)((0,D.Ga)(b.gc,"dnd","reorder"))&&("full"===d||"row"===d)&&(b.Se!=D.r?b.Vh(b.nb.firstChild.childNodes[b.Se.row+1]):b.Ed!=D.r&&"row"===b.Ed.axis?b.Vh(b.tc.firstChild.childNodes[b.Ed.index+1]):D.r)===b.Vh(c)?D.o:D.u);return d};
D.nc=function(b,c,d){c!=D.r&&((0,D.hc)(b,c)?(b.tc.style.cursor="move",d||(c.style.cursor="move"),b.Rna=D.o):("move"===b.tc.style.cursor&&(b.tc.style.cursor="default"),"move"===c.style.cursor&&(c.style.cursor="default"),b.Rna=D.u))};
D.Uc=function(b){var c,d;d=b.Qm();for(c=0;c<d.length;c+=1)(0,D.rd)(b,d[c]);b.Se!=D.r&&"row"==b.gc.rj()&&(0,D.Lc)(b)};D.rd=function(b,c){var d=(0,D.yc)(b,c),e,f,g,h;if(!(d==D.r||0==d.length))if(f=b.getMappedStyle("selected"),g=b.getMappedStyle("active"),f!=D.r&&g!=D.r)for(e=0;e<d.length;e+=1)h=d[e],(0,D.za)(h,g),(0,D.za)(h,f),(0,D.Oc)(h)};D.td=function(b,c,d){c=(0,D.yc)(b,c);(0,D.sd)(b,c);d&&(0,D.Tc)(b,"accessibleMultiCellSelected",{num:c.length})};
D.sd=function(b,c){var d,e,f;if(!(c==D.r||0==c.length))if(d=b.getMappedStyle("selected"),d!=D.r)for(e=0;e<c.length;e+=1)f=c[e],(0,D.Ba)(f,d),(0,D.Mc)(b,f)};D.Gb=function(b,c,d){var e,f,g;f=b.Qm();for(e=0;e<f.length;e+=1)g=(0,D.yc)(b,f[e],c,d),(0,D.sd)(b,g)};D.wa.prototype.LK=function(b){var c=this.getMappedStyle("selected");return"row"==this.gc.rj()&&c!=D.r?(0,D.ya)((0,D.gc)(this,b),c):c!=D.r?(0,D.ya)(b,c):D.u};
D.oc=function(b,c){var d,e,f,g,h,k=D.o;e=(0,D.Qb)(b,c.target);e!=D.r&&(d={row:b.Hf(e.parentNode),column:b.An(e)});if(d!=D.r&&d!=D.n){(0,D.pc)(b,-1);b.Ed=D.r;(0,D.yb)(b,d);h=b.Qm().slice(0);f=(0,D.Cc)(b.Xf,c);g=c.shiftKey;if((0,D.ac)(b))if(b.Xf.da())if(b.LK(e)){e=d;var m,p,q,t;"row"==b.gc.rj()&&(e=b.createIndex(e.row));d=e.row;e=e.column;f=-1;g=b.Qm();for(k=0;k<g.length;k+=1)if(m=g[k],p=m.startIndex,m=(0,D.Qc)(m),q=p.row,t=m.row,!(q!=d||t!=d))if(!(0,window.isNaN)(p.column)&&!(0,window.isNaN)(m.column)){if(p=
p.column,m=m.column,!(p!=e||m!=e)){f=k;break}}else if((0,window.isNaN)(e)){f=k;break}-1!=f&&((0,D.rd)(b,g[f]),g.splice(f,1));k=D.u}else(0,D.ud)(b,d);else!f&&!g?b.OH(d):!f&&g?((0,D.rc)(b,d),k=D.u):(0,D.ud)(b,d);else b.OH(d);(0,D.sc)(b.Qm(),h)||b.Dl(c);k&&(0,D.qc)(b,c)}};
D.sc=function(b,c){var d,e,f;if(b.length!==c.length)return D.u;for(d=0;d<b.length;d+=1){f=D.u;for(e=0;e<c.length;e+=1)b[d].startIndex.row===c[e].startIndex.row&&(b[d].startIndex.column===c[e].startIndex.column&&b[d].endIndex.row===c[e].endIndex.row&&b[d].endIndex.column===c[e].endIndex.column)&&(f=D.o);if(f===D.u)return D.u}return D.o};D.gc=function(b,c){return b.find(c,"row")};D.Sc=function(b){(0,D.Uc)(b);b.Qm().length=0};
D.zc=function(b,c){b.T7=c?"actionable":"navigation";(0,D.Tc)(b,"actionable"===b.T7?"accessibleActionableMode":"accessibleNavigationMode")};D.vc=function(b,c,d){var e;e=b.createIndex(c,0);c=b.createIndex(c,-1);(0,D.vd)(b,e,c,d)};D.wc=function(b,c,d){var e;e=b.createIndex(0,c);c=b.createIndex(-1,c);(0,D.vd)(b,e,c,d)};D.vd=function(b,c,d,e){(0,D.Sc)(b);c=b.createRange(c,d);b.Qm().push(c);(0,D.td)(b,c);b.Se!=D.r&&(b.NV=b.Se,(0,D.Bb)(b));b.Dl(e)};
D.wa.prototype.Qm=function(){this.MV==D.r&&(this.MV=[]);return this.MV};D.wa.prototype.GetSelection=D.wa.prototype.Qm;D.wa.prototype.Yra=function(b){b!=D.n&&(b==D.r&&(b=[]),this.MV=b,this.nb!=D.r&&(0,D.Gb)(this,this.Lc,this.Td),this.Dl(D.r))};D.wa.prototype.SetSelection=D.wa.prototype.Yra;D.wa.prototype.Dl=function(b){b={event:b,ui:{selection:this.Qm()}};this.fireEvent("select",b)};
D.rc=function(b,c){var d,e,f,g,h;d=b.Se;if(d!=D.r&&(b.NV=c,"row"==b.gc.rj()&&(c=b.createIndex(c.row)),d=b.createRange(d,c),e=b.Qm(),f=e[e.length-1],g=f.startIndex.row==d.startIndex.row,f.startIndex.column!=D.r&&d.startIndex.column!=D.r&&(g=g&&f.startIndex.column==d.startIndex.column),h=f.endIndex.row==d.endIndex.row,f.endIndex.column!=D.r&&d.endIndex.column!=D.r&&(h=h&&f.endIndex.column==d.endIndex.column),!g||!h))e.pop(),e.push(d),(0,D.rd)(b,f),(0,D.td)(b,d,D.o),(0,D.Bb)(b)};
D.ud=function(b,c){var d,e;d=b.Qm();0<d.length&&b.Se!=D.r&&(0,D.Lc)(b,!b.CH);b.setActive(c);b.NV=c;"row"==b.gc.rj()&&(c=b.createIndex(c.row));e=b.createRange(c,c);d.push(e);(0,D.Bb)(b);(0,D.Db)(b,c,"selected")};D.wa.prototype.OH=function(b){this.CH?this.Se!=D.r&&this.NV==this.Se&&((0,D.Nc)(this,this.Se),this.Qm().pop()):(0,D.Sc)(this);(0,D.ud)(this,b)};
D.Bc=function(b){var c,d,e,f,g;c=[];if(window.document.evaluate){b=window.document.evaluate(".//input|.//select|.//textarea|.//button|.//a|.//INPUT|.//SELECT|.//TEXTAREA|.//BUTTON|.//A",b,D.r,window.XPathResult.ANY_TYPE,D.r);for(d=b.iterateNext();d;)!d.disabled&&(!d.tabIndex||0<d.tabIndex)&&c.push(d),d=b.iterateNext()}else{b=b.getElementsByTagName("*");e=b.length;f=/^INPUT|SELECT|BUTTON|^A\b|TEXTAREA/;for(g=0;g<e;g+=1)d=b[g],d.tagName.match(f)&&(!d.disabled&&(!d.tabIndex||0<d.tabIndex))&&c.push(d)}return c};
D.cc=function(b,c){var d;if(b.eD===D.u)b.Bu=(0,D.ed)(b,c),b.ve!=D.r&&(d=b.find(b.ve,"header"),d!=D.r&&(d.style.cursor="default"==b.Bu?b.Rna===D.o?"move":b.Bu:b.Bu));else{var e;b.nN=c.pageX;b.CV=c.pageY;b.Xf.da()?(b.nN=c.touches[0].pageX,b.CV=c.touches[0].pageY):(b.nN=c.pageX,b.CV=c.pageY);d=(0,D.ya)(b.ve,b.getMappedStyle("colheadercell"))?"column":"row";"col-resize"===b.Bu?"column"===d?(d=(0,window.isNaN)((0,D.cb)(b.ve))?50:(0,D.cb)(b.ve),e=(0,D.gd)(b,"column",d),(0,D.hd)(b,d,e)):"row"===d&&(d=(0,D.cb)(b.tc),
e=(0,D.gd)(b,"row",d),(0,D.id)(b,d,e)):"row-resize"===b.Bu&&("row"===d?(d=(0,window.isNaN)((0,D.bb)(b.ve.parentNode))?(0,D.Ka)(b):(0,D.bb)(b.ve.parentNode),e=(0,D.jd)(b,"row",d),(0,D.kd)(b,d,e)):"column"===d&&(d=(0,D.bb)(b.Ld),e=(0,D.jd)(b,"column",d),(0,D.ld)(b,d,e)));(0,D.gb)(b);b.FV=b.nN;b.U7=b.CV}};
D.ec=function(b,c){if("col-resize"===b.Bu||"row-resize"===b.Bu)b.eD=D.o,b.Xf.da()?(b.FV=c.touches[0].pageX,b.U7=c.touches[0].pageY):(b.FV=c.pageX,b.U7=c.pageY),b.fD=0,b.HV=0,b.pN=0,b.IV=0,b.JV=0,b.GV=0};D.lc=function(b,c){var d;b.eD===D.o&&(d="col-resize"===b.Bu?b.ve.style.width:b.ve.style.height,d={event:c,ui:{header:b.Vh(b.ve),size:d}},b.fireEvent("resize",d),b.eD=D.u,b.Bu="default",b.find(b.ve,"header").style.cursor=b.Bu)};D.md=function(b,c){return"true"===c.getAttribute(b.fb().getMappedAttribute("resizable"))};
D.nd=function(b,c){if((0,D.ya)(c,b.getMappedStyle("colheadercell"))){if(c.previousSibling!==D.r)return"true"===c.previousSibling.getAttribute(b.fb().getMappedAttribute("resizable"))}else if((0,D.ya)(c,b.getMappedStyle("rowheadercell"))&&c.parentNode.previousSibling.firstChild!==D.r)return"true"===c.parentNode.previousSibling.firstChild.getAttribute(b.fb().getMappedAttribute("resizable"));return D.u};
D.ed=function(b,c){var d=c.target,e,f,g,h,k,m,p,q;(d=b.find(c.target,"colheadercell"))?e="column":(d=b.find(c.target,"rowheadercell"),e="row");if(!d)return"default";"column"===e?(m="enable"===(0,D.bc)(b.gc,e).height?D.o:D.u,k=(0,D.md)(b,d),p=(0,D.nd)(b,d)):"row"===e&&(k="enable"===(0,D.bc)(b.gc,e).width?D.o:D.u,m=(0,D.md)(b,d),p=(0,D.nd)(b,d));b.Xf.da()?(g=c.touches[0].pageX,h=c.touches[0].pageY):(g=c.pageX,h=c.pageY);q=d;var t,v;t=(0,D.Ec)(b,q);f=t[0];t=t[1];(0,D.ya)(q,b.getMappedStyle("colheadercell"))?
(v=(0,window.isNaN)((0,D.cb)(q))?50:(0,D.cb)(q),q=(0,D.bb)(b.Ld)):(v=(0,D.cb)(b.tc),q=(0,window.isNaN)((0,D.bb)(q.parentNode))?(0,D.Ka)(b):(0,D.bb)(q.parentNode));f=[f,t,f+v,t+q];q=b.fb().isRTLMode();if(k&&(q?g<f[0]+5:g>f[2]-5))return b.ve=d,"col-resize";if("column"===e&&p&&(q?g>f[2]-5:g<f[0]+5))if(b.ve=d.previousSibling,b.ve!==D.r)return"col-resize";return m&&h>f[3]-5?(b.ve=d,"row-resize"):"row"===e&&(p&&h<f[1]+5)&&(b.ve=d.parentNode.previousSibling.firstChild,b.ve!==D.r)?"row-resize":"default"};
D.hd=function(b,c,d){var e;c=d-c;e=(0,D.cb)(b.kd.firstChild)+c;if(e>=(0,D.cb)(b.nb)){(0,D.Oa)(b.kd.firstChild,e);(0,D.Oa)(b.nb.firstChild,e);(0,D.Oa)(b.Ld.firstChild,e);(0,D.od)(b);(0,D.Oa)(b.ve,d);var f,g,h,k,m,p,q;f=b.fb().isRTLMode()?"right":"left";g=b.nb.firstChild.childNodes;h=b.ve.parentNode.childNodes;k=D.u;if(h.length===g[1].childNodes.length){b.nb.style.display="none";b.Ld.style.display="none";for(m=0;m<h.length;m+=1)if(h[m]!==b.ve&&k===D.o){p=(0,D.Nb)(h[m],f)+c;(0,D.eb)(h[m],p,f);for(q=
1;q<g.length;q+=1)(0,D.eb)(g[q].childNodes[m],p,f)}else if(h[m]===b.ve){k=D.o;b.rN.Zj("column",b.ve.getAttribute(b.fb().getMappedAttribute("key")),d);for(q=1;q<g.length;q+=1)(0,D.Oa)(g[q].childNodes[m],d)}b.nb.style.display="block";b.Ld.style.display="block"}b.Lh+=c;b.cp+=c;b.ap=e/b.Pc.getCount("column")}else b.fD+=c};
D.kd=function(b,c,d){var e,f;c=d-c;e=(0,D.bb)(b.kd.firstChild)+c;if(e>=(0,D.bb)(b.nb)){(0,D.fb)(b.ve.parentNode,d);f=(0,D.bb)(b.tc.firstChild)+c;(0,D.fb)(b.tc.firstChild,f);(0,D.fb)(b.kd.firstChild,e);(0,D.fb)(b.nb.firstChild,e);var g,h,k,m;f=b.nb.firstChild.childNodes;g=b.ve.parentNode.parentNode.childNodes;h=D.u;if(f.length===g.length){b.nb.style.display="none";b.tc.style.display="none";for(k=1;k<g.length;k+=1)g[k].firstChild!==b.ve&&h===D.o?(m=(0,D.Nb)(g[k],"top")+c,(0,D.eb)(g[k],m,"top"),(0,D.eb)(f[k],
m,"top")):g[k].firstChild===b.ve&&(h=D.o,b.rN.Zj("row",b.ve.parentNode.getAttribute(b.fb().getMappedAttribute("key")),d),(0,D.fb)(f[k],d));b.nb.style.display="block";b.tc.style.display="block"}(0,D.od)(b);b.Jf+=c;b.Qk+=c;b.Em=e/b.Pc.getCount("row")}};D.ld=function(b,c,d){var e,f,g,h;(0,D.fb)(b.Ld,d);b.zV=d+"px";e=b.nb;f=b.kd;g=b.tc;c=d-c;h=(0,D.bb)(e);(0,D.fb)(e,h-c);(0,D.eb)(e,d,"top");(0,D.fb)(g,h-c);(0,D.eb)(g,d,"top");(0,D.fb)(f,(0,D.bb)(f)-c);(0,D.eb)(f,d,"top");(0,D.od)(b)};
D.id=function(b,c,d){var e,f,g,h;(0,D.Oa)(b.tc,d);b.LV=d+"px";(0,D.od)(b);e=b.nb;f=b.kd;g=b.Ld;c=d-c;h=(0,D.cb)(e);b=b.fb().isRTLMode()?"right":"left";(0,D.Oa)(e,h-c);(0,D.eb)(e,d,b);(0,D.Oa)(g,h-c);(0,D.eb)(g,d,b);(0,D.Oa)(f,(0,D.cb)(f)-c);(0,D.eb)(f,d,b)};
D.gd=function(b,c,d){var e,f,g,h,k;e=(0,D.cb)(b.nb);f=b.fb().isRTLMode()?b.FV-b.nN:b.nN-b.FV;g=d+f+b.fD+b.HV+b.JV;h=(0,D.cb)(b.kd.firstChild);k=window.Math.round((0,D.cb)(b.Kf)/2);h+f+b.fD<e?(b.fD+=f-e+h,g=d+(e-h)):20>g?(b.HV+=f-20+d,g=20):(b.HV=0,b.fD=0);"row"===c&&(g>k?(b.JV+=f-k+d,g=k):b.JV=0);return g};
D.jd=function(b,c,d){var e,f,g,h,k;e=(0,D.bb)(b.nb);f=b.CV-b.U7;g=d+f+b.pN+b.IV+b.GV;h=(0,D.bb)(b.kd.firstChild);k=window.Math.round((0,D.bb)(b.Kf)/2);h+f+b.pN<e&&(b.pN+=f-e+h,g=d+e-h);20>g?(b.IV+=f-20+d,g=20):(b.IV=0,b.pN=0);"column"===c&&(g>k?(b.GV+=f-k+d,g=k):b.GV=0);return g};
D.od=function(b){var c,d,e,f,g,h,k,m,p;c=b.nb;d=b.kd;e=b.Ld;f=b.tc;g=(0,D.cb)(c);h=(0,D.bb)(c);k=(0,D.jb)(b,h);m=(0,D.ib)(b,g);p=(0,D.hb)(b.Xf);m&&!k&&!b.Du&&!b.Eu?k=(0,D.jb)(b,h-p):!m&&k&&!b.Du&&!b.Eu?m=(0,D.ib)(b,g-p):m&&(k&&b.Du&&b.Eu)&&(!(0,D.jb)(b,h+p)&&!(0,D.ib)(b,g+p))&&(k=m=D.u);!k&&!m&&b.Du&&b.Eu?((0,D.Oa)(c,g+p),(0,D.fb)(c,h+p),(0,D.Oa)(e,g+p),(0,D.fb)(f,h+p),d.style.overflow="visible"):!k&&b.Eu?((0,D.Oa)(c,g+p),(0,D.Oa)(e,g+p)):!m&&b.Du&&((0,D.fb)(c,h+p),(0,D.fb)(f,h+p));k&&m&&!b.Du&&!b.Eu?
(d.style.overflow="auto",(0,D.Oa)(c,g-p),(0,D.fb)(c,h-p),(0,D.Oa)(e,g-p),(0,D.fb)(f,h-p)):k&&!b.Eu?(d.style.overflow="auto",(0,D.Oa)(c,g-p),(0,D.Oa)(e,g-p)):m&&!b.Du&&(d.style.overflow="auto",(0,D.fb)(c,h-p),(0,D.fb)(f,h-p));b.Du=m;b.Eu=k};
D.Ub=function(b,c,d,e){e=(0,window.parseInt)(e,10);if((0,D.ya)(c,b.getMappedStyle("sortascending"))||(0,D.ya)(c,b.getMappedStyle("sortdescending"))||(0,D.ya)(c,b.getMappedStyle("sortindicators")))c=(0,D.Tb)(b,c);b.ve=c;"resizeWidth"===d?(c=c.offsetWidth,c!==e&&((0,D.ya)(b.ve,b.getMappedStyle("colheadercell"))?(0,D.md)(b,b.ve)&&(0,D.hd)(b,c,e):(0,D.id)(b,c,e))):"resizeHeight"===d&&(c=c.offsetHeight,c!==e&&((0,D.ya)(b.ve,b.getMappedStyle("colheadercell"))?(0,D.ld)(b,c,e):(0,D.md)(b,b.ve)&&(0,D.kd)(b,
c,e)));(0,D.gb)(b)};
D.Yc=function(b,c,d){c!=D.r&&(c=(0,D.Xc)(c),"descending"===d&&(0,D.ya)(c,b.getMappedStyle("sortascending"))?((0,D.za)(c,b.getMappedStyle("sortascending")),(0,D.Ba)(c,b.getMappedStyle("sortdescending"))):"ascending"===d&&(0,D.ya)(c,b.getMappedStyle("sortdescending"))&&((0,D.za)(c,b.getMappedStyle("sortdescending")),(0,D.Ba)(c,b.getMappedStyle("sortascending"))))};
D.mc=function(b,c,d){var e,f=D.u;c!=D.r&&(e=(0,D.Xc)(c),b.In!=D.r&&(f=b.In.key===b.Vh(c)),d===D.u&&!f?((0,D.za)(e,b.getMappedStyle("disabled")),(0,D.Ba)(e,b.getMappedStyle("default"))):d===D.o&&!f&&((0,D.za)(e,b.getMappedStyle("default")),(0,D.Ba)(e,b.getMappedStyle("disabled"))))};D.Xb=function(b,c,d){var e;e=(0,D.Tb)(b,c.target);e!=D.r&&(d==D.r&&(d=b.In!=D.r&&b.In.key===b.Vh(e)?"ascending"===b.In.direction?"descending":"ascending":"ascending"),(0,D.Wb)(b,c,e,d))};
D.Wb=function(b,c,d,e){var f,g;d.setAttribute(b.fb().getMappedAttribute("sortDir"),e);f=b.Vh(d);var h;g=b.getMappedStyle("colheadercell");h=b.getMappedStyle("rowheadercell");g=(0,D.ya)(d,g)?"column":(0,D.ya)(d,h)?"row":D.r;var k;b.In!=D.r&&(h=(0,D.Kc)(b,b.In.key),k=(0,D.Xc)(h),(0,D.Yc)(b,h,"ascending"),"descending"===b.In.direction&&((0,D.za)(k,b.getMappedStyle("sortdescending")),(0,D.Ba)(k,b.getMappedStyle("sortascending"))),(0,D.Ba)(k,b.getMappedStyle("disabled")),(0,D.za)(k,b.getMappedStyle("default")),
(0,D.za)(h.lastChild,b.getMappedStyle("enabled")));b.In={key:f,axis:g,direction:e};(0,D.Yc)(b,d,e);b.In!=D.r&&(d=(0,D.Kc)(b,b.In.key),h=(0,D.Xc)(d),(0,D.Ba)(h,b.getMappedStyle("default")),(0,D.za)(h,b.getMappedStyle("disabled")),(0,D.za)(h,b.getMappedStyle("selected")),(0,D.Ba)(d.lastChild,b.getMappedStyle("enabled")));e!=D.r&&(f!=D.r&&g!=D.r)&&((0,D.nb)(b),d={axis:g,key:f,direction:e},b.Pc.sort(d,{success:b.bxa.bind(b),error:b.axa.bind(b)}),c={event:c,ui:{header:f,direction:e}},b.fireEvent("sort",
c));(0,D.Tc)(b,"ascending"===e?"accessibleSortAscending":"accessibleSortDescending",{id:f})};D.wa.prototype.axa=function(){(0,D.sb)(this)};
D.wa.prototype.bxa=function(){(0,D.sb)(this);var b=window.document.createElement("div");b.id=(0,D.Qa)(this,"rowHeader");b.className=this.fb().getMappedStyle("rowheader")+" "+this.fb().getMappedStyle("header");this.fetchHeaders("row",this.Lc,b,this.Td-this.Lc);this.fetchCells(this.nb,this.kd,this.Lc,this.Md,this.Td-this.Lc,this.Wf-this.Md,{success:this.pEa.bind(this,b),error:this.Uma})};
D.wa.prototype.pEa=function(b,c,d){var e,f,g,h;this.Rk.cells=D.u;(0,D.Ta)(this)&&(0,D.sb)(this);e=d[0].start;f=c.getCount("row");g=d[1].start;c.getCount("column");d=window.document.createDocumentFragment();d.appendChild(window.document.createElement("div"));h=window.document.createDocumentFragment();(0,D.vb)(this,d,D.o,this.Fm,e,f,g,D.u,c);c=this.nb.firstChild;e=this.tc.firstChild;if(b&&b.firstChild)for(;b.firstChild.firstChild;)h.appendChild(b.firstChild.firstChild);b=e;var k,m,p,q,t,v,w,A,D$,K,
G,M,O,T,Q,V;T=D.u;k=this;m=0;Q=d.cloneNode(D.o);V=h?h.cloneNode(D.o):D.r;O=this.fb().getMappedAttribute("key");e=c.childElementCount;p=(0,D.Zc)(this,d);f=(0,D.Zc)(this,c);g=[];m=[];A=[];D$=[];K=0;t=this.getHeight()-(0,D.bb)(this.Ld);v=(0,D.Ka)(this);(w=(0,window.parseInt)(c.childNodes[1].style.top.split("px")[0]))||(w=0);q=this.Ng-w;w=[q,q+t];t=[window.Math.ceil(q/v),window.Math.floor((q+t)/v)];b.childElementCount!=e&&b.firstChild.children.length==e+1&&(b=b.firstChild);if(b.childElementCount==e&&
h){T=D.o;for(q=1;q<b.childElementCount;q++)b.childNodes[q].id+="_old"}if(T)for(q=0;q<V.childElementCount;q++)V.children[q].style.top=c.children[q].style.top;for(q=0;q<f.length;q++)g[f[q]]=q;for(G=0;G<p.length;G++)if(g.hasOwnProperty(p[G])){if(g[p[G]]<t[0]-1&&G<t[0]-1||g[p[G]]>t[1]+1&&G>t[1]+1||g[p[G]]<t[0]-1&&G>t[1]+1||g[p[G]]>t[1]+1&&G<t[0]-1)g[p[G]]="no_0";(0,D.$c)(g[p[G]])&&(g[p[G]]>G?(G<t[0]&&g[p[G]]>t[0]?q=g[p[G]]-(t[0]+1):((0,D.$c)(g[p[G]])&&g[p[G]]>t[1]&&(q=t[1]-g[p[G]]-1,(0,D.ad)(c.childNodes[g[p[G]]+
1],0,0,"linear",q*v),T&&(0,D.ad)(b.childNodes[g[p[G]]+1],0,0,"linear",(q+1)*v)),q=g[p[G]]-G),g[p[G]]="up_-"+q):g[p[G]]<G?(G>t[1]&&g[p[G]]<t[1]?q=t[1]+1-g[p[G]]:((0,D.$c)(g[p[G]])&&g[p[G]]<t[0]&&(q=t[0]-g[p[G]]-1,(0,D.ad)(c.childNodes[g[p[G]]+1],0,0,"linear",q*v),T&&(0,D.ad)(b.childNodes[g[p[G]]+1],0,0,"linear",q*v)),q=G-g[p[G]]),g[p[G]]="down_"+q):g[p[G]]==G&&(g[p[G]]="no_0"))}else m[p[G]]=G;for(p=0;p<f.length;p++)g.hasOwnProperty(f[p])&&(0,D.$c)(g[f[p]])&&(g[f[p]]<t[0]&&(g[f[p]]="no_0"),g[f[p]]>
t[1]&&(g[f[p]]="no_0"),g[f[p]]>=t[0]&&g[f[p]]<=t[1]&&(q=t[1]-g[f[p]]+2,g[f[p]]="down_"+q));for(M in m)m.hasOwnProperty(M)&&(K++,p=m[M],t=w[1]+c.childNodes[1].clientHeight,q=w[0]-c.childNodes[1].clientHeight,G=p*c.childNodes[1].clientHeight,G<t&&G>q&&(t=d.childNodes[p+1],A.push(t),T&&D$.push(h.childNodes[p+1])));for(M=0;M<A.length;M++){for(p=0;p<A[M].attributes.length;p++)d=D.r,A[M].attributes[p].nodeName==O&&(d=A[M].attributes[p].nodeValue,m.hasOwnProperty(d)&&(d=m[d],(0,D.ad)(A[M],0,0,"linear",w[1]-
d*v),T&&(D$[M].style.top=A[M].style.top,(0,D.ad)(D$[M],0,0,"linear",w[1]-d*v))));c.appendChild(A[M]);T&&b.appendChild(D$[M])}for(M=0;M<c.childElementCount;M++)if(d=0*M+"ms",M<e-1?(m=(0,window.parseInt)(g[f[M]].split("_")[1])*v,m<w[1]-M*v||(m=w[1]-(M-1)*c.childNodes[1].clientHeight),(0,D.ad)(c.childNodes[M+1],"400ms",d,"ease-in",m),T&&(0,D.ad)(b.childNodes[M+1],"400ms",d,"ease-in",m)):((0,D.ad)(c.childNodes[M+1],"400ms",d,"ease-in",0),T&&(0,D.ad)(b.childNodes[M+1],"400ms",d,"ease-in",0)),M==c.childElementCount-
2){c.childNodes[M].addEventListener("transitionend",function(){(0,window.setTimeout)(function(){if(T){var b=k.tc.firstChild;k.tc.firstChild=D.r;b.innerHTML="";b.appendChild(V);k.Ql=0}b=k.nb.firstChild;b.innerHTML="";b.appendChild(Q)},1E3)},D.u);break}};D.$c=function(b){return/^-{0,1}\d*\.{0,1}\d+$/.test(b)};
D.Zc=function(b,c){var d,e,f,g;d=[];e=b.fb().getMappedAttribute("key");for(f=0;f<c.childElementCount;f++)for(g=0;g<c.children[f].attributes.length;g++)if(c.children[f].attributes[g].nodeName==e){d.push(c.children[f].attributes[g].nodeValue);break}return d};
D.cd=function(b){function c(b){return b.replace(/\-([a-z])/gi,function(b,c){return c.toUpperCase()})}var d,e,f,g;d=" -moz- -webkit- -o- -ms- -khtml-".split(" ");e=window.document.documentElement;for(f=0;f<d.length;f++)if(g=c(d[f]+b),"Ms"==g.substr(0,2)&&(g="m"+g.substr(1)),g in e.style)return g};D.dd=function(b,c,d){"undefined"!=typeof c&&(b.style[c]=d)};
D.ad=function(b,c,d,e,f){(0,D.dd)(b,(0,D.cd)("transition-delay"),d);(0,D.dd)(b,(0,D.cd)("transition-timing-function"),e);(0,D.dd)(b,(0,D.cd)("transition-duration"),c);(0,D.dd)(b,(0,D.cd)("transform"),"translate3d(0,"+f+"px,0)")};D.Xc=function(b){return b.lastChild.firstChild};
return DvtDataGrid;
});