define(['./DvtToolkit', './DvtAxis'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.wa=(0,D.w)();(0,D.sa)("DvtGauge",D.wa);D.E.l(D.wa,D.Ha,"DvtGauge");D.wa.prototype.Init=function(b,c,d,e){D.wa.n.Init.call(this,b,c,d);this.fi=new D.Ia;e||(this.pa=this.Z5(),this.pa.Re(this),this.setId("gauge1000"+window.Math.floor(1E9*window.Math.random())),this.vz=new D.Ja(b,0,0),(0,D.Ka)(this.vz),this.j(this.vz));this.$y=D.t;this.zD=D.r};D.wa.prototype.Qd=function(b){this.S=b;D.I.Zh()||(this.S.animationOnDisplay="none",this.S.animationOnDataChange="none")};
D.wa.prototype.H=function(b,c,d){b?this.Qd(b):this.S||this.Qd(D.r);this.S.thresholds&&(this.S.thresholds=this.S.thresholds.sort(D.La));!(0,window.isNaN)(c)&&!(0,window.isNaN)(d)&&(this.Ob=c,this.Ab=d);c=this.Oy;this.Oy=[];d=new D.K(this.e);this.ya(d,0);this.zk(d,this.Ob,this.Ab);var e=b!=D.r,f=this.Ob,g=this.Ab;this.jb&&this.jb.stop();b=D.t;var h=this.$y?"none":this.Ha().animationOnDataChange,k=this.$y?"none":this.Ha().animationOnDisplay,m=this.Ha().animationDuration/1E3;if(k||h){f=new D.L(0,0,f,
g);g=this.e;if(!this.ba&&"none"!==k)this.jb=D.Ma.ZE(g,k,d,f,m),this.jb||(this.jb=this.qU(this.Oy,k,m));else if(this.ba&&"none"!=h&&e)if(this.jb=D.Ma.Dx(g,h,this.ba,d,f,m))b=D.o;else{e=this.Oy;h=[];for(k=0;k<c.length;k++){var f=e[k],p=c[k].pe(),g=f.pe();f.rf(p);p=new D.Da(this.e,f,m);(0,D.G)(p.M,"typeNumberArray",f,f.pe,f.rf,g);h.push(p)}this.jb=new D.Fa(this.e,h)}b||this.removeChild(this.ba);this.jb&&(this.jb.play(),this.jb.gd(this.aJ,this));b&&(this.Nk=this.ba);this.ba=d}this.vz&&(this.S.readOnly===
D.t&&D.I.$()?(this.vz.fa(this.Ob),this.vz.ua(this.Ab)):(this.vz.fa(0),this.vz.ua(0)));(0,D.Na)(d);(0,D.Oa)(d,"label",this.S.shortDesc)};D.wa.prototype.render=D.wa.prototype.H;D.D=D.wa.prototype;D.D.zk=(0,D.w)();D.D.qU=(0,D.ba)(D.r);D.D.Sv=(0,D.ba)(D.r);D.D.aJ=function(){this.Nk&&(this.removeChild(this.Nk),this.Nk=D.r);this.jb=D.r};D.D.Ha=(0,D.B)("S");D.D.Ca=(0,D.B)("pa");D.D.qN=function(b,c){this.$y=D.o;this.zD=this.S.value;this.YG(b,c)};
D.D.YG=function(b,c){this.S.value=D.Pa.yga(this.S,this.Sv(b,c));this.H();this.Ra(new D.Qa(this.zD,this.S.value,D.t))};D.D.pN=function(b,c){this.YG(b,c);this.Ra(new D.Qa(this.zD,this.S.value,D.o));this.$y=D.t;this.zD=D.r};D.D.Z5=function(){return new D.Ra(this)};D.La=function(b,c){return b.max&&c.max?window.Math.abs(b.max)-window.Math.abs(c.max):b.max?-window.Infinity:window.Infinity};
D.Ia=(0,D.w)();D.E.l(D.Ia,D.kp,"DvtGaugeBundle");D.Ia._defaults={EMPTY_TEXT:"No data to display"};D.Ia.prototype.zy=function(b){return D.Ia._defaults[b]};D.Ia.prototype.yy=(0,D.ba)("DvtGaugeBundle");
D.wu=(0,D.w)();D.E.l(D.wu,D.tr,"DvtGaugeDefaults");D.xu={skin:"alta",color:"#393737",metricLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};D.yu={skin:"skyros",min:0,max:100,color:"#313842",borderColor:D.r,visualEffects:"auto",emptyText:D.r,animationOnDataChange:"none",animationOnDisplay:"none",animationDuration:1E3,readOnly:"true",metricLabel:{rendered:"off",scaling:"auto",style:new D.P,textType:"number"},__layout:{outerGap:1,labelGap:3}};
D.wu.prototype.Init=function(b){b={skyros:D.Ic.qb(b.skyros,D.yu),alta:D.Ic.qb(b.alta,D.xu)};D.wu.n.Init.call(this,b)};D.uu=function(b){return"skyros"==b.Ha().skin};
D.Wa={};D.E.l(D.Wa,D.E,"DvtGaugeDataUtils");D.Wa.dt=function(b){b=b.Ha();return!b||(0,window.isNaN)(b.value)||b.value===D.r?D.t:D.o};D.Wa.G3=function(b){var c=b.Ha();b=c.value;c=c.thresholds;if(!c)return-1;for(var d=0;d<c.length;d++)if(b<=c[d].max)return d;return c.length-1};D.Wa.E3=function(b,c){var d=b.Ha().thresholds;return d&&0<=c&&c<d.length?d[c]:D.r};D.Wa.sHa=function(b,c){var d=b.Ha().referenceLines;return d&&0<=c&&c<d.length?d[c]:D.r};
D.Ra=function(b){this.Init(b.e,b.Ra,b);this.lh=b;this.ok=D.t};D.E.l(D.Ra,D.Bc,"DvtGaugeEventManager");D.D=D.Ra.prototype;D.D.yk=function(b){this.lh.Ha().readOnly===D.t?(this.ok=D.o,this.dc(),b=(0,D.Au)(this,b.pageX,b.pageY),this.lh.qN(b.x,b.y)):D.Ra.n.yk.call(this,b)};D.D.gm=function(b){this.ok?(this.ok=D.t,b=(0,D.Au)(this,b.pageX,b.pageY),this.lh.pN(b.x,b.y)):D.Ra.n.gm.call(this,b)};
D.D.Mr=function(b){if(this.ok){var c=(0,D.Au)(this,b.pageX,b.pageY);this.lh.YG(c.x,c.y)}(this.B7()||!this.ok)&&D.Ra.n.Mr.call(this,b)};D.D.B7=(0,D.ba)(D.t);
D.D.HG=function(b){if(D.dd.ud===b.type&&this.lh.Ha().readOnly===D.t){this.ok=D.o;var c=(0,D.Au)(this,b.touches[0].pageX,b.touches[0].pageY);this.lh.qN(c.x,c.y);b.preventDefault()}else D.dd.Og===b.type&&this.ok?(c=(0,D.Au)(this,b.touches[0].pageX,b.touches[0].pageY),this.lh.YG(c.x,c.y),b.preventDefault()):D.dd.Df===b.type&&this.ok?(this.ok=D.t,c=(0,D.Au)(this,b.changedTouches[0].pageX,b.changedTouches[0].pageY),this.lh.pN(c.x,c.y),b.preventDefault()):D.Ra.n.HG.call(this,b)};
D.Au=function(b,c,d){c=(0,D.Xg)(b.e,c,d);return b.lh.yb(c)};
D.tu={};D.E.l(D.tu,D.E,"DvtGaugeStyleUtils");D.tu.v9=["#ed6647","#fad55c","#68c182"];D.tu.rpa=["#D62800","#FFCF21","#84AE31"];D.tu.Fb=function(b){var c=b.Ha(),d=D.Wa.G3(b),e=D.Wa.E3(b,d);return e&&(!(b instanceof D.Aa)||b instanceof D.Aa&&"onIndicator"==c.thresholdDisplay)?D.tu.VK(b,e,d):c.color};D.tu.th=function(b){var c=b.Ha(),d=D.Wa.E3(b,D.Wa.G3(b));return d&&d.borderColor&&(!(b instanceof D.Aa)||b instanceof D.Aa&&"onIndicator"==c.thresholdDisplay)?d.borderColor:c.borderColor};
D.tu.Cia=function(b){var c=b.Ha(),d=D.Wa.G3(b),e=D.Wa.E3(b,d);return e&&(!(b instanceof D.Aa)||b instanceof D.Aa&&"onIndicator"!=c.thresholdDisplay)?D.tu.VK(b,e,d):c.plotArea.color};D.tu.VK=function(b,c,d){if(c.color)return c.color;if(d<D.tu.v9.length)return(0,D.uu)(b)?D.tu.rpa[d]:D.tu.v9[d]};
D.Pa={};D.E.l(D.Pa,D.E,"DvtGaugeRenderer");D.Pa.zW=2;D.Pa.e9=1;D.Pa.ly=function(b,c,d){var e=b.Ha(),f=e.emptyText;f||(f=(0,D.ct)(b.fi,"EMPTY_TEXT",D.r));var g=d.f-2*D.Pa.zW,h=d.g-2*D.Pa.e9;d=new D.le(b.e,f,d.x+d.f/2,d.y+d.g/2);e.metricLabel.style.q("font-size")||e.metricLabel.style.va("font-size","13px");d.Ka(e.metricLabel.style);d.jf();d.Zd();D.me.Yb(d,g,h,c)&&d.of()&&b.Ca().ha(d,new D.Ec(f))};
D.Pa.PA=function(b,c){var d=c.Ha(),e="percent"==d.metricLabel.textType;e&&(b=100*D.Pa.XE(d,d.min,b));var f=D.r;"on"==d.metricLabel.rendered&&d.metricLabel.converter&&(f=d.metricLabel.converter);var g=D.r;"on"==d.metricLabel.rendered&&d.metricLabel.scaling&&(g=d.metricLabel.scaling);return D.Pa.eba(b,c,f,g,d.metricLabel.autoPrecision?d.metricLabel.autoPrecision:"on",e)};
D.Pa.XR=function(b,c){var d=c.Ha(),e="percent"==d.tickLabel.textType;e&&(b=100*D.Pa.XE(d,d.min,b));var f=D.r;"on"==d.tickLabel.rendered&&d.tickLabel.converter&&(f=d.tickLabel.converter);var g=D.r;"on"==d.tickLabel.rendered&&d.tickLabel.scaling&&(g=d.tickLabel.scaling);return D.Pa.eba(b,c,f,g,d.tickLabel.autoPrecision?d.tickLabel.autoPrecision:"on",e)};
D.Pa.eba=function(b,c,d,e,f,g){var h=c.Ha();c=b;c=h.min;var h=h.max,k=h-c,m=D.r;(0,window.isNaN)(k)||(m=k/(1E3>k?100:1E3));e=new D.Cu(c,h,m,e,f);if(d&&d.getAsString)c=e.Gm(b,d);else{if(d&&d.format)return e.Gm(b,d);c=e.Gm(b)}return g?(0,window.String)(c)+"%":c};D.Pa.XE=function(b,c,d){b=(d-c)/(b.max-b.min);return b=window.Math.min(window.Math.max(0,b),1)};
D.Pa.L4=function(b,c,d,e){var f=b.Ha();if("on"==f.metricLabel.rendered){var g=D.Pa.PA(f.value,b),h=d.f,k=d.g,m=new D.le(b.e,g,d.x+d.f/2,d.y+d.g/2);m.Ka(f.metricLabel.style);var p=f.metricLabel.style.q("font-size");if(!f.metricLabel.style.q("font-size")){var p=window.Math.max(f.max.toString().length,f.min.toString().length,g.length),q="";"percent"==f.metricLabel.textType&&(p=window.Math.max(3,g.length),q+="%");for(f=0;f<p;f++)q+="0";m.sd(q);p=m.eF(d);m.sd(g);m.Af(p)}m.Zd();m.jf();e!=D.r&&m.ga(e);D.me.Yb(m,
h,k,c)&&m.of()&&b.Ca().ha(m,new D.Ec(g))}};D.Pa.yga=function(b,c){var d=(0,window.Number)(b.step);if(d&&0<d){var e=(c-b.min)/d;return 0.5<e?window.Math.max(window.Math.min(b.max,window.Math.ceil(e)*d+b.min),b.min):b.min}return c};
D.va=(0,D.w)();(0,D.sa)("DvtLedGauge",D.va);D.E.l(D.va,D.wa,"DvtLedGauge");D.xa=function(b,c,d,e){var f=new D.va;f.Init(b,c,d,e);return f};D.va.newInstance=D.xa;D.va.prototype.Init=function(b,c,d,e){D.va.n.Init.call(this,b,c,d,e);this.Fe=new D.ya};D.va.prototype.Qd=function(b){D.va.n.Qd.call(this,this.Fe.Gg(b));"auto"==this.S.animationOnDisplay&&(this.S.animationOnDisplay="zoom");"auto"==this.S.animationOnDataChange&&(this.S.animationOnDataChange="alphaFade");this.S.readOnly=D.o};
D.va.prototype.zk=function(b,c,d){D.za.H(this,b,c,d)};
D.ya=function(){this.Init({skyros:D.zu,alta:{}})};D.E.l(D.ya,D.wu,"DvtLedGaugeDefaults");D.zu={type:"circle"};
D.za={};D.E.l(D.za,D.E,"DvtLedGaugeRenderer");D.za.TEa=1/6;D.za.ppa="M8,86.6Q0,86.6,3.46,78.6L46,6.93Q50,0,54,6.93L96.54,78.6Q100,86.6,92,86.6Z";D.za.kpa="M0,86.6L50,0L100,86.6Z";D.za.qpa="M0,86.6L50,0L100,86.6Z";D.za.t9=[-13.05,-12.94,-50,-11.13,-21.06,11.9,-30.74,47.6,0.1,27.18,31.06,47.44,21.17,11.79,50,-11.39,13.05,-13.01,-0.06,-47.59];D.za.jpa=[-50,-11.22,-16.69,-17.94,0,-47.55,16.69,-17.94,50,-11.22,26.69,13.8,30.9,47.56,0,33.42,-30.9,47.56,-26.69,13.8];D.za.npa="M50,95L71,95Q74.414,94.414,75,91L75,60L92,60Q98.5,59.1,95,54L52,12Q50,11,48,12L5,54Q1.5,59.1,8,60L25,60L25,91Q25.586,94.414,29,95Z";
D.za.ipa="M75,98L75,58L97.5,58L50,11L2.5,58L25,58L25,98Z";D.za.opa="M75,98L75,58L97.5,58L50,11L2.5,58L25,58L25,98Z";
D.za.H=function(b,c,d,e){if(D.Wa.dt(b)){var f=b.Ha(),g=f.__layout.outerGap,h=f&&(0<=f.size||1>f.size)?window.Math.sqrt(f.size):1;d=new D.L(g+(d-2*g)*(1-h)/2,g+(e-2*g)*(1-h)/2,(d-2*g)*h,(e-2*g)*h);D.za.zJ(b,c,d);D.za.v0(b,c,d);"on"==f.metricLabel.rendered&&(f.metricLabel.style.q("color")!=D.r?D.Pa.L4(b,c,D.za.sba(b,d)):(e=D.tu.Fb(b),e=D.R.Uk(e),f.metricLabel.style.va("color",e),D.Pa.L4(b,c,D.za.sba(b,d),e)))}else D.Pa.ly(b,c,new D.L(0,0,d,e))};
D.za.zJ=function(b,c,d){var e=b.e,f=b.Ha(),g=f.type,h=D.tu.Fb(b),k=D.tu.th(b),m=d.x+d.f/2,p=d.y+d.g/2,q=window.Math.min(d.f,d.g)/2,s=(0,D.uu)(b);"rectangle"==g?e=new D.Ja(e,d.x,d.y,d.f,d.g):"diamond"==g?e=new D.$e(e,[m-q,p,m,p-q,m+q,p,m,p+q]):"triangle"==g?(m=s?D.za.ppa:D.za.kpa,e=new D.ad(e,m)):"star"==g?(m=s?D.za.t9:D.za.jpa,p=window.Math.min(d.f/100,d.g/100),m=D.Mm.scale(m,p,p),m=D.Mm.translate(m,d.x+d.f/2,d.y+d.g/2),e=new D.$e(e,m)):"arrow"==g?(m=s?D.za.npa:D.za.ipa,e=new D.ad(e,m)):e=new D.lc(e,
m,p,q);s||"none"==f.visualEffects?e.ga(h):(s=[D.R.Sf(h,-0.09,0.04),D.R.Sf(h,-0.04,-0.05)],m=f&&0==f.rotation%90?f.rotation:0,e.B(new D.Ke("arrow"==g||"star"==g||"triangle"==g?360-m:270,s,[1,1],[0,1])));k&&e.Ga(k);(f=f.shortDesc)&&b.Ca().ha(e,new D.Ec(D.r,f,h));e=D.za.WQ(b,c,e,d);c.j(e)};
D.za.WQ=function(b,c,d,e){var f=b.Ha(),g=f.type;if("triangle"==g||"arrow"==g){var h=new D.K(b.e);b=new D.K(b.e);c.j(h);h.j(b);b.j(d);f=f&&0==f.rotation%90?f.rotation:0;f="star"==g?0:f;g=new D.sd;g.rotate(window.Math.PI*(90-f)/180);d.na(g);g=b.v();g=window.Math.min(e.f/g.f,e.g/g.g);f=new D.sd;f.scale(g,g);b.na(f);f=h.v();b=e.x+e.f/2-(f.x+f.f/2);e=e.y+e.g/2-(f.y+f.g/2);f=new D.sd;f.translate(b,e);h.na(f);c.removeChild(h);if(c=d.Zb())c=c.clone(),c.fa(c.getWidth()/g),d.Q(c);return h}return d};
D.za.v0=function(b,c,d){var e=b.Ha(),f=e.type;"none"!=e.visualEffects&&(0,D.uu)(b)&&("rectangle"==f?D.za.rwa(b,c,d):"diamond"==f?D.za.qwa(b,c,d):"triangle"==f?D.za.twa(b,c,d):"star"==f?D.za.swa(b,c,d):"arrow"==f?D.za.owa(b,c,d):D.za.pwa(b,c,d))};
D.za.rwa=function(b,c,d){var e=0.05*d.f,f=0.05*d.g;d=new D.L(d.x+e,d.y+f,d.f-2*e,d.g-2*f);b=new D.Ja(b.e,d.x,d.y,d.f,d.g);b.ea(D.t);c.j(b);c=new D.Ke(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.B(c)};
D.za.qwa=function(b,c,d){var e=0.05*d.f,f=0.05*d.g,f=new D.L(d.x+e,d.y+f,d.f-2*e,d.g-2*f);d=f.x+f.f/2;e=f.y+f.g/2;f=window.Math.min(f.f,f.g)/2;b=new D.$e(b.e,[d-f,e,d,e-f,d+f,e,d,e+f]);b.ea(D.t);c.j(b);c=new D.Ke(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.B(c)};
D.za.twa=function(b,c,d){var e=0.05*d.f,f=0.05*d.g;d=new D.L(d.x+e,d.y+f,d.f-2*e,d.g-2*f);e=new D.ad(b.e,D.za.qpa);f=b.Ha();f=new D.Ke(360-(f&&0==f.rotation%90?f.rotation:0),["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);e.B(f);e=D.za.WQ(b,c,e,d);e.ea(D.t);c.j(e)};
D.za.owa=function(b,c,d){var e=0.05*d.f,f=0.05*d.g;d=new D.L(d.x+e,d.y+f,d.f-2*e,d.g-2*f);e=new D.ad(b.e,D.za.opa);f=b.Ha();f=new D.Ke(360-(f&&0==f.rotation%90?f.rotation:0),["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);e.B(f);e=D.za.WQ(b,c,e,d);e.ea(D.t);c.j(e)};
D.za.swa=function(b,c,d){var e=0.05*d.f,f=0.05*d.g;d=new D.L(d.x+e,d.y+f,d.f-2*e,d.g-2*f);var e=new D.ad(b.e,D.za.t9),f=b.Ha(),f=360-(f&&0==f.rotation%90?f.rotation:0),g=D.tu.Fb(b),g=[D.R.Xk(g,0.9),g,D.R.Gha(g)],f=new D.Ke(f,g,[1,1,1],[0.1,0.4,0.8]);e.B(f);e=D.za.WQ(b,c,e,d);e.ea(D.t);c.j(e)};
D.za.pwa=function(b,c,d){var e=0.05*d.f,f=0.05*d.g;d=new D.L(d.x+e,d.y+f,d.f-2*e,d.g-2*f);var e=d.x+d.f/2,f=d.y+d.g/2,g=window.Math.min(d.f,d.g)/2,h=new D.lc(b.e,e,f,g);h.ea(D.t);c.j(h);var k=new D.Um(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.25,0.5],[0.15,0.7,0.95],e,f-0.6*g,1.5*g,[d.x,d.y,d.f,d.g]);h.B(k);h=0.6*g;g*=0.4;f-=0.3*g;b=new D.Ym(b.e,e,f-g,h,g);b.ea(D.t);c.j(b);c=new D.Um(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.2,0.5],[0.6,0.8,1],e,f,h,[d.x,d.y,d.f,d.g]);b.B(c)};
D.za.sba=function(b,c){var d=b.Ha(),e=d.type,d=0==d.rotation%90?d.rotation:0,f=window.Math.min(c.f,c.g),g=c.x+c.f/2-f/2,h=c.y+c.g/2-f/2,k=f,m=f;"triangle"==e?0==d?(g+=0.05*f,h+=0.2*f,k-=0.3*f,m-=0.4*f):90==d?(g+=0.2*f,h+=0.25*f,k-=0.4*f,m-=0.3*f):180==d?(g+=0.25*f,h+=0.2*f,k-=0.3*f,m-=0.4*f):270==d&&(g+=0.2*f,h+=0.05*f,k-=0.4*f,m-=0.3*f):"arrow"==e?0==d?(g+=0.05*f,h+=0.2*f,k-=0.28*f,m-=0.4*f):90==d?(g+=0.2*f,h+=0.2*f,k-=0.4*f,m-=0.4*f):180==d?(g+=0.23*f,h+=0.2*f,k-=0.28*f,m-=0.4*f):270==d&&(g+=0.2*
f,h+=0.2*f,k-=0.4*f,m-=0.4*f):"star"==e?(g+=0.25*f,h+=0.25*f,k-=0.5*f,m-=0.4*f):"diamond"==e?(g+=0.15*f,h+=0.15*f,k-=0.3*f,m-=0.3*f):"rectangle"==e?(g+=0.1*f,h+=0.1*f,k-=0.2*f,m-=0.2*f):"circle"==e&&(g+=0.15*f,h+=0.15*f,k-=0.3*f,m-=0.3*f);return new D.L(g,h,k,m)};
D.Aa=(0,D.w)();(0,D.sa)("DvtStatusMeterGauge",D.Aa);D.E.l(D.Aa,D.wa,"DvtStatusMeterGauge");D.Aa.newInstance=function(b,c,d){var e=new D.Aa;e.Init(b,c,d);return e};D.D=D.Aa.prototype;D.D.Init=function(b,c,d){D.Aa.n.Init.call(this,b,c,d);this.Fe=new D.Ba;this.D9=D.r};D.D.Qd=function(b){D.Aa.n.Qd.call(this,this.Fe.Gg(b))};D.D.zk=function(b,c,d){D.Ca.H(this,b,c,d)};
D.D.qU=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.pe();"horizontal"==this.S.orientation?f.rf([g[0],g[0],g[2],g[3]]):f.rf([g[0],g[1],0,g[3],g[4]]);var h=new D.Da(this.e,f,d);(0,D.G)(h.M,"typeNumberArray",f,f.pe,f.rf,g);h.M.Mi(function(b){return(0,D.Ea)(b,0.7)});c.push(h)}return new D.Fa(this.e,c)};
D.D.Sv=function(b,c){if("horizontal"==this.S.orientation)return this.D9.TE(b);if("circular"==this.S.orientation){var d=D.Ga.H4(window.Math.atan2(c-this.Ab/2,b-this.Ob/2))-270,d=(d+720)%360;0<=d&&360>=d||(d=360<d?360-d<d-360?0:360:0-d<d?0:360);if(D.I.N(this.e))for(d=360-d;0>d;)d+=360;var e=this.S.min;return d/360*(this.S.max-e)+e}};
D.Ba=function(){this.Init({skyros:D.Gu,alta:D.Hu})};D.E.l(D.Ba,D.wu,"DvtStatusMeterGaugeDefaults");D.Hu={color:"#393737",metricLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},plotArea:{color:"#f5f6f7",borderColor:"#D6DFE6"}};D.Gu={color:"#313842",indicatorSize:1,metricLabel:{style:new D.P("color: #333333;")},orientation:"horizontal",plotArea:{color:"#AAAAAA",borderColor:"#C6C6C6",rendered:"auto"},thresholdDisplay:"onIndicator"};
D.Ca={};D.E.l(D.Ca,D.E,"DvtStatusMeterGaugeRenderer");D.Ca.H=function(b,c,d,e){if(D.Wa.dt(b)){var f=b.Ha(),g=f.__layout.outerGap;d=new D.L(g,g,d-2*g,e-2*g);"horizontal"==f.orientation?(D.Ca.Rq(b,c,d),D.Ca.zJ(b,c,d)):"circular"==f.orientation&&(f=window.Math.min(d.f,d.g),D.Pa.L4(b,c,new D.L(d.x+d.f/2-0.325*f,d.y+d.g/2-0.25*f,0.65*f,0.5*f)),D.Ca.Yva(b,c,d))}else D.Pa.ly(b,c,new D.L(0,0,d,e))};
D.Ca.Yva=function(b,c,d){var e=b.Ha(),f=0,g=e.value,h=e.thresholds,k=window.Math.min(d.f,d.g),m=0.3125*k,p=0.4625*k,q=1.5*window.Math.PI,f=2*f*window.Math.PI;if(h&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(var s=0;s<h.length;s++){var u=D.tu.VK(b,h[s],s),f=h[s].max?h[s].max:e.max,v=0==s?e.min:h[s-1].max,q=1.5*window.Math.PI+2*window.Math.PI*D.Pa.XE(e,e.min,v),f=D.Pa.XE(e,v,f),f=2*f*window.Math.PI;D.Ca.IY(b,c,d,q,f,m,p,u,D.t)}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&
"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(u=D.tu.Cia(b),q=1.5*window.Math.PI,f=2*window.Math.PI,D.Ca.IY(b,c,d,q,f,m,p,u,D.o));if((h=e.indicatorSize)&&1!=h)k*=0.075*(1-h),m+=k,p-=k;q=1.5*window.Math.PI;f=D.Pa.XE(e,e.min,g);f=2*f*window.Math.PI;D.Ca.IY(b,c,d,q,f,m,p,D.tu.Fb(b),D.t);if(m=e.referenceLines)for(p=0;p<m.length;p++)k=m[p].color?m[p].color:"black",h=m[p].lineWidth?m[p].lineWidth:2,q=m[p].lineStyle,g=m[p].value,window.angle=1.5*window.Math.PI+2*D.Pa.XE(e,e.min,g)*window.Math.PI,
D.Ca.fsa(b,c,d,k,h,q);d=new D.Ja(b.e,d.x,d.y,d.f,d.g);(0,D.Ka)(d);c.j(d);((c=e.shortDesc)||b.Ha().readOnly===D.t)&&b.Ca().ha(d,new D.Ec(D.r,c,D.tu.Fb(b)))};
D.Ca.zJ=function(b,c,d){var e=b.Ha(),f=D.I.N(b.e),g={layout:{}};g.layout.gapRatio=0;g.timeAxisType="disabled";g.position="bottom";g.min=e.min;g.max=e.max;g.dataMin=e.min;g.dataMax=e.max;g.tickLabel={rendered:"off"};g=(0,D.Eu)(b.e,g,d);b.D9=g;var h=0;0>e.max?h=e.max:0<e.min&&(h=e.min);var k=g.kj(h);"off"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&(k=g.Zc(e.min));var m=g.Zc(e.value),m=window.Math.max(d.x,window.Math.min(d.x+d.f,m)),p=0,p=0>e.min&&0>e.value?
g.Zc(e.min):g.Zc(e.max),p=window.Math.max(d.x,window.Math.min(d.x+d.f,p)),q=d.y,s=d.y+d.g,u=d.y+(1-e.indicatorSize)/2*d.g,v=d.y+d.g*(1-(1-e.indicatorSize)/2),z=D.o;m==k&&(z=D.t);var C=D.tu.th(b),F=e.plotArea.borderColor,H=e.thresholds;if(H&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(var J=H.length-1;0<=J;J--){var M=J,S=D.Ca.Bw(b,b.e,k,p,q,s,D.o),Q=new D.Za("pacp"+b.getId());if(M==H.length-1)f?(0,D.$a)(Q,g.Zc(e.max),0,d.f+2,s-q+2,0,0):(0,D.$a)(Q,0,0,d.f+2,s-q+2,0,0);else if(f){var W=
H[H.length-2-M].max==D.r?100:H[H.length-2-M].max;(0,D.$a)(Q,g.Zc(e.max),0,1*(e.max-W)/window.Math.abs(h-e.max)*d.f,s-q+2,0,0)}else(0,D.$a)(Q,0,0,1*H[M].max/window.Math.abs(h-e.max)*d.f,s-q+2,0,0);(0,D.ab)(S,Q);f&&(M=H.length-1-J);S.ga(D.tu.VK(b,H[M],M));S.Ga(F);D.Ca.Xea(b,c,S,D.tu.VK(b,H[M],M))}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(S=D.Ca.Bw(b,b.e,g.Zc(e.min),g.Zc(e.max),q,s,D.o),J=D.tu.Cia(b),S.ga(J),S.Ga(F),
D.Ca.Xea(b,c,S,J));J=D.Ca.Bw(b,b.e,f?k-0.5:k+0.5,f?m+0.5:m-0.5,u+0.5,v-0.5,D.o);b.Oy.push(J);f=D.tu.Fb(b);!(0,D.uu)(b)&&"none"!=e.visualEffects?(F=[D.R.Sf(f,-0.09,0.04),D.R.Sf(f,-0.04,-0.05)],F=new D.Ke(270,F,[1,1],[0,1]),J.B(F)):J.ga(f);C&&J.Ga(C);z&&c.j(J);J=D.Ca.Bw(b,b.e,k,m,u,v,D.o);D.Ca.v0(b,c,J,z);if(z=e.referenceLines)for(J=0;J<z.length;J++)f=z[J].color?z[J].color:"white",u=e.indicatorSize,k=((1-u)/2+u)*d.g,m=g.Zc(z[J].value),u=d.y+(1-u)/4*d.g,k=new D.Re(b.e,m,u,m,u+k),m=new D.re(f,1,z[J].lineWidth?
z[J].lineWidth:2),z[J].lineStyle&&m.va((0,D.Ns)(z[J].lineStyle)),k.Q(m),m=new D.vn(D.R.Gv(0,0,0,0.8),0.75,3,3,50,1,2,D.t,D.t,D.t),c.j(k),(0,D.qc)(k,m);d=new D.Ja(b.e,d.x,d.y,d.f,d.g);(0,D.Ka)(d);c.j(d);((c=e.shortDesc)||e.readOnly===D.t)&&b.Ca().ha(d,new D.Ec(D.r,c,f))};D.Ca.Bw=function(b,c,d,e,f,g,h){return new window.DvtStatusMeterGaugeIndicator(b,c,d,e,f,g,h)};
D.Ca.v0=function(b,c,d,e){if("none"!=b.Ha().visualEffects&&(0,D.uu)(b)){var f=new D.Ke(270,["#FFFFFF","#FFFFFF","#FFFFFF"],[0.5,0.3125,0],[0,0.3,1]);d.B(f);b.Oy.push(d);d.ea(D.t);e&&c.j(d)}};D.Ca.Xea=function(b,c,d,e){var f=b.Ha();d.ea(D.t);c.j(d);"none"!=f.visualEffects&&((0,D.uu)(b)?(b=[D.R.Xk(e,0.9),e,D.R.Gha(e)],b=new D.Ke(270,b,[1,1,1],[0,0.04,0.73])):(b=[D.R.Sf(e,-0.04,-0.05),D.R.Sf(e,-0.09,0.04)],b=new D.Ke(270,b,[1,1],[0,1])),d.B(b))};
D.Ca.Rq=function(b,c,d){var e=b.Ha(),f=D.I.N(b.e);e.metricLabel.style&&!e.metricLabel.style.q("font-size")&&e.metricLabel.style.va("font-size","13px");if("on"==e.metricLabel.rendered){var g=new D.le(b.e,"");g.Ka(e.metricLabel.style);if(!(D.me.Gi(g).g>d.g)){var h=e.__layout.labelGap,k;if(0<e.max||"off"!=e.plotArea.rendered||!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)){k=D.Pa.PA(0<e.max?e.max:e.min,b);k=new D.le(b.e,k);k.Ka(e.metricLabel.style);var m=k.Lb();k=f?d.x+m.f:d.x+d.f;
window.labelSpace=m.f;f&&(d.x+=m.f+h);d.f-=m.f+h}if(0>e.min&&"on"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)){m=D.Pa.PA(e.min,b);m=new D.le(b.e,m);m.Ka(e.metricLabel.style);m=m.Lb();if(0>e.value||0>=e.max)k=f?d.x+d.f:d.x+m.f,window.labelSpace=m.f;f||(d.x+=m.f+h);d.f-=m.f+h}e=D.Pa.PA(e.value,b);g.sd(e);g.aa(k);g.qa(d.y+d.g/2);g.Zd();g.zi();D.me.Yb(g,window.labelSpace,d.g,c)&&g.of()&&b.Ca().ha(g,new D.Ec(e))}}};
D.Ca.Zr=function(b,c,d){return{x:window.Math.cos(d)*c+b.f/2+b.x,y:window.Math.sin(d)*c+b.g/2+b.y}};D.Ca.IY=function(b,c,d,e,f,g,h,k,m){var p=b.e;D.I.N(b.e)&&(e=window.Math.PI-e-f,e=0<e?e:e+2*window.Math.PI);d=new D.Fu(p,d,e,f,g,h);b.Oy.push(d);d.ga(k);(b=D.tu.th(b))&&!m&&d.Ga(b);c.j(d)};
D.Ca.fsa=function(b,c,d,e,f,g){var h=window.angle,k=b.e,m=window.Math.min(d.f,d.g),p=0.275*m,m=0.5*m;D.I.N(b.e)&&(h=window.Math.PI-h,h=0<h?h:h+2*window.Math.PI);window.p1=D.Ca.Zr(d,p,h);window.p2=D.Ca.Zr(d,m,h);b=new D.Re(k,window.p1.x,window.p1.y,window.p2.x,window.p2.y);e=new D.re(e,1,f);g&&e.va((0,D.Ns)(g));b.Q(e);c.j(b)};
window.DvtStatusMeterGaugeIndicator=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.E.l(window.DvtStatusMeterGaugeIndicator,D.Ja,"DvtStatusMeterGaugeIndicator");window.DvtStatusMeterGaugeIndicator.Moa=2.5;window.DvtStatusMeterGaugeIndicator.prototype.Init=function(b,c,d,e,f,g,h){window.DvtStatusMeterGaugeIndicator.n.Init.call(this,c);this.lh=b;this.Dwa=h;(0,D.Bu)(this,d,e,f,g)};
D.Bu=function(b,c,d,e,f){b.Gk=c;b.pm=d;b.Cxa=e;b.Dxa=f;var g=window.Math.min(c,d);f-=e;(0,D.mo)(b,g,e,window.Math.abs(c-d),f);b.Dwa&&(c=f*((0,D.uu)(b.lh)?0.25:0.15),c>=window.DvtStatusMeterGaugeIndicator.Moa&&(0,D.bg)(b,c,c))};window.DvtStatusMeterGaugeIndicator.prototype.pe=function(){return[this.Gk,this.pm,this.Cxa,this.Dxa]};window.DvtStatusMeterGaugeIndicator.prototype.rf=function(b){b&&4==b.length&&(0,D.Bu)(this,b[0],b[1],b[2],b[3])};
D.Fu=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.E.l(D.Fu,D.ad,"DvtStatusMeterGaugeCircularIndicator");D.Fu.prototype.Init=function(b,c,d,e,f,g){D.Fu.n.Init.call(this,b);(0,D.Iu)(this,c,d,e,f,g)};
D.Iu=function(b,c,d,e,f,g){var h,k,m;c&&c instanceof D.L?b.Sa=c:c=b.Sa;b.yc=d;b.Rc=e;b.nh=f;b.Vg=g;e<2*window.Math.PI?(h=D.Ca.Zr(c,g,d),k=D.Ca.Zr(c,g,d+e),m=D.Ca.Zr(c,f,d+e),c=D.Ca.Zr(c,f,d),g=window.DvtPathUtils.moveTo(h.x,h.y)+window.DvtPathUtils.arcTo(g,g,e,1,k.x,k.y)+window.DvtPathUtils.lineTo(m.x,m.y)+window.DvtPathUtils.arcTo(f,f,e,0,c.x,c.y)+window.DvtPathUtils.closePath()):(h=D.Ca.Zr(c,g,d),k=D.Ca.Zr(c,g,d+e/2),m=D.Ca.Zr(c,f,d),c=D.Ca.Zr(c,f,d+e/2),g=window.DvtPathUtils.moveTo(h.x,h.y)+window.DvtPathUtils.arcTo(g,
g,e/2,1,k.x,k.y)+window.DvtPathUtils.arcTo(g,g,e/2,1,h.x,h.y),0<f&&(g+=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(f,f,e/2,0,m.x,m.y)+window.DvtPathUtils.arcTo(f,f,e/2,0,c.x,c.y)),g+=window.DvtPathUtils.closePath());b.tj(g)};D.Fu.prototype.pe=function(){return[this.Sa,this.yc,this.Rc,this.nh,this.Vg]};D.Fu.prototype.rf=function(b){b&&5==b.length&&(0,D.Iu)(this,b[0],b[1],b[2],b[3],b[4])};
D.cb=(0,D.w)();(0,D.sa)("DvtDialGauge",D.cb);D.E.l(D.cb,D.wa,"DvtDialGauge");D.cb.newInstance=function(b,c,d){var e=new D.cb;e.Init(b,c,d);return e};D.D=D.cb.prototype;D.D.Init=function(b,c,d){D.cb.n.Init.call(this,b,c,d);this.Fe=new D.db;this.LW=D.r};D.D.Qd=function(b){D.cb.n.Qd.call(this,this.Fe.Gg(b))};D.D.zk=function(b,c,d){D.eb.H(this,b,c,d)};
D.D.qU=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.pe(),h=D.eb.Kpa(this);f.pg(h);h=new D.Da(this.e,f,d);(0,D.G)(h.M,"typeNumberArray",f,f.pe,f.rf,g);h.M.Mi(function(b){return(0,D.Ea)(b,0.7)});c.push(h)}return new D.Fa(this.e,c)};
D.D.Sv=function(b,c){var d=D.Ga.H4(window.Math.atan2(c-this.LW.y,b-this.LW.x));0>=d&&(d+=360);var e=D.I.N(this.e),f=this.Ha().background,g=e?180+f.startAngle:360-f.startAngle,f=f.angleExtent,h=g+f;if(e){h=g;for(g-=f;0>g;)g+=360,h+=360}d+360>=g&&d+360<=h?d+=360:d>=g&&d<=h||(d=d>h?g+360-d<d-h?g:h:g-d<d+360-h?g:h);d=(d-g)/f;e&&(d=1-d);e=this.S.min;return d*(this.S.max-e)+e};
D.db=function(){this.Init({skyros:D.Du,alta:{}})};D.E.l(D.db,D.wu,"DvtDialGaugeDefaults");D.Du={background:{startAngle:180,angleExtent:180,indicatorLength:0.7},metricLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},tickLabel:{scaling:"auto",style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};
D.eb={};D.E.l(D.eb,D.E,"DvtDialGaugeRenderer");D.eb.H=function(b,c,d,e){D.Wa.dt(b)?(d=new D.L(0,0,d,e),D.eb.zJ(b,c,d),D.eb.Rq(b,c,d)):D.Pa.ly(b,c,new D.L(0,0,d,e))};
D.eb.zJ=function(b,c,d){var e=b.Ha(),f=D.eb.$X(b,d);c.j(f);e.background.majorTickCount&&e.background.radius&&D.eb.vwa(b,c,d);var g=D.eb.Fra(b,d),h=new D.K(b.e),k=new D.vu(b.e);c.j(h);h.j(k);k.j(g);var m=g.v(),p=D.eb.wba(b,e.value),f=D.eb.kba(b,d),q=D.eb.Qsa(b,m);d=D.eb.Rsa(b,d,m);m=new D.sd;m.translate(-q.x,-q.y);m.scale(d,d);g.na(m);k.pg(p);m=new D.sd;m.translate(f.x,f.y);h.na(m);b.Oy.push(k);((e=e.shortDesc)||b.Ha().readOnly===D.t)&&b.Ca().ha(c,new D.Ec(D.r,e));b.LW=f};
D.eb.$X=function(b,c){var d=b.Ha().background,e=D.I.N(b.e),f=D.I.$(),g=f?2*c.f:c.f,h=f?2*c.g:c.g,k=d.images;if(k&&0<k.length){var m,p,q,f=[];for(m=0;m<k.length;m++){var s="rtl"==k[m].dir;e&&s?f.push(k[m]):!e&&!s&&f.push(k[m])}k=0<f.length?f:k;for(m=0;m<k.length;m++){var u=k[m],s=u.src,f=u.width,u=u.height,v=s&&-1<s.search(".svg");0==m&&(p=f,q=u);if(v||f>=g&&u>=h||m==k.length-1){var g=new D.Xc(b.e,s,0,0,f,u),z=new D.sd,h=window.Math.min(c.f/f,c.g/u),k=(c.f-h*f)/2;m=(c.g-h*u)/2;z.scale(h,h);z.translate(k,
m);g.na(z);v&&D.I.qr()&&(s=D.He.Ii(b.e,s,D.E.Ai(g,g.OW)))&&g.OW(s);c.x+=k;c.y+=m;c.f=h*f;c.g=h*u;!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=e?c.x+c.f-c.f*d.anchorX/p:c.x+c.f*d.anchorX/p,d._anchorY=c.y+c.g*d.anchorY/q);d.metricLabelBounds&&(f={},f.width=c.f*d.metricLabelBounds.width/p,f.height=c.g*d.metricLabelBounds.height/q,f.y=c.y+c.g*d.metricLabelBounds.y/q,f.x=e?c.x+c.f-c.f*d.metricLabelBounds.x/p-f.width:c.x+c.f*d.metricLabelBounds.x/p,d._metricLabelBounds=f);e=window.Math.min(c.f/
p,c.g/q);d._radius=d.radius*e;d._tickLabelHeight=d.tickLabelHeight*c.g/q;d._tickLabelWidth=d.tickLabelWidth*c.f/p;return g}}}return D.r};
D.eb.Fra=function(b,c){var d=b.Ha().indicator,e=D.eb.qba(b,c),f=D.I.$()?2*e:e,g,h,k=d.images;if(k&&0<k.length)for(var m=0;m<k.length;m++){var p=k[m],e=p.src,q=p.width,p=p.height,s=e&&-1<e.search(".svg");0==m&&(g=q,h=p);if(s||p>=f||m==k.length-1)return f=new D.Xc(b.e,e,0,0,q,p),s&&D.I.qr()&&D.He.Ii(b.e,e,D.E.Ai(f,f.OW))&&(f.fa(q),f.ua(p)),!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=d.anchorX*q/g,d._anchorY=d.anchorY*p/h),f}return D.r};
D.eb.Kpa=function(b){var c=b.Ha().background;b=D.I.N(b.e)?180-c.startAngle:c.startAngle;return window.Math.PI*(90-b)/180};D.eb.wba=function(b,c){var d=b.Ha(),e=d.background,f=d.min,d=d.max;c=window.Math.max(window.Math.min(c,d),f);f=(c-f)/(d-f);d=D.I.N(b.e);return window.Math.PI*(90-((d?180-e.startAngle:e.startAngle)-f*(d?-e.angleExtent:e.angleExtent)))/180};
D.eb.kba=function(b,c){var d=b.Ha().background,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.N(e,d):new D.N(c.x+c.f/2,c.y+c.g/2)};D.eb.qba=function(b,c){var d=window.Math.min(c.f,c.g)/2;return b.Ha().background.indicatorLength*d};D.eb.Qsa=function(b,c){var d=b.Ha().indicator,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.N(e,d):new D.N(c.x+c.f/2,c.y+c.g)};D.eb.Rsa=function(b,c,d){return D.eb.qba(b,c)/d.g};
D.eb.Rq=function(b,c,d){var e=b.Ha();if("on"==e.metricLabel.rendered){var f=D.Pa.PA(e.value,b),g=d.x+d.f/2,h=d.y+d.g/2,k=d.f,m=d.g,p=e.background._metricLabelBounds;p&&(g=p.x+p.width/2,h=p.y+p.height/2,d.f=p.width,d.g=p.height);g=new D.le(b.e,f,g,h);!e.metricLabel.style.q("color")&&e.background._isDark&&e.metricLabel.style.va("color","#CCCCCC");g.Ka(e.metricLabel.style);h=(0,window.parseInt)(e.metricLabel.style.YE());if(!h){h=window.Math.max(D.Pa.PA(e.max,b).length,D.Pa.PA(e.min,b).length,f.length);
p="";"percent"==e.metricLabel.textType&&(h=window.Math.max(3,f.length),p+="%");for(e=0;e<h;e++)p+="0";g.sd(p);h=g.eF(d);g.sd(f);g.Af(h)}g.jf();g.Zd();D.me.Yb(g,k,m,c)&&g.of()&&b.Ca().ha(g,new D.Ec(f))}};
D.eb.vwa=function(b,c,d){var e=b.Ha(),f=D.I.N(b.e);if(e.background.radius&&e.background.majorTickCount){var g=e.background._radius,h=e.min,k=e.max,m=e.background.majorTickCount,p=12,q=new D.L(C,v,d.f,d.g),s=e.metricLabel.style.q("font-size");e.background._tickLabelHeight&&!s&&(q.g=e.background._tickLabelHeight);e.background._tickLabelWidth&&!s&&(q.f=e.background._tickLabelWidth);if(!s){var u=new D.le(b.e,"",C,v),p=window.Math.max(D.Pa.XR(e.max,b).length,D.Pa.XR(e.min,b).length),s="";"percent"==e.tickLabel.textType&&
(p=window.Math.max(3,D.Pa.XR(100,b).length-1),s+="%");for(C=0;C<p;C++)s+="0";u.sd(s);p=u.eF(q)}for(s=0;s<m;s++){C=h+window.Math.abs(k-h)*s/(m-1);f&&(C=h+window.Math.abs(k-h)*(m-1-s)/(m-1));var u=D.Pa.XR(C,b),v=D.eb.wba(b,C),z=D.eb.kba(b,d),C=z.x+g*window.Math.cos(v-window.Math.PI/2),v=z.y+g*window.Math.sin(v-window.Math.PI/2),u=new D.le(b.e,u,C,v);!e.tickLabel.style.q("color")&&e.background._isDark&&e.tickLabel.style.va("color","#CCCCCC");u.Ka(e.tickLabel.style);e.tickLabel.style.q("font-size")||
u.Af(p);u.jf();u.Zd();D.me.Yb(u,q.f,q.g,c)&&u.of()&&b.Ca().ha(u,new D.Ec(u.Sn))}}};
D.vu=function(b){this.Init(b)};D.E.l(D.vu,D.K,"DvtDialGaugeIndicator");D.vu.prototype.pg=function(b){var c=new D.sd;c.rotate(b);this.na(c);this.fqa=b};D.vu.prototype.pe=function(){return[this.fqa]};D.vu.prototype.rf=function(b){b&&1==b.length&&this.pg(b[0])};
D.Sa=(0,D.w)();(0,D.sa)("DvtRatingGauge",D.Sa);D.E.l(D.Sa,D.wa,"DvtRatingGauge");D.Sa.newInstance=function(b,c,d){var e=new D.Sa;e.Init(b,c,d);return e};D.Sa.prototype.Init=function(b,c,d){D.Sa.n.Init.call(this,b,c,d);this.Fe=new D.Ta};D.Sa.prototype.Qd=function(b){D.Sa.n.Qd.call(this,this.Fe.Gg(b))};
D.Sa.prototype.zk=function(b,c,d){var e=this.Ha().__layout.outerGap,f=this.S.max;this.fj=window.Math.min(d-2*e,(c-2*e)/f);this.Sa=new D.L((this.Ob-this.fj*f)/2,e,this.fj*f,this.Ab-2*e);D.Ua.H(this,b,c,d)};D.Sa.prototype.Sv=function(b){if(D.Wa.dt(this)){b=window.Math.max(window.Math.min(b,this.Sa.x+this.Sa.f),this.Sa.x);var c=0,c=D.I.N(this.e)?window.Math.max((this.Sa.x+this.Sa.f-b)/this.fj,this.S.min):window.Math.max((b-this.Sa.x)/this.fj,this.S.min);return D.Pa.yga(this.S,c)}return D.r};
D.Ya=function(b){(0,D.Xa)(b,b.S.value,"render")};D.Sa.prototype.qN=function(b,c){(0,D.Xa)(this,this.Sv(b,c),"hover")};D.Sa.prototype.YG=function(b,c){var d=this.Sv(b,c);(0,D.Xa)(this,d,"hover");this.Ra(new D.Qa(this.S.value,d,D.t))};D.Sa.prototype.pN=function(b,c){var d=this.S.value;this.S.value=this.Sv(b,c);this.S.changed=D.o;this.H();this.Ra(new D.Qa(d,this.S.value,D.t));this.Ra(new D.Qa(d,this.S.value,D.o))};
D.Xa=function(b,c,d,e){if(D.Wa.dt(b)){e||(e=b.ba);var f=D.I.N(b.e);c=window.Math.max(window.Math.min(c,b.S.max),0);var g=0,h=c*b.fj,k=c*b.fj;"render"==d&&(g=c*b.fj,h=0);f?(c=e.da(0),d=new D.Za("unsel"+b.getId()),(0,D.$a)(d,b.Sa.x,b.Sa.y,b.Sa.f-k,b.Sa.g),(0,D.ab)(c,d),c=e.da(1),d=new D.Za("sel"+b.getId()),(0,D.$a)(d,b.Sa.x+b.Sa.f-k,b.Sa.y,g,b.Sa.g),(0,D.ab)(c,d),e=e.da(2),g=new D.Za("hover"+b.getId()),(0,D.$a)(g,b.Sa.x+b.Sa.f-k,b.Sa.y,h,b.Sa.g)):(c=e.da(0),d=new D.Za("unsel"+b.getId()),(0,D.$a)(d,
b.Sa.x+k,b.Sa.y,b.Sa.f-k,b.Sa.g),(0,D.ab)(c,d),c=e.da(1),d=new D.Za("sel"+b.getId()),(0,D.$a)(d,b.Sa.x,b.Sa.y,g,b.Sa.g),(0,D.ab)(c,d),e=e.da(2),g=new D.Za("hover"+b.getId()),(0,D.$a)(g,b.Sa.x,b.Sa.y,h,b.Sa.g));(0,D.ab)(e,g)}};D.Sa.prototype.Z5=function(){return new D.bb(this)};
D.Ta=function(){this.Init({skyros:D.Ju,alta:D.Ku})};D.E.l(D.Ta,D.wu,"DvtRatingGaugeDefaults");D.Ku={unselectedState:{shape:"star",color:"#C4CED7",borderColor:D.r},selectedState:{shape:"star",color:"#F8C15A",borderColor:D.r},hoverState:{shape:"star",color:"#007CC8",borderColor:D.r},changedState:{shape:"star",color:"#ED2C02",borderColor:D.r}};
D.Ju={min:0,max:5,unselectedState:{shape:"star",color:"#F2F2F2",borderColor:"#B6B6B6"},selectedState:{shape:"star",color:"#F8C15A",borderColor:"#F5A700"},hoverState:{shape:"star",color:"#66A7DA",borderColor:"#4A86C5"},changedState:{shape:"star",color:"#F8C15A",borderColor:"#959595"},step:1};
D.Ua={};D.E.l(D.Ua,D.E,"DvtRatingGaugeRenderer");D.Ua.mN=["circle","diamond","rectangle","star"];
D.Ua.H=function(b,c,d,e){if(D.Wa.dt(b)){var f=b.Ha(),g=f.__layout.outerGap,h=f.max,k=window.Math.min(e-2*g,(d-2*g)/h);d=new D.L((d-k*h)/2,g,k*h,e-2*g);e={value:0,type:f.unselectedState.shape,color:f.unselectedState.color,borderColor:f.unselectedState.borderColor,visualEffects:f.visualEffects};var g={value:0,type:f.selectedState.shape,color:f.selectedState.color,borderColor:f.selectedState.borderColor,visualEffects:f.visualEffects},m={value:0,type:f.changedState.shape,color:f.changedState.color,borderColor:f.changedState.borderColor,
visualEffects:f.visualEffects},p={value:0,type:f.hoverState.shape,color:f.hoverState.color,borderColor:f.hoverState.borderColor,visualEffects:f.visualEffects};"dot"==f.unselectedState.shape&&(e.type="circle",e.visualEffects="none",e.size=0.05);var q=new D.K(b.e);c.j(q);var s=new D.K(b.e);c.j(s);var u=new D.K(b.e);c.j(u);(0,D.Xa)(b,f.value,"render",c);for(var v=0;v<h;v++){if("none"!=f.unselectedState.shape){var z=(0,D.xa)(b.e,D.r,D.r,D.o);q.j(z);(0,D.nc)(z,d.x+v*k,d.y+d.g/2-k/2);-1==D.Nd.Ba(D.Ua.mN,
e.type)&&(e.type="star");z.H(e,k,k)}f.changed?(z=(0,D.xa)(b.e,D.r,D.r,D.o),s.j(z),(0,D.nc)(z,d.x+v*k,d.y+d.g/2-k/2),-1==D.Nd.Ba(D.Ua.mN,m.type)&&(m.type="star"),z.H(m,k,k)):(z=(0,D.xa)(b.e,D.r,D.r,D.o),s.j(z),(0,D.nc)(z,d.x+v*k,d.y+d.g/2-k/2),-1==D.Nd.Ba(D.Ua.mN,g.type)&&(g.type="star"),z.H(g,k,k));z=(0,D.xa)(b.e,D.r,D.r,D.o);u.j(z);(0,D.nc)(z,d.x+v*k,d.y+d.g/2-k/2);-1==D.Nd.Ba(D.Ua.mN,p.type)&&(p.type="star");z.H(p,k,k)}h=new D.Ja(b.e,d.x,d.y,d.f,d.g);(0,D.Ka)(h);c.j(h);(c=f.shortDesc)&&b.Ca().ha(h,
new D.Ec(D.r,c))}else D.Pa.ly(b,c,new D.L(0,0,d,e))};
D.bb=function(b){this.Init(b.e,b.Ra,b);this.lh=b;this.wH=this.ok=D.t;this.lca=D.I.zd();this.$0=D.t};D.E.l(D.bb,D.Ra,"DvtRatingGaugeEventManager");D.D=D.bb.prototype;D.D.kn=function(b){if(this.lh.Ha().readOnly===D.t&&!this.wH){var c=(0,D.Au)(this,b.pageX,b.pageY),d=this.lh;(0,D.Xa)(d,d.Sv(c.x,c.y),"hover");this.ok=D.o}D.Ra.n.kn.call(this,b)};
D.D.xj=function(b){if(this.lh.Ha().readOnly===D.t){if(this.lca&&this.wH&&this.$0){this.$0=D.t;return}(0,D.Au)(this,b.pageX,b.pageY);(0,D.Ya)(this.lh);this.wH=D.t}D.Ra.n.xj.call(this,b)};D.D.yk=function(b){this.wH||(this.lh.Ha().readOnly===D.t?(this.ok=D.o,this.dc(),b=(0,D.Au)(this,b.pageX,b.pageY),this.lh.qN(b.x,b.y)):D.Ra.n.yk.call(this,b))};
D.D.gm=function(b){this.ok&&(this.lh.Ha().readOnly===D.t?(this.ok=D.t,b=(0,D.Au)(this,b.pageX,b.pageY),this.lh.pN(b.x,b.y),(0,D.Ya)(this.lh),this.wH=D.o,this.lca&&(this.$0=D.o)):D.Ra.n.gm.call(this,b))};D.D.B7=(0,D.ba)(D.o);
});