define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.qh=(0,D.w)();(0,D.sa)("DvtLegend",D.qh);D.E.l(D.qh,D.Ha,"DvtLegend");D.Jc=function(b,c,d){var e=new D.qh;e.Init(b,c,d);return e};D.qh.newInstance=D.Jc;D.qh.getDefaults=function(b){return(0,D.Yb)(new D.rh,b)};D.qh.prototype.Init=function(b,c,d){D.qh.n.Init.call(this,b,c,d);this.setId("legend1000"+window.Math.floor(1E9*window.Math.random()));this.Fe=new D.rh;this.Ja=new D.sh(this);this.Ja.Re(this);this.oh=[];this.XQ=[]};D.qh.prototype.Qd=function(b){b?this.S=this.Fe.Gg(b):this.S||(this.S=(0,D.Zb)(this))};
D.qh.prototype.Sx=function(b,c,d){this.Qd(b);this.Ha().isLayout=D.o;b=D.th.H(this,new D.L(0,0,c,d));this.Ha().isLayout=D.t;return b};D.qh.prototype.H=function(b,c,d){this.Qd(b);this.Ha().isLayout=D.t;this.bi();D.th.H(this,new D.L(0,0,c,d))};D.qh.prototype.render=D.qh.prototype.H;D.qh.prototype.Rl=function(b){(0,D.uh)(b,this.oh)};D.qh.prototype.highlight=D.qh.prototype.Rl;
D.qh.prototype.qf=function(b,c){var d=b.ta();if("categoryRollOver"==d||"categoryRollOut"==d){"dim"==this.Ha().hoverBehavior&&(0,D.Sd)(b,this.oh);for(var e=0;e<this.XQ.length;e++)for(var f=this.XQ[e],g=b.rl,g=g[0]?g[0]:g,h=0;h<f.oh.length;h++){var k=f.oh[h];if(k&&k.jg&&-1<D.Nd.Ba(k.jg(),g)){f.scrollIntoView(h);break}}}(this==c||"showPopup"==d||"hidePopup"==d)&&this.Ra(b)};D.qh.prototype.Ha=(0,D.B)("S");D.qh.prototype.Ca=(0,D.B)("Ja");D.qh.prototype.NW=function(b){this.oh.push(b)};
D.ph={};(0,D.sa)("DvtLegendConstants",D.ph);D.E.l(D.ph,D.E,"DvtLegendConstants");D.ph.FB="background";D.ph.BACKGROUND=D.ph.FB;D.ph.RB="legendItem";D.ph.LEGEND_ITEM=D.ph.RB;D.ph.Fo="title";D.ph.TITLE=D.ph.Fo;
D.rh=function(){this.Init({skyros:D.jD,alta:D.kD})};D.E.l(D.rh,D.tr,"DvtLegendDefaults");D.kD={skin:"alta",textStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"),titleStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333;"),colors:D.os};
D.jD={skin:"skyros",orientation:"vertical",position:D.r,backgroundColor:D.r,borderColor:D.r,textStyle:new D.P("font-size: 11px; color: #333333;"),titleStyle:new D.P("font-size: 12px; color: #003d5b;"),titleHalign:"start",hideAndShowBehavior:"none",hoverBehavior:"none",scrolling:"asNeeded",colors:D.ns,markerShape:"square",lineWidth:3,layout:{gapRatio:1,outerGapWidth:3,outerGapHeight:3,titleGap:3,markerSize:10,markerGap:5,rowGap:0,columnGap:8,sectionGap:6},isLayout:D.t};
D.hD=function(b,c){return window.Math.ceil(c*b.layout.gapRatio)};
D.sh=function(b){this.Init(b.e,b.qf,b);this.eb=b};D.E.l(D.sh,D.Bc,"DvtLegendEventManager");D.D=D.sh.prototype;D.D.Fr=function(b,c){var d=D.r;c instanceof D.Ec&&c.Ol()!=D.r?d=c.Ol():c instanceof D.fD&&(d=c.getId(),d={type:D.ph.RB,id:d});this.ug(new D.ub(b,d),this.eb)};D.D.Zf=function(b){D.sh.n.Zf.call(this,b);var c=(0,D.ye)(this,b.target);if(c){var d=this.FQ(c),c=(0,D.gD)(this,c);(d||c)&&b.stopPropagation()}};
D.D.kn=function(b){D.sh.n.kn.call(this,b);var c=(0,D.ye)(this,b.target);c&&this.qx(c,D.o)&&b.stopPropagation()};D.D.xj=function(b){D.sh.n.xj.call(this,b);var c=(0,D.ye)(this,b.target);c&&this.qx(c,D.t)&&b.stopPropagation()};D.D.Ht=function(b){var c=(0,D.ye)(this,b.target);if(c){b=b.Gka;var d=this.FQ(c),c=(0,D.gD)(this,c);(d||c)&&b&&b.preventDefault()}};D.D.qV=function(b){var c=(0,D.ye)(this,b.target);this.qx(c,D.o)&&b.stopPropagation()};
D.D.oV=function(b){var c=(0,D.ye)(this,b.target);this.qx(c,D.t)&&b.stopPropagation()};D.D.GM=function(b){var c=(0,D.ye)(this,b.target);this.qx(c,D.o)&&b.stopPropagation()};D.D.pV=function(b){var c=(0,D.ye)(this,b.target);this.qx(c,D.t)&&b.stopPropagation()};
D.D.FQ=function(b){if("none"==this.eb.Ha().hideAndShowBehavior)return D.t;var c=b.jg?b.jg():D.r;if(!c||0>=c.length)return D.t;for(var d=b.Be(),e=0;e<d.length;e++){var f=d[e];f instanceof D.Pd&&f.my(b.Fb())}c=c[0];b=b.getData();"hidden"==b.categoryVisibility?(b.categoryVisibility="visible",this.ug(new D.Cb(D.Cb.bC,c),this.eb)):(b.categoryVisibility="hidden",this.ug(new D.Cb(D.Cb.$v,c),this.eb));return D.o};D.gD=function(b,c){return c&&c.pv&&c.Ef?(b.ug(new D.Ab("action",c.Ef,c.getId()),b.eb),D.o):D.t};
D.sh.prototype.qx=function(b,c){if("none"==this.eb.Ha().hoverBehavior)return D.t;var d=b&&b.jg?b.jg():D.r;if(!d||0>=d.length)return D.t;this.ug(new D.kb(c?"categoryRollOver":"categoryRollOut",d[0]),this.eb);return D.o};
D.fD=function(b,c,d,e){this.Init(b,c,d,e)};D.E.l(D.fD,D.E,"DvtLegendObjPeer");D.fD.prototype.Init=function(b,c,d,e){this.eb=b;this.jh=c;this.sca=d;this.za=d.id?d.id:d.text;this.Ef=d.action;this.Xwa=d._spb;this.ne=e;if(this.Ef)for(b=0;b<this.jh.length;b++)this.jh[b].setCursor("pointer")};D.iD=function(b,c,d,e){if(!b||!d)return D.r;d=new D.fD(c,b,d,e);c.NW(d);for(e=0;e<b.length;e++)c.Ca().ha(b[e],d);return d};D.D=D.fD.prototype;D.D.getData=(0,D.B)("sca");D.D.Fb=function(){return this.sca.color};
D.D.getId=(0,D.B)("za");D.D.Be=(0,D.B)("jh");D.D.jg=function(){return[this.za]};D.D.Gd=(0,D.B)("ne");D.D.pv=(0,D.B)("Ef");D.D.od=(0,D.B)("Xwa");
D.th={};D.E.l(D.th,D.E,"DvtLegendRenderer");D.th.a9=10;D.th.Hoa=5;D.th.Ioa=2;D.th.Foa=6;
D.th.H=function(b,c){var d=b.Ha(),e=(0,D.hD)(d,d.layout.outerGapWidth),f=(0,D.hD)(d,d.layout.outerGapHeight),g=new D.L(c.x+e,c.y+f,c.f-2*e,c.g-2*f);if(0>=g.f)return new D.Xh(0,0);var h;d.isLayout||(h=D.th.$X(b,c));var k="vertical"==d.orientation?D.t:D.o,m=D.th.LQ(b,d.title,g,D.r);g.y+=m.g;g.g-=window.Math.floor(m.g);var p=D.th.hta(b),q="off"!==d.scrolling,g=k?D.th.ewa(b,g,p):D.th.wwa(b,g,p,q),k=(0,D.Dd)(m,g);if(0>=b.XQ.length){for(p=new D.K(b.e);0<b.xa();)p.j(b.da(0));b.j(p);p.F((c.f-k.f)/2-k.x)}h&&
b.ya(h,0);return d.isLayout?new D.Xh(window.Math.max(m.f,g.f)+2*e,k.g+2*f):new D.Xh(k.f+2*e,k.g+2*f)};D.th.$X=function(b,c){var d=b.Ha(),e;d.backgroundColor&&(e=e?e:new D.Ja(b.e,c.x,c.y,c.f,c.g),e.ga(d.backgroundColor));d.borderColor&&(e=e?e:new D.Ja(b.e,c.x,c.y,c.f,c.g),e.Ga(d.borderColor),(0,D.Mb)(e));e&&b.Ca().ha(e,new D.Ec(D.r,D.r,D.r,{type:D.ph.FB,id:D.n}));return e};
D.th.LQ=function(b,c,d,e){var f=b.Ha();if(!c)return new D.L(d.x,d.y,0,0);c=new D.le(b.e,c,d.x,d.y);var g=e&&e.titleStyle?new D.P(e.titleStyle):f.titleStyle;c.Ka(g);if(D.me.Yb(c,d.f,d.g,b)){b.Ca().ha(c,new D.Ec(c.Sn,D.r,D.r,{type:D.ph.Fo,id:D.n}));var g=c.Lb(),h=(0,D.hD)(f,f.layout.titleGap);f.isLayout?b.removeChild(c):(0,D.ip)(d,e&&e.titleHalign?e.titleHalign:f.titleHalign,c,g.f);g.g+=h;return g}return new D.L(d.x,d.y,0,0)};
D.th.cP=function(b,c){var d=b.sections;c.push(b);if(d)for(var e=0;e<d.length;e++)D.th.cP(d[e],c)};D.th.wwa=function(b,c,d,e){for(var f=b.Ha(),g=D.th.bra(b,c,d,e),h=[],k=0;k<f.sections.length;k++)D.th.cP(f.sections[k],h);var m=h.length,f=(0,D.hD)(f,f.layout.sectionGap);c=c.clone();for(var p=D.r,q,k=0;k<h.length;k++)c.g=g[k],q=D.th.yJ(b,h[k],k,c,d,e),k!=m-1&&h[k].items&&(c.y+=q.g+f),p=p?(0,D.Dd)(p,q):q;return p};
D.th.ewa=function(b,c,d){for(var e=b.Ha(),f=D.I.N(b.e),g=0,h=[],k=0;k<e.sections.length;k++)D.th.cP(e.sections[k],h);for(var m=h.length,p=0,k=0;k<h.length;k++)h[k].items&&(p+=h[k].items.length);var q=(0,D.hD)(e,e.layout.sectionGap),s=c.f-q*(m-1),u,v;if(e.sections)for(var z=0,C=0,k=0;k<m;k++)e=c.clone(),(u=h[k].items)?(u=window.Math.round(u.length/p*s),e.f=u,e.x=f?c.x+c.f-g-e.f:c.x+g,0<z&&(e.y+=C,e.g-=C),u=D.th.yJ(b,h[k],k,e,d,D.t),0<z&&(e.g+=C,z--),g+=u.f,k!=m-1&&(g+=q)):(e.f=c.f-g,e.x=f?c.x:c.x+
g,u=D.th.yJ(b,h[k],k,e,d,D.t),C=u.g,z=h[k].sections.length),v=v?(0,D.Dd)(v,u):u;return v};
D.th.yJ=function(b,c,d,e,f,g){if(c){var h=e.clone(),k=b.Ha(),m=b.e,p=h.y,q=k.layout.markerSize,s=(0,D.hD)(k,k.layout.markerGap),u=(0,D.hD)(k,k.layout.rowGap),v=(0,D.hD)(k,k.layout.columnGap),z=D.th.LQ(b,c.title,h,c);h.y+=z.g;if(c.items){h.g-=z.g;var p=p+z.g,C=D.th.cra(b,h,f,c.items,g),F=C.numCols,H=C.numRows,J=C.width;h.g=window.Math.ceil(window.Math.min(h.g,H*(f+u)-u)+z.g);h.f=J*F+v*(F-1);if(k.isLayout){if(1==H){for(d=e=0;d<c.items.length;d++)g=c.items[d],J=window.Math.ceil(D.th.VC(b,g.text)),e+=
J+q+s+v;h.f=e-v}return h}if(0==H||0==F)return h;var M=D.r,S=b,Q=H*(f+u)-u+z.g,C=c.items.length;"vertical"===k.orientation&&(g&&Q>h.g)&&(S=D.th.Era(b,m,h,d),M=D.th.Kra(b,m,h,S,Q,C),b.XQ.push(M));var Q=J-q-s,W=D.I.N(b.e),Y=0,la=1;if(1==H){for(d=M=0;d<C;d++)g=c.items[d],J=window.Math.ceil(D.th.VC(b,g.text)),J<Q&&(M+=Q-J);for(d=0;d<C;d++){g=c.items[d];var oa=W?h.x+h.f-q:h.x,ma=W?h.x+h.f-q-s:h.x+q+s,mb=D.th.laa(b,oa,h.y,f,q,g,d),hb=g.text,J=window.Math.ceil(D.th.VC(b,g.text)),Va=D.r;hb&&(J<Q?Va=D.th.cY(b,
m,h,Q,hb,k.textStyle):(Va=D.th.cY(b,m,h,Q+M,hb,k.textStyle),Va!=D.r&&(J=window.Math.ceil(D.th.VC(b,Va.Md())),M-=Q-J)),J=Va!=D.r?window.Math.ceil(D.th.VC(b,Va.Md())):0,Va&&(Va.aa(ma),Va.qa(h.y+f/2),W&&Va.zi()));b.j(mb);J=J+q+s;oa=window.Math.min(oa,ma);ma=la==F?J:J+v;oa=new D.Ja(m,oa,h.y,ma,f);(0,D.Ka)(oa);S.j(oa);ma=Va!=D.r?Va.Sn:D.r;Va=(0,D.iD)([oa,mb,Va],b,g,ma);"hidden"==g.categoryVisibility&&Va&&mb.my(Va.Fb());h.y+=f+u;Y++;Y===H&&la!==F&&(h.y=p,W?h.f-=J+v:h.x+=J+v,Y=0,la++)}}else for(d=0;d<C;d++){g=
c.items[d];oa=W?h.x+h.f-q:h.x;ma=W?h.x+h.f-q-s:h.x+q+s;mb=D.th.laa(b,oa,h.y,f,q,g,d);hb=g.text;Va=D.r;if(hb&&(Va=D.th.cY(S,m,h,Q,hb,k.textStyle)))Va.aa(ma),Va.qa(h.y+f/2),W&&Va.zi();S.j(mb);oa=window.Math.min(oa,ma);ma=la==F?J:J+v;oa=new D.Ja(m,oa,h.y,ma,f);(0,D.Ka)(oa);S.j(oa);ma=Va!=D.r?Va.Sn:D.r;Va=(0,D.iD)([oa,mb,Va],b,g,ma);M&&Va instanceof D.fD&&M.NW(Va);"hidden"==g.categoryVisibility&&Va&&mb.my(Va.Fb());h.y+=f+u;Y++;Y===H&&la!==F&&(h.y=p,W?h.f-=J+v:h.x+=J+v,Y=0,la++)}h.y=p+h.g-z.height;return new D.L(e.x,
p-z.height,e.f,h.g)}h.g=z.g}};
D.th.bra=function(b,c,d,e){var f=b.Ha(),g=f.isLayout;f.isLayout=D.o;for(var h=0,k=0,m=c.x,p=c.y,q=[],s=0;s<f.sections.length;s++)D.th.cP(f.sections[s],q);for(var u=q.length,v=(0,D.hD)(f,f.layout.sectionGap),z=c.g-v*(u-1),C=c.f,F=[],H,s=0;s<u;s++)c.g=z,c.f=C,H=D.th.yJ(b,q[s],s,c,d,e),F[s]=H.g;window.arSectionSpaceNeeded=[];window.extraSpace=window.numShortSections=0;H=z/u;for(s=0;s<u;s++)z=F[s]-H,0>=z?(window.arSectionSpaceNeeded[s]=0,window.extraSpace-=z):(F[s]=H,window.arSectionSpaceNeeded[s]=z,
window.numShortSections++);for(;0<window.extraSpace&&0<window.numShortSections;){H=window.extraSpace/window.numShortSections;for(s=0;s<u;s++)0<window.arSectionSpaceNeeded[s]&&(z=window.arSectionSpaceNeeded[s]-H,0>=z?(F[s]+=window.arSectionSpaceNeeded[s],window.arSectionSpaceNeeded[s]=0,window.extraSpace-=H+z,window.numShortSections--):(F[s]+=H,window.extraSpace-=H,window.arSectionSpaceNeeded[s]=z))}c.x=m;c.y=p;c.f=C;for(s=0;s<u;s++)c.g=F[s],D.th.yJ(b,q[s],s,c,d,e),c.x=m,k=window.Math.max(c.f,k),h+=
c.g,s!=u-1&&(c.y=c.g+p+v,h+=v);c.f=k;c.g=h;c.x=m;c.y=p;f.isLayout=g;return F};
D.th.cra=function(b,c,d,e,f){for(var g=b.Ha(),h=0,k=0;k<e.length;k++){var m=D.th.VC(b,e[k].text);m>h&&(h=m)}b=g.layout.markerSize;var p=(0,D.hD)(g,g.layout.markerGap),k=(0,D.hD)(g,g.layout.rowGap),m=(0,D.hD)(g,g.layout.columnGap),h=g.isLayout?window.Math.ceil(b+p+h):c.f;"vertical"==g.orientation?f?(g=1,f=e.length):(f=window.Math.min(window.Math.floor((c.g+k)/(d+k)),e.length),g=window.Math.ceil(e.length/f)):(g=window.Math.min(window.Math.floor(c.f/h),e.length),f=window.Math.ceil(((h+m)*e.length-m)/
c.f),f*(d+k)-k>c.g&&(f=window.Math.floor(window.Math.ceil(c.g+k)/(d+k)),g=window.Math.ceil(e.length/f)));c=window.Math.min(h,(c.f-m*(g-1))/g);return c<b?{width:0,height:0,numCols:0,numRows:0}:{width:c,numCols:g,numRows:f}};D.th.hta=function(b){var c=b.Ha();b=new D.le(b.e,"Test");b.Ka(c.textStyle);b.Zd();b=D.me.Gi(b);return window.Math.ceil(window.Math.max(b.g,c.layout.markerSize))};D.th.VC=function(b,c){var d=b.Ha(),e=new D.le(b.e,c);e.Ka(d.textStyle);return e.Lb().f};
D.th.cY=function(b,c,d,e,f,g){c=new D.le(c,f);c.Zd();c.Ka(g);return c=D.me.Yb(c,e,d.g,b)?c:D.r};
D.th.laa=function(b,c,d,e,f,g,h){var k=b.Ha();g.markerShape||(g.markerShape=k.markerShape);if(!g.color){var m=k.colors;g.color=m[h%m.length]}g.lineWidth||(g.lineWidth=k.lineWidth);"line"==g.type?(g.lineWidth=window.Math.min(g.lineWidth,D.th.Hoa),f=D.th.maa(b.e,c,d,e,g)):"lineWithMarker"==g.type?(g.lineWidth=window.Math.min(g.lineWidth,D.th.Ioa),f=D.th.maa(b.e,c,d,e,g),"hidden"!=g.categoryVisibility&&f.j(D.th.oaa(b,c,d,e,D.th.Foa,g))):f=D.th.oaa(b,c,d,e,f,g);return f};
D.th.oaa=function(b,c,d,e,f,g){var h=b.e,k=b.Ha();b=g.markerShape;var m=g.markerColor?g.markerColor:g.color,p=g.pattern;d+=(e-f)/2;c="lineWithMarker"==g.type?c+(D.th.a9-f)/2:c;p?(f=new D.Pd(h,b,k.skin,0,0,f,f),f.B(new D.cf(p,m,"#FFFFFF")),(0,D.nc)(f,c,d)):(f=new D.Pd(h,b,k.skin,c,d,f,f),f.ga(m));g.borderColor&&f.Ga(g.borderColor);"square"==b&&(0,D.Mb)(f);return f};
D.th.maa=function(b,c,d,e,f){d+=e/2;b=new D.Re(b,c,d,c+D.th.a9,d);c=new D.re(f.color,1,f.lineWidth);f=f.lineStyle;"dashed"==f?c.dl((0,D.Ns)(f),"4,2,4"):"dotted"==f&&c.dl((0,D.Ns)(f),"2");b.Q(c);(0,D.Mb)(b);return b};D.th.Era=function(b,c,d,e){var f=[d.x,d.y,d.x+d.f,d.y+d.g];d=d.clone();e=b.getId()+"_"+e;c=new D.sr(c,"legendHandler",f,d,e);b.j(c);return c};D.th.Kra=function(b,c,d,e,f,g){c=new D.jr(c,d.x,d.y,d.f,d.g,f,e,g);c.TF(b.Ca().al());b.j(c);e.H();return c};
});