define(['./DvtToolkit', './DvtPanZoomCanvas', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Fc=function(b,c,d){this.Init(b,c,d)};(0,D.sa)("DvtAmxThematicMap",D.Fc);D.E.l(D.Fc,D.K,"DvtAmxThematicMap");D.Fc.dw=10;D.Fc.prototype.Init=function(b,c,d){D.Fc.n.Init.call(this,b);this.I=new D.Gc(b,c,d);this.mR=new D.K(b);this.mR.j(this.I);this.j(this.mR);this.Fe=new D.Hc};D.Fc.newInstance=function(b,c,d){return new D.Fc(b,c,d)};D.Fc.newInstance=D.Fc.newInstance;D.Fc.prototype.H=function(b,c,d){this.S=this.Fe.Gg(b);this.O=c;this.T=d;c=new D.L(0,0,c,d);this.xJ(this,c);this.I.H(b,c.f,c.g)};
D.Fc.prototype.render=D.Fc.prototype.H;
D.Fc.prototype.xJ=function(b,c){this.eb&&(b.removeChild(this.eb),this.eb=D.r);var d=new D.L(D.Fc.dw,D.Fc.dw,c.f-2*D.Fc.dw,c.g-2*D.Fc.dw),e=this.S,f=e.legend.rendered,g=e.legend.scrolling,h=D.Ic.clone(e.legend);this.RW(this.S,h);if(f&&!(h.rDa&&0==h.rDa.length)){f=e.legend.position;delete h.position;h.layout.gapRatio=this.Ix();h.hideAndShowBehavior="none";h.rolloverBehavior="none";h.scrolling=e.legend.scrolling;var k=(0,D.Jc)(this.I.e,D.r,D.r);this.I.getId()!=D.r&&k.setId(this.I.getId()+"legend");b.j(k);
"auto"==f&&"asNeeded"!==g?f="bottom":"auto"==f&&"asNeeded"==g&&(f="end");g=D.I.N(b.e);"start"==f?f=g?"right":"left":"end"==f&&(f=g?"left":"right");h.orientation="left"==f||"right"==f?"vertical":"horizontal";g="top"==f||"bottom"==f;g=k.Sx(h,g?d.f:e.layout.legendMaxSize*d.f,g?e.layout.legendMaxSize*d.g:d.g);if(0<g.f&&0<g.g)switch(k.H(h,g.f,g.g),this.eb=k,e=window.Math.ceil(e.layout.legendGap*this.Ix()),(0,D.Kc)(d,f,k,g.f,g.g,e),f){case "top":this.mR.R(g.g+D.Fc.dw);case "bottom":c.g-=g.g+D.Fc.dw;break;
case "left":this.mR.F(g.f+D.Fc.dw);case "right":c.f-=g.f+D.Fc.dw}}};D.Fc.prototype.Ix=function(){if(this.S.layout.gapRatio!==D.r&&!(0,window.isNaN)(this.S.layout.gapRatio))return this.S.layout.gapRatio;var b=window.Math.min(this.O/400,1),c=window.Math.min(this.T/300,1);return window.Math.min(b,c)};
D.Fc.prototype.RW=function(b,c){c.title=b.legend?b.legend.title:D.r;c.sections=[];if(b&&b.legend&&b.legend.sections)for(var d=0;d<b.legend.sections.length;d++){var e=b.legend.sections[d];e&&c.sections.push({title:e.title,items:e.items,sections:e.sections})}return c};
D.Gc=function(b,c,d){this.Init(b,c,d)};(0,D.sa)("DvtThematicMap",D.Gc);D.E.l(D.Gc,D.Lc,"DvtThematicMap");
D.Gc.prototype.Init=function(b,c,d){D.Gc.n.Init.call(this,b);this.Na=c;this.ca=d;(0,D.Mc)(this);this.Vd=[];this.qu=[];this.lD=this.Fn=this.cc=this.eb=D.r;this.HN=D.t;this.IC=[];this.dD={};this.GQ=D.t;this.SO={};this.NX={};this.wl=[];this.bX=new D.K(this.e);this.NH=new D.K(this.e);this.ju=new D.K(this.e);this.ts=new D.K(this.e);this.tP=D.t;this.JD=this.Bx=D.o;this.q_=6;this.Iq=D.o;this.fE={};this.Rj=16777215;this.Fe=new D.Hc};D.Gc.newInstance=function(b,c,d){return new D.Gc(b,c,d)};
D.Gc.prototype.Qd=function(b){this.S=this.Fe.Gg(b);D.I.Zh()||(this.S.animationOnDisplay="none",this.S.animationOnMapChange="none",this.S.animationOnDrill="none");this.S.skin||(this.S.skin="alta")};D.Gc.prototype.H=function(b,c,d){b&&"object"==typeof b&&this.Qd(b);D.Gc.n.H.call(this,b,c,d)};D.Gc.prototype.render=D.Gc.prototype.H;D.Nc=function(b,c){for(var d=0;d<b.Vd.length;d++)if(b.Vd[d].af==c)return b.Vd[d]};D.D=D.Gc.prototype;D.D.io=function(b){this.Sr=(0,window.parseFloat)(b)};D.D.La=(0,D.B)("Sr");
D.D.sB=function(b){this.Ug=(0,window.parseInt)(b);D.Gc.n.sB.call(this,this.Ug);b=this.Rj;if(1==this.Ug||3==this.Ug||5==this.Ug||7==this.Ug)b&=-17,this.JD=D.t;if(2==this.Ug||3==this.Ug||6==this.Ug||7==this.Ug)b&=-4098,this.Bx=D.t;if(4==this.Ug||5==this.Ug||6==this.Ug||7==this.Ug)b&=-257;this.Rj=b};D.D.KT=function(b){this.Xi=b;this.pa.KT(b)};D.D.oL=function(b,c,d,e){this.S?(new D.Oc(this)).parse(this.S):b==D.r||0==b.length||D.Gc.n.oL.call(this,b,c,d,e)};
D.D.zV=function(b,c){this.Ag=D.t;this.Mva&&(this.Vd=[],this.IC=[],this.dD={},this.SO={},this.NX={},this.wl=[],this.removeChild(this.cc),this.lD=this.Fn=this.eb=this.cc=D.r,this.sB(0),this.Rj=16777215,this.JD=this.Bx=D.o,this.yD=this.ub,this.bX=new D.K(this.e),this.NH=new D.K(this.e),this.ju=new D.K(this.e),this.ts=new D.K(this.e),(0,D.Mc)(this));this.pa.dc();this.rG().XS(c)};D.Mc=function(b){b.pa=new D.Pc(b.e,b.Ra,b);b.pa.Re(b);D.I.$()?b.JZ=D.r:(b.JZ=new D.Qc(b,b.pa),(0,D.Rc)(b.pa,b.JZ))};D.D=D.Gc.prototype;
D.D.gma=function(b){D.I.N(this.e)||(b=this.O-5-b.getWidth(),this.cc.F(b))};
D.D.xJ=function(){if(this.Fn){this.cc&&(this.cc.W(),this.removeChild(this.cc));var b="true"==this.Fn.k("disclosed"),c="fixed"==this.Fn.k("display")||D.I.ht();if(!c||b){var d=this.Fn.k("maxWidth"),e=d.indexOf("%"),d=-1!=e?(0,window.parseFloat)(d.substring(0,e))/100*this.O:(0,window.parseFloat)(d),e=this.T-10;if("alta"==this.Sc)this.cc=new D.Sc(this.e,D.r,this,"pd"),this.cc.J("dvtPanelDrawerEvent",this.W6,D.t,this),this.cc.Wm(d),this.cc.PF(e),this.cc.Ju=c,D.I.N(this.e)?(this.cc.yq="right",this.cc.F(0)):
this.cc.F(this.O);else{this.cc=new D.Tc(this.e,d,e,f,this.lD,this.gr(),b,c);this.cc.J("dvtCollapsiblePanelEvent",this.W6,D.t,this);this.cc.J("dvtResizeEvent",this.gma,D.t,this);var d=this.Fn.k("expandTooltip"),e=this.Fn.k("collapseTooltip"),f=D.I.N(this.e)?"col_northwest":"col_northeast",f=this.cc;f.yz=d;f.kz=e}this.eb=new D.DvtCommonLegend(this.e,this.cc.i3(),this.cc.h3(),this.lD,this.XZ);this.eb.VT(this.Fn);this.j(this.cc);this.j(this.eb);this.eb.H();var g;if("alta"==this.Sc){f=this.eb.v();(0,D.Wc)(this.cc,
f.g);this.removeChild(this.eb);var f=new D.Xc(this.e,(0,D.Yc)(this).legendEna,0,0,24,24),d=new D.Xc(this.e,(0,D.Yc)(this).legendOvr,0,0,24,24),e=new D.Xc(this.e,(0,D.Yc)(this).legendDwn,0,0,24,24),h=(0,D.Yc)(this).legendTip;(0,D.Zc)(this.cc,this.eb,f,d,e,h,"legend");this.cc.Li();b&&this.cc.Xe(D.o,D.o)}else g=this.cc,b=this.eb,g.dd.j(b),b.J("dvtResizeEvent",g.wma,D.t,g),f=g.dd.v(),b=f.f+10,f=f.g+10,g.T=f,g.O=b,g.Xa?(g.Xa.tj((0,D.$c)(g,b,f)),b="col_northwest"==g.Kh||"col_southwest"==g.Kh,g.Ff&&b&&g.Ff.F(g.O)):
(b=new D.ad(g.e,(0,D.$c)(g,b,f)),f=g.A.borderAlpha,b.ga(g.cu,g.Ui),b.Ga(g.oq,f),g.Xa=b,g.ya(g.Xa,0),g.Ju||(g.Ff=D.cd.Y1(g.e,25,g.A,D.t),g.Ff.u(g.A.borderAlpha),g.j(g.Ff),g.Wi=g.isCollapsed()?D.O.LR(g.e,g.ag,25,g.A,D.t):D.O.JR(g.e,g.ag,25,g.A,D.t),g.Ff.j(g.Wi),"col_northwest"==g.Kh||"col_southwest"==g.Kh||(g.Ff.R(25),g.Ff.Ni(-window.Math.PI)),D.I.N(g.e)&&g.Ff.F(g.O),D.I.$()?g.Wi.J(D.dd.ud,g.VB,D.t,g):(g.Wi.J(D.ed,g.VB,D.t,g),g.Wi.J(D.fd,g.JV,D.t,g),g.Wi.J(D.gd,g.IV,D.t,g)))),g.oO&&(0,D.id)(g,D.t),
g=this.cc.v(),b=D.I.N(this.e)?5:this.O-5-g.f-g.x,(0,D.nc)(this.cc,b,5),g.f+=5;if(this.AP=c)g||(g=this.cc.v()),this.AI=g.f}}};D.D.Jt=function(){D.Gc.n.Jt.call(this)};
D.D.kl=function(){D.Gc.n.kl.call(this);var b=new D.K(this.e),c=new D.K(this.e);this.ub.j(b);this.ub.V.j(c);this.Xg(b,c);if(this.gj){(this.Tb=this.ub.Tb)&&this.ub.j(this.Tb);(0,D.jd)(this);var d=new D.L(0,0,this.O,this.T);if(!this.Ag&&!this.yD)D.Ma.isSupported(this.aX)&&(this.jb=D.Ma.ZE(this.e,this.aX,this.ub,d,this.Sr));else{var e=D.r;if(this.HN&&!this.sw)e=this.Q9;else if(this.gj&&this.gj.af!=this.fva&&(e=this.gj.yp(),!e)){var f=this.gj.tg,g;for(g in f)if(f[g].yp()){e=f[g].yp();break}}e&&D.Ma.isSupported(e)?
(this.jb=D.Ma.Dx(this.e,e,this.yD,this.ub,d,this.Sr))&&this.j(this.yD):this.ub.V.removeChild(this.AC)}this.jb&&(this.Tb&&this.j(this.Tb),this.pa.dc(),this.pa.ky(this),this.jb.gd(this.Co,this),this.jb.play());this.Mva=b;this.AC=c;this.gj&&(this.fva=this.gj.af);this.Ag=D.o}};
D.D.Xg=function(b,c){this.xJ();c.j(this.bX);c.j(this.NH);this.Iq?b.j(this.ju):c.j(this.ju);b.j(this.ts);var d=this.ub.V.ja();this.q1=D.t;for(var e=0;e<this.Vd.length;e++){var f=this.Vd[e];if(!this.q1&&f instanceof D.kd||!(f instanceof D.kd))f.H(d),!this.q1&&f instanceof D.kd&&(this.q1=D.o,this.gj=f)}this.gj&&(d=(0,D.ld)(this),0==d.length&&(d=(0,D.md)(this)),this.JZ&&(d=d[0])&&D.Pc.n.mo.call(this.pa,d),this.ub.At(D.r),this.ub.Jv(D.r),this.ub.Mo=D.o,this.ub.Fj=D.o,!this.HN&&!this.sw&&this.AZ!=D.r?(this.ub.ei(this.AZ),
this.ub.eo(this.Tta,this.Uta)):this.tP?(0,D.nd)(this):this.ub.vk(D.r,this.gj.QA()),(0,D.od)(this),d=this.ub.Un,e=this.gj.QA(),f=this.ub.nc(),f.f=this.AP?f.f-this.AI:f.f,d=window.Math.min((f.f-2*d)/e.f,(f.g-2*d)/e.g),this.ub.At(d),this.ub.Jv(d*(this.Bx?this.q_:1)),this.ub.Mo=this.Bx,this.ub.Fj=this.JD)};D.pd=function(b){(0,D.od)(b);b.tP?(0,D.nd)(b):b.AZ==D.r&&b.ub.vk(D.r,b.gj.QA())};
D.Gc.prototype.tk=function(b){b=b.fb();for(var c=0;c<b.length;c++){var d=b[c],e=d.getName();if("controlPanelResources"==e)D.Gc.n.oka.call(this,d);else if("legendResources"==e)this.lD=d;else if("panelDrawerResources"==e){d=d.getAttributes();for(e=0;e<d.length;e++){var f=d[e];(0,D.Yc)(this)[f.name]=f.value}}}};D.Gc.prototype.tka=(0,D.A)("YD");D.Gc.prototype.rG=function(){return new D.qd(this)};D.td=function(b,c){var d=new D.sd;d.translate(c.vb,c.pb);b.Iq&&b.ju.na(d);b.ts.na(d)};
D.Gc.prototype.sG=function(b){D.Gc.n.sG.call(this,b);var c=new D.qb;(0,D.Bb)(c,"controlPanelBehavior","show"==b.dh()?"initExpanded":"initCollapsed");this.Ra(c)};D.Gc.prototype.W6=function(b){var c=new D.qb;(0,D.Bb)(c,D.DvtCommonLegend.F7,"show"==b.dh());this.Ra(c)};
D.vd=function(b,c,d){if(c=c.M){var e=b.ub.V,f=(0,D.ud)(c,e,e.ja);d&&(b.vaa=e.ja(),(0,D.G)(c,"typeMatrix",b,b.Esa,b.Owa,f));d=new D.sd(1,0,0,1,f.vb,f.pb);b.Iq&&(0,D.G)(c,"typeMatrix",b.ju,b.ju.ja,b.ju.na,d);(0,D.G)(c,"typeMatrix",b.ts,b.ts.ja,b.ts.na,d)}};
D.Gc.prototype.$e=function(b){switch(b.dh()){case "adjustPanConstraints":if(this.JD){var c=b.bx;b=this.ub.Un;var d=this.ub.nc();b=new D.L(b,b,d.f-2*b,d.g-2*b);var e=this.gj.QA(),f=e.x*c,d=e.y*c,g=e.f*c,c=e.g*c;g>b.f?(this.ub.hp=b.x+b.f-(f+g),this.ub.fp=b.x-f):(e=0,this.AP&&(D.I.N(this.e)?e=this.GZ?2*-this.AI:-this.AI:this.GZ||(e=this.AI)),f=(b.x+b.f-e)/2-(f+g/2),this.ub.hp=f,this.ub.fp=f);c>b.g?(this.ub.ip=b.y+b.g-(d+c),this.ub.gp=b.y-d):(b=(b.y+b.g)/2-(d+c/2),this.ub.ip=b,this.ub.gp=b)}break;case "zooming":case "elasticAnimBegin":(0,D.vd)(this,
b,D.o);break;case "zoomed":if(b.bx!=D.r){d=this.ub.V.ja();(0,D.Bb)(b,"panX",d.vb);(0,D.Bb)(b,"panY",d.pb);b.M=D.r;D.lb.dispatchEvent(this.Na,this.ca,this,b);(0,D.td)(this,d);for(c=0;c<this.Vd.length;c++)this.Vd[c].$e(b,d)}break;case "zoomAndCenter":(0,D.wd)(this);break;case "zoomToFitBegin":this.GZ=D.o;this.AP&&this.ub.uj(this.O-this.AI,this.T,D.o);break;case "zoomToFitEnd":this.GZ=D.t,this.AP&&this.ub.uj(this.O,this.T,D.o),D.lb.dispatchEvent(this.Na,this.ca,this,new D.tb)}};
D.Gc.prototype.Ir=function(b){var c=b.dh();if("elasticAnimBegin"==c)(0,D.vd)(this,b,D.t);else if("panned"==c&&b.vda!=D.r){var d=this.ub.V.ja();(0,D.Bb)(b,"zoom",this.ub.kc());(0,D.Bb)(b,"panX",d.vb);(0,D.Bb)(b,"panY",d.pb);b.M=D.r;D.lb.dispatchEvent(this.Na,this.ca,this,b);(0,D.td)(this,d);for(b=0;b<this.Vd.length;b++)this.Vd[b].Ir(d)}this.cc&&("alta"==this.Sc?"dragPanBegin"===c?this.cc.ea(D.t):"dragPanEnd"===c&&this.cc.ea(D.o):(d=this.gr(),b=this.cc.Xa.Zb().clone(),"dragPanBegin"===c?(this.eb.u(d.backgroundDragAlpha),
b.u(d.borderDragAlpha),this.cc.Xa.Q(b),this.cc.Ff&&this.cc.Ff.u(d.borderDragAlpha),this.cc.ea(D.t)):"dragPanEnd"===c&&(this.eb.u(1),b.u(d.borderAlpha),this.cc.Xa.Q(b),this.cc.Ff&&this.cc.Ff.u(d.borderAlpha),this.cc.ea(D.o))))};
D.Gc.prototype.vy=function(b,c){if("none"==this.Xi&&(7==this.Ug||!this.Bx&&"alta"==this.Sc))this.Aw="hidden";this.ub=D.Gc.n.vy.call(this,b,c);if("hidden"!=this.Aw&&"none"!=this.Xi){var d=[D.E.Ai(this,this.m2),D.E.Ai(this,this.SR),D.E.Ai(this,this.O4)],d=new D.xd(this.e,this.Xi,this.ag,d,this.ub,this.pea,this.Rj,this);(0,D.zd)(this.ub,d)}return this.pa.ub=this.ub};
D.od=function(b){b.GQ=D.o;for(var c=0;c<b.Vd.length;c++){var d=b.Vd[c].af;d in b.dD&&(b.fE[d]=b.dD[d][1],b.Vi=d,b.gu=b.dD[d][0],b.SR())}b.GQ=D.t};
D.Gc.prototype.O4=function(){(0,D.jd)(this);for(var b=[],c=[],d=this.Vd.length-1;-1<d;d--)this.Vd[d].af==this.gj.af?this.Vd[d].reset(c):this.Vd[d].reset(b);for(d=0;d<b.length;d++)if(b[d]){var e=b[d].getParent();e&&e.removeChild(b[d])}for(d=0;d<c.length;d++)c[d]&&c[d].u(1);this.IC=[];b=new D.Ad(this.e,0.3);this.ub.vk(b);b.play();this.wl=[];this.Tb&&"none"!=this.Xi&&((0,D.Bd)(this.Tb,D.t),(0,D.Cd)(this.Tb,D.t))};
D.nd=function(b){var c=b.NH.v(),d=b.ju.v();if(b.Iq){var e=b.ub.V.ja();d.f/=e.tc;d.g/=e.Ud;d.x/=e.tc;d.y/=e.Ud}c=(0,D.Dd)(c,d);(0,D.jd)(b);D.I.Zh()&&(b.jb=new D.Ad(b.e,0.3));0<c.f&&0<c.g?b.ub.vk(b.jb,c):b.ub.vk(b.jb,b.gj.QA());b.jb&&b.jb.play()};D.Gc.prototype.GE=function(b){var c=new D.Ad(this.e,0.3);this.ub.vk(c,b);c.play()};
D.wd=function(b){if(b.gu){var c=(0,D.Nc)(b,b.Vi).Bi(b.gu);if(c&&(c=c.Db)){for(var c=c.getSelection(),d=0;d<c.length;d++)c[d]=c[d].nb();if(0<c.length){for(var e=c[0].v(),d=1;d<c.length;d++)e=(0,D.Dd)(e,c[d].v());b.GE(e)}}}};D.Fd=function(b,c){var d=D.Ed.sAa(b.Wd,c);return(0,D.Nc)(b,d)};D.Gd=function(b,c){var d=D.Ed.Iha(b.Wd,c);return(0,D.Nc)(b,d)};D.ld=function(b){var c=[];if(b.gj)for(var d=0;d<b.Vd.length;d++){var e=b.Vd[d].tg,f;for(f in e)c=b.gj.af==b.Vd[d].af?c.concat((0,D.Hd)(e[f])):c.concat((0,D.Id)(e[f]))}return c};
D.md=function(b){var c=[];if(b.gj)for(var d=0;d<b.Vd.length;d++){var e=b.Vd[d].tg;if(b.gj.af==b.Vd[d].af||!(b.Vd[d]instanceof D.kd))for(var f in e)c=c.concat(e[f].Rg)}return c};D.Gc.prototype.Owa=function(b){this.vaa=b;if(this.Iq){for(var c=(0,D.md)(this),d=0;d<c.length;d++)c[d].$e(b);c=this.ts.xa();for(d=0;d<c;d++)for(var e=this.ts.da(d),f=e.xa(),g=0;g<f;g++){var h=e.da(g);h instanceof D.Jd&&h.update(b)}}};D.Gc.prototype.Esa=(0,D.B)("vaa");
D.Gc.prototype.SR=function(){(0,D.jd)(this);var b=(0,D.Gd)(this,this.Vi),c=(0,D.Nc)(this,this.Vi),d=[];if(b){this.SO[this.Vi]=this.gu;var e=this.fE[this.Vi];!this.GQ&&"single"==this.Xi&&(this.wl.pop(),c.reset(d,e),b.reset(this.qu));for(var f=[],g=0;g<e.length;g++){var h=e[g],k=(0,D.Kd)(c,h);f.push(k[0]);for(var m=0;m<k.length;m++)this.NX[k[m]]=e[g];b.k2(k,d);if(k=c.Bi(this.gu)){for(var m=h,p=this.qu,q=0;q<k.$b.length;q++)if(k.$b[q].wk==m){k.$b[q].NF(D.o);k.wl.push(m);p.push(k.$b[q].nb());if(q=k.$b[q].uh())p.push(q),
(q=q.Zi)&&p.push(q);break}for(q=0;q<k.Rg.length;q++)if(k.Rg[q].wk==m){p.push(k.Rg[q].nb());break}}this.wl.push(h)}(0,D.Ld)(this,this.qu,d,D.t);(0,D.Md)(this,b.af);this.Vi=b.af;this.fE[this.Vi]=f}};
D.Gc.prototype.m2=function(){(0,D.jd)(this);for(var b=(0,D.Nc)(this,this.Vi),c=(0,D.Fd)(this,this.Vi),d=[],e=[],f=this.fE[this.Vi],g=0;g<f.length;g++){var h=this.NX[f[g]];e.push(h);if(-1!=D.Nd.Ba(this.wl,h)){b.ZL((0,D.Kd)(c,h),this.qu);for(var k=c.Bi(this.SO[c.af]),m=h,p=d,q=0;q<k.$b.length;q++)if(k.$b[q].wk==m){k.wl.splice(D.Nd.Ba(k.wl,m),1);k.$b[q].NF(D.t);var s=k.$b[q].nb();k.Oj.j(s);p.push(s);if(q=k.$b[q].uh())q.update(k.SD),p.push(q),p.push(q.Zi);break}for(q=0;q<k.Rg.length;q++)if(k.Rg[q].wk==
m){s=k.Rg[q].nb();k.xq.j(s);p.push(s);break}h=D.Nd.Ba(this.wl,h);-1!=h&&this.wl.splice(h,1)}}(0,D.Ld)(this,this.qu,d,D.o);this.Vi=c.af;this.gu=this.SO[this.Vi];this.fE[this.Vi]=e;(0,D.Md)(this,this.Vi)};D.jd=function(b){b.jb&&(b.jb.stop(D.o),b.jb=D.r)};
D.Ld=function(b,c,d,e){b.ub.V.ja();if(b.ksa&&!b.GQ){var f=new D.Ad(b.e,0.3);D.I.Zh()||(f=D.r);e?b.ub.vk(f):(0,D.wd)(b);f&&f.play()}(0,D.jd)(b);b.jb=D.Ma.Dx(b.e,b.qqa,c,d,D.r,0.5);D.I.Zh()||(b.jb=D.r);b.jb?(b.pa.dc(),b.pa.ky(b),b.jb.gd(b.hna,b),b.jb.play()):(0,D.Od)(b)};
D.Gc.prototype.Ra=function(b){var c=b.ta();if("selection"==c)if(this.gu){this.G0=b.getSelection();for(var c=this.fE,d=this.Vi,e=this.G0,f=[],g=(0,D.Nc)(this,this.Vi).Bi(this.gu).$b,h=0;h<e.length;h++)for(var k=0;k<g.length;k++)if(g[k].getId()==e[h]){f.push(g[k].wk);break}c[d]=f;(0,D.Md)(this,this.Vi);(0,D.Bb)(b,"clientId",this.gu);this.nO&&!(this.nO instanceof D.Pd)&&(this.sga=this.nO)}else(0,D.Md)(this,D.r),this.sga=D.r;else c==D.Qd.z8?((0,D.Bb)(b,"clientId",this.UO),this.IC="multiple"==this.Xi?
this.IC.concat(this.G0):this.G0,c=b.isa,c==D.Qd.tla&&this.m2(),c==D.Qd.EU?this.SR():c==D.Qd.sna&&this.O4(),b.Xe(this.IC)):("showPopup"==c||"hidePopup"==c)&&(0,D.Bb)(b,"clientId",this.UO);D.lb.dispatchEvent(this.Na,this.ca,this,b)};D.Md=function(b,c){if(b.Tb&&b.Xi&&"none"!=b.Xi){var d=(0,D.Gd)(b,c),e=(0,D.Fd)(b,c);d?(0,D.Bd)(b.Tb,D.o):(0,D.Bd)(b.Tb,D.t);e?(0,D.Cd)(b.Tb,D.o):(0,D.Cd)(b.Tb,D.t)}};D.Gc.prototype.W=function(){D.Gc.n.W.call(this);this.pa&&(this.pa.W(),this.pa=D.r)};
D.Gc.prototype.Co=function(){this.Tb&&this.ub.j(this.Tb);this.yD&&(this.removeChild(this.yD),this.yD=D.r);this.jb=D.r;this.pa.Re(this)};D.Gc.prototype.hna=function(){(0,D.Od)(this);this.jb=D.r;this.pa.Re(this)};D.Od=function(b){if(0<b.qu.length){for(var c=0;c<b.qu.length;c++){var d=b.qu[c];if(d)if(d instanceof D.Jd)d.reset();else if(d.gt&&d.gt())d.u(0);else{var e=d.getParent();e&&e.removeChild(d)}}b.qu=[]}};
D.Gc.prototype.QQ=function(b){this.YO("mouseover"==b.qda?"categoryRollOver":"categoryRollOut",b.Z2())};D.Gc.prototype.YO=function(b,c){var d=new D.kb(b,c),e=[],f;for(f in this.zg)for(var g in this.zg[f])e.push(this.zg[f][g]);for(f in this.Mu)for(g in this.Mu[f])e.push(this.Mu[f][g]);f=this.eb.mZ;for(var h in f)g=new D.Rd(f[h].yd(),h),e.push(g);(0,D.Sd)(d,e,0.1)};D.Gc.prototype.$R=function(){this.cG||(this.cG=new D.Td(this));return this.cG};D.Gc.prototype.getAutomation=D.Gc.prototype.$R;
D.Hc=function(){this.Init({fusion:D.vC,skyros:D.wC,alta:D.xC})};D.E.l(D.Hc,D.tr,"DvtThematicMapDefaults");
D.vC={skin:D.r,animationDuration:500,animationOnDisplay:"none",animationOnDrill:"none",animationOnMapChange:"none",controlPanelBehavior:"hidden",drilling:"off",initialZooming:"none",maintainDrill:"off",markerZoomBehavior:"fixed",panning:"none",tooltipDisplay:"auto",zooming:"none",styleDefaults:{areaStyle:"background-color:#B8CDEC;border-color:#FFFFFF;",dataAreaDefaults:{borderColor:"#FFFFFF",drilledInnerColor:"#FFFFFF",drilledOuterColor:"#000000",hoverColor:"#FFFFFF",opacity:1,selectedInnerColor:"#FFFFFF",
selectedOuterColor:"#000000"},dataMarkerDefaults:{borderColor:"#FFFFFF",borderStyle:"solid",borderWidth:"0.5px",color:"#000000",height:8,labelStyle:"font-family:Tahoma;font-size:13pt;color:#000000",opacity:0.4,scaleX:1,scaleY:1,shape:"circle",width:8},labelStyle:"font-family:Tahoma;font-size:11pt;"},legend:{position:"auto",rendered:D.o,layout:{gapRatio:1}},layout:{gapRatio:D.r,legendMaxSize:0.3,legendGap:10}};D.wC={styleDefaults:{backgroundColor:"#FFFFFF"}};
D.xC={skin:"alta",styleDefaults:{areaStyle:"background-color:#DDDDDD;border-color:#FFFFFF;",backgroundColor:"#FFFFFF",dataAreaDefaults:{drilledOuterColor:"#0572CE"},dataMarkerDefaults:{color:"rgb(51,51,51)",labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;color:#333333',opacity:1},labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;'}};D.kC={animationOnLayerChange:"none",labelDisplay:"auto",labelType:"short"};
D.lC={animationOnDataChange:"none",selection:"none"};
D.hC=function(b){for(var c=0;c<b.Vd.length;c++){var d=b.Vd[c].tg,e;for(e in d){var f=d[e].Sj;if(f&&f.uz)return f}}return D.r};D.Gc.prototype.Hi=function(b,c,d){this.bsa=D.t;return(b=(0,D.hC)(this))?b.Hi(d):D.t};D.Gc.prototype.mk=function(b,c){var d=(0,D.hC)(this);return d?d.mk(b,c):D.r};

D.sC=function(b,c){this.$Ea=b;this.oFa=c};D.E.l(D.sC,D.Gp,"DvtThematicMapDropTarget");
D.Td=(0,D.A)("I");D.E.l(D.Td,D.mu,"DvtThematicMapAutomation");D.Td.prototype.N6=function(b){b=(0,D.ye)(this.I.pa,b);var c;if(b&&(b instanceof D.NB||b instanceof D.WB))a:{for(var d=this.I.Vd,e=0;e<d.length;e++){var f=d[e].tg;for(c in f)if(b instanceof D.NB)for(var g=f[c].$b,h=0;h<g.length;h++){if(g[h]===b){c=(0,D.iC)(c)+":area["+b.getId()+"]";break a}}else if(b instanceof D.WB){g=f[c].Rg;for(h=0;h<g.length;h++)if(g[h]===b){c=(0,D.iC)(c)+":marker["+b.getId()+"]";break a}}}c=D.r}else c=D.r;return c};
D.Td.prototype.Sha=function(b){var c=b.indexOf(":"),d=b.indexOf("[");b=0<c&&0<d?(b=(0,D.jC)(this,b.substring(0,c),b.substring(c+1,d),b.substring(d+1,b.length-1)))?b.nb().Ea():D.r:D.r;return b};D.Td.prototype.getData=function(b,c,d){return(c=(0,D.jC)(this,b,c,d))?(b={},b.color=c.Ci(),b.tooltip=c.Ig(),c=c.uh(),b.label=c?c.Md():D.r,b):D.r};(0,D.sa)("DvtThematicMapAutomation.prototype.getData",D.Td.prototype.getData);
D.jC=function(b,c,d,e){b=b.I.Vd;for(var f=0;f<b.length;f++){var g=b[f].tg,h;for(h in g)if((0,D.iC)(h)==c)if("area"==d)for(var k=g[h].$b,m=0;m<k.length;m++){if(k[m].getId()===e)return k[m]}else if("marker"==d){k=g[h].Rg;for(m=0;m<k.length;m++)if(k[m].getId()===e)return k[m]}}return D.r};D.iC=function(b){var c=b.lastIndexOf(":");return 0<c?b.substring(c+1):b};
D.bC=function(b,c){this.Init(b,c)};D.E.l(D.bC,D.ad,"DvtDrillablePath");D.D=D.bC.prototype;D.D.Init=function(b,c){D.bC.n.Init.call(this,b);this.Gw=this.Fw=this.LO=this.KO=D.r;this.zP=D.t;this.Zoom=1;this.Td=c};D.D.gt=(0,D.B)("zP");
D.D.NF=function(b){this.zP!=b&&(this.zP=b,this.gt()?(this.Fw=this.Rh(),this.Fw.B(D.r),this.Fw.ea(D.t),this.Gw=this.Rh(),this.Gw.B(D.r),this.Gw.ea(D.t),b=this.getParent(),b.j(this.Gw),b.j(this.Fw),this.Fw.Q((0,D.pC)(this,this.KO,2)),this.Gw.Q((0,D.pC)(this,this.LO,4)),this.ea(D.t)):(this.fh()&&(this.Hh(),this.Yf.Q((0,D.pC)(this,this.Xp,1),2)),this.Gw.getParent().removeChild(this.Gw),this.Fw.getParent().removeChild(this.Fw),this.ea(D.o),this.u(1)))};
D.D.Gb=function(b){this.yo!=b&&(b&&(this.fh()?(this.jG(),this.Ak=(0,D.pC)(this,this.Ak,2),this.Bj=(0,D.pC)(this,this.Bj,6)):(this.Zp=(0,D.pC)(this,this.Zp,1),this.mn=(0,D.pC)(this,this.mn,4))),D.bC.n.Gb.call(this,b))};D.D.wc=function(){this.ib()?(this.jG(),this.Ak=(0,D.pC)(this,this.Ak,2),this.Bj=(0,D.pC)(this,this.Bj,6)):this.Xp=(0,D.pC)(this,this.Xp,2);D.bC.n.wc.call(this)};
D.D.jG=function(){this.Ak||(this.Ak=this.Xp.clone(),this.Ak.fa(2),this.Td&&(this.Ak.Hc=D.o));this.Bj||(this.Bj=this.mn.clone(),this.Bj.fa(6),this.Td&&(this.Bj.Hc=D.o))};D.D.hc=function(){this.ib()&&(this.Zp=(0,D.pC)(this,this.Zp,1),this.mn=(0,D.pC)(this,this.mn,4));D.bC.n.hc.call(this)};D.D.Qp=function(b,c){D.bC.n.Qp.call(this,b,c);this.Td&&(this.Xp&&(this.Xp.Hc=D.o),this.HM&&(this.HM.Hc=D.o));return this};
D.D.Tp=function(b,c){D.bC.n.Tp.call(this,b,c);this.Td&&(this.Zp&&(this.Zp.Hc=D.o),this.mn&&(this.mn.Hc=D.o));return this};D.D.Ct=function(b,c){D.bC.n.Ct.call(this,b,c);this.Td&&(this.Ak&&(this.Ak.Hc=D.o),this.Bj&&(this.Bj.Hc=D.o));return this};D.cC=function(b,c,d){b.KO=c;b.KO&&b.Td&&(b.KO.Hc=D.o);b.LO=d;b.LO&&b.Td&&(b.LO.Hc=D.o)};D.qC=function(b,c,d){if(!b.Td){var e=c.Zb();e&&(e=e.clone(),e.fa(d/b.Zoom),c.Q(e))}};D.pC=function(b,c,d){b.Td||(c=c.clone(),c.fa(d/b.Zoom));return c};
D.OB=function(b,c){b.Zoom=c.tc;b.gt()?((0,D.qC)(b,b.Fw,2),(0,D.qC)(b,b.Gw,4)):b.ib()?b.fh()?((0,D.qC)(b,b.Yf,2),(0,D.qC)(b,b,6)):((0,D.qC)(b,b.Yf,1),(0,D.qC)(b,b,4)):b.fh()?(0,D.qC)(b,b.Yf,2):(0,D.qC)(b,b,1)};
D.Ed=this.DvtBaseMapManager;D.Ed?(D.Ed.cq=D.Ed._UNPROCESSED_MAPS,D.Ed.dC=D.Ed._UNPROCESSED_PARENT_UPDATES):D.Ed={cq:[[],[],[]],dC:[[],[],[]]};"undefined"!=typeof D.DVT_ADVANCED_CLOSURE&&((0,D.sa)("DvtBaseMapManager",D.Ed),D.Ed._UNPROCESSED_MAPS=D.Ed.cq,D.Ed._UNPROCESSED_PARENT_UPDATES=D.Ed.dC);D.E.l(D.Ed,D.E,"DvtBaseMapManager");D.Ed.aC=0;D.Ed.LG=1;D.Ed.qW=2;D.Ed.pW=3;D.Ed.cN=4;D.Ed.Nr="__index";D.Ed.xg={};
D.Ed.Fha=function(b,c){D.Ed.zm();var d=D.Ed.xg[b][c];return d&&(d=d[D.Ed.cN])?new D.L(d[0],d[1],d[2],d[3]):D.r};D.Ed.zha=function(b,c){D.Ed.zm();var d=D.Ed.xg[b][c];return d?d[D.Ed.pW]:D.r};D.Ed.Aha=function(b,c){D.Ed.zm();var d=D.Ed.xg[b][c];return d?d[D.Ed.aC]:D.r};D.Ed.lia=function(b,c,d){D.Ed.zm();b=D.Ed.xg[b][c];var e;b&&(e=b[D.Ed.aC]);return e&&e[d]?e[d][1]:D.r};D.Ed.Lha=function(b,c){D.Ed.zm();var d=D.Ed.xg[b];if(d&&(d=d.cities))if(d=d[D.Ed.LG][c])return new D.N(d[0],d[1]);return D.r};
D.Ed.Mha=function(b,c){D.Ed.zm();var d=D.Ed.xg[b];if(d&&(d=d.cities))if(d=d[D.Ed.aC][c])return d[1];return D.r};D.Ed.yha=function(b,c,d){D.Ed.zm();var e=D.Ed.xg[b];if(e&&(e=e[c])){if((e=e[D.Ed.pW])&&e[d])return(0,D.up)(e[d][0]).nd();b=D.Ed.xg[b][c][D.Ed.LG][d];if(!b)return D.r;b=window.DvtPathUtils.MR(b);return window.DvtPathUtils.v(b).nd()}return D.r};D.Ed.Iha=function(b,c){D.Ed.zm();var d=D.Ed.xg[b][c];return d?D.Ed.xg[b][D.Ed.Nr][d.__index+1]:D.r};
D.Ed.sAa=function(b,c){D.Ed.zm();return D.Ed.xg[b][c]?D.Ed.xg[b][D.Ed.Nr][D.Ed.xg[b][c].__index-1]:D.r};D.Ed.Bha=function(b,c){D.Ed.zm();return D.Ed.xg[b][c][D.Ed.LG]};D.Ed.tAa=function(b,c,d){D.Ed.zm();return D.Ed.xg[b][c][D.Ed.LG][d]};D.Ed.Jha=function(b,c){D.Ed.zm();var d=D.Ed.Iha(b,c);return d&&(d=D.Ed.xg[b][d][D.Ed.qW])?d:[]};D.Ed.nHa=function(b,c){D.Ed.zm();return D.Ed.xg[b][D.Ed.Nr][c]};
D.Ed.zT=function(b,c,d,e,f,g,h,k){var m=D.Ed.xg[b];m||(m={},m[D.Ed.Nr]=[],D.Ed.xg[b]=m);b=m[c];b||(b={},m[c]=b,h!=D.r&&(m[D.Ed.Nr][h]=c));b[D.Ed.aC]=d;b[D.Ed.LG]=e;b[D.Ed.qW]=f;b[D.Ed.pW]=g;b[D.Ed.cN]=k;b[D.Ed.Nr]=h};(0,D.sa)("DvtBaseMapManager.registerBaseMapLayer",D.Ed.zT);D.Ed.hka=function(b,c,d){var e=D.Ed.xg[b];e||(e={},D.Ed.xg[b]=e);b=e[c];b||(b={},e[c]=b);(b=e[c])&&(b[D.Ed.aC]=d)};(0,D.sa)("DvtBaseMapManager.registerResourceBundle",D.Ed.hka);
D.Ed.Jka=function(b,c,d){if(b=D.Ed.xg[b])if(c=b[c])for(var e in d)c[D.Ed.aC][e]=d[e]};(0,D.sa)("DvtBaseMapManager.updateResourceBundle",D.Ed.Jka);D.Ed.lCa=function(b,c){D.Ed.cq=b;D.Ed.dC=c;D.Ed.zm()};(0,D.sa)("DvtBaseMapManager.loadUnprocessedMaps",D.Ed.lCa);
D.Ed.zm=function(){var b,c;if(D.Ed.cq){for(b=0;b<D.Ed.cq[0].length;b++)c=D.Ed.cq[0][b],D.Ed.zT(c[0],c[1],c[2],c[3],c[4],c[5],c[6],c[7]);for(b=0;b<D.Ed.cq[1].length;b++)c=D.Ed.cq[1][b],D.Ed.hka(c[0],c[1],c[2]);for(b=0;b<D.Ed.cq[2].length;b++)c=D.Ed.cq[2][b],D.Ed.Jka(c[0],c[1],c[2]);D.Ed.cq=D.r}if(D.Ed.dC)for(b=0;b<D.Ed.dC[0].length;b++){c=D.Ed.dC[0][b];var d=c[1],e=c[2],f=D.Ed.xg[c[0]],g;if(f){if(d=f[d]){d[D.Ed.qW]=c[3];g=d[D.Ed.cN];b=d[D.Ed.Nr];d=f[D.Ed.Nr];d.splice(b,0,e);f[e][D.Ed.Nr]=b;for(b+=
1;b<d.length;b++)(e=f[d[b]])&&e[D.Ed.Nr]++}(d=f[c[2]])&&(d[D.Ed.cN]=g)}}};D.Ed.HDa=function(b,c,d,e,f,g){if(0<g){c=1/(window.Math.min(e/c,f/d)*g);if(1>=c)return b;d=[];if(b)for(var h in b)e=b[h],(0,window.isNaN)(e)&&(e=window.DvtPathUtils.MR(b[h])),d[h]=window.DvtPathUtils.IDa(e,c);return d}return b};
D.Rd=function(b,c){this.Init(b,c)};D.E.l(D.Rd,D.E,"DvtThematicMapCategoryWrapper");D.Rd.prototype.Init=function(b,c){this.WH=b;this.rl=c};D.Rd.prototype.jg=(0,D.B)("rl");D.Rd.prototype.Be=function(){return[this.WH]};
D.Qd=function(b){this.Init(D.Qd.z8);this.isa=b};D.E.l(D.Qd,D.fb,"DvtMapDrillEvent");D.Qd.z8="drill";D.Qd.tla=0;D.Qd.EU=1;D.Qd.sna=2;D.Qd.prototype.Xe=(0,D.A)("If");
D.MB=function(b,c,d){this.Init("action");this.cs=b;this.FJ=c;this.Ef=d};(0,D.sa)("DvtMapActionEvent",D.MB);D.E.l(D.MB,D.fb,"DvtMapActionEvent");D.MB.TYPE="action";D.MB.prototype.Hg=(0,D.B)("cs");D.MB.prototype.getClientId=D.MB.prototype.Hg;D.MB.prototype.s3=(0,D.B)("FJ");D.MB.prototype.getRowKey=D.MB.prototype.s3;D.MB.prototype.pv=(0,D.B)("Ef");D.MB.prototype.getAction=D.MB.prototype.pv;
D.Jd=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.E.l(D.Jd,D.le,"DvtMapLabel");D.D=D.Jd.prototype;D.D.Init=function(b,c,d,e,f,g){D.Jd.n.Init.call(this,b,c,0,0);this.Td=g;this.du=[];this.ea(D.t);this.jf();this.Zd();this.$r=D.r;this.En=e;this.nA=f;if(d&&(this.du.push((0,D.up)(d[0])),1<d.length)){this.WZ=[];for(c=1;c<d.length;c++)e=d[c],this.du.push((0,D.up)(e[0])),e=new D.Lb(b,e[1]),(0,D.Mb)(e),f=new D.re("#000000"),this.Td&&(f.Hc=D.o),e.Q(f),this.WZ.push(e)}};
D.D.update=function(b){b=b.tc;for(var c=-1,d=D.me.Gi(this),e=D.t,f=0;f<this.du.length;f++){var g=this.du[f].f*b;if(d.f<=g){c=f;break}else if(this.getParent()||(e=D.o,this.nA.j(this)),this.v().f<=g){c=f;break}}-1==c&&"on"==this.En&&(c=this.du.length-1);this.mY!=c?(-1==c?this.reset():(this.getParent()||this.nA.j(this),d=this.du[c].nd(),this.jo(d),this.WZ&&(this.nA.removeChild(this.Zi),this.Zi=D.r,0<c?(this.Zi=this.WZ[c-1],this.nA.j(this.Zi),e=this.vc(),e.va("color","#000000"),this.Ka(e),e=this.du[c],
f=this.Zi.lb(),g=f.length,e.x>f[g-2]?(this.hj(),this.Zd(),this.jo(new D.N(e.x,d.y))):e.y>f[g-1]?(this.Wn(),this.jf(),this.jo(new D.N(d.x,e.y))):e.x+e.f<f[g-2]?(this.zi(),this.Zd(),this.jo(new D.N(e.x+e.f,d.y))):e.y+e.g<f[g-1]&&(this.lv(),this.jf(),this.jo(new D.N(d.x,e.y+e.g)))):(this.jf(),this.Zd(),e=this.vc(),e.va("color",this.xca),this.Ka(e)))),this.mY=c):-1==c&&e&&this.nA.removeChild(this);-1!=this.mY&&(c=new D.sd,c.translate(b*this.$r.x-this.$r.x,b*this.$r.y-this.$r.y),this.na(c),this.Zi&&(this.Zi.na(new D.sd(b,
0,0,b)),this.Td||(c=this.Zi.Zb().clone(),c.fa(1/b),this.Zi.Q(c))))};D.D.jo=function(b){this.$r=b;this.aa(b.x);this.qa(b.y)};D.D.nd=(0,D.B)("$r");D.D.Ka=function(b){D.Jd.n.Ka.call(this,b);this.xca||(this.xca=b.q("color"))};D.D.reset=function(){this.nA.removeChild(this);this.mY=-1;this.Zi&&(this.nA.removeChild(this.Zi),this.Zi=D.r)};
D.LB=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.E.l(D.LB,D.K,"DvtMapDataObject");D.D=D.LB.prototype;D.D.Init=function(b,c,d,e,f){D.LB.n.Init.call(this,b,D.r,e);this.lm=[];this.Mb=D.r;this.za=d;this.cs=e;this.wk=f;this.rGa=D.r;this.PH="#000000";this.Zoom=1;this.iZ=D.t;this.IO=c};D.D.getId=(0,D.B)("za");D.D.Hg=(0,D.B)("cs");D.D.de=function(b){(this.Mb=b)&&(0,D.Na)(this.Mb)};D.D.jo=(0,D.A)("hl");D.D.nd=(0,D.B)("hl");D.D.nb=(0,D.B)("Mb");D.D.Rp=(0,D.A)("gn");D.D.uh=(0,D.B)("gn");D.D.rc=(0,D.A)("J7");
D.D.pv=(0,D.B)("Ef");D.D.Qa=function(b){D.LB.n.Qa.call(this,b);this.gn&&this.gn.Qa(b)};D.D.Be=function(){return[this.Mb]};D.D.jg=(0,D.B)("lm");D.D.Ig=(0,D.B)("Ew");D.D.Ci=(0,D.B)("PH");D.D.Z4=function(b){this.PH=b;this.Mb&&this.Mb.lo&&this.Mb.lo(b)};D.D.Y4=function(b){this.Ew=b;this.Mb&&(0,D.Oa)(this.Mb,"label",b)};D.D.ic=function(){return this.Mb.ic()};D.D.ib=function(){return this.Mb.ib()};D.D.wc=(0,D.w)();D.D.hc=function(){this.vm||this.vV()};D.D.vV=(0,D.w)();D.D.k5=(0,D.A)("xd");D.D.od=(0,D.B)("xd");
D.D.Hi=function(b){for(var c=this.IO.Hg(),d=0;d<b.length&&b[d]!=c;d++);return c};D.D.Bi=(0,D.B)("IO");D.D.mk=function(){return this.IO.jw(this)};D.D.NA=function(){return this.IO.iw()};D.D.Di=function(b){return b.type==D.ed?this:32==b.keyCode&&b.ctrlKey?this:(0,D.ut)(this,b,this.YU())};D.D.YU=(0,D.ba)(D.r);D.D.Jg=function(){return this.Mb&&this.Mb.getParent()?this.Mb.v():new D.L(0,0,0,0)};D.D.el=function(){this.vm=D.o;this.wc()};D.D.nf=function(){this.vm&&(this.vm=D.t,this.hc())};D.D.bl=(0,D.B)("vm");
D.D.$e=function(b){this.Mb.getParent()&&(this.Zoom=b.tc,this.xT())};D.D.Do=(0,D.w)();D.D.xT=(0,D.w)();
D.NB=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.E.l(D.NB,D.LB,"DvtMapDataArea");D.D=D.NB.prototype;D.D.Init=function(b,c,d,e,f){D.NB.n.Init.call(this,b,c,d,e,f);this.CZ=D.t};D.D.de=function(b){D.NB.n.de.call(this,b)};D.D.Gb=function(b){b&&!this.CZ&&this.Oj.j(this.Mb);this.Mb.Gb(b)};D.D.wc=function(){this.Oj.j(this.Mb);this.Mb.wc();this.CZ=D.o};D.D.vV=function(){this.ib()?this.Oj.j(this.Mb):this.Oj.ya(this.Mb,0);this.Mb.hc();this.CZ=D.t};D.D.gt=function(){return this.Mb.gt()};
D.D.NF=function(b){(this.zP=b)?this.Oj.j(this.Mb):this.Oj.ya(this.Mb,0);this.Mb.NF(b)};D.D.$e=function(b){this.Mb.getParent()&&(D.NB.n.$e.call(this,b),(0,D.OB)(this.Mb,b),this.gt()||this.Do(b))};D.D.Do=function(b){this.gn&&this.gn.update(b)};D.D.YU=function(){return(0,D.ld)(this.Bi().I)};
D.WB=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.E.l(D.WB,D.LB,"DvtMapDataMarker");D.D=D.WB.prototype;D.D.Init=function(b,c,d,e,f){D.WB.n.Init.call(this,b,c,d,e,f);this.jEa=1;this.fj=0};D.D.Gb=function(b){this.Mb.Gb(b)};D.D.wc=function(){this.Mb.wc()};D.D.vV=function(){this.Mb.hc()};
D.D.Do=function(){if(this.gn){this.gn.jf();var b=(this.Mb.Y()+(0,D.Rk)(this.Mb)/2)*this.Zoom,c=this.Mb.Z()*this.Zoom,d=(0,D.Sk)(this.Mb),e=this.Mb.ta();"top"==this.J7?(c-=4,this.gn.lv()):"bottom"==this.J7?(c+=d,this.gn.Wn()):(c="triangleUp"==e?c+2*d/3:"triangleDown"==e?c+d/3:c+d/2,this.gn.Zd());this.gn.aa(b);this.gn.qa(c)}};
D.D.xT=function(){var b=this.Mb.getParent(),c=(0,D.Sk)(this.Mb);(0,D.Rk)(this.Mb)!=D.r&&(c!=D.r&&b)&&(c=this.Mb.VA(),this.gn&&this.Mb.VA()?((0,D.nc)(b,this.hl.x*this.Zoom-this.hl.x,this.hl.y*this.Zoom-this.hl.y),D.I.H5(b)):((0,D.nc)(this.Mb,this.hl.x*this.Zoom-(this.hl.x*window.Math.cos(c)-this.hl.y*window.Math.sin(c)),this.hl.y*this.Zoom-(this.hl.x*window.Math.sin(c)+this.hl.y*window.Math.cos(c))),D.I.H5(this.Mb)))};D.D.YU=function(){return(0,D.md)(this.Bi().I)};D.D.uj=(0,D.A)("fj");D.D.nc=(0,D.B)("fj");
D.KB=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.E.l(D.KB,D.LB,"DvtMapDataImage");D.D=D.KB.prototype;D.D.Init=function(b,c,d,e,f){D.KB.n.Init.call(this,b,c,d,e,f)};D.D.oT=function(b){b&&(b.width&&b.height)&&(this.Mb.getWidth()||this.Mb.fa(b.width),this.Mb.getHeight()||this.Mb.ua(b.height),this.uj(b.width*b.height),this.Mb.aa(this.hl.x-b.width/2),this.Mb.qa(this.hl.y-b.height/2),this.xT())};
D.D.xT=function(){var b=this.Mb.getWidth(),c=this.Mb.getHeight();b!=D.r&&(c!=D.r&&this.Mb.getParent())&&(b=this.Mb.Y()+b/2,c=this.Mb.Z()+c/2,(0,D.nc)(this.Mb,b*this.Zoom-this.hl.x,c*this.Zoom-this.hl.y))};D.D.uj=(0,D.A)("fj");D.D.nc=(0,D.B)("fj");
D.gC=function(b,c,d,e){this.Init(b,c,d,e)};D.E.l(D.gC,D.K,"DvtMapArea");D.D=D.gC.prototype;D.D.Init=function(b,c,d,e){D.gC.n.Init.call(this,b);this.tI=this.ZN=D.t;this.aFa=d;this.D=c;this.j(this.D);this.Td=e;if(b=c.Zb())this.V9=b.getWidth();this.D&&(0,D.Na)(this.D)};D.D.Gd=(0,D.B)("ne");D.D.Mv=function(b){this.ne=b;this.D&&(0,D.Oa)(this.D,"label",b)};D.D.Zb=function(){return this.D instanceof D.ak?this.D.Zb():D.r};D.D.Q=function(b){this.D instanceof D.ak&&this.D.Q(b)};
D.D.B=function(b){this.D instanceof D.ak&&this.D.B(b)};D.D.zc=function(){return this.D instanceof D.ak?this.D.zc():D.r};D.D.KA=function(){return this.D instanceof D.ad?this.D.KA():D.r};D.D.tj=function(b){this.D instanceof D.ad&&this.D.tj(b)};D.D.zB=function(b){this.D instanceof D.Xc&&this.D.zB(b)};D.D.contains=function(b,c){var d=this.v();return b>=d.x&&b<=d.x+d.f&&c>=d.y&&c<=d.y+d.g};D.D.$e=function(b){if(!this.Td&&this.D&&this.V9){var c=this.D.Zb().clone();c.fa(this.V9/b.tc);this.D.Q(c)}};
D.UB=function(b,c){this.Init(b,c)};D.E.l(D.UB,D.E,"DvtMapLayer");D.D=D.UB.prototype;D.D.Init=function(b,c){this.I=b;this.af="cities";this.U5=D.r;this.pG=c;this.tg={};this.hm=new D.sd};D.D.Z7=(0,D.w)();D.D.PM=(0,D.w)();
D.D.v5=function(b,c){this.jb&&(this.Ty=D.o,this.jb.stop(D.o));this.hm=c;this.Ds=this.Bi(b.Hg());this.tg[b.Hg()]=b;b.H(this.hm);b.$e(new D.tb("zoomed"),this.hm);if(this.Ds){var d=b.yp(),e=b.La();if(D.Ma.isSupported(d)){for(var f=new D.L(0,0,this.I.O,this.I.T),g=(0,D.oC)(this.Ds),h=0;h<g.length;h++){var k=new D.Ja(this.I.e,0,0,this.I.O,this.I.T);k.B(D.r);g[h].j(k)}for(var m=(0,D.oC)(b),h=0;h<m.length;h++)k=new D.Ja(this.I.e,0,0,this.I.O,this.I.T),k.B(D.r),m[h].j(k);f=D.Ma.Dx(this.I.e,d,g,m,f,e);g=new D.L(0,
0,this.I.O/this.hm.tc,this.I.T/this.hm.tc);m=[this.Ds.Oj];for(h=0;h<m.length;h++)k=new D.Ja(this.I.e,0,0,this.I.O/this.hm.tc,this.I.T/this.hm.tc),k.B(D.r),m[h].j(k);for(var p=[b.Oj],h=0;h<p.length;h++)k=new D.Ja(this.I.e,0,0,this.I.O/this.hm.tc,this.I.T/this.hm.tc),k.B(D.r),p[h].j(k);h=D.Ma.Dx(this.I.e,d,m,p,g,e);this.jb=new D.Fa(this.I.e,[f,h])}else{d=[this.Ds.Oj,this.Ds.xq,this.Ds.pz];for(h=0;h<d.length;h++)d[h].getParent().removeChild(d[h]);this.PM()}if(this.jb){this.pG.ky(this.ca);var q=this;
this.jb.gd(function(){q.Co(b)},this);this.Z7();this.jb.play()}}else this.PM(),(0,D.pd)(this.I)};D.D.Bi=function(b){return this.tg?this.tg[b]:D.r};D.D.Hg=(0,D.B)("U5");D.D.H=function(b){this.hm=b;for(var c in this.tg)this.tg[c].H(b)};D.D.reset=function(b,c){for(var d in this.tg)this.tg[d].reset(b,c)};D.D.$e=function(b,c){this.hm=c;for(var d in this.tg)this.tg[d].$e(b,c)};D.D.Ir=function(b){this.hm=b;for(var c in this.tg)this.tg[c].Ir(b)};
D.D.Co=function(b){if(this.Ds)for(var c=[this.Ds.Oj,this.Ds.xq,this.Ds.pz],d=0;d<c.length;d++){var e=c[d].getParent();e&&e.removeChild(c[d])}c=(0,D.oC)(b);for(d=0;d<c.length;d++)c[d].ho(c[d].xa()-1);b=[b.Oj];for(d=0;d<b.length;d++)b[d].ho(b[d].xa()-1);this.PM();(0,D.pd)(this.I);this.Ty=D.t;this.jb=D.r;this.pG.Re(this.ca)};
D.kd=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.E.l(D.kd,D.UB,"DvtMapAreaLayer");D.D=D.kd.prototype;D.D.Init=function(b,c,d,e,f,g){D.kd.n.Init.call(this,b,g);this.En=e;this.af=c;this.U5=d;this.LZ=f;this.eH={};this.ro={};this.dm={};this.Uz=this.Ym=D.r;this.If=[];this.lp={};this.Rq={};this.MQ={};this.cM=new D.K(this.I.e);this.yG=new D.K(this.I.e);this.I.bX.ya(this.cM,0);this.I.ts.ya(this.yG,0);this.KY=new D.sC(this,this.I.Wd)};D.D.LF=(0,D.A)("$W");D.D.yp=(0,D.B)("$W");D.D.io=(0,D.A)("ZW");
D.D.La=(0,D.B)("ZW");D.SB=function(b,c){b.Ym=c;for(var d in b.Ym)b.lp[d]=D.o,b.Rq[d]=D.o};D.kd.prototype.nS=function(b){return!this.Uz?D.r:this.Uz[b]};D.Kd=function(b,c){return b.fe[c]?b.fe[c].split(","):[]};D.kd.prototype.$E=(0,D.B)("En");D.ZB=function(b,c){b.uI=c;b.jD=D.r;for(var d in b.dm)d!=c&&(b.lp[d]=D.t)};
D.kd.prototype.QA=function(){this.jD||(this.uI?this.jD=window.DvtPathUtils.v(window.DvtPathUtils.MR(D.Ed.tAa(this.I.Wd,this.af,this.uI))):("world"!=this.I.Wd&&"worldRegions"!=this.I.Wd&&(this.jD=D.Ed.Fha(this.I.Wd,this.af)),this.jD||(this.jD=(0,D.Dd)(this.cM.v(),this.I.NH.v()))));return this.jD};
D.tC=function(b,c,d){var e=b.dm[c];if(e&&((d||!b.ro[c])&&b.Ika(c),b.ro[c]||(d=new D.gC(b.I.e,e,c,b.I.Td),b.ro[c]=d,b.pG.ha(e,d),d.Mv(b.Ym&&b.Ym[c]?b.Ym[c][1]:D.r)),b.Rq[c]&&(d=b.eH[c],!d&&("off"!=b.En&&b.Ym)&&(d="short"==b.LZ?b.Ym[c][0]:b.Ym[c][1]))))b.Uz&&b.Uz[c]?d=new D.Jd(b.I.e,d,b.Uz[c],b.En,b.yG,b.I.Td):(e=(0,D.Nj)(b.I.e,e),d=new D.Jd(b.I.e,d,[[e.x,e.y,e.f,e.g]],b.En,b.yG,b.I.Td)),b.eH[c]=d,b.PP&&d.Ka(b.PP)};
D.uC=function(b,c,d){if(b.dm[c]){b.cM.j(b.ro[c]);var e=b.eH[c];e&&(b.Rq[c]?e.update(b.hm):e.reset(),b.MQ[c]=b.Rq[c]);d&&(d.push(b.ro[c]),e&&(d.push(e),d.push(e.Zi)))}};D.kd.prototype.Ika=function(b){if(!this.tea||this.m$){this.m$=D.t;var c;this.tea=(c="world"==this.I.Wd||"worldRegions"==this.I.Wd?D.Ed.Fha(this.I.Wd,this.af):this.QA())?D.Ed.HDa(D.Ed.Bha(this.I.Wd,this.af),c.f,c.g,this.I.O,this.I.T,this.I.Bx?this.I.q_:1):D.Ed.Bha(this.I.Wd,this.af)}c=this.tea[b];this.dm[b]&&c?this.dm[b].tj(c):delete this.dm[b]};
D.TB=function(b){for(var c in b.Ym)b.lp[c]=D.o,b.Rq[c]=D.o};D.D=D.kd.prototype;D.D.v5=function(b,c,d){D.kd.n.v5.call(this,b,c,d);if(d==this.af)for(var e in this.dm)(0,D.tC)(this,e,D.o),this.lp[e]&&(0,D.uC)(this,e)};D.D.H=function(b){this.m$=D.o;for(var c in this.dm)(0,D.tC)(this,c,D.o),this.lp[c]&&(0,D.uC)(this,c);D.kd.n.H.call(this,b)};D.D.Z7=function(){for(var b in this.lp)this.lp[b]||((0,D.tC)(this,b,D.t),(0,D.uC)(this,b))};
D.D.PM=function(){for(var b in this.lp)if(!this.lp[b]){this.cM.removeChild(this.ro[b]);var c=this.eH[b];c&&(this.MQ[b]=D.t,this.yG.removeChild(c),(c=c.Zi)&&this.yG.removeChild(c))}};D.D.k2=function(b,c){for(var d=0;d<b.length;d++)(0,D.tC)(this,b[d],D.t),this.lp[b[d]]&&(0,D.uC)(this,b[d],c);for(var e in this.tg)this.tg[e].k2(b,c,this.hm);this.If=this.If.concat(b)};
D.D.ZL=function(b,c){for(var d in this.tg)this.tg[d].ZL(b,c);d=(0,D.Gd)(this.I,this.af);for(var e=0;e<b.length;e++){var f=b[e];if(this.ro[f]){var g=D.Nd.Ba(this.If,f);-1!==g&&(this.If.splice(g,1),c.push(this.ro[f]))}d&&d.ZL((0,D.Kd)(this,f),c)}};D.D.reset=function(b,c){D.kd.n.reset.call(this,b,c);"none"!=this.I.Xi&&(this.ZL(this.If,b),this.If=[])};D.D.$e=function(b,c){D.kd.n.$e.call(this,b,c);if(!this.I.Td)for(var d in this.ro)this.ro[d].$e(c);for(d in this.MQ)if(this.MQ[d]){var e=this.eH[d];e&&e.update(c)}};
D.RB=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.E.l(D.RB,D.kd,"DvtMapCustomAreaLayer");D.RB.prototype.Init=function(b,c,d,e,f,g){D.RB.n.Init.call(this,b,c,d,e,f,g)};D.RB.prototype.Ika=(0,D.w)();D.RB.prototype.QA=function(){return new D.L(0,0,this.tua,this.sua)};D.eC=function(b){var c=b.I.O,d=b.I.T;b=b.wqa;for(var e=0;e<b.length;e++){var f=b[e],g=f.source,h=f.width,f=f.height;if(g&&-1<g.search(".svg")||h>=c&&f>=d||e==b.length-1)return g}};
D.$B=function(b,c){var d=D.r,e=D.I.N(b.I.e);if(c&&0<c.length){var d=c[0].width,f=c[0].height;b.tua=d;b.sua=f;for(var g=[],h=0;h<c.length;h++)e&&"rtl"==c[h].dir?g.push(c[h]):!e&&"ltr"==c[h].dir&&g.push(c[h]);b.wqa=0<g.length?g:c;b.pP=(0,D.eC)(b);d=new D.Xc(b.I.e,b.pP,0,0,d,f)}d&&((0,D.SB)(b,{image:[D.r,D.r]}),b.dm={image:d})};D.RB.prototype.$e=function(b,c){D.RB.n.$e.call(this,b,c);if(this.ro.image){var d=(0,D.eC)(this);d!=this.pP&&(this.pP=d,this.ro[window.areaName].zB(this.pP))}};
D.VB=function(b,c,d,e){this.Init(b,c,d,e)};D.E.l(D.VB,D.E,"DvtMapDataLayer");D.VB.prototype.Init=function(b,c,d,e){this.I=b;this.cs=d;this.$b=[];this.Rg=[];this.pa=e;this.Sj=new D.Ud(b.e);(0,D.$d)(this.pa,this.Sj);this.Oj=new D.K(this.I.e);this.xq=new D.K(this.I.e);this.pz=new D.K(this.I.e);this.I.NH.ya(this.Oj,0);this.I.ju.ya(this.xq,0);this.I.ts.ya(this.pz,0);this.rea=c;this.If=[];this.wl=[]};D.oC=function(b){var c=[b.pz];b.I.Iq&&c.push(b.xq);return c};
D.Hd=function(b){for(var c=[],d=0;d<b.$b.length;d++)b.$b[d].gt()||c.push(b.$b[d]);return c};D.Id=function(b){for(var c=[],d=0;d<b.$b.length;d++)for(var e=0;e<b.If.length;e++)b.$b[d].wk==b.If[e]&&(b.$b[d].gt()||c.push(b.$b[d]));return c};D.YB=function(b,c){b.$b.push(c);b.pa.ha(c.nb(),c);c.Oj=b.Oj};D.D=D.VB.prototype;D.D.Hg=(0,D.B)("cs");D.D.LF=(0,D.A)("$W");D.D.yp=(0,D.B)("$W");D.D.io=(0,D.A)("ZW");D.D.La=(0,D.B)("ZW");D.D.py=function(b){if(this.Vq=b)this.Db=new D.se(this.Vq),this.pa.oy(this.cs,this.Db)};
D.D.ic=function(){return this.Vq!=D.r};D.rC=function(b,c){var d;d=b.$b[c];var e=d.nb(),f=b.rea.dm[d.wk];f?(e.tj(f.KA()),d=D.o):(d=b.$b.indexOf(d),-1!==d&&b.$b.splice(d,1),d=D.t);if(d){e=b.$b[c].nb();b.Oj.j(e);if(d=b.$b[c].uh())0<d.du.length||(e=e.v(),d.du.push(e)),d.update(b.SD);return D.o}return D.t};D.D=D.VB.prototype;
D.D.H=function(b){this.g$=D.o;this.SD=b;var c={};this.Rg.sort(function(b,c){return b.nc()<c.nc()?1:b.nc()>c.nc()?-1:0});for(var d=0;d<this.Rg.length;d++){var e=this.Rg[d],f=e.nb(),g=e.uh();if(g){if(f.VA()){var h=new D.K(f.e);this.xq.j(h);h.j(f);h.j(g)}else this.xq.j(f),f.j(g);e.Do(b)}else this.xq.j(f);(e=e.wk)&&(c[e]=D.o)}for(d=0;d<this.$b.length;d++)c[this.$b[d].wk]&&this.$b[d].Rp(D.r),(0,D.rC)(this,d)||d--;this.qP&&this.PD()};
D.D.k2=function(b,c,d){this.SD=d;for(var e=[],f=0;f<b.length;f++)for(var g=0;g<this.$b.length;g++)if(this.$b[g].wk==b[f]){e.push(this.$b[g].wk);(0,D.rC)(this,g);var h=this.$b[g].nb();c.push(h);(0,D.OB)(h,d);if(g=this.$b[g].uh())c.push(g),(g=g.Zi)&&c.push(g);break}for(g=0;g<this.Rg.length;g++)for(f=0;f<b.length;f++)d=this.Rg[g].wk,h=this.Rg[g].nb(),d!=D.r?d==b[f]&&(this.xq.j(h),c.push(h)):(this.xq.j(h),c.push(h));this.If=this.If.concat(e)};
D.D.ZL=function(b,c){for(var d=0;d<b.length;d++)for(var e=0;e<this.$b.length;e++)if(this.$b[e].wk==b[d]){this.$b[e].gt()&&this.$b[e].NF(D.t);this.$b[e].ib()&&this.Db.EL(this.$b[e]);var f=D.Nd.Ba(this.If,b[d]);if(-1<f&&(this.If.splice(f,1),c.push(this.$b[e].nb()),e=this.$b[e].uh()))c.push(e),c.push(e.Zi);break}};
D.D.reset=function(b,c){if(this.Db)for(var d=this.Db.getSelection(),e=0;e<d.length;e++)(!c||c&&-1==D.Nd.Ba(c,d[e].wk))&&this.Db.EL(d[e]);if("none"!=this.I.Xi)for(d=0;d<this.wl.length;d++){for(e=0;e<this.$b.length;e++)if(this.$b[e].wk==this.wl[d]){this.$b[e].NF(D.t);var f=this.$b[e].nb();this.Oj.j(f);b.push(f);if(e=this.$b[e].uh())e.update(this.SD),b.push(e),b.push(e.Zi);break}for(e=0;e<this.Rg.length;e++)if(this.Rg[e].wk==this.wl[d]){f=this.Rg[e].nb();this.xq.j(f);b.push(f);break}}this.wl=[]};
D.D.$e=function(b,c){this.SD=c;var d=c.tc,e=b.dh();if(this.g$&&"zoomed"==e){this.g$=D.t;for(e=0;e<this.$b.length;e++){var f=this.$b[e].nb(),g=f.Iea;if(g){var h=new D.cf;g.$c(h);h.na(new D.sd(1/d,D.r,D.r,1/d));f.B(h)}}}e=this.$b;for(d=0;d<e.length;d++)e[d].$e(c);if(this.I.Iq){e=this.Rg;for(d=0;d<e.length;d++)e[d].$e(c)}};D.D.Ir=(0,D.A)("SD");D.D.PD=function(){this.Db&&((0,D.ue)(this.Db,this.qP,this.Rg.concat(this.$b)),this.qP=D.r)};
D.D.jw=function(b){if(this.Db){b.ib()||(this.Db.ai(b,D.t),this.pa.Ml(b));b=[];for(var c=this.Db.getSelection(),d=0;d<c.length;d++)b.push(c[d].getId());return b}return D.r};D.D.iw=function(){for(var b=[],c=this.Db.getSelection(),d=0;d<c.length;d++)b.push(c[d].nb());return b};
D.Qc=function(b,c){this.Init(b,c)};D.E.l(D.Qc,D.rA,"DvtThematicMapKeyboardHandler");D.D=D.Qc.prototype;D.D.Init=function(b,c){D.Qc.n.Init(b,c);this.I=b};D.D.jL=function(b){return this.Jp(b)&&!b.ctrlKey};
D.D.Iv=function(b){var c=b.keyCode;if(221==c){var c=(0,D.qt)(this.Ja),d=(0,D.md)(this.I);c instanceof D.NB&&0<d.length&&(c=(0,D.ut)(c,b,d));this.Ja.mo(c);(0,D.fC)(this.Ja,c)}else 219==c?(c=(0,D.qt)(this.Ja),d=(0,D.ld)(this.I),!(c instanceof D.NB)&&0<d.length&&(c=(0,D.ut)(c,b,d)),this.Ja.mo(c),(0,D.fC)(this.Ja,c)):(c=D.Qc.n.Iv.call(this,b),this.Jp(b)&&!b.ctrlKey&&(0,D.fC)(this.Ja,c));return c};D.D.rF=function(b){return 32==b.keyCode&&b.ctrlKey};
D.D.Jp=function(b){var c=D.Qc.n.Jp.call(this,b);if(!c&&(b=b.keyCode,219==b||221==b))c=D.o;return c};
D.Pc=function(b,c,d){this.Init(b,c,d)};D.E.l(D.Pc,D.Bc,"DvtThematicMapEventManager");D.D=D.Pc.prototype;D.D.Init=function(b,c,d){D.Pc.n.Init.call(this,b,c,d);this.bv={};this.I=d;this.Wr=D.t};D.D.Ue=function(b){if(b&&b.Bi)return this.bv[b.Bi().Hg()]};D.D.oy=function(b,c){this.bv[b]=c};D.D.KT=(0,D.A)("Xi");D.D.EL=function(b,c){var d=this.bv[b];d&&d.EL(c)};D.D.vK=function(b){(b=this.bv[b])&&b.vK()};
D.D.kn=function(b){var c=(0,D.ye)(this,b.target);c&&(c.od&&c.Bi)&&(this.I.UO=c.Bi().Hg());D.Pc.n.kn.call(this,b)};D.D.yk=function(b){this.Wr=D.t;D.Pc.n.yk.call(this,b)};D.D.Mr=function(b){this.Wr=D.o;D.Pc.n.Mr.call(this,b)};D.D.Zf=function(b){if(!this.Wr){var c=(0,D.ye)(this,b.target);(0,D.fC)(this,c);if(!c||!c.ic||!c.ic())for(var d in this.bv)if(this.bv[d].ai(D.r,b.ctrlKey)){var e=new D.sb([]);(0,D.Bb)(e,"clientId",d);this.Na.call(this.ca,e)}D.Pc.n.Zf.call(this,b);this.Ow(c)}};
D.D.Ow=function(b){if(b instanceof D.LB)if(b.iZ){var c=new D.MB(b.Hg(),b.getId(),b.Ef);(0,D.Bb)(c,"clientId",b.Bi().Hg());this.dc();this.Na.call(this.ca,c)}else b.od()&&(this.I.UO=b.Bi().Hg())};D.fC=function(b,c){var d=D.r,e=D.r,f=D.r;c&&(c instanceof D.LB?f=c.nb():c instanceof D.gC&&(f=c),c.Bi&&(e=c.Bi(),d=e.Hg(),e=e.rea.af));var g=b.I;g.Vi=e;g.gu=d;g.nO=f};D.D=D.Pc.prototype;
D.D.jn=function(b){D.Pc.n.jn.call(this,b);b=(0,D.ye)(this,b.target);this.Ue(b)&&(this.Xi&&"none"!=this.Xi)&&(b=new D.Qd(D.Qd.EU),this.Na.call(this.ca,b))};
D.D.Eo=function(b){var c=D.o,d=b.keyCode;if((48==d||96==d)&&b.ctrlKey&&b.shiftKey)this.I.O4(),b.preventDefault();else if(220==d)(d=this.I.cc)&&(d instanceof D.Tc?(0,D.kf)(d,!d.isCollapsed()):d instanceof D.Sc&&d.Xe(!d.bb())),b.preventDefault();else if(13==d)b.shiftKey?this.I.m2():this.I.SR(),b.preventDefault();else if(32==d&&b.ctrlKey)d=(0,D.qt)(this),(0,D.fC)(this,d),(0,D.Wt)(this,d,D.o),b.preventDefault();else if((48==d||96==d)&&b.ctrlKey){var e=(0,D.qt)(this);b.altKey?(d=this.I,e=e.nb(),e||(e=
d.sga),e||(e=d.nO),d.GE(e.v())):(0,D.wd)(this.I);b.preventDefault()}else c=D.Pc.n.Eo.call(this,b);return c};D.D.Lr=function(b){var c=(0,D.ye)(this,b.target);(0,D.fC)(this,c);if(!c||c.FHa)for(var d in this.bv)if(this.bv[d].ai(D.r,b.ctrlKey)){for(var e=this.bv[d].getSelection(),f=[],g=0;g<e.length;g++)f.push(e[g].getId());e=new D.sb(f);this.Na.call(this.ca,e)}D.Pc.n.Lr.call(this,b);this.Ow(c)};D.D.GM=function(b){if((b=(0,D.ye)(this,b.target))&&b.od&&b.Bi)this.I.UO=b.Bi().Hg()};
D.D.Gy=function(b){var c=(0,D.ye)(this,b.target);c&&(this.Ue(c)&&this.Xi&&"none"!=this.Xi)&&((0,D.Wt)(this,c,b.ctrlKey),b=new D.Qd(D.Qd.EU),this.Na.call(this.ca,b))};
D.qd=function(b){this.Init(b)};D.E.l(D.qd,D.E,"DvtThematicMapParser");D.PB="inlineStyle";D.QB="animationOnMapChange";D.QB="animationOnMapChange";D.PB="inlineStyle";D.D=D.qd.prototype;D.D.Init=function(b){this.I=b;this.zaa={};this.tN=this.vN=this.uN=this.Ur=D.r;this.nca=D.I.$()};D.D.XS=function(b){b=b.fb();for(var c,d,e=0;e<b.length;e++)c=b[e],d=c.getName(),"mapProperties"==d?this.SV(c):"customLayer"==d?this.vEa(c):"layers"==d?this.DG(c):"legend"==d&&this.OM(c)};
D.D.SV=function(b){var c;if(c=b.k("source"))this.Iu=D.o;if(c=b.k("baseMapName")){var d=this.I;c=this.Iu?"$"+c:c;d.HN=d.Wd&&d.Wd!=c;d.Wd=c}if(c=b.k("animationOnDisplay"))this.I.aX=c;if(c=b.k(D.QB))this.I.Q9=c;(c=b.k("animationDuration"))&&this.I.io(c);if(c=b.k("displayTooltips"))this.I.DY=c;if(c=b.k("dropTargetStyle"))this.vqa=new D.P(c);if(c=b.k("controlPanelBehavior"))this.I.Aw=c;(c=b.k("featuresOff"))&&this.I.sB(c);if(c=b.k("centerX"))this.I.Tta=(0,window.parseFloat)(c);if(c=b.k("centerY"))this.I.Uta=
(0,window.parseFloat)(c);if(c=b.k("curZoom"))this.I.AZ=(0,window.parseFloat)(c);if((c=b.k("animationOnDrill"))&&"alphaFade"==c)this.I.qqa=c;(c=b.k("drillMode"))&&this.I.KT(c);if(c=b.k("drillZoomToFit"))this.I.ksa="true"==c;c=b.k("initialZooming");"auto"==c&&(this.I.tP=D.o);c=b.k("zooming");"none"==c&&(this.I.Bx=D.t);c=b.k("panning");"none"==c&&(this.I.JD=D.t);c=(0,window.parseFloat)(b.k("maxZoom"));(0,window.isNaN)(c)||(this.I.q_=c);if(c=b.k("markerZoomBehavior"))this.I.Iq="fixed"==c;(0,D.fx)(this.I,
b);b=b.fb();for(var e,d=0;d<b.length;d++)if(c=b[d],e=c.getName(),"resources"==e)this.UV(c);else if("mapHierarchy"==e){c=c.fb();e=this.I.Wd;for(var f=D.n,g=D.n,h=D.n,k=D.n,g=D.n,m=0;m<c.length;m++){var p=c[m];if("pointLayer"!=p.getName()){var f=p.k("layerName"),g=p.k("labelDisplay"),h=p.k("clientId"),k=p.k("labelType"),q=p.k("areaStyle");q&&this.Ur.qb(new D.P(q));(q=p.k("labelStyle"))&&this.Ur.qb(new D.P(q));this.Iu?g=new D.RB(this.I,f,h,g,k,this.I.pa):(g=new D.kd(this.I,f,h,g,k,this.I.pa),q=D.Ed.Aha(e,
f),h=this.fY(q),g.dm=h,(0,D.SB)(g,q),q=D.Ed.zha(e,f),g.Uz=q,f=D.Ed.Jha(this.I.Wd,f),g.fe=f,g.uN=this.uN,g.vN=this.vN,g.tN=this.tN);g.PP=this.Ur;g.BFa=this.vqa;if(q=p.k("animationOnLayerChange")){(p=p.k("animationDuration"))&&(p=(0,window.parseFloat)(p));if(!p||(0,window.isNaN)(p))p=1;g.LF(q);g.io(p)}g&&this.I.Vd.push(g)}}}else if("panZoomCanvasProperties"==e)this.I.pea=c;else if("regionLayer"==e){if(e=c.k(D.PB))this.Ur=new D.P(e);if(e=c.k("hoverStyle"))this.uN=new D.P(e);if(e=c.k("selectStyle"))this.vN=
new D.P(e);if(e=c.k("disclosedStyle"))this.tN=new D.P(e)}else"markerStyle"==e?(c=new D.P(c.k(D.PB)),this.I.fda=c):"basemap"==e&&this.I.Wd=="$"+c.k("id")&&this.OV(c)};
D.D.DG=function(b,c,d){var e=b.getElementsByTagName("layer");b=b.getElementsByTagName("legend");c&&(b&&b[0])&&this.OM(b[0]);for(b=0;b<e.length;b++){var f=e[b].k("clientId"),g=e[b].k("id"),h=(0,D.Nc)(this.I,g);h?h instanceof D.kd&&(0,D.TB)(h):(h=e[b].k("showWith"))?h=(0,D.Nc)(this.I,h):(h=new D.UB(this.I,this.I.pa),this.I.Vd.push(h));var f=new D.VB(this.I,h,f,this.I.pa),k=e[b].k("selectionMode");"single"==k?f.py("s"):"multiple"==k&&f.py("m");if(k=e[b].k("animationDataChange")){var m=e[b].k("animationDuration");
m&&(m=(0,window.parseFloat)(m));if(!m||(0,window.isNaN)(m))m=1;f.LF(k);f.io(m)}k=D.r;h instanceof D.kd&&(k=e[b].k("isolatedRowKey"));for(var m=[],p=[],q=this.f0(e[b].getElementsByTagName("styles")),s=e[b].getElementsByTagName("row"),u=this.e0(e[b],q),v=0;v<s.length;v++){var z=s[v].k("styleId");a:{var C=h,F=f,H=g,J=s[v],M=q[z],S=m,Q=p,W=k,Y=this.I.e,la=J.k("rowKey"),oa=J.k("clientId"),z=J.k("id"),ma=D.n,mb=M.getName();if("colorStyles"==mb){if(W){if(W!=la){z=D.r;break a}this.uI=z}C.lp[z]=D.t;ma=new D.NB(Y,
F,la,oa,z);this.c0(Y,z,C,J,ma)}else if("graduatedSymbol"==mb)ma=new D.WB(Y,F,la,oa,z),this.d0(Y,M,H,J,ma);else if("image"==mb){var ma=new D.KB(Y,F,la,oa,z),M=Y,hb=H,Va=J,W=ma,oa=Va.k("url"),Ub=D.r;if(hb=(0,D.XB)(this,hb,Va,"cities"!=hb)){Ub=new D.Xc(M,oa);W.jo(hb);W.de(Ub);var xb=D.n,yd=D.n;if(Va=Va.k(D.PB))Va=new D.P(Va),(xb=Va.q("width").substring(0,Va.q("width").indexOf("px")))&&Ub.fa(xb),(yd=Va.q("height").substring(0,Va.q("height").indexOf("px")))&&Ub.ua(yd),xb!=D.r&&yd!=D.r&&(Ub.aa(hb.x-xb/
2),Ub.qa(hb.y-yd/2),W.uj(xb*yd));(!xb||!yd)&&D.He.Ii(M,oa,D.E.Ai(W,W.oT))}}if(M=ma.nb()){if(W=(0,window.parseInt)(J.k("rotation")))W=W*window.Math.PI/180,M.Ni(W),oa=ma.nd(),(0,D.nc)(M,oa.x-(oa.x*window.Math.cos(W)-oa.y*window.Math.sin(W)),oa.y-(oa.x*window.Math.sin(W)+oa.y*window.Math.cos(W)));z&&C instanceof D.kd&&(C.Rq[z]=D.t);W="true"==J.k("hasAction");if(ma.iZ=W)W=J.k("action"),ma.Ef=W;if(W=J.k("destination"))oa=[],oa.destination=W,oa.targetFrame="_blank",oa.focusable=D.o,(0,D.Ll)(M,oa);"true"==
J.k("selected")&&S.push(la);"true"==J.k("drilled")&&(Q.push(J.k("id")),this.I.IC.push(la));S=J.k("label");Q="off";S?Q="on":"colorStyles"==mb&&(Q=C.$E());!S&&(z&&"off"!=Q)&&(S="long"==C.LZ?C.Ym[z][1]:C.Ym[z][0]);if(S){la=D.n;C.nS&&(la=C.nS(z));var Uc=D.n,Uc=la?new D.Jd(Y,S,la,Q,F.pz,this.I.Td):"colorStyles"!=mb?new D.le(Y,S,0,0):new D.Jd(Y,S,D.r,Q,F.pz,this.I.Td);(F=J.k("labelPosition"))&&ma.rc(F);F=new D.P;"colorStyles"==mb?F.qb(C.PP):"graduatedSymbol"==mb&&F.qb(this.I.fda);(C=J.k("labelStyle"))&&
F.qb(new D.P(C));Uc instanceof D.Jd&&(F.q("color")||F.va("color",D.R.Uk(ma.Ci())));Uc.Ka(F)}ma.Rp(Uc);C=this.I.DY;"none"!=C&&(J=J.k("shortDesc"),"auto"==C&&(C=D.n,z&&(C="cities"==H||this.Iu?D.Ed.Mha(this.I.Wd,z):D.Ed.lia(this.I.Wd,H,z)),C&&(J=J?C+": "+J:C)),J&&ma.Y4(J));z=ma}else z=D.r}z&&(z.nb().di(f.ic()&&!(z instanceof D.KB)),0<u.length&&z.k5(u),z instanceof D.NB?(0,D.YB)(f,z):(H=f,H.Rg.push(z),H.pa.ha(z.nb(),z)))}k&&this.uI&&(f.$ta=k,(0,D.ZB)(h,this.uI));f.ic()&&0<m.length&&(f.qP=m);0<p.length&&
(this.I.dD[h.af]=[f.Hg(),p]);c||h.Bi(f.Hg())?h.v5(f,c,d):h.tg[f.Hg()]=f}};D.D.OM=function(b){this.I.Fn=b};D.D.UV=function(b){this.I.tk(b)};D.D.OV=function(b){b=b.fb();for(var c,d,e=0;e<b.length;e++)c=b[e],d=c.getName(),"layer"==d?this.a0(c):"points"==d&&this.b0(c)};
D.D.a0=function(b){var c=b.fb();b=b.k("id");for(var d,e,f=[],g=0;g<c.length;g++)if(d=c[g],e=d.getName(),"image"==e){e={};e.source=d.k("source");e.width=d.k("width");e.height=d.k("height");var h=d.k("bidi");d=d.k("dir");e.dir="true"==h||"rtl"==d?"rtl":"ltr";f.push(e)}(0,D.$B)((0,D.Nc)(this.I,b),f)};
D.D.b0=function(b){b=b.fb();for(var c,d,e={},f={},g=0;g<b.length;g++)c=b[g],d=c.getName(),"point"==d&&(e[c.k("name")]=[c.k("x"),c.k("y")],f[c.k("name")]=[D.r,c.k("longLabel")]);D.Ed.zT(this.I.Wd,"cities",f,e,D.r,D.r,1)};D.D.fY=function(b){var c={},d=this.I.e,e;for(e in b)c[e]=new D.ad(d),(0,D.aC)(this,"colorStyles",this.Ur,c[e]);return c};D.D.f0=function(b){var c={};if(b&&0<b.length){b=b[0].fb();for(var d=0;d<b.length;d++){var e=b[d].k("id");c[e]=b[d]}}return c};
D.D.e0=function(b,c){for(var d=b.getElementsByTagName("spb"),e=[],f=0;f<d.length;f++){var g=d[f].k("alignId"),h=(0,D.Zq)(d[f]),k;for(k in c)if(g==k){h=new D.Ml(h.Qx(),h.eh(),D.r,h.IA());break}e.push(h)}return e};D.XB=function(b,c,d,e){b=b.I.Wd;var f=d.k("id");if(f)return e?D.Ed.yha(b,c,f):D.Ed.Lha(b,f);c=(0,window.parseFloat)(d.k("x"));d=(0,window.parseFloat)(d.k("y"));return new D.N(c,d)};
D.qd.prototype.c0=function(b,c,d,e,f){if(d.dm[c]){c=new D.P(e.k(D.PB));b=new D.bC(b,this.I.Td);var g=d.vN;e=d.tN;d=new D.re(d.uN.q("border-color"),1,2);var h=new D.re(g.q("-tr-inner-color"),1,1),g=new D.re(g.q("-tr-outer-color"),1,4);b.Qp(d,D.r).Tp(h,g);e&&(d=new D.re(e.q("-tr-inner-color"),1,2),e=new D.re(e.q("-tr-outer-color"),1,4),(0,D.cC)(b,d,e));f.de(b);(0,D.aC)(this,"colorStyles",c,b,f)}};
D.qd.prototype.d0=function(b,c,d,e,f){var g=D.r;if(d=(0,D.XB)(this,d,e,"cities"!=d)){if(g=e.k("source"))g=[g,e.k("sourceSelected"),e.k("sourceHover"),e.k("sourceHoverSelected")];else if((g=e.k("shapeType"))||(g="c"),!(0,D.Tn)(g)){c=c.getElementsByTagName("markerDef");for(var h=0;h<c.length;h++)!this.zaa[g]&&c[h].k("id")==g&&(this.zaa[g]=D.bf.Rga(b,c[h]))}c=e.k("scaleX");c=(0,window.isNaN)(c)?1:(0,window.parseFloat)(c);var h=e.k("scaleY"),h=(0,window.isNaN)(h)?1:(0,window.parseFloat)(h),k=e.k("width"),
m=e.k("height"),k=!k||(0,window.isNaN)(k)?8:(0,window.parseInt)(k),m=!m||(0,window.isNaN)(m)?8:(0,window.parseInt)(m),g=new D.Pd(b,g,this.I.Sc,d.x-k*c/2,d.y-m*h/2,k,m,D.r,c,h);f.jo(d);f.de(g);f.uj(k*c*m*h);if(b=e.k(D.PB))b=new D.P(b),(0,D.aC)(this,"graduatedSymbol",b,g,f)}};
D.aC=function(b,c,d,e,f){d||(d={});var g=d.q("pattern"),h=d.q("pattern-color"),k=d.q("background-color"),m=b.nca||"alta"==b.I.Sc?D.t:d.q("gradient");k&&f?f.lm.push(k):h&&f&&f.lm.push(h);var p;p=d.q("opacity")?(0,window.parseFloat)(d.q("opacity")):1;f&&f.Z4(k?k:h);if("graduatedSymbol"==c&&(0,D.Tn)(e.ta())){c=b.I.fda;if("none"!=(d.q("border-style")?d.q("border-style"):c.q("border-style")))f=d.q("border-color")?d.q("border-color"):c.q("border-color"),(d=d.q("border-width")?d.q("border-width"):c.q("border-width"))&&
(d=(0,window.parseFloat)(d.substring(0,d.indexOf("px")))),d=new D.re(f,1,d),b.I.Iq||(d.Hc=D.o),e.Q(d);"true"==m&&k?e.B(new D.Ok.a2(k,e,p)):g?e.B(new D.cf(g,h,k)):k?e.ga(k,p):e.ga(c.q("background-color"),p)}else if("colorStyles"==c){if((m=d.q("border-color"))&&"transparent"!=m)d=new D.re(m),b.I.Td&&(d.Hc=D.o),e.Q(d);g?(b=new D.cf(g,h,k),e.Iea=b):k&&"transparent"!=k?e.ga(k,p):e.B(D.r)}};
D.Oc=function(b){this.Init(b)};D.E.l(D.Oc,D.E,"DvtThematicMapJsonParser");D.D=D.Oc.prototype;D.D.Init=function(b){this.I=b;this.Iu=D.t;this.Ur=D.r;this.nca=D.I.$();this.xaa={}};
D.D.parse=function(b){b.skin="alta";this.SV(b);var c=b.styleDefaults;this.Ur=new D.P(c.areaStyle+c.labelStyle);var d=new D.P("fill-type:solid;background-color:"+c.backgroundColor);this.I.rO=d;this.I.Zq=c;this.Iu&&(c=(new D.Ek).parse(b.sourceXml))&&this.OV(c);for(var c=b.areaLayers,d=this.I.Wd,e=0;e<c.length;e++){var f=D.Ic.qb(c[e],D.kC),g=f.layer;if(g){var h;f.areaStyle&&(0,D.Hj)(this.Ur,f.areaStyle);if(this.Iu)h=new D.RB(this.I,g,D.r,f.labelDisplay,f.labelType,this.I.pa),(0,D.$B)(h,this.xaa[g]);
else{h=new D.kd(this.I,g,D.r,f.labelDisplay,f.labelType,this.I.pa);var k=D.Ed.Aha(d,g),m=this.fY(k);h.dm=m;(0,D.SB)(h,k);k=D.Ed.zha(d,g);h.Uz=k;g=D.Ed.Jha(this.I.Wd,g);h.fe=g}h.PP=this.Ur;h.LF("auto"==f.animationOnLayerChange?"alphaFade":f.animationOnLayerChange);h.io(this.I.La());this.I.Vd.push(h);f.areaDataLayer&&this.DG([f.areaDataLayer],h,D.o);f.pointDataLayers&&this.DG(f.pointDataLayers,h,D.t)}}this.DG(b.pointDataLayers,D.r,D.t)};
D.D.SV=function(b){this.I.io(b.animationDuration/1E3);this.I.aX="auto"==b.animationOnDisplay?"alphaFade":b.animationOnDisplay;this.I.Q9="auto"==b.animationOnMapChange?"alphaFade":b.animationOnMapChange;this.Iu=b.source!=D.r;var c=this.I,d=this.Iu?"$"+b.basemap:b.basemap;c.HN=c.Wd&&c.Wd!=d;c.Wd=d;this.I.Aw=b.controlPanelBehavior;this.I.KT("none");this.I.tP="auto"==b.initialZooming;this.I.Iq="fixed"==b.markerZoomBehavior;this.I.JD="auto"==b.panning;c=b.tooltipDisplay;"shortDesc"==c?c="shortDescOnly":
"labelAndShortDesc"==c&&(c="auto");this.I.DY=c;this.I.Bx="auto"==b.zooming};
D.D.DG=function(b,c,d){if(b)for(var e=0;e<b.length;e++){var f=D.Ic.qb(b[e],D.lC);c?c instanceof D.kd&&(0,D.TB)(c):(c=new D.UB(this.I,this.I.pa),this.I.Vd.push(c));var g=new D.VB(this.I,c,f.id,this.I.pa),h=f.selection;"single"==h?g.py("s"):"multiple"==h&&g.py("m");g.LF("auto"==f.animationOnDataChange?"alphaFade":f.animationOnDataChange);g.io(this.I.La());var k=D.r;c instanceof D.kd&&(k=f.isolatedItem);var m=f.disclosedItems,h=[],p,q=f.areas;if(q)for(var s=0;s<q.length;s++){var u=q[s].location;if(k)if(k!=
q[s].id)continue;else p=u;m&&-1!=m.indexOf(q[s].id)&&h.push(u);if(u=this.c0(c,g,q[s])){if(g.ic()){var v=u.nb();v.di(D.o)}(0,D.YB)(g,u)}}if(m=f.markers)for(s=0;s<m.length;s++){u=m[s].location;if(d&&k)if(k!=m[s].id)continue;else p=u;if(u=this.d0(c,g,m[s],d))g.ic()&&(v=u.nb(),v.di(D.o)),q=g,q.Rg.push(u),q.pa.ha(u.nb(),u)}p&&(g.$ta=k,(0,D.ZB)(c,p));if((f=f.selectedItems)&&0<f.length)g.qP=f;h&&0<h.length&&(this.I.dD[c.af]=[g.Hg(),h]);c.tg[g.Hg()]=g}};
D.D.OV=function(b){b=b.fb();for(var c,d,e=0;e<b.length;e++)c=b[e],d=c.getName(),"layer"==d?this.a0(c):"points"==d&&this.b0(c)};D.D.a0=function(b){var c=b.fb();b=b.k("id");for(var d,e,f=[],g=0;g<c.length;g++)if(d=c[g],e=d.getName(),"image"==e){e={};e.source=d.k("source");e.width=d.k("width");e.height=d.k("height");var h=d.k("bidi");d=d.k("dir");e.dir="true"==h||"rtl"==d?"rtl":"ltr";f.push(e)}this.xaa[b]=f};
D.D.b0=function(b){b=b.fb();for(var c,d,e={},f={},g=0;g<b.length;g++)c=b[g],d=c.getName(),"point"==d&&(e[c.k("name")]=[c.k("x"),c.k("y")],f[c.k("name")]=[D.r,c.k("longLabel")]);D.Ed.zT(this.I.Wd,"cities",f,e,D.r,D.r,1)};D.D.fY=function(b){var c={},d=this.I.e,e;for(e in b)c[e]=new D.ad(d),(0,D.mC)(this,this.Ur,c[e]);return c};
D.D.c0=function(b,c,d){var e=d.location;if(b.dm[e]&&d.color){b.lp[e]=D.t;var f=this.I.e,g=new D.bC(f,this.I.Td);d=D.Ic.qb(d,this.I.Zq.dataAreaDefaults);d.labelStyle||(d.labelStyle=this.I.Zq.labelStyle);var h=new D.re(d.hoverColor,1,2),k=new D.re(d.selectedInnerColor,1,1),m=new D.re(d.selectedOuterColor,1,4);g.Qp(h,D.r).Tp(k,m);h=new D.re(d.drilledInnerColor,1,2);k=new D.re(d.drilledOuterColor,1,4);(0,D.cC)(g,h,k);e=new D.NB(f,c,d.id,d.clientId,e);e.de(g);(0,D.nC)(this,b,c,d,g,e,D.o);return e}return D.r};
D.D.d0=function(b,c,d,e){var f;f=d;var g=this.I.Wd,h=f.location;f=h?e?D.Ed.yha(g,b.af,h):D.Ed.Lha(g,h):D.$.YCa(f.x,f.y,this.I.Wd);if(!f)return D.r;g=this.I.e;window.dataObj=new D.WB(g,c,d.id,d.clientId,d.location);window.dataObj.jo(f);d=D.Ic.qb(d,this.I.Zq.dataMarkerDefaults);(h=d.source)?h=[h,d.sourceSelected,d.sourceHover,d.sourceHoverSelected]:(h=d.shape)||(h="c");var k=d.scaleX;(0,window.isNaN)(k)&&(k=1);var m=d.scaleY;(0,window.isNaN)(m)&&(m=1);var p=d.width,q=d.height;if(!p||(0,window.isNaN)(p))p=
8;if(!q||(0,window.isNaN)(q))q=8;window.marker=new D.Pd(g,h,"alta",f.x-p*k/2,f.y-q*m/2,p,q,D.r,k,m);window.dataObj.de(window.marker);window.dataObj.uj(p*k*q*m);window.dataObj.rc(d.labelPosition);if(f=d.rotation)g=f*window.Math.PI/180,window.marker.Ni(g),f=window.dataObj.nd(),(0,D.nc)(window.marker,f.x-(f.x*window.Math.cos(g)-f.y*window.Math.sin(g)),f.y-(f.x*window.Math.sin(g)+f.y*window.Math.cos(g)));(0,D.nC)(this,b,c,d,window.marker,window.dataObj,e);return window.dataObj};
D.nC=function(b,c,d,e,f,g,h){var k=e.location;h&&"auto"==c.$E()&&(c.Rq[k]=D.t);e.action&&(g.iZ=D.o,g.Ef=e.action);if(k=e.destination){var m=[];m.destination=k;m.targetFrame="_blank";m.focusable=D.o;(0,D.Ll)(f,m)}m=b.I.DY;if("none"!=m){k=e.shortDesc;if("auto"==m){var p;(m=e.location)&&(p=!h||b.Iu?D.Ed.Mha(b.I.Wd,m):D.Ed.lia(b.I.Wd,c.af,m));p&&(k=k?p+": "+k:p)}k&&g.Y4(k)}p=new D.P;p.va("background-color",e.color);p.va("pattern",e.pattern);p.va("border-color",e.borderColor);p.va("border-style",e.borderStyle);
e.borderWidth&&p.va("border-width",e.borderWidth);p.va("opacity",e.opacity);(0,D.mC)(b,p,f,g);f=e.location;k=(p=e.label)?"on":"off";h&&(k=c.$E());!p&&(g instanceof D.NB&&"off"!=k)&&(p="long"==c.LZ?c.Ym[f][1]:c.Ym[f][0]);if(p){var q=b.I.e,q=g instanceof D.WB?new D.le(q,p,0,0):new D.Jd(q,p,c.nS?c.nS(f):D.r,k,d.pz,b.I.Td);b=new D.P(e.labelStyle);q instanceof D.Jd&&(b.q("color")||b.va("color",D.R.Uk(g.Ci())));q.Ka(b)}g.Rp(q)};
D.mC=function(b,c,d,e){c||(c={});var f=c.q("pattern"),g=c.q("background-color");e&&e.Z4(g);if(d instanceof D.Pd&&(0,D.Tn)(d.ta())){"none"!=c.q("border-style")&&(e=new D.re(c.q("border-color"),1,c.q("border-width")),b.I.Iq||(e.Hc=D.o),d.Q(e));var h=c.q("opacity");"true"==D.t&&g?d.B(new D.Ok.a2(g,d,h)):f?d.B(new D.cf(f,g,"#FFFFFF")):g?d.ga(g,h):d.ga(c.q("background-color"),h)}else if(d instanceof D.ad){if((c=c.q("border-color"))&&"transparent"!=c)e=new D.re(c),b.I.Td&&(e.Hc=D.o),d.Q(e);f?(b=new D.cf(f,
g,"#FFFFFF"),d.Iea=b):"transparent"!=g?d.ga(g,h):d.B(D.r)}};
D.$={};D.E.l(D.$,D.E,"DvtThematicMapProjections");D.$.St=new D.L(0,0,800,500);D.$.lN=6378206.4;D.$.EW=new D.L(500,200,200,200);D.$.DW=new D.L(163,-49,17,17);D.$.P8=new D.L(-17.379205428479874,-37.201510854305546,68.66391442808313,77.50071544582713);D.$.S8=new D.L(-0.8436866097568272,-0.7626456732012923,1.8336308036296942,1.5748427214611724);D.$.T8=new D.L(113.29667079927977,-52.89550592498755,65.25257389065216,42.123114617504626);
D.$.f9=new D.L(-0.47944476148667076,-0.0014669405958800579,0.7364925893845453,0.6293972741802124);D.$.o9=new D.L(-0.6154469465354344,-0.24589767758847714,1.2448236795108683,1.2631535127174947);D.$.u9=new D.L(-80.60817722658722,-60.796273249672765,46.608687602908056,66.96595767361796);D.$.R8=new D.L(68.20516856593524,-52.89892708045518,111.65739821771903,116.55460214469134);D.$.d9=new D.L(-24.543831069368586,-37.202500659225905,204.54283106936856,164.9634493690208);
D.$.n9=new D.L(-117.12451221229134,-54.95921623126266,82.33223251442891,87.67786623127876);D.$.y9=new D.L(-0.6154656300926513,0.0507209798775865,1.0153104799231851,0.966537441082997);D.$.z9=new D.L(-171.9,-62.6,349.8,150.8);D.$.Yna=new D.L(172,51,8,3);D.$.Zna=new D.L(-180,51,51,21);D.$.Aoa=new D.L(-178.5,18.9,35,11);D.$.ypa=new D.L(-124.8,24.4,58,25.5);D.$.Q8=new D.L(-187.5517578125,59.82610321044922,57.562225341796875,43.83738708496094);
D.$.j9=new D.L(-160.23606872558594,18.91549301147461,5.4374847412109375,3.3189010620117188);D.$.x9=new D.L(-2386803.25,-1183550.5,4514111,2908402);D.$.BW=new D.L(165,400,100,100);D.$.wW=new D.L(-75,350,240,150);D.$.Bk=[[1,0],[0.9986,0.0314],[0.9954,0.0629],[0.99,0.0943],[0.9822,0.1258],[0.973,0.1572],[0.96,0.1887],[0.9427,0.2201],[0.9216,0.2515],[0.8962,0.2826],[0.8679,0.3132],[0.835,0.3433],[0.7986,0.3726],[0.7597,0.4008],[0.6732,0.4532],[0.6213,0.4765],[0.5722,0.4951],[0.5322,0.5072]];
D.$.YCa=function(b,c,d){var e;switch(d){case "africa":e=D.$.zu(D.$.P8,D.$.mI(b,c));break;case "asia":e=D.$.zu(D.$.S8,D.$.aP(40,95,20,60,b,c),D.$.sg(5));break;case "australia":e=D.$.Csa(b,c);break;case "europe":e=D.$.zu(D.$.f9,D.$.aP(35,25,40,65,b,c),D.$.sg(10));break;case "northAmerica":e=D.$.zu(D.$.o9,D.$.aP(23,-96,20,60,b,c));break;case "southAmerica":e=D.$.zu(D.$.u9,new D.N(b,c),D.$.sg(5));break;case "apac":e=D.$.zu(D.$.R8,D.$.mI(b,c));break;case "emea":e=D.$.zu(D.$.d9,D.$.mI(b,c));break;case "latinAmerica":e=
D.$.zu(D.$.n9,new D.N(b,c));break;case "usaAndCanada":e=D.$.zu(D.$.y9,D.$.aP(23,-96,20,60,b,c));break;case "worldRegions":e=D.$.Cba(b,c);break;case "usa":e=D.$.mta(b,c);break;case "world":e=D.$.Cba(b,c)}return e?new D.N(10*e.x,10*e.y):new D.N(b,c)};
D.$.mta=function(b,c){var d;return(0,D.zo)(D.$.Yna,b,c)||(0,D.zo)(D.$.Zna,b,c)?(d=D.$.tm(D.$.Q8,D.$.wW),D.$.ZG(d,D.$.mI(b,c))):(0,D.zo)(D.$.Aoa,b,c)?(d=D.$.tm(D.$.j9,D.$.BW),D.$.ZG(d,new D.N(b,c))):(0,D.zo)(D.$.ypa,b,c)?(d=D.$.tm(D.$.x9,D.$.St),D.$.ZG(d,D.$.cta(new D.N(-95,36),b,c))):new D.N(b,c)};D.$.Cba=function(b,c){var d=D.$.tm(D.$.z9,D.$.St);return D.$.ZG(d,D.$.gta(b,c))};D.$.Csa=function(b,c){var d;d=(0,D.zo)(D.$.DW,b,c)?D.$.tm(D.$.DW,D.$.EW):D.$.tm(D.$.T8,D.$.St);return D.$.ZG(d,D.$.mI(b,c))};
D.$.zu=function(b,c,d){b=D.$.tm(b,D.$.St);if(d){var e=new D.sd;e.rotate(d);b=D.$.X$(b,e)}return(0,D.Xm)(b,c)};D.$.aP=function(b,c,d,e,f,g){c=D.$.sg(c);b=D.$.sg(b);d=D.$.sg(d);e=D.$.sg(e);e=0.5*(window.Math.sin(d)+window.Math.sin(e));d=window.Math.pow(window.Math.cos(d),2)+2*e*window.Math.sin(d);b=d-2*e*window.Math.sin(b);b=window.Math.sqrt(b)/e;f=e*(D.$.sg(f)-c);g=d-2*e*window.Math.sin(D.$.sg(g));g=window.Math.sqrt(g)/e;return new D.N(g*window.Math.sin(f),b-g*window.Math.cos(f))};
D.$.mI=function(b,c){var d=window.Math.log(window.Math.tan(0.25*window.Math.PI+0.5*D.$.sg(c)));return new D.N(b,D.$.ZF(d))};D.$.cta=function(b,c,d){c=D.$.sg(c);d=D.$.sg(d);var e=D.$.sg(b.x);b=D.$.sg(b.y);return new D.N(window.Math.cos(d)*window.Math.sin(c-e)*D.$.lN,(window.Math.cos(b)*window.Math.sin(d)-window.Math.sin(b)*window.Math.cos(d)*window.Math.cos(c-e))*D.$.lN)};
D.$.gta=function(b,c){var d=window.Math.floor(window.Math.abs(c)/5);d>=D.$.Bk.length-1&&(d=D.$.Bk.length-2);var e=(window.Math.abs(c)-5*d)/5,f=b*(D.$.Bk[d][0]+e*(D.$.Bk[d+1][0]-D.$.Bk[d][0])),d=D.$.Bk[d][1]+e*(D.$.Bk[d+1][1]-D.$.Bk[d][1]);0>c&&(d*=-1);return new D.N(f,180*d)};D.$.ZG=function(b,c){return new D.N(c.x*b.tc+b.vb,c.y*b.Ud+b.pb)};D.$.X$=function(b,c){var d=b.tc,e=b.Ud;return new D.sd(c.tc*d,c.sf*d,c.Ke*e,c.Ud*e,b.vb+c.vb*d,b.pb+c.pb*e)};
D.$.tm=function(b,c){var d=c.x,e=c.y,f=b.f,g=b.g,h=0,h=c.f/f,k=c.g/g,h=h<=k?h:k,d=d-b.x*h,e=e+b.y*h,d=d+(c.f-f*h)/2,e=e+(c.g-(c.g-g*h)/2);return new D.sd(h,0,0,-h,d,e)};D.$.sg=function(b){return b*(window.Math.PI/180)};D.$.ZF=function(b){return b*(180/window.Math.PI)};
D.$.EHa=function(b,c,d){var e;b/=10;c/=10;switch(d){case "africa":e=D.$.Au(D.$.P8,new D.N(b,c));e=D.$.lI(e.x,e.y);break;case "asia":e=D.$.Au(D.$.S8,new D.N(b,c),D.$.sg(5));e=D.$.bP(40,95,20,60,e.x,e.y);break;case "australia":e=D.$.Ssa(b,c);break;case "europe":e=D.$.Au(D.$.f9,new D.N(b,c),D.$.sg(10));e=D.$.bP(35,25,40,65,e.x,e.y);break;case "northAmerica":e=D.$.Au(D.$.o9,new D.N(b,c));e=D.$.bP(23,-96,20,60,e.x,e.y);break;case "southAmerica":e=D.$.Au(D.$.u9,new D.N(b,c),D.$.sg(5));break;case "apac":e=
D.$.Au(D.$.R8,new D.N(b,c));e=D.$.lI(e.x,e.y);break;case "emea":e=D.$.Au(D.$.d9,new D.N(b,c));e=D.$.lI(e.x,e.y);break;case "latinAmerica":e=D.$.Au(D.$.n9,new D.N(b,c));break;case "usaAndCanada":e=D.$.Au(D.$.y9,new D.N(b,c));e=D.$.bP(23,-96,20,60,e.x,e.y);break;case "worldRegions":e=D.$.rba(b,c);break;case "usa":e=D.$.Vsa(b,c);break;case "world":e=D.$.rba(b,c)}return e?e:new D.N(b,c)};
D.$.Vsa=function(b,c){var d;return(0,D.zo)(D.$.wW,b,c)?(d=D.$.tm(D.$.Q8,D.$.wW),d.et(),d=(0,D.Xm)(d,new D.N(b,c)),D.$.lI(d.x,d.y)):(0,D.zo)(D.$.BW,b,c)?(d=D.$.tm(D.$.j9,D.$.BW),d.et(),(0,D.Xm)(d,new D.N(b,c))):(0,D.zo)(D.$.St,b,c)?(d=D.$.tm(D.$.x9,D.$.St),d.et(),d=(0,D.Xm)(d,new D.N(b,c)),D.$.Tsa(new D.N(-95,36),d.x,d.y)):new D.N(b,c)};D.$.rba=function(b,c){var d=D.$.tm(D.$.z9,D.$.St);d.et();d=(0,D.Xm)(d,new D.N(b,c));return D.$.Usa(d.x,d.y)};
D.$.Ssa=function(b,c){var d;d=(0,D.zo)(D.$.EW,b,c)?D.$.tm(D.$.DW,D.$.EW):D.$.tm(D.$.T8,D.$.St);d.et();d=(0,D.Xm)(d,new D.N(b,c));return D.$.lI(d.x,d.y)};D.$.Au=function(b,c,d){b=D.$.tm(b,D.$.St);if(d){var e=new D.sd;e.rotate(d);b=D.$.X$(b,e)}b.et();return(0,D.Xm)(b,c)};
D.$.bP=function(b,c,d,e,f,g){c=D.$.sg(c);b=D.$.sg(b);d=D.$.sg(d);e=D.$.sg(e);e=0.5*(window.Math.sin(d)+window.Math.sin(e));d=window.Math.pow(window.Math.cos(d),2)+2*e*window.Math.sin(d);b=d-2*e*window.Math.sin(b);b=window.Math.sqrt(b)/e;var h=window.Math.sqrt(f*f+(b-g)*(b-g));return new D.N(D.$.ZF(c+window.Math.atan(f/(b-g))/e),D.$.ZF(window.Math.asin((d-h*h*e*e)/(2*e))))};D.$.lI=function(b,c){return new D.N(b,D.$.ZF(2*window.Math.atan(window.Math.exp(D.$.sg(c)))-0.5*window.Math.PI))};
D.$.Tsa=function(b,c,d){c/=D.$.lN;d/=D.$.lN;var e=D.$.sg(b.y),f=window.Math.sqrt(c*c+d*d),g=window.Math.asin(f);return new D.N(D.$.ZF(D.$.sg(b.x)+window.Math.atan(c*window.Math.sin(g)/(f*window.Math.cos(e)*window.Math.cos(g)-d*window.Math.sin(e)*window.Math.sin(g)))),D.$.ZF(window.Math.asin(window.Math.cos(g)*window.Math.sin(e)+d*window.Math.sin(g)*window.Math.cos(e)/f)))};
D.$.Usa=function(b,c){var d=window.Math.floor(window.Math.abs(c)/5);d>=D.$.Bk.length-1&&(d=D.$.Bk.length-2);var e=(window.Math.abs(c/180)-D.$.Bk[d][1])/(D.$.Bk[d+1][1]-D.$.Bk[d][1]),f=5*e+5*d,d=b/(D.$.Bk[d][0]+e*(D.$.Bk[d+1][0]-D.$.Bk[d][0]));0>c&&(f*=-1);return new D.N(d,f)};
D.Ce=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.E.l(D.Ce,D.pf,"DvtMapControlButton");D.Ce.prototype.Init=function(b,c,d,e,f,g,h){D.Ce.n.Init.call(this,b,e,g);this.GX=f;this.zb=c;this.Ja=h;(0,D.rf)(this.zb,this.ima,this);this.zb.setCursor("pointer");b=0==this.GX?this.hb().$$:1==this.GX?this.hb().Z$:2==this.GX?this.hb().baa:D.r;b=new D.sf(this,D.r,D.r,D.r,D.r,D.r,b);this.Ja.ha(this.zb,b);this.j(this.zb);this.$ca=d;this.fca=D.o};
D.Ce.prototype.qg=function(b){this.u(b?1:0.4);this.zb.setCursor(b?"pointer":D.r);this.fca=b;this.zb.qg(b);(0,D.uf)(this.zb)};D.Ce.prototype.ima=function(b){(0,D.Hf)(b);this.fca&&this.$ca&&this.$ca()};
D.xd=function(b,c,d,e,f,g,h,k){this.Init(b,c,d,e,f,g,h,k)};D.E.l(D.xd,D.of,"DvtThematicMapControlPanel");D.xd.prototype.Init=function(b,c,d,e,f,g,h,k){D.xd.n.Init.call(this,b,f,d,g,h,k);this.tk(new D.dC(g));this.Xi=c;this.ag=d;this.jsa=e[0];this.hsa=e[1];this.ywa=e[2];this.Jw=this.Kw=this.NQ=D.r;this.Oaa=this.Naa=D.t;this.A=k.gr()};D.Bd=function(b,c){b.Naa=c;b.Jw&&b.Jw.qg(c)};D.Cd=function(b,c){b.Oaa=c;b.Kw&&b.Kw.qg(c)};
D.xd.prototype.tk=function(b){D.xd.n.tk.call(this,b);this.Jw&&this.Jw.tk(b);this.Kw&&this.Kw.tk(b);this.NQ&&this.NQ.tk(b)};
D.xd.prototype.GG=function(b){if(this.Xi&&"none"!=this.Xi){var c=(0,D.Ge)(this.A,"buttonWidth",0);this.NQ=D.O.wya(this.e,this.ywa,this.X,this.hb(),this.ag,this.Ja,this.A);b.j(this.NQ);this.Jw=D.O.jya(this.e,this.hsa,this.X,this.hb(),this.ag,this.Ja,this.A);this.Jw.F(c);this.Jw.qg(this.Naa);b.j(this.Jw);this.Kw=D.O.kya(this.e,this.jsa,this.X,this.hb(),this.ag,this.Ja,this.A);this.Kw.F(2*c);this.Kw.qg(this.Oaa);b.j(this.Kw)}};
D.dC=function(b){this.Init(b)};D.E.l(D.dC,D.Lf,"DvtThematicMapControlPanelResources");D.dC.prototype.Init=function(b){D.dC.n.Init.call(this,b);b?(this.$$=b.k("pdu"),this.Z$=b.k("pdd"),this.baa=b.k("res")):(this.$$="Show Control Panel (/)",this.Z$="Hide (/)",this.baa="Zoom and Center (Ctrl+Alt+0)")};
});