define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Vt=(0,D.z)();(0,D.ta)("DvtAxis",D.Vt);D.F.l(D.Vt,D.Sb,"DvtAxis");D.Vt.newInstance=function(b,c,d){var e=new D.Vt;e.Init(b,c,d);return e};D.Xt=function(b){return(0,D.Tb)(new D.Wt,b)};D.Vt.getDefaults=D.Xt;D.Vt.prototype.Init=function(b,c,d){D.Vt.q.Init.call(this,b,c,d);this.ef=new D.Wt;this.xa=new D.Yt(this);this.xa.$e(this);this.OR=D.o;this.Qa=D.r};D.Vt.prototype.Yd=function(b){b?this.X=this.ef.pg(b):this.X||(this.X=(0,D.Xb)(this))};
D.Vt.prototype.mz=function(b,c,d){this.Yd(b);this.Da().isLayout=D.o;this.L(D.r,c,d);b=this.C();this.Da().isLayout=D.u;this.Mi();var e=this.Da().position;if("top"==e||"bottom"==e)return b.j<=d&&(this.OR=D.u),new D.hl(c,window.Math.min(b.j,d));e=0<b.g?window.Math.max(1,0.1*b.g):0;b.g+e<=c&&(this.OR=D.u);return new D.hl(window.Math.min(b.g+e,c),d)};D.Vt.prototype.L=function(b,c,d,e,f){this.Yd(b);this.ub=c;this.Ob=d;this.Mi();e||(e=0);f||(f=0);D.Zt.L(this,new D.I(e,f,c,d))};D.Vt.prototype.render=D.Vt.prototype.L;
D.E=D.Vt.prototype;D.E.Kf=function(b,c){this===c&&this.ib(b)};D.E.Da=(0,D.C)("X");D.E.Va=(0,D.C)("xa");D.E.getWidth=(0,D.C)("ub");D.E.getHeight=(0,D.C)("Ob");D.E.V=function(){this.xa&&(this.xa.rs(this),this.xa.V(),this.xa=D.r);D.Vt.q.V.call(this)};D.E.eZ=(0,D.B)("Qa");D.E.vq=function(){return new D.$t(this)};D.Vt.prototype.getAutomation=D.Vt.prototype.vq;
D.au={};(0,D.ta)("DvtAxisConstants",D.au);D.F.l(D.au,D.F,"DvtAxisConstants");D.au.qx="tickLabel";D.au.TICK_LABEL=D.au.qx;D.au.tp="title";D.au.TITLE=D.au.tp;
D.AJ=(0,D.B)("mv");D.F.l(D.AJ,D.F,"DvtAbstractAxisValueFormatter");D.AJ.prototype.sq=(0,D.z)();
D.$t=function(b){this.Ph=b;this.rd=this.Ph.Da();this.Zba=this.Ph.Ib};(0,D.ta)("DvtAxisAutomation",D.$t);D.F.l(D.$t,D.gn,"DvtAxisAutomation");D.$t.prototype.bx=function(b){if((b=(0,D.Dc)(this.Ph.Va(),b))&&b instanceof D.rc&&this.rd.groups){b=b.Gl().id;for(var c=0;c<this.rd.groups.length;c++)if(this.rd.groups[c]==b)return"item["+c+"]"}return D.r};D.$t.prototype.bs=function(b){if(this.Zba instanceof D.vB){var c=b.indexOf("["),d=b.indexOf("]");if(0<c&&0<d)return b=b.substring(c+1,d),this.Zba.Cw(this.Ph.e)[b].Ea()}return D.r};
D.$t.prototype.getDomElementForSubId=D.$t.prototype.bs;
D.Wt=function(){this.Init({skyros:D.DJ,alta:D.EJ})};D.F.l(D.Wt,D.Mg,"DvtAxisDefaults");D.EJ={axisLine:{lineColor:"#9E9E9E"},majorTick:{lineColor:"rgba(196,206,215,0.4)"},minorTick:{lineColor:"rgba(196,206,215,0.2)"},tickLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},titleStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;")};
D.DJ={position:D.r,baselineScaling:"zero",axisLine:{lineColor:"#8A8DAC",lineWidth:1,rendered:"on"},majorTick:{lineColor:"rgba(138,141,172,0.4)",lineWidth:1,rendered:"auto",lineStyle:"solid"},minorTick:{lineColor:"rgba(138,141,172,0.20)",lineWidth:1,rendered:"off",lineStyle:"solid"},tickLabel:{scaling:"auto",style:new D.P("font-size: 11px; color: #333333;"),rotation:"auto",rendered:"on"},titleStyle:new D.P("font-size: 11px; color: #737373;"),startGroupOffset:0,endGroupOffset:0,layout:{gapRatio:1,titleGap:4,
verticalAxisGap:3,horizontalAxisGap:5},_useBaselineColor:D.u,isLayout:D.u};
D.Yt=function(b){this.Init(b.e,b.Kf,b);this.Ph=b};D.F.l(D.Yt,D.Bc,"DvtAxisEventManager");D.Yt.prototype.Ds=function(b,c){c instanceof D.rc&&c.Gl()!=D.r&&this.Ug(new D.no(b,c.Gl()),this.Ph)};
D.Zt={};D.F.l(D.Zt,D.F,"DvtAxisRenderer");D.Zt.Vra=5;D.Zt.L=function(b,c){var d=b.Da(),e=(0,D.iD)(b.e,d,c);b.Ib=e;"off"!=d.rendered&&(b.eZ(c.clone()),D.Zt.PS(b,e,c),D.Zt.yL(b,e,c))};
D.Zt.PS=function(b,c,d){var e=b.Da();if(e.title&&(c=e.position,!("radial"==c||"tangential"==c)))if(e.isLayout&&"bottom"==c&&(c="top"),b="top"==c||"bottom"==c?D.Zt.dda(b.Va(),b,e.title,e.titleStyle,d.g,d.j):D.Zt.dda(b.Va(),b,e.title,e.titleStyle,d.j,d.g)){var f=b.Vb(),e=window.Math.ceil(e.layout.titleGap*e.layout.gapRatio);"top"==c?(b.fa(d.x+d.g/2-f.g/2),b.ua(d.y),d.y+=f.j+e,d.j-=f.j+e):"bottom"==c?(b.fa(d.x+d.g/2-f.g/2),b.ua(d.y+d.j-f.j),d.j-=f.j+e):"left"==c?(b.Oi(3*window.Math.PI/2),(0,D.Ya)(b,
d.x,d.y+d.j/2+f.g/2),d.x+=f.j+e,d.g-=f.j+e):"right"==c&&(b.Oi(3*window.Math.PI/2),(0,D.Ya)(b,d.x+d.g-f.j,d.y+d.j/2+f.g/2),d.g-=f.j+e)}};D.Zt.yL=function(b,c,d){var e=b.Da();"on"==e.tickLabel.rendered&&(e=e.position,"top"==e||"bottom"==e?D.Zt.Gya(b,c,d):"tangential"==e?D.Zt.Hya(b,c,d):D.Zt.Iya(b,c,d))};
D.Zt.Gya=function(b,c,d){for(var e=c.Cw(b.e),f=b.Da().isLayout,g=0,h=D.K.R(b.e),k=0;k<e.length;k++){var m=e[k];if(m!=D.r){if(c.TU()){!f&&b.OR&&(m=D.qc.Wb(m,d.j,d.g,b)?m:D.r);if(!m)continue;h?m.Ik():m.Bi();m.O(d.y)}else m.Uo(),m.ua(d.y);b.Va().ma(m,new D.rc(m.Po,D.r,D.r,{type:D.au.qx,id:m.ne()}));b.k(m);g=window.Math.max(g,D.qc.Xj(m).j)}}c=c.Cw(b.e,1);f=0;if(c!=D.r)for(k=0;k<c.length;k++)m=c[k],m!=D.r&&(b.Va().ma(m,new D.rc(D.r,D.r,D.r,{type:D.au.qx,id:m.ne()})),e[k]!=D.r&&(f=e[k].Vb().g/2),h?m.fa(m.ea()+
f):m.fa(m.ea()-f),m.Uo(),m.ua(d.y+g),b.k(m))};
D.Zt.Iya=function(b,c,d){var e=b.Da(),f=e.isLayout,g=e._alwaysAlignRight,h=e.position,e=D.K.R(b.e),k="radial"==h&&e||f&&"left"==h||!g&&!f&&"right"==h,m;"radial"==h?(m=d.x+d.g/2,m+=D.Zt.Vra*(e?1:-1)):m=k?d.x:d.x+d.g;for(var g=function(e){!f&&b.OR&&(e=D.qc.Wb(e,d.g,d.j,b)?e:D.r);if(e){b.Va().ma(e,new D.rc(e.Po,D.r,D.r,{type:D.au.qx,id:e.ne()}));e.fa(m);k?e.Ik():e.Bi();if("radial"==h){var g=e.ha();e.ua(d.y+d.j/2-g);var p=e.C(),q=0.15*p.j,g=g+p.j/2>c.Gka()&&"circle"==b.Da().polarGridShape?1:0.3,p=window.DvtPathUtils.EH(p.x-
q,p.y,p.g+2*q,p.j,2,2,2,2),p=new D.Ra(b.e,p);p.na("#FFFFFF",g);b.k(p)}b.k(e)}},p=c.Cw(b.e),e=0;e<p.length;e++){var q=p[e];q!=D.r&&g(q)}p=c.Cw(b.e,1);if(p!=D.r)for(e=0;e<p.length;e++)q=p[e],q!=D.r&&g(q)};D.Zt.Hya=function(b,c,d){c=c.Cw(b.e);for(var e=0;e<c.length;e++){var f=c[e];if(f!=D.r){var g=f.ne();b.Va().ma(f,new D.rc(f.bf()?g:D.r,D.r,D.r,{type:D.au.qx,id:g}));f.F(d.x+d.g/2);f.O(d.y+d.j/2);b.k(f)}}};
D.Zt.dda=function(b,c,d,e,f,g){var h={type:D.au.tp,id:D.n};d=new D.pc(c.e,d,0,0);d.Ia(e);return D.qc.Wb(d,f,g,c)?(b.ma(d,new D.rc(d.Po,D.r,D.r,h)),d):D.r};
D.rJ=(0,D.z)();D.F.l(D.rJ,D.F,"DvtAxisInfo");D.iD=function(b,c,d){return c.timeAxisType&&"disabled"!=c.timeAxisType?new D.wB(b,c,d):(0,window.isNaN)(c.dataMin)&&(0,window.isNaN)(c.dataMax)?new D.vB(b,c,d):new D.CJ(b,c,d)};D.E=D.rJ.prototype;
D.E.Init=function(b,c,d){this.e=b;this.jd=c.position;this.Mj=c._radius;"top"==this.jd||"bottom"==this.jd?(this.Xg=d.x,this.ph=d.x+d.g):"left"==this.jd||"right"==this.jd?(this.Xg=d.y,this.ph=d.y+d.j):"radial"==this.jd?(this.Xg=0,this.ph=this.Mj):"tangential"==this.jd&&(D.K.R(b)?(this.Xg=2*window.Math.PI,this.ph=0):(this.Xg=0,this.ph=2*window.Math.PI));this.MGa=this.mi=this.ni=this.uf=this.gf=this.Xd=this.Hc=D.r;this.Rn=this.io=0;c.leftBuffer==D.r&&(c.leftBuffer=window.Infinity);c.rightBuffer==D.r&&
(c.rightBuffer=window.Infinity);this.X=c};D.E.H=(0,D.C)("X");D.E.Cw=(0,D.ca)(D.r);D.E.NG=(0,D.ca)(D.r);D.E.iz=function(){return[]};D.E.uC=function(){return[]};D.E.Tj=(0,D.ca)(D.r);D.E.kC=(0,D.ca)(D.r);D.E.jC=(0,D.ca)(D.r);D.E.Gn=(0,D.ca)(D.r);D.E.Vc=(0,D.ca)(D.r);D.E.OG=(0,D.ca)(D.r);D.E.TU=(0,D.ca)(D.u);
D.E.lp=function(b,c,d){if("tangential"==this.jd){var e=16/180*window.Math.PI,f=1/180*window.Math.PI,g=this.Mj+5;if(d<f||d>2*window.Math.PI-f)g+=5;b=new D.pc(b,c,g*window.Math.sin(d),-g*window.Math.cos(d));d<f||window.Math.abs(d-window.Math.PI)<f||d>2*window.Math.PI-f?b.of():d<window.Math.PI?b.Ik():b.Bi();window.Math.abs(d-window.Math.PI/2)<e||window.Math.abs(d-3*window.Math.PI/2)<e?b.Ce():d<window.Math.PI/2||d>3*window.Math.PI/2?b.qw():b.Uo()}else b=new D.pc(b,c,d,d),b.Ce(),b.of();b.Ia(this.X.tickLabel.style);
return b};D.zJ=function(b,c,d,e){var f=!D.K.da()||1<D.K.FM();"radial"==b.jd?("polygon"==b.X.polarGridShape?(e=D.Xf.aH(0,0,b.X._numGroups,e),c=new D.vc(c,e)):c=new D.Rd(c,0,0,e),(0,D.ed)(c)):"tangential"==b.jd?(c=new D.jc(c,0,0,b.Mj*window.Math.sin(e),-b.Mj*window.Math.cos(e)),0.01>e%window.Math.PI/2&&f&&(0,D.kc)(c)):(c=new D.jc(c,e,e,e,e),f&&(0,D.kc)(c));c.Y(d);c.la(D.u);return c};
D.xJ=function(b,c,d){if(!c||0>=c.length)return D.u;var e=(0,window.parseInt)(b.X.tickLabel.style.v("font-size")),f=b instanceof D.CJ?0.55*e:0.3*e,g=b instanceof D.CJ?0.35*e:0.1*e,f=(e="left"==b.jd||"right"==b.jd||"radial"==b.jd)||b.TU()?g:f;b=D.K.R(b.e);for(var h,k,m,p=0;p<c.length;p+=d+1)if(c[p]!=D.r)if(h==D.r||k==D.r)e?(h=c[p].y,k=c[p].y+c[p].j):(h=c[p].x,k=c[p].x+c[p].g);else{if(e){if(g=c[p].y,m=c[p].y+c[p].j,g>=h&&g-f<k||g<h&&m+f>h)return D.o}else if(g=c[p].x,m=c[p].x+c[p].g,!b&&g-f<k||b&&m+f>
h)return D.o;h=g;k=m}return D.u};D.vJ=function(b,c,d){for(var e=0,f=(0,D.xJ)(b,d,e);f;)e++,f=(0,D.xJ)(b,d,e);if(0<e){b=[];for(d=0;d<c.length;d+=e+1)b.push(c[d]);return b}return c};D.yJ=function(b,c){for(var d=[],e=0;e<b.length;e++){var f=b[e];f==D.r?d.push(D.r):(f=f.Vb(c),d.push(f))}return d};
D.uJ=function(b,c,d,e){var f=[];"undefined"==typeof e&&(e=1);for(var g=0;g<c.length;g++){var h=c[g];if(h==D.r)f.push(D.r);else{d.k(h);var k=D.qc.Xj(h),m=k.g*e,k=k.j;d.removeChild(h);h=b.TU()?new D.I(h.M()-k/2,h.K()-m/2,k,m):new D.I(h.ea()-m/2,h.ha()-k/2,m,k);f.push(h)}}return f};D.E=D.rJ.prototype;D.E.tU=(0,D.ca)(D.r);D.E.UV=(0,D.z)();D.E.zU=(0,D.ca)(D.r);D.E.VV=(0,D.z)();D.E.JM=(0,D.ca)(D.r);D.E.yU=(0,D.ca)(D.r);D.E.zw=(0,D.C)("gf");D.E.yw=(0,D.C)("uf");D.E.ls=(0,D.C)("Hc");D.E.Hw=(0,D.C)("Xd");
D.E.I5=(0,D.C)("ni");D.E.H5=(0,D.C)("mi");D.E.Dw=(0,D.ca)(0);D.E.Gka=(0,D.C)("ph");D.E.HU=(0,D.C)("io");D.E.kU=(0,D.C)("Rn");
D.CJ=function(b,c,d){this.Init(b,c,d)};D.F.l(D.CJ,D.rJ,"DvtDataAxisInfo");D.E=D.CJ.prototype;
D.E.Init=function(b,c,d){D.CJ.q.Init.call(this,b,c,d);"top"==this.jd||"bottom"==this.jd?("off"!=c.tickLabel.rendered&&"off"!=c.rendered&&(this.io=window.Math.max(10-c.leftBuffer,0),this.Rn=window.Math.max(10-c.rightBuffer,0)),D.K.R(b)?(this.yi=this.ph-this.Rn,this.Ak=this.Xg+this.io):(this.yi=this.Xg+this.io,this.Ak=this.ph-this.Rn)):"tangential"==this.jd||"radial"==this.jd?(this.yi=this.Xg,this.Ak=this.ph):(this.yi=this.ph,this.Ak=this.Xg);this.gf=c.min;this.uf=c.max;this.Hc=c.viewportMin==D.r?this.gf:
c.viewportMin;this.Xd=c.viewportMax==D.r?this.uf:c.viewportMax;this.fh=c.step;this.zB=c.minorStep;this.P1=c.minStep;this.ah=D.r;c.tickLabel!=D.r&&(this.ah=c.tickLabel.converter);this.ni=c.dataMin;this.mi=c.dataMax;b="zero"==this.X.baselineScaling;c="on"==this.X._continuousExtent;b&&(this.ni=window.Math.min(0,this.ni),this.mi=window.Math.max(0,this.mi));d=(0,D.JJ)(this,this.gf!=D.r?this.gf:this.ni,this.uf!=D.r?this.uf:this.mi);this.ni==this.mi&&(this.ni-=3*d,this.mi+=2*d);if(this.gf==D.r)if(b&&0<=
this.ni)this.gf=0;else if(c)this.gf=this.ni-0.1*(this.mi-this.ni),0<=this.ni&&(this.gf=window.Math.max(this.gf,0));else if(!b&&this.uf!=D.r)for(this.gf=this.uf;this.gf>this.ni;)this.gf-=d;else this.gf=window.Math.floor(this.ni/d)*d;if(this.uf==D.r)if(b&&0>=this.mi)this.uf=0;else if(c)this.uf=this.mi+0.1*(this.mi-this.ni),0>=this.mi&&(this.uf=window.Math.min(this.uf,0));else if(b)this.uf=(window.Math.floor(this.mi/d)+1)*d;else for(this.uf=this.gf;this.uf<=this.mi;)this.uf+=d;this.uf==this.gf&&(this.uf=
100,this.gf=0,d=(this.uf-this.gf)/10);this.Hc==D.r&&(this.Hc=this.gf);this.Xd==D.r&&(this.Xd=this.uf);if(this.Hc!=this.gf||this.Xd!=this.uf)d=(0,D.JJ)(this,this.Hc,this.Xd);this.fh=this.fh?this.fh:d;this.P1!=D.r&&this.fh<this.P1&&(this.fh=this.P1);this.pF=(this.Xd-this.YG())/this.fh;this.zB!=D.r&&2<=this.fh/this.zB?this.uF=this.fh/this.zB:(this.uF=2,this.zB=this.fh/this.uF)};
D.E.YG=function(){return"zero"==this.X.baselineScaling||"on"==this.X._continuousExtent&&this.X.min==D.r?window.Math.ceil(this.Hc/this.fh)*this.fh:window.Math.ceil((this.Hc-this.gf)/this.fh)*this.fh+this.gf};
D.E.Cw=function(b,c){if(c&&0<c)return D.r;var d=[],e=[],e=b.Ac,f="tangential"==this.jd;this.X.tickLabel&&this.X.tickLabel.scaling&&(this.FP=new D.LB(this.Hc,this.Xd,this.fh,this.X.tickLabel.scaling,this.X.tickLabel.autoPrecision?this.X.tickLabel.autoPrecision:"on"));for(var g=0;g<=this.pF;g++){var h=g*this.fh+this.YG();if(!(f&&h==this.Xd)){var k=this.vo(h),h=this.Vc(h),k=this.lp(b,k,h);d.push(k)}}f||(e=(0,D.yJ)(d,e),d=(0,D.vJ)(this,d,e));return d};
D.E.NG=function(b){var c=this.X.axisLine;return"on"==c.rendered?(c=new D.Vd(c.lineColor,1,c.lineWidth),(0,D.zJ)(this,b,c,this.Ak)):D.r};
D.E.iz=function(b){var c=[],d,e,f=this.X.majorTick;if("off"==f.rendered)return c;var g=new D.Vd(f.lineColor,1,f.lineWidth);f.lineStyle&&g.aa((0,D.ii)(f.lineStyle));f=g.clone();if(this.X._useBaselineColor){var h=D.S.B(this.X.axisLine.lineColor,0.75);f.ts(h)}for(h=0;h<=this.pF;h++)d=h*this.fh+this.YG(),"tangential"==this.jd&&d==this.Xd||(e=0==d?f:g,d=this.Vc(d),e=(0,D.zJ)(this,b,e,d),c.push(e));return c};
D.E.uC=function(b){var c=[],d,e=this.X.minorTick;if("on"!=e.rendered)return c;var f=new D.Vd(e.lineColor,1,e.lineWidth);e.lineStyle&&f.aa((0,D.ii)(e.lineStyle));for(e=-1;e<=this.pF;e++)for(var g=e*this.fh+this.YG(),h=1;h<this.uF;h++){d=g+h*this.zB;if(d>this.Xd)break;d<this.Hc||(d=this.Vc(d),d=(0,D.zJ)(this,b,f,d),c.push(d))}return c};D.E.Tj=function(b){return b<this.Hc||b>this.Xd?D.r:this.Vc(b)};
D.E.kC=function(b){var c=window.Math.min(this.yi,this.Ak),d=window.Math.max(this.yi,this.Ak);b<c?b=c:b>d&&(b=d);return this.Gn(b)};D.E.jC=function(b){b<this.Hc?b=this.Hc:b>this.Xd&&(b=this.Xd);return this.Vc(b)};D.E.Gn=function(b){return this.Hc+(b-this.yi)/(this.Ak-this.yi)*(this.Xd-this.Hc)};D.E.Vc=function(b){return this.yi+(b-this.Hc)/(this.Xd-this.Hc)*(this.Ak-this.yi)};D.E.OG=function(){var b=0;0>this.Xd?b=this.Xd:0<this.Hc&&(b=this.Hc);return this.Tj(b)};
D.E.vo=function(b){if(this.ah&&(this.ah.getAsString||this.ah.format)){if(this.FP)return this.FP.sq(b,this.ah);if(this.ah.getAsString)return this.ah.getAsString(b);if(this.ah.format)return this.ah.format(b)}else{if(this.FP)return this.FP.sq(b);var c=window.Math.log(this.fh)/window.Math.log(10),c=window.Math.max(window.Math.ceil(-c),0);return b.toFixed(c)}};
D.JJ=function(b,c,d){if(b.fh)return b.fh;b=d-c;if(0==b)return 0==c?10:window.Math.pow(10,window.Math.floor(window.Math.log(c)/window.Math.LN10)-1);c=window.Math.log(b)/window.Math.log(10);c=window.Math.pow(10,window.Math.ceil(c)-2);b=window.Math.round(b/c);return(10<=b&&14>=b?2:15<=b&&19>=b?3:20<=b&&24>=b?4:25<=b&&45>=b?5:46<=b&&80>=b?10:20)*c};D.E=D.CJ.prototype;D.E.tU=(0,D.C)("pF");D.E.UV=function(b){this.pF=b;this.fh=(this.Xd-this.Hc)/this.pF};D.E.zU=(0,D.C)("uF");
D.E.VV=function(b){this.uF=b;this.zB=this.fh/this.uF};D.E.JM=(0,D.C)("fh");D.E.yU=(0,D.C)("zB");D.E.Dw=function(){return(this.uf-this.gf)/64};D.E.HU=function(){return("top"==this.jd||"bottom"==this.jd)&&D.K.R(this.e)?this.Rn:this.io};D.E.kU=function(){return("top"==this.jd||"bottom"==this.jd)&&D.K.R(this.e)?this.io:this.Rn};
D.vB=function(b,c,d){this.Init(b,c,d)};D.F.l(D.vB,D.rJ,"DvtGroupAxisInfo");
D.vB.prototype.Init=function(b,c,d){D.vB.q.Init.call(this,b,c,d);b=D.K.R(b);if(("top"==this.jd||"bottom"==this.jd)&&b)d=this.Xg,this.Xg=this.ph,this.ph=d;this.st=c.groups;d=0<c.endGroupOffset?(0,window.Number)(c.endGroupOffset):0;var e=0<c.startGroupOffset?(0,window.Number)(c.startGroupOffset):0;this.ni=0;this.mi=this.st.length-1;this.gf=c.min==D.r?this.ni-e:c.min;this.uf=c.max==D.r?this.mi+d:c.max;this.Hc=c.viewportMin==D.r?this.gf:c.viewportMin;this.Xd=c.viewportMax==D.r?this.uf:c.viewportMax;var f=
(0,D.sJ)(this,c.viewportStartGroup),g=(0,D.sJ)(this,c.viewportEndGroup);-1!=f&&(this.Hc=f-e);-1!=g&&(this.Xd=g+d);this.Dia=b?c.rightBuffer:c.leftBuffer;this.Lda=b?c.leftBuffer:c.rightBuffer;this.cfa=D.u;this.c3=c._renderGridAtLabels;this.Rv=D.r};D.wJ=function(b,c,d,e){var f,g=D.K.R(b.e);b.cfa=D.o;(0,D.tJ)(b,e,e,c);for(var h=0;h<c.length;h++)e=c[h],e!=D.r&&(f=e.ea(),e.fa(0),e.ua(0),g?e.Oi(window.Math.PI/2):e.Oi(3*window.Math.PI/2),e.F(f));d=(0,D.uJ)(b,c,d);return(0,D.vJ)(b,c,d)};
D.vB.prototype.TU=(0,D.C)("cfa");D.tJ=function(b,c,d,e){c=window.Math.max(c-b.Dia,0);d=window.Math.max(d-b.Lda,0);var f=D.K.R(b.e);b.Xg+=(c-b.io)*(f?-1:1);b.ph-=(d-b.Rn)*(f?-1:1);for(f=0;f<e.length;f++){var g=e[f];g&&g.fa(b.Tj(f))}b.io=c;b.Rn=d};D.E=D.vB.prototype;D.E.Cw=function(b,c){if(c&&0<c)return D.r;this.Rv||(this.Rv=this.w0(b));return this.Rv};
D.E.w0=function(b){for(var c=[],d=b.Ac,e="top"==this.jd||"bottom"==this.jd,f=D.K.R(b),g=this.st.length,h,k,m=0;m<g;m++){var p=(0,D.JB)(this,m),q=this.Tj(m);q!=D.r?(k=this.lp(b,p,q),c.push(k),h||(h=k)):c.push(D.r)}if("tangential"==this.jd)return c;b=h.Vb();e&&(this.X._startOverflow!=D.r&&this.X._endOverflow!=D.r?(g=this.X._startOverflow,f=this.X._endOverflow):(h=k.Vb(),g=f?b.g+b.x-this.Xg:this.Xg-b.x,f=f?this.ph-h.x:h.g+h.x-this.ph),(g>this.Dia||f>this.Lda)&&(0,D.tJ)(this,g,f,c));f=[];f=(0,D.uJ)(this,
c,d,0.3);g=(0,D.uJ)(this,c,d);if(!(0,D.xJ)(this,g,0))return c;if(e){if("auto"==this.X.tickLabel.rotation){if((0,D.xJ)(this,f,0))return(0,D.wJ)(this,c,d,b.j/2);f=(0,D.yJ)(c,d);return(0,D.xJ)(this,f,0)?(0,D.wJ)(this,c,d,b.j/2):c}f=(0,D.yJ)(c,d);return(0,D.vJ)(this,c,f)}return(0,D.vJ)(this,c,g)};D.E.NG=function(b){var c=this.X.axisLine;return"on"==c.rendered?(c=new D.Vd(c.lineColor,1,c.lineWidth),(0,D.zJ)(this,b,c,0)):D.r};
D.E.iz=function(b){var c=[],d,e=this.X.majorTick,f=new D.Vd(e.lineColor,1,e.lineWidth);e.lineStyle&&f.aa((0,D.ii)(e.lineStyle));e=e.rendered;if("on"==e||"auto"==e&&"tangential"==this.jd)for(var e=this.st.length,g=0;g<e;g++){if(this.c3)d=this.Tj(g);else if(this.Tj(g+0.5))d=this.Tj(g+0.5);else continue;d!=D.r&&(d=(0,D.zJ)(this,b,f,d),c.push(d))}return c};D.E.Tj=function(b){return b<this.Hc||b>this.Xd?D.r:this.Vc(b)};
D.E.kC=function(b){var c=window.Math.min(this.Xg,this.ph),d=window.Math.max(this.Xg,this.ph);b<c?b=c:b>d&&(b=d);return this.Gn(b)};D.E.jC=function(b){b<this.Hc?b=this.Hc:b>=this.Xd&&(b=this.Xd);return this.Vc(b)};D.E.Gn=function(b){return this.Hc+(b-this.Xg)/((this.ph-this.Xg)/(this.Xd-this.Hc))};D.E.Vc=function(b){return this.Xg+(b-this.Hc)*((this.ph-this.Xg)/(this.Xd-this.Hc))};D.JB=function(b,c){c=window.Math.round(c);if(0>c||c>=b.st.length)return D.r;var d=b.st[c];d&&d.name&&(d=d.name);return d};
D.sJ=function(b,c){if(c==D.r)return-1;for(var d=-1,e=0;e<b.st.length;e++)if(c==(0,D.JB)(b,e)){d=e;break}return d};D.vB.prototype.Dw=(0,D.ca)(1);
D.LB=function(b,c,d,e,f){this.mv=new D.Wb;this.Init(b,c,d,e,f)};D.F.l(D.LB,D.AJ,"DvtLinearScaleAxisValueFormatter");
D.LB.prototype.Init=function(b,c,d,e,f){this.jia={};this.Lr=[];this.Oda={};var g=function(b,c,d){var e;this.mv&&d&&(e=(0,D.Na)(this.mv,d,D.r));d={ss:c,GEa:e};this.jia[b]=d;this.Lr.push(d);this.Oda[c]=d};g.call(this,"none",0);g.call(this,"thousand",3,"SCALING_SUFFIX_THOUSAND");g.call(this,"million",6,"SCALING_SUFFIX_MILLION");g.call(this,"billion",9,"SCALING_SUFFIX_BILLION");g.call(this,"trillion",12,"SCALING_SUFFIX_TRILLION");g.call(this,"quadrillion",15,"SCALING_SUFFIX_QUADRILLION");this.Lr.sort(function(b,
c){return b.ss<c.ss?-1:b.ss>c.ss?1:0});var h=D.u,k,m,g=D.u;"off"!==f&&(g=D.o);e||(e="auto");if(e=this.jia[e])m=e.ss;"number"!==typeof m&&(h=D.o);if(h)if(h=window.Math.max(window.Math.abs(b),window.Math.abs(c)),h=(0,D.BJ)(h),m=0,h<=this.Lr[0].ss)m=this.Lr[0].ss;else if(h>=this.Lr[this.Lr.length-1].ss)m=this.Lr[this.Lr.length-1].ss;else for(e=this.Lr.length-1;0<=e;e--)if(this.Lr[e].ss<=h){m=this.Lr[e].ss;break}g===D.o&&(0==d&&b==c?(b=m-(0,D.BJ)(c),k=0>=b?3+b:window.Math.max(b,4)):k=window.Math.max(m-
(0,D.BJ)(d),0));this.Jza=g;this.o3=m;this.S_=k};
D.LB.prototype.sq=function(b,c){var d=(0,window.parseFloat)(b);if((0,window.isNaN)(d))return b;var e;if(0<this.o3){for(e=0;e<this.o3;e++)d/=10;e=this.Oda[this.o3].GEa}if(c&&c.getAsString)d=c.getAsString(d);else if(c&&c.format)d=c.format(d);else if(this.Jza&&!(0,window.isNaN)((0,window.parseFloat)(d))&&(d=(0,window.parseFloat)((new window.Number(d)).toFixed(this.S_)),d=""+d,0<this.S_)){-1==d.indexOf(".")&&(d+=".");for(var f=d.substring(d.indexOf(".")+1).length;f<this.S_;)d+="0",f++}"string"===typeof e&&
(d+=e);return d};D.BJ=function(b){b=0<=b?b:-b;var c=0;if(1E-15>b)return 0;if(window.Infinity==b)return window.Number.MAX_VALUE;if(10<=b)for(;10<=b;)c+=1,b/=10;else if(1>b)for(;1>b;)c-=1,b*=10;return c};
D.wB=function(b,c,d){this.Init(b,c,d)};D.F.l(D.wB,D.rJ,"DvtTimeAxisInfo");D.FJ=864E5*(365/12);
D.wB.prototype.Init=function(b,c,d){D.wB.q.Init.call(this,b,c,d);"top"==this.jd||"bottom"==this.jd?(!c._isOverview&&"on"==c.tickLabel.rendered&&(this.io=window.Math.max(10-c.leftBuffer,0),this.Rn=window.Math.max(10-c.rightBuffer,0)),D.K.R(b)?(this.yi=this.ph-this.Rn,this.Ak=this.Xg+this.io):(this.yi=this.Xg+this.io,this.Ak=this.ph-this.Rn)):(this.yi=this.Xg,this.Ak=this.ph);this.ah=D.r;c.tickLabel!=D.r&&(this.ah=c.tickLabel.converter);this.st=c.groups;this.ni=c.dataMin;this.mi=c.dataMax;this.Xm=0<
this.st.length?(this.mi-this.ni)/(this.st.length-1):0;b=0<c.endGroupOffset?c.endGroupOffset*this.Xm:0;d=0<c.startGroupOffset?c.startGroupOffset*this.Xm:0;this.gf=c.min!=D.r?c.min:this.ni-d;this.uf=c.max!=D.r?c.max:this.mi+b;this.Hc=c.viewportMin==D.r?this.gf:c.viewportMin;this.Xd=c.viewportMax==D.r?this.uf:c.viewportMax;c.viewportStartGroup!=D.r&&(this.Hc=c.viewportStartGroup-d);c.viewportEndGroup!=D.r&&(this.Xd=c.viewportEndGroup+b);this.Qia=0;this.g4=this.Xd-this.Hc;this.XR=this.yt=this.Jfa=this.Rv=
D.r;this.GR=D.o;b=new D.Wb;this.vm=[(0,D.Na)(b,"MONTH_SHORT_JANUARY",D.r),(0,D.Na)(b,"MONTH_SHORT_FEBRUARY",D.r),(0,D.Na)(b,"MONTH_SHORT_MARCH",D.r),(0,D.Na)(b,"MONTH_SHORT_APRIL",D.r),(0,D.Na)(b,"MONTH_SHORT_MAY",D.r),(0,D.Na)(b,"MONTH_SHORT_JUNE",D.r),(0,D.Na)(b,"MONTH_SHORT_JULY",D.r),(0,D.Na)(b,"MONTH_SHORT_AUGUST",D.r),(0,D.Na)(b,"MONTH_SHORT_SEPTEMBER",D.r),(0,D.Na)(b,"MONTH_SHORT_OCTOBER",D.r),(0,D.Na)(b,"MONTH_SHORT_NOVEMBER",D.r),(0,D.Na)(b,"MONTH_SHORT_DECEMBER",D.r)];this.c3=c._renderGridAtLabels};
D.KB=function(b,c,d){var e=D.r,f=D.r;if(b.ah&&b.ah.getAsString)e=b.ah.getAsString(c);else if(b.ah&&b.ah.format)e=b.ah.format(c);else if(31536E6<=b.Xm)e=(0,D.GJ)(b,c,D.u,D.u,D.o);else if(31536E6<=b.g4||24192E5<=b.Xm){if(d==D.r||d.getMonth()!=c.getMonth())e=(0,D.GJ)(b,c,D.u,D.o,D.u);if(d==D.r||d.getYear()!=c.getYear())f=(0,D.GJ)(b,c,D.u,D.u,D.o)}else if(24192E5<=b.g4||864E5<=b.Xm){if(d==D.r||d.getDate()!=c.getDate())e=(0,D.GJ)(b,c,D.o,D.u,D.u);d==D.r||d.getYear()!=c.getYear()?f=(0,D.GJ)(b,c,D.u,D.o,
D.o):d.getMonth()!=c.getMonth()&&(f=(0,D.GJ)(b,c,D.u,D.o,D.u))}else{if(36E5<=b.g4||6E4<=b.Xm){if(d==D.r||d.getHours()!=c.getHours()||d.getMinutes()!=c.getMinutes())e=(0,D.HJ)(b,c,D.u)}else if(d==D.r||d.getSeconds()!=c.getSeconds())e=(0,D.HJ)(b,c,D.o);d==D.r||d.getMonth()!=c.getMonth()?f=(0,D.GJ)(b,c,D.o,D.o,D.u):d.getDate()!=c.getDate()&&(f="left"==b.jd||"right"==b.jd?(0,D.GJ)(b,c,D.o,D.o,D.u):(0,D.GJ)(b,c,D.o,D.u,D.u))}return[e,f]};
D.GJ=function(b,c,d,e,f){var g=c.getFullYear(),h;h=b.vm&&12<=b.vm.length?b.vm[c.getMonth()]:c.toString().split(" ")[1];c=c.getDate();if(b.vm&&17<b.vm.length){var k=b.vm[17],g=g+b.vm[16];c+=k}k="DMY";b.vm&&15<b.vm.length&&(k=b.vm[15]);b="";for(var m=0;m<k.length;m++)d&&"D"==k[m]?b+=c+" ":e&&"M"==k[m]?b+=h+" ":f&&"Y"==k[m]&&(b+=g+" ");return 0<b.length?b.slice(0,b.length-1):b};
D.HJ=function(b,c,d){var e=c.getHours(),f=c.getMinutes();c=c.getSeconds();var g="",h="",k=D.u;b.vm!=D.r&&14<b.vm&&(g=b.vm[window.DvtTimeAxis.qGa],h=b.vm[window.DvtTimeAxis.RGa],k="t"==b.vm[14]);b=""!=g&&""!=h;var m;b&&(m=h,12<e?(e-=12,m=h):0==e?(m=g,e=12):12>e&&(m=g));e=(10>e?"0"+e:""+e)+":"+(10>f?"0"+f:""+f);d&&(e+=":"+(10>c?"0"+c:""+c));return b?k?m+" "+e:e+" "+m:e};
D.wB.prototype.w0=function(b){var c=[],d=[],e=[],f=[],g=D.r,h=0,k=0,k=b.Ac,m=D.K.R(b),p="left"==this.jd||"right"==this.jd,q="off"!=this.X.zoomAndScroll;if(q)var t=D.o;var v=0;p&&D.K.tz()&&(v=0.2*(0,window.parseInt)(this.X.tickLabel.style.v("font-size")));var w=[],h=0;if("mixedFrequency"==this.X.timeAxisType){for(var A=this.Hc,h=31536E6<=this.Xm?31536E6:this.Xm>=D.FJ?D.FJ:864E5<=this.Xm?864E5:36E5<=this.Xm?36E5:6E4<=this.Xm?6E4:1E3;A<=this.Xd;)w.push(A),A+=h;h=window.Math.floor(this.Xm/h)-1}else w=
this.st;for(var D$=0;D$<w.length;D$++){var A=w[D$],J=this.Tj(A);if(J!=D.r){var A=new window.Date(A+this.Qia),G=(0,D.KB)(this,A,g),g=G[0],G=G[1];g!=D.r?(G!=D.r?c.push(this.lp(b,g,J+v)):c.push(this.lp(b,g,J)),e.push(J)):(c.push(D.r),e.push(D.r));q&&t&&(J=this.Hc?this.Tj(this.Hc):J,t=D.u);G!=D.r?(g=D.r,g=G!=D.r?this.lp(b,G,J-v):this.lp(b,G,J),f.push(J),p||(m?g.Bi():g.Ik()),d.push(g),this.GR=D.u):(d.push(D.r),f.push(D.r));g=A}}b=c;m=(0,D.yJ)(c,k);v=h;h=[];for(t=0;t<m.length;t++)m[t]!=D.r&&h.push(m[t]);
m=v;for(t=(0,D.xJ)(this,h,m);t;)m++,t=(0,D.xJ)(this,h,m);h=h.length;if(0<m)for(t=v=0;t<b.length;t++)b[t]!=D.r&&(0!=v%(m+1)&&(b[t]=D.r,h--),v++);b=d;k=(0,D.yJ)(d,k);if(!k||0>=k.length)k=D.u;else{m=(t="left"==this.jd||"right"==this.jd)?this.X.layout.verticalAxisGap:this.X.layout.horizontalAxisGap;v=0;if(k[0]!=D.r){t?(w=k[0].y,D$=k[0].y+k[0].j):(w=k[0].x,D$=k[0].x+k[0].g);v++;for(A=1;A<k.length;A++)k[A]!=D.r&&(t?(J=k[A].y,g=k[A].y+k[A].j):(J=k[A].x,g=k[A].x+k[A].g),(J>=w&&J-m<D$||J<w&&g+m>w)&&(b[A]=
D.r),b[A]!=D.r&&(w=J,D$=g,v++))}k=v}if(!q)if(h<=1.5*k&&1<k){c=d;d=D.r;for(q=0;q<c.length;q++)c[q]!=D.r&&c[q].of()}else 2>k&&(d=D.r);2>k&&(this.GR=D.o);if(p&&d!=D.r){var p=c,q=d,L=0.1*(0,window.parseInt)(this.X.tickLabel.style.v("font-size")),k=function(b,c){return c.y>=b.y&&c.y-L<b.y+b.j||c.y<b.y&&c.y+c.j+L>b.y?D.o:D.u},t=D.r,h=D.u;for(b=0;b<p.length;b++)if(p[b]&&q[b])if(p[b].Uo(),q[b].qw(),t&&k(t,p[b].Vb())){h=D.o;break}else if(p[b+1]&&k(p[b].Vb(),p[b+1].Vb())){h=D.o;break}else t=q[b].Vb();else if(p[b]||
q[b])if(m=p[b]?p[b]:q[b],t&&k(t,m.Vb())){h=D.o;break}else t=m.Vb();if(h){m=h=t=D.r;for(b=0;b<p.length;b++)q[b]?(p[b]=D.r,q[b].Ce(),v=q[b].Vb(),h&&k(h,v)&&(p[t]=D.r),m=v):p[b]&&(v=p[b].Vb(),m&&k(m,v)?p[b]=D.r:(h=v,t=b))}}this.Rv=c;this.Jfa=d;this.yt=e;this.XR=f};D.wB.prototype.Cw=function(b,c){if(c&&1<c)return D.r;this.Rv||this.w0(b);return 1==c?this.Jfa:this.Rv};
D.wB.prototype.NG=function(b){var c=this.X.axisLine;return"on"==c.rendered?(c=new D.Vd(c.lineColor,1,c.lineWidth),(0,D.zJ)(this,b,c,10)):D.r};D.IJ=function(b,c){if(b.c3)return 0;for(var d=b.yt[c],e=D.r,f=c-1;0<=f;f--)if(b.yt[f]!=D.r){e=b.yt[f];break}return e==D.r?window.Infinity:(d-e)/2};D.E=D.wB.prototype;
D.E.iz=function(b){var c=this.X.majorTick;if("on"!=c.rendered)return[];var d=[];if(this.GR)for(var e=0;e<this.yt.length;e++)this.yt[e]!=D.r&&this.Rv[e]!=D.r&&d.push(this.yt[e]-(0,D.IJ)(this,e));else for(e=1;e<this.XR.length;e++)this.XR[e]!=D.r&&d.push(this.XR[e]-(0,D.IJ)(this,e));var f=new D.Vd(c.lineColor,1,c.lineWidth);c.lineStyle&&f.aa((0,D.ii)(c.lineStyle));c=[];for(e=0;e<d.length;e++)d[e]>=this.yi&&d[e]<=this.Ak&&c.push((0,D.zJ)(this,b,f,d[e]));return c};
D.E.uC=function(b){var c=this.X.minorTick;if("on"!=c.rendered||this.GR)return[];for(var d=[],e=0;e<this.yt.length;e++)this.yt[e]!=D.r&&this.Rv[e]!=D.r&&d.push(this.yt[e]-(0,D.IJ)(this,e));var f=new D.Vd(c.lineColor,1,c.lineWidth);c.lineStyle&&f.aa((0,D.ii)(c.lineStyle));c=[];for(e=0;e<d.length;e++)d[e]>=this.yi&&d[e]<=this.Ak&&c.push((0,D.zJ)(this,b,f,d[e]));return c};D.E.Tj=function(b){return b<this.Hc||b>this.Xd?D.r:this.Vc(b)};
D.E.kC=function(b){var c=window.Math.min(this.yi,this.Ak),d=window.Math.max(this.yi,this.Ak);b<c?b=c:b>d&&(b=d);return this.Gn(b)};D.E.jC=function(b){b<this.Hc?b=this.Hc:b>this.Xd&&(b=this.Xd);return this.Vc(b)};D.E.Gn=function(b){return this.Hc+(b-this.yi)/(this.Ak-this.yi)*(this.Xd-this.Hc)};D.E.Vc=function(b){return this.yi+(b-this.Hc)/(this.Xd-this.Hc)*(this.Ak-this.yi)};D.E.U5=function(){return window.Math.abs(this.Vc(this.Hc+this.Xm)-this.Vc(this.Hc))};D.E.Dw=(0,D.C)("Xm");
D.E.HU=function(){return("top"==this.jd||"bottom"==this.jd)&&D.K.R(this.e)?this.Rn:this.io};D.E.kU=function(){return("top"==this.jd||"bottom"==this.jd)&&D.K.R(this.e)?this.io:this.Rn};
});