define(['./DvtToolkit', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Po=(0,D.z)();D.F.l(D.Po,D.Sb,"DvtBaseTreeView");D.E=D.Po.prototype;D.E.Init=function(b,c,d){D.Po.q.Init.call(this,b,c,d);this.xa=this.xW(this,b,this.ib,this);this.xa.$e(this);this.vk=new D.ci(b);this.h0=new D.Jp(this);(0,D.hm)(this.xa,this.vk);this.Xaa=new D.Kp(this);this.CX=this.Na=D.r;this.Eea=D.u;this.$K=D.r};
D.E.L=function(b,c,d){this.ub=c;this.Ob=d;this.xa&&this.xa.oc();this.Nm&&!b&&(b=this.CX);b&&(this.CX=b);b&&(c=this.Tu(b),this.aI(c));d=new D.I(0,0,this.ub,this.Ob);this.Zn(d);c=new D.H(this.e);this.k(c);this.a4&&(this.lZ=new D.Lp(this.e,this.xa),this.lZ.TF=D.o);this.Vm(c,d);this.Nm&&(this.iW=D.o,this.Nm.stop());var e=new D.I(0,0,this.ub,this.Ob);d=D.u;if(this.ga){if(this.ZH&&b)if(D.ab.isSupported(this.ZH))this.Nm=D.ab.bz(this.e,this.ZH,this.ga,c,e,this.tD),d=D.o;else if(this.iL&&"auto"==this.ZH){this.Wi=
this.XW();this.k(this.Wi);var e=new D.Mp(this.e,this.Wi),f=this.iL,g=this.kb,h=this.pS,k=this.Fx;e.nJ=D.u;e.iL=f;e.pS=h;(0,D.Np)(k,f)||(0,D.Np)(h,g)?(e.nJ=D.o,h=(0,D.So)(f),k=(0,D.So)(g),h.push(f),k.push(g),(0,D.Yn)(e,h,k)):(0,D.Yn)(e,[f],[g]);this.Nm=e.tq()}}else this.Nm=this.ZW(c,e);this.pS=this.iL=D.r;this.Nm&&(this.xa.rs(this),this.Nm.zd(this.rp,this),this.Nm.play());d?this.Dk=this.ga:this.ga&&this.removeChild(this.ga);this.ga=c;b?(this.LF(),(0,D.Op)(this,!this.Nm)):this.oY()};D.E.Tu=(0,D.ca)(D.r);
D.E.Zn=(0,D.z)();D.E.Vm=(0,D.z)();D.E.RO=function(b){var c=new D.cd(this.e,0,0,this.ub,this.Ob);(0,D.ed)(c);b.k(c)};D.To=function(b,c){if(b.Fx&&0<b.Fx.length){var d=b.kb?b.kb.kh():D.r;b.am&&(0,D.Rm)(b.xa,b.am.ld());b.am=D.Pp.L(b,c,b.Fx,d);(0,D.Qm)(b.xa,b.am.ld())}else(0,D.Rm)(b.xa,b.am),b.am=D.r};D.Uo=function(b,c){var d=D.r;if(b.Ifa&&b.vZ)for(var e=0;e<b.vZ.length;e++){var f=b.vZ[e];if(f.id==b.Ifa){d=f.au;break}}if(b.xia||b.Oca||d)b.Na=D.Qp.L(b,c,b.ih.legendSize,b.ih.legendColor,b.xia,b.Oca,d)};
D.Wo=function(b,c){if(b.Hp){var d=new D.pc(b.e,b.Hp,b.ub/2,b.Ob/2);d.of();d.Ce();D.qc.Wb(d,b.ub-4,b.Ob-4,b);c.k(d)}};D.Vo=function(b){return b.kb&&0<b.kb.vc()};D.E=D.Po.prototype;D.E.ZW=function(b,c){return D.ab.isSupported(this.hW)?D.ab.VG(this.e,this.hW,b,c,this.tD):D.r};D.E.rp=function(){this.Wi&&(this.removeChild(this.Wi),this.Wi=D.r);this.Dk&&(this.removeChild(this.Dk),this.Dk=D.r);this.iW=D.u;this.Nm=D.r;this.xa.$e(this);(0,D.Op)(this,D.o)};D.E.XW=function(){return new D.H(this.e)};D.E.yD=function(b){return new D.Rp(b)};
D.E.xW=function(b,c,d,e){return new D.Sp(b,c,d,e)};D.E.N9=(0,D.ba)();D.E.Va=(0,D.C)("xa");D.Tp=function(b,c){var d=c,e=b.pb();if(e)for(var f=0;f<e.length;f++)var g=(0,D.Tp)(e[f],c+1),d=window.Math.max(d,g);return d};
D.Po.prototype.aI=function(b){this.iL=this.kb;this.pS=this.Fx;this.tl=b.WEa;this.ih=b.ana?b.ana:{};this.kb=b.root;this.Hp=b.m5;this.Fx=b.gAa;this.VHa=new D.Ud(b.fBa,b.gBa);this.WHa=new D.Vd(b.eBa);this.hW=b.I4;this.ZH=b.jAa;this.tD=b.hAa;this.aP=b.gGa;this.un=b.kGa;this.Z1=b.Ima;b.o8&&(this.a4=b.o8);this.Z1?(this.Mb=new D.In(b.Ima),this.jB=b.PFa):this.Mb=D.r;this.xa.Kz(this.Mb);this.xa.Pz=b.Q4;this.Mb?(0,D.Ha)(this.xa,this.yD(this.xa)):(0,D.Ha)(this.xa,D.r);this.kb&&(this.Yp=(0,D.Tp)(this.kb,0));
this.vZ=b.au;this.Ifa=b.BEa;this.xia=b.eGa;this.Oca=b.zAa};D.Po.prototype.oY=function(){for(var b=this.Mb?this.Mb.getSelection():[],c=0;c<b.length;c++)b[c].Pb(D.o)};D.Po.prototype.LF=function(){if(this.Mb&&this.jB){var b=[];(0,D.Up)(this,this.kb,b);(0,D.Kn)(this.Mb,this.jB,b);this.jB=D.r}};D.Op=function(b,c){var d=D.r,e=b.$K;e&&(d=(0,D.cq)(b.kb,e),b.xa.Pl(d));c&&(b.$K=D.r);d||(d=b.N9(b.kb),b.xa.Pl(d));c&&b.fp(b.SU())};D.Po.prototype.fp=function(b){this.Eea=b;this.xa.fp(b)};D.Po.prototype.SU=(0,D.C)("Eea");
D.Up=function(b,c,d){if(c&&(d.push(c),c=c.pb()))for(var e=0;e<c.length;e++)(0,D.Up)(b,c[e],d)};D.Po.prototype.XD=function(b){return this.Mb?b[0]:D.r};D.Po.prototype.Dx=function(b){b.lb()||(this.Mb.Li(b,D.u),this.xa.Bl());b=[];for(var c=this.Mb.getSelection(),d=0;d<c.length;d++)b.push(c[d].getId());return b};D.Po.prototype.Cx=function(){for(var b=[],c=this.Mb.getSelection(),d=0;d<c.length;d++)b.push(c[d].cZ());return b};D.Po.prototype.Gsa=function(b){b instanceof D.dq&&(0,D.eq)(this,b.getId(),D.u)};
D.eq=function(b,c,d){d&&b.kb&&c==b.kb.getId()&&b.Fx&&0<b.Fx.length?(b.$K=c,b.ib(new D.oo(b.Fx[0].id))):d||b.ib(new D.oo(c));b.e.hd().oc()};D.Po.prototype.vq=(0,D.C)("Xaa");D.Po.prototype.Vka=function(b){return(0,D.Dc)(this.xa,b)};
D.Po.prototype.sj=function(b,c,d){return this.vk.sj(d)};D.Po.prototype.Mk=function(b,c){return this.vk.Mk(b,c)};

D.Mp=function(b,c){this.Init(b,c)};D.F.l(D.Mp,D.Xn,"DvtBaseTreeAnimationHandler");D.Np=function(b,c){if(!c||!b)return D.u;for(var d=0;d<b.length;d++)if(b[d].id==c.getId())return D.o;return D.u};
D.Jp=(0,D.B)("I");D.F.l(D.Jp,D.bi,"DvtBaseTreeDropTarget");
D.Sp=function(b,c,d,e){this.Init(c,d,e);this.I=b};D.F.l(D.Sp,D.Bc,"DvtBaseTreeEventManager");D.E=D.Sp.prototype;D.E.$n=function(b){D.Sp.q.$n.call(this,b);var c=(0,D.Dc)(this,b.target);c&&(b=b.shiftKey,c.Fq&&c.Fq()&&(0,D.eq)(this.I,c.getId(),b))};D.E.Vg=function(b){D.Sp.q.Vg.call(this,b);b=(0,D.Dc)(this,b.target);(0,D.vD)(this,b)};D.E.ao=function(b){D.Sp.q.ao.call(this,b);(b=(0,D.Dc)(this,b.target))&&b.Jw&&b.Jw()};
D.E.dk=function(b){D.Sp.q.dk.call(this,b);var c=(0,D.Dc)(this,b.target);c&&c.Cq&&(b=(0,D.Dc)(this,b.relatedTarget),(b&&b.getId?b.getId():D.r)!=c.getId()&&c.Cq())};D.E.Vl=function(b){var c=D.u,c=(0,D.im)(this);13==b.keyCode&&!b.ctrlKey?(c=(0,D.im)(this),c.Fq&&c.Fq()&&(b.shiftKey&&(c=this.I.kb),(0,D.eq)(this.I,c.getId(),b.shiftKey)),b.preventDefault(),c=D.o):c=D.Sp.q.Vl.call(this,b);return c};
D.E.Ou=function(b){b=(0,D.Dc)(this,b.target);(0,D.vD)(this,b);this.TJ&&this.TJ!=b&&(this.TJ.Cq(),this.TJ=D.r);b&&b instanceof D.cC&&this.TJ!=b&&(this.TJ=b,b.Jw())};D.E.$z=function(b){(b=(0,D.Dc)(this,b.target))&&b.Fq&&b.Fq()&&(0,D.eq)(this.I,b.getId(),D.u)};D.vD=function(b,c){c&&(c instanceof D.qt&&c.Lx)&&(0,D.eq)(b.I,c.getId(),D.u)};
D.PB=(0,D.z)();D.F.l(D.PB,D.F,"DvtBaseTreeParser");D.E=D.PB.prototype;D.E.Init=function(b){this.I=b;this.Go=new D.jl;this.O1=window.Infinity;this.I1=-window.Infinity};
D.E.parse=function(b){var c=this.Go.parse(b);b=this.Ul(c);var c=c.pb(),d;d=(0,D.xD)(c,"f");var e=d.length;if(0<e){for(var f,g,h={},k=0;k<e;k++)f=d[k],g=f.o("name"),h[g]=D.hq.Tk(f);d=h}else d=D.r;b.o8=d;this.tl=0;f=(0,D.xD)(c,"n");e=[];for(d=0;d<f.length;d++)(g=this.IF(f[d],b.o8))&&e.push(g);b.WEa=this.tl;if(1==e.length)d=e[0];else{d=this.I;for(g=f=0;g<e.length;g++)f+=e[g].vc();d=this.Pm(d,{size:f,oAa:D.o,Sja:D.o});(0,D.rD)(d,e)}b.root=d;for(d=0;d<c.length;d++)if(e=c[d],f=b,e)if(g=e.getName(),"spb"==
g)e=this.O2(e,f),f.jna||(f.jna=[]),f.jna.push(e);else if("menus"==g)f.Q4||(f.Q4=new D.hn(this.I.e)),f.Q4.add(e);else if("ag"==g){k=e;e=f;h=D.n;f=k.o("id");g=k.o("T");if("continuous"==k.o("t")){var h=k.o("minValue"),m=k.o("maxValue"),p=k.o("minLabel"),q=k.o("maxLabel"),k=k.o("ramp").split(";");h==D.r&&(h=this.O1);m==D.r&&(m=this.I1);h=new D.Lu(h,m,p,q,k)}else{h=new D.Ku;k=k.pb();for(m=0;m<k.length;m++){var t=k[m];t&&(p=t.o("g"),q=t.o("l"),t={color:t.o("c"),pattern:t.o("p")},h.add(p,q,t))}}e.au||(e.au=
[]);e.au.push({au:h,n8:g,id:f})}else if("styles"==g)f.kGa=this.P2(e,f);else if("a"==g){g=[];e=e.pb();for(h=0;h<e.length;h++)k=e[h].o("id"),m=e[h].o("l"),g.push({id:k,text:m});f.gAa=g}else if("resources"==g){g={};e=e.getAttributes();for(h=0;h<e.length;h++)g[e[h].name]=e[h].value;f.ana=g}this.mo(b.root,b);return b};D.E.Pm=(0,D.ca)(D.r);
D.E.Ul=function(b){var c={},d=b.o("sel");c.Ima="none"==d?D.r:"single"==d?"s":"m";c.gGa=b.o("sort");if(d=b.o("selIds"))c.PFa=d.split(",");c.m5=b.o("emptyText");c.BEa=b.o("ls");c.eGa=b.o("sv");c.zAa=b.o("cv");if(d=b.o("adu"))c.hAa=d/1E3;c.jAa=b.o("adc");c.I4=b.o("adi");return c};
D.E.Uu=function(b){var c={};c.n8=b.o("T");c.SEa=b.o("M");c.HT=b.o("ag");c.id=b.o("id");c.size=(0,window.Number)(b.o("s"));c.color=b.o("c");c.pattern=b.o("p");c.label=b.o("l");c.nGa=b.o("tt");c.aV=b.o("ld");c.dBa=b.o("d");c.WDa=b.o("iip");c.Sja="t"==b.o("di")?D.o:D.u;c.OFa=b.o("nsel");var d=b.o("tn");d&&(c.ona=d);if(b=b.o("ls"))c.ou=new D.P(b);c.HT!=D.r&&(this.I1=window.Math.max(this.I1,c.HT),this.O1=window.Math.min(this.O1,c.HT));return c};
D.E.IF=function(b,c){if(!b||"n"!=b.getName())return D.r;this.tl++;var d=this.Uu(b),d=this.Pm(this.I,d,c);(0,D.rD)(d,this.ES(b,d,c));return d};D.E.ES=function(b,c,d){var e=[];b=b.pb();for(var f=0;f<b.length;f++){var g=b[f];g&&("el"==g.getName()?d&&c.waa&&c.waa((0,D.go)(g)):c.nb()&&e.push(this.IF(g,d)))}return e};D.E.O2=function(b,c){var d=(0,D.Bg)(b),e=b.o("T");c.VH||(c.VH={});c.VH[e]||(c.VH[e]=[]);c.VH[e].push(d)};
D.E.mo=function(b,c){if(b){var d=b.No;if(c.VH){var e=c.VH[d];e&&b.i8(e)}if(c.au)for(var f=0;f<c.au.length;f++)if(e=c.au[f],e.n8==d){if(e.au instanceof D.Lu&&(d=b,e=e.au.get(d.Vsa)))d.xg=e;break}if(d=b.pb())for(e=0;e<d.length;e++)this.mo(d[e],c)}};D.xD=function(b,c){for(var d=[],e=0;e<b.length;e++){var f=b[e];f&&f.getName()==c&&d.push(f)}return d};
D.PB.prototype.P2=function(b,c){var d={},e=new D.P(b.o("top"));d.BACKGROUND_STYLE=e;d.ANIMATION_UPDATE_COLOR_STYLE=e.v("-tr-animation-update-color");e=new D.P(b.o("node"));d.LABEL_TEXT_DEFAULT_STYLE=e;var f=e.clone().zb(new D.P(b.o("node-hover"))),g=e.clone().zb(new D.P(b.o("node-selected")));c.fBa=b.o("dsf");c.eBa=b.o("dsb");c.gBa=b.o("dso");this.RX(e,f,g,d);this.baa(b,d);e=new D.P(b.o("rootText"));d.TEXT_STYLE=e;e=new D.P(b.o("attrType"));d.ATTRIBUTE_TYPE_STYLE=e;e=new D.P(b.o("attrValue"));d.ATTRIBUTE_VALUE_STYLE=
e;e=new D.P(b.o("drillText"));d.DRILL_TEXT_STYLE=e;e=new D.P(b.o("currentText"));d.CURRENT_TEXT_STYLE=e;return d};D.PB.prototype.RX=(0,D.z)();D.PB.prototype.baa=(0,D.z)();
D.cC=(0,D.z)();D.F.l(D.cC,D.F,"DvtBaseTreeNode");D.st=new D.mf("#000000",2,5,5,45,0.5);
D.cC.prototype.Init=function(b,c,d){this.I=b;this.No=c.n8;this.N1=c.SEa;this.Vsa=c.HT;this.Ra=c.id;this.Qj=c.size;this.xg=c.color?c.color:"#000000";this.Io=c.pattern;this.Wy=c.label;this.ay=c.nGa;this.mm=c.ou;this.EE=c.dBa;this.eg=c.Sja;this.Ewa=c.WDa;this.wZ=c.oAa;this.Ss=1;this.SR=D.r;this.Qf=D.u;this.a4=d;c.ona?(0,D.qD)(this,c.ona):d&&d.content?(0,D.qD)(this,"content"):d&&d.rootContent&&(0,D.qD)(this,"rootContent");this.wI=D.u;this.VO=c.OFa};
D.rD=function(b,c){if(c!=D.r)for(var d=0;d<c.length;d++)c[d].Ye=b;b.Zd=c};D.cC.prototype.pb=(0,D.C)("Zd");D.So=function(b){var c=[],d,e;if(!b.oe())return c;for(var f=0;f<b.Zd.length;f++)e=b.Zd[f],d=(0,D.So)(e),c.push(e),c=c.concat(d);return c};D.iC=function(b){var c=b.Ye;c&&(c.SR=b)};D.cC.prototype.IC=function(b){return!b||!this.Ye?D.u:this.Ye==b?D.o:this.Ye.IC(b)};
D.kC=function(b,c,d){var e=[];if(0>d)return e;if(0==d)return[b];if(c.oe()){b=c.pb();for(var f=0;f<b.length;f++)c=b[f],e=e.concat((0,D.kC)(c,c,d-1))}return e};D.ap=function(b){var c=[],d;if(!b.oe())return[b];for(var e=0;e<b.Zd.length;e++)d=b.Zd[e],d=(0,D.ap)(d),c=c.concat(d);return c};D.cq=function(b,c){if(b.getId()==c)return b;for(var d=D.r,e=b.pb(),f=e.length,d=D.r,g=0;g<f;g++)if(d=e[g],d=(0,D.cq)(d,c))return d;return D.r};D.E=D.cC.prototype;D.E.getId=(0,D.C)("Ra");D.E.vc=(0,D.C)("Qj");D.E.Nb=(0,D.C)("xg");
D.E.Fe=(0,D.C)("ay");D.E.nj=(0,D.C)("xg");D.E.Z=(0,D.C)("Ss");D.E.B=function(b){this.Ss=b;this.J&&this.J.B(this.Ss)};D.E.nb=(0,D.C)("eg");D.E.Fq=function(){return"r"==this.EE||"ir"==this.EE};D.E.i8=(0,D.B)("bd");D.E.xd=(0,D.C)("bd");D.E.xw=(0,D.C)("N1");D.E.L=(0,D.z)();D.E.Du=function(b){var c=this.pb();if(c!=D.r)for(var d=0;d<c.length;d++)c[d].L(b)};D.E.lh=function(){(0,D.iC)(this);return this};D.E.He=function(){return new D.I(0,0,0,0)};D.E.li=function(){this.Bc();this.Jw&&this.Jw();this.Qf=D.o};
D.E.pe=function(){this.ji()&&this.qc();this.Cq&&this.Cq();this.Qf=D.u};D.E.ji=(0,D.C)("Qf");D.E.Jw=function(){this.wI=D.o};D.E.Cq=function(){this.wI=D.u};D.E.rc=(0,D.ca)(D.o);D.E.lb=(0,D.C)("Fd");D.E.Pb=(0,D.B)("Fd");D.E.Bc=(0,D.z)();D.E.qc=(0,D.z)();D.E.sj=function(b){return this.I.XD(b)};D.E.Mk=function(){return this.I.Dx(this)};D.E.qC=function(){return this.I.Cx()};D.E.cZ=(0,D.C)("J");D.E.wC=(0,D.ca)(D.r);D.E.contains=(0,D.ca)(D.u);D.E.al=function(){return[]};D.E.fo=(0,D.z)();
D.E.Ef=function(b,c){b.nJ||(0,D.Yn)(b,c.pb(),this.pb());var d=c.al(),e=this.al(),f;if(!D.Jb.Fh(d,e)&&(f=new D.Mj(this.I.e,this,this.I.tD),(0,D.N)(f.S,"typeNumberArray",this,this.al,this.fo,e),b.add(f,1),e=this.Qj!=c.Qj,f=D.S.EU(this.xg)!=D.S.EU(c.xg),this.fo(d),(d=(0,D.hC)(this,D.r,"ANIMATION_UPDATE_COLOR_STYLE"))&&(e||f)))this.xg=d};D.E.Ig=function(b){if(!b.nJ||!b.nJ||!(b.iL.getId()==this.getId()||(0,D.Np)(b.pS,this))){this.B(0);var c=new D.kj(this.I.e,this,this.I.tD);b.add(c,2);for(c=0;c<this.Zd.length;c++)this.Zd[c].Ig(b)}};
D.E.ai=function(b,c){c.k(this.J);var d=new D.Ij(this.I.e,this,this.I.tD);b.add(d,0);if(!b.nJ)for(d=0;d<this.Zd.length;d++)this.Zd[d].ai(b,c)};D.E.oe=function(){return this.Zd!=D.r&&0<this.Zd.length};D.jC=function(b){var c=0;for(b=b.Ye;b;)c++,b=b.Ye;return c};D.cC.prototype.BD=function(){return this.Io?new D.zc(this.Io,this.xg):new D.Ud(this.xg)};D.oC=function(b){if(b.Io)return"#000000";var c=b.xg;b=D.S.gd(c);var d=D.S.fd(c),c=D.S.dd(c);return 128<=(299*b+587*d+114*c)/1E3?"#000000":"#FFFFFF"};
D.nC=function(b,c){var d=(0,D.oC)(b);c.na(d);d=[];d.push(b.I.un.LABEL_TEXT_DEFAULT_STYLE);b.mm&&d.push(b.mm);c.Ia((0,D.Vl)(d))};D.hC=function(b,c,d){(b=b.I.un[d])&&(c=b);return c};D.dC=function(b){var c=11;(b=b.I.un.LABEL_TEXT_DEFAULT_STYLE.UG())&&(c=(0,window.parseFloat)(b));return c};D.cC.prototype.Ka=(0,D.C)("J");D.cC.prototype.kh=(0,D.C)("Wy");D.cC.prototype.waa=function(b){b&&!this.TL&&(0,D.qD)(this,"content");this.Sh=b};D.qD=function(b,c){c&&(b.TL=b.a4[c])};D.cC.prototype.Lg=function(){return this.Fq()};
D.qt=function(b,c,d,e,f){this.Init(d,e,f);this.wb=b;this.Ra=c;this.Lx=D.u};D.F.l(D.qt,D.rc,"DvtBaseTreePeer");D.qt.prototype.getId=(0,D.C)("Ra");D.qt.prototype.ama=(0,D.C)("Lx");D.qt.prototype.b8=(0,D.B)("Lx");D.qt.prototype.Cq=function(){this.wb&&this.wb.Cq&&this.wb.Cq()};
D.Pp=(0,D.z)();D.F.l(D.Pp,D.F,"DvtTreeBreadcrumbsRenderer");D.Pp.era=6;D.Pp.pra="color: #003286;";
D.Pp.L=function(b,c,d,e){var f=b.e,g=[];g.push(b.un.TEXT_STYLE);g.push(new D.P(D.Pp.pra));g.push(b.un.DRILL_TEXT_STYLE);var g=(0,D.Vl)(g).toString(),h=g+"text-decoration: underline;",k=[];k.push(b.un.TEXT_STYLE);k.push(b.un.CURRENT_TEXT_STYLE);k=(0,D.Vl)(k).toString();f=new D.Eu(f,b.Gsa,b,{ou:g,h7:h,g7:h,Rja:k});b.k(f);d=d.slice(0).reverse();d.push({text:e});f.L({items:d},c.g);e=f.C();(0,D.Ya)(f,c.x,c.y);e=e.j+D.Pp.era;c.y+=e;c.j-=e;b.removeChild(f);return f};
D.Qp=(0,D.z)();D.F.l(D.Qp,D.F,"DvtTreeLegendRenderer");D.Qp.xra=4;D.Qp.Ps=7;D.Qp.jP=24;D.Qp.wra=11;D.Qp.mba="#636363";D.Qp.dHa="color:"+D.Qp.mba+";";
D.Qp.L=function(b,c,d,e,f,g,h){var k=b.e,m=b.Va(),p=new D.H(k);b.k(p);var q=D.Qp.yL(k,b,p,c.g,d,e,f,g,h),t=b.ih.alta?D.r:"#000000",v=[];v.push(b.un.TEXT_STYLE);var v={borderColor:t,ou:(0,D.Vl)(v)},t=D.pD.K7(k,m,p,c.g,c.j,h,v),w=q?q.C():D.r,A=t?t.C():D.r;if(q&&!t)q.F(c.y+(c.g-w.g)/2);else if(t&&!q)t.F(c.y+(c.g-A.g)/2);else if(t&&q){var D$=c.g-D.Qp.jP;w.g+A.g>D$&&(w.g>D$/2&&A.g>D$/2?(p.removeChild(q),p.removeChild(t),q=D.Qp.yL(k,b,p,D$/2,d,e,f,g,h),t=D.pD.K7(k,m,p,D$/2,c.j,h,v)):w.g>A.g?(m=D$-A.g,p.removeChild(q),
q=D.Qp.yL(k,b,p,m,d,e,f,g,h)):(d=D$-w.g,p.removeChild(t),t=D.pD.K7(k,m,p,d,c.j,h,v)),w=q.C(),A=t.C());D.K.R(k)?(t.F(c.x),q.F(c.x+c.g-w.g)):(q.F(c.x),t.F(c.x+c.g-A.g))}h=p.C();p.O(c.y+c.j-h.j);c.j-=h.j+D.Qp.xra;b.removeChild(p);return p};
D.Qp.yL=function(b,c,d,e,f,g,h,k){var m=D.K.R(b),p=c.Va(),q=D.r;if(h||k){q=new D.H(b);d.k(q);var t=[];t.push(c.un.TEXT_STYLE);t.push(c.un.ATTRIBUTE_TYPE_STYLE);d=(0,D.Vl)(t);t=[];t.push(c.un.TEXT_STYLE);t.push(c.un.ATTRIBUTE_VALUE_STYLE);var t=(0,D.Vl)(t),v,w,A,D$;c=0;h&&(v=new D.pc(b,f,0,0),v.Ia(d),q.k(v),A=v.Vb().g,w=new D.pc(b,h,0,0),w.Ia(t),q.k(w),D$=w.Vb().g,c=A+D$+D.Qp.Ps);var J,G,L,O;f=0;k&&(J=new D.pc(b,g,0,0),J.Ia(d),q.k(J),L=J.Vb().g,G=new D.pc(b,k,0,0),G.Ia(t),q.k(G),O=G.Vb().g,f=L+O+D.Qp.Ps);
e-=D.Qp.jP;c+f>e&&(b=e/2,c>b&&f>b?(D.qc.Wb(w,b-A-D.Qp.Ps,window.Infinity,q)?(D$=w.Vb().g,p.ma(w,new D.rc(h))):(q.removeChild(v),q.removeChild(w),w=D.r,D$=0),D.qc.Wb(G,b-L-D.Qp.Ps,window.Infinity,q)?(O=G.Vb().g,p.ma(G,new D.rc(k))):(q.removeChild(J),q.removeChild(G),G=D.r,O=0)):c>f?D.qc.Wb(w,e-f-A-D.Qp.Ps,window.Infinity,q)?(D$=w.Vb().g,p.ma(w,new D.rc(h))):(q.removeChild(v),q.removeChild(w),w=D.r,D$=0):D.qc.Wb(G,e-c-L-D.Qp.Ps,window.Infinity,q)?(O=G.Vb().g,p.ma(G,new D.rc(k))):(q.removeChild(J),q.removeChild(G),
G=D.r,O=0));e=0;m?(G&&(G.fa(e),e+=O+D.Qp.Ps,J.fa(e),e+=L+D.Qp.jP),w&&(w.fa(e),e+=D$+D.Qp.Ps,v.fa(e))):(w&&(v.fa(e),e+=A+D.Qp.Ps,w.fa(e),e+=D$+D.Qp.jP),G&&(J.fa(e),e+=L+D.Qp.Ps,G.fa(e)))}return q};
D.Rp=function(b){this.Init(b)};D.F.l(D.Rp,D.Nn,"DvtBaseTreeKeyboardHandler");D.Rp.prototype.pH=function(b){return this.Yj(b)&&!b.ctrlKey};D.Rp.prototype.KC=function(b){return 32==b.keyCode&&b.ctrlKey};
D.qC=(0,D.z)();D.F.l(D.qC,D.Mg,"DvtBaseTreeDefaults");D.uD={skin:"skyros",emptyText:"No data to display",nodeDefaults:{labelStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px;")},styleDefaults:{_attributeTypeTextStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;font-weight:bold;color:#4F4F4F"),_attributeValueTextStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;")},_resources:{}};
D.qC.prototype.Init=function(b){b={skyros:D.xa.zb(b.skyros,D.uD),alta:D.xa.zb(b.alta,{})};D.qC.q.Init.call(this,b)};
D.YB=(0,D.z)();D.F.l(D.YB,D.F,"DvtBaseTreeJsonUtils");
D.YB.prototype.q8=function(b){var c;c="\x3c"+this.qO();c+=this.UI(b);c+="\x3e\n";if(b&&b.nodes)for(var d=b.nodes,e=0;e<d.length;e++)c+=(0,D.wD)(this,b,d[e]);d="\x3ca/\x3e\n"+this.KY(b);d+=this.WI(b);if(e=b.attributeGroups?b.attributeGroups[0]:D.r)if(b='\x3cag id\x3d"'+e.id+'"',"continuous"==e.attributeType)b+=this.Ca("t","continuous"),b+=this.Ca("ramp",e.colors.join(";")),b+=this.Ca("minValue",e.min),b+=this.Ca("maxValue",e.max),b+=this.Ca("minLabel",e.minLabel),b+=this.Ca("maxLabel",e.maxLabel),
b+="/\x3e";else{b+="\x3e\n";for(var e=e.groups,f=0;f<e.length;f++)b+="\x3ci",b+=this.Ca("g",e[f].id),b+=this.Ca("l",e[f].label),b+=this.Ca("c",e[f].color),b+=this.Ca("p",e[f].pattern),b+="/\x3e\n";b+="\x3c/ag\x3e\n"}else b="";d=d+b+("\x3c/"+this.qO()+"\x3e");return c+=d};D.YB.prototype.Ca=function(b,c){return c!=D.r?" "+b+'\x3d"'+c+'"':""};D.YB.prototype.qO=(0,D.ca)(D.r);
D.YB.prototype.UI=function(b){var c;c=""+this.Ca("sv",b.sizeLabel);c+=this.Ca("cv",b.colorLabel);var d=b.attributeGroups?b.attributeGroups[0]:D.r;d&&(c+=this.Ca("ls",d.id));for(var d=b.selectedNodes?b.selectedNodes:[],e="",f=0;f<d.length;f++)0<e.length&&(e+=","),e+=d[f];0<e.length&&(c+=this.Ca("selIds",e));c+=this.Ca("adu",b.animationDuration);c+=this.Ca("adc",b.animationOnDataChange);c+=this.Ca("emptyText",b.emptyText);c+=this.Ca("sel",b.selection);return c+=this.Ca("sort",b.sorting)};
D.wD=function(b,c,d){var e;e="\x3cn"+b.VI(c,d);if(d&&d.nodes&&0<d.nodes.length){e+=b.Ca("di","t");e+="\x3e\n";d=d.nodes;for(var f=0;f<d.length;f++)e+=(0,D.wD)(b,c,d[f]);e+="\x3c/n\x3e\n"}else e+="/\x3e\n";return e};
D.YB.prototype.VI=function(b,c){var d;d=""+this.Ca("id",c.id);d+=this.Ca("s",c.value);d+=this.Ca("c",c.color);d+=this.Ca("l",c.label);d+=this.Ca("p",c.pattern);d+=this.Ca("tt",c.shortDesc?c.shortDesc:c.tooltip);d+=this.Ca("ls",c.labelStyle?c.labelStyle:b.nodeDefaults.labelStyle);var e=c.drilling?c.drilling:b.nodeDefaults.drilling;"insert"==e?d+=this.Ca("d","i"):"replace"==e?d+=this.Ca("d","r"):"insertAndReplace"==e&&(d+=this.Ca("d","ir"));return d+=this.Ca("nsel",c.selectable?c.selectable:"auto")};
D.YB.prototype.KY=(0,D.z)();D.YB.prototype.WI=function(b){var c;c="\x3cstyles "+this.Ca("attrType",b.styleDefaults._attributeTypeTextStyle);return c+=this.Ca("attrValue",b.styleDefaults._attributeValueTextStyle)};
D.Kp=function(b){this.mb(b)};D.F.l(D.Kp,D.F,"DvtTreeAutomation");D.Kp.prototype.mb=(0,D.B)("cja");D.Kp.prototype.click=function(b){this.I7(b,0)};
D.Kp.prototype.I7=function(b,c){c===D.n&&(c=-1);if(b==D.r)return D.r;var d;if(-1!=c){if(0==c){var e=(0,D.sD)(b);e&&"node"==e[0]&&(e=(0,D.tD)(this.cja.kb,e,1))&&(0,D.Fe)(e.Ka(),D.Ua)}}else if((e=(0,D.sD)(b))&&"node"==e[0]){var f=e.length-1,g=e[f];0<=g.indexOf("#")&&(e[f]=D.r,(e=(0,D.tD)(this.cja.kb,e,1))&&("#label"==g?d=e.kh():"#size"==g?d=e.vc():"#color"==g?d=e.Nb():"#tooltip"==g&&(d=e.Fe())))}return d};
D.tD=function(b,c,d){var e=D.r;if(b.Ewa==c[d])if(c[d+1]==D.r)e=b;else if(b=b.pb())for(var f=0;f<b.length&&!(e=(0,D.tD)(b[f],c,d+1));f++);return e};D.sD=function(b){b=b.split("[");var c;c=D.r;if(b&&0<=b.length){var d=b.length-1,e=b[d],f=e.indexOf("#");0<f&&(b[d]=e.substr(0,f),c=e.substr(f))}d=b.length;for(e=1;e<d;e++)f=b[e],f=f.substr(0,f.length-1),window.tempIdAsNumber=(0,window.parseFloat)(f),f=(0,window.isNaN)(window.tempIdAsNumber)?f:window.tempIdAsNumber,b[e]=f;c&&(b[d]=c);return b};
});