define(['./DvtToolkit', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Zo=(0,D.z)();D.F.o(D.Zo,D.Rb,"DvtBaseTreeView");D.E=D.Zo.prototype;D.E.Init=function(b,c,d){D.Zo.q.Init.call(this,b,c,d);this.wa=this.YW(this,b,this.ib,this);this.wa.bf(this);this.yk=new D.gi(b);this.J0=new D.Tp(this);(0,D.om)(this.wa,this.yk);this.Kba=new D.Up(this);this.cY=this.Ua=D.r;this.$fa=D.u;this.nL=D.r};
D.E.L=function(b,c,d){this.ub=c;this.Mb=d;this.wa&&this.wa.oc();this.Sm&&!b&&(b=this.cY);b&&(this.cY=b);b&&(c=this.gv(b),this.nI(c));d=new D.I(0,0,this.ub,this.Mb);this.bo(d);c=new D.H(this.e);this.k(c);this.G4&&(this.MZ=new D.Vp(this.e,this.wa),this.MZ.fG=D.o);this.ll(c,d);this.Sm&&(this.JW=D.o,this.Sm.stop());var e=new D.I(0,0,this.ub,this.Mb);d=D.u;if(this.ga){if(this.lI&&b)if(D.$a.isSupported(this.lI))this.Sm=D.$a.nz(this.e,this.lI,this.ga,c,e,this.HD),d=D.o;else if(this.wL&&"auto"==this.lI){this.aj=
this.xX();this.k(this.aj);var e=new D.Wp(this.e,this.aj),f=this.wL,g=this.kb,h=this.MS,k=this.Qx;e.zJ=D.u;e.wL=f;e.MS=h;(0,D.Xp)(k,f)||(0,D.Xp)(h,g)?(e.zJ=D.o,h=(0,D.bp)(f),k=(0,D.bp)(g),h.push(f),k.push(g),(0,D.io)(e,h,k)):(0,D.io)(e,[f],[g]);this.Sm=e.Cq()}}else this.Sm=this.zX(c,e);this.MS=this.wL=D.r;this.Sm&&(this.wa.Es(this),this.Sm.Ad(this.wp,this),this.Sm.play());d?this.Gk=this.ga:this.ga&&this.removeChild(this.ga);this.ga=c;b?(this.YF(),(0,D.aq)(this,!this.Sm)):this.QY()};D.E.gv=(0,D.ca)(D.r);
D.E.bo=(0,D.z)();D.E.ll=(0,D.z)();D.E.dP=function(b){var c=new D.td(this.e,0,0,this.ub,this.Mb);(0,D.vd)(c);b.k(c)};D.cp=function(b,c){if(b.Qx&&0<b.Qx.length){var d=b.kb?b.kb.mh():D.r;b.ur&&(0,D.$m)(b.wa,b.ur);b.ur=D.bq.L(b,c,b.Qx,d);(0,D.Zm)(b.wa,b.ur)}else(0,D.$m)(b.wa,b.ur),b.ur=D.r};D.dp=function(b,c){var d=D.r;if(b.dha&&b.WZ)for(var e=0;e<b.WZ.length;e++){var f=b.WZ[e];if(f.id==b.dha){d=f.pu;break}}if(b.Vja||b.gea||d)b.Ua=D.cq.L(b,c,b.de.legendSize,b.de.legendColor,b.Vja,b.gea,d)};
D.fp=function(b,c){if(b.Op){var d=new D.nc(b.e,b.Op,b.ub/2,b.Mb/2);d.rf();d.Fe();D.oc.Vb(d,b.ub-4,b.Mb-4,b);c.k(d)}};D.ep=function(b){return b.kb&&0<b.kb.xc()};D.E=D.Zo.prototype;D.E.zX=function(b,c){return D.$a.isSupported(this.IW)?D.$a.iH(this.e,this.IW,b,c,this.HD):D.r};D.E.wp=function(){this.aj&&(this.removeChild(this.aj),this.aj=D.r);this.Gk&&(this.removeChild(this.Gk),this.Gk=D.r);this.JW=D.u;this.Sm=D.r;this.wa.bf(this);(0,D.aq)(this,D.o)};D.E.xX=function(){return new D.H(this.e)};D.E.ND=function(b){return new D.dq(b)};
D.E.YW=function(b,c,d,e){return new D.eq(b,c,d,e)};D.E.y$=(0,D.ba)();D.E.Sa=(0,D.C)("wa");D.fq=function(b,c){var d=c,e=b.pb();if(e)for(var f=0;f<e.length;f++)var g=(0,D.fq)(e[f],c+1),d=window.Math.max(d,g);return d};
D.Zo.prototype.nI=function(b){this.wL=this.kb;this.MS=this.Qx;this.Al=b.UFa;this.de=b.yoa?b.yoa:{};this.kb=b.root;this.Op=b.W5;this.Qx=b.YAa;this.YIa=new D.Td(b.XBa,b.YBa);this.ZIa=new D.Ud(b.WBa);this.IW=b.s5;this.lI=b.aBa;this.HD=b.ZAa;this.nP=b.eHa;this.yn=b.iHa;this.E2=b.foa;b.Z8&&(this.G4=b.Z8);this.E2?(this.Kb=new D.Sn(b.foa),this.wB=b.NGa):this.Kb=D.r;this.wa.Vz(this.Kb);this.wa.$z=b.A5;this.Kb?(0,D.Ga)(this.wa,this.ND(this.wa)):(0,D.Ga)(this.wa,D.r);this.kb&&(this.eq=(0,D.fq)(this.kb,0));
this.WZ=b.pu;this.dha=b.xFa;this.Vja=b.cHa;this.gea=b.pBa};D.Zo.prototype.QY=function(){for(var b=this.Kb?this.Kb.getSelection():[],c=0;c<b.length;c++)b[c].Ob(D.o)};D.Zo.prototype.YF=function(){if(this.Kb&&this.wB){var b=[];(0,D.gq)(this,this.kb,b);(0,D.Un)(this.Kb,this.wB,b);this.wB=D.r}};D.aq=function(b,c){var d=D.r,e=b.nL;e&&(d=(0,D.hq)(b.kb,e),b.wa.Xl(d));c&&(b.nL=D.r);d||(d=b.y$(b.kb),b.wa.Xl(d));c&&b.kp(b.pV())};D.Zo.prototype.kp=function(b){this.$fa=b;this.wa.kp(b)};D.Zo.prototype.pV=(0,D.C)("$fa");
D.gq=function(b,c,d){if(c&&(d.push(c),c=c.pb()))for(var e=0;e<c.length;e++)(0,D.gq)(b,c[e],d)};D.Zo.prototype.kE=function(b){return this.Kb?b[0]:D.r};D.Zo.prototype.Ox=function(b){b.mb()||(this.Kb.Pi(b,D.u),this.wa.Il());b=[];for(var c=this.Kb.getSelection(),d=0;d<c.length;d++)b.push(c[d].getId());return b};D.Zo.prototype.Nx=function(){for(var b=[],c=this.Kb.getSelection(),d=0;d<c.length;d++)b.push(c[d].DZ());return b};D.Zo.prototype.wta=function(b){b instanceof D.iq&&(0,D.jq)(this,b.getId(),D.u)};
D.jq=function(b,c,d){d&&b.kb&&c==b.kb.getId()&&b.Qx&&0<b.Qx.length?(b.nL=c,b.ib(new D.yo(b.Qx[0].id))):d||b.ib(new D.yo(c));b.e.kd().oc()};D.Zo.prototype.Eq=(0,D.C)("Kba");D.Zo.prototype.sma=function(b){return(0,D.Ac)(this.wa,b)};
D.Zo.prototype.xj=function(b,c,d){return this.yk.xj(d)};D.Zo.prototype.Rk=function(b,c){return this.yk.Rk(b,c)};

D.Wp=function(b,c){this.Init(b,c)};D.F.o(D.Wp,D.ho,"DvtBaseTreeAnimationHandler");D.Xp=function(b,c){if(!c||!b)return D.u;for(var d=0;d<b.length;d++)if(b[d].id==c.getId())return D.o;return D.u};
D.Tp=(0,D.B)("I");D.F.o(D.Tp,D.fi,"DvtBaseTreeDropTarget");
D.eq=function(b,c,d,e){this.Init(c,d,e);this.I=b};D.F.o(D.eq,D.xc,"DvtBaseTreeEventManager");D.E=D.eq.prototype;D.E.eo=function(b){D.eq.q.eo.call(this,b);var c=(0,D.Ac)(this,b.target);c&&(b=b.shiftKey,c.Nq&&c.Nq()&&(0,D.jq)(this.I,c.getId(),b))};D.E.zg=function(b){D.eq.q.zg.call(this,b);b=(0,D.Ac)(this,b.target);(0,D.BD)(this,b)};D.E.fo=function(b){D.eq.q.fo.call(this,b);(b=(0,D.Ac)(this,b.target))&&b.Ww&&b.Ww()};
D.E.gk=function(b){D.eq.q.gk.call(this,b);var c=(0,D.Ac)(this,b.target);c&&c.Kq&&(b=(0,D.Ac)(this,b.relatedTarget),(b&&b.getId?b.getId():D.r)!=c.getId()&&c.Kq())};D.E.cm=function(b){var c=D.u,c=(0,D.pm)(this);13==b.keyCode&&!b.ctrlKey?(c=(0,D.pm)(this),c.Nq&&c.Nq()&&(b.shiftKey&&(c=this.I.kb),(0,D.jq)(this.I,c.getId(),b.shiftKey)),b.preventDefault(),c=D.o):c=D.eq.q.cm.call(this,b);return c};
D.E.bv=function(b){b=(0,D.Ac)(this,b.target);(0,D.BD)(this,b);this.fK&&this.fK!=b&&(this.fK.Kq(),this.fK=D.r);b&&b instanceof D.iC&&this.fK!=b&&(this.fK=b,b.Ww())};D.E.mA=function(b){(b=(0,D.Ac)(this,b.target))&&b.Nq&&b.Nq()&&(0,D.jq)(this.I,b.getId(),D.u)};D.BD=function(b,c){c&&(c instanceof D.wt&&c.Wx)&&(0,D.jq)(b.I,c.getId(),D.u)};
D.WB=(0,D.z)();D.F.o(D.WB,D.F,"DvtBaseTreeParser");D.E=D.WB.prototype;D.E.Init=function(b){this.I=b;this.Lo=new D.ml;this.r2=window.Infinity;this.k2=-window.Infinity};
D.E.parse=function(b){var c=this.Lo.parse(b);b=this.bm(c);var c=c.pb(),d;d=(0,D.DD)(c,"f");var e=d.length;if(0<e){for(var f,g,h={},k=0;k<e;k++)f=d[k],g=f.l("name"),h[g]=D.mq.Yk(f);d=h}else d=D.r;b.Z8=d;this.Al=0;f=(0,D.DD)(c,"n");e=[];for(d=0;d<f.length;d++)(g=this.VF(f[d],b.Z8))&&e.push(g);b.UFa=this.Al;if(1==e.length)d=e[0];else{d=this.I;for(g=f=0;g<e.length;g++)f+=e[g].xc();d=this.Um(d,{size:f,fBa:D.o,pla:D.o});(0,D.xD)(d,e)}b.root=d;for(d=0;d<c.length;d++)if(e=c[d],f=b,e)if(g=e.getName(),"spb"==
g)e=this.u3(e,f),f.Hoa||(f.Hoa=[]),f.Hoa.push(e);else if("menus"==g)f.A5||(f.A5=new D.rn(this.I.e)),f.A5.add(e);else if("ag"==g){k=e;e=f;h=D.n;f=k.l("id");g=k.l("T");if("continuous"==k.l("t")){var h=k.l("minValue"),m=k.l("maxValue"),p=k.l("minLabel"),q=k.l("maxLabel"),k=k.l("ramp").split(";");h==D.r&&(h=this.r2);m==D.r&&(m=this.k2);h=new D.Ru(h,m,p,q,k)}else{h=new D.Qu;k=k.pb();for(m=0;m<k.length;m++){var t=k[m];t&&(p=t.l("g"),q=t.l("l"),t={color:t.l("c"),pattern:t.l("p")},h.add(p,q,t))}}e.pu||(e.pu=
[]);e.pu.push({pu:h,Y8:g,id:f})}else if("styles"==g)f.iHa=this.v3(e,f);else if("a"==g){g=[];e=e.pb();for(h=0;h<e.length;h++)k=e[h].l("id"),m=e[h].l("l"),g.push({id:k,text:m});f.YAa=g}else if("resources"==g){g={};e=e.getAttributes();for(h=0;h<e.length;h++)g[e[h].name]=e[h].value;f.yoa=g}this.qo(b.root,b);return b};D.E.Um=(0,D.ca)(D.r);
D.E.bm=function(b){var c={},d=b.l("sel");c.foa="none"==d?D.r:"single"==d?"s":"m";c.eHa=b.l("sort");if(d=b.l("selIds"))c.NGa=d.split(",");c.W5=b.l("emptyText");c.xFa=b.l("ls");c.cHa=b.l("sv");c.pBa=b.l("cv");if(d=b.l("adu"))c.ZAa=d/1E3;c.aBa=b.l("adc");c.s5=b.l("adi");return c};
D.E.iv=function(b){var c={};c.Y8=b.l("T");c.QFa=b.l("M");c.eU=b.l("ag");c.id=b.l("id");c.size=(0,window.Number)(b.l("s"));c.color=b.l("c");c.pattern=b.l("p");c.label=b.l("l");c.lHa=b.l("tt");c.yV=b.l("ld");c.VBa=b.l("d");c.SEa=b.l("iip");c.pla="t"==b.l("di")?D.o:D.u;c.MGa=b.l("nsel");var d=b.l("tn");d&&(c.Moa=d);if(b=b.l("ls"))c.Eu=new D.P(b);c.eU!=D.r&&(this.k2=window.Math.max(this.k2,c.eU),this.r2=window.Math.min(this.r2,c.eU));return c};
D.E.VF=function(b,c){if(!b||"n"!=b.getName())return D.r;this.Al++;var d=this.iv(b),d=this.Um(this.I,d,c);(0,D.xD)(d,this.aT(b,d,c));return d};D.E.aT=function(b,c,d){var e=[];b=b.pb();for(var f=0;f<b.length;f++){var g=b[f];g&&("el"==g.getName()?d&&c.jba&&c.jba((0,D.qo)(g)):c.nb()&&e.push(this.VF(g,d)))}return e};D.E.u3=function(b,c){var d=(0,D.Bg)(b),e=b.l("T");c.hI||(c.hI={});c.hI[e]||(c.hI[e]=[]);c.hI[e].push(d)};
D.E.qo=function(b,c){if(b){var d=b.So;if(c.hI){var e=c.hI[d];e&&b.T8(e)}if(c.pu)for(var f=0;f<c.pu.length;f++)if(e=c.pu[f],e.Y8==d){if(e.pu instanceof D.Ru&&(d=b,e=e.pu.get(d.Lta)))d.Bg=e;break}if(d=b.pb())for(e=0;e<d.length;e++)this.qo(d[e],c)}};D.DD=function(b,c){for(var d=[],e=0;e<b.length;e++){var f=b[e];f&&f.getName()==c&&d.push(f)}return d};
D.WB.prototype.v3=function(b,c){var d={},e=new D.P(b.l("top"));d.BACKGROUND_STYLE=e;d.ANIMATION_UPDATE_COLOR_STYLE=e.v("-tr-animation-update-color");e=new D.P(b.l("node"));d.LABEL_TEXT_DEFAULT_STYLE=e;var f=e.clone().zb(new D.P(b.l("node-hover"))),g=e.clone().zb(new D.P(b.l("node-selected")));c.XBa=b.l("dsf");c.WBa=b.l("dsb");c.YBa=b.l("dso");this.rY(e,f,g,d);this.Paa(b,d);e=new D.P(b.l("rootText"));d.TEXT_STYLE=e;e=new D.P(b.l("attrType"));d.ATTRIBUTE_TYPE_STYLE=e;e=new D.P(b.l("attrValue"));d.ATTRIBUTE_VALUE_STYLE=
e;e=new D.P(b.l("drillText"));d.DRILL_TEXT_STYLE=e;e=new D.P(b.l("currentText"));d.CURRENT_TEXT_STYLE=e;return d};D.WB.prototype.rY=(0,D.z)();D.WB.prototype.Paa=(0,D.z)();
D.iC=(0,D.z)();D.F.o(D.iC,D.F,"DvtBaseTreeNode");D.yt=new D.lf("#000000",2,5,5,45,0.5);
D.iC.prototype.Init=function(b,c,d){this.I=b;this.So=c.Y8;this.q2=c.QFa;this.Lta=c.eU;this.Qa=c.id;this.Uj=c.size;this.Bg=c.color?c.color:"#000000";this.No=c.pattern;this.hz=c.label;this.my=c.lHa;this.tm=c.Eu;this.QE=c.VBa;this.hg=c.pla;this.uxa=c.SEa;this.XZ=c.fBa;this.et=1;this.hS=D.r;this.Vf=D.u;this.G4=d;c.Moa?(0,D.wD)(this,c.Moa):d&&d.content?(0,D.wD)(this,"content"):d&&d.rootContent&&(0,D.wD)(this,"rootContent");this.JI=D.u;this.hP=c.MGa};
D.xD=function(b,c){if(c!=D.r)for(var d=0;d<c.length;d++)c[d].$e=b;b.Zd=c};D.iC.prototype.pb=(0,D.C)("Zd");D.bp=function(b){var c=[],d,e;if(!b.pe())return c;for(var f=0;f<b.Zd.length;f++)e=b.Zd[f],d=(0,D.bp)(e),c.push(e),c=c.concat(d);return c};D.oC=function(b){var c=b.$e;c&&(c.hS=b)};D.iC.prototype.VC=function(b){return!b||!this.$e?D.u:this.$e==b?D.o:this.$e.VC(b)};
D.qC=function(b,c,d){var e=[];if(0>d)return e;if(0==d)return[b];if(c.pe()){b=c.pb();for(var f=0;f<b.length;f++)c=b[f],e=e.concat((0,D.qC)(c,c,d-1))}return e};D.kp=function(b){var c=[],d;if(!b.pe())return[b];for(var e=0;e<b.Zd.length;e++)d=b.Zd[e],d=(0,D.kp)(d),c=c.concat(d);return c};D.hq=function(b,c){if(b.getId()==c)return b;for(var d=D.r,e=b.pb(),f=e.length,d=D.r,g=0;g<f;g++)if(d=e[g],d=(0,D.hq)(d,c))return d;return D.r};D.E=D.iC.prototype;D.E.getId=(0,D.C)("Qa");D.E.xc=(0,D.C)("Uj");D.E.Lb=(0,D.C)("Bg");
D.E.Jf=(0,D.C)("my");D.E.sj=(0,D.C)("Bg");D.E.Z=(0,D.C)("et");D.E.B=function(b){this.et=b;this.J&&this.J.B(this.et)};D.E.nb=(0,D.C)("hg");D.E.Nq=function(){return"r"==this.QE||"ir"==this.QE};D.E.T8=(0,D.B)("ed");D.E.yd=(0,D.C)("ed");D.E.Kw=(0,D.C)("q2");D.E.L=(0,D.z)();D.E.Ru=function(b){var c=this.pb();if(c!=D.r)for(var d=0;d<c.length;d++)c[d].L(b)};D.E.nh=function(){(0,D.oC)(this);return this};D.E.Je=function(){return new D.I(0,0,0,0)};D.E.ni=function(){this.Dc();this.Ww&&this.Ww();this.Vf=D.o};
D.E.qe=function(){this.li()&&this.sc();this.Kq&&this.Kq();this.Vf=D.u};D.E.li=(0,D.C)("Vf");D.E.Ww=function(){this.JI=D.o};D.E.Kq=function(){this.JI=D.u};D.E.uc=(0,D.ca)(D.o);D.E.mb=(0,D.C)("Gd");D.E.Ob=(0,D.B)("Gd");D.E.Dc=(0,D.z)();D.E.sc=(0,D.z)();D.E.xj=function(b){return this.I.kE(b)};D.E.Rk=function(){return this.I.Ox(this)};D.E.DC=function(){return this.I.Nx()};D.E.DZ=(0,D.C)("J");D.E.JC=(0,D.ca)(D.r);D.E.contains=(0,D.ca)(D.u);D.E.jl=function(){return[]};D.E.jo=(0,D.z)();
D.E.If=function(b,c){b.zJ||(0,D.io)(b,c.pb(),this.pb());var d=c.jl(),e=this.jl(),f;if(!D.Ib.Hh(d,e)&&(f=new D.Nj(this.I.e,this,this.I.HD),(0,D.N)(f.T,"typeNumberArray",this,this.jl,this.jo,e),b.add(f,1),e=this.Uj!=c.Uj,f=D.S.bV(this.Bg)!=D.S.bV(c.Bg),this.jo(d),(d=(0,D.nC)(this,D.r,"ANIMATION_UPDATE_COLOR_STYLE"))&&(e||f)))this.Bg=d};D.E.Mg=function(b){if(!b.zJ||!b.zJ||!(b.wL.getId()==this.getId()||(0,D.Xp)(b.MS,this))){this.B(0);var c=new D.lj(this.I.e,this,this.I.HD);b.add(c,2);for(c=0;c<this.Zd.length;c++)this.Zd[c].Mg(b)}};
D.E.di=function(b,c){c.k(this.J);var d=new D.Jj(this.I.e,this,this.I.HD);b.add(d,0);if(!b.zJ)for(d=0;d<this.Zd.length;d++)this.Zd[d].di(b,c)};D.E.pe=function(){return this.Zd!=D.r&&0<this.Zd.length};D.pC=function(b){var c=0;for(b=b.$e;b;)c++,b=b.$e;return c};D.iC.prototype.QD=function(){return this.No?new D.wc(this.No,this.Bg):new D.Td(this.Bg)};D.uC=function(b){if(b.No)return"#000000";var c=b.Bg;b=D.S.jd(c);var d=D.S.hd(c),c=D.S.fd(c);return 128<=(299*b+587*d+114*c)/1E3?"#000000":"#FFFFFF"};
D.tC=function(b,c){var d=(0,D.uC)(b);c.na(d);d=[];d.push(b.I.yn.LABEL_TEXT_DEFAULT_STYLE);b.tm&&d.push(b.tm);c.Ia((0,D.am)(d))};D.nC=function(b,c,d){(b=b.I.yn[d])&&(c=b);return c};D.jC=function(b){var c=11;(b=b.I.yn.LABEL_TEXT_DEFAULT_STYLE.hH())&&(c=(0,window.parseFloat)(b));return c};D.iC.prototype.La=(0,D.C)("J");D.iC.prototype.mh=(0,D.C)("hz");D.iC.prototype.jba=function(b){b&&!this.gM&&(0,D.wD)(this,"content");this.Wh=b};D.wD=function(b,c){c&&(b.gM=b.G4[c])};D.iC.prototype.Pg=function(){return this.Nq()};
D.wt=function(b,c,d,e,f){this.Init(d,e,f);this.wb=b;this.Qa=c;this.Wx=D.u};D.F.o(D.wt,D.pc,"DvtBaseTreePeer");D.wt.prototype.getId=(0,D.C)("Qa");D.wt.prototype.zna=(0,D.C)("Wx");D.wt.prototype.M8=(0,D.B)("Wx");D.wt.prototype.Kq=function(){this.wb&&this.wb.Kq&&this.wb.Kq()};
D.bq=(0,D.z)();D.F.o(D.bq,D.F,"DvtTreeBreadcrumbsRenderer");D.bq.xsa=6;D.bq.Esa="color: #003286;";
D.bq.L=function(b,c,d,e){var f=b.e,g=[];g.push(b.yn.TEXT_STYLE);g.push(new D.P(D.bq.Esa));g.push(b.yn.DRILL_TEXT_STYLE);var g=(0,D.am)(g).toString(),h=g+"text-decoration: underline;",k=[];k.push(b.yn.TEXT_STYLE);k.push(b.yn.CURRENT_TEXT_STYLE);k=(0,D.am)(k).toString();f=new D.Ku(f,b.wta,b,{Eu:g,S7:h,R7:h,ola:k});b.k(f);d=d.slice(0).reverse();d.push({text:e});f.L({items:d},c.g);e=f.C();(0,D.Xa)(f,c.x,c.y);e=e.j+D.bq.xsa;c.y+=e;c.j-=e;b.removeChild(f);return f};
D.cq=(0,D.z)();D.F.o(D.cq,D.F,"DvtTreeLegendRenderer");D.cq.Jsa=4;D.cq.at=7;D.cq.zP=24;D.cq.Isa=11;D.cq.kca="#636363";D.cq.cIa="color:"+D.cq.kca+";";
D.cq.L=function(b,c,d,e,f,g,h){var k=b.e,m=b.Sa(),p=new D.H(k);b.k(p);var q=D.cq.ML(k,b,p,c.g,d,e,f,g,h),t=b.de.alta?D.r:"#000000",v=[];v.push(b.yn.TEXT_STYLE);var v={borderColor:t,Eu:(0,D.am)(v)},t=D.vD.v8(k,m,p,c.g,c.j,h,v),w=q?q.C():D.r,A=t?t.C():D.r;if(q&&!t)q.F(c.y+(c.g-w.g)/2);else if(t&&!q)t.F(c.y+(c.g-A.g)/2);else if(t&&q){var D$=c.g-D.cq.zP;w.g+A.g>D$&&(w.g>D$/2&&A.g>D$/2?(p.removeChild(q),p.removeChild(t),q=D.cq.ML(k,b,p,D$/2,d,e,f,g,h),t=D.vD.v8(k,m,p,D$/2,c.j,h,v)):w.g>A.g?(m=D$-A.g,p.removeChild(q),
q=D.cq.ML(k,b,p,m,d,e,f,g,h)):(d=D$-w.g,p.removeChild(t),t=D.vD.v8(k,m,p,d,c.j,h,v)),w=q.C(),A=t.C());D.J.S(k)?(t.F(c.x),q.F(c.x+c.g-w.g)):(q.F(c.x),t.F(c.x+c.g-A.g))}h=p.C();p.Q(c.y+c.j-h.j);c.j-=h.j+D.cq.Jsa;b.removeChild(p);return p};
D.cq.ML=function(b,c,d,e,f,g,h,k){var m=D.J.S(b),p=c.Sa(),q=D.r;if(h||k){q=new D.H(b);d.k(q);var t=[];t.push(c.yn.TEXT_STYLE);t.push(c.yn.ATTRIBUTE_TYPE_STYLE);d=(0,D.am)(t);t=[];t.push(c.yn.TEXT_STYLE);t.push(c.yn.ATTRIBUTE_VALUE_STYLE);var t=(0,D.am)(t),v,w,A,D$;c=0;h&&(v=new D.nc(b,f,0,0),v.Ia(d),q.k(v),A=v.Ub().g,w=new D.nc(b,h,0,0),w.Ia(t),q.k(w),D$=w.Ub().g,c=A+D$+D.cq.at);var K,G,M,O;f=0;k&&(K=new D.nc(b,g,0,0),K.Ia(d),q.k(K),M=K.Ub().g,G=new D.nc(b,k,0,0),G.Ia(t),q.k(G),O=G.Ub().g,f=M+O+D.cq.at);
e-=D.cq.zP;c+f>e&&(b=e/2,c>b&&f>b?(D.oc.Vb(w,b-A-D.cq.at,window.Infinity,q)?(D$=w.Ub().g,p.ma(w,new D.pc(h))):(q.removeChild(v),q.removeChild(w),w=D.r,D$=0),D.oc.Vb(G,b-M-D.cq.at,window.Infinity,q)?(O=G.Ub().g,p.ma(G,new D.pc(k))):(q.removeChild(K),q.removeChild(G),G=D.r,O=0)):c>f?D.oc.Vb(w,e-f-A-D.cq.at,window.Infinity,q)?(D$=w.Ub().g,p.ma(w,new D.pc(h))):(q.removeChild(v),q.removeChild(w),w=D.r,D$=0):D.oc.Vb(G,e-c-M-D.cq.at,window.Infinity,q)?(O=G.Ub().g,p.ma(G,new D.pc(k))):(q.removeChild(K),q.removeChild(G),
G=D.r,O=0));e=0;m?(G&&(G.fa(e),e+=O+D.cq.at,K.fa(e),e+=M+D.cq.zP),w&&(w.fa(e),e+=D$+D.cq.at,v.fa(e))):(w&&(v.fa(e),e+=A+D.cq.at,w.fa(e),e+=D$+D.cq.zP),G&&(K.fa(e),e+=M+D.cq.at,G.fa(e)))}return q};
D.dq=function(b){this.Init(b)};D.F.o(D.dq,D.Xn,"DvtBaseTreeKeyboardHandler");D.dq.prototype.DH=function(b){return this.bk(b)&&!b.ctrlKey};D.dq.prototype.XC=function(b){return 32==b.keyCode&&b.ctrlKey};
D.wC=(0,D.z)();D.F.o(D.wC,D.Mg,"DvtBaseTreeDefaults");D.AD={skin:"skyros",emptyText:"No data to display",nodeDefaults:{labelStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px;")},styleDefaults:{_attributeTypeTextStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;font-weight:bold;color:#4F4F4F"),_attributeValueTextStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;")},_resources:{}};
D.wC.prototype.Init=function(b){b={skyros:D.xa.zb(b.skyros,D.AD),alta:D.xa.zb(b.alta,{})};D.wC.q.Init.call(this,b)};
D.dC=(0,D.z)();D.F.o(D.dC,D.F,"DvtBaseTreeJsonUtils");
D.dC.prototype.b9=function(b){var c;c="\x3c"+this.DO();c+=this.gJ(b);c+="\x3e\n";if(b&&b.nodes)for(var d=b.nodes,e=0;e<d.length;e++)c+=(0,D.CD)(this,b,d[e]);d="\x3ca/\x3e\n"+this.lZ(b);d+=this.iJ(b);if(e=b.attributeGroups?b.attributeGroups[0]:D.r)if(b='\x3cag id\x3d"'+e.id+'"',"continuous"==e.attributeType)b+=this.Ca("t","continuous"),b+=this.Ca("ramp",e.colors.join(";")),b+=this.Ca("minValue",e.min),b+=this.Ca("maxValue",e.max),b+=this.Ca("minLabel",e.minLabel),b+=this.Ca("maxLabel",e.maxLabel),
b+="/\x3e";else{b+="\x3e\n";for(var e=e.groups,f=0;f<e.length;f++)b+="\x3ci",b+=this.Ca("g",e[f].id),b+=this.Ca("l",e[f].label),b+=this.Ca("c",e[f].color),b+=this.Ca("p",e[f].pattern),b+="/\x3e\n";b+="\x3c/ag\x3e\n"}else b="";d=d+b+("\x3c/"+this.DO()+"\x3e");return c+=d};D.dC.prototype.Ca=function(b,c){return c!=D.r?" "+b+'\x3d"'+c+'"':""};D.dC.prototype.DO=(0,D.ca)(D.r);
D.dC.prototype.gJ=function(b){var c;c=""+this.Ca("sv",b.sizeLabel);c+=this.Ca("cv",b.colorLabel);var d=b.attributeGroups?b.attributeGroups[0]:D.r;d&&(c+=this.Ca("ls",d.id));for(var d=b.selectedNodes?b.selectedNodes:[],e="",f=0;f<d.length;f++)0<e.length&&(e+=","),e+=d[f];0<e.length&&(c+=this.Ca("selIds",e));c+=this.Ca("adu",b.animationDuration);c+=this.Ca("adc",b.animationOnDataChange);c+=this.Ca("emptyText",b.emptyText);c+=this.Ca("sel",b.selection);return c+=this.Ca("sort",b.sorting)};
D.CD=function(b,c,d){var e;e="\x3cn"+b.hJ(c,d);if(d&&d.nodes&&0<d.nodes.length){e+=b.Ca("di","t");e+="\x3e\n";d=d.nodes;for(var f=0;f<d.length;f++)e+=(0,D.CD)(b,c,d[f]);e+="\x3c/n\x3e\n"}else e+="/\x3e\n";return e};
D.dC.prototype.hJ=function(b,c){var d;d=""+this.Ca("id",c.id);d+=this.Ca("s",c.value);d+=this.Ca("c",c.color);d+=this.Ca("l",c.label);d+=this.Ca("p",c.pattern);d+=this.Ca("tt",c.shortDesc?c.shortDesc:c.tooltip);d+=this.Ca("ls",c.labelStyle?c.labelStyle:b.nodeDefaults.labelStyle);var e=c.drilling?c.drilling:b.nodeDefaults.drilling;"insert"==e?d+=this.Ca("d","i"):"replace"==e?d+=this.Ca("d","r"):"insertAndReplace"==e&&(d+=this.Ca("d","ir"));return d+=this.Ca("nsel",c.selectable?c.selectable:"auto")};
D.dC.prototype.lZ=(0,D.z)();D.dC.prototype.iJ=function(b){var c;c="\x3cstyles "+this.Ca("attrType",b.styleDefaults._attributeTypeTextStyle);return c+=this.Ca("attrValue",b.styleDefaults._attributeValueTextStyle)};
D.Up=function(b){this.lb(b)};D.F.o(D.Up,D.F,"DvtTreeAutomation");D.Up.prototype.lb=(0,D.B)("zka");D.Up.prototype.click=function(b){this.t8(b,0)};
D.Up.prototype.t8=function(b,c){c===D.n&&(c=-1);if(b==D.r)return D.r;var d;if(-1!=c){if(0==c){var e=(0,D.yD)(b);e&&"node"==e[0]&&(e=(0,D.zD)(this.zka.kb,e,1))&&(0,D.De)(e.La(),D.Ta)}}else if((e=(0,D.yD)(b))&&"node"==e[0]){var f=e.length-1,g=e[f];0<=g.indexOf("#")&&(e[f]=D.r,(e=(0,D.zD)(this.zka.kb,e,1))&&("#label"==g?d=e.mh():"#size"==g?d=e.xc():"#color"==g?d=e.Lb():"#tooltip"==g&&(d=e.Jf())))}return d};
D.zD=function(b,c,d){var e=D.r;if(b.uxa==c[d])if(c[d+1]==D.r)e=b;else if(b=b.pb())for(var f=0;f<b.length&&!(e=(0,D.zD)(b[f],c,d+1));f++);return e};D.yD=function(b){b=b.split("[");var c;c=D.r;if(b&&0<=b.length){var d=b.length-1,e=b[d],f=e.indexOf("#");0<f&&(b[d]=e.substr(0,f),c=e.substr(f))}d=b.length;for(e=1;e<d;e++)f=b[e],f=f.substr(0,f.length-1),window.tempIdAsNumber=(0,window.parseFloat)(f),f=(0,window.isNaN)(window.tempIdAsNumber)?f:window.tempIdAsNumber,b[e]=f;c&&(b[d]=c);return b};
});