define(['./DvtToolkit', './DvtAxis'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.vp=(0,D.z)();(0,D.ta)("DvtGauge",D.vp);D.F.o(D.vp,D.Rb,"DvtGauge");D.vp.prototype.Init=function(b,c,d,e){D.vp.q.Init.call(this,b,c,d);this.Oe=new D.Dp;e||(this.wa=this.N9(),this.wa.bf(this),this.setId("gauge1000"+window.Math.floor(1E9*window.Math.random())),this.eB=new D.td(b,0,0),(0,D.vd)(this.eB),this.k(this.eB));this.JA=D.u;this.KF=D.r};D.vp.prototype.te=function(b){this.W=b;D.J.Nh()||(this.W.animationOnDisplay="none",this.W.animationOnDataChange="none")};
D.vp.prototype.L=function(b,c,d){b?this.te(b):this.W||this.te(D.r);this.W.thresholds&&(this.W.thresholds=this.W.thresholds.sort(D.Ep));!(0,window.isNaN)(c)&&!(0,window.isNaN)(d)&&(this.ub=c,this.Mb=d);c=this.xA;this.xA=[];d=new D.H(this.e);this.Ha(d,0);this.ll(d,this.ub,this.Mb);var e=b!=D.r,f=this.ub,g=this.Mb;this.qb&&this.qb.stop();b=D.u;var h=this.JA?"none":this.Fa().animationOnDataChange,k=this.JA?"none":this.Fa().animationOnDisplay,m=this.Fa().animationDuration/1E3;if(k||h){f=new D.I(0,0,f,
g);g=this.e;if(!this.ga&&"none"!==k)this.qb=D.$a.iH(g,k,d,f,m),this.qb||(this.qb=this.UW(this.xA,k,m));else if(this.ga&&"none"!=h&&e)if(this.qb=D.$a.nz(g,h,this.ga,d,f,m))b=D.o;else{e=this.xA;h=[];for(k=0;k<c.length;k++){var f=e[k],p=c[k].Te(),g=f.Te();f.Qf(p);p=new D.Nj(this.e,f,m);(0,D.N)(p.T,"typeNumberArray",f,f.Te,f.Qf,g);h.push(p)}this.qb=new D.Nd(this.e,h)}b||this.removeChild(this.ga);this.qb&&(this.qb.play(),this.qb.Ad(this.xL,this));b&&(this.Gk=this.ga);this.ga=d}this.eB&&(this.W.readOnly===
D.u&&D.J.da()?(this.eB.ia(this.ub),this.eB.va(this.Mb)):(this.eB.ia(0),this.eB.va(0)));(0,D.vf)(d);(0,D.xf)(d,"label",this.W.shortDesc)};D.vp.prototype.render=D.vp.prototype.L;D.E=D.vp.prototype;D.E.ll=(0,D.z)();D.E.UW=(0,D.ca)(D.r);D.E.tx=(0,D.ca)(D.r);D.E.xL=function(){this.Gk&&(this.removeChild(this.Gk),this.Gk=D.r);this.qb=D.r};D.E.Fa=(0,D.C)("W");D.E.Sa=(0,D.C)("wa");D.E.GP=function(b,c){this.JA=D.o;this.KF=this.W.value;this.oJ(b,c)};
D.E.oJ=function(b,c){this.W.value=D.Fp.Nka(this.W,this.tx(b,c));this.L();this.ib(new D.to(this.KF,this.W.value,D.u))};D.E.FP=function(b,c){this.oJ(b,c);this.ib(new D.to(this.KF,this.W.value,D.o));this.JA=D.u;this.KF=D.r};D.E.N9=function(){return new D.Gp(this)};D.Ep=function(b,c){return b.max&&c.max?window.Math.abs(b.max)-window.Math.abs(c.max):b.max?-window.Infinity:window.Infinity};
D.Dp=(0,D.z)();D.F.o(D.Dp,D.km,"DvtGaugeBundle");D.Dp._defaults={EMPTY_TEXT:"No data to display"};D.Dp.prototype.fA=function(b){return D.Dp._defaults[b]};D.Dp.prototype.eA=(0,D.ca)("DvtGaugeBundle");
D.iD=(0,D.z)();D.F.o(D.iD,D.Mg,"DvtGaugeDefaults");D.jD={skin:"alta",color:"#393737",metricLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};D.kD={skin:"skyros",min:0,max:100,color:"#313842",borderColor:D.r,visualEffects:"auto",emptyText:D.r,animationOnDataChange:"none",animationOnDisplay:"none",animationDuration:500,readOnly:"true",metricLabel:{rendered:"off",scaling:"auto",style:new D.P,textType:"number"},__layout:{outerGap:1,labelGap:3}};
D.iD.prototype.Init=function(b){b={skyros:D.xa.zb(b.skyros,D.kD),alta:D.xa.zb(b.alta,D.jD)};D.iD.q.Init.call(this,b)};D.gD=function(b){return"skyros"==b.Fa().skin};
D.Pp={};D.F.o(D.Pp,D.F,"DvtGaugeDataUtils");D.Pp.wu=function(b){b=b.Fa();return!b||(0,window.isNaN)(b.value)||b.value===D.r?D.u:D.o};D.Pp.n7=function(b){var c=b.Fa();b=c.value;c=c.thresholds;if(!c)return-1;for(var d=0;d<c.length;d++)if(b<=c[d].max)return d;return c.length-1};D.Pp.l7=function(b,c){var d=b.Fa().thresholds;return d&&0<=c&&c<d.length?d[c]:D.r};D.Pp.MKa=function(b,c){var d=b.Fa().referenceLines;return d&&0<=c&&c<d.length?d[c]:D.r};
D.Gp=function(b){this.Init(b.e,b.ib,b);this.Yh=b;this.Tk=D.u};D.F.o(D.Gp,D.xc,"DvtGaugeEventManager");D.E=D.Gp.prototype;D.E.kl=function(b){this.Yh.Fa().readOnly===D.u?(this.Tk=D.o,this.oc(),b=(0,D.eD)(this,b.pageX,b.pageY),this.Yh.GP(b.x,b.y)):D.Gp.q.kl.call(this,b)};D.E.Ym=function(b){this.Tk?(this.Tk=D.u,b=(0,D.eD)(this,b.pageX,b.pageY),this.Yh.FP(b.x,b.y)):D.Gp.q.Ym.call(this,b)};
D.E.Xm=function(b){if(this.Tk){var c=(0,D.eD)(this,b.pageX,b.pageY);this.Yh.oJ(c.x,c.y)}(this.oaa()||!this.Tk)&&D.Gp.q.Xm.call(this,b)};D.E.oaa=(0,D.ca)(D.u);
D.E.XI=function(b){if(D.Sa.Sd===b.type&&this.Yh.Fa().readOnly===D.u){this.Tk=D.o;var c=(0,D.eD)(this,b.touches[0].pageX,b.touches[0].pageY);this.Yh.GP(c.x,c.y);b.preventDefault()}else D.Sa.sh===b.type&&this.Tk?(c=(0,D.eD)(this,b.touches[0].pageX,b.touches[0].pageY),this.Yh.oJ(c.x,c.y),b.preventDefault()):D.Sa.eg===b.type&&this.Tk?(this.Tk=D.u,c=(0,D.eD)(this,b.changedTouches[0].pageX,b.changedTouches[0].pageY),this.Yh.FP(c.x,c.y),b.preventDefault()):D.Gp.q.XI.call(this,b)};
D.eD=function(b,c,d){c=(0,D.rg)(b.e,c,d);return b.Yh.Gb(c)};
D.hD={};D.F.o(D.hD,D.F,"DvtGaugeStyleUtils");D.hD.Fca=["#ed6647","#fad55c","#68c182"];D.hD.mta=["#D62800","#FFCF21","#84AE31"];D.hD.Lb=function(b){var c=b.Fa(),d=D.Pp.n7(b),e=D.Pp.l7(b,d);return e&&(!(b instanceof D.zp)||b instanceof D.zp&&"onIndicator"==c.thresholdDisplay)?D.hD.bN(b,e,d):c.color};D.hD.Ih=function(b){var c=b.Fa(),d=D.Pp.l7(b,D.Pp.n7(b));return d&&d.borderColor&&(!(b instanceof D.zp)||b instanceof D.zp&&"onIndicator"==c.thresholdDisplay)?d.borderColor:c.borderColor};
D.hD.Kma=function(b){var c=b.Fa(),d=D.Pp.n7(b),e=D.Pp.l7(b,d);return e&&(!(b instanceof D.zp)||b instanceof D.zp&&"onIndicator"!=c.thresholdDisplay)?D.hD.bN(b,e,d):c.plotArea.color};D.hD.bN=function(b,c,d){if(c.color)return c.color;if(d<D.hD.Fca.length)return(0,D.gD)(b)?D.hD.mta[d]:D.hD.Fca[d]};
D.Fp={};D.F.o(D.Fp,D.F,"DvtGaugeRenderer");D.Fp.qZ=2;D.Fp.bca=1;D.Fp.Qz=function(b,c,d){var e=b.Fa(),f=e.emptyText;f||(f=(0,D.Wm)(b.Oe,"EMPTY_TEXT",D.r));var g=d.g-2*D.Fp.qZ,h=d.j-2*D.Fp.bca;d=new D.nc(b.e,f,d.x+d.g/2,d.y+d.j/2);e.metricLabel.style.v("font-size")||e.metricLabel.style.ba("font-size","13px");d.Ia(e.metricLabel.style);d.rf();d.Fe();D.oc.Vb(d,g,h,c)&&d.ef()&&b.Sa().ma(d,new D.pc(f))};
D.Fp.qz=function(b,c){var d=c.Fa(),e="percent"==d.metricLabel.textType;e&&(b=100*D.Fp.gH(d,d.min,b));var f=D.r;"on"==d.metricLabel.rendered&&d.metricLabel.converter&&(f=d.metricLabel.converter);var g=D.r;"on"==d.metricLabel.rendered&&d.metricLabel.scaling&&(g=d.metricLabel.scaling);return D.Fp.rfa(b,c,f,g,d.metricLabel.autoPrecision?d.metricLabel.autoPrecision:"on",e)};
D.Fp.yU=function(b,c){var d=c.Fa(),e="percent"==d.tickLabel.textType;e&&(b=100*D.Fp.gH(d,d.min,b));var f=D.r;"on"==d.tickLabel.rendered&&d.tickLabel.converter&&(f=d.tickLabel.converter);var g=D.r;"on"==d.tickLabel.rendered&&d.tickLabel.scaling&&(g=d.tickLabel.scaling);return D.Fp.rfa(b,c,f,g,d.tickLabel.autoPrecision?d.tickLabel.autoPrecision:"on",e)};
D.Fp.rfa=function(b,c,d,e,f,g){var h=c.Fa();c=b;c=h.min;var h=h.max,k=h-c,m=D.r;(0,window.isNaN)(k)||(m=k/(1E3>k?100:1E3));e=new D.SB(c,h,m,e,f);if(d&&d.getAsString)c=e.Bq(b,d);else{if(d&&d.format)return e.Bq(b,d);c=e.Bq(b)}return g?(0,window.String)(c)+"%":c};D.Fp.gH=function(b,c,d){b=(d-c)/(b.max-b.min);return b=window.Math.min(window.Math.max(0,b),1)};
D.Fp.x8=function(b,c,d,e){var f=b.Fa();if("on"==f.metricLabel.rendered){var g=D.Fp.qz(f.value,b),h=d.g,k=d.j,m=new D.nc(b.e,g,d.x+d.g/2,d.y+d.j/2);m.Ia(f.metricLabel.style);var p=f.metricLabel.style.v("font-size");if(!f.metricLabel.style.v("font-size")){var p=window.Math.max(f.max.toString().length,f.min.toString().length,g.length),q="";"percent"==f.metricLabel.textType&&(p=window.Math.max(3,g.length),q+="%");for(f=0;f<p;f++)q+="0";m.pd(q);p=m.Rw(d);m.pd(g);m.wf(p)}m.Fe();m.rf();e!=D.r&&m.na(e);D.oc.Vb(m,
h,k,c)&&m.ef()&&b.Sa().ma(m,new D.pc(g))}};D.Fp.Nka=function(b,c){var d=(0,window.Number)(b.step);if(d&&0<d){var e=(c-b.min)/d;return 0.5<e?window.Math.max(window.Math.min(b.max,window.Math.ceil(e)*d+b.min),b.min):b.min}return c};
D.up=(0,D.z)();(0,D.ta)("DvtLedGauge",D.up);D.F.o(D.up,D.vp,"DvtLedGauge");D.wp=function(b,c,d,e){var f=new D.up;f.Init(b,c,d,e);return f};D.up.newInstance=D.wp;D.up.prototype.Init=function(b,c,d,e){D.up.q.Init.call(this,b,c,d,e);this.hf=new D.xp};D.up.prototype.te=function(b){D.up.q.te.call(this,this.hf.sg(b));"auto"==this.W.animationOnDisplay&&(this.W.animationOnDisplay="zoom");"auto"==this.W.animationOnDataChange&&(this.W.animationOnDataChange="alphaFade");this.W.readOnly=D.o};
D.up.prototype.ll=function(b,c,d){D.yp.L(this,b,c,d)};
D.xp=function(){this.Init({skyros:D.qD,alta:{}})};D.F.o(D.xp,D.iD,"DvtLedGaugeDefaults");D.qD={type:"circle"};
D.yp={};D.F.o(D.yp,D.F,"DvtLedGaugeRenderer");D.yp.oIa=1/6;D.yp.kta="M8,86.6Q0,86.6,3.46,78.6L46,6.93Q50,0,54,6.93L96.54,78.6Q100,86.6,92,86.6Z";D.yp.fta="M0,86.6L50,0L100,86.6Z";D.yp.lta="M0,86.6L50,0L100,86.6Z";D.yp.Dca=[-13.05,-12.94,-50,-11.13,-21.06,11.9,-30.74,47.6,0.1,27.18,31.06,47.44,21.17,11.79,50,-11.39,13.05,-13.01,-0.06,-47.59];D.yp.eta=[-50,-11.22,-16.69,-17.94,0,-47.55,16.69,-17.94,50,-11.22,26.69,13.8,30.9,47.56,0,33.42,-30.9,47.56,-26.69,13.8];D.yp.ita="M50,95L71,95Q74.414,94.414,75,91L75,60L92,60Q98.5,59.1,95,54L52,12Q50,11,48,12L5,54Q1.5,59.1,8,60L25,60L25,91Q25.586,94.414,29,95Z";
D.yp.dta="M75,98L75,58L97.5,58L50,11L2.5,58L25,58L25,98Z";D.yp.jta="M75,98L75,58L97.5,58L50,11L2.5,58L25,58L25,98Z";
D.yp.L=function(b,c,d,e){if(D.Pp.wu(b)){var f=b.Fa(),g=f.__layout.outerGap,h=f&&(0<=f.size||1>f.size)?window.Math.sqrt(f.size):1;d=new D.I(g+(d-2*g)*(1-h)/2,g+(e-2*g)*(1-h)/2,(d-2*g)*h,(e-2*g)*h);D.yp.PL(b,c,d);D.yp.N3(b,c,d);"on"==f.metricLabel.rendered&&(f.metricLabel.style.v("color")!=D.r?D.Fp.x8(b,c,D.yp.Gfa(b,d)):(e=D.hD.Lb(b),e=D.S.Kl(e),f.metricLabel.style.ba("color",e),D.Fp.x8(b,c,D.yp.Gfa(b,d),e)))}else D.Fp.Qz(b,c,new D.I(0,0,d,e))};
D.yp.PL=function(b,c,d){var e=b.e,f=b.Fa(),g=f.type,h=D.hD.Lb(b),k=D.hD.Ih(b),m=d.x+d.g/2,p=d.y+d.j/2,q=window.Math.min(d.g,d.j)/2,t=(0,D.gD)(b);"rectangle"==g?e=new D.td(e,d.x,d.y,d.g,d.j):"diamond"==g?e=new D.tc(e,[m-q,p,m,p-q,m+q,p,m,p+q]):"triangle"==g?(m=t?D.yp.kta:D.yp.fta,e=new D.Pa(e,m)):"star"==g?(m=t?D.yp.Dca:D.yp.eta,p=window.Math.min(d.g/100,d.j/100),m=D.Yf.scale(m,p,p),m=D.Yf.translate(m,d.x+d.g/2,d.y+d.j/2),e=new D.tc(e,m)):"arrow"==g?(m=t?D.yp.ita:D.yp.dta,e=new D.Pa(e,m)):e=new D.Rd(e,
m,p,q);t||"none"==f.visualEffects?e.na(h):(t=[D.S.rg(h,-0.09,0.04),D.S.rg(h,-0.04,-0.05)],m=f&&0==f.rotation%90?f.rotation:0,e.G(new D.xd("arrow"==g||"star"==g||"triangle"==g?360-m:270,t,[1,1],[0,1])));k&&e.Ma(k);(f=f.shortDesc)&&b.Sa().ma(e,new D.pc(D.r,f,h));e=D.yp.wT(b,c,e,d);c.k(e)};
D.yp.wT=function(b,c,d,e){var f=b.Fa(),g=f.type;if("triangle"==g||"arrow"==g){var h=new D.H(b.e);b=new D.H(b.e);c.k(h);h.k(b);b.k(d);f=f&&0==f.rotation%90?f.rotation:0;f="star"==g?0:f;g=new D.ib;g.rotate(window.Math.PI*(90-f)/180);d.qa(g);g=b.C();g=window.Math.min(e.g/g.g,e.j/g.j);f=new D.ib;f.scale(g,g);b.qa(f);f=h.C();b=e.x+e.g/2-(f.x+f.g/2);e=e.y+e.j/2-(f.y+f.j/2);f=new D.ib;f.translate(b,e);h.qa(f);c.removeChild(h);if(c=d.nc())c=c.clone(),c.ia(c.getWidth()/g),d.Y(c);return h}return d};
D.yp.N3=function(b,c,d){var e=b.Fa(),f=e.type;"none"!=e.visualEffects&&(0,D.gD)(b)&&("rectangle"==f?D.yp.Gza(b,c,d):"diamond"==f?D.yp.Fza(b,c,d):"triangle"==f?D.yp.Iza(b,c,d):"star"==f?D.yp.Hza(b,c,d):"arrow"==f?D.yp.Dza(b,c,d):D.yp.Eza(b,c,d))};
D.yp.Gza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);b=new D.td(b.e,d.x,d.y,d.g,d.j);b.la(D.u);c.k(b);c=new D.xd(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.G(c)};
D.yp.Fza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j,f=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);d=f.x+f.g/2;e=f.y+f.j/2;f=window.Math.min(f.g,f.j)/2;b=new D.tc(b.e,[d-f,e,d,e-f,d+f,e,d,e+f]);b.la(D.u);c.k(b);c=new D.xd(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.G(c)};
D.yp.Iza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);e=new D.Pa(b.e,D.yp.lta);f=b.Fa();f=new D.xd(360-(f&&0==f.rotation%90?f.rotation:0),["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);e.G(f);e=D.yp.wT(b,c,e,d);e.la(D.u);c.k(e)};
D.yp.Dza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);e=new D.Pa(b.e,D.yp.jta);f=b.Fa();f=new D.xd(360-(f&&0==f.rotation%90?f.rotation:0),["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);e.G(f);e=D.yp.wT(b,c,e,d);e.la(D.u);c.k(e)};
D.yp.Hza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);var e=new D.Pa(b.e,D.yp.Dca),f=b.Fa(),f=360-(f&&0==f.rotation%90?f.rotation:0),g=D.hD.Lb(b),g=[D.S.Ll(g,0.9),g,D.S.Qla(g)],f=new D.xd(f,g,[1,1,1],[0.1,0.4,0.8]);e.G(f);e=D.yp.wT(b,c,e,d);e.la(D.u);c.k(e)};
D.yp.Eza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);var e=d.x+d.g/2,f=d.y+d.j/2,g=window.Math.min(d.g,d.j)/2,h=new D.Rd(b.e,e,f,g);h.la(D.u);c.k(h);var k=new D.dg(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.25,0.5],[0.15,0.7,0.95],e,f-0.6*g,1.5*g,[d.x,d.y,d.g,d.j]);h.G(k);h=0.6*g;g*=0.4;f-=0.3*g;b=new D.Ze(b.e,e,f-g,h,g);b.la(D.u);c.k(b);c=new D.dg(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.2,0.5],[0.6,0.8,1],e,f,h,[d.x,d.y,d.g,d.j]);b.G(c)};
D.yp.Gfa=function(b,c){var d=b.Fa(),e=d.type,d=0==d.rotation%90?d.rotation:0,f=window.Math.min(c.g,c.j),g=c.x+c.g/2-f/2,h=c.y+c.j/2-f/2,k=f,m=f;"triangle"==e?0==d?(g+=0.05*f,h+=0.2*f,k-=0.3*f,m-=0.4*f):90==d?(g+=0.2*f,h+=0.25*f,k-=0.4*f,m-=0.3*f):180==d?(g+=0.25*f,h+=0.2*f,k-=0.3*f,m-=0.4*f):270==d&&(g+=0.2*f,h+=0.05*f,k-=0.4*f,m-=0.3*f):"arrow"==e?0==d?(g+=0.05*f,h+=0.2*f,k-=0.28*f,m-=0.4*f):90==d?(g+=0.2*f,h+=0.2*f,k-=0.4*f,m-=0.4*f):180==d?(g+=0.23*f,h+=0.2*f,k-=0.28*f,m-=0.4*f):270==d&&(g+=0.2*
f,h+=0.2*f,k-=0.4*f,m-=0.4*f):"star"==e?(g+=0.25*f,h+=0.25*f,k-=0.5*f,m-=0.4*f):"diamond"==e?(g+=0.15*f,h+=0.15*f,k-=0.3*f,m-=0.3*f):"rectangle"==e?(g+=0.1*f,h+=0.1*f,k-=0.2*f,m-=0.2*f):"circle"==e&&(g+=0.15*f,h+=0.15*f,k-=0.3*f,m-=0.3*f);return new D.I(g,h,k,m)};
D.zp=(0,D.z)();(0,D.ta)("DvtStatusMeterGauge",D.zp);D.F.o(D.zp,D.vp,"DvtStatusMeterGauge");D.Ap=function(b,c,d){var e=new D.zp;e.Init(b,c,d);return e};D.zp.newInstance=D.Ap;D.E=D.zp.prototype;D.E.Init=function(b,c,d){D.zp.q.Init.call(this,b,c,d);this.hf=new D.Bp;this.CZ=D.r};D.E.te=function(b){D.zp.q.te.call(this,this.hf.sg(b))};D.E.ll=function(b,c,d){D.Cp.L(this,b,c,d)};
D.E.UW=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.Te();"horizontal"==this.W.orientation||"vertical"==this.W.orientation?f.Qf([g[0],g[0],g[2],g[3]]):f.Qf([g[0],g[1],0,g[3],g[4]]);var h=new D.Nj(this.e,f,d);(0,D.N)(h.T,"typeNumberArray",f,f.Te,f.Qf,g);h.T.Cj(function(b){return(0,D.Dj)(b,0.7)});c.push(h)}return new D.Nd(this.e,c)};
D.E.tx=function(b,c){if("horizontal"==this.W.orientation)return this.CZ.xC(b);if("vertical"==this.W.orientation)return this.CZ.xC(c);if("circular"==this.W.orientation){var d=D.Xe.u8(window.Math.atan2(c-this.Mb/2,b-this.ub/2))-270,d=(d+720)%360;0<=d&&360>=d||(d=360<d?360-d<d-360?0:360:0-d<d?0:360);if(D.J.S(this.e))for(d=360-d;0>d;)d+=360;var e=this.W.min;return d/360*(this.W.max-e)+e}};
D.Bp=function(){this.Init({skyros:D.tD,alta:D.uD})};D.F.o(D.Bp,D.iD,"DvtStatusMeterGaugeDefaults");D.uD={color:"#393737",metricLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},plotArea:{color:"#f5f6f7",borderColor:"#D6DFE6"}};D.tD={color:"#313842",indicatorSize:1,metricLabel:{style:new D.P("color: #333333;")},orientation:"horizontal",plotArea:{color:"#AAAAAA",borderColor:"#C6C6C6",rendered:"auto"},thresholdDisplay:"onIndicator"};
D.Cp={};D.F.o(D.Cp,D.F,"DvtStatusMeterGaugeRenderer");D.Cp.L=function(b,c,d,e){if(D.Pp.wu(b)){var f=b.Fa(),g=f.__layout.outerGap;d=new D.I(g,g,d-2*g,e-2*g);"horizontal"==f.orientation||"vertical"==f.orientation?(D.Cp.Vr(b,c,d),D.Cp.PL(b,c,d)):"circular"==f.orientation&&(f=window.Math.min(d.g,d.j),D.Fp.x8(b,c,new D.I(d.x+d.g/2-0.325*f,d.y+d.j/2-0.25*f,0.65*f,0.5*f)),D.Cp.mza(b,c,d))}else D.Fp.Qz(b,c,new D.I(0,0,d,e))};
D.Cp.mza=function(b,c,d){var e=b.Fa(),f=0,g=e.value,h=e.thresholds,k=window.Math.min(d.g,d.j),m=0.3125*k,p=0.4625*k,q=1.5*window.Math.PI,f=2*f*window.Math.PI;if(h&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(var t=0;t<h.length;t++){var v=D.hD.bN(b,h[t],t),f=h[t].max?h[t].max:e.max,w=0==t?e.min:h[t-1].max,q=1.5*window.Math.PI+2*window.Math.PI*D.Fp.gH(e,e.min,w),f=D.Fp.gH(e,w,f),f=2*f*window.Math.PI;D.Cp.I0(b,c,d,q,f,m,p,v,D.u)}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&
"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(v=D.hD.Kma(b),q=1.5*window.Math.PI,f=2*window.Math.PI,D.Cp.I0(b,c,d,q,f,m,p,v,D.o));if((h=e.indicatorSize)&&1!=h)k*=0.075*(1-h),m+=k,p-=k;q=1.5*window.Math.PI;f=D.Fp.gH(e,e.min,g);f=2*f*window.Math.PI;D.Cp.I0(b,c,d,q,f,m,p,D.hD.Lb(b),D.u);if(m=e.referenceLines)for(p=0;p<m.length;p++)k=m[p].color?m[p].color:"black",h=m[p].lineWidth?m[p].lineWidth:2,q=m[p].lineStyle,g=m[p].value,window.angle=1.5*window.Math.PI+2*D.Fp.gH(e,e.min,g)*window.Math.PI,
D.Cp.Nva(b,c,d,k,h,q);d=new D.td(b.e,d.x,d.y,d.g,d.j);(0,D.vd)(d);c.k(d);((c=e.shortDesc)||b.Fa().readOnly===D.u)&&b.Sa().ma(d,new D.pc(D.r,c,D.hD.Lb(b)))};
D.Cp.PL=function(b,c,d){var e=b.Fa(),f=D.J.S(b.e),g="vertical"==e.orientation,h={layout:{}};h.layout.gapRatio=0;h.timeAxisType="disabled";h.position=g?"left":"bottom";h.min=e.min;h.max=e.max;h.dataMin=e.min;h.dataMax=e.max;h.tickLabel={rendered:"off"};h=(0,D.oD)(b.e,h,d);b.CZ=h;var k=0;0>e.max?k=e.max:0<e.min&&(k=e.min);var m=h.Xj(k);"off"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&(m=h.Wc(e.min));var p=h.Wc(e.value),p=g?window.Math.max(d.y,window.Math.min(d.y+
d.j,p)):window.Math.max(d.x,window.Math.min(d.x+d.g,p)),q=0,q=0>e.min&&0>e.value?h.Wc(e.min):h.Wc(e.max),t,v,w,A,D$,K,G,M=0;g?(t=d.x,v=d.x+d.g,A=m,w=window.Math.max(d.y,window.Math.min(d.y+d.j,q)),D$=d.x+(1-e.indicatorSize)/2*d.g+0.5,K=d.x+d.g*(1-(1-e.indicatorSize)/2)-0.5,M=m-0.5,G=p+0.5):(t=m,v=window.Math.max(d.x,window.Math.min(d.x+d.g,q)),w=d.y,A=d.y+d.j,D$=f?m-0.5:m+0.5,K=f?p+0.5:p-0.5,G=d.y+(1-e.indicatorSize)/2*d.j+0.5,M=d.y+d.j*(1-(1-e.indicatorSize)/2)-0.5);q=D.o;p==m&&(q=D.u);var O=D.hD.Ih(b),
T=e.plotArea.borderColor,Q=e.thresholds,m=g?0:270;if(Q&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(p=Q.length-1;0<=p;p--){var V=p,aa=D.Cp.Ev(b,b.e,t,v,w,A,D.o),oa=new D.Sg("pacp"+b.getId());if(V==Q.length-1)g?(0,D.Tg)(oa,0,0,d.g+2,A-w+2,0,0):f?(0,D.Tg)(oa,h.Wc(e.max),0,d.g+2,A-w+2,0,0):(0,D.Tg)(oa,0,0,d.g+2,A-w+2,0,0);else if(g){var sa=Q[Q.length-2-V].max==D.r?100:Q[Q.length-2-V].max;(0,D.Tg)(oa,0,h.Wc(e.max),v-t+2,1*Q[V].max/window.Math.abs(k-e.max)*d.j,0,0)}else f?(sa=Q[Q.length-
2-V].max==D.r?100:Q[Q.length-2-V].max,(0,D.Tg)(oa,0,0,1*(e.max-sa)/window.Math.abs(k-e.max)*d.g,A-w+2,0,0)):(0,D.Tg)(oa,0,0,1*Q[V].max/window.Math.abs(k-e.max)*d.g,A-w+2,0,0);(0,D.sf)(aa,oa);if(f||g)V=Q.length-1-p;aa.na(D.hD.bN(b,Q[V],V));aa.Ma(T);D.Cp.sja(b,c,aa,D.hD.bN(b,Q[V],V),m)}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(aa=g?D.Cp.Ev(b,b.e,t,v,h.Wc(e.max),h.Wc(e.min),D.o):D.Cp.Ev(b,b.e,h.Wc(e.min),h.Wc(e.max),
w,A,D.o),p=D.hD.Kma(b),aa.na(p),aa.Ma(T),D.Cp.sja(b,c,aa,p,m));p=D.Cp.Ev(b,b.e,D$,K,G,M,D.o);b.xA.push(p);f=D.hD.Lb(b);!(0,D.gD)(b)&&"none"!=e.visualEffects?(k=[D.S.rg(f,-0.09,0.04),D.S.rg(f,-0.04,-0.05)],k=new D.xd(m,k,[1,1],[0,1]),p.G(k)):p.na(f);O&&p.Ma(O);q&&c.k(p);M=D.Cp.Ev(b,b.e,D$,K,G,M,D.o);D.Cp.N3(b,c,M,q,m);if(M=e.referenceLines)for(p=0;p<M.length;p++)f=M[p].color?M[p].color:"white",q=M[p].value,D$=e.indicatorSize,g?(window.referenceLineSize=((1-D$)/2+D$)*d.g,window.xCoord=d.x+(1-D$)/4*
d.g,window.yCoord=h.Wc(q),window.referenceLine=new D.hc(b.e,window.xCoord,window.yCoord,window.xCoord+window.referenceLineSize,window.yCoord)):(window.referenceLineSize=((1-D$)/2+D$)*d.j,window.xCoord=h.Wc(q),window.yCoord=d.y+(1-D$)/4*d.j,window.referenceLine=new D.hc(b.e,window.xCoord,window.yCoord,window.xCoord,window.yCoord+window.referenceLineSize)),q=new D.Ud(f,1,M[p].lineWidth?M[p].lineWidth:2),M[p].lineStyle&&q.ba((0,D.mi)(M[p].lineStyle)),window.referenceLine.Y(q),q=new D.lf(D.S.bx(0,0,0,
0.8),0.75,3,3,50,1,2,D.u,D.u,D.u),c.k(window.referenceLine),(0,D.bf)(window.referenceLine,q);d=new D.td(b.e,d.x,d.y,d.g,d.j);(0,D.vd)(d);c.k(d);((c=e.shortDesc)||e.readOnly===D.u)&&b.Sa().ma(d,new D.pc(D.r,c,f))};D.Cp.Ev=function(b,c,d,e,f,g,h){return new window.DvtStatusMeterGaugeIndicator(b,c,d,e,f,g,h)};D.Cp.N3=function(b,c,d,e,f){"none"!=b.Fa().visualEffects&&(0,D.gD)(b)&&(f=new D.xd(f,["#FFFFFF","#FFFFFF","#FFFFFF"],[0.5,0.3125,0],[0,0.3,1]),d.G(f),b.xA.push(d),d.la(D.u),e&&c.k(d))};
D.Cp.sja=function(b,c,d,e,f){var g=b.Fa();d.la(D.u);c.k(d);"none"!=g.visualEffects&&((0,D.gD)(b)?(b=[D.S.Ll(e,0.9),e,D.S.Qla(e)],f=new D.xd(f,b,[1,1,1],[0,0.04,0.73])):(b=[D.S.rg(e,-0.04,-0.05),D.S.rg(e,-0.09,0.04)],f=new D.xd(f,b,[1,1],[0,1])),d.G(f))};
D.Cp.Vr=function(b,c,d){var e=b.Fa(),f=D.J.S(b.e),g="vertical"==e.orientation,h=new D.nc(b.e,""),k=D.Fp.qz(e.value,b),m=e.__layout.labelGap;h.Ia(e.metricLabel.style);if(g&&"on"==e.metricLabel.rendered){var p=0<e.max?e.max:e.min,p=D.Fp.qz(p,b),p=new D.nc(b.e,p);p.Ia(e.metricLabel.style);var f=new D.I(d.x,d.y+0.8*d.j,d.g,0.2*d.j),g=(g=e.metricLabel.style.v("font-size"))?(0,window.parseInt)(g):p.Rw(f),q=p.Ub();d.j-=q.j;window.labelSpace=q.g;h.wf(g);h.pd(k);h.fa(d.x+d.g/2);h.ua(d.y+d.j);d.j-=m;h.rf();
D.oc.Vb(h,d.g,d.j,c)&&h.ef()&&b.Sa().ma(h,new D.pc(k))}else if(!g&&"on"==e.metricLabel.rendered){var g=(g=e.metricLabel.style.v("font-size"))?(0,window.parseInt)(g):13,q=window.Math.max(e.max.toString().length,e.min.toString().length),t="";"percent"==e.metricLabel.textType&&(q=3,t+="%");for(var v=0;v<q;v++)t+="0";h.pd(t);18>d.j&&(g=h.Rw(d));h.wf(g);if(0<e.max||"off"!=e.plotArea.rendered||!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay))p=0<e.max?e.max:e.min,p=D.Fp.qz(p,b),p=new D.nc(b.e,
p),p.Ia(e.metricLabel.style),p.wf(g),q=h.Ub(),p=f?d.x+q.g:d.x+d.g,window.labelSpace=q.g,f&&(d.x+=q.g+m),d.g-=q.g+m;if(0>e.min&&"on"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)){g=D.Fp.qz(e.min,b);g=new D.nc(b.e,g);g.Ia(e.metricLabel.style);g=g.Ub();if(0>e.value||0>=e.max)p=f?d.x+d.g:d.x+g.g,window.labelSpace=g.g;f||(d.x+=g.g+m);d.g-=g.g+m}h.pd(k);h.fa(p);h.ua(d.y+d.j/2);h.Fe();h.Fi();D.oc.Vb(h,window.labelSpace,d.j,c)&&h.ef()&&b.Sa().ma(h,new D.pc(k))}};
D.Cp.ot=function(b,c,d){return{x:window.Math.cos(d)*c+b.g/2+b.x,y:window.Math.sin(d)*c+b.j/2+b.y}};D.Cp.I0=function(b,c,d,e,f,g,h,k,m){var p=b.e;D.J.S(b.e)&&(e=window.Math.PI-e-f,e=0<e?e:e+2*window.Math.PI);d=new D.pD(p,d,e,f,g,h);b.xA.push(d);d.na(k);(b=D.hD.Ih(b))&&!m&&d.Ma(b);c.k(d)};
D.Cp.Nva=function(b,c,d,e,f,g){var h=window.angle,k=b.e,m=window.Math.min(d.g,d.j),p=0.275*m,m=0.5*m;D.J.S(b.e)&&(h=window.Math.PI-h,h=0<h?h:h+2*window.Math.PI);window.p1=D.Cp.ot(d,p,h);window.p2=D.Cp.ot(d,m,h);b=new D.hc(k,window.p1.x,window.p1.y,window.p2.x,window.p2.y);e=new D.Ud(e,1,f);g&&e.ba((0,D.mi)(g));b.Y(e);c.k(b)};
window.DvtStatusMeterGaugeIndicator=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.o(window.DvtStatusMeterGaugeIndicator,D.td,"DvtStatusMeterGaugeIndicator");window.DvtStatusMeterGaugeIndicator.Ssa=2.5;window.DvtStatusMeterGaugeIndicator.prototype.Init=function(b,c,d,e,f,g,h){window.DvtStatusMeterGaugeIndicator.q.Init.call(this,c);this.Yh=b;this.Sza=h;this.Dxa="vertical"==b.Fa().orientation;(0,D.fD)(this,d,e,f,g)};
D.fD=function(b,c,d,e,f){b.Vo=c;b.Wo=d;b.OAa=e;b.PAa=f;var g=window.Math.min(c,d),h=window.Math.min(e,f);c=window.Math.abs(c-d);e=window.Math.abs(f-e);(0,D.Jf)(b,g,h,c,e);b.Sza&&(g=(b.Dxa?c:e)*((0,D.gD)(b.Yh)?0.25:0.15),g>=window.DvtStatusMeterGaugeIndicator.Ssa&&(0,D.ud)(b,g,g))};window.DvtStatusMeterGaugeIndicator.prototype.Te=function(){return[this.Vo,this.Wo,this.OAa,this.PAa]};window.DvtStatusMeterGaugeIndicator.prototype.Qf=function(b){b&&4==b.length&&(0,D.fD)(this,b[0],b[1],b[2],b[3])};
D.pD=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.o(D.pD,D.Pa,"DvtStatusMeterGaugeCircularIndicator");D.pD.prototype.Init=function(b,c,d,e,f,g){D.pD.q.Init.call(this,b);(0,D.sD)(this,c,d,e,f,g)};
D.sD=function(b,c,d,e,f,g){var h,k,m;c&&c instanceof D.I?b.Pa=c:c=b.Pa;b.Qc=d;b.Zc=e;b.$h=f;b.Ah=g;e<2*window.Math.PI?(h=D.Cp.ot(c,g,d),k=D.Cp.ot(c,g,d+e),m=D.Cp.ot(c,f,d+e),c=D.Cp.ot(c,f,d),g=window.DvtPathUtils.moveTo(h.x,h.y)+window.DvtPathUtils.arcTo(g,g,e,1,k.x,k.y)+window.DvtPathUtils.lineTo(m.x,m.y)+window.DvtPathUtils.arcTo(f,f,e,0,c.x,c.y)+window.DvtPathUtils.closePath()):(h=D.Cp.ot(c,g,d),k=D.Cp.ot(c,g,d+e/2),m=D.Cp.ot(c,f,d),c=D.Cp.ot(c,f,d+e/2),g=window.DvtPathUtils.moveTo(h.x,h.y)+window.DvtPathUtils.arcTo(g,
g,e/2,1,k.x,k.y)+window.DvtPathUtils.arcTo(g,g,e/2,1,h.x,h.y),0<f&&(g+=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(f,f,e/2,0,m.x,m.y)+window.DvtPathUtils.arcTo(f,f,e/2,0,c.x,c.y)),g+=window.DvtPathUtils.closePath());b.ck(g)};D.pD.prototype.Te=function(){return[this.Pa,this.Qc,this.Zc,this.$h,this.Ah]};D.pD.prototype.Qf=function(b){b&&5==b.length&&(0,D.sD)(this,b[0],b[1],b[2],b[3],b[4])};
D.Hp=(0,D.z)();(0,D.ta)("DvtDialGauge",D.Hp);D.F.o(D.Hp,D.vp,"DvtDialGauge");D.Ip=function(b,c,d){var e=new D.Hp;e.Init(b,c,d);return e};D.Hp.newInstance=D.Ip;D.E=D.Hp.prototype;D.E.Init=function(b,c,d){D.Hp.q.Init.call(this,b,c,d);this.hf=new D.Jp;this.BZ=D.r};D.E.te=function(b){D.Hp.q.te.call(this,this.hf.sg(b))};D.E.ll=function(b,c,d){D.Kp.L(this,b,c,d)};
D.E.UW=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.Te(),h=D.Kp.uta(this);f.Sg(h);h=new D.Nj(this.e,f,d);(0,D.N)(h.T,"typeNumberArray",f,f.Te,f.Qf,g);h.T.Cj(function(b){return(0,D.Dj)(b,0.7)});c.push(h)}return new D.Nd(this.e,c)};
D.E.tx=function(b,c){var d=D.Xe.u8(window.Math.atan2(c-this.BZ.y,b-this.BZ.x));0>=d&&(d+=360);var e=D.J.S(this.e),f=this.Fa().background,g=e?180+f.startAngle:360-f.startAngle,f=f.angleExtent,h=g+f;if(e){h=g;for(g-=f;0>g;)g+=360,h+=360}d+360>=g&&d+360<=h?d+=360:d>=g&&d<=h||(d=d>h?g+360-d<d-h?g:h:g-d<d+360-h?g:h);d=(d-g)/f;e&&(d=1-d);e=this.W.min;return d*(this.W.max-e)+e};
D.Jp=function(){this.Init({skyros:D.lD,alta:{}})};D.F.o(D.Jp,D.iD,"DvtDialGaugeDefaults");D.lD={background:{startAngle:180,angleExtent:180,indicatorLength:0.7},metricLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},tickLabel:{scaling:"auto",style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};
D.Kp={};D.F.o(D.Kp,D.F,"DvtDialGaugeRenderer");D.Kp.L=function(b,c,d,e){D.Pp.wu(b)?(d=new D.I(0,0,d,e),D.Kp.PL(b,c,d),D.Kp.Vr(b,c,d)):D.Fp.Qz(b,c,new D.I(0,0,d,e))};
D.Kp.PL=function(b,c,d){var e=b.Fa(),f=D.Kp.c0(b,d);c.k(f);e.background.majorTickCount&&e.background.radius&&D.Kp.Kza(b,c,d);var g=D.Kp.mva(b,d),h=new D.H(b.e),k=new D.rD(b.e);c.k(h);h.k(k);k.k(g);var m=g.C(),p=D.Kp.Kfa(b,e.value),f=D.Kp.yfa(b,d),q=D.Kp.uwa(b,m);d=D.Kp.vwa(b,d,m);m=new D.ib;m.translate(-q.x,-q.y);m.scale(d,d);g.qa(m);k.Sg(p);m=new D.ib;m.translate(f.x,f.y);h.qa(m);b.xA.push(k);((e=e.shortDesc)||b.Fa().readOnly===D.u)&&b.Sa().ma(c,new D.pc(D.r,e));b.BZ=f};
D.Kp.c0=function(b,c){var d=b.Fa().background,e=D.J.S(b.e),f=D.J.da(),g=f?2*c.g:c.g,h=f?2*c.j:c.j,k=d.images;if(k&&0<k.length){var m,p,q,f=[];for(m=0;m<k.length;m++){var t="rtl"==k[m].dir;e&&t?f.push(k[m]):!e&&!t&&f.push(k[m])}k=0<f.length?f:k;for(m=0;m<k.length;m++){var v=k[m],t=v.src,f=v.width,v=v.height,w=t&&-1<t.search(".svg");0==m&&(p=f,q=v);if(w||f>=g&&v>=h||m==k.length-1){var g=new D.La(b.e,t,0,0,f,v),A=new D.ib,h=window.Math.min(c.g/f,c.j/v),k=(c.g-h*f)/2;m=(c.j-h*v)/2;A.scale(h,h);A.translate(k,
m);g.qa(A);w&&D.J.dp()&&(t=D.Pd.yj(b.e,t,D.F.oj(g,g.GZ)))&&g.GZ(t);c.x+=k;c.y+=m;c.g=h*f;c.j=h*v;!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=e?c.x+c.g-c.g*d.anchorX/p:c.x+c.g*d.anchorX/p,d._anchorY=c.y+c.j*d.anchorY/q);d.metricLabelBounds&&(f={},f.width=c.g*d.metricLabelBounds.width/p,f.height=c.j*d.metricLabelBounds.height/q,f.y=c.y+c.j*d.metricLabelBounds.y/q,f.x=e?c.x+c.g-c.g*d.metricLabelBounds.x/p-f.width:c.x+c.g*d.metricLabelBounds.x/p,d._metricLabelBounds=f);e=window.Math.min(c.g/
p,c.j/q);d._radius=d.radius*e;d._tickLabelHeight=d.tickLabelHeight*c.j/q;d._tickLabelWidth=d.tickLabelWidth*c.g/p;return g}}}return D.r};
D.Kp.mva=function(b,c){var d=b.Fa().indicator,e=D.Kp.Efa(b,c),f=D.J.da()?2*e:e,g,h,k=d.images;if(k&&0<k.length)for(var m=0;m<k.length;m++){var p=k[m],e=p.src,q=p.width,p=p.height,t=e&&-1<e.search(".svg");0==m&&(g=q,h=p);if(t||p>=f||m==k.length-1)return f=new D.La(b.e,e,0,0,q,p),t&&D.J.dp()&&D.Pd.yj(b.e,e,D.F.oj(f,f.GZ))&&(f.ia(q),f.va(p)),!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=d.anchorX*q/g,d._anchorY=d.anchorY*p/h),f}return D.r};
D.Kp.uta=function(b){var c=b.Fa().background;b=D.J.S(b.e)?180-c.startAngle:c.startAngle;return window.Math.PI*(90-b)/180};D.Kp.Kfa=function(b,c){var d=b.Fa(),e=d.background,f=d.min,d=d.max;c=window.Math.max(window.Math.min(c,d),f);f=(c-f)/(d-f);d=D.J.S(b.e);return window.Math.PI*(90-((d?180-e.startAngle:e.startAngle)-f*(d?-e.angleExtent:e.angleExtent)))/180};
D.Kp.yfa=function(b,c){var d=b.Fa().background,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.R(e,d):new D.R(c.x+c.g/2,c.y+c.j/2)};D.Kp.Efa=function(b,c){var d=window.Math.min(c.g,c.j)/2;return b.Fa().background.indicatorLength*d};D.Kp.uwa=function(b,c){var d=b.Fa().indicator,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.R(e,d):new D.R(c.x+c.g/2,c.y+c.j)};D.Kp.vwa=function(b,c,d){return D.Kp.Efa(b,c)/d.j};
D.Kp.Vr=function(b,c,d){var e=b.Fa();if("on"==e.metricLabel.rendered){var f=D.Fp.qz(e.value,b),g=d.x+d.g/2,h=d.y+d.j/2,k=d.g,m=d.j,p=e.background._metricLabelBounds;p&&(g=p.x+p.width/2,h=p.y+p.height/2,d.g=p.width,d.j=p.height);g=new D.nc(b.e,f,g,h);!e.metricLabel.style.v("color")&&e.background._isDark&&e.metricLabel.style.ba("color","#CCCCCC");g.Ia(e.metricLabel.style);h=(0,window.parseInt)(e.metricLabel.style.hH());if(!h){h=window.Math.max(D.Fp.qz(e.max,b).length,D.Fp.qz(e.min,b).length,f.length);
p="";"percent"==e.metricLabel.textType&&(h=window.Math.max(3,f.length),p+="%");for(e=0;e<h;e++)p+="0";g.pd(p);h=g.Rw(d);g.pd(f);g.wf(h)}g.rf();g.Fe();D.oc.Vb(g,k,m,c)&&g.ef()&&b.Sa().ma(g,new D.pc(f))}};
D.Kp.Kza=function(b,c,d){var e=b.Fa(),f=D.J.S(b.e);if(e.background.radius&&e.background.majorTickCount){var g=e.background._radius,h=e.min,k=e.max,m=e.background.majorTickCount,p=12,q=new D.I(D$,w,d.g,d.j),t=e.metricLabel.style.v("font-size");e.background._tickLabelHeight&&!t&&(q.j=e.background._tickLabelHeight);e.background._tickLabelWidth&&!t&&(q.g=e.background._tickLabelWidth);if(!t){var v=new D.nc(b.e,"",D$,w),p=window.Math.max(D.Fp.yU(e.max,b).length,D.Fp.yU(e.min,b).length),t="";"percent"==
e.tickLabel.textType&&(p=window.Math.max(3,D.Fp.yU(100,b).length-1),t+="%");for(D$=0;D$<p;D$++)t+="0";v.pd(t);p=v.Rw(q)}for(t=0;t<m;t++){D$=h+window.Math.abs(k-h)*t/(m-1);f&&(D$=h+window.Math.abs(k-h)*(m-1-t)/(m-1));var v=D.Fp.yU(D$,b),w=D.Kp.Kfa(b,D$),A=D.Kp.yfa(b,d),D$=A.x+g*window.Math.cos(w-window.Math.PI/2),w=A.y+g*window.Math.sin(w-window.Math.PI/2),v=new D.nc(b.e,v,D$,w);!e.tickLabel.style.v("color")&&e.background._isDark&&e.tickLabel.style.ba("color","#CCCCCC");v.Ia(e.tickLabel.style);e.tickLabel.style.v("font-size")||
v.wf(p);v.rf();v.Fe();D.oc.Vb(v,q.g,q.j,c)&&v.ef()&&b.Sa().ma(v,new D.pc(v.Uo))}}};
D.rD=function(b){this.Init(b)};D.F.o(D.rD,D.H,"DvtDialGaugeIndicator");D.rD.prototype.Sg=function(b){var c=new D.ib;c.rotate(b);this.qa(c);this.Rta=b};D.rD.prototype.Te=function(){return[this.Rta]};D.rD.prototype.Qf=function(b){b&&1==b.length&&this.Sg(b[0])};
D.Lp=(0,D.z)();(0,D.ta)("DvtRatingGauge",D.Lp);D.F.o(D.Lp,D.vp,"DvtRatingGauge");D.Mp=function(b,c,d){var e=new D.Lp;e.Init(b,c,d);return e};D.Lp.newInstance=D.Mp;D.Lp.prototype.Init=function(b,c,d){D.Lp.q.Init.call(this,b,c,d);this.hf=new D.Np};D.Lp.prototype.te=function(b){D.Lp.q.te.call(this,this.hf.sg(b))};
D.Lp.prototype.ll=function(b,c,d){var e=this.Fa().__layout.outerGap,f=this.W.max;this.Uj=window.Math.min(d-2*e,(c-2*e)/f);this.Pa=new D.I((this.ub-this.Uj*f)/2,e,this.Uj*f,this.Mb-2*e);D.Op.L(this,b,c,d)};D.Lp.prototype.tx=function(b){if(D.Pp.wu(this)){b=window.Math.max(window.Math.min(b,this.Pa.x+this.Pa.g),this.Pa.x);var c=0,c=D.J.S(this.e)?window.Math.max((this.Pa.x+this.Pa.g-b)/this.Uj,this.W.min):window.Math.max((b-this.Pa.x)/this.Uj,this.W.min);return D.Fp.Nka(this.W,c)}return D.r};
D.Rp=function(b){(0,D.Qp)(b,b.W.value,"render")};D.Lp.prototype.GP=function(b,c){(0,D.Qp)(this,this.tx(b,c),"hover")};D.Lp.prototype.oJ=function(b,c){var d=this.tx(b,c);(0,D.Qp)(this,d,"hover");this.ib(new D.to(this.W.value,d,D.u))};D.Lp.prototype.FP=function(b,c){var d=this.W.value;this.W.value=this.tx(b,c);this.W.changed=D.o;this.L();this.ib(new D.to(d,this.W.value,D.u));this.ib(new D.to(d,this.W.value,D.o))};
D.Qp=function(b,c,d,e){if(D.Pp.wu(b)){e||(e=b.ga);var f=D.J.S(b.e);c=window.Math.max(window.Math.min(c,b.W.max),0);var g=0,h=c*b.Uj,k=c*b.Uj;"render"==d&&(g=c*b.Uj,h=0);f?(c=e.ca(0),d=new D.Sg("unsel"+b.getId()),(0,D.Tg)(d,b.Pa.x,b.Pa.y,b.Pa.g-k,b.Pa.j),(0,D.sf)(c,d),c=e.ca(1),d=new D.Sg("sel"+b.getId()),(0,D.Tg)(d,b.Pa.x+b.Pa.g-k,b.Pa.y,g,b.Pa.j),(0,D.sf)(c,d),e=e.ca(2),g=new D.Sg("hover"+b.getId()),(0,D.Tg)(g,b.Pa.x+b.Pa.g-k,b.Pa.y,h,b.Pa.j)):(c=e.ca(0),d=new D.Sg("unsel"+b.getId()),(0,D.Tg)(d,
b.Pa.x+k,b.Pa.y,b.Pa.g-k,b.Pa.j),(0,D.sf)(c,d),c=e.ca(1),d=new D.Sg("sel"+b.getId()),(0,D.Tg)(d,b.Pa.x,b.Pa.y,g,b.Pa.j),(0,D.sf)(c,d),e=e.ca(2),g=new D.Sg("hover"+b.getId()),(0,D.Tg)(g,b.Pa.x,b.Pa.y,h,b.Pa.j));(0,D.sf)(e,g)}};D.Lp.prototype.N9=function(){return new D.Sp(this)};
D.Np=function(){this.Init({skyros:D.mD,alta:D.nD})};D.F.o(D.Np,D.iD,"DvtRatingGaugeDefaults");D.nD={unselectedState:{shape:"star",color:"#C4CED7",borderColor:D.r},selectedState:{shape:"star",color:"#F8C15A",borderColor:D.r},hoverState:{shape:"star",color:"#007CC8",borderColor:D.r},changedState:{shape:"star",color:"#ED2C02",borderColor:D.r}};
D.mD={min:0,max:5,unselectedState:{shape:"star",color:"#F2F2F2",borderColor:"#B6B6B6"},selectedState:{shape:"star",color:"#F8C15A",borderColor:"#F5A700"},hoverState:{shape:"star",color:"#66A7DA",borderColor:"#4A86C5"},changedState:{shape:"star",color:"#F8C15A",borderColor:"#959595"},step:1};
D.Op={};D.F.o(D.Op,D.F,"DvtRatingGaugeRenderer");D.Op.CP=["circle","diamond","rectangle","star"];
D.Op.L=function(b,c,d,e){if(D.Pp.wu(b)){var f=b.Fa(),g=f.__layout.outerGap,h=f.max,k=window.Math.min(e-2*g,(d-2*g)/h);d=new D.I((d-k*h)/2,g,k*h,e-2*g);e={value:0,type:f.unselectedState.shape,color:f.unselectedState.color,borderColor:f.unselectedState.borderColor,visualEffects:f.visualEffects};var g={value:0,type:f.selectedState.shape,color:f.selectedState.color,borderColor:f.selectedState.borderColor,visualEffects:f.visualEffects},m={value:0,type:f.changedState.shape,color:f.changedState.color,borderColor:f.changedState.borderColor,
visualEffects:f.visualEffects},p={value:0,type:f.hoverState.shape,color:f.hoverState.color,borderColor:f.hoverState.borderColor,visualEffects:f.visualEffects};"dot"==f.unselectedState.shape&&(e.type="circle",e.visualEffects="none",e.size=0.05);var q=new D.H(b.e);c.k(q);var t=new D.H(b.e);c.k(t);var v=new D.H(b.e);c.k(v);(0,D.Qp)(b,f.value,"render",c);for(var w=0;w<h;w++){if("none"!=f.unselectedState.shape){var A=(0,D.wp)(b.e,D.r,D.r,D.o);q.k(A);(0,D.Xa)(A,d.x+w*k,d.y+d.j/2-k/2);-1==D.Ib.Ea(D.Op.CP,
e.type)&&(e.type="star");A.L(e,k,k)}f.changed?(A=(0,D.wp)(b.e,D.r,D.r,D.o),t.k(A),(0,D.Xa)(A,d.x+w*k,d.y+d.j/2-k/2),-1==D.Ib.Ea(D.Op.CP,m.type)&&(m.type="star"),A.L(m,k,k)):(A=(0,D.wp)(b.e,D.r,D.r,D.o),t.k(A),(0,D.Xa)(A,d.x+w*k,d.y+d.j/2-k/2),-1==D.Ib.Ea(D.Op.CP,g.type)&&(g.type="star"),A.L(g,k,k));A=(0,D.wp)(b.e,D.r,D.r,D.o);v.k(A);(0,D.Xa)(A,d.x+w*k,d.y+d.j/2-k/2);-1==D.Ib.Ea(D.Op.CP,p.type)&&(p.type="star");A.L(p,k,k)}h=new D.td(b.e,d.x,d.y,d.g,d.j);(0,D.vd)(h);c.k(h);(c=f.shortDesc)&&b.Sa().ma(h,
new D.pc(D.r,c))}else D.Fp.Qz(b,c,new D.I(0,0,d,e))};
D.Sp=function(b){this.Init(b.e,b.ib,b);this.Yh=b;this.OJ=this.Tk=D.u;this.xga=D.J.Nd();this.z4=D.u};D.F.o(D.Sp,D.Gp,"DvtRatingGaugeEventManager");D.E=D.Sp.prototype;D.E.fo=function(b){if(this.Yh.Fa().readOnly===D.u&&!this.OJ){var c=(0,D.eD)(this,b.pageX,b.pageY),d=this.Yh;(0,D.Qp)(d,d.tx(c.x,c.y),"hover");this.Tk=D.o}D.Gp.q.fo.call(this,b)};
D.E.gk=function(b){if(this.Yh.Fa().readOnly===D.u){if(this.xga&&this.OJ&&this.z4){this.z4=D.u;return}(0,D.eD)(this,b.pageX,b.pageY);(0,D.Rp)(this.Yh);this.OJ=D.u}D.Gp.q.gk.call(this,b)};D.E.kl=function(b){this.OJ||(this.Yh.Fa().readOnly===D.u?(this.Tk=D.o,this.oc(),b=(0,D.eD)(this,b.pageX,b.pageY),this.Yh.GP(b.x,b.y)):D.Gp.q.kl.call(this,b))};
D.E.Ym=function(b){this.Tk&&(this.Yh.Fa().readOnly===D.u?(this.Tk=D.u,b=(0,D.eD)(this,b.pageX,b.pageY),this.Yh.FP(b.x,b.y),(0,D.Rp)(this.Yh),this.OJ=D.o,this.xga&&(this.z4=D.o)):D.Gp.q.Ym.call(this,b))};D.E.oaa=(0,D.ca)(D.o);
});