define(['./DvtToolkit', './DvtAxis'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.lp=(0,D.z)();(0,D.ta)("DvtGauge",D.lp);D.F.l(D.lp,D.Sb,"DvtGauge");D.lp.prototype.Init=function(b,c,d,e){D.lp.q.Init.call(this,b,c,d);this.bb=new D.tp;e||(this.xa=this.c9(),this.xa.$e(this),this.setId("gauge1000"+window.Math.floor(1E9*window.Math.random())),this.SA=new D.cd(b,0,0),(0,D.ed)(this.SA),this.k(this.SA));this.vA=D.u;this.xF=D.r};D.lp.prototype.Yd=function(b){this.X=b;D.K.Kh()||(this.X.animationOnDisplay="none",this.X.animationOnDataChange="none")};
D.lp.prototype.L=function(b,c,d){b?this.Yd(b):this.X||this.Yd(D.r);this.X.thresholds&&(this.X.thresholds=this.X.thresholds.sort(D.up));!(0,window.isNaN)(c)&&!(0,window.isNaN)(d)&&(this.ub=c,this.Ob=d);c=this.kA;this.kA=[];d=new D.H(this.e);this.Ha(d,0);this.Vm(d,this.ub,this.Ob);var e=b!=D.r,f=this.ub,g=this.Ob;this.qb&&this.qb.stop();b=D.u;var h=this.vA?"none":this.Da().animationOnDataChange,k=this.vA?"none":this.Da().animationOnDisplay,m=this.Da().animationDuration/1E3;if(k||h){f=new D.I(0,0,f,
g);g=this.e;if(!this.ga&&"none"!==k)this.qb=D.ab.VG(g,k,d,f,m),this.qb||(this.qb=this.tW(this.kA,k,m));else if(this.ga&&"none"!=h&&e)if(this.qb=D.ab.bz(g,h,this.ga,d,f,m))b=D.o;else{e=this.kA;h=[];for(k=0;k<c.length;k++){var f=e[k],p=c[k].Qe(),g=f.Qe();f.Lf(p);p=new D.Mj(this.e,f,m);(0,D.N)(p.S,"typeNumberArray",f,f.Qe,f.Lf,g);h.push(p)}this.qb=new D.Od(this.e,h)}b||this.removeChild(this.ga);this.qb&&(this.qb.play(),this.qb.zd(this.jL,this));b&&(this.Dk=this.ga);this.ga=d}this.SA&&(this.X.readOnly===
D.u&&D.K.da()?(this.SA.ia(this.ub),this.SA.va(this.Ob)):(this.SA.ia(0),this.SA.va(0)));(0,D.Ac)(d,"img");(0,D.xc)(d,"label",this.X.shortDesc)};D.lp.prototype.render=D.lp.prototype.L;D.E=D.lp.prototype;D.E.Vm=(0,D.z)();D.E.tW=(0,D.ca)(D.r);D.E.gx=(0,D.ca)(D.r);D.E.jL=function(){this.Dk&&(this.removeChild(this.Dk),this.Dk=D.r);this.qb=D.r};D.E.Bx=(0,D.C)("bb");D.E.Da=(0,D.C)("X");D.E.Va=(0,D.C)("xa");D.E.pP=function(b,c){this.vA=D.o;this.xF=this.X.value;this.bJ(b,c)};
D.E.bJ=function(b,c){this.X.value=D.vp.qja(this.X,this.gx(b,c));this.L();this.ib(new D.jo(this.xF,this.X.value,D.u))};D.E.oP=function(b,c){this.bJ(b,c);this.ib(new D.jo(this.xF,this.X.value,D.o));this.vA=D.u;this.xF=D.r};D.E.c9=function(){return new D.wp(this)};D.up=function(b,c){return b.max&&c.max?window.Math.abs(b.max)-window.Math.abs(c.max):b.max?-window.Infinity:window.Infinity};
D.tp=(0,D.z)();D.F.l(D.tp,D.dm,"DvtGaugeBundle");D.tp._defaults={EMPTY_TEXT:"No data to display"};D.tp.prototype.Fs=function(b){return D.tp._defaults[b]};D.tp.prototype.ax=(0,D.ca)("DvtGaugeBundle");
D.cD=(0,D.z)();D.F.l(D.cD,D.Mg,"DvtGaugeDefaults");D.dD={skin:"alta",color:"#393737",metricLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};D.eD={skin:"skyros",min:0,max:100,color:"#313842",borderColor:D.r,visualEffects:"auto",emptyText:D.r,animationOnDataChange:"none",animationOnDisplay:"none",animationDuration:500,readOnly:"true",metricLabel:{rendered:"off",scaling:"auto",style:new D.P,textType:"number"},__layout:{outerGap:1,labelGap:3}};
D.cD.prototype.Init=function(b){b={skyros:D.xa.zb(b.skyros,D.eD),alta:D.xa.zb(b.alta,D.dD)};D.cD.q.Init.call(this,b)};D.aD=function(b){return"skyros"==b.Da().skin};
D.Fp={};D.F.l(D.Fp,D.F,"DvtGaugeDataUtils");D.Fp.gu=function(b){b=b.Da();return!b||(0,window.isNaN)(b.value)||b.value===D.r?D.u:D.o};D.Fp.C6=function(b){var c=b.Da();b=c.value;c=c.thresholds;if(!c)return-1;for(var d=0;d<c.length;d++)if(b<=c[d].max)return d;return c.length-1};D.Fp.A6=function(b,c){var d=b.Da().thresholds;return d&&0<=c&&c<d.length?d[c]:D.r};D.Fp.AJa=function(b,c){var d=b.Da().referenceLines;return d&&0<=c&&c<d.length?d[c]:D.r};
D.wp=function(b){this.Init(b.e,b.ib,b);this.Uh=b;this.Ok=D.u};D.F.l(D.wp,D.Bc,"DvtGaugeEventManager");D.E=D.wp.prototype;D.E.bl=function(b){this.Uh.Da().readOnly===D.u?(this.Ok=D.o,this.oc(),b=(0,D.ZC)(this,b.pageX,b.pageY),this.Uh.pP(b.x,b.y)):D.wp.q.bl.call(this,b)};D.E.Tm=function(b){this.Ok?(this.Ok=D.u,b=(0,D.ZC)(this,b.pageX,b.pageY),this.Uh.oP(b.x,b.y)):D.wp.q.Tm.call(this,b)};
D.E.Sm=function(b){if(this.Ok){var c=(0,D.ZC)(this,b.pageX,b.pageY);this.Uh.bJ(c.x,c.y)}(this.B$()||!this.Ok)&&D.wp.q.Sm.call(this,b)};D.E.B$=(0,D.ca)(D.u);
D.E.JI=function(b){if(D.Ta.Rd===b.type&&this.Uh.Da().readOnly===D.u){this.Ok=D.o;var c=(0,D.ZC)(this,b.touches[0].pageX,b.touches[0].pageY);this.Uh.pP(c.x,c.y);b.preventDefault()}else D.Ta.qh===b.type&&this.Ok?(c=(0,D.ZC)(this,b.touches[0].pageX,b.touches[0].pageY),this.Uh.bJ(c.x,c.y),b.preventDefault()):D.Ta.$f===b.type&&this.Ok?(this.Ok=D.u,c=(0,D.ZC)(this,b.changedTouches[0].pageX,b.changedTouches[0].pageY),this.Uh.oP(c.x,c.y),b.preventDefault()):D.wp.q.JI.call(this,b)};
D.ZC=function(b,c,d){c=(0,D.og)(b.e,c,d);return b.Uh.Hb(c)};
D.bD={};D.F.l(D.bD,D.F,"DvtGaugeStyleUtils");D.bD.xba=["#ed6647","#fad55c","#68c182"];D.bD.lsa=["#D62800","#FFCF21","#84AE31"];D.bD.Nb=function(b){var c=b.Da(),d=D.Fp.C6(b),e=D.Fp.A6(b,d);return e&&(!(b instanceof D.pp)||b instanceof D.pp&&"onIndicator"==c.thresholdDisplay)?D.bD.OM(b,e,d):c.color};D.bD.Gh=function(b){var c=b.Da(),d=D.Fp.A6(b,D.Fp.C6(b));return d&&d.borderColor&&(!(b instanceof D.pp)||b instanceof D.pp&&"onIndicator"==c.thresholdDisplay)?d.borderColor:c.borderColor};
D.bD.mla=function(b){var c=b.Da(),d=D.Fp.C6(b),e=D.Fp.A6(b,d);return e&&(!(b instanceof D.pp)||b instanceof D.pp&&"onIndicator"!=c.thresholdDisplay)?D.bD.OM(b,e,d):c.plotArea.color};D.bD.OM=function(b,c,d){if(c.color)return c.color;if(d<D.bD.xba.length)return(0,D.aD)(b)?D.bD.lsa[d]:D.bD.xba[d]};
D.vp={};D.F.l(D.vp,D.F,"DvtGaugeRenderer");D.vp.QY=2;D.vp.gba=1;D.vp.Fz=function(b,c,d){var e=b.Da(),f=e.emptyText;f||(f=(0,D.Na)(b.Bx(),"EMPTY_TEXT",D.r));var g=d.g-2*D.vp.QY,h=d.j-2*D.vp.gba;d=new D.pc(b.e,f,d.x+d.g/2,d.y+d.j/2);e.metricLabel.style.v("font-size")||e.metricLabel.style.aa("font-size","13px");d.Ia(e.metricLabel.style);d.of();d.Ce();D.qc.Wb(d,g,h,c)&&d.bf()&&b.Va().ma(d,new D.rc(f))};
D.vp.ez=function(b,c){var d=c.Da(),e="percent"==d.metricLabel.textType;e&&(b=100*D.vp.TG(d,d.min,b));var f=D.r;"on"==d.metricLabel.rendered&&d.metricLabel.converter&&(f=d.metricLabel.converter);var g=D.r;"on"==d.metricLabel.rendered&&d.metricLabel.scaling&&(g=d.metricLabel.scaling);return D.vp.Wda(b,c,f,g,d.metricLabel.autoPrecision?d.metricLabel.autoPrecision:"on",e)};
D.vp.aU=function(b,c){var d=c.Da(),e="percent"==d.tickLabel.textType;e&&(b=100*D.vp.TG(d,d.min,b));var f=D.r;"on"==d.tickLabel.rendered&&d.tickLabel.converter&&(f=d.tickLabel.converter);var g=D.r;"on"==d.tickLabel.rendered&&d.tickLabel.scaling&&(g=d.tickLabel.scaling);return D.vp.Wda(b,c,f,g,d.tickLabel.autoPrecision?d.tickLabel.autoPrecision:"on",e)};
D.vp.Wda=function(b,c,d,e,f,g){var h=c.Da();c=b;c=h.min;var h=h.max,k=h-c,m=D.r;(0,window.isNaN)(k)||(m=k/(1E3>k?100:1E3));e=new D.LB(c,h,m,e,f);if(d&&d.getAsString)c=e.sq(b,d);else{if(d&&d.format)return e.sq(b,d);c=e.sq(b)}return g?(0,window.String)(c)+"%":c};D.vp.TG=function(b,c,d){b=(d-c)/(b.max-b.min);return b=window.Math.min(window.Math.max(0,b),1)};
D.vp.M7=function(b,c,d,e){var f=b.Da();if("on"==f.metricLabel.rendered){var g=D.vp.ez(f.value,b),h=d.g,k=d.j,m=new D.pc(b.e,g,d.x+d.g/2,d.y+d.j/2);m.Ia(f.metricLabel.style);var p=f.metricLabel.style.v("font-size");if(!f.metricLabel.style.v("font-size")){var p=window.Math.max(f.max.toString().length,f.min.toString().length,g.length),q="";"percent"==f.metricLabel.textType&&(p=window.Math.max(3,g.length),q+="%");for(f=0;f<p;f++)q+="0";m.od(q);p=m.Ew(d);m.od(g);m.tf(p)}m.Ce();m.of();e!=D.r&&m.na(e);D.qc.Wb(m,
h,k,c)&&m.bf()&&b.Va().ma(m,new D.rc(g))}};D.vp.qja=function(b,c){var d=(0,window.Number)(b.step);if(d&&0<d){var e=(c-b.min)/d;return 0.5<e?window.Math.max(window.Math.min(b.max,window.Math.ceil(e)*d+b.min),b.min):b.min}return c};
D.kp=(0,D.z)();(0,D.ta)("DvtLedGauge",D.kp);D.F.l(D.kp,D.lp,"DvtLedGauge");D.mp=function(b,c,d,e){var f=new D.kp;f.Init(b,c,d,e);return f};D.kp.newInstance=D.mp;D.kp.prototype.Init=function(b,c,d,e){D.kp.q.Init.call(this,b,c,d,e);this.ef=new D.np};D.kp.prototype.Yd=function(b){D.kp.q.Yd.call(this,this.ef.pg(b));"auto"==this.X.animationOnDisplay&&(this.X.animationOnDisplay="zoom");"auto"==this.X.animationOnDataChange&&(this.X.animationOnDataChange="alphaFade");this.X.readOnly=D.o};
D.kp.prototype.Vm=function(b,c,d){D.op.L(this,b,c,d)};
D.np=function(){this.Init({skyros:D.kD,alta:{}})};D.F.l(D.np,D.cD,"DvtLedGaugeDefaults");D.kD={type:"circle"};
D.op={};D.F.l(D.op,D.F,"DvtLedGaugeRenderer");D.op.mHa=1/6;D.op.jsa="M8,86.6Q0,86.6,3.46,78.6L46,6.93Q50,0,54,6.93L96.54,78.6Q100,86.6,92,86.6Z";D.op.esa="M0,86.6L50,0L100,86.6Z";D.op.ksa="M0,86.6L50,0L100,86.6Z";D.op.vba=[-13.05,-12.94,-50,-11.13,-21.06,11.9,-30.74,47.6,0.1,27.18,31.06,47.44,21.17,11.79,50,-11.39,13.05,-13.01,-0.06,-47.59];D.op.dsa=[-50,-11.22,-16.69,-17.94,0,-47.55,16.69,-17.94,50,-11.22,26.69,13.8,30.9,47.56,0,33.42,-30.9,47.56,-26.69,13.8];D.op.hsa="M50,95L71,95Q74.414,94.414,75,91L75,60L92,60Q98.5,59.1,95,54L52,12Q50,11,48,12L5,54Q1.5,59.1,8,60L25,60L25,91Q25.586,94.414,29,95Z";
D.op.csa="M75,98L75,58L97.5,58L50,11L2.5,58L25,58L25,98Z";D.op.isa="M75,98L75,58L97.5,58L50,11L2.5,58L25,58L25,98Z";
D.op.L=function(b,c,d,e){if(D.Fp.gu(b)){var f=b.Da(),g=f.__layout.outerGap,h=f&&(0<=f.size||1>f.size)?window.Math.sqrt(f.size):1;d=new D.I(g+(d-2*g)*(1-h)/2,g+(e-2*g)*(1-h)/2,(d-2*g)*h,(e-2*g)*h);D.op.BL(b,c,d);D.op.h3(b,c,d);"on"==f.metricLabel.rendered&&(f.metricLabel.style.v("color")!=D.r?D.vp.M7(b,c,D.op.kea(b,d)):(e=D.bD.Nb(b),e=D.S.Cl(e),f.metricLabel.style.aa("color",e),D.vp.M7(b,c,D.op.kea(b,d),e)))}else D.vp.Fz(b,c,new D.I(0,0,d,e))};
D.op.BL=function(b,c,d){var e=b.e,f=b.Da(),g=f.type,h=D.bD.Nb(b),k=D.bD.Gh(b),m=d.x+d.g/2,p=d.y+d.j/2,q=window.Math.min(d.g,d.j)/2,t=(0,D.aD)(b);"rectangle"==g?e=new D.cd(e,d.x,d.y,d.g,d.j):"diamond"==g?e=new D.vc(e,[m-q,p,m,p-q,m+q,p,m,p+q]):"triangle"==g?(m=t?D.op.jsa:D.op.esa,e=new D.Ra(e,m)):"star"==g?(m=t?D.op.vba:D.op.dsa,p=window.Math.min(d.g/100,d.j/100),m=D.Xf.scale(m,p,p),m=D.Xf.translate(m,d.x+d.g/2,d.y+d.j/2),e=new D.vc(e,m)):"arrow"==g?(m=t?D.op.hsa:D.op.csa,e=new D.Ra(e,m)):e=new D.Rd(e,
m,p,q);t||"none"==f.visualEffects?e.na(h):(t=[D.S.og(h,-0.09,0.04),D.S.og(h,-0.04,-0.05)],m=f&&0==f.rotation%90?f.rotation:0,e.G(new D.gd("arrow"==g||"star"==g||"triangle"==g?360-m:270,t,[1,1],[0,1])));k&&e.Ma(k);(f=f.shortDesc)&&b.Va().ma(e,new D.rc(D.r,f,h));e=D.op.ZS(b,c,e,d);c.k(e)};
D.op.ZS=function(b,c,d,e){var f=b.Da(),g=f.type;if("triangle"==g||"arrow"==g){var h=new D.H(b.e);b=new D.H(b.e);c.k(h);h.k(b);b.k(d);f=f&&0==f.rotation%90?f.rotation:0;f="star"==g?0:f;g=new D.jb;g.rotate(window.Math.PI*(90-f)/180);d.qa(g);g=b.C();g=window.Math.min(e.g/g.g,e.j/g.j);f=new D.jb;f.scale(g,g);b.qa(f);f=h.C();b=e.x+e.g/2-(f.x+f.g/2);e=e.y+e.j/2-(f.y+f.j/2);f=new D.jb;f.translate(b,e);h.qa(f);c.removeChild(h);if(c=d.nc())c=c.clone(),c.ia(c.getWidth()/g),d.Y(c);return h}return d};
D.op.h3=function(b,c,d){var e=b.Da(),f=e.type;"none"!=e.visualEffects&&(0,D.aD)(b)&&("rectangle"==f?D.op.Qya(b,c,d):"diamond"==f?D.op.Pya(b,c,d):"triangle"==f?D.op.Sya(b,c,d):"star"==f?D.op.Rya(b,c,d):"arrow"==f?D.op.Nya(b,c,d):D.op.Oya(b,c,d))};
D.op.Qya=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);b=new D.cd(b.e,d.x,d.y,d.g,d.j);b.la(D.u);c.k(b);c=new D.gd(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.G(c)};
D.op.Pya=function(b,c,d){var e=0.05*d.g,f=0.05*d.j,f=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);d=f.x+f.g/2;e=f.y+f.j/2;f=window.Math.min(f.g,f.j)/2;b=new D.vc(b.e,[d-f,e,d,e-f,d+f,e,d,e+f]);b.la(D.u);c.k(b);c=new D.gd(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.G(c)};
D.op.Sya=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);e=new D.Ra(b.e,D.op.ksa);f=b.Da();f=new D.gd(360-(f&&0==f.rotation%90?f.rotation:0),["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);e.G(f);e=D.op.ZS(b,c,e,d);e.la(D.u);c.k(e)};
D.op.Nya=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);e=new D.Ra(b.e,D.op.isa);f=b.Da();f=new D.gd(360-(f&&0==f.rotation%90?f.rotation:0),["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);e.G(f);e=D.op.ZS(b,c,e,d);e.la(D.u);c.k(e)};
D.op.Rya=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);var e=new D.Ra(b.e,D.op.vba),f=b.Da(),f=360-(f&&0==f.rotation%90?f.rotation:0),g=D.bD.Nb(b),g=[D.S.Dl(g,0.9),g,D.S.ska(g)],f=new D.gd(f,g,[1,1,1],[0.1,0.4,0.8]);e.G(f);e=D.op.ZS(b,c,e,d);e.la(D.u);c.k(e)};
D.op.Oya=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.I(d.x+e,d.y+f,d.g-2*e,d.j-2*f);var e=d.x+d.g/2,f=d.y+d.j/2,g=window.Math.min(d.g,d.j)/2,h=new D.Rd(b.e,e,f,g);h.la(D.u);c.k(h);var k=new D.cg(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.25,0.5],[0.15,0.7,0.95],e,f-0.6*g,1.5*g,[d.x,d.y,d.g,d.j]);h.G(k);h=0.6*g;g*=0.4;f-=0.3*g;b=new D.$e(b.e,e,f-g,h,g);b.la(D.u);c.k(b);c=new D.cg(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.2,0.5],[0.6,0.8,1],e,f,h,[d.x,d.y,d.g,d.j]);b.G(c)};
D.op.kea=function(b,c){var d=b.Da(),e=d.type,d=0==d.rotation%90?d.rotation:0,f=window.Math.min(c.g,c.j),g=c.x+c.g/2-f/2,h=c.y+c.j/2-f/2,k=f,m=f;"triangle"==e?0==d?(g+=0.05*f,h+=0.2*f,k-=0.3*f,m-=0.4*f):90==d?(g+=0.2*f,h+=0.25*f,k-=0.4*f,m-=0.3*f):180==d?(g+=0.25*f,h+=0.2*f,k-=0.3*f,m-=0.4*f):270==d&&(g+=0.2*f,h+=0.05*f,k-=0.4*f,m-=0.3*f):"arrow"==e?0==d?(g+=0.05*f,h+=0.2*f,k-=0.28*f,m-=0.4*f):90==d?(g+=0.2*f,h+=0.2*f,k-=0.4*f,m-=0.4*f):180==d?(g+=0.23*f,h+=0.2*f,k-=0.28*f,m-=0.4*f):270==d&&(g+=0.2*
f,h+=0.2*f,k-=0.4*f,m-=0.4*f):"star"==e?(g+=0.25*f,h+=0.25*f,k-=0.5*f,m-=0.4*f):"diamond"==e?(g+=0.15*f,h+=0.15*f,k-=0.3*f,m-=0.3*f):"rectangle"==e?(g+=0.1*f,h+=0.1*f,k-=0.2*f,m-=0.2*f):"circle"==e&&(g+=0.15*f,h+=0.15*f,k-=0.3*f,m-=0.3*f);return new D.I(g,h,k,m)};
D.pp=(0,D.z)();(0,D.ta)("DvtStatusMeterGauge",D.pp);D.F.l(D.pp,D.lp,"DvtStatusMeterGauge");D.qp=function(b,c,d){var e=new D.pp;e.Init(b,c,d);return e};D.pp.newInstance=D.qp;D.E=D.pp.prototype;D.E.Init=function(b,c,d){D.pp.q.Init.call(this,b,c,d);this.ef=new D.rp;this.bZ=D.r};D.E.Yd=function(b){D.pp.q.Yd.call(this,this.ef.pg(b))};D.E.Vm=function(b,c,d){D.sp.L(this,b,c,d)};
D.E.tW=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.Qe();"horizontal"==this.X.orientation||"vertical"==this.X.orientation?f.Lf([g[0],g[0],g[2],g[3]]):f.Lf([g[0],g[1],0,g[3],g[4]]);var h=new D.Mj(this.e,f,d);(0,D.N)(h.S,"typeNumberArray",f,f.Qe,f.Lf,g);h.S.xj(function(b){return(0,D.Cj)(b,0.7)});c.push(h)}return new D.Od(this.e,c)};
D.E.gx=function(b,c){if("horizontal"==this.X.orientation)return this.bZ.kC(b);if("vertical"==this.X.orientation)return this.bZ.kC(c);if("circular"==this.X.orientation){var d=D.Ye.J7(window.Math.atan2(c-this.Ob/2,b-this.ub/2))-270,d=(d+720)%360;0<=d&&360>=d||(d=360<d?360-d<d-360?0:360:0-d<d?0:360);if(D.K.R(this.e))for(d=360-d;0>d;)d+=360;var e=this.X.min;return d/360*(this.X.max-e)+e}};
D.rp=function(){this.Init({skyros:D.nD,alta:D.oD})};D.F.l(D.rp,D.cD,"DvtStatusMeterGaugeDefaults");D.oD={color:"#393737",metricLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},plotArea:{color:"#f5f6f7",borderColor:"#D6DFE6"}};D.nD={color:"#313842",indicatorSize:1,metricLabel:{style:new D.P("color: #333333;")},orientation:"horizontal",plotArea:{color:"#AAAAAA",borderColor:"#C6C6C6",rendered:"auto"},thresholdDisplay:"onIndicator"};
D.sp={};D.F.l(D.sp,D.F,"DvtStatusMeterGaugeRenderer");D.sp.L=function(b,c,d,e){if(D.Fp.gu(b)){var f=b.Da(),g=f.__layout.outerGap;d=new D.I(g,g,d-2*g,e-2*g);"horizontal"==f.orientation||"vertical"==f.orientation?(D.sp.Kr(b,c,d),D.sp.BL(b,c,d)):"circular"==f.orientation&&(f=window.Math.min(d.g,d.j),D.vp.M7(b,c,new D.I(d.x+d.g/2-0.325*f,d.y+d.j/2-0.25*f,0.65*f,0.5*f)),D.sp.wya(b,c,d))}else D.vp.Fz(b,c,new D.I(0,0,d,e))};
D.sp.wya=function(b,c,d){var e=b.Da(),f=0,g=e.value,h=e.thresholds,k=window.Math.min(d.g,d.j),m=0.3125*k,p=0.4625*k,q=1.5*window.Math.PI,f=2*f*window.Math.PI;if(h&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(var t=0;t<h.length;t++){var v=D.bD.OM(b,h[t],t),f=h[t].max?h[t].max:e.max,w=0==t?e.min:h[t-1].max,q=1.5*window.Math.PI+2*window.Math.PI*D.vp.TG(e,e.min,w),f=D.vp.TG(e,w,f),f=2*f*window.Math.PI;D.sp.g0(b,c,d,q,f,m,p,v,D.u)}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&
"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(v=D.bD.mla(b),q=1.5*window.Math.PI,f=2*window.Math.PI,D.sp.g0(b,c,d,q,f,m,p,v,D.o));if((h=e.indicatorSize)&&1!=h)k*=0.075*(1-h),m+=k,p-=k;q=1.5*window.Math.PI;f=D.vp.TG(e,e.min,g);f=2*f*window.Math.PI;D.sp.g0(b,c,d,q,f,m,p,D.bD.Nb(b),D.u);if(m=e.referenceLines)for(p=0;p<m.length;p++)k=m[p].color?m[p].color:"black",h=m[p].lineWidth?m[p].lineWidth:2,q=m[p].lineStyle,g=m[p].value,window.angle=1.5*window.Math.PI+2*D.vp.TG(e,e.min,g)*window.Math.PI,
D.sp.Xua(b,c,d,k,h,q);d=new D.cd(b.e,d.x,d.y,d.g,d.j);(0,D.ed)(d);c.k(d);((c=e.shortDesc)||b.Da().readOnly===D.u)&&b.Va().ma(d,new D.rc(D.r,c,D.bD.Nb(b)))};
D.sp.BL=function(b,c,d){var e=b.Da(),f=D.K.R(b.e),g="vertical"==e.orientation,h={layout:{}};h.layout.gapRatio=0;h.timeAxisType="disabled";h.position=g?"left":"bottom";h.min=e.min;h.max=e.max;h.dataMin=e.min;h.dataMax=e.max;h.tickLabel={rendered:"off"};h=(0,D.iD)(b.e,h,d);b.bZ=h;var k=0;0>e.max?k=e.max:0<e.min&&(k=e.min);var m=h.Tj(k);"off"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&(m=h.Vc(e.min));var p=h.Vc(e.value),p=g?window.Math.max(d.y,window.Math.min(d.y+
d.j,p)):window.Math.max(d.x,window.Math.min(d.x+d.g,p)),q=0,q=0>e.min&&0>e.value?h.Vc(e.min):h.Vc(e.max),t,v,w,A,D$,J,G,L=0;g?(t=d.x,v=d.x+d.g,A=m,w=window.Math.max(d.y,window.Math.min(d.y+d.j,q)),D$=d.x+(1-e.indicatorSize)/2*d.g+0.5,J=d.x+d.g*(1-(1-e.indicatorSize)/2)-0.5,L=m-0.5,G=p+0.5):(t=m,v=window.Math.max(d.x,window.Math.min(d.x+d.g,q)),w=d.y,A=d.y+d.j,D$=f?m-0.5:m+0.5,J=f?p+0.5:p-0.5,G=d.y+(1-e.indicatorSize)/2*d.j+0.5,L=d.y+d.j*(1-(1-e.indicatorSize)/2)-0.5);q=D.o;p==m&&(q=D.u);var O=D.bD.Gh(b),
T=e.plotArea.borderColor,Q=e.thresholds,m=g?0:270;if(Q&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(p=Q.length-1;0<=p;p--){var V=p,aa=D.sp.rv(b,b.e,t,v,w,A,D.o),oa=new D.Sg("pacp"+b.getId());if(V==Q.length-1)g?(0,D.Tg)(oa,0,0,d.g+2,A-w+2,0,0):f?(0,D.Tg)(oa,h.Vc(e.max),0,d.g+2,A-w+2,0,0):(0,D.Tg)(oa,0,0,d.g+2,A-w+2,0,0);else if(g){var qa=Q[Q.length-2-V].max==D.r?100:Q[Q.length-2-V].max;(0,D.Tg)(oa,0,h.Vc(e.max),v-t+2,1*Q[V].max/window.Math.abs(k-e.max)*d.j,0,0)}else f?(qa=Q[Q.length-
2-V].max==D.r?100:Q[Q.length-2-V].max,(0,D.Tg)(oa,0,0,1*(e.max-qa)/window.Math.abs(k-e.max)*d.g,A-w+2,0,0)):(0,D.Tg)(oa,0,0,1*Q[V].max/window.Math.abs(k-e.max)*d.g,A-w+2,0,0);(0,D.tf)(aa,oa);if(f||g)V=Q.length-1-p;aa.na(D.bD.OM(b,Q[V],V));aa.Ma(T);D.sp.Wha(b,c,aa,D.bD.OM(b,Q[V],V),m)}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(aa=g?D.sp.rv(b,b.e,t,v,h.Vc(e.max),h.Vc(e.min),D.o):D.sp.rv(b,b.e,h.Vc(e.min),h.Vc(e.max),
w,A,D.o),p=D.bD.mla(b),aa.na(p),aa.Ma(T),D.sp.Wha(b,c,aa,p,m));p=D.sp.rv(b,b.e,D$,J,G,L,D.o);b.kA.push(p);f=D.bD.Nb(b);!(0,D.aD)(b)&&"none"!=e.visualEffects?(k=[D.S.og(f,-0.09,0.04),D.S.og(f,-0.04,-0.05)],k=new D.gd(m,k,[1,1],[0,1]),p.G(k)):p.na(f);O&&p.Ma(O);q&&c.k(p);L=D.sp.rv(b,b.e,D$,J,G,L,D.o);D.sp.h3(b,c,L,q,m);if(L=e.referenceLines)for(p=0;p<L.length;p++)f=L[p].color?L[p].color:"white",q=L[p].value,D$=e.indicatorSize,g?(window.referenceLineSize=((1-D$)/2+D$)*d.g,window.xCoord=d.x+(1-D$)/4*
d.g,window.yCoord=h.Vc(q),window.referenceLine=new D.jc(b.e,window.xCoord,window.yCoord,window.xCoord+window.referenceLineSize,window.yCoord)):(window.referenceLineSize=((1-D$)/2+D$)*d.j,window.xCoord=h.Vc(q),window.yCoord=d.y+(1-D$)/4*d.j,window.referenceLine=new D.jc(b.e,window.xCoord,window.yCoord,window.xCoord,window.yCoord+window.referenceLineSize)),q=new D.Vd(f,1,L[p].lineWidth?L[p].lineWidth:2),L[p].lineStyle&&q.aa((0,D.ii)(L[p].lineStyle)),window.referenceLine.Y(q),q=new D.mf(D.S.Pw(0,0,0,
0.8),0.75,3,3,50,1,2,D.u,D.u,D.u),c.k(window.referenceLine),(0,D.cf)(window.referenceLine,q);d=new D.cd(b.e,d.x,d.y,d.g,d.j);(0,D.ed)(d);c.k(d);((c=e.shortDesc)||e.readOnly===D.u)&&b.Va().ma(d,new D.rc(D.r,c,f))};D.sp.rv=function(b,c,d,e,f,g,h){return new window.DvtStatusMeterGaugeIndicator(b,c,d,e,f,g,h)};D.sp.h3=function(b,c,d,e,f){"none"!=b.Da().visualEffects&&(0,D.aD)(b)&&(f=new D.gd(f,["#FFFFFF","#FFFFFF","#FFFFFF"],[0.5,0.3125,0],[0,0.3,1]),d.G(f),b.kA.push(d),d.la(D.u),e&&c.k(d))};
D.sp.Wha=function(b,c,d,e,f){var g=b.Da();d.la(D.u);c.k(d);"none"!=g.visualEffects&&((0,D.aD)(b)?(b=[D.S.Dl(e,0.9),e,D.S.ska(e)],f=new D.gd(f,b,[1,1,1],[0,0.04,0.73])):(b=[D.S.og(e,-0.04,-0.05),D.S.og(e,-0.09,0.04)],f=new D.gd(f,b,[1,1],[0,1])),d.G(f))};
D.sp.Kr=function(b,c,d){var e=b.Da(),f=D.K.R(b.e),g="vertical"==e.orientation,h=new D.pc(b.e,""),k=D.vp.ez(e.value,b),m=e.__layout.labelGap;h.Ia(e.metricLabel.style);if(g&&"on"==e.metricLabel.rendered){var p=0<e.max?e.max:e.min,p=D.vp.ez(p,b),p=new D.pc(b.e,p);p.Ia(e.metricLabel.style);var f=new D.I(d.x,d.y+0.8*d.j,d.g,0.2*d.j),g=(g=e.metricLabel.style.v("font-size"))?(0,window.parseInt)(g):p.Ew(f),q=p.Vb();d.j-=q.j;window.labelSpace=q.g;h.tf(g);h.od(k);h.fa(d.x+d.g/2);h.ua(d.y+d.j);d.j-=m;h.of();
D.qc.Wb(h,d.g,d.j,c)&&h.bf()&&b.Va().ma(h,new D.rc(k))}else if(!g&&"on"==e.metricLabel.rendered){var g=(g=e.metricLabel.style.v("font-size"))?(0,window.parseInt)(g):13,q=window.Math.max(e.max.toString().length,e.min.toString().length),t="";"percent"==e.metricLabel.textType&&(q=3,t+="%");for(var v=0;v<q;v++)t+="0";h.od(t);18>d.j&&(g=h.Ew(d));h.tf(g);if(0<e.max||"off"!=e.plotArea.rendered||!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay))p=0<e.max?e.max:e.min,p=D.vp.ez(p,b),p=new D.pc(b.e,
p),p.Ia(e.metricLabel.style),p.tf(g),q=h.Vb(),p=f?d.x+q.g:d.x+d.g,window.labelSpace=q.g,f&&(d.x+=q.g+m),d.g-=q.g+m;if(0>e.min&&"on"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)){g=D.vp.ez(e.min,b);g=new D.pc(b.e,g);g.Ia(e.metricLabel.style);g=g.Vb();if(0>e.value||0>=e.max)p=f?d.x+d.g:d.x+g.g,window.labelSpace=g.g;f||(d.x+=g.g+m);d.g-=g.g+m}h.od(k);h.fa(p);h.ua(d.y+d.j/2);h.Ce();h.Bi();D.qc.Wb(h,window.labelSpace,d.j,c)&&h.bf()&&b.Va().ma(h,new D.rc(k))}};
D.sp.at=function(b,c,d){return{x:window.Math.cos(d)*c+b.g/2+b.x,y:window.Math.sin(d)*c+b.j/2+b.y}};D.sp.g0=function(b,c,d,e,f,g,h,k,m){var p=b.e;D.K.R(b.e)&&(e=window.Math.PI-e-f,e=0<e?e:e+2*window.Math.PI);d=new D.jD(p,d,e,f,g,h);b.kA.push(d);d.na(k);(b=D.bD.Gh(b))&&!m&&d.Ma(b);c.k(d)};
D.sp.Xua=function(b,c,d,e,f,g){var h=window.angle,k=b.e,m=window.Math.min(d.g,d.j),p=0.275*m,m=0.5*m;D.K.R(b.e)&&(h=window.Math.PI-h,h=0<h?h:h+2*window.Math.PI);window.p1=D.sp.at(d,p,h);window.p2=D.sp.at(d,m,h);b=new D.jc(k,window.p1.x,window.p1.y,window.p2.x,window.p2.y);e=new D.Vd(e,1,f);g&&e.aa((0,D.ii)(g));b.Y(e);c.k(b)};
window.DvtStatusMeterGaugeIndicator=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.l(window.DvtStatusMeterGaugeIndicator,D.cd,"DvtStatusMeterGaugeIndicator");window.DvtStatusMeterGaugeIndicator.Gra=2.5;window.DvtStatusMeterGaugeIndicator.prototype.Init=function(b,c,d,e,f,g,h){window.DvtStatusMeterGaugeIndicator.q.Init.call(this,c);this.Uh=b;this.bza=h;this.Nwa="vertical"==b.Da().orientation;(0,D.$C)(this,d,e,f,g)};
D.$C=function(b,c,d,e,f){b.Qo=c;b.Ro=d;b.Xza=e;b.Yza=f;var g=window.Math.min(c,d),h=window.Math.min(e,f);c=window.Math.abs(c-d);e=window.Math.abs(f-e);(0,D.Pf)(b,g,h,c,e);b.bza&&(g=(b.Nwa?c:e)*((0,D.aD)(b.Uh)?0.25:0.15),g>=window.DvtStatusMeterGaugeIndicator.Gra&&(0,D.dd)(b,g,g))};window.DvtStatusMeterGaugeIndicator.prototype.Qe=function(){return[this.Qo,this.Ro,this.Xza,this.Yza]};window.DvtStatusMeterGaugeIndicator.prototype.Lf=function(b){b&&4==b.length&&(0,D.$C)(this,b[0],b[1],b[2],b[3])};
D.jD=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.l(D.jD,D.Ra,"DvtStatusMeterGaugeCircularIndicator");D.jD.prototype.Init=function(b,c,d,e,f,g){D.jD.q.Init.call(this,b);(0,D.mD)(this,c,d,e,f,g)};
D.mD=function(b,c,d,e,f,g){var h,k,m;c&&c instanceof D.I?b.Qa=c:c=b.Qa;b.Nc=d;b.Xc=e;b.Xh=f;b.yh=g;e<2*window.Math.PI?(h=D.sp.at(c,g,d),k=D.sp.at(c,g,d+e),m=D.sp.at(c,f,d+e),c=D.sp.at(c,f,d),g=window.DvtPathUtils.moveTo(h.x,h.y)+window.DvtPathUtils.arcTo(g,g,e,1,k.x,k.y)+window.DvtPathUtils.lineTo(m.x,m.y)+window.DvtPathUtils.arcTo(f,f,e,0,c.x,c.y)+window.DvtPathUtils.closePath()):(h=D.sp.at(c,g,d),k=D.sp.at(c,g,d+e/2),m=D.sp.at(c,f,d),c=D.sp.at(c,f,d+e/2),g=window.DvtPathUtils.moveTo(h.x,h.y)+window.DvtPathUtils.arcTo(g,
g,e/2,1,k.x,k.y)+window.DvtPathUtils.arcTo(g,g,e/2,1,h.x,h.y),0<f&&(g+=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(f,f,e/2,0,m.x,m.y)+window.DvtPathUtils.arcTo(f,f,e/2,0,c.x,c.y)),g+=window.DvtPathUtils.closePath());b.Zj(g)};D.jD.prototype.Qe=function(){return[this.Qa,this.Nc,this.Xc,this.Xh,this.yh]};D.jD.prototype.Lf=function(b){b&&5==b.length&&(0,D.mD)(this,b[0],b[1],b[2],b[3],b[4])};
D.xp=(0,D.z)();(0,D.ta)("DvtDialGauge",D.xp);D.F.l(D.xp,D.lp,"DvtDialGauge");D.yp=function(b,c,d){var e=new D.xp;e.Init(b,c,d);return e};D.xp.newInstance=D.yp;D.E=D.xp.prototype;D.E.Init=function(b,c,d){D.xp.q.Init.call(this,b,c,d);this.ef=new D.zp;this.aZ=D.r};D.E.Yd=function(b){D.xp.q.Yd.call(this,this.ef.pg(b))};D.E.Vm=function(b,c,d){D.Ap.L(this,b,c,d)};
D.E.tW=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.Qe(),h=D.Ap.Esa(this);f.Og(h);h=new D.Mj(this.e,f,d);(0,D.N)(h.S,"typeNumberArray",f,f.Qe,f.Lf,g);h.S.xj(function(b){return(0,D.Cj)(b,0.7)});c.push(h)}return new D.Od(this.e,c)};
D.E.gx=function(b,c){var d=D.Ye.J7(window.Math.atan2(c-this.aZ.y,b-this.aZ.x));0>=d&&(d+=360);var e=D.K.R(this.e),f=this.Da().background,g=e?180+f.startAngle:360-f.startAngle,f=f.angleExtent,h=g+f;if(e){h=g;for(g-=f;0>g;)g+=360,h+=360}d+360>=g&&d+360<=h?d+=360:d>=g&&d<=h||(d=d>h?g+360-d<d-h?g:h:g-d<d+360-h?g:h);d=(d-g)/f;e&&(d=1-d);e=this.X.min;return d*(this.X.max-e)+e};
D.zp=function(){this.Init({skyros:D.fD,alta:{}})};D.F.l(D.zp,D.cD,"DvtDialGaugeDefaults");D.fD={background:{startAngle:180,angleExtent:180,indicatorLength:0.7},metricLabel:{style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},tickLabel:{scaling:"auto",style:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};
D.Ap={};D.F.l(D.Ap,D.F,"DvtDialGaugeRenderer");D.Ap.L=function(b,c,d,e){D.Fp.gu(b)?(d=new D.I(0,0,d,e),D.Ap.BL(b,c,d),D.Ap.Kr(b,c,d)):D.vp.Fz(b,c,new D.I(0,0,d,e))};
D.Ap.BL=function(b,c,d){var e=b.Da(),f=D.Ap.z_(b,d);c.k(f);e.background.majorTickCount&&e.background.radius&&D.Ap.Uya(b,c,d);var g=D.Ap.wua(b,d),h=new D.H(b.e),k=new D.lD(b.e);c.k(h);h.k(k);k.k(g);var m=g.C(),p=D.Ap.oea(b,e.value),f=D.Ap.cea(b,d),q=D.Ap.Eva(b,m);d=D.Ap.Fva(b,d,m);m=new D.jb;m.translate(-q.x,-q.y);m.scale(d,d);g.qa(m);k.Og(p);m=new D.jb;m.translate(f.x,f.y);h.qa(m);b.kA.push(k);((e=e.shortDesc)||b.Da().readOnly===D.u)&&b.Va().ma(c,new D.rc(D.r,e));b.aZ=f};
D.Ap.z_=function(b,c){var d=b.Da().background,e=D.K.R(b.e),f=D.K.da(),g=f?2*c.g:c.g,h=f?2*c.j:c.j,k=d.images;if(k&&0<k.length){var m,p,q,f=[];for(m=0;m<k.length;m++){var t="rtl"==k[m].dir;e&&t?f.push(k[m]):!e&&!t&&f.push(k[m])}k=0<f.length?f:k;for(m=0;m<k.length;m++){var v=k[m],t=v.src,f=v.width,v=v.height,w=t&&-1<t.search(".svg");0==m&&(p=f,q=v);if(w||f>=g&&v>=h||m==k.length-1){var g=new D.Ma(b.e,t,0,0,f,v),A=new D.jb,h=window.Math.min(c.g/f,c.j/v),k=(c.g-h*f)/2;m=(c.j-h*v)/2;A.scale(h,h);A.translate(k,
m);g.qa(A);w&&D.K.Zo()&&(t=D.Qd.tj(b.e,t,D.F.jj(g,g.fZ)))&&g.fZ(t);c.x+=k;c.y+=m;c.g=h*f;c.j=h*v;!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=e?c.x+c.g-c.g*d.anchorX/p:c.x+c.g*d.anchorX/p,d._anchorY=c.y+c.j*d.anchorY/q);d.metricLabelBounds&&(f={},f.width=c.g*d.metricLabelBounds.width/p,f.height=c.j*d.metricLabelBounds.height/q,f.y=c.y+c.j*d.metricLabelBounds.y/q,f.x=e?c.x+c.g-c.g*d.metricLabelBounds.x/p-f.width:c.x+c.g*d.metricLabelBounds.x/p,d._metricLabelBounds=f);e=window.Math.min(c.g/
p,c.j/q);d._radius=d.radius*e;d._tickLabelHeight=d.tickLabelHeight*c.j/q;d._tickLabelWidth=d.tickLabelWidth*c.g/p;return g}}}return D.r};
D.Ap.wua=function(b,c){var d=b.Da().indicator,e=D.Ap.iea(b,c),f=D.K.da()?2*e:e,g,h,k=d.images;if(k&&0<k.length)for(var m=0;m<k.length;m++){var p=k[m],e=p.src,q=p.width,p=p.height,t=e&&-1<e.search(".svg");0==m&&(g=q,h=p);if(t||p>=f||m==k.length-1)return f=new D.Ma(b.e,e,0,0,q,p),t&&D.K.Zo()&&D.Qd.tj(b.e,e,D.F.jj(f,f.fZ))&&(f.ia(q),f.va(p)),!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=d.anchorX*q/g,d._anchorY=d.anchorY*p/h),f}return D.r};
D.Ap.Esa=function(b){var c=b.Da().background;b=D.K.R(b.e)?180-c.startAngle:c.startAngle;return window.Math.PI*(90-b)/180};D.Ap.oea=function(b,c){var d=b.Da(),e=d.background,f=d.min,d=d.max;c=window.Math.max(window.Math.min(c,d),f);f=(c-f)/(d-f);d=D.K.R(b.e);return window.Math.PI*(90-((d?180-e.startAngle:e.startAngle)-f*(d?-e.angleExtent:e.angleExtent)))/180};
D.Ap.cea=function(b,c){var d=b.Da().background,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.R(e,d):new D.R(c.x+c.g/2,c.y+c.j/2)};D.Ap.iea=function(b,c){var d=window.Math.min(c.g,c.j)/2;return b.Da().background.indicatorLength*d};D.Ap.Eva=function(b,c){var d=b.Da().indicator,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.R(e,d):new D.R(c.x+c.g/2,c.y+c.j)};D.Ap.Fva=function(b,c,d){return D.Ap.iea(b,c)/d.j};
D.Ap.Kr=function(b,c,d){var e=b.Da();if("on"==e.metricLabel.rendered){var f=D.vp.ez(e.value,b),g=d.x+d.g/2,h=d.y+d.j/2,k=d.g,m=d.j,p=e.background._metricLabelBounds;p&&(g=p.x+p.width/2,h=p.y+p.height/2,d.g=p.width,d.j=p.height);g=new D.pc(b.e,f,g,h);!e.metricLabel.style.v("color")&&e.background._isDark&&e.metricLabel.style.aa("color","#CCCCCC");g.Ia(e.metricLabel.style);h=(0,window.parseInt)(e.metricLabel.style.UG());if(!h){h=window.Math.max(D.vp.ez(e.max,b).length,D.vp.ez(e.min,b).length,f.length);
p="";"percent"==e.metricLabel.textType&&(h=window.Math.max(3,f.length),p+="%");for(e=0;e<h;e++)p+="0";g.od(p);h=g.Ew(d);g.od(f);g.tf(h)}g.of();g.Ce();D.qc.Wb(g,k,m,c)&&g.bf()&&b.Va().ma(g,new D.rc(f))}};
D.Ap.Uya=function(b,c,d){var e=b.Da(),f=D.K.R(b.e);if(e.background.radius&&e.background.majorTickCount){var g=e.background._radius,h=e.min,k=e.max,m=e.background.majorTickCount,p=12,q=new D.I(D$,w,d.g,d.j),t=e.metricLabel.style.v("font-size");e.background._tickLabelHeight&&!t&&(q.j=e.background._tickLabelHeight);e.background._tickLabelWidth&&!t&&(q.g=e.background._tickLabelWidth);if(!t){var v=new D.pc(b.e,"",D$,w),p=window.Math.max(D.vp.aU(e.max,b).length,D.vp.aU(e.min,b).length),t="";"percent"==
e.tickLabel.textType&&(p=window.Math.max(3,D.vp.aU(100,b).length-1),t+="%");for(D$=0;D$<p;D$++)t+="0";v.od(t);p=v.Ew(q)}for(t=0;t<m;t++){D$=h+window.Math.abs(k-h)*t/(m-1);f&&(D$=h+window.Math.abs(k-h)*(m-1-t)/(m-1));var v=D.vp.aU(D$,b),w=D.Ap.oea(b,D$),A=D.Ap.cea(b,d),D$=A.x+g*window.Math.cos(w-window.Math.PI/2),w=A.y+g*window.Math.sin(w-window.Math.PI/2),v=new D.pc(b.e,v,D$,w);!e.tickLabel.style.v("color")&&e.background._isDark&&e.tickLabel.style.aa("color","#CCCCCC");v.Ia(e.tickLabel.style);e.tickLabel.style.v("font-size")||
v.tf(p);v.of();v.Ce();D.qc.Wb(v,q.g,q.j,c)&&v.bf()&&b.Va().ma(v,new D.rc(v.Po))}}};
D.lD=function(b){this.Init(b)};D.F.l(D.lD,D.H,"DvtDialGaugeIndicator");D.lD.prototype.Og=function(b){var c=new D.jb;c.rotate(b);this.qa(c);this.ata=b};D.lD.prototype.Qe=function(){return[this.ata]};D.lD.prototype.Lf=function(b){b&&1==b.length&&this.Og(b[0])};
D.Bp=(0,D.z)();(0,D.ta)("DvtRatingGauge",D.Bp);D.F.l(D.Bp,D.lp,"DvtRatingGauge");D.Cp=function(b,c,d){var e=new D.Bp;e.Init(b,c,d);return e};D.Bp.newInstance=D.Cp;D.Bp.prototype.Init=function(b,c,d){D.Bp.q.Init.call(this,b,c,d);this.ef=new D.Dp};D.Bp.prototype.Yd=function(b){D.Bp.q.Yd.call(this,this.ef.pg(b))};
D.Bp.prototype.Vm=function(b,c,d){var e=this.Da().__layout.outerGap,f=this.X.max;this.Qj=window.Math.min(d-2*e,(c-2*e)/f);this.Qa=new D.I((this.ub-this.Qj*f)/2,e,this.Qj*f,this.Ob-2*e);D.Ep.L(this,b,c,d)};D.Bp.prototype.gx=function(b){if(D.Fp.gu(this)){b=window.Math.max(window.Math.min(b,this.Qa.x+this.Qa.g),this.Qa.x);var c=0,c=D.K.R(this.e)?window.Math.max((this.Qa.x+this.Qa.g-b)/this.Qj,this.X.min):window.Math.max((b-this.Qa.x)/this.Qj,this.X.min);return D.vp.qja(this.X,c)}return D.r};
D.Hp=function(b){(0,D.Gp)(b,b.X.value,"render")};D.Bp.prototype.pP=function(b,c){(0,D.Gp)(this,this.gx(b,c),"hover")};D.Bp.prototype.bJ=function(b,c){var d=this.gx(b,c);(0,D.Gp)(this,d,"hover");this.ib(new D.jo(this.X.value,d,D.u))};D.Bp.prototype.oP=function(b,c){var d=this.X.value;this.X.value=this.gx(b,c);this.X.changed=D.o;this.L();this.ib(new D.jo(d,this.X.value,D.u));this.ib(new D.jo(d,this.X.value,D.o))};
D.Gp=function(b,c,d,e){if(D.Fp.gu(b)){e||(e=b.ga);var f=D.K.R(b.e);c=window.Math.max(window.Math.min(c,b.X.max),0);var g=0,h=c*b.Qj,k=c*b.Qj;"render"==d&&(g=c*b.Qj,h=0);f?(c=e.ca(0),d=new D.Sg("unsel"+b.getId()),(0,D.Tg)(d,b.Qa.x,b.Qa.y,b.Qa.g-k,b.Qa.j),(0,D.tf)(c,d),c=e.ca(1),d=new D.Sg("sel"+b.getId()),(0,D.Tg)(d,b.Qa.x+b.Qa.g-k,b.Qa.y,g,b.Qa.j),(0,D.tf)(c,d),e=e.ca(2),g=new D.Sg("hover"+b.getId()),(0,D.Tg)(g,b.Qa.x+b.Qa.g-k,b.Qa.y,h,b.Qa.j)):(c=e.ca(0),d=new D.Sg("unsel"+b.getId()),(0,D.Tg)(d,
b.Qa.x+k,b.Qa.y,b.Qa.g-k,b.Qa.j),(0,D.tf)(c,d),c=e.ca(1),d=new D.Sg("sel"+b.getId()),(0,D.Tg)(d,b.Qa.x,b.Qa.y,g,b.Qa.j),(0,D.tf)(c,d),e=e.ca(2),g=new D.Sg("hover"+b.getId()),(0,D.Tg)(g,b.Qa.x,b.Qa.y,h,b.Qa.j));(0,D.tf)(e,g)}};D.Bp.prototype.c9=function(){return new D.Ip(this)};
D.Dp=function(){this.Init({skyros:D.gD,alta:D.hD})};D.F.l(D.Dp,D.cD,"DvtRatingGaugeDefaults");D.hD={unselectedState:{shape:"star",color:"#C4CED7",borderColor:D.r},selectedState:{shape:"star",color:"#F8C15A",borderColor:D.r},hoverState:{shape:"star",color:"#007CC8",borderColor:D.r},changedState:{shape:"star",color:"#ED2C02",borderColor:D.r}};
D.gD={min:0,max:5,unselectedState:{shape:"star",color:"#F2F2F2",borderColor:"#B6B6B6"},selectedState:{shape:"star",color:"#F8C15A",borderColor:"#F5A700"},hoverState:{shape:"star",color:"#66A7DA",borderColor:"#4A86C5"},changedState:{shape:"star",color:"#F8C15A",borderColor:"#959595"},step:1};
D.Ep={};D.F.l(D.Ep,D.F,"DvtRatingGaugeRenderer");D.Ep.lP=["circle","diamond","rectangle","star"];
D.Ep.L=function(b,c,d,e){if(D.Fp.gu(b)){var f=b.Da(),g=f.__layout.outerGap,h=f.max,k=window.Math.min(e-2*g,(d-2*g)/h);d=new D.I((d-k*h)/2,g,k*h,e-2*g);e={value:0,type:f.unselectedState.shape,color:f.unselectedState.color,borderColor:f.unselectedState.borderColor,visualEffects:f.visualEffects};var g={value:0,type:f.selectedState.shape,color:f.selectedState.color,borderColor:f.selectedState.borderColor,visualEffects:f.visualEffects},m={value:0,type:f.changedState.shape,color:f.changedState.color,borderColor:f.changedState.borderColor,
visualEffects:f.visualEffects},p={value:0,type:f.hoverState.shape,color:f.hoverState.color,borderColor:f.hoverState.borderColor,visualEffects:f.visualEffects};"dot"==f.unselectedState.shape&&(e.type="circle",e.visualEffects="none",e.size=0.05);var q=new D.H(b.e);c.k(q);var t=new D.H(b.e);c.k(t);var v=new D.H(b.e);c.k(v);(0,D.Gp)(b,f.value,"render",c);for(var w=0;w<h;w++){if("none"!=f.unselectedState.shape){var A=(0,D.mp)(b.e,D.r,D.r,D.o);q.k(A);(0,D.Ya)(A,d.x+w*k,d.y+d.j/2-k/2);-1==D.Jb.Fa(D.Ep.lP,
e.type)&&(e.type="star");A.L(e,k,k)}f.changed?(A=(0,D.mp)(b.e,D.r,D.r,D.o),t.k(A),(0,D.Ya)(A,d.x+w*k,d.y+d.j/2-k/2),-1==D.Jb.Fa(D.Ep.lP,m.type)&&(m.type="star"),A.L(m,k,k)):(A=(0,D.mp)(b.e,D.r,D.r,D.o),t.k(A),(0,D.Ya)(A,d.x+w*k,d.y+d.j/2-k/2),-1==D.Jb.Fa(D.Ep.lP,g.type)&&(g.type="star"),A.L(g,k,k));A=(0,D.mp)(b.e,D.r,D.r,D.o);v.k(A);(0,D.Ya)(A,d.x+w*k,d.y+d.j/2-k/2);-1==D.Jb.Fa(D.Ep.lP,p.type)&&(p.type="star");A.L(p,k,k)}h=new D.cd(b.e,d.x,d.y,d.g,d.j);(0,D.ed)(h);c.k(h);(c=f.shortDesc)&&b.Va().ma(h,
new D.rc(D.r,c))}else D.vp.Fz(b,c,new D.I(0,0,d,e))};
D.Ip=function(b){this.Init(b.e,b.ib,b);this.Uh=b;this.CJ=this.Ok=D.u;this.bfa=D.K.Md();this.T3=D.u};D.F.l(D.Ip,D.wp,"DvtRatingGaugeEventManager");D.E=D.Ip.prototype;D.E.ao=function(b){if(this.Uh.Da().readOnly===D.u&&!this.CJ){var c=(0,D.ZC)(this,b.pageX,b.pageY),d=this.Uh;(0,D.Gp)(d,d.gx(c.x,c.y),"hover");this.Ok=D.o}D.wp.q.ao.call(this,b)};
D.E.dk=function(b){if(this.Uh.Da().readOnly===D.u){if(this.bfa&&this.CJ&&this.T3){this.T3=D.u;return}(0,D.ZC)(this,b.pageX,b.pageY);(0,D.Hp)(this.Uh);this.CJ=D.u}D.wp.q.dk.call(this,b)};D.E.bl=function(b){this.CJ||(this.Uh.Da().readOnly===D.u?(this.Ok=D.o,this.oc(),b=(0,D.ZC)(this,b.pageX,b.pageY),this.Uh.pP(b.x,b.y)):D.wp.q.bl.call(this,b))};
D.E.Tm=function(b){this.Ok&&(this.Uh.Da().readOnly===D.u?(this.Ok=D.u,b=(0,D.ZC)(this,b.pageX,b.pageY),this.Uh.oP(b.x,b.y),(0,D.Hp)(this.Uh),this.CJ=D.o,this.bfa&&(this.T3=D.o)):D.wp.q.Tm.call(this,b))};D.E.B$=(0,D.ca)(D.o);
});