define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Rb=(0,D.z)();(0,D.ta)("DvtLegend",D.Rb);D.F.l(D.Rb,D.Sb,"DvtLegend");D.ya=function(b,c,d){var e=new D.Rb;e.Init(b,c,d);return e};D.Rb.newInstance=D.ya;D.Rb.getDefaults=function(b){return(0,D.Tb)(new D.Ub,b)};D.E=D.Rb.prototype;D.E.Init=function(b,c,d){D.Rb.q.Init.call(this,b,c,d);this.setId("legend1000"+window.Math.floor(1E9*window.Math.random()));this.ef=new D.Ub;this.Ga=new D.Vb(this);this.Ga.$e(this);this.zh=[];this.$S=[];this.Qa=D.r;this.mv=new D.Wb};D.E.Bx=(0,D.C)("mv");
D.E.Yd=function(b){b?this.X=this.ef.pg(b):this.X||(this.X=(0,D.Xb)(this))};D.E.mz=function(b,c,d){this.Yd(b);this.Da().isLayout=D.o;b=D.Yb.L(this,new D.I(0,0,c,d));this.Da().isLayout=D.u;return b};D.E.L=function(b,c,d){this.Yd(b);this.Da().isLayout=D.u;this.Mi();D.Yb.L(this,new D.I(0,0,c,d))};D.Rb.prototype.render=D.Rb.prototype.L;D.Rb.prototype.Cm=function(b){(0,D.Zb)(b,this.zh)};D.Rb.prototype.highlight=D.Rb.prototype.Cm;D.E=D.Rb.prototype;
D.E.Kf=function(b,c){var d=b.Ba();if("categoryRollOver"==d||"categoryRollOut"==d){"dim"==this.Da().hoverBehavior&&(0,D.Pb)(b,this.zh);for(var e=0;e<this.$S.length;e++)for(var f=this.$S[e],g=b.dm,g=g[0]?g[0]:g,h=0;h<f.zh.length;h++){var k=f.zh[h];if(k&&k.Kg&&-1<D.Jb.Fa(k.Kg(),g)){f.scrollIntoView(h);break}}}(this==c||"showPopup"==d||"hidePopup"==d)&&this.ib(b)};D.E.Da=(0,D.C)("X");D.E.Va=(0,D.C)("Ga");D.E.dZ=function(b){this.zh.push(b)};
D.E.V=function(){this.Ga&&(this.Ga.rs(this),this.Ga.V(),this.Ga=D.r);D.Rb.q.V.call(this)};D.E.eZ=(0,D.B)("Qa");D.E.vq=function(){return new D.$b(this)};D.Rb.prototype.getAutomation=D.Rb.prototype.vq;
D.ac={};(0,D.ta)("DvtLegendConstants",D.ac);D.F.l(D.ac,D.F,"DvtLegendConstants");D.ac.uD="background";D.ac.BACKGROUND=D.ac.uD;D.ac.GD="legendItem";D.ac.LEGEND_ITEM=D.ac.GD;D.ac.tp="title";D.ac.TITLE=D.ac.tp;
D.$b=function(b){this.Na=b;this.rd=this.Na.Da()};(0,D.ta)("DvtLegendAutomation",D.$b);D.F.l(D.$b,D.gn,"DvtLegendAutomation");D.$b.prototype.bx=function(b){if((b=(0,D.Dc)(this.Na.Va(),b))&&b instanceof D.Fv)if(b=b.getData(),b=(0,D.Gv)(this,b,this.rd))return"item"+b;return D.r};
D.Gv=function(b,c,d){if(d.sections&&0<d.sections.length){for(var e=0;e<d.sections.length;e++){var f=(0,D.Gv)(b,c,d.sections[e]);if(f)return"["+e+"]"+f}return D.r}if(d.items&&0<d.items.length){for(b=0;b<d.items.length;b++)if(d.items[b]==c)return"["+b+"]";return D.r}};
D.Hv=function(b,c,d){if(d.sections&&0<d.sections.length){for(var e=0;e<d.sections.length;e++){var f=(0,D.Hv)(b,c,d.sections[e]);if(f)return"["+e+"]"+f}return D.r}if(d.items&&0<d.items.length){for(b=0;b<d.items.length;b++)if(d.items[b].text==c.name)return"["+b+"]";return D.r}};D.Iv=function(b,c,d){var e=d.indexOf("["),f=d.indexOf("]");if(0<=e&&0<=f)return e=d.substring(e+1,f),d=d.substring(f+1),f=d.indexOf("]"),0<=d.indexOf("[")&&0<=f?(0,D.Iv)(b,c.sections[e],d):c.items[e]};
D.$b.prototype.bs=function(b){b=(0,D.Iv)(this,this.rd,b);for(var c=this.Na.zh,d=0;d<c.length;d++){var e=c[d].getData();if(b==e)return c[d].Ge()[0].Ea()}return D.r};D.$b.prototype.getDomElementForSubId=D.$b.prototype.bs;
D.Ub=function(){this.Init({skyros:D.Kv,alta:D.Lv})};D.F.l(D.Ub,D.Mg,"DvtLegendDefaults");D.Lv={skin:"alta",textStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"),titleStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333;"),colors:D.pl};
D.Kv={skin:"skyros",orientation:"vertical",position:D.r,backgroundColor:D.r,borderColor:D.r,textStyle:new D.P("font-size: 11px; color: #333333;"),titleStyle:new D.P("font-size: 12px; color: #003d5b;"),titleHalign:"start",hideAndShowBehavior:"none",hoverBehavior:"none",scrolling:"asNeeded",colors:D.ol,markerShape:"square",lineWidth:3,layout:{gapRatio:1,outerGapWidth:3,outerGapHeight:3,titleGap:3,markerSize:10,markerGap:5,rowGap:0,columnGap:8,sectionGap:6},isLayout:D.u};
D.Dv=function(b,c){return window.Math.ceil(c*b.layout.gapRatio)};
D.Vb=function(b){this.Init(b.e,b.Kf,b);this.Na=b};D.F.l(D.Vb,D.Bc,"DvtLegendEventManager");D.E=D.Vb.prototype;D.E.Ds=function(b,c){var d=D.r;c instanceof D.rc&&c.Gl()!=D.r?d=c.Gl():c instanceof D.Fv&&(d=c.getId(),d={type:D.ac.GD,id:d});this.Ug(new D.no(b,d),this.Na)};D.E.Vg=function(b){D.Vb.q.Vg.call(this,b);var c=(0,D.Dc)(this,b.target);if(c){var d=this.JS(c),c=(0,D.Jv)(this,c);(d||c)&&b.stopPropagation()}};
D.E.ao=function(b){D.Vb.q.ao.call(this,b);var c=(0,D.Dc)(this,b.target);c&&(this.Oy(c,D.o)&&b.stopPropagation(),(0,D.Gc)(this,c))};D.E.dk=function(b){D.Vb.q.dk.call(this,b);var c=(0,D.Dc)(this,b.target);c&&this.Oy(c,D.u)&&b.stopPropagation()};D.E.Ou=function(b){var c=(0,D.Dc)(this,b.target);if(c){b=b.tna;var d=this.JS(c),c=(0,D.Jv)(this,c);(d||c)&&b&&b.preventDefault()}};D.E.vX=function(b){var c=(0,D.Dc)(this,b.target);this.Oy(c,D.o)&&b.stopPropagation()};
D.E.tX=function(b){var c=(0,D.Dc)(this,b.target);this.Oy(c,D.u)&&b.stopPropagation()};D.E.EO=function(b){var c=(0,D.Dc)(this,b.target);this.Oy(c,D.o)&&b.stopPropagation()};D.E.uX=function(b){var c=(0,D.Dc)(this,b.target);this.Oy(c,D.u)&&b.stopPropagation()};
D.E.JS=function(b){if("none"==this.Na.Da().hideAndShowBehavior)return D.u;var c=b.Kg?b.Kg():D.r;if(!c||0>=c.length)return D.u;for(var d=b.getData(),e=d.categoryVisibility,f=b.Ge(),g=0;g<f.length;g++){var h=f[g];h instanceof D.Lb&&h.fD(b.Nb());h instanceof D.cd&&(0,D.xc)(h,"label",d.text+". "+(0,D.Na)(this.Na.Bx(),"visible"==e?"STATE_HIDDEN":"STATE_VISIBLE"))}b=c[0];"hidden"==e?(d.categoryVisibility="visible",this.Ug(new D.mo(D.mo.SD,b),this.Na)):(d.categoryVisibility="hidden",this.Ug(new D.mo(D.mo.sx,
b),this.Na));return D.o};D.Jv=function(b,c){return c&&c.uw&&c.ag?(b.Ug(new D.wm("action",c.ag,c.getId()),b.Na),D.o):D.u};D.Vb.prototype.Oy=function(b,c){if("none"==this.Na.Da().hoverBehavior)return D.u;var d=b&&b.Kg?b.Kg():D.r;if(!d||0>=d.length)return D.u;this.Ug(new D.Nb(c?"categoryRollOver":"categoryRollOut",d[0]),this.Na);return D.o};
D.Fv=function(b,c,d,e){this.Init(b,c,d,e)};D.F.l(D.Fv,D.F,"DvtLegendObjPeer");D.Fv.prototype.Init=function(b,c,d,e){this.Na=b;this.Rh=c;this.hfa=d;this.Ra=d.id?d.id:d.text;this.ag=d.action;this.rza=d._spb;this.Pe=e;if(this.ag)for(b=0;b<this.Rh.length;b++)this.Rh[b].setCursor("pointer")};D.Ev=function(b,c,d,e){if(!b||!d)return D.r;d=new D.Fv(c,b,d,e);c.dZ(d);for(e=0;e<b.length;e++)c.Va().ma(b[e],d);return d};D.E=D.Fv.prototype;D.E.getData=(0,D.C)("hfa");D.E.Nb=function(){return this.hfa.color};
D.E.getId=(0,D.C)("Ra");D.E.Ge=(0,D.C)("Rh");D.E.Kg=function(){return[this.Ra]};D.E.ee=(0,D.C)("Pe");D.E.uw=(0,D.C)("ag");D.E.xd=(0,D.C)("rza");
D.Yb={};D.F.l(D.Yb,D.F,"DvtLegendRenderer");D.Yb.cba=10;D.Yb.Bra=5;D.Yb.Cra=2;D.Yb.zra=6;
D.Yb.L=function(b,c){var d=b.Da(),e=(0,D.Dv)(d,d.layout.outerGapWidth),f=(0,D.Dv)(d,d.layout.outerGapHeight),g=new D.I(c.x+e,c.y+f,c.g-2*e,c.j-2*f);b.eZ(g.clone());if(0>=g.g)return new D.hl(0,0);var h;d.isLayout||(h=D.Yb.z_(b,c));var k="vertical"==d.orientation?D.u:D.o,m=D.Yb.PS(b,d.title,g,D.r);g.y+=m.j;g.j-=window.Math.floor(m.j);var p=D.Yb.Wva(b),q="off"!==d.scrolling,g=k?D.Yb.Dya(b,g,p):D.Yb.Vya(b,g,p,q),k=(0,D.xb)(m,g);if(0>=b.$S.length){for(p=new D.H(b.e);0<b.Aa();)p.k(b.ca(0));b.k(p);p.F((c.g-
k.g)/2-k.x)}h&&b.Ha(h,0);return d.isLayout?new D.hl(window.Math.max(m.g,g.g)+2*e,k.j+2*f):new D.hl(k.g+2*e,k.j+2*f)};D.Yb.z_=function(b,c){var d=b.Da(),e;d.backgroundColor&&(e=e?e:new D.cd(b.e,c.x,c.y,c.g,c.j),e.na(d.backgroundColor));d.borderColor&&(e=e?e:new D.cd(b.e,c.x,c.y,c.g,c.j),e.Ma(d.borderColor),(0,D.kc)(e));e&&b.Va().ma(e,new D.rc(D.r,D.r,D.r,{type:D.ac.uD,id:D.n}));return e};
D.Yb.PS=function(b,c,d,e){var f=b.Da();if(!c)return new D.I(d.x,d.y,0,0);c=new D.pc(b.e,c,d.x,d.y);var g=e&&e.titleStyle?new D.P(e.titleStyle):f.titleStyle;c.Ia(g);if(D.qc.Wb(c,d.g,d.j,b)){b.Va().ma(c,new D.rc(c.Po,D.r,D.r,{type:D.ac.tp,id:D.n}));var g=c.Vb(),h=(0,D.Dv)(f,f.layout.titleGap);f.isLayout?b.removeChild(c):(0,D.ho)(d,e&&e.titleHalign?e.titleHalign:f.titleHalign,c,g.g);g.j+=h;return g}return new D.I(d.x,d.y,0,0)};
D.Yb.eR=function(b,c){var d=b.sections;c.push(b);if(d)for(var e=0;e<d.length;e++)D.Yb.eR(d[e],c)};D.Yb.Vya=function(b,c,d,e){for(var f=b.Da(),g=D.Yb.Xta(b,c,d,e),h=[],k=0;k<f.sections.length;k++)D.Yb.eR(f.sections[k],h);var m=h.length,f=(0,D.Dv)(f,f.layout.sectionGap);c=c.clone();for(var p=D.r,q,k=0;k<h.length;k++)c.j=g[k],q=D.Yb.AL(b,h[k],k,c,d,e),k!=m-1&&h[k].items&&(c.y+=q.j+f),p=p?(0,D.xb)(p,q):q;return p};
D.Yb.Dya=function(b,c,d){for(var e=b.Da(),f=D.K.R(b.e),g=0,h=[],k=0;k<e.sections.length;k++)D.Yb.eR(e.sections[k],h);for(var m=h.length,p=0,k=0;k<h.length;k++)h[k].items&&(p+=h[k].items.length);var q=(0,D.Dv)(e,e.layout.sectionGap),t=c.g-q*(m-1),v,w;if(e.sections)for(var A=0,D$=0,k=0;k<m;k++)e=c.clone(),(v=h[k].items)?(v=window.Math.round(v.length/p*t),e.g=v,e.x=f?c.x+c.g-g-e.g:c.x+g,0<A&&(e.y+=D$,e.j-=D$),v=D.Yb.AL(b,h[k],k,e,d,D.u),0<A&&(e.j+=D$,A--),g+=v.g,k!=m-1&&(g+=q)):(e.g=c.g-g,e.x=f?c.x:
c.x+g,v=D.Yb.AL(b,h[k],k,e,d,D.u),D$=v.j,A=h[k].sections.length),w=w?(0,D.xb)(w,v):v;return w};
D.Yb.AL=function(b,c,d,e,f,g){if(c){var h=e.clone(),k=b.Da(),m=b.e,p=h.y,q=k.layout.markerSize,t=(0,D.Dv)(k,k.layout.markerGap),v=(0,D.Dv)(k,k.layout.rowGap),w=(0,D.Dv)(k,k.layout.columnGap),A=D.Yb.PS(b,c.title,h,c);h.y+=A.j;if(c.items){h.j-=A.j;var p=p+A.j,D$=D.Yb.Yta(b,h,f,c.items,g),J=D$.numCols,G=D$.numRows,L=D$.width;h.j=window.Math.ceil(window.Math.min(h.j,G*(f+v)-v)+A.j);h.g=L*J+w*(J-1);if(k.isLayout){if(1==G){for(d=e=0;d<c.items.length;d++)g=c.items[d],L=window.Math.ceil(D.Yb.SE(b,g.text)),
e+=L+q+t+w;h.g=e-w}return h}if(0==G||0==J)return h;var O=D.r,T=b,Q=G*(f+v)-v+A.j,D$=c.items.length;"vertical"===k.orientation&&(g&&Q>h.j)&&(T=D.Yb.vua(b,m,h,d),O=D.Yb.Bua(b,m,h,T,Q,D$),b.$S.push(O));var Q=L-q-t,V=D.K.R(b.e),aa=0,oa=1;if(1==G){for(d=O=0;d<D$;d++)g=c.items[d],L=window.Math.ceil(D.Yb.SE(b,g.text)),L<Q&&(O+=Q-L);for(d=0;d<D$;d++){g=c.items[d];var qa=V?h.x+h.g-q:h.x,ra=V?h.x+h.g-q-t:h.x+q+t,$a=D.Yb.$ca(b,qa,h.y,f,q,g,d),Oa=g.text,L=window.Math.ceil(D.Yb.SE(b,g.text)),eb=D.r;Oa&&(L<Q?eb=
D.Yb.C_(b,m,h,Q,Oa,k.textStyle):(eb=D.Yb.C_(b,m,h,Q+O,Oa,k.textStyle),eb!=D.r&&(L=window.Math.ceil(D.Yb.SE(b,eb.ne())),O-=Q-L)),L=eb!=D.r?window.Math.ceil(D.Yb.SE(b,eb.ne())):0,eb&&(eb.fa(ra),eb.ua(h.y+f/2),V&&eb.Bi()));b.k($a);L=L+q+t;qa=window.Math.min(qa,ra);ra=oa==J?L:L+w;qa=new D.cd(m,qa,h.y,ra,f);(0,D.ed)(qa);T.k(qa);ra=eb!=D.r?eb.Po:D.r;eb=(0,D.Ev)([qa,$a,eb],b,g,ra);"hidden"==g.categoryVisibility&&eb&&$a.fD(eb.Nb());"none"!=b.Da().hideAndShowBehavior&&((0,D.Ac)(qa,"img"),(0,D.xc)(qa,"label",
Oa+". "+(0,D.Na)(b.Bx(),"hidden"==g.categoryVisibility?"STATE_HIDDEN":"STATE_VISIBLE")));h.y+=f+v;aa++;aa===G&&oa!==J&&(h.y=p,V?h.g-=L+w:h.x+=L+w,aa=0,oa++)}}else for(d=0;d<D$;d++){g=c.items[d];qa=V?h.x+h.g-q:h.x;ra=V?h.x+h.g-q-t:h.x+q+t;$a=D.Yb.$ca(b,qa,h.y,f,q,g,d);Oa=g.text;eb=D.r;if(Oa&&(eb=D.Yb.C_(T,m,h,Q,Oa,k.textStyle)))eb.fa(ra),eb.ua(h.y+f/2),V&&eb.Bi();T.k($a);qa=window.Math.min(qa,ra);ra=oa==J?L:L+w;qa=new D.cd(m,qa,h.y,ra,f);(0,D.ed)(qa);T.k(qa);ra=eb!=D.r?eb.Po:D.r;eb=(0,D.Ev)([qa,$a,
eb],b,g,ra);O&&eb instanceof D.Fv&&O.dZ(eb);"hidden"==g.categoryVisibility&&eb&&$a.fD(eb.Nb());"none"!=b.Da().hideAndShowBehavior&&((0,D.Ac)(qa,"img"),(0,D.xc)(qa,"label",Oa+". "+(0,D.Na)(b.Bx(),"hidden"==g.categoryVisibility?"STATE_HIDDEN":"STATE_VISIBLE")));h.y+=f+v;aa++;aa===G&&oa!==J&&(h.y=p,V?h.g-=L+w:h.x+=L+w,aa=0,oa++)}h.y=p+h.j-A.height;return new D.I(e.x,p-A.height,e.g,h.j)}h.j=A.j}};
D.Yb.Xta=function(b,c,d,e){var f=b.Da(),g=f.isLayout;f.isLayout=D.o;for(var h=0,k=0,m=c.x,p=c.y,q=[],t=0;t<f.sections.length;t++)D.Yb.eR(f.sections[t],q);for(var v=q.length,w=(0,D.Dv)(f,f.layout.sectionGap),A=c.j-w*(v-1),D$=c.g,J=[],G,t=0;t<v;t++)c.j=A,c.g=D$,G=D.Yb.AL(b,q[t],t,c,d,e),J[t]=G.j;window.arSectionSpaceNeeded=[];window.extraSpace=window.numShortSections=0;G=A/v;for(t=0;t<v;t++)A=J[t]-G,0>=A?(window.arSectionSpaceNeeded[t]=0,window.extraSpace-=A):(J[t]=G,window.arSectionSpaceNeeded[t]=
A,window.numShortSections++);for(;0<window.extraSpace&&0<window.numShortSections;){G=window.extraSpace/window.numShortSections;for(t=0;t<v;t++)0<window.arSectionSpaceNeeded[t]&&(A=window.arSectionSpaceNeeded[t]-G,0>=A?(J[t]+=window.arSectionSpaceNeeded[t],window.arSectionSpaceNeeded[t]=0,window.extraSpace-=G+A,window.numShortSections--):(J[t]+=G,window.extraSpace-=G,window.arSectionSpaceNeeded[t]=A))}c.x=m;c.y=p;c.g=D$;for(t=0;t<v;t++)c.j=J[t],D.Yb.AL(b,q[t],t,c,d,e),c.x=m,k=window.Math.max(c.g,k),
h+=c.j,t!=v-1&&(c.y=c.j+p+w,h+=w);c.g=k;c.j=h;c.x=m;c.y=p;f.isLayout=g;return J};
D.Yb.Yta=function(b,c,d,e,f){for(var g=b.Da(),h=0,k=0;k<e.length;k++){var m=D.Yb.SE(b,e[k].text);m>h&&(h=m)}b=g.layout.markerSize;var p=(0,D.Dv)(g,g.layout.markerGap),k=(0,D.Dv)(g,g.layout.rowGap),m=(0,D.Dv)(g,g.layout.columnGap),h=g.isLayout?window.Math.ceil(b+p+h):c.g;"vertical"==g.orientation?f?(g=1,f=e.length):(f=window.Math.min(window.Math.floor((c.j+k)/(d+k)),e.length),g=window.Math.ceil(e.length/f)):(g=window.Math.min(window.Math.floor(c.g/h),e.length),f=window.Math.ceil(((h+m)*e.length-m)/
c.g),f*(d+k)-k>c.j&&(f=window.Math.floor(window.Math.ceil(c.j+k)/(d+k)),g=window.Math.ceil(e.length/f)));c=window.Math.min(h,(c.g-m*(g-1))/g);return c<b?{width:0,height:0,numCols:0,numRows:0}:{width:c,numCols:g,numRows:f}};D.Yb.Wva=function(b){var c=b.Da();b=new D.pc(b.e,"Test");b.Ia(c.textStyle);b.Ce();b=D.qc.Xj(b);return window.Math.ceil(window.Math.max(b.j,c.layout.markerSize))};D.Yb.SE=function(b,c){var d=b.Da(),e=new D.pc(b.e,c);e.Ia(d.textStyle);return e.Vb().g};
D.Yb.C_=function(b,c,d,e,f,g){c=new D.pc(c,f);c.Ce();c.Ia(g);return c=D.qc.Wb(c,e,d.j,b)?c:D.r};
D.Yb.$ca=function(b,c,d,e,f,g,h){var k=b.Da();g.markerShape||(g.markerShape=k.markerShape);if(!g.color){var m=k.colors;g.color=m[h%m.length]}g.lineWidth||(g.lineWidth=k.lineWidth);"line"==g.type?(g.lineWidth=window.Math.min(g.lineWidth,D.Yb.Bra),f=D.Yb.ada(b.e,c,d,e,g)):"lineWithMarker"==g.type?(g.lineWidth=window.Math.min(g.lineWidth,D.Yb.Cra),f=D.Yb.ada(b.e,c,d,e,g),"hidden"!=g.categoryVisibility&&f.k(D.Yb.cda(b,c,d,e,D.Yb.zra,g))):f=D.Yb.cda(b,c,d,e,f,g);return f};
D.Yb.cda=function(b,c,d,e,f,g){var h=b.e,k=b.Da();b=g.markerShape;var m=g.markerColor?g.markerColor:g.color,p=g.pattern;d+=(e-f)/2;c="lineWithMarker"==g.type?c+(D.Yb.cba-f)/2:c;p?(f=new D.Lb(h,b,k.skin,0,0,f,f),f.G(new D.zc(p,m,"#FFFFFF")),(0,D.Ya)(f,c,d)):(f=new D.Lb(h,b,k.skin,c,d,f,f),f.na(m));g.borderColor&&f.Ma(g.borderColor,D.r,g._borderWidth?g._borderWidth:1);"square"==b&&(0,D.kc)(f);return f};
D.Yb.ada=function(b,c,d,e,f){d+=e/2;b=new D.jc(b,c,d,c+D.Yb.cba,d);c=new D.Vd(f.color,1,f.lineWidth);f=f.lineStyle;"dashed"==f?c.Pi((0,D.ii)(f),"4,2,4"):"dotted"==f&&c.Pi((0,D.ii)(f),"2");b.Y(c);(0,D.kc)(b);return b};D.Yb.vua=function(b,c,d,e){var f=[d.x,d.y,d.x+d.g,d.y+d.j];d=d.clone();e=b.getId()+"_"+e;c=new D.Pg(c,"legendHandler",f,d,e);b.k(c);return c};D.Yb.Bua=function(b,c,d,e,f,g){c=new D.hh(c,d.x,d.y,d.g,d.j,f,e,g);c.SH(b.Va().Il());b.k(c);e.L();return c};
});