define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Sz={Zl:function(){return D.J.da()}};D.F.o(D.Sz,D.F,"DvtTimeUtils");D.Sz.df=function(b,c,d,e){d=(d-b)*e;b=c-b;return 0==d||0==b?0:d/b};D.Sz.Ke=function(b,c,d,e){c=d*(c-b);return 0==c||0==e?b:c/e+b};
D.gA=function(b,c,d){this.Init(b,c,d)};(0,D.ta)("DvtOverview",D.gA);D.F.o(D.gA,D.H,"DvtOverview");
D.gA.prototype.Init=function(b,c,d){D.gA.q.Init.call(this,b);this.Xa=c;this.ka=d;this.qn=this.Bu()?7:6;if(this.Xa!=D.r||this.ka!=D.r)D.Sz.Zl()?(this.P(D.Sa.Sd,this.YX,D.u,this),this.P(D.Sa.sh,this.XX,D.u,this),this.P(D.Sa.eg,this.TX,D.u,this),this.P(D.Ta,this.GI,D.u,this)):(this.P(D.Ua,this.QX,D.u,this),this.P(D.Va,this.PX,D.u,this),this.P(D.Ta,this.GI,D.u,this),this.P(D.uc,this.Yn,D.u,this),this.P(D.dd,this.Zn,D.u,this),this.P(D.cd,this.av,D.u,this),this.P(D.xe,this.yqa,D.u,this),this.P(D.we,this.Aqa,
D.u,this));this.v1=0};D.gA.prototype.Wz=function(b,c){var d=this.df(b),e=this.df(c);if(!(d<this.$p||e>(0,D.zC)(this))){var f=window.Math.max(e-d,(0,D.AC)(this));0<f&&(0<=d&&e<=this.ub)&&(e=this.ca(1),this.Ni()?(0,D.BC)(this,e,this.ub-(d+f)):(0,D.BC)(this,e,d),(0,D.CC)(this,e,f),(0,D.DC)(this))}};D.EC=function(b){return b.yh==D.r?D.u:-1!=b.yh.indexOf("zoom")};
D.gA.prototype.L=function(b,c,d){if(b==D.r){var e=this.Jg,f=this.wh,g=this.ca(1),h=(0,D.FC)(this,g);g!=D.r&&0!=h&&(this.tja=D.Sz.Ke(e,f,h,this.ub));this.Qi()}c!=D.r&&d!=D.r&&(this.ub=c,this.Mb=d);b&&(b=this.gv(b),this.qo(b));b=this.Xa!=D.r||this.ka!=D.r;this.WG(c,d);if(b){f=(e=this.yc())?new D.td(this.e,0,0,c,0,"window"):new D.td(this.e,0,0,0,d,"window");f.na(this.UT,this.FAa);(0,D.ic)(f);if(!(0,D.EC)(this)){var k=(0,D.GC)(),m=(0,D.HC)();if(e){var p=(c-36)/2,q=window.DvtPathUtils.moveTo(p,0)+window.DvtPathUtils.Yb(p+
3,6,p+8,8)+window.DvtPathUtils.lineTo(p+28,8)+window.DvtPathUtils.Yb(p+33,6,p+36,0);window.DvtPathUtils.closePath();h=window.DvtPathUtils.moveTo(p,0)+window.DvtPathUtils.Yb(p+3,-6,p+8,-8)+window.DvtPathUtils.lineTo(p+28,-8)+window.DvtPathUtils.Yb(p+33,-6,p+36,0);window.DvtPathUtils.closePath();var g=new D.td(this.e,0,0,c,k,"lhb"),k=new D.td(this.e,0,0,c,k,"rhb"),t="row-resize";if(this.e1)var v=(0,D.IC)(this,c,10),p=(0,D.IC)(this,c,10);else v=(0,D.JC)(this,p),p=(0,D.JC)(this,p)}else p=(d-36)/2,q=window.DvtPathUtils.moveTo(0,
p)+window.DvtPathUtils.Yb(6,p+3,8,p+8)+window.DvtPathUtils.lineTo(8,p+28)+window.DvtPathUtils.Yb(6,p+33,0,p+36),window.DvtPathUtils.closePath(),h=window.DvtPathUtils.moveTo(0,p)+window.DvtPathUtils.Yb(-6,p+3,-8,p+8)+window.DvtPathUtils.lineTo(-8,p+28)+window.DvtPathUtils.Yb(-6,p+33,0,p+36),window.DvtPathUtils.closePath(),g=new D.td(this.e,0-m,0,k,d,"lhb"),k=new D.td(this.e,m,0,k,d,"rhb"),t="col-resize",this.e1?(v=(0,D.IC)(this,10,d),p=(0,D.IC)(this,10,d)):(v=(0,D.JC)(this,p),p=(0,D.JC)(this,p));g.na(this.UT,
0);k.na(this.UT,0);(0,D.ic)(g);(0,D.ic)(k);q=new D.Pa(this.e,q,"lh");h=new D.Pa(this.e,h,"rh");q.na(this.KK);q.Ma(this.KK);h.na(this.KK);h.Ma(this.KK);this.UT==this.KK&&((0,D.ic)(q),(0,D.ic)(h));g.setCursor(t);k.setCursor(t);q.setCursor(t);h.setCursor(t);v.setCursor(t);p.setCursor(t);f.k(g);f.k(q);f.k(v);f.k(k);f.k(h);f.k(p)}f.setCursor("move");this.k(f);f=e?new D.hc(this.e,c-this.cN(),0,c-this.cN(),d,"tab"):"above"==this.VS?new D.hc(this.e,0,this.$j(),c,this.$j(),"tab"):new D.hc(this.e,0,d-this.$j(),
c,d-this.$j(),"tab");f.Ma(this.oAa,this.pAa);(0,D.ic)(f);this.k(f);this.Oq()&&(e?(f=new D.td(this.e,0,0,c,0,"lbg"),g=new D.td(this.e,0,0,c,0,"rbg")):(f=new D.td(this.e,0,0,0,d,"lbg"),g=new D.td(this.e,0,0,0,d,"rbg")),f.na(this.bha,this.Sxa),this.k(f),g.na(this.zja,this.Pza),this.k(g),D.Sz.Zl()&&m!=D.n&&((0,D.HC)(),e?(e=new D.td(this.e,0,0,c,m,"lbgrh"),m=new D.td(this.e,0,0,c,m,"rbgrh")):(e=new D.td(this.e,0,0,m,d,"lbgrh"),m=new D.td(this.e,0,0,m,d,"rbgrh")),e.na(this.bha,0),this.k(e),m.na(this.zja,
0),this.k(m)))}this.Voa(c,d);if(this.X0!=D.r)for(m=0;m<this.X0.length;m++)g=this.X0[m],e=c,f=d,t=(0,window.parseInt)(g.l("rs"),10),h=(0,window.parseInt)(g.l("re"),10),g=g.l("c"),t!=D.r&&h!=D.r&&(k=(0,D.KC)(this),t=this.df(t),h=this.df(h)-t,this.Ni()&&(t=k-t-h),e=this.yc()?new D.td(this.e,0,t,e-this.cN(),h,"ftr"):new D.td(this.e,t,"above"==this.VS?this.$j():0,h,f-this.$j(),"ftr"),g!=D.r&&e.na(g,0.4),e.setCursor("move"),(0,D.ic)(e),this.k(e));this.n0==D.r||(0,window.isNaN)(this.n0)||(m=this.df(this.n0),
this.yc()?m=new D.hc(this.e,0,m,c,m,"ocd"):(this.Ni()&&(m=c-m),m=new D.hc(this.e,m,0,m,d,"ocd")),m.Ma(this.wva),(0,D.ic)(m),this.k(m));this.DN(c,d);b&&(f=this.ca(1),this.yc()?(b=f.ha(),m=f.ha()+f.getHeight()-1,this.Bu()||D.J.dp()?(e=0,k=c-1):(e=1,k=c),f=new D.hc(this.e,0,b,c,b,"lh"),g=new D.hc(this.e,0,m,c,m,"rh"),h=new D.hc(this.e,e,0,e,b,"ltb"),c=new D.hc(this.e,e,m,e,d,"rtb"),d=new D.hc(this.e,k,b,k,m,"bb"),b=new D.hc(this.e,e,b,e,m,"tb")):(b=1,this.Bu()&&(b=0),m=d-1,e=f.ea(),k=f.ea()+f.getWidth()-
1,f=new D.hc(this.e,e,b,e,m,"lh"),g=new D.hc(this.e,k,b,k,m,"rh"),h=new D.hc(this.e,0,window.Math.max(0,b-1),e+1,window.Math.max(0,b-1),"ltb"),c=new D.hc(this.e,k-1,window.Math.max(0,b-1),c,window.Math.max(0,b-1),"rtb"),d=new D.hc(this.e,e,m,k,m,"bb"),b=new D.hc(this.e,e,b,k,b,"tb")),(0,D.ic)(f),(0,D.ic)(g),(0,D.ic)(h),(0,D.ic)(c),(0,D.ic)(d),(0,D.ic)(b),"none"!=this.JAa&&f.Ma(this.IAa),this.k(f),"none"!=this.LAa&&g.Ma(this.KAa),this.k(g),"none"!=this.Iua&&this.t_&&(h.Ma(this.t_),c.Ma(this.t_)),this.k(h),
this.k(c),"none"!=this.HAa&&d.Ma(this.GAa),this.k(d),"none"!=this.NAa&&b.Ma(this.MAa),this.k(b),this.Bu()&&(c=this.yc()?window.DvtPathUtils.moveTo(6,0)+window.DvtPathUtils.lineTo(0,5)+window.DvtPathUtils.lineTo(5,5)+window.DvtPathUtils.lineTo(5,17)+window.DvtPathUtils.lineTo(0,17)+window.DvtPathUtils.lineTo(6,22)+window.DvtPathUtils.lineTo(12,17)+window.DvtPathUtils.lineTo(7,17)+window.DvtPathUtils.lineTo(7,5)+window.DvtPathUtils.lineTo(12,5)+window.DvtPathUtils.closePath():window.DvtPathUtils.moveTo(5,
0)+window.DvtPathUtils.lineTo(0,6)+window.DvtPathUtils.lineTo(5,12)+window.DvtPathUtils.lineTo(5,7)+window.DvtPathUtils.lineTo(17,7)+window.DvtPathUtils.lineTo(17,12)+window.DvtPathUtils.lineTo(22,6)+window.DvtPathUtils.lineTo(17,0)+window.DvtPathUtils.lineTo(17,4)+window.DvtPathUtils.lineTo(5,4)+window.DvtPathUtils.lineTo(5,0)+window.DvtPathUtils.closePath(),c=new D.Pa(this.e,c,"arr"),c.na("#ffffff"),c.Ma("#000000"),c.$a(D.u),this.k(c),this.cG=c),b=this.yc(),d=this.ca(1),c=(0,D.KC)(this),m=b?this.Mb:
this.ub,f=this.R,g=this.Jg,h=this.wh,b=this.tja,e=D.Sz.Ke(g,h,0,f),f=D.Sz.Ke(g,h,m,f),e=this.df(e),m=window.Math.min(m,this.df(f)),b=this.df(b),m-=e,this.Ni()?(0,D.BC)(this,d,c-b-m):(0,D.BC)(this,d,b),(0,D.CC)(this,d,m),(0,D.DC)(this),d=this.R,b=this.Jg,m=this.wh,e=D.Sz.Ke(b,m,1,c),c=D.Sz.Ke(b,m,2,c),e=D.Sz.df(b,m,e,d),this.t1=D.Sz.df(b,m,c,d)-e);this.nga!=D.r&&(this.v1=window.Math.max(0,D.Sz.df(this.Jg,this.wh,this.nga,this.R)));0<this.v1&&(c=this.v1/this.t1,this.Ni()&&(c=0-c),(0,D.lA)(this,c))};
D.gA.prototype.render=D.gA.prototype.L;D.E=D.gA.prototype;D.E.Ima=function(){return new D.xC(this)};D.E.gv=function(b){return this.Ima(b).parse(b)};
D.E.qo=function(b){this.Jg=b.start;this.wh=b.end;this.R=b.width;this.tja=b.A8;this.n0=b.currentTime;this.nga=b.UEa;this.aua=b.$Aa;this.$p=window.Math.max(0,b.wFa);this.dG=window.Math.max(0,b.GGa);(0,window.isNaN)(this.$p)&&(this.$p=0);(0,window.isNaN)(this.dG)&&(this.dG=0);this.Py=b.orientation;this.VS=b.joa;this.Cga=b.uV;b.xla!=D.r&&(this.yh=b.xla.split(" "));b.a8!=D.r&&0<b.a8&&(this.Hha=b.a8);this.Hua=b.iBa;this.kM=b.Poa;b.Poa!=D.r&&(this.jM=this.kM.kHa);this.X0=b.oCa;this.Iua=b.borderTopStyle;
this.t_=b.borderTopColor;this.UT=b.h9;this.FAa=b.Xoa;this.NAa=b.p9;this.LAa=b.n9;this.HAa=b.j9;this.JAa=b.l9;this.MAa=b.o9;this.KAa=b.m9;this.GAa=b.i9;this.IAa=b.k9;this.fxa=b.C7;this.KK=b.x7;this.e1=b.Yma;this.Zfa=b.lna;this.Wfa=b.jna;this.Gya=b.f8;this.wva=b.M5;this.qAa=b.a9;this.oAa=b.Noa;this.pAa=b.Ooa;this.bha=b.Mna;this.Sxa=b.Lna;this.zja=b.Aoa;this.Pza=b.zoa};D.E.df=function(b){return window.Math.max(0,D.Sz.df(this.Jg,this.wh,b,(0,D.KC)(this)))+this.$p};
D.E.Ke=function(b){return D.Sz.Ke(this.Jg,this.wh,window.Math.max(0,b-this.$p),(0,D.KC)(this))};D.E.Ni=function(){return!this.yc()&&"true"==this.Cga};D.E.yc=function(){return"vertical"==this.Py};D.KC=function(b){return b.yc()?b.Mb-b.$p-b.dG:b.ub-b.$p-b.dG};D.zC=function(b){return b.yc()?b.Mb-b.dG:b.ub-b.dG};D.AC=function(b){return b.u2!=D.r?b.u2:b.Hha!=D.r?(b.u2=D.Sz.df(b.Jg,b.wh,b.Jg+b.Hha,(0,D.KC)(b)),b.u2):10};D.HC=function(){return D.Sz.Zl()?(0,D.GC)()/2:0};
D.GC=function(){return D.Sz.Zl()?30:10};D.LC=function(b){var c=b.getId();return"lh"==c||"rh"==c||"lhb"==c||"rhb"==c||"grpy"==c||"lbgrh"==c||"rbgrh"==c||b.getParent()!=D.r&&"grpy"==b.getParent().getId()};D.gA.prototype.cN=function(){if(this.kM==D.r)return 0;if(this.lM==D.r){var b=(0,window.parseInt)(this.kM.width,10);this.lM=!(0,window.isNaN)(b)&&b<this.ub?b:40}return this.lM};
D.gA.prototype.$j=function(){if(this.kM==D.r)return 0;if(this.mka==D.r){var b=(0,window.parseInt)(this.kM.height,10);this.mka=!(0,window.isNaN)(b)&&b<this.Mb?b:20}return this.mka};D.MC=function(b){return D.Sz.Zl()&&b.targetTouches!=D.r?0<b.targetTouches.length?b.targetTouches[0].pageX:D.r:b.pageX};D.NC=function(b){return D.Sz.Zl()&&b.targetTouches!=D.r?0<b.targetTouches.length?b.targetTouches[0].pageY:D.r:b.pageY};D.gA.prototype.Oq=(0,D.ca)(D.u);D.OC=function(b){return b.Oq()?b.ca(3):D.r};
D.PC=function(b){return b.Oq()?b.ca(4):D.r};D.QC=function(b){return b.Oq()&&!(0,D.EC)(b)?b.ca(6):D.r};D.RC=function(b,c,d,e){b.yc()?(-1!=d&&c.Ui(d),-1!=e&&c.dl(e)):(-1!=d&&c.ek(d),-1!=e&&c.mi(e))};D.SC=function(b,c){return b.yc()?c.Rl():c.Ki()};D.gA.prototype.YE=function(b){b=b.target;if(b!=D.r){var c=b.getId();if(c==D.r)return D.r;if("_border"==c.substr(c.length-7))return this.o6(b);if("tick"!=c.substr(0,4)&&"ltb"!=c&&"rtb"!=c&&"bb"!=c&&"tab"!=c)return b}return D.r};
D.jA=function(b){return"window"==b.getId()||"ftr"==b.getId()||"sta"==b.getId()||(0,D.LC)(b)?D.o:D.u};D.gA.prototype.Bu=function(){return window&&window.Bu};D.gA.prototype.WG=function(b,c){var d=new D.td(this.e,0,0,b,c,"bg");d.na(this.Gya);(0,D.ic)(d);this.k(d);return d};D.IC=function(b,c,d){return new D.La(b.e,b.e1,(c-b.Zfa)/2,(d-b.Wfa)/2,b.Zfa,b.Wfa,"grpy")};
D.JC=function(b,c){var d=new D.H(b.e,"grpy"),e=b.fxa;if(b.yc()){for(var f=8+c,g=3,h=0;9>h;h++){var k=new D.hc(b.e,f+2*h,g,f+2*h+1,g,"dot1"+h);k.Ma(e);d.k(k);g+=2;k=new D.hc(b.e,f+1+2*h,g,f+1+2*h+1,g,"dot2"+h);k.Ma(e);d.k(k);g+=2;k=new D.hc(b.e,f+2*h,g,f+2*h+1,g,"dot3"+h);k.Ma(e);d.k(k);g=3}k=new D.hc(b.e,f+18,g,f+18+1,g,"dot4");k.Ma(e);d.k(k);g+=4;k=new D.hc(b.e,f+18,g,f+18+1,g,"dot5")}else{f=3;g=8+c;for(h=0;9>h;h++)k=new D.hc(b.e,f,g+2*h,f,g+2*h+1,"dot1"+h),k.Ma(e),d.k(k),f+=2,k=new D.hc(b.e,f,g+
1+2*h,f,g+1+2*h+1,"dot2"+h),k.Ma(e),d.k(k),f+=2,k=new D.hc(b.e,f,g+2*h,f,g+2*h+1,"dot3"+h),k.Ma(e),d.k(k),f=3;k=new D.hc(b.e,f,g+18,f,g+18+1,"dot4");k.Ma(e);d.k(k);f+=4;k=new D.hc(b.e,f,g+18,f,g+18+1,"dot5")}k.Ma(e);d.k(k);(0,D.ic)(d);return d};D.TC=function(b,c){return b.yc()?c.getHeight():c.getWidth()};D.FC=function(b,c){return b.yc()?c.K():c.M()};
D.BC=function(b,c,d){d=window.Math.max(0,d);b.yc()?c.Q(d):c.F(d);if(b.Oq()){(0,D.OC)(b).ia(d);c=d+(0,D.TC)(b,c);var e=(0,D.PC)(b);e.fa(c);e.ia(window.Math.max(0,b.ub-c));D.Sz.Zl()&&!(0,D.EC)(b)&&(e=(0,D.HC)(),(b.Oq()&&!(0,D.EC)(b)?b.ca(5):D.r).fa(d-e),(0,D.QC)(b).fa(c))}};
D.CC=function(b,c,d){d=window.Math.max((0,D.AC)(b),d);var e=d=window.Math.min(b.yc()?b.Mb:b.ub,d);b.yc()?c.va(e):c.ia(e);if(b.Oq()){var e=(0,D.FC)(b,c)+d,f=(0,D.PC)(b);f.fa(e);f.ia(window.Math.max(0,b.ub-e));D.Sz.Zl()&&!(0,D.EC)(b)&&(0,D.QC)(b).fa(e)}(0,D.EC)(b)||(e=c.ca(3),f=c.ca(4),c=c.ca(5),b.yc()?(f.Q(d),e.Q(d-(0,D.GC)()),c.Q(d-10)):(f.F(d),e.F(d-(0,D.GC)()),c.F(d-10)))};
D.gA.prototype.Voa=function(b,c){if(this.jM!=D.r){this.yc();for(var d=(0,D.KC)(this),e=0;e<this.jM.length;e++){var f=this.jM[e],g=(0,window.parseInt)(f.l("time"),10),g=this.df(g),f=f.l("label"),h=0;e+1<this.jM.length?(h=(0,window.parseInt)(this.jM[e+1].l("time"),10),h=this.df(h)-g):h=d-g;this.Ni()&&(g=d-g);this.cU(g,b,c,"tick"+e);this.p5(g,f,b,c,h,"label"+e)}}};
D.gA.prototype.cU=function(b,c,d,e){b=this.yc()?new D.hc(this.e,0,b,c,b,e):new D.hc(this.e,b,0,b,d,e);c=new D.Ud(this.qAa);c.ba(1,3);b.Y(c);(0,D.ic)(b);this.k(b)};D.gA.prototype.p5=function(b,c,d,e,f,g){this.yc()?b=new D.nc(this.e,c,4,b,g):(d="above"==this.VS?2:e-this.$j()+2,b=new D.nc(this.e,c,b+5,d,g));b.Ia(new D.P("font-weight:bold"));D.oc.Vb(b,f,window.Infinity,this);b.dza=b.Uo};D.gA.prototype.DN=(0,D.z)();
D.lA=function(b,c){var d=b.ca(1);d.ca(3);d.ca(4);d.ca(5);if(c!=(0,D.FC)(b,d)){var e=b.ca(b.Aa()-b.qn),f=b.ca(b.Aa()-(b.qn-1)),g=b.ca(b.Aa()-(b.qn-2)),h=b.ca(b.Aa()-(b.qn-3)),k=b.ca(b.Aa()-(b.qn-4)),m=b.ca(b.Aa()-(b.qn-5));if(b.yc())var p=d.K,q=d.Q,t=e.Rl,v=e.Ui,w=e.Jq,A=e.dl,D$=f.Rl,K=f.Ui,G=f.Jq,M=f.dl,O=g.Jq,T=g.dl,Q=h.Rl,V=h.Ui,aa=k.Rl,oa=k.Ui,sa=k.Jq,ra=k.dl,Za=m.Rl,Ra=m.Ui,db=m.Jq,Cb=m.dl;else p=d.M,q=d.F,t=e.Ki,v=e.ek,w=e.Ln,A=e.mi,D$=f.Ki,K=f.ek,G=f.Ln,M=f.mi,O=g.Ln,T=g.mi,Q=h.Ki,V=h.ek,aa=
k.Ki,oa=k.ek,sa=k.Ln,ra=k.mi,Za=m.Ki,Ra=m.ek,db=m.Ln,Cb=m.mi;var Eb=b.$p,Cd=(0,D.zC)(b),Xc=(0,D.TC)(b,d);c=window.Math.max(Eb,window.Math.min(Cd-Xc,c));Eb="off"!==b.aua?new D.tb(b.e,0.5,0,D.wj):D.r;(0,D.UC)(Eb,d,p,q,c);(0,D.UC)(Eb,e,t,v,c);(0,D.UC)(Eb,e,w,A,c);(0,D.UC)(Eb,f,D$,K,c+Xc);(0,D.UC)(Eb,f,G,M,c+Xc);(0,D.UC)(Eb,g,O,T,c+1);(0,D.UC)(Eb,h,Q,V,c+Xc-1);(0,D.UC)(Eb,k,aa,oa,c);(0,D.UC)(Eb,m,Za,Ra,c);(0,D.UC)(Eb,k,sa,ra,c+Xc);(0,D.UC)(Eb,m,db,Cb,c+Xc);b.Oq()&&(d=(0,D.OC)(b),(0,D.UC)(Eb,d,d.getWidth,
d.ia,c),Xc=c+Xc,d=(0,D.PC)(b),e=d.getWidth,f=d.ia,g=d.ea,h=d.fa,k=b.yc()?b.Mb:b.ub,(0,D.UC)(Eb,d,e,f,k-Xc),(0,D.UC)(Eb,d,g,h,Xc),D.Sz.Zl()&&!(0,D.EC)(b)&&(d=(0,D.HC)(),e=b.Oq()&&!(0,D.EC)(b)?b.ca(5):D.r,f=e.ea,g=e.fa,h=(0,D.QC)(b),k=h.ea,m=h.fa,(0,D.UC)(Eb,e,f,g,c-d),(0,D.UC)(Eb,h,k,m,Xc)));Eb!=D.r&&Eb.play()}};D.UC=function(b,c,d,e,f){b!=D.r?(0,D.N)(b,"typeNumber",c,d,e,f):e.call(c,f)};
D.gA.prototype.QX=function(b){var c=this.YE(b);if(c&&!("bg"==c.getId()||"ocd"==c.getId()))if("label"==c.getId().substr(0,5)&&c instanceof D.nc)c.ef()&&this.e.kd().fI(b.pageX,b.pageY,c.dza,"#000000");else if(this.cG!=D.r&&(0,D.LC)(c)&&(b=(0,D.rg)(this.e,b.pageX,b.pageY),b=this.Gb(b),this.yc()?(0,D.Xa)(this.cG,b.x+6,b.y-10):(0,D.Xa)(this.cG,b.x-6,b.y-20),this.cG.$a(D.o)),"window"==c.getId()||"ftr"==c.getId()||"arr"==c.getId()||(0,D.LC)(c))this.Bu()&&this.setCursor("move");else return c};
D.gA.prototype.PX=function(b){this.vm==D.r&&this.setCursor("default");b=this.YE(b);if(b!=D.r)return(0,D.LC)(b)&&this.cG!=D.r&&this.cG.$a(D.u),b};
D.gA.prototype.GI=function(b,c,d){b.stopPropagation();var e=this.YE(b);if(e&&!("window"==e.getId()||(0,D.LC)(e)))if("bg"==e.getId()||"label"==e.getId().substr(0,5)||"ocd"==e.getId()||"lbg"==e.getId()||"rbg"==e.getId()){c==D.n&&(c=b.pageX);d==D.n&&(d=b.pageY);b=(0,D.rg)(this.e,c,d);b=this.Gb(b);this.yc()?(d=b.y,e=this.Mb):(d=b.x,e=this.ub);b=this.ca(1);c=d-(0,D.TC)(this,b)/2;(0,D.lA)(this,c);this.Ni()&&(d=this.ub-d);var f=this.Ke(d);d=new D.wh("scrollTime");d.setTime(f);c=window.Math.max(0,window.Math.min(c,
e-(0,D.TC)(this,b)));this.Ni()?(e=this.Ke(this.ub-(c+(0,D.TC)(this,b))),b=this.Ke(this.ub-c)):(e=this.Ke(c),b=this.Ke(c+(0,D.TC)(this,b)));(0,D.xh)(d,e);(0,D.yh)(d,b);this.dispatchEvent(d)}else return e};D.gA.prototype.Yn=function(b){(0,D.VC)(this,b)};
D.VC=function(b,c){c.stopPropagation();var d=b.YE(c);if(d!=D.r&&(0,D.jA)(d)){if("ftr"==d.getId()||"sta"==d.getId())d=b.ca(1);b.KR=(0,D.MC)(c);b.mga=(0,D.NC)(c);if((0,D.LC)(d)){var e=b.ca(1);b.Ni()?(b.I2=b.ub-e.ea(),b.R2=b.I2-e.getWidth()):(b.R2=e.ea(),b.I2=b.R2+e.getWidth());"grpy"==d.getParent().getId()&&(d=d.getParent());var f=d.getId();"grpy"==f&&(d=e.EU(d),f=d.getId());if("lh"==f||"rh"==f)d=e.EU(d),f=d.getId();"lbgrh"==f&&(d=e.ca(0));"rbgrh"==f&&(d=e.ca(e.Aa()-3));D.Sz.Zl()||(b.yc()?(d.ua(-20),
d.va(2*(d.getHeight()+20))):(d.fa(-20),d.ia(2*(d.getWidth()+20))));e=d.getCursor();f=b.ca(1);f!=D.r&&f.setCursor(e);if(b.Oq()){var f=(0,D.OC)(b),g=(0,D.PC)(b);f!=D.r&&g!=D.r&&(f.setCursor(e),g.setCursor(e))}}b.vm=d;d=new D.wh("dropCallback");b.dispatchEvent(d)}};D.gA.prototype.Zn=function(b){(0,D.WC)(this,b)};
D.WC=function(b,c){c!=D.r&&c.stopPropagation();if(b.vm!=D.r){if("window"==b.vm.getId())b.Bla(0,0,0);else if((0,D.LC)(b.vm)){b.b6();D.Sz.Zl()||(b.yc()?(b.vm.ua(0),b.vm.va((0,D.GC)())):(b.vm.fa(0),b.vm.ia((0,D.GC)())));var d=b.ca(1);d!=D.r&&d.setCursor("move");if(b.Oq()){var d=(0,D.OC)(b),e=(0,D.PC)(b);d!=D.r&&e!=D.r&&(d.setCursor("default"),e.setCursor("default"))}}b.vm=D.r;b.KR=-1}};D.gA.prototype.av=function(b){(0,D.XC)(this,b)};
D.XC=function(b,c){c.stopPropagation();if(b.vm!=D.r&&-1!=b.KR){var d=(0,D.MC)(c),e=(0,D.NC)(c),f=d-b.KR,g=e-b.mga;b.KR=d;b.mga=e;"window"==b.vm.getId()?b.mna(0,f,g):"lh"==b.vm.getId()||"lhb"==b.vm.getId()?(0,D.YC)(b,c,f,g,D.o):("rh"==b.vm.getId()||"rhb"==b.vm.getId())&&b.B7(c,f,g)}};D.E=D.gA.prototype;
D.E.YX=function(b){var c=b.targetTouches[0];this.GG=c.pageX;this.nC=c.pageY;2==b.targetTouches.length?(b.preventDefault(),c=b.targetTouches[1],this.HG=c.pageX,this.rM=c.pageY,20>window.Math.abs(this.nC-this.rM)?this.dK=0:this.rM=this.HG=this.nC=this.GG=D.r):(0,D.VC)(this,b)};
D.E.XX=function(b){b.preventDefault();if(this.HG!=D.r&&this.rM!=D.r)if(50>this.dK)this.dK++;else{var c=b.targetTouches[1];this.B7(D.r,c.pageX-this.HG,0);this.HG=c.pageX;this.dK=0}else{c=b.targetTouches[0];if(this.GG!=c.pageX||this.nC!=c.pageY)this.nC=this.GG=D.r;(0,D.XC)(this,b)}};D.E.TX=function(b){this.HG!=D.r&&this.rM!=D.r?this.b6():((0,D.WC)(this,b),this.GG!=D.r&&this.nC!=D.r&&this.GI(b,this.GG,this.nC));this.rM=this.HG=this.nC=this.GG=D.r};
D.E.yqa=function(b){var c=b.keyCode;if(37===c||39===c)c=37===c?-1:1,(b.shiftKey?this.B7:this.mna).call(this,b,c,c)};D.E.Aqa=function(b){var c=b.keyCode;if(37===c||39===c)c=37===c?-1:1,(b.shiftKey?this.b6:this.Bla).call(this,b,c,c)};D.E.mna=function(b,c,d){(0,D.ZC)(this,"scrollPos",c,d)};D.E.Bla=function(b,c,d){(0,D.ZC)(this,"scrollEnd",c,d)};
D.ZC=function(b,c,d,e){var f=b.ca(1),g=(0,D.FC)(b,f),h=(0,D.TC)(b,f),k=b.$p,m=(0,D.zC)(b);d=b.yc()?e:d;g+d<=k?((0,D.BC)(b,f,k),h=b.Ni()?-2:-1):g+h+d>=m?((0,D.BC)(b,f,m-h),h=b.Ni()?-1:-2):((0,D.BC)(b,f,g+d),h=b.Ni()?(m-h-g-b.$p)*b.t1:(g-b.$p)*b.t1);(0,D.DC)(b);c=new D.wh(c);c.Ug(h);b.Ni()?(h=b.Ke(b.ub-(g+(0,D.TC)(b,f))),f=b.Ke(b.ub-g)):(h=b.Ke(g),f=b.Ke(g+(0,D.TC)(b,f)));(0,D.xh)(c,h);(0,D.yh)(c,f);b.dispatchEvent(c)};D.gA.prototype.B7=function(b,c,d){(0,D.YC)(this,b,c,d,D.u)};
D.YC=function(b,c,d,e,f){var g=(0,D.KC)(b);e=b.yc()?e:d;if(0!=e){d=b.ca(1);var h=(0,D.FC)(b,d),k=(0,D.TC)(b,d);if(f){if(k-e<=(0,D.AC)(b)||h+e<=b.$p)return;c=b.yc()?(0,D.rg)(b.e,(0,D.MC)(c),(0,D.NC)(c)).y:(0,D.rg)(b.e,(0,D.MC)(c),(0,D.NC)(c)).x;c=b.Gb(c);if(0<e&&c<=h||0>e&&c>=h)return;(0,D.BC)(b,d,h+e);(0,D.CC)(b,d,k-e)}else{if(k+e<=(0,D.AC)(b)||h+k+e>=(0,D.zC)(b))return;c=b.yc()?(0,D.rg)(b.e,(0,D.MC)(c),(0,D.NC)(c)).y:(0,D.rg)(b.e,(0,D.MC)(c),(0,D.NC)(c)).x;c=b.Gb(c);if(0<e&&c<=h+k||0>e&&c>=h+k)return;
(0,D.CC)(b,d,k+e)}(0,D.DC)(b);c=b.Ke((0,D.TC)(b,d));c=g*(b.wh-b.Jg)/(c-b.Jg);b.Cna()&&(g=new D.wh("rangeChanging"),(0,D.lb)(g,"newSize",c),c=b.Ni()?f:!f,(0,D.lb)(g,"endHandle",c),f?(0,D.lb)(g,"expand",0>e):(0,D.lb)(g,"expand",0<e),b.Ni()?(f=b.Ke(b.ub-((0,D.FC)(b,d)+(0,D.TC)(b,d))),d=b.Ke(b.ub-(0,D.FC)(b,d))):(f=b.Ke((0,D.FC)(b,d)),d=b.Ke((0,D.FC)(b,d)+(0,D.TC)(b,d))),(0,D.xh)(g,f),(0,D.yh)(g,d),b.dispatchEvent(g))}};D.gA.prototype.Cna=(0,D.ca)(D.o);
D.gA.prototype.b6=function(){var b=this.Jg,c=this.wh,d=this.R,e=(0,D.KC)(this),f=this.ca(1),g=this.Ke((0,D.TC)(this,f)),b=e*(c-b)/(g-b),c=this.Ke(this.R2),e=this.Ke(this.I2);this.Ni()?(g=this.Ke(this.ub-((0,D.FC)(this,f)+(0,D.TC)(this,f))),f=this.Ke(this.ub-(0,D.FC)(this,f))):(g=this.Ke((0,D.FC)(this,f)),f=this.Ke((0,D.FC)(this,f)+(0,D.TC)(this,f)));var h=new D.wh("rangeChange");(0,D.lb)(h,"oldSize",d);(0,D.lb)(h,"newSize",b);(0,D.lb)(h,"oldStartTime",c);(0,D.lb)(h,"oldEndTime",e);(0,D.xh)(h,g);(0,D.yh)(h,
f);this.dispatchEvent(h)};D.DC=function(b){var c=b.ca(1),d=b.ca(b.Aa()-b.qn),e=b.ca(b.Aa()-(b.qn-1)),f=b.ca(b.Aa()-(b.qn-2)),g=b.ca(b.Aa()-(b.qn-3)),h=b.ca(b.Aa()-(b.qn-4)),k=b.ca(b.Aa()-(b.qn-5));(0,D.RC)(b,d,(0,D.FC)(b,c),(0,D.FC)(b,c));(0,D.RC)(b,e,(0,D.FC)(b,c)+(0,D.TC)(b,c),(0,D.FC)(b,c)+(0,D.TC)(b,c));(0,D.RC)(b,f,-1,(0,D.FC)(b,c)+1);(0,D.RC)(b,g,(0,D.SC)(b,e)-1,-1);(0,D.RC)(b,h,(0,D.SC)(b,d),(0,D.SC)(b,e));(0,D.RC)(b,k,(0,D.SC)(b,d),(0,D.SC)(b,e))};
D.gA.prototype.dispatchEvent=function(b){D.ob.dispatchEvent(this.Xa,this.ka,this,b)};
D.xC=function(b){this.Init(b)};D.F.o(D.xC,D.F,"DvtOverviewParser");D.xC.prototype.Init=(0,D.B)("I");D.xC.prototype.parse=function(b){return this.bm(b)};
D.xC.prototype.bm=function(b){var c={};c.$Aa=b.animationOnClick;b.startTime!=D.r&&(c.start=b.startTime);b.endTime!=D.r&&(c.end=b.endTime);c.start==D.r&&(c.start=(new window.Date).getTime());if(c.end==D.r||c.end<=c.start)c.end=c.start+864E5;b.currentTime!=D.r&&(c.currentTime=b.currentTime);b.initialFocusTime!=D.r&&(c.UEa=b.initialFocusTime);c.orientation="horizontal";b.orientation!=D.r&&(c.orientation=b.orientation);c.xla=b.featuresOff;c.a8=b.minimumWindowSize;c.wFa=b.leftMargin;c.GGa=b.rightMargin;
if(b.viewportEndTime!=D.r){var d=b.viewportEndTime,e=c.start;b.viewportStartTime!=D.r&&b.viewportStartTime<d&&(e=b.viewportStartTime);c.width=b.viewportEndPos!=D.r?(0,D.yC)(c.start,c.end,e,d,b.viewportEndPos):(0,D.yC)(c.start,c.end,e,d,this.I.ub);c.A8=e}else c.A8=c.start;0==c.width&&(c.width=1E3);c.joa="below";c.MN="none";c.uV=D.J.S(this.I.e).toString();b.rtl!=D.r&&(c.uV=b.rtl.toString());c.x7="#FFFFFF";c.C7="#B3C6DB";c.h9="#FFFFFF";c.Xoa=1;c.p9="solid";c.n9="solid";c.j9="solid";c.l9="solid";c.o9=
"#4F4F4F";c.m9="#4F4F4F";c.i9="#4F4F4F";c.k9="#4F4F4F";c.f8="#E6ECF3";c.M5="#C000D1";c.a9="#BCC7D2";c.Noa="#e5e5e5";c.Ooa=1;c.Mna="#FFFFFF";c.Lna=0.7;c.Aoa="#FFFFFF";c.zoa=0.7;b.style!=D.r&&(b.style.handleFillColor!=D.r&&(c.x7=b.style.handleFillColor),b.style.handleTextureColor!=D.r&&(c.C7=b.style.handleTextureColor),b.style.handleBackgroundImage!=D.r&&(c.Yma=b.style.handleBackgroundImage),b.style.handleWidth!=D.r&&(c.lna=b.style.handleWidth),b.style.handleHeight!=D.r&&(c.jna=b.style.handleHeight),
b.style.windowBackgroundColor!=D.r&&(c.h9=b.style.windowBackgroundColor),b.style.windowBackgroundAlpha!=D.r&&(c.Xoa=b.style.windowBackgroundAlpha),b.style.windowBorderTopStyle!=D.r&&(c.p9=b.style.windowBorderTopStyle),b.style.windowBorderRightStyle!=D.r&&(c.n9=b.style.windowBorderRightStyle),b.style.windowBorderBottomStyle!=D.r&&(c.j9=b.style.windowBorderBottomStyle),b.style.windowBorderLeftStyle!=D.r&&(c.l9=b.style.windowBorderLeftStyle),b.style.windowBorderTopColor!=D.r&&(c.o9=b.style.windowBorderTopColor),
b.style.windowBorderRightColor!=D.r&&(c.m9=b.style.windowBorderRightColor),b.style.windowBorderBottomColor!=D.r&&(c.i9=b.style.windowBorderBottomColor),b.style.windowBorderLeftColor!=D.r&&(c.k9=b.style.windowBorderLeftColor),b.style.overviewBackgroundColor!=D.r&&(c.f8=b.style.overviewBackgroundColor),b.style.currentTimeIndicatorColor!=D.r&&(c.M5=b.style.currentTimeIndicatorColor),b.style.timeIndicatorColor!=D.r&&(c.a9=b.style.timeIndicatorColor),b.style.leftFilterPanelColor!=D.r&&(c.Mna=b.style.leftFilterPanelColor),
b.style.leftFilterPanelAlpha!=D.r&&(c.Lna=b.style.leftFilterPanelAlpha),b.style.rightFilterPanelColor!=D.r&&(c.Aoa=b.style.rightFilterPanelColor),b.style.rightFilterPanelAlpha!=D.r&&(c.zoa=b.style.rightFilterPanelAlpha));return c};D.yC=function(b,c,d,e,f){b=f*(c-b);d=e-d;return 0==b||0==d?0:b/d};
D.wh=function(b){this.Init("overview");this.El=b};D.F.o(D.wh,D.ed,"DvtOverviewEvent");D.wh.prototype.Lh=(0,D.C)("El");D.wh.prototype.setTime=function(b){(0,D.lb)(this,"time",b)};D.wh.prototype.getTime=function(){return this.uj("time")};D.xh=function(b,c){(0,D.lb)(b,"newStartTime",c)};D.yh=function(b,c){(0,D.lb)(b,"newEndTime",c)};D.wh.prototype.Ug=function(b){(0,D.lb)(this,"pos",b)};D.wh.prototype.Kf=function(){return this.uj("pos")};
});