define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Zc=function(b,c,d){this.Init(b,c,d)};D.F.l(D.Zc,D.H,"DvtComboBox");D.Zc.prototype.Init=function(b,c,d){D.Zc.q.Init.call(this,b,D.r,c);this.D=d;this.LR=[];this.vb=[];this.Via=[];this.tn=0;this.HZ=this.aQ=D.u;this.K1=new D.I(0,0,0,0);this.Tc=new D.I(0,0,0,0);this.ZL=b.hd();this.$0=D.K.da();this.Kb=(0,D.$c)(this,c+"_cl");this.k(this.Kb);this.PJ=new D.H(b);this.PJ.la(D.u);this.k(this.PJ);this.J0=new D.Pc(b,100,this.Yoa,this,1);this.cha=new D.Pc(b,100,this.hpa,this,1);this.i0=D.u};
D.Zc.prototype.WV=function(b){this.tn=b;this.aQ||(0,D.ad)(this);b=new D.bd("cbItemChange",b,this.yg);this.yg=D.r;this.cc(b)};
D.$c=function(b,c){var d=b.e,e=b.e,f=b.C(),f=new D.cd(e,0,0,f.g,f.j,c+"_up");(0,D.dd)(f,D.M.hY);(0,D.ed)(f);f.k((0,D.fd)(e,f.getWidth(),f.getHeight()));var g=b.e,e=b.C(),e=new D.cd(g,0,0,e.g,e.j,c+"_up");e.Ma(D.M.$N);e.G(new D.gd(0,[D.M.G9,D.M.F9]));(0,D.dd)(e,D.M.hY);e.k((0,D.fd)(g,e.getWidth(),e.getHeight()));var g=b.e,h=b.C(),h=new D.cd(g,0,0,h.g,h.j,c+"_up");(0,D.dd)(h,D.M.hY);h.Ma(D.M.$N);h.G(new D.gd(0,[D.M.F9,D.M.G9]));h.k((0,D.fd)(g,h.getWidth(),h.getHeight()));d=new D.tc(d,f,e,h,D.r,c);(0,D.Mc)(d,
b.sI,b);d.setCursor("pointer");b.$0||d.P(D.wc,b.T9,D.u,b);d.AA=D.o;return d};D.E=D.Zc.prototype;D.E.ij=function(b,c,d,e,f){b.la(D.u);this.vb.push(b);this.Via.push(c);c=D.M.lm(this.e,d?d:b);var g=this.K1,h=this.C();c.g>g.g&&(g.g=c.g,h.g=c.g+16);c.j>g.j&&(g.j=c.j,h.j=c.j);this.K1=g;c=D.r;d&&(e&&f)&&(c=[],c[0]=d,c[1]=e,c[2]=f);this.LR.push(c);this.aQ||(this.removeChild(this.Kb),this.Kb=(0,D.$c)(this,b.getId()),this.Ha(this.Kb,0),(0,D.ad)(this))};D.E.getItem=function(b){return this.vb[b]};
D.E.s6=function(){var b=this.tn;return 0>b||b>this.vb.length-1?D.r:this.vb[b]};
D.E.sI=function(b){(0,D.Vc)(b);this.HZ&&(this.HZ=D.u,this.Gp&&(this.Gp.$a(D.u),this.Gp.getParent().removeChild(this.Gp),this.Gp=D.r));b=this.e;for(var c=this.D?this.D.comboBox:D.r,d=(0,D.id)(c,"paddingLeft",0),e=(0,D.id)(c,"paddingBottom",0),f=(0,D.id)(c,"paddingRight",0),g=(0,D.id)(c,"paddingInner",0),h=(0,D.id)(c,"paddingTop",0),k=this.e,m,p,q,t=new D.H(k,"__dd"),v=0;v<this.vb.length;v++)q=this.vb[v],m=D.M.lm(k,q),p=new D.H(k,"__it"+v),(0,D.Ya)(p,d,h),p.k(q),q.la(D.o),q.setCursor("pointer"),h+=
m.j+g,this.Ga&&(m=new D.Nc(this,this.Woa,this.T9,D.r,D.r,D.r,this.Via[v]),this.Ga.ma(q,m)),t.k(p);c=D.M.bBa(k,this.K1.g+d+f,h+e-g,c);c.k(t);t=(0,D.id)(this.D,"background-color",D.r);d=(0,D.id)(this.D,"backgroundAlpha",1);c.Ma((0,D.id)(this.D,"border-color",D.r),(0,D.id)(this.D,"borderAlpha",1));t&&c.na(t,d);this.Gp=c;c=D.M.lm(b,this.Gp);this.k(this.Gp);t=this.Kb.C();c=D.K.R(b)?-c.g+1*t.g/4:3*t.g/4;(0,D.Ya)(this.Gp,c,3*t.j/4);this.Kb.la(D.u);(0,D.jd)(this.Kb,D.o);this.cc(new D.bd("cbShowDropdown"));
(b=b.Ac)&&(this.$0?b.P(D.Ta.Rd,this.DO,D.o,this):b.P(D.Tc,this.DO,D.o,this))};D.E.Yoa=function(){(0,D.kd)(this);this.aQ||(0,D.ad)(this)};D.E.DO=function(){this.i0=D.u;this.cha.reset();this.cha.start()};D.E.hpa=function(){this.i0||(this.J0.reset(),this.J0.start())};D.E.T9=function(){(0,D.Vc)()};
D.E.Woa=function(b){this.i0=D.o;this.J0.stop();(0,D.Vc)(b);var c;c=b.target;for(var d,e;c;){if((e=c.getId())&&c instanceof D.H&&"__it"==e.substr(0,4)){d=c;break}c=c.getParent()}c=d;var f;this.Gp&&c&&(d=this.Gp.ca(0))&&(f=d.Ee(c));(0,D.kd)(this);this.yg=b;this.WV(f)};D.kd=function(b){b.Gp&&(b.Gp.$a(D.u),(0,D.jd)(b.Kb,D.u),b.cc(new D.bd("cbHideDropdown")),b.HZ=D.o);var c=b.e.Ac;c&&(b.$0?c.Pa(D.Ta.Rd,b.DO,D.o,b):c.Pa(D.Tc,b.DO,D.o,b));b.Kb.la(D.o)};D.Zc.prototype.C=(0,D.C)("Tc");
D.ad=function(b){var c=D.o,d=b.tn;if(b.LR&&b.LR.length>d&&(d=b.LR[d])&&2<d.length)(0,D.ld)(b.Kb,d[0]),(0,D.md)(b.Kb,d[1]),(0,D.pd)(b.Kb,d[2]),c=D.u;c&&(0<b.PJ.Aa()&&b.PJ.dp(0),b.PJ.k(b.s6()))};D.fd=function(b,c,d){var e=[];e.push(c-12,d/2-2);e.push(c-4,d/2-2);e.push(c-8,d/2+2);e.push(c-12,d/2-2);b=new D.vc(b,e,D.r);b.Ma(D.M.$N);b.na(D.M.$N);b.la(D.u);return b};D.Zc.prototype.QV=(0,D.B)("Ga");D.qd=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.l(D.qd,D.cd,"DropdownItemSprite");
D.qd.prototype.Init=function(b){D.cd.q.Init.call(this,b)};
D.bd=function(b,c,d){this.Init(b,c,d)};D.F.l(D.bd,D.rd,"DvtComboBoxEvent");D.bd.prototype.Init=function(b,c,d){D.bd.q.Init.call(this,"comboBoxEvent");c===D.n&&(c=-1);this.WH=b;this.hB=c;this.JE=d};D.bd.prototype.Fa=(0,D.C)("hB");
D.Lc=function(b,c,d){this.Init(b,c,d)};D.F.l(D.Lc,D.H,"DvtBaseControl");D.Lc.prototype.Init=function(b,c,d){D.Lc.q.Init.call(this,b);this.ba=c;this.e=b;this.ZL=b.hd();this.bb=d};D.Lc.prototype.hd=(0,D.C)("ZL");
D.Oc=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.Oc,D.Lc,"DvtZoomInButton");D.E=D.Oc.prototype;D.E.Init=function(b,c,d,e,f){D.Oc.q.Init.call(this,b,d,e);this.LZ=D.u;this.BT=new D.Pc(b,100,this.ypa,this);this.eC=new D.Pc(b,250,this.yX,this,1);this.ym=c;(0,D.Mc)(this.ym,this.wpa,this);this.Ga=f;b=new D.Nc(this,D.r,this.xpa,this.u$,this.u$,D.r,(0,D.Na)(this.bb,"CONTROL_PANEL_ZOOMIN"));this.Ga.ma(this.ym,b);this.k(this.ym)};
D.E.wpa=function(){if(!this.BT.Mg()){var b=this.ba.Fc(),b=(0,D.Qc)(this.ba,b),c=new D.ub(this.e,this.ba.Ta());this.ba.bk(b,D.n,D.n,c);c.play()}};D.E.xpa=function(){this.LZ=D.o;this.BT.stop();this.eC.stop();this.eC.start()};D.E.u$=function(){this.LZ&&(this.LZ=D.u,this.BT.stop(),this.eC.stop())};D.E.yX=function(){this.BT.start()};D.E.ypa=function(){var b=this.ba.Fc();this.ba.bk((0,D.Qc)(this.ba,b))};D.E.Pg=function(b){this.ym.setCursor(b?"pointer":D.r);this.ym.Pg(b);(0,D.Rc)(this.ym)};
D.sd=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.sd,D.Lc,"DvtZoomOutButton");D.E=D.sd.prototype;D.E.Init=function(b,c,d,e,f){D.sd.q.Init.call(this,b,d,e);this.MZ=D.u;this.CT=new D.Pc(b,100,this.Bpa,this);this.eC=new D.Pc(b,250,this.yX,this,1);this.zm=c;(0,D.Mc)(this.zm,this.zpa,this);this.Ga=f;b=new D.Nc(this,D.r,this.Apa,this.v$,this.v$,D.r,(0,D.Na)(this.bb,"CONTROL_PANEL_ZOOMOUT"));this.Ga.ma(this.zm,b);this.k(this.zm)};
D.E.zpa=function(){if(!this.CT.Mg()){var b=this.ba.Fc(),b=(0,D.td)(this.ba,b),c=new D.ub(this.e,this.ba.Ta());this.ba.bk(b,D.n,D.n,c);c.play()}};D.E.Apa=function(){this.MZ=D.o;this.CT.stop();this.eC.stop();this.eC.start()};D.E.v$=function(){this.MZ&&(this.MZ=D.u,this.CT.stop(),this.eC.stop())};D.E.yX=function(){this.CT.start()};D.E.Bpa=function(){var b=this.ba.Fc();this.ba.bk((0,D.td)(this.ba,b))};D.E.Pg=function(b){this.zm.setCursor(b?"pointer":D.r);this.zm.Pg(b);(0,D.Rc)(this.zm)};
D.Kc=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.Kc,D.Lc,"DvtZoomToFitButton");D.Kc.prototype.Init=function(b,c,d,e,f){D.Kc.q.Init.call(this,b,d,e);this.Yt=c;(0,D.Mc)(this.Yt,this.Cpa,this);this.Yt.setCursor("pointer");this.Ga=f;b=new D.Nc(this,D.r,D.r,D.r,D.r,D.r,(0,D.Na)(this.bb,"CONTROL_PANEL_ZOOMTOFIT"));this.Ga.ma(this.Yt,b);this.k(this.Yt)};D.Kc.prototype.Cpa=function(){var b=new D.ub(this.e,this.ba.Ta());this.ba.Yk(b);b.play()};
D.Sc=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.l(D.Sc,D.Lc,"DvtPanControl");D.E=D.Sc.prototype;
D.E.Init=function(b,c,d,e,f,g,h){D.Sc.q.Init.call(this,b,e,f);this.kha=new D.Pc(b,50,this.rpa,this);this.vJ=D.u;this.BS=new D.R(20,20);this.qo=g?g:16777215;c.k(d);d&&(this.Ek=d,this.Ek.$a(D.u),this.Ek.P(D.Ta.Rd,this.c$,D.u,this),D.K.da()||(this.Ek.P(D.Ua,this.c$,D.u,this),this.Ek.P(D.wc,this.ipa,D.u,this),this.Ek.P(D.Tc,this.mpa,D.u,this),this.Ek.P(D.Va,this.lpa,D.u,this),this.Ek.P(D.Wa,this.kpa,D.u,this)),this.Ek.P(D.Uc,this.jpa,D.u,this));this.qn=c;this.qn.P(D.Ta.Rd,this.d$,D.u,this);D.K.da()||
(this.qn.P(D.Ua,this.d$,D.u,this),this.qn.P(D.wc,this.npa,D.u,this),this.qn.P(D.Tc,this.e$,D.u,this),this.qn.P(D.Va,this.qpa,D.u,this),this.qn.P(D.Wa,this.ppa,D.u,this),this.qn.P(D.Uc,this.opa,D.u,this));this.Jt=D.M.KAa(b,h);this.Jt.k(this.qn);this.k(this.Jt)};D.E.d$=function(b){(0,D.Vc)(b)};D.E.npa=function(b){(0,D.Vc)(b);this.vJ=D.o;this.Ek&&this.Ek.$a(D.u);b=(0,D.Wc)(this.ba,b);b=this.qn.Hb(b);(0,D.Yc)(this,b.x,b.y,this.qn.Jg);this.E2=new D.R(b.x,b.y);this.kha.start();this.lha=0};
D.E.e$=function(b){this.vJ&&((0,D.Vc)(b),this.vJ=D.u,this.Ek&&this.Ek.$a(D.o),this.kha.stop());this.qn.Fr(b);this.hd().oc()};D.E.qpa=function(b){this.Ek&&this.Ek.$a(D.o);var c=(0,D.Na)(this.bb,"CONTROL_PANEL_PAN");this.hd().UH(b.pageX,b.pageY,c,b.target)};D.E.ppa=function(b){this.e$(b);this.Ek&&this.Ek.$a(D.u)};D.E.opa=function(b){(0,D.Vc)(b);b=(0,D.Wc)(this.ba,b);b=this.qn.Hb(b);this.vJ?((0,D.Yc)(this,b.x,b.y,this.qn.Jg),this.E2=new D.R(b.x,b.y)):(0,D.Yc)(this,b.x,b.y,this.qn.oh)};
D.E.rpa=function(){if(this.vJ){var b=window.Math.atan2(this.BS.y-this.E2.y,this.BS.x-this.E2.x),c=window.Math.cos(b),b=window.Math.sin(b),d=15;this.lha++;40<this.lha&&(d*=3);this.ba.Kq(d*c,d*b)}};D.E.c$=function(b){(0,D.Vc)(b);this.ba.aW()};D.E.ipa=function(b){(0,D.Vc)(b)};D.E.mpa=function(b){(0,D.Vc)(b);this.hd().oc()};D.E.lpa=function(b){var c=(0,D.Na)(this.bb,"CONTROL_PANEL_ZOOMANDCENTER");this.hd().UH(b.pageX,b.pageY,c,b.target);this.Ek.$a(D.o);(0,D.Vc)(b)};
D.E.kpa=function(b){this.hd().oc();(0,D.Vc)(b)};D.E.jpa=function(b){(0,D.Vc)(b)};D.Yc=function(b,c,d,e){e.Oi(window.Math.atan2(d-b.BS.y,c-b.BS.x)-window.Math.PI/4)};
D.Ic=function(b){this.Init("dvtPZCPExpand");this.xl=b};D.F.l(D.Ic,D.Jc,"DvtControlPanelEvent");D.Ic.prototype.hi=(0,D.C)("xl");
D.ud=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.l(D.ud,D.H,"DvtControlPanel");D.wd=[0,0.25,0.5,0.75,1];
D.ud.prototype.Init=function(b,c,d,e,f,g){D.ud.q.Init.call(this,b,D.r,"_controlPanel");this.FZ=this.XP=D.u;this.ba=c;this.ZL=b.hd();this.bb=e;this.qo=f==D.r?16777215:f;this.D=D.r;if(this.I=g)this.D=this.I.$r(),this.D.centerButtonDisplayed||(this.qo&=-17,this.I.Xi=this.qo);this.bAa=D.wd;this.vd=1;this.Ym=D.u;this.Gj=d;this.Fj=this.D.backgroundAlpha;this.Ga=new D.xd(b,D.r,g);this.Ga.Nt.push(D.ud);this.Ga.$e(this);this.Ga.ma(this,this);b=(0,D.yd)(this);this.fb.B(this.Fj);this.qd.B(this.D.borderAlpha);
this.k(b);this.dLa=D.u;(0,D.kc)(this)};D.ud.prototype.RH=function(b){this.vd!=b&&(this.UN(),this.vd=b,(0,D.zd)(this))};D.ud.prototype.hd=(0,D.C)("ZL");D.Ad=function(b){b.XP=D.o;b.fb.la(D.u);b.qd.la(D.u);b.fb.B(b.D.backgroundDragAlpha);b.qd.B(b.D.borderDragAlpha)};D.Bd=function(b){b.XP=D.u;b.fb.la(D.o);b.qd.la(D.o);b.FZ?b.Bj(D.r):b.Ri(D.r)};D.ud.prototype.qH=(0,D.ca)(D.o);D.ud.prototype.Wo=function(){var b=0,b=this.qH()?D.Sa.LU():D.Sa.Wo();return window.Math.max((0,D.id)(this.D,"tabSize",0),b)};
D.yd=function(b){var c=b.e,d=new D.H(c),e=b.Wo(),f=D.K.R(c);b.fb=D.Sa.Fja(c,e,b.D,f);b.qd=D.Sa.V4(c,e,b.D,f);b.hua=D.M.lm(c,b.qd);b.Mc=D.M.QT(b.e,b.Gj,b.Wo(),b.D,f);(0,D.Mc)(b.Mc,b.sI,b);b.Mc.setCursor("pointer");c=new D.Nc(b,D.r,D.r,D.r,D.r,D.r,(0,D.Na)(b.bb,"CONTROL_PANEL"));b.Ga.ma(b.Mc,c);b.qd.k(b.Mc);d.k(b.fb);d.k(b.qd);return d};D.ud.prototype.II=(0,D.z)();D.ud.prototype.UN=function(){this.Ym||(2===this.vd?this.OA():1===this.vd&&this.fK())};
D.ud.prototype.sI=function(b){(0,D.Vc)(b);this.Ym||(this.fK(),this.hd()&&this.hd().oc())};
D.ud.prototype.fK=function(){this.Ym=D.o;this.la(D.u);var b=this.e,c=new D.H(b);this.fb=new D.H(b);this.qd=new D.H(b);c.k(this.fb);c.k(this.qd);var d=D.K.R(b),e=0,f=new D.H(b),g;g=0;var h=this.e,k=this.qH();0!=(this.qo&16)&&(this.Jt=D.M.LAa(h,this.ba,this.bb,this.qo,this.Gj,this.D),k&&(this.aw=D.M.Kja(h,this.D),this.pL=D.M.Kja(h,this.D),f.k(this.pL),f.k(this.aw)),f.k(this.Jt),g++);this.vi=D.M.OT(this.e,this.Gj,this.Wo(),this.D,D.K.R(this.e));(0,D.Mc)(this.vi,this.hX,this);this.vi.setCursor("pointer");
h=new D.Nc(this,D.r,D.r,D.r,D.r,D.r,(0,D.Na)(this.bb,"CONTROL_PANEL"));this.Ga.ma(this.vi,h);f.k(this.vi);this.ar=new D.H(this.e);this.II(this.ar);0<this.ar.Aa()?(f.k(this.ar),g++):this.ar=D.r;var h=e,e=this.e,m=D.r,k=(0,D.id)(this.D,"openCloseButtonWidth",0),p=(0,D.id)(this.D,"buttonWidth",0),q=(0,D.id)(this.D,"tabSize",0),t=this.Wo(),v=(0,D.id)(this.D.hbar,"paddingLeft",0),w=(0,D.id)(this.D.hbar,"paddingInner",0);d?(this.vi.F(0),h+=k,this.ar&&(m=D.M.lm(e,this.ar),h+=w,(0,D.Ya)(this.ar,h,(t-m.j)/
2),h+=window.Math.max(m.g,p)),this.Jt&&(h+=w,m=3.5,(0,D.Ya)(this.Jt,h,m),this.aw&&(0,D.Ya)(this.aw,h,m),this.pL&&(0,D.Ya)(this.pL,h,m),m=D.M.lm(e,this.Jt),h+=m.g),h+=v):(this.Jt&&(h+=v,m=3.5,(0,D.Ya)(this.Jt,v,m),this.aw&&(0,D.Ya)(this.aw,v,m),this.pL&&(0,D.Ya)(this.pL,v,m),m=D.M.lm(e,this.Jt),h+=w+m.g,h+=1),this.ar&&(m=D.M.lm(e,this.ar),0==h&&(h+=v),(0,D.Ya)(this.ar,h,(t-m.j)/2),h+=m.g,h=window.Math.max(h+w,q)),this.vi.F(h),h+=k);e=h;h=D.r;k=this.qo&16||this.D&&this.D.panelDrawerStyles&&0==g?(0,D.id)(this.D.vbar,
"paddingTop",0):0;this.qH()&&0!=(this.qo&16)&&(k+=D.Sa.Wo()-this.Wo());if(0!=(this.qo&256)||0!=(this.qo&4097))h=new D.H(b),h.O(f.K()+this.Wo()),q=h,0!=(this.qo&256)&&(t=(0,D.id)(this.D.vbar,"paddingInner",0),v=(0,D.id)(this.D.vbar,"paddingLeft",0),this.Yt=D.M.XAa(this.e,this.ba,this.bb,this.Ga,this.Gj,this.D),(0,D.Ya)(this.Yt,v,this.Yt.K()+k),v=D.M.lm(this.e,this.Yt),q.k(this.Yt),k+=v.j,k+=t),q=h,t=D.r,v=(0,D.id)(this.D.vbar,"paddingInner",0),w=(0,D.id)(this.D.vbar,"paddingLeft",0),0!=(this.qo&4097)&&
(this.ym=D.M.VAa(this.e,this.ba,this.bb,this.Ga,this.Gj,this.D),(0,D.Ya)(this.ym,w,this.ym.K()+k),t=D.M.lm(this.e,this.ym),q.k(this.ym),k+=t.j+v,this.zm=D.M.WAa(this.e,this.ba,this.bb,this.Ga,this.Gj,this.D),(0,D.Ya)(this.zm,w,this.zm.K()+k),t=D.M.lm(this.e,this.zm),q.k(this.zm),k+=t.j,q=this.ba.Fc(),t=(0,D.Qc)(this.ba,q),v=(0,D.td)(this.ba,q),this.ym&&this.ym.Pg(q!=t),this.zm&&this.zm.Pg(q!=v)),this.qd.k(h);var q=h,t=g,v=this.e,A=(0,D.id)(this.D,"openCloseButtonWidth",0),w=(0,D.id)(this.D,"tabSize",
0),p=(m=(0,D.id)(this.D,"panelDrawerStyles",D.r))?e:e-A,D$=this.Wo(),J=0,e=0;m?m&&0==t&&(e=d?-w:w):(J=d?A:0,e=d?A:0);if(0<t||m)A=D.r,A=(0,window.parseInt)((0,D.id)(this.D,"border-radius",0)),A=m?D.Sa.NEa(v,A,p,D$,0<t&&q!=D.r?D.Sa.HX:D.Sa.IX,w):D.Sa.Cma(v,A,p-2*A,D$-2*A,!d),A.Ma((0,D.id)(this.D,"border-color",D.r)),A.G(D.r),A.F(f.M()+J),f.Ha(A,0),d=D.Sa.GAa(v,p,this.Wo(),!d,this.D),(0,D.Ya)(d,f.M()+e,f.K()),this.fb.k(d);this.qd.k(f);d=h;e=this.e;q=D.K.R(e);t=(0,D.id)(this.D,"openCloseButtonWidth",
0);!this.ar&&0==(this.qo&16)?q?(f.F(0-f.M()),f.O(0),d&&(D.M.lm(e,d),f.F(f.M()-t),d.O(0))):d?(e=(0,D.id)(this.D,"tabSize",0),(0,D.Ya)(d,0,0),(0,D.Ya)(f,f.M()+e,0)):(0,D.Ya)(f,f.M(),0):q&&d&&(e=D.M.lm(e,f),q=(0,D.id)(this.D,"tabSize",0),f.F(0),d.F(e.g+e.x-q));d=h;q=k;h=this.e;d&&(e=d.Aa(),e=1<e||this.Yt==D.r||1<g||0<g&&1==e,k=D.r,this.D&&this.D.panelDrawerStyles&&(k=0<g?D.Sa.KX:D.Sa.JX),f=D.M.lm(h,f),q+=4,g=e?q:window.Math.max(f.j,q),g+=(0,D.id)(this.D.vbar,"paddingBottom",0),f=D.Sa.xFa(h,g,this.D,
k,this.Wo()),g=D.Sa.wFa(h,g,e,this.D,k,this.Wo()),(0,D.Ya)(f,d.M(),d.K()),this.fb.k(f),d.Ha(g,0));this.gva=D.M.lm(b,c);this.k(c);(0,D.Dd)(this);var G=this.ca(0),b=G.C(),f=(0,D.id)(this.D,"openCloseButtonWidth",0);b&&0!=b.g?(g=c.C(),d=new D.ub(this.e,0.25),G.B(1),c.B(0),(0,D.N)(d,"typeNumber",G,G.Z,G.B,0),(0,D.N)(d,"typeNumber",c,c.Z,c.B,1),c.Ad(b.g/g.g),(0,D.N)(d,"typeNumber",c,c.Rb,c.Ad,1),D.K.R(this.e)&&(c.F(G.M()),h=g.g+g.x,(0,D.N)(d,"typeNumber",c,c.M,c.F,G.M()+f-h)),c.Hd(b.j/g.j),(0,D.N)(d,"typeNumber",
c,c.Ub,c.Hd,1),d.zd(function(){G.getParent().removeChild(G);this.Ym=D.u;this.la(D.o)},this),d.play()):(G.getParent().removeChild(G),D.K.R(this.e)?(g=(0,D.Ed)(this.e,c),h=window.Math.floor(g.g+g.x),b=f-h):b=0,(0,D.Ya)(c,b,0));this.vd=2;c=new D.Ic("show");this.cc(c)};D.Dd=function(b){var c=D.u;b.e.Ac&&(c=D.o);c?(0,D.Fd)(b):(0,D.zd)(b)};D.ud.prototype.hX=function(b){(0,D.Vc)(b);this.Ym||this.OA()};
D.ud.prototype.OA=function(){this.Ym=D.o;var b=(0,D.yd)(this);this.k(b);(0,D.Dd)(this);var c=this.ca(0),d=new D.ub(this.e,0.25);c.B(1);b.B(0);(0,D.N)(d,"typeNumber",c,c.Z,c.B,0);(0,D.N)(d,"typeNumber",b,b.Z,b.B,1);var e=this.hua,f=this.gva;(0,D.N)(d,"typeNumber",c,c.Rb,c.Ad,e.g/f.g);D.K.R(this.e)&&(0,D.N)(d,"typeNumber",c,c.M,c.F,b.M());(0,D.N)(d,"typeNumber",c,c.Ub,c.Hd,e.j/f.j);d.zd(function(){c.getParent().removeChild(c);this.Ym=D.u},this);d.play();this.vd=1;b=new D.Ic("hide");this.cc(b)};
D.ud.prototype.Bj=function(){this.FZ=D.o;this.XP||(0,D.Fd)(this)};D.ud.prototype.Ri=function(){this.FZ=D.u;this.XP||(0,D.zd)(this)};D.Fd=function(b){b.fb.B(b.D.backgroundHoverAlpha);b.qd.B(b.D.borderHoverAlpha);b.aw&&b.aw.B(b.D.backgroundHoverAlpha)};D.zd=function(b){b.fb.B(b.Fj);b.qd.B(b.D.borderAlpha);b.aw&&b.aw.B(b.Fj)};D.ud.prototype.C=function(){this.Tc||(this.Tc=D.ud.q.C.call(this));return this.Tc};D.ud.prototype.Ni=(0,D.z)();D.ud.prototype.wq=(0,D.C)("Gj");D.Gd=function(b,c){b.ym&&b.ym.Pg(c)};
D.Hd=function(b,c){b.zm&&b.zm.Pg(c)};
D.Mv={};D.F.l(D.Mv,D.F,"DvtControlPanelDefaults");
D.Mv.qY={"fill-type":"solid",backgroundAlpha:1,backgroundDragAlpha:1,borderDragAlpha:1,panelDrawerStyles:D.o,buttonWidth:42,buttonHeight:42,buttonRadius:0,openCloseButtonWidth:42,tabSize:42,paddingTop:15,paddingSide:-1,imageWidth:24,imageHeight:24,centerButtonDisplayed:D.u,scrollbarBackground:"linear-gradient(bottom, #dce2e7 0%, #f8f8f8 8%)",scrollbarBorderColor:"#dce2e7",scrollbarHandleColor:"#abb0b4",scrollbarHandleHoverColor:"#333333",scrollbarHandleActiveColor:"#333333",comboBox:{paddingTop:0,
paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0,itemHeight:30,imagePadding:0,itemPadding:10},vbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0},hbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0}};D.Mv.rY={"fill-type":"solid"};
D.Mv.Rz={"fill-type":"gradient","border-color":"#ffffff","background-color":"#ffffff","border-radius":6,backgroundAlpha:0.5,backgroundHoverAlpha:1,backgroundDragAlpha:0.5,borderAlpha:1,borderHoverAlpha:1,borderDragAlpha:0.5,tabSize:26,buttonWidth:22,buttonHeight:22,buttonRadius:3,paddingTop:5,paddingSide:5,imageWidth:22,imageHeight:20,openCloseButtonWidth:10,centerButtonDisplayed:D.o,comboBox:{paddingTop:2,paddingBottom:6,paddingLeft:3,paddingRight:3,paddingInner:2,itemHeight:22,radius:4,imagePadding:2,
itemPadding:7},vbar:{paddingTop:2.5,paddingBottom:2.5,paddingLeft:2,paddingRight:2,paddingInner:2},hbar:{paddingTop:2,paddingBottom:2,paddingLeft:3,paddingRight:3,paddingInner:2}};D.Mv.pg=function(b){var c=D.Mv.$A(b);return b?D.xa.zb(b,c):c};D.Mv.$A=function(b){var c=D.r;return c=b&&"skyros"===b.skin?D.xa.zb(D.Mv.rY,D.Mv.Rz):b&&"alta"===b.skin?D.xa.zb(D.Mv.qY,D.Mv.Rz):D.xa.clone(D.Mv.Rz)};
D.xd=function(b,c,d){this.Init(b,c,d)};D.F.l(D.xd,D.Bc,"DvtControlPanelEventManager");D.E=D.xd.prototype;D.E.bl=function(b){var c=(0,D.Dc)(this,(0,D.um)(this,b));D.xd.q.bl.call(this,b);c&&(c.Vn&&c.Vn(b),b.stopPropagation())};D.E.Tm=function(b){var c=(0,D.Dc)(this,(0,D.um)(this,b));D.xd.q.Tm.call(this,b);c&&(c.Wn&&c.Wn(b),b.stopPropagation())};D.E.dk=function(b){var c=(0,D.Dc)(this,(0,D.um)(this,b));D.xd.q.dk.call(this,b);c&&(c.FD&&c.FD(b),b.stopPropagation())};
D.E.Sm=function(b){var c=(0,D.Dc)(this,(0,D.um)(this,b));D.xd.q.Sm.call(this,b);c&&(c.Nu&&c.Nu(b),b.stopPropagation())};D.E.Vg=function(b){var c=(0,D.Dc)(this,(0,D.um)(this,b));D.xd.q.Vg.call(this,b);c&&(c.Rc&&c.Rc(b),b.stopPropagation())};D.E.Su=function(b){D.xd.q.Su.call(this,b);var c=(0,D.Dc)(this,(0,D.um)(this,b));c&&c.Bj&&c.Bj(b)};D.E.Ru=function(b){D.xd.q.Ru.call(this,b);var c=(0,D.Dc)(this,(0,D.um)(this,b));c&&c.Ri&&c.Ri(b)};
D.E.Ns=function(b){var c=(0,D.Dc)(this,(0,D.um)(this,b));c&&(c.Rc&&c.Rc(b),b.stopPropagation())};D.E.ED=function(b){b.Wr();(0,D.Vc)(b)};
D.Nc=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.l(D.Nc,D.F,"DvtControlPanelEventHandlerProxy");D.E=D.Nc.prototype;D.E.Init=function(b,c,d,e,f,g,h){this.ka=b;this.iy=c;this.Cea=e;this.kR=d;this.lR=f;this.mR=g;this.Pe=h};D.E.Rc=function(b){this.iy&&this.iy.call(this.ka,b)};D.E.Vn=function(b){this.kR&&this.kR.call(this.ka,b)};D.E.Wn=function(b){this.Cea&&this.Cea.call(this.ka,b)};D.E.FD=function(b){this.lR&&this.lR.call(this.ka,b)};D.E.zO=function(b){this.mR&&this.mR.call(this.ka,b)};
D.E.ee=(0,D.C)("Pe");
D.Sa={};D.F.l(D.Sa,D.F,"DvtControlPanelLAFUtils");D.Sa.KX="top";D.Sa.JX="right";D.Sa.IX="left";D.Sa.HX="bottom";D.Sa.Kaa=47;D.Sa.Jaa=26;D.Sa.Bd=window.Math.sin(window.Math.PI/4);D.Sa.Cd=window.Math.tan(window.Math.PI/8);D.Sa.Wo=function(){return D.Sa.Kaa};D.Sa.LU=function(){return D.Sa.Jaa};D.Sa.GAa=function(b,c,d,e,f){c||(c=86);d||(d=47);e===D.n&&(e=D.o);var g=(0,window.parseInt)((0,D.id)(f,"border-radius",0));b=D.Sa.Cma(b,g,c-2*g,d-2*g,e);b.na((0,D.id)(f,"background-color",D.r));return b};
D.Sa.Cma=function(b,c,d,e,f){var g=d+c,h=e+c,k=window.DvtPathUtils.moveTo(g+c,h+c),k=k+window.DvtPathUtils.lineTo(g-d,h+c),g=g-d,k=k+window.DvtPathUtils.lineTo(g-c,h+c),k=k+window.DvtPathUtils.lineTo(g-c,h-e),h=h-e;f?(k+=window.DvtPathUtils.Zb(-c+g,-D.Sa.Cd*c+h,-D.Sa.Bd*c+g,-D.Sa.Bd*c+h)+window.DvtPathUtils.Zb(-D.Sa.Cd*c+g,-c+h,g,-c+h)+window.DvtPathUtils.lineTo(g,-c+h),k+=window.DvtPathUtils.lineTo(g+d+c,-c+h),k+=window.DvtPathUtils.lineTo(g+d+c,h+e)):(k+=window.DvtPathUtils.lineTo(g-c,-c+h),k+=
window.DvtPathUtils.lineTo(g+d,-c+h),g+=d,k+=window.DvtPathUtils.Zb(D.Sa.Cd*c+g,-c+h,D.Sa.Bd*c+g,-D.Sa.Bd*c+h)+window.DvtPathUtils.Zb(c+g,-D.Sa.Cd*c+h,c+g,h)+window.DvtPathUtils.lineTo(g+c,h+e));k+=window.DvtPathUtils.closePath();return new D.Ra(b,k)};
D.Sa.Fja=function(b,c,d,e){c||(c=47);var f=(0,window.parseInt)((0,D.id)(d,"border-radius",0)),g=(0,D.id)(d,"openCloseButtonWidth",0);c=window.Math.max(c,(0,D.id)(d,"buttonHeight",c));e=D.M.VW(g,c,f,e);e=e.concat("Z");b=new D.Ra(b,e,"cls_shape");(e=(0,D.id)(d,"tab-color-inactive",D.r))||(e=(0,D.id)(d,"background-color",D.r));b.na(e);return b};
D.Sa.V4=function(b,c,d,e){c||(c=47);var f=(0,window.parseInt)((0,D.id)(d,"border-radius",0)),g=(0,D.id)(d,"openCloseButtonWidth",0);c=window.Math.max(c,(0,D.id)(d,"buttonHeight",c));e=D.M.VW(g,c,f,e);e=e.concat("Z");b=new D.Ra(b,e,"cls_shape");b.Ma((0,D.id)(d,"border-color",D.r));b.G(D.r);return b};
D.Sa.xFa=function(b,c,d,e,f){c||(c=137);var g=(0,window.parseInt)((0,D.id)(d,"border-radius",0)),h=(0,D.id)(d,"tabSize",0),k=h-2*g,m=c+7-2*g;b=e&&f?D.Sa.Ema(b,g,h,c,e,f):D.Sa.Dma(b,g,k,m);b.na((0,D.id)(d,"background-color",D.r));return b};D.Sa.wFa=function(b,c,d,e,f,g){c||(c=137);d||(d=D.o);var h=(0,window.parseInt)((0,D.id)(e,"border-radius",0)),k=(0,D.id)(e,"tabSize",0),m=k-2*h,p=c+7-2*h,q=D.r,q=f&&g?D.Sa.Ema(b,h,k,c,f,g):D.Sa.Dma(b,h,m,p,d);q.Ma((0,D.id)(e,"border-color",D.r));q.G(D.r);return q};
D.Sa.Dma=function(b,c,d,e,f){f||(f=D.o);var g=d+c,h=e,k=window.DvtPathUtils.moveTo(g+c,h),k=f?k+(window.DvtPathUtils.Zb(c+g,D.Sa.Cd*c+h,D.Sa.Bd*c+g,D.Sa.Bd*c+h)+window.DvtPathUtils.Zb(D.Sa.Cd*c+g,c+h,g,c+h)+window.DvtPathUtils.lineTo(g,c+h)):k+window.DvtPathUtils.lineTo(g+c,h+c),k=k+window.DvtPathUtils.lineTo(g-d,c+h),g=g-d,k=k+(window.DvtPathUtils.Zb(-D.Sa.Cd*c+g,c+h,-D.Sa.Bd*c+g,D.Sa.Bd*c+h)+window.DvtPathUtils.Zb(-c+g,D.Sa.Cd*c+h,-c+g,h)+window.DvtPathUtils.lineTo(-c+g,h)+window.DvtPathUtils.lineTo(-c+
g,h-e)),h=h-e,k=k+(window.DvtPathUtils.lineTo(g+d+c,h)+window.DvtPathUtils.lineTo(g+d+c,h+e)+window.DvtPathUtils.closePath());return new D.Ra(b,k)};D.Sa.Ema=function(b,c,d,e,f,g){c=D.Sa.Q9(d,e,c,f,g);return new D.Ra(b,c)};D.Sa.NEa=function(b,c,d,e,f,g){c=D.Sa.Q9(d,e,c,f,g);return new D.Ra(b,c)};
D.Sa.Q9=function(b,c,d,e,f){var g,h=D.K.R();e==D.Sa.KX&&!h&&(g=["M",b,0,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c,"L",0,0]);e==D.Sa.KX&&h?g=["M",b,0,"L",b,c,"L",d,c,"A",d,d,0,0,1,0,c-d,"L",0,0]:e==D.Sa.JX&&!h?g=["M",b,f,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c,"L",0,0,"L",b,0]:e==D.Sa.JX&&h?g=["M",0,0,"L",b,0,"L",b,c,"L",d,c,"A",d,d,0,0,1,0,c-d,"L",0,f]:e==D.Sa.IX&&!h?g=["M",0,0,"L",b-d,0,"A",d,d,0,0,1,b,d,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c]:e==D.Sa.IX&&h?g=["M",b,c,"L",d,c,"A",d,d,0,0,1,0,c-d,"L",0,
d,"A",d,d,0,0,1,d,0,"L",b,0]:e==D.Sa.HX&&!h?g=["M",0,c,"L",0,0,"L",b-d,0,"A",d,d,0,0,1,b,d,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",f,c]:e==D.Sa.HX&&h&&(g=["M",b,c,"L",b,0,"L",d,0,"A",d,d,0,0,0,0,d,"L",0,c-d,"A",d,d,0,0,0,d,c,"L",b-f,c]);return g};
D.Nv=function(b){this.Init(b)};(0,D.ta)("DvtAbstractComponent",D.Nv);D.F.l(D.Nv,D.H,"DvtAbstractComponent");D.E=D.Nv.prototype;D.E.Init=function(b){D.Nv.q.Init.call(this,b);this.po=new D.cd(b,0,0,0,0);this.k(this.po);this.WR=this.x_=this.OJ=this.i3=D.r;this.Tb="";this.Zs=D.u;this.qe=!D.K.Md()&&!(D.K.nh()&&17>=D.K.Gw())};D.E.Ni=function(){this.Pu();this.dl()};D.E.Pu=function(){this.$ba=D.u};D.E.dl=function(){this.$ba||this.RO();this.$ba=D.o};
D.E.cN=function(b,c,d,e){var f=new D.jl;if(f&&(b=f.parse(b)))if("r"===b.getName()&&(b=b.getFirstChild()),b)switch(c){default:this.DX(c,b,d,e)}};D.E.i7=function(b,c,d,e){if(b)switch(c){default:this.L$(c,b,d,e)}};D.E.DX=(0,D.z)();D.E.L$=(0,D.z)();D.E.L=function(b,c,d){this.Q=c;this.W=d;this.po.ia(this.Q);this.po.va(this.W);b?b=this.gY(b):this.Zs=D.o;this.cN(b);this.Ni();this.Zs=D.u};D.Nv.prototype.render=D.Nv.prototype.L;
D.Nv.prototype.AFa=function(b,c,d){this.Q=c;this.W=d;this.po.ia(this.Q);this.po.va(this.W);b?b=this.gY(b):this.Zs=D.o;this.i7(b);this.Ni();this.Zs=D.u};D.Nv.prototype.renderJson=D.Nv.prototype.AFa;D.Nv.prototype.RO=function(){if(this.OJ){var b;var c=this.OJ;c?(b=c.v("fill-type"),(c=c.v("background-color"))||(c="#7396C8"),b="solid"==b?new D.Ud(c):(0,D.Zv)(this,c)):b=D.n;b&&this.po.G(b)}else"none"!=this.yp?(b=(0,D.Zv)(this,this.yp),this.po.G(b)):(0,D.ed)(this.po)};
D.Zv=function(b,c){var d,e=1;if(c&&"#7396C8"!=c){e=D.S.Z(c);d=(D.S.gd("#AECDEA")-D.S.gd("#7396C8"))/(255-D.S.gd("#7396C8"));var f=(D.S.fd("#AECDEA")-D.S.fd("#7396C8"))/(255-D.S.fd("#7396C8")),g=(D.S.dd("#AECDEA")-D.S.dd("#7396C8"))/(255-D.S.dd("#7396C8")),h=D.S.gd(c),k=D.S.fd(c),m=D.S.dd(c);d=D.S.Ow(window.Math.round(h+d*(255-h)),window.Math.round(k+f*(255-k)),window.Math.round(m+g*(255-m)));f=D.S.Ei(c);d=["#FFFFFF","#FFFFFF",d,f]}else d=["#FFFFFF","#FFFFFF","#AECDEA","#7396C8"];var e=[e,e,e,e],f=
[0,45/255,190/255,1],k=b.Q,g=1.7*1.7*k,h=1.7*b.W,k=0+(k-g)/2,m=k+g/2,p=-35+h/2,q=1.5*window.Math.min(g/2,h/2);return new D.cg(d,e,f,m,p,q,[k,-35,g,h])};D.Ka=function(b){b.i3||(b.i3=b.X?b.X.resources:{});return b.i3};D.Nv.prototype.Wk=(0,D.B)("Tb");D.Nv.prototype.$r=(0,D.C)("x_");
D.ov=function(b,c){var d;d=(0,D.$v)(c.o("skinStyle"),D.r);if(d=(0,D.$v)(c.o("inlineStyle"),d))b.OJ=d;var e={};if(d=c.o("skin"))b.Wk(d),e.skin=d;(0,D.Yl)(e,"background-color",c.o("cpBackgroundColor"));(0,D.Yl)(e,"border-color",c.o("cpBorderColor"));(0,D.Yl)(e,"border-radius",c.o("cpBorderRadius"));(0,D.Yl)(e,"box-shadow",c.o("cpBoxShadow"));(0,D.Yl)(e,"tab-color-inactive",c.o("tabBgColorInactive"));(0,D.Yl)(e,"tab-border-color-inactive",c.o("tabBorderColorInactive"));(0,D.Yl)(e,"scrollbarBackground",
c.o("scrollbarBg"));(0,D.Yl)(e,"scrollbarBorderColor",c.o("scrollbarBorderColor"));(0,D.Yl)(e,"scrollbarHandleColor",c.o("scrollbarHandleColor"));(0,D.Yl)(e,"scrollbarHandleActiveColor",c.o("scrollbarHandleActiveColor"));(0,D.Yl)(e,"scrollbarHandleHoverColor",c.o("scrollbarHandleHoverColor"));e=D.Mv.pg(e);b.x_=e;e={};d&&(e.skin=d);d=D.Hc.pg(e);b.WR=d};D.$v=function(b,c){b&&(c?c.zb(new D.P(b)):c=new D.P(b));return c};D.Nv.prototype.gY=(0,D.ba)();D.Nv.prototype.Yd=(0,D.B)("X");
D.Aa=function(b){this.Init(b)};(0,D.ta)("DvtAbstractPanZoomComponent",D.Aa);D.F.l(D.Aa,D.Nv,"DvtAbstractPanZoomComponent");D.E=D.Aa.prototype;D.E.Init=function(b){D.Aa.q.Init.call(this,b);this.wh=0;this.qv="initCollapsed";this.Xi=16777215};D.E.Pu=function(){D.Aa.q.Pu.call(this);if(this.Zs)this.ba.$j(this.Q,this.W);else{this.ba&&(this.removeChild(this.ba),this.ba=D.r);this.ba=this.Qz(this.Q,this.W);this.ba.Ni();var b=this.ba.dc;b&&b.P("dvtPZCPExpand",this.rI,D.u,this)}this.WO(this.Q,this.W)};
D.E.Qz=function(b,c){var d=this.e,e=(0,D.Ka)(this),f;a:switch(this.qv){case "initCollapsed":f=0;break a;case "initExpanded":f=1;break a;default:f=2}d=new D.Ov(d,e,b,c,D.r,f,this.bb,this.Xi,this);d.P("dvtPan",this.Hs,D.u,this);d.P("dvtZoom",this.Yf,D.u,this);this.Ha(d,1);return d};D.E.rI=(0,D.z)();D.E.Hs=(0,D.z)();D.E.Yf=(0,D.z)();D.Pv=function(b){return b.ba};D.E=D.Aa.prototype;D.E.Kq=function(b,c,d){this.ba.Kq(b,c,d)};D.E.cp=function(b,c,d){this.ba.cp(b,c,d)};
D.E.bW=function(b,c,d,e){this.ba.bW(b,c,d,e)};D.E.bk=function(b,c,d,e){this.ba.bk(b,c,d,e)};D.E.Yk=function(b){this.ba.Yk(b)};D.E.Hz=(0,D.B)("wh");D.E.QU=(0,D.ca)(D.o);D.E.jEa=function(){return this.ba.xp&&0==(this.wh&2)};D.Aa.prototype.isMouseWheelHandled=D.Aa.prototype.jEa;D.Aa.prototype.WO=function(b,c){var d=new D.Sg("comp");(0,D.Tg)(d,this.M(),this.K(),b,c);(0,D.tf)(this,d)};
D.Ov=function(b,c,d,e,f,g,h,k,m){this.Init(b,c,d,e,f,g,h,k,m)};D.F.l(D.Ov,D.H,"DvtPanZoomCanvas");
D.Ov.prototype.Init=function(b,c,d,e,f,g,h,k,m){D.Ov.q.Init.call(this,b,D.r,f);this.I=m;this.ng=d;this.Ag=e;this.Gj=c;this.Ct=this.Bt=this.Py=this.NF=0;this.$p=this.bq=this.Zp=this.aq=D.r;this.sl=0.1;this.nm=1;this.CS=15;this.kM=0.05;this.GHa=D.u;this.To=20;this.dc=D.r;this.rE=g?g:0;this.Xi=k||0==k?k:16777215;this.oua=h;this.mca=this.xp=this.Ej=D.o;this.po=new D.cd(this.e,0,0,this.ng,this.Ag);this.k(this.po);(0,D.ed)(this.po);this.$=new D.H(this.e);this.k(this.$);this.$.qa(new D.jb);this.Ts=0.5;this.Ga=
new D.Qv(b,this.cc,this);this.Ga.$e(this);this.QHa=1;this.WO(d,e);this.wA=D.u;this.so=D.r};D.Ov.prototype.$j=function(b,c,d){this.ng=b;this.Ag=c;d||(this.po.ia(b),this.po.va(c),this.dc&&(0,D.Rv)(this),this.WO(b,c))};D.Ov.prototype.vc=function(){return new D.hl(this.ng,this.Ag)};D.Ov.prototype.WO=function(b,c){var d=new D.Sg("pzc");(0,D.Tg)(d,this.M(),this.K(),b,c);(0,D.tf)(this,d)};D.Sv=function(b){return b.$};D.Tv=function(b,c){if(c){var d=(0,D.nb)(c,b.$,b.$.pa);if(d)return d}return b.$.pa()};
D.E=D.Ov.prototype;D.E.Fc=function(b){return(0,D.Tv)(this,b).Ic};
D.E.Kq=function(b,c,d){if(this.Ej){var e=(0,D.Tv)(this,d).Fb,f=(0,D.Tv)(this,d).yb,g=(0,D.Uv)(this,e+b),h=(0,D.Vv)(this,f+c);c=g-e;var k=h-f;b=D.r;d&&(b=(0,D.nb)(d,this.$,this.$.pa))&&(b=b.clone());b||(b=this.$.pa().clone());b.translate(c,k);var m=this;c=function(){var b=new D.ko("panning",g,h,e,f,d);m.cc(b)};k=function(){var b=new D.ko("panned",g,h,e,f,d);m.cc(b)};d?((0,D.N)(d,"typeMatrix",this.$,this.$.pa,this.$.qa,b),(0,D.Ck)(d,c),(0,D.Qj)(d,k)):(c(),this.$.qa(b),k())}};
D.E.cp=function(b,c,d){this.Ej&&(b-=(0,D.Tv)(this,d).Fb,c-=(0,D.Tv)(this,d).yb,this.Kq(b,c,d))};
D.E.bW=function(b,c,d,e){if(this.xp){!c&&0!==c&&(c=this.ng/2);!d&&0!==d&&(d=this.Ag/2);var f=this.Fc(e),g=(0,D.Wv)(this,f*b);this.dc&&(b=this.Fc(),g==this.sl&&g==this.nm?((0,D.Gd)(this.dc,D.u),(0,D.Hd)(this.dc,D.u)):b<=g&&g==this.nm?((0,D.Gd)(this.dc,D.u),(0,D.Hd)(this.dc,D.o)):b>=g&&g==this.sl?((0,D.Gd)(this.dc,D.o),(0,D.Hd)(this.dc,D.u)):((0,D.Gd)(this.dc,D.o),(0,D.Hd)(this.dc,D.o)));if(window.Math.round(1E5*f)!=window.Math.round(1E5*g)){var h=g/f;b=D.r;e&&(b=(0,D.nb)(e,this.$,this.$.pa))&&(b=b.clone());
b||(b=this.$.pa().clone());b.scale(h,h,c,d);var k=(0,D.Uv)(this,b.Fb)-b.Fb,m=(0,D.Vv)(this,b.yb)-b.yb;(0,D.Xv)(this,"adjustPanConstraints",g,f,e,D.r,c,d,k,m);k=(0,D.Uv)(this,b.Fb)-b.Fb;m=(0,D.Vv)(this,b.yb)-b.yb;b.translate(k,m);var p=this,h=function(){(0,D.Xv)(p,"zooming",g,f,e,D.r,c,d,k,m)},q=function(){(0,D.Xv)(p,"zoomed",p.Fc(),f,e,D.r,c,d,k,m)};e?((0,D.N)(e,"typeMatrix",this.$,this.$.pa,this.$.qa,b),(0,D.Ck)(e,h),(0,D.Qj)(e,q)):(h(),this.$.qa(b),q())}}};
D.E.bk=function(b,c,d,e){this.xp&&(b/=this.Fc(e),this.bW(b,c,d,e))};D.E.wAa=function(b,c){var d=this.Ej;this.Ej=D.o;var e=c;e||(e=this.$.C());var f=(e.x+e.g/2)*this.Fc(),e=(e.y+e.j/2)*this.Fc();this.cp(this.ng/2-f,this.Ag/2-e,b);this.Ej=d};
D.E.Yk=function(b,c){if(this.mca){var d=this.Ej,e=this.xp;this.xp=this.Ej=D.o;try{var f=c;f||(f=this.$.C());var f=(0,D.Xv)(this,"zoomToFitCalcBounds",D.r,D.r,b,f).BG,g=window.Math.min((this.ng-2*this.To)/f.g,(this.Ag-2*this.To)/f.j),g=(0,D.Wv)(this,g),h=this.ng/2-(f.x+f.g/2)*g,k=this.Ag/2-(f.y+f.j/2)*g,m=this,p=function(){(0,D.Xv)(m,"zoomToFitBegin",D.r,D.r,b,f)},q=function(){(0,D.Xv)(m,"zoomToFitEnd",D.r,D.r,b,f)};b?(0,D.Ck)(b,p):p();this.bk(g,0,0,b);this.cp(h,k,b);b?(0,D.Qj)(b,q):q()}finally{this.Ej=
d,this.xp=e}}};D.E.rz=function(){var b=(0,D.Ce)(this,new D.R(0,0)),c=(0,D.Ce)(this,new D.R(this.ng,this.Ag)),b=this.$.Hb(b),c=this.$.Hb(c);return new D.I(b.x,b.y,c.x-b.x,c.y-b.y)};
D.Yv=function(b,c){if(b.wA=c)b.so&&(b.so.Mg()&&b.so.stop(),b.so=D.r);else{var d=(0,D.Tv)(b,D.n).Fb,e=(0,D.Tv)(b,D.n).yb,f=b.Fc();b.KP=d!=(0,D.Uv)(b,d)||e!=(0,D.Vv)(b,e);b.LP=f!=(0,D.Wv)(b,f);if(b.KP||b.LP)b.so=new D.ub(b.e,0.4),b.so.xj(D.xj),b.LP&&b.bW(1,0.5*b.ng,0.5*b.Ag,b.so),b.KP&&b.Kq(0,0,b.so),(0,D.Qj)(b.so,b.dva,b),b.KP&&(d=new D.ko("elasticAnimBegin",D.r,D.r,D.r,D.r,b.so),b.cc(d)),b.LP&&(0,D.Xv)(b,"elasticAnimBegin",D.r,D.r,D.r,D.r,b.so),b.so.play()}};
D.Ov.prototype.dva=function(){this.so=D.r;if(this.KP){var b=new D.ko("elasticAnimEnd",D.n,D.n,D.n,D.n,D.n);this.cc(b)}this.LP&&(0,D.Xv)(this,"elasticAnimEnd")};D.Uv=function(b,c){var d=c;b.aq!=D.r&&d<b.aq&&(b.wA?(d=b.aq-d,d=b.aq-window.Math.sqrt(4*(0.01*b.ng)*d)):d=b.aq);b.Zp!=D.r&&d>b.Zp&&(b.wA?(d-=b.Zp,d=b.Zp+window.Math.sqrt(4*(0.01*b.ng)*d)):d=b.Zp);return d};
D.Vv=function(b,c){var d=c;b.bq!=D.r&&d<b.bq&&(b.wA?(d=b.bq-d,d=b.bq-window.Math.sqrt(4*(0.01*b.Ag)*d)):d=b.bq);b.$p!=D.r&&d>b.$p&&(b.wA?(d-=b.$p,d=b.$p+window.Math.sqrt(4*(0.01*b.Ag)*d)):d=b.$p);return d};D.Wv=function(b,c){var d=window.Math.max(0,c);b.sl&&d<b.sl&&(b.wA?(d=b.sl-d,d=b.sl-window.Math.sqrt(4*(0.002*(b.nm-b.sl))*d)):d=b.sl);b.nm&&d>b.nm&&(b.wA?(d-=b.nm,d=b.nm+window.Math.sqrt(4*(0.002*(b.nm-b.sl))*d)):d=b.nm);return d};
D.Ov.prototype.Ni=function(){2!=this.rE&&!this.dc&&(this.dc=new D.ud(this.e,this,this.Gj,this.oua,this.Xi,this.I),this.k(this.dc),0==this.rE?this.dc.RH(1):1==this.rE&&this.dc.RH(2),(0,D.Rv)(this),this.dc.Ni())};D.tb=function(b,c){b.dc&&b.removeChild(b.dc);b.dc=c;2!=b.rE&&(b.k(b.dc),0==b.rE?b.dc.RH(1):1==b.rE&&b.dc.RH(2),(0,D.Rv)(b))};
D.Rv=function(b){var c=b.I.$r(),d=(0,D.id)(c,"paddingSide",0),e=(0,D.id)(c,"paddingTop",0),c=(0,D.id)(c,"openCloseButtonWidth",0),d=D.K.R(b.e)?b.ng-c-d:d;(0,D.Ya)(b.dc,d,e)};D.Wc=function(b,c){return(0,D.og)(b.e,c.pageX,c.pageY)};D.Xv=function(b,c,d,e,f,g,h,k,m,p){c=new D.rb(c,d,e,f,g,new D.R(h,k),m,p);b.cc(c);return c};D.Ov.prototype.aW=function(){(0,D.Xv)(this,"zoomAndCenter")};D.Qc=function(b,c){var d;d=c+b.kM;d>b.nm&&(d=b.nm);return d};D.td=function(b,c){var d;d=c-b.kM;d<b.sl&&(d=b.sl);return d};
D.Ov.prototype.vs=(0,D.B)("sl");D.Ov.prototype.Gu=function(b){0>b&&(b=1);this.nm=b};D.Ov.prototype.Mn=(0,D.B)("Ts");D.Ov.prototype.Ta=(0,D.C)("Ts");
D.Qv=function(b,c,d){this.Init(b,c,d)};D.F.l(D.Qv,D.Bc,"DvtPanZoomCanvasEventManager");D.E=D.Qv.prototype;D.E.Init=function(b,c,d){D.Qv.q.Init.call(this,b,c,d);this.xb=d;this.Vr=D.r;this.gr=this.jE=D.u;this.VP=D.o};D.E.$e=function(b){D.Qv.q.$e.call(this,b);D.K.nh()?b.P("DOMMouseScroll",this.aA,D.u,this):b.P(D.yi,this.aA,D.u,this)};
D.E.bl=function(b){2!=b.button&&(b=(0,D.Wc)(this.ka,b),this.Bt=b.x,this.Ct=b.y,this.NF=this.Bt,this.Py=this.Ct,this.zZ=D.o,this.tS=(0,D.Tv)(this.ka,D.n).Fb,this.uS=(0,D.Tv)(this.ka,D.n).yb,this.vS=this.ka.Fc(),this.VP&&(this.Fp=(new window.Date).getTime()));this.bj&&this.bj.Mg()&&(this.bj.stop(),this.bj.reset())};
D.E.Sm=function(b){if(this.zZ){var c=(0,D.Wc)(this.ka,b),d=c.x,c=c.y;b.ctrlKey?(this.gr||(this.Xa.call(this.ka,new D.rb("dragZoomBegin")),this.gr=D.o,this.xb.dc&&(0,D.Ad)(this.xb.dc),(0,D.Yv)(this.ka,D.o)),b=this.vS*window.Math.pow(1+0.01*(this.Py>=c?1:-1),window.Math.abs(this.Py-c)),this.ka.Ej?this.ka.bk(b,this.NF,this.Py):this.ka.bk(b,D.r,D.r)):(0,D.aw)(this,d,c);this.Bt=d;this.Ct=c}};D.E.Tm=function(){this.zZ=D.u;this.jE&&(0,D.bw)(this);this.gr&&(0,D.cw)(this)};
D.E.dk=function(b){if(this.zZ&&(this.jE||this.gr))(!b.relatedTarget||b.relatedTarget==D.r)&&this.Tm(b);D.Qv.q.dk.call(this,b)};D.E.aA=function(b){var c=this.ka.Fc();this.Vr&&(c=this.Vr,this.Vr.stop(),c=this.ka.Fc(c),this.Vr=D.r);this.Vr=D.r;var d=0;b.wheelDelta!=D.r&&(d=b.wheelDelta,D.K.nh()&&(d=-d));c*=1+this.ka.kM*d/window.Math.abs(d);d=(0,D.Wc)(this.ka,b);this.e.cz().vAa(b);this.ka.Ej?this.ka.bk(c,d.x,d.y,this.Vr):this.ka.bk(c,D.r,D.r,this.Vr);this.Vr&&((0,D.Qj)(this.Vr,this.eua,this),this.Vr.play())};
D.E.eua=function(){this.Vr=D.r};D.E.kwa=(0,D.z)();D.E.lwa=function(){var b=1-0.04*this.V1,b=b*b,c=this.bj.nU(),d=b*this.txa*c,b=b*this.uxa*c;this.T1+=d;this.U1+=b;var c=this.tS+this.Bt-this.NF+this.T1,e=this.uS+this.Ct-this.Py+this.U1;this.ka.cp(c,e);var f=D.u;if(24<=this.V1)f=D.o;else{var g=(0,D.Tv)(this.ka,D.n).Fb,h=(0,D.Tv)(this.ka,D.n).yb;if(window.Math.abs(g-c)>window.Math.abs(d)||window.Math.abs(h-e)>window.Math.abs(b))f=D.o}f?(this.bj.stop(),this.bj.reset(),(0,D.Yv)(this.ka,D.u)):this.V1++};
D.E.ED=function(b){this.ka.xp&&(0,D.Di)(b,this.Rqa,this);this.ka.Ej&&(0,D.Di)(b,this.fqa,this)};D.E.yO=function(b){this.ka.xp&&(0,D.Ei)(this.Qb,b,"zoomTouch");this.ka.Ej&&(0,D.Ei)(this.Qb,b,"panTouch");b&&b.preventDefault()};D.E.xO=function(b){this.ka.xp&&(0,D.Pi)(this.Qb,b,"zoomTouch");this.ka.Ej&&(0,D.Pi)(this.Qb,b,"panTouch")};
D.E.Rqa=function(b,c){var d=(0,D.Xi)(this.Qb,"zoomTouch");1>=d.length&&((0,D.oh)(this.Qb,c.identifier,"zoomTouch",D.r,"zoomTouch","zoomTouch",this.Qqa,this.Pqa,this),this.Bt=c.pageX,this.Ct=c.pageY,this.NF=this.Bt,this.Py=this.Ct,this.tS=(0,D.Tv)(this.ka,D.n).Fb,this.uS=(0,D.Tv)(this.ka,D.n).yb,this.vS=this.ka.Fc(),this.sS=D.r,d=(0,D.Xi)(this.Qb,"zoomTouch"),d=(0,D.Zi)(this.Qb,d),this.ka.J_=d);this.bj&&this.bj.Mg()&&(this.bj.stop(),this.bj.reset())};
D.E.Qqa=function(){var b=(0,D.Xi)(this.Qb,"zoomTouch");if(2==b.length){var c;var d=this.Qb;if(2==b.length)if(c=d.Eh[b[0]],d=d.Eh[b[1]],c==D.r||d==D.r||0==c.Wja&&0==d.Xja)c=D.r;else{var e=c.pageX-d.pageX,f=c.pageY-d.pageY,e=window.Math.sqrt(e*e+f*f),f=c.C7-d.C7,g=c.D7-d.D7,h=(c.pageX+d.pageX)/2,k=(c.pageY+d.pageY)/2;c={pBa:e-window.Math.sqrt(f*f+g*g),ST:h,LG:k,YAa:h-(c.C7+d.C7)/2,ZAa:k-(c.D7+d.D7)/2,Tja:e}}else c=D.r;c&&(this.gr||(this.gr=D.o,this.Qb.Wr(),this.Xa.call(this.ka,new D.rb("dragZoomBegin")),
this.xb.dc&&(0,D.Ad)(this.xb.dc)),(0,D.Yv)(this.ka,D.o),this.sS==D.r&&(this.sS=c.Tja-c.pBa),d=this.vS*(c.Tja/this.sS),e=(0,D.og)(this.xb.e,c.ST,c.LG),this.oc(),b=(0,D.Zi)(this.Qb,b),this.ka.J_=b,this.ka.bk(d,e.x,e.y),this.ka.Kq(c.YAa,c.ZAa))}};D.E.Pqa=function(){this.gr&&(this.sS=D.r,this.Qb.QZ=D.u,(0,D.cw)(this));var b=(0,D.Xi)(this.Qb,"zoomTouch"),c=(0,D.Zi)(this.Qb,b);this.ka.J_=c;0==b.length&&this.Xa.call(this.ka,new D.rb("zoomEnd"))};
D.E.fqa=function(b,c){!this.gr&&1>=(0,D.Xi)(this.Qb,"panTouch").length&&((0,D.oh)(this.Qb,c.identifier,"panTouch",D.r,"panTouch","panTouch",this.eqa,this.dqa,this),this.Bt=c.pageX,this.Ct=c.pageY,this.NF=this.Bt,this.Py=this.Ct,this.tS=(0,D.Tv)(this.ka,D.n).Fb,this.uS=(0,D.Tv)(this.ka,D.n).yb,this.vS=this.ka.Fc(),this.VP&&(this.Fp=(new window.Date).getTime()));this.bj&&this.bj.Mg()&&(this.bj.stop(),this.bj.reset())};
D.E.eqa=function(b,c){if(!this.gr&&1==(0,D.Xi)(this.Qb,"panTouch").length){var d=c.pageX,e=c.pageY;(0,D.aw)(this,d,e);this.Bt=d;this.Ct=e}};D.E.dqa=function(){!this.gr&&this.jE&&(0,D.bw)(this)};D.cw=function(b){b.Xa.call(b.ka,new D.rb("dragZoomEnd"));b.gr=D.u;b.xb.dc&&(0,D.Bd)(b.xb.dc);(0,D.Yv)(b.ka,D.u)};
D.aw=function(b,c,d){b.jE||(b.Xa.call(b.ka,new D.ko("dragPanBegin")),b.jE=D.o,b.xb.dc&&(0,D.Ad)(b.xb.dc),(0,D.Yv)(b.ka,D.o),b.VP&&(b.sA=[]));b.ka.cp(b.tS+c-b.NF,b.uS+d-b.Py);b.VP&&(b.Wwa=b.Fp,b.Fp=(new window.Date).getTime(),b.Vv?(b.Vv.Mg()&&b.Vv.stop(),b.Vv.reset()):b.Vv=new D.Pc(b.e,50,b.kwa,b,1),b.sA.push({hBa:b.Fp-b.Wwa,Wja:c-b.Bt,Xja:d-b.Ct}),5<b.sA.length&&b.sA.splice(0,1),b.Vv.start())};
D.bw=function(b){b.Xa.call(b.ka,new D.ko("dragPanEnd"));b.jE=D.u;b.xb.dc&&(0,D.Bd)(b.xb.dc);if(b.Vv&&b.Vv.Mg()){b.Vv.stop();b.Vv.reset();b.bj?b.bj.reset():b.bj=new D.Pc(b.e,50,b.lwa,b);for(var c=0,d=0,e=0,f=b.sA.length;0<b.sA.length;)var g=b.sA.pop(),c=c+g.hBa,d=d+g.Wja,e=e+g.Xja;b.sA=D.r;b.txa=d/c;b.uxa=e/c;b.bj.setInterval(window.Math.ceil(c/f));b.V1=1;b.T1=0;b.U1=0;b.xb.Ej&&b.bj.start()}else(0,D.Yv)(b.ka,D.u)};
D.Mu=function(b,c){this.Init(b,c)};D.F.l(D.Mu,D.Nn,"DvtPanZoomCanvasKeyboardHandler");D.Mu.prototype.Init=function(b,c){D.Mu.q.Init(c);this.mua=b};
D.Mu.prototype.qs=function(b){var c=b.keyCode,d=this.mua.ba;if(33==c)b.ctrlKey||b.shiftKey?d.Kq(d.CS,0):d.Kq(0,d.CS);else if(34==c)b.ctrlKey||b.shiftKey?d.Kq(-d.CS,0):d.Kq(0,-d.CS);else if(191==c)(b=d.dc)&&b.UN();else{var e=b.keyCode;if((D.K.nh()?61==e&&!b.shiftKey:187==e&&!b.shiftKey)||(0,D.ui)(b))d.bk(d.Fc()+d.kM);else{if(!(e=(0,D.vi)(b)))e=b.keyCode,e=D.K.nh()?173==e&&b.shiftKey?D.o:D.u:189==e&&b.shiftKey?D.o:D.u;if(e)d.bk(d.Fc()-d.kM);else if((48==c||96==c)&&!b.ctrlKey&&!b.shiftKey)d.Yk();else return D.Mu.q.qs.call(this,
b)}}};
D.Ja=function(b,c,d,e,f,g,h,k){this.Init(b,c,d,e,f,g,h,k)};D.F.l(D.Ja,D.H,"DvtCollapsiblePanel");
D.Ja.prototype.Init=function(b,c,d,e,f,g,h,k){D.Ja.q.Init.call(this,b);this.jg=c;this.xc=d;this.wi=e?e:"col_northeast";D.K.R(this.e)&&("col_northeast"==this.wi?this.wi="col_northwest":"col_northwest"==this.wi?this.wi="col_northeast":"col_southeast"==this.wi?this.wi="col_southwest":"col_southwest"==this.wi&&(this.wi="col_southeast"));this.Gj=f;this.Ov=k?k:D.K.ku();this.qb=this.FA=this.UA=D.r;this.D=g;this.Ap=(0,D.id)(this.D,"border-color",D.r);this.sh=(0,window.parseInt)((0,D.id)(this.D,"border-radius",
D.r));this.jv=(0,D.id)(this.D,"background-color",D.r);this.Fj=(0,D.id)(this.D,"backgroundAlpha",1);this.nQ=h!==D.n?!h:D.u;this.Ed=new D.Id(b,0,0,c-10,d-10,3,"collapsiblePanel");this.k(this.Ed);this.Ed.K0=D.u;(0,D.Ya)(this.Ed,5,5);this.P(D.Va,this.zO,D.u,this);this.P(D.Wa,this.FD,D.u,this)};
D.Ja.prototype.upa=function(){this.Ed.refresh();var b=this.Ed.C(),c=b.g+10,b=b.j+10;this.fb.Zj((0,D.Qa)(this,c,b));var d="col_northwest"==this.wi||"col_southwest"==this.wi;this.bg&&d&&this.bg.F(c);this.cc(new D.mc(c,b,0,0))};D.Ja.prototype.isCollapsed=(0,D.C)("nQ");D.Kd=function(b,c){b.nQ!=c&&(b.nQ=c,(0,D.Xa)(b,D.o),b.cc(new D.Jd(c?"hide":"show")))};D.Ja.prototype.g6=function(){return this.jg-27};D.Ja.prototype.f6=function(){return this.xc-27};
D.Ld=function(b,c,d){return!b.isCollapsed()?d?new D.R(1/c.x,1/c.y):new D.R(-c.x,-c.y):c};
D.Xa=function(b,c){b.qb&&(b.cJ=D.o,b.qb.stop(D.o));var d="col_northwest"==b.wi||"col_northeast"==b.wi,e="col_northwest"==b.wi||"col_southwest"==b.wi,f=e?0:b.Q,g=d?0:b.W,h=new D.R(1/b.Q,1/b.W),f=new D.R(f,g),d=new D.R(e?-b.Q:b.Q,g-(d?0:25));c||(b.fb.B(0),b.bg&&b.bg.B(0));h=new D.Md(b.e,b.fb,(0,D.Ld)(b,h,D.o),c?0.25:1E-5);d=new D.Nd(b.e,b.bg,(0,D.Ld)(b,d),c?0.25:1E-5);f=new D.Nd(b.e,b.fb,(0,D.Ld)(b,f),c?0.25:1E-5);b.qb=new D.Od(b.e,h,d,f);b.qb&&(b.e.hd().oc(),b.Pa(D.Va,b.zO,D.u,b),b.Pa(D.Wa,b.FD,D.u,
b),b.Ij&&(b.Ij.Pa(D.Ta.Rd,b.LD,D.u,b),b.Ij.Pa(D.Ua,b.LD,D.u,b),b.Ij.Pa(D.Va,b.NX,D.u,b),b.Ij.Pa(D.Wa,b.MX,D.u,b)),b.isCollapsed()&&b.Ed.B(0),b.qb.zd(b.rp,b),b.qb.play())};
D.Qa=function(b,c,d){var e=b.sh,f,g="col_northwest"==b.wi||"col_southwest"==b.wi;25>=d&&(d=25);f=b.Ov||g?window.DvtPathUtils.moveTo(e,0):window.DvtPathUtils.moveTo(0,0);f+=window.DvtPathUtils.lineTo(c-e,0);!b.Ov&&g?(f+=window.DvtPathUtils.lineTo(c,0),f+=window.DvtPathUtils.lineTo(c,e)):f+=window.DvtPathUtils.Zb(c,0,c,e);!b.Ov&&25==d&&g?f+=window.DvtPathUtils.lineTo(c,d):(f+=window.DvtPathUtils.lineTo(c,d-e),f+=window.DvtPathUtils.Zb(c,d,c-e,d));f+=window.DvtPathUtils.lineTo(e,d);f=!b.Ov&&25==d&&!g?
f+window.DvtPathUtils.lineTo(0,d):f+window.DvtPathUtils.Zb(0,d,0,d-e);if(b.Ov||g)f+=window.DvtPathUtils.lineTo(0,e),f+=window.DvtPathUtils.Zb(0,0,e,0);return f+=window.DvtPathUtils.closePath()};D.E=D.Ja.prototype;
D.E.rp=function(){this.cJ=D.u;this.qb=D.r;var b=this.fb.nc().clone();b.B(this.D.borderAlpha);this.fb.Y(b);var b=this.D[D.ud.tGa],c=this.fb.Ec().clone();c.B(b);this.fb.G(c);this.bg&&this.bg.B(this.D.borderAlpha);this.isCollapsed()||this.Ed.B(1);this.P(D.Va,this.zO,D.u,this);this.P(D.Wa,this.FD,D.u,this);this.Ij&&(this.Ij=this.isCollapsed()?D.M.QT(this.e,this.Gj,25,this.D,D.u):D.M.OT(this.e,this.Gj,25,this.D,D.u),this.bg.k(this.Ij),this.bg.dp(0),D.K.da()?this.Ij.P(D.Ta.Rd,this.LD,D.u,this):(this.Ij.P(D.Ua,
this.LD,D.u,this),this.Ij.P(D.Va,this.NX,D.u,this),this.Ij.P(D.Wa,this.MX,D.u,this)))};D.E.LD=function(){this.e.hd().oc();(0,D.Kd)(this,!this.isCollapsed())};D.E.NX=function(b){var c=this.isCollapsed()?this.UA:this.FA;c!=D.r&&this.e.hd().UH(b.pageX,b.pageY,c,this.Ij,D.o)};D.E.MX=function(){this.e.hd().oc()};D.E.zO=function(){var b=this.fb.nc().clone();b.B(this.D.borderHoverAlpha);this.fb.Y(b);var b=this.D.backgroundHoverAlpha,c=this.fb.Ec().clone();c.B(b);this.fb.G(c);this.bg&&this.bg.B(this.D.borderHoverAlpha)};
D.E.FD=function(){var b=this.fb.nc().clone();b.B(this.D.borderAlpha);this.fb.Y(b);b=this.fb.Ec().clone();b.B(this.Fj);this.fb.G(b);this.bg&&this.bg.B(this.D.borderAlpha)};
D.Jd=function(b){this.Init("dvtCollapsiblePanelEvent");this.xl=b};D.F.l(D.Jd,D.Jc,"DvtCollapsiblePanelEvent");D.Jd.prototype.hi=(0,D.C)("xl");
D.Sd={};D.F.l(D.Sd,D.F,"DvtImageLAFUtils");D.Sd.rH=function(b,c){var d=new D.Ma(b,c);d.la(D.u);D.Qd.tj(b,c,function(b){b!=D.r&&(b.width&&b.height)&&(d.ia(b.width),d.va(b.height))});return d};
D.M={};D.F.l(D.M,D.F,"DvtButtonLAFUtils");D.M.zGa=-6;D.M.V8=23;D.M.U8=21;D.M.$Ga=20;D.M.PGa=22;D.M.OGa=20;D.M.Kaa=47;D.M.Jaa=26;D.M.Bd=window.Math.sin(window.Math.PI/4);D.M.Cd=window.Math.tan(window.Math.PI/8);D.M.$N="#7C8191";D.M.F9="#E0E1E1";D.M.G9="#F0F1F2";D.M.hY=8;D.M.hoa="solid";D.M.eoa="#7BA0D9";D.M.GW="#3474D3";D.M.h9="#BFD8FB";D.M.vsa="zoominUp";D.M.wsa="zoominOver";D.M.usa="zoominDown";D.M.tsa="zoominDisabled";D.M.Csa="zoomtofitUp";D.M.Dsa="zoomtofitOver";D.M.Bsa="zoomtofitDown";
D.M.zsa="zoomoutUp";D.M.Asa="zoomoutOver";D.M.ysa="zoomoutDown";D.M.xsa="zoomoutDisabled";D.M.Pra="pandialUp";D.M.Qra="pandialOver";D.M.Ora="pandialDown";D.M.Xra="recenterUp";D.M.Yra="recenterOver";D.M.Wra="recenterDown";D.M.rba="resetUp";D.M.$ra="resetOver";D.M.Zra="resetDown";D.M.eba="drillupUp";D.M.ora="drillupOver";D.M.nra="drillupDown";D.M.dba="drilldownUp";D.M.mra="drilldownOver";D.M.lra="drilldownDown";D.M.gHa="maxUp";D.M.hHa="maxOver";D.M.fHa="maxDown";D.M.jHa="restoreUp";D.M.kHa="restoreOver";
D.M.iHa="restoreDown";D.M.bra="collapseEna";D.M.cra="collapseOvr";D.M.ara="collapseDwn";D.M.rra="expandEna";D.M.sra="expandOvr";D.M.qra="expandDwn";D.M.Sra="quickQueryEna";D.M.Tra="quickQueryOvr";D.M.Rra="quickQueryDwn";D.M.Zqa="clearResultsEna";D.M.$qa="clearResultsOvr";D.M.Yqa="clearResultsDwn";D.M.rsa="Up";D.M.Nra="Over";D.M.kra="Down";D.M.bsa="Sel";D.M.Ura="_r";D.M.msa="synchronize";
D.M.LAa=function(b,c,d,e,f,g){var h=D.M.E_(b,f[D.M.Pra],g),k=new D.H(b);(0,D.Ya)(k,20,20);var m=D.M.E_(b,f[D.M.Ora],g);(0,D.Ya)(m,-20,-20);k.k(m);m=new D.H(b);(0,D.Ya)(m,20,20);var p=D.M.E_(b,f[D.M.Qra],g);(0,D.Ya)(p,-20,-20);m.k(p);h=new D.tc(b,h,m,k);if(0<(e&16)){var q=new D.tc(b,D.M.G_(b,f[D.M.Xra],g),D.M.G_(b,f[D.M.Yra],g),D.M.G_(b,f[D.M.Wra],g));(0,D.Ya)(q,9,9)}return new D.Sc(b,h,q,c,d,e,g)};
D.M.FAa=function(b,c,d,e,f,g,h){var k=D.M.cg(b,0,f[D.M.eba],h),m=D.M.cg(b,1,f[D.M.ora],h),p=D.M.cg(b,2,f[D.M.nra],h);f=D.M.cg(b,0,f[D.M.eba],h);return new D.Pd(b,new D.tc(b,k,m,p,f),c,d,0,e,g)};D.M.EAa=function(b,c,d,e,f,g,h){var k=D.M.cg(b,0,f[D.M.dba],h),m=D.M.cg(b,1,f[D.M.mra],h),p=D.M.cg(b,2,f[D.M.lra],h);f=D.M.cg(b,0,f[D.M.dba],h);return new D.Pd(b,new D.tc(b,k,m,p,f),c,d,1,e,g)};
D.M.RAa=function(b,c,d,e,f,g,h){var k=D.M.cg(b,0,f[D.M.rba],h),m=D.M.cg(b,1,f[D.M.$ra],h),p=D.M.cg(b,2,f[D.M.Zra],h);f=D.M.cg(b,0,f[D.M.rba],h);return new D.Pd(b,new D.tc(b,k,m,p,f),c,d,2,e,g)};D.M.XAa=function(b,c,d,e,f,g){var h=D.M.cg(b,0,f[D.M.Csa],g),k=D.M.cg(b,1,f[D.M.Dsa],g);f=D.M.cg(b,2,f[D.M.Bsa],g);return new D.Kc(b,new D.tc(b,h,k,f),c,d,e)};
D.M.VAa=function(b,c,d,e,f,g){var h=D.M.cg(b,0,f[D.M.vsa],g),k=D.M.cg(b,1,f[D.M.wsa],g),m=D.M.cg(b,2,f[D.M.usa],g);f=D.M.cg(b,3,f[D.M.tsa],g);return new D.Oc(b,new D.tc(b,h,k,m,f),c,d,e)};D.M.WAa=function(b,c,d,e,f,g){var h=D.M.cg(b,0,f[D.M.zsa],g),k=D.M.cg(b,1,f[D.M.Asa],g),m=D.M.cg(b,2,f[D.M.ysa],g);f=D.M.cg(b,3,f[D.M.xsa],g);return new D.sd(b,new D.tc(b,h,k,m,f),c,d,e)};
D.M.HAa=function(b,c,d,e,f){var g=(0,D.id)(f,"buttonRadius",0),h=(0,D.id)(f,"buttonWidth",0),k=(0,D.id)(f,"buttonWidth",0),m=D.M.A_(b,g,h,k,f);D.M.D3(d,m,h,k+2*g,f,D.o);c=D.M.B0(b,d,c);(b=D.M.Sfa(b,e[c],h,k))&&m.k(b);return m};D.M.B0=function(b,c,d,e){var f="";0==c?c=D.M.rsa:1==c?c=D.M.Nra:2==c&&(c=D.M.kra);e&&(d+=D.M.bsa,D.K.R(b)&&(f=D.M.Ura));return d+(c+f)};D.M.Z4=function(b,c,d,e){var f=D.M.B0(b,c,D.M.msa,D.o);return D.M.cg(b,c,e[f],d)};
D.M.MAa=function(b,c,d,e,f){var g=(0,D.id)(f,"buttonRadius",0);b=D.M.A_(b,g,d,e,f);D.M.D3(c,b,d,e+2*g,f,D.o);return b};D.M.DAa=function(b,c,d,e,f){c=D.M.B0(b,d,c);return D.M.cg(b,d,e[c],f)};D.M.QT=function(b,c,d,e,f){var g=D.M.tE(b,0,d,c[D.M.rra],e,f),h=D.M.tE(b,1,d,c[D.M.sra],e,f);c=D.M.tE(b,2,d,c[D.M.qra],e,f);return new D.tc(b,g,h,c)};D.M.OT=function(b,c,d,e,f){var g=D.M.tE(b,0,d,c[D.M.bra],e,f),h=D.M.tE(b,1,d,c[D.M.cra],e,f);c=D.M.tE(b,2,d,c[D.M.ara],e,f);return new D.tc(b,g,h,c)};
D.M.PAa=function(b,c){var d=D.M.uE(b,c[D.M.Sra]),e=D.M.uE(b,c[D.M.Tra]),f=D.M.uE(b,c[D.M.Rra]);return new D.tc(b,d,e,f)};D.M.CAa=function(b,c){var d=D.M.uE(b,c[D.M.Zqa]),e=D.M.uE(b,c[D.M.$qa]),f=D.M.uE(b,c[D.M.Yqa]);return new D.tc(b,d,e,f)};D.M.cg=function(b,c,d,e){var f,g,h=(0,D.id)(e,"buttonRadius",0);if("undefined"===f||f==D.r)f=(0,D.id)(e,"buttonWidth",0);if("undefined"===g||g==D.r)g=(0,D.id)(e,"buttonWidth",0);c=D.M.Wua(b,c,h,f,g,e);(b=D.M.Sfa(b,d,f,g))&&c.k(b);return c};
D.M.Sfa=function(b,c,d,e){var f=new D.Ma(b,c);f.la(D.u);D.Qd.tj(b,c,function(b){b!=D.r&&(b.width&&b.height)&&(f.ia(b.width),f.va(b.height),(0,D.Ya)(f,d/2-b.width/2,e/2-b.height/2))});return f};D.M.E_=function(b,c,d){var e=new D.H(b),f=new D.Rd(b,20,20,20);f.B(0);f.na((0,D.id)(d,"background-color",D.r));e.k(f);(b=D.Sd.rH(b,c))&&e.k(b);return e};D.M.G_=function(b,c,d){var e=new D.H(b),f=new D.Rd(b,11,11,8);f.B(0);f.na((0,D.id)(d,"background-color",D.r));e.k(f);(b=D.Sd.rH(b,c))&&e.k(b);return e};
D.M.tE=function(b,c,d,e,f,g){d||(d=47);c=D.M.Yua(b,c,d,f,g);if(b=D.Sd.rH(b,e))e=(0,D.id)(f,"imageWidth",0),g=(0,D.id)(f,"imageHeight",0),c.k(b),(0,D.Ya)(b,((0,D.id)(f,"openCloseButtonWidth",0)-e)/2,(d-g)/2);return c};D.M.uE=function(b,c){var d=D.Sd.rH(b,c);d.la(D.o);return d};
D.M.KAa=function(b,c){var d=D.M.zda(b),e=(0,D.id)(c,"background-color",D.r),f=(0,D.id)(c,"border-color",D.r);"solid"==(0,D.id)(c,"fill-type",D.r)?(d.Ma(f),d.na(e)):(d.Y(new D.Td(36,["#8D93A5","#E0EAEB",f],[1,1,1],[0,125/255,1],[0,0,40,40],1)),d.G(new D.gd(90,[e,e,"#5A83BE",e],[0.9,0.1,0,0.7],[0,105/255,150/255,1],[0,0,40,40])));return d};D.M.Kja=function(b,c){var d=D.M.zda(b),e=(0,D.id)(c,"background-color",D.r);d.Ma(e);d.na(e);return d};
D.M.zda=function(b){var c=window.DvtPathUtils.moveTo(40,20)+window.DvtPathUtils.Zb(40,20*D.M.Cd+20,20*D.M.Bd+20,20*D.M.Bd+20)+window.DvtPathUtils.Zb(20*D.M.Cd+20,40,20,40)+window.DvtPathUtils.Zb(20*-D.M.Cd+20,40,20*-D.M.Bd+20,20*D.M.Bd+20)+window.DvtPathUtils.Zb(0,20*D.M.Cd+20,0,20)+window.DvtPathUtils.Zb(0,20*-D.M.Cd+20,20*-D.M.Bd+20,20*-D.M.Bd+20)+window.DvtPathUtils.Zb(20*-D.M.Cd+20,0,20,0)+window.DvtPathUtils.Zb(20*D.M.Cd+20,0,20*D.M.Bd+20,20*-D.M.Bd+20)+window.DvtPathUtils.Zb(40,20*-D.M.Cd+20,
40,20)+window.DvtPathUtils.closePath();return new D.Ra(b,c,"draw_pan_button")};D.M.fT=function(b,c,d,e,f){b.Ma("#FFFFFF");b.Y(new D.Td(63,["#8D93A5","#E0EAEB","#FFFFFF"],[1,1,1],[0,155/255,1],[e,f,c,d],1))};
D.M.D3=function(b,c,d,e,f,g){if((0,D.id)(f,"panelDrawerStyles",D.r))!g||g&&0==b?(0,D.ed)(c):(1==b||2==b)&&c.G(new D.Ud("#EBECED"));else if("skyros"==f.skin)switch(b){case 1:c.G(new D.Ud("#FFFFFF",0.7));c.Y(new D.Vd((0,D.id)(f,"border-color",D.r)));break;case 2:c.G(new D.Ud("#B3C6DB"));c.Y(new D.Vd((0,D.id)(f,"border-color",D.r)));break;default:(0,D.ed)(c)}else{var h,k,m;switch(b){case 3:case 0:h=["#5B868A","#FFFFFF","#FFFFFF","#5B868A"];k=[0.01,0,0.05,0.01];m=[0,120/255,130/255,1];break;case 1:D.M.fT(c,
d,e,0,0);h=["#FFFFFF","#4671B0","#4671B0","#FFFFFF"];k=[0.5,0.2,0.1,0.7];m=[0,120/255,130/255,1];break;case 2:D.M.fT(c,d,e,0,0),h=["#E0EAEB","#5B868A","#4671B0"],k=[0.1,0.3,0.6],m=[0,130/255,1]}c.G(new D.gd(90,h,k,m,[0,0,d,e]))}};
D.M.kza=function(b,c,d,e,f){if((0,D.id)(f,"panelDrawerStyles",D.r))(0,D.ed)(c);else{var g;g=(0,D.id)(f,"border-color",D.r);if("solid"==(0,D.id)(f,"fill-type",D.r)){d=(0,D.id)(f,"background-color",D.r);switch(b){case 0:window.bgAlpha=(0,D.id)(f,"backgroundAlpha",1);window.strokeAlpha=(0,D.id)(f,"borderAlpha",1);break;case 2:case 1:window.bgAlpha=(0,D.id)(f,"backgroundHoverAlpha",1),window.strokeAlpha=(0,D.id)(f,"borderHoverAlpha",1)}b=new D.Ud(d,window.bgAlpha);g=new D.Vd(g,window.strokeAlpha)}else{var h,
k,m;switch(b){case 0:h=["#FFFFFF","#5B868A","#5B868A"];k=[0,0.2,0.3];m=[0,130/255,1];break;case 1:h=["#FFFFFF","#FFFFFF","#4671B0","#4671B0"];k=[0.1,0.2,0.1,0.6];m=[0,120/255,130/255,1];break;case 2:h=["#4671B0","#5B868A","#5B868A"],k=[0.5,0.2,0.4],m=[0,130/255,1]}b=new D.gd(0,h,k,m,[0,0,d,e]);g=new D.Vd(g,1,0.8)}c.Y(g);c.G(b)}};
D.M.IIa=function(b,c,d,e,f,g){var h,k,m;switch(b){case 0:c.Ma("#FFFFFF",1,0.25);h=["#FFFFFF","#4671B0","#E0EAEB","#FFFFFF"];k=[0.6,0.3,0.3,0.8];m=[0,125/255,130/255,1];break;case 1:D.M.fT(c,d,e,f,g);h=["#4671B0","#FFFFFF","#FFFFFF","#FFFFFF"];k=[0.4,0.3,0.7,1];m=[0,70/255,200/255,1];break;case 2:D.M.fT(c,d,e,f,g),h=["#FFFFFF","#4671B0","#E0EAEB"],k=[0.6,0.5,0.8],m=[0,130/255,1]}c.G(new D.gd(90,h,k,m,[f,g,d,e]))};
D.M.VW=function(b,c,d,e){return e?["M",b,0,"L",d,0,"A",d,d,0,0,0,0,d,"L",0,c-d,"A",d,d,0,0,0,d,c,"L",b,c]:["M",0,0,"L",b-d,0,"A",d,d,0,0,1,b,d,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c]};D.M.Yua=function(b,c,d,e,f){d||(d=47);var g=(0,window.parseInt)((0,D.id)(e,"border-radius",0)),h=(0,D.id)(e,"openCloseButtonWidth",0);d=window.Math.max(d,(0,D.id)(e,"buttonHeight",d));b=new D.Ra(b,D.M.VW(h,d,g,f));D.M.kza(c,b,h,d,e);return b};D.M.Wua=function(b,c,d,e,f,g){b=D.M.A_(b,d,e,f,g);D.M.D3(c,b,e,f+2*d,g);return b};
D.M.A_=function(b,c,d,e,f){if("skyros"==f.skin)return new D.cd(b,0,0,d,e);d-=2*c;e-=2*c;f=d+c;var g=e+c,h=window.DvtPathUtils.moveTo(f+c,g)+window.DvtPathUtils.Zb(c+f,D.M.Cd*c+g,D.M.Bd*c+f,D.M.Bd*c+g)+window.DvtPathUtils.Zb(D.M.Cd*c+f,c+g,f,c+g)+window.DvtPathUtils.lineTo(f,g+c)+window.DvtPathUtils.lineTo(f-d,c+g);f-=d;h+=window.DvtPathUtils.Zb(-D.M.Cd*c+f,c+g,-D.M.Bd*c+f,D.M.Bd*c+g)+window.DvtPathUtils.Zb(-c+f,D.M.Cd*c+g,-c+f,g)+window.DvtPathUtils.lineTo(f-c,g)+window.DvtPathUtils.lineTo(f-c,g-
e);g-=e;h+=window.DvtPathUtils.Zb(-c+f,-D.M.Cd*c+g,-D.M.Bd*c+f,-D.M.Bd*c+g)+window.DvtPathUtils.Zb(-D.M.Cd*c+f,-c+g,f,-c+g)+window.DvtPathUtils.lineTo(f,-c+g)+window.DvtPathUtils.lineTo(f+d,-c+g);f+=d;h+=window.DvtPathUtils.Zb(D.M.Cd*c+f,-c+g,D.M.Bd*c+f,-D.M.Bd*c+g)+window.DvtPathUtils.Zb(c+f,-D.M.Cd*c+g,c+f,g)+window.DvtPathUtils.lineTo(f+c,g+e)+window.DvtPathUtils.closePath();return new D.Ra(b,h)};
D.M.bBa=function(b,c,d,e){e=(0,D.id)(e,"radius",0);c-=2*e;d-=e;var f=c+e,g=d,h=window.DvtPathUtils.moveTo(f+e,g)+window.DvtPathUtils.Zb(e+f,D.M.Cd*e+g,D.M.Bd*e+f,D.M.Bd*e+g)+window.DvtPathUtils.Zb(D.M.Cd*e+f,e+g,f,e+g)+window.DvtPathUtils.lineTo(f,e+g)+window.DvtPathUtils.lineTo(f-c,e+g),f=f-c,h=h+(window.DvtPathUtils.Zb(-D.M.Cd*e+f,e+g,-D.M.Bd*e+f,D.M.Bd*e+g)+window.DvtPathUtils.Zb(-e+f,D.M.Cd*e+g,-e+f,g)+window.DvtPathUtils.lineTo(-e+f,g)+window.DvtPathUtils.lineTo(-e+f,g-d)),g=g-d,h=h+(window.DvtPathUtils.lineTo(f+
c+e,g)+window.DvtPathUtils.lineTo(f+c+e,g+d)+window.DvtPathUtils.closePath());return new D.Ra(b,h)};D.M.jJa=function(b,c){var d=new window.DvtDropShadowFilter(7,45,"#5A83BE",0.9,14,14,1,3,D.u,D.u,D.u),e=[];e.push(d);c.filters=e};D.M.lm=function(b,c){c instanceof D.tc&&(c=c.ca(0));return(0,D.Ed)(b,c)};
D.M.y7=function(b,c){var d=D.M.hoa,e=D.M.eoa,f=D.M.GW,g;c&&(c.v("fill-type")&&(d=c.v("fill-type")),c.v("border-color")&&(e=c.v("border-color")),c.v("background-color")&&(f=c.v("background-color")),c.v("background")&&(g=c.v("background")));var e=new D.Vd(e),h;if("solid"==d)h=new D.Ud(f);else{var k,m,p;if(g&&0<=g.indexOf("linear-gradient")){if(d=(0,D.Wd)(g))p=d.Sj(),h=d.jl,k=d.il,m=d.bv}else h=f,k=D.M.h9,h!=D.M.GW&&(k=D.S.Xo(D.M.GW,D.M.h9,h)),h=[h,k],k=[0.6,0.8],m=[0,1],p=-270;h=new D.gd(p,h,k,m)}b.G(h);
b.Y(e)};
D.Hc={};D.F.l(D.Hc,D.F,"DvtCommonLegendDefaults");D.Hc.qY={rowColGap:6,separatorGap:7,indicatorSize:16,buttonSize:12,dwn:"#0572CE",ovr:"#5D5D5D",ena:"#7E7F80",separatorColor:"#D9DFE3"};D.Hc.rY={dwn:"#202F48",ovr:"#184DD8",ena:"#003D5B"};D.Hc.Rz={rowColGap:4,separatorGap:4,indicatorSize:11,buttonSize:11,dwn:"#000000",ovr:"#245EDD",ena:"#495D7C",separatorColor:"#ADB6C7"};D.Hc.pg=function(b){var c=D.Hc.$A(b);return b?D.xa.zb(b,c):c};
D.Hc.$A=function(b){var c=D.r;return c=b&&"skyros"===b.skin?D.xa.zb(D.Hc.rY,D.Hc.Rz):b&&"alta"===b.skin?D.xa.zb(D.Hc.qY,D.Hc.Rz):D.xa.clone(D.Hc.Rz)};
D.DvtCommonLegend=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.DvtCommonLegend,D.H,"DvtCommonLegend");D.DvtCommonLegend.F$="isLegendDisclosed";D.DvtCommonLegend.uqa="skin";D.E=D.DvtCommonLegend.prototype;D.E.Init=function(b,c,d,e,f){D.DvtCommonLegend.q.Init.call(this,b,D.r,c,d);this.xh=D.K.R();this.Q=this.MIa=c;this.W=d;this.BP={};this.I0={};this.jJ=[];this.$D=D.u;this.gq=[];this.$ya=this.iT=D.u;this.yK=[];this.$i=e;this.D=f;this.a1=D.u;this.mv=new D.Wb};D.E.Bx=(0,D.C)("mv");D.E.wz=(0,D.C)("a1");
D.E.YV=(0,D.B)("iF");D.E.c8=function(b){b&&(this.sB=b)};D.E.nb=(0,D.C)("bF");D.E.Le=(0,D.B)("bF");
D.dc=function(b,c,d,e,f){var g=c.o("label"),g=new D.bc(b.e,b,g,b.y3,b.D);g.L(d,e,f);if(c=c.pb())for(var h=0;h<c.length;h++){var k=c[h],m;if("item"==k.getName()){m=b;var p={};p.itemId=k.o("itemId");p.attributeGroupId=k.o("attributeGroupId");p.hideAttrs=k.o("hideAttrs");m=new D.cc(m.e,m,p,m.KK,m.D);k=k.pb();for(p=0;p<k.length;p++)if("marker"==k[p].getName()){var q=m,t=k[p],v=t.o("url"),w=t.o("shapeType"),A=t.o("color"),D$=t.o("pattern");(t=t.o("opacity"))&&(t=(0,window.parseFloat)(t));q.setMarker(v,
w,A,D$,t)}else"text"==k[p].getName()&&m.Rg(k[p].o("value"))}else"text"==k.getName()&&(m=new D.cc(b.e,b,D.r,b.KK,b.D),m.Rg(k.o("value")));m&&(m.L(g,e,f),g.ij(m))}d.k(g);e.y=e.y-b.D.rowColGap+b.D.rowColGap;return g};
D.ec=function(b,c,d,e,f){var g=new D.bc(b.e,b,c.label,b.y3,b.D);g.L(d,e,f);var h=c.item,k;if(h)for(var m=0;m<h.length;m++){var p=b;k=h[m];var q={};q.itemId=k.itemId;q.attributeGroupId=k.attributeGroupId;q.hideAttrs=k.hideAttrs;var p=new D.cc(p.e,p,q,p.KK,p.D),t=k.marker,q=t.url,v=t.shapeType,w=t.color,A=t.pattern;(t=t.opacity)&&(t=(0,window.parseFloat)(t));p.setMarker(q,v,w,A,t);p.Rg(k.text.value);if(k=p)k.L(g,e,f),g.ij(k)}if(c=c.text)for(m=0;m<c.length;m++)k=new D.cc(b.e,b,D.r,b.KK,b.D),k.Rg(c[m].value),
k&&(k.L(g,e,f),g.ij(k));d.k(g);e.y=e.y-b.D.rowColGap+b.D.rowColGap;return g};D.hc=function(b,c,d,e,f){var g=c.o("label"),h="true"==c.o("disclosed"),k=c.o("expandTooltip"),m=c.o("collapseTooltip"),g=new D.gc(b.e,b,g,b.w3,m,k,h,b.D);g.L(d,e,f);d=f?-1:1;if(c=c.pb())for(h=0;h<c.length;h++)k=c[h],"section"==k.getName()&&(e.x+=(b.D.buttonSize+b.D.rowColGap)*d,k=(0,D.dc)(b,k,g,e,f),e.x-=(b.D.buttonSize+b.D.rowColGap)*d,g.ij(k));e.y=e.y-b.D.rowColGap+b.D.rowColGap;return g};
D.ic=function(b,c,d,e,f){var g=new D.gc(b.e,b,c.label,b.w3,c.collapseTooltip,c.expandTooltip,"true"==c.disclosed,b.D);g.L(d,e,f);d=f?-1:1;if(c=c.section)for(var h=0;h<c.length;h++){e.x+=(b.D.buttonSize+b.D.rowColGap)*d;var k=(0,D.ec)(b,c[h],g,e,f);e.x-=(b.D.buttonSize+b.D.rowColGap)*d;g.ij(k)}e.y=e.y-b.D.rowColGap+b.D.rowColGap;return g};
D.lc=function(b,c,d){d.y=d.y-b.D.rowColGap+b.D.separatorGap;var e=new D.jc(b.e,d.x,d.y,d.x,d.y);(0,D.kc)(e);e.Ma(b.D.separatorColor);b.gq.push(e);var f;if("alta"==b.D.skin)f=e;else{d.y++;var g=new D.jc(b.e,d.x,d.y,d.x,d.y);g.Ma("#FFFFFF");(0,D.kc)(g);f=new D.H(b.e);f.k(e);f.k(g);b.gq.push(g)}c.k(f);d.y+=b.D.separatorGap;return f};
D.DvtCommonLegend.prototype.update=function(b,c){for(var d=this.Zd.indexOf(b),d=d+1;d<this.Zd.length;)this.Zd[d].O(this.Zd[d].K()+c),d++;this.Tc.j+=c;this.cc(new D.mc(this.Tc.g,this.Tc.j,0,0))};D.DvtCommonLegend.prototype.ld=(0,D.C)("xa");
D.DvtCommonLegend.prototype.L=function(){if(this.iF){this.xa=new D.nc(this.e,this.exa,this);this.wd=this.iF.o("label");this.bF="true"==this.iF.o("disclosed");var b=this.iF.getElementsByTagName("style");if(b&&(b=b[0].pb()))for(var c=0;c<b.length;c++){var d=b[c];"legend-title"==d.getName()?this.LK=d.getTextContent():"sectionGroup-title"==d.getName()?this.w3=d.getTextContent():"section-title"==d.getName()?this.y3=d.getTextContent():"legend-item"==d.getName()&&(this.KK=d.getTextContent())}if(b=this.iF.o("noWrap"))this.a1=
"false"==b;b=this.xh?new D.I(this.Q,0,this.Q,this.W):new D.I(0,0,this.Q,this.W);this.mn=new D.H(this.e);this.k(this.mn);if(this.wd&&(c=this.wz()?new D.oc(this.e):new D.pc(this.e),d=b.g-b.x,this.xh&&(d=b.g-d),0<d&&(this.xh&&c.Bi(),this.LK&&c.Ia(new D.P(this.LK)),c.od(this.wd),c.fa(b.x),c.ua(b.y),D.qc.Wb(c,d,b.j,this.mn),c.bf()&&this.xa.ma(c,new D.rc(this.wd)),(c=c.C())&&0<c.j)))b.y=b.y+c.j+this.D.rowColGap;this.Zd=[];if(d=this.iF.pb()){for(c=0;c<d.length;c++){var e=d[c];if("separatorDef"==e.getName()&&
(e=e.pb(),0<e.length&&"separator"==e[0].getName())){this.$D=D.o;break}}for(c=0;c<d.length;c++)e=d[c],b.x=this.xh?this.Q:0,"sectionGroup"==e.getName()?(this.$D&&(this.wd||1<c)&&this.Zd.push((0,D.lc)(this,this.mn,b)),this.Zd.push((0,D.hc)(this,e,this.mn,b,this.xh))):"section"==e.getName()&&(this.$D&&(this.wd||1<c)&&this.Zd.push((0,D.lc)(this,this.mn,b)),this.Zd.push((0,D.dc)(this,e,this.mn,b,this.xh)))}}else{this.xa=new D.nc(this.e,this.exa,this);this.wd=this.sB.label;this.bF="true"==this.sB.disclosed;
if(b=this.sB.style)this.LK=b["legend-title"],this.w3=b["sectionGroup-title"],this.y3=b["section-title"],this.KK=b["legend-item"];if(b=this.sB.noWrap)this.a1="false"==b;b=this.xh?new D.I(this.Q,0,this.Q,this.W):new D.I(0,0,this.Q,this.W);this.mn=new D.H(this.e);this.k(this.mn);if(this.wd&&(c=this.wz()?new D.oc(this.e):new D.pc(this.e),d=b.g-b.x,this.xh&&(d=b.g-d),0<d&&(this.xh&&c.Bi(),this.LK&&c.Ia(new D.P(this.LK)),c.od(this.wd),c.fa(b.x),c.ua(b.y),D.qc.Wb(c,d,b.j,this.mn),c.bf()&&this.xa.ma(c,new D.rc(this.wd)),
(c=c.C())&&0<c.j)))b.y=b.y+c.j+this.D.rowColGap;this.Zd=[];if(d=this.sB.separatorDef)for(c=0;c<d.length;c++)if((e=d[c].separator)&&0<e.length){this.$D=D.o;break}d=this.sB.sectionGroup;b.x=this.xh?this.Q:0;if(d)for(c=0;c<d.length;c++)this.$D&&(this.wd||1<c)&&this.Zd.push((0,D.lc)(this,this.mn,b)),this.Zd.push((0,D.ic)(this,d[c],this.mn,b,this.xh));if(d=this.sB.section)for(c=0;c<d.length;c++)this.$D&&(this.wd||1<c)&&this.Zd.push((0,D.lc)(this,this.mn,b)),this.Zd.push((0,D.ec)(this,d[c],this.mn,b,this.xh))}this.Tc=
this.C();for(b=0;b<this.gq.length;b++)this.xh?(this.Tc.x=this.gq[b].Gi()-this.Tc.g,this.gq[b].ki(this.Tc.x)):this.gq[b].ki(this.Tc.g+this.gq[b].Gi());this.xa.$e(this);for(c=0;c<this.jJ.length;c++)b=this.jJ[c],this.xa.ma(b,b),this.yK&&-1<D.Jb.Fa(this.yK,b.lj()+":"+b.Aw())&&(0,D.sc)(b);this.xh&&this.mn.F(-this.Tc.x)};D.gc=function(b,c,d,e,f,g,h,k){this.Init(b,c,d,e,f,g,h,k)};D.F.l(D.gc,D.H,"DvtCommonLegendSection");
D.gc.prototype.Init=function(b,c,d,e,f,g,h,k){D.bc.q.Init.call(this,b);this.wd=d;this.Xy=e;this.vb=[];this.Na=c;this.FA=f;this.UA=g;this.FJ=h?0:1;this.D=k};
D.uc=function(b,c,d,e,f,g,h){if(!c)return new D.tc(b.e);switch(h){case 1:h=new D.Ma(b.e,c.groupColEna,d,e,f,g);var k=new D.Ma(b.e,c.groupColOvr,d,e,f,g);c=new D.Ma(b.e,c.groupColDwn,d,e,f,g);return new D.tc(b.e,h,k,c);default:return h=new D.Ma(b.e,c.groupExpDwn,d,e,f,g),k=new D.Ma(b.e,c.groupExpOvr,d,e,f,g),c=new D.Ma(b.e,c.groupExpDwn,d,e,f,g),new D.tc(b.e,h,k,c)}};D.E=D.gc.prototype;
D.E.Bea=function(){this.e.hd().oc();var b=D.K.R()?-1:1;this.x3||(this.x3=this.C().j-this.Jv);0==this.FJ?("alta"==this.D.skin?(b=this.Kb.getParent(),b.removeChild(this.Kb),this.Kb=this.Qx,b.k(this.Kb)):this.Kb.gc([this.kr+1.5*b,this.lr+1.5,this.kr+9.5*b,this.lr+5.5,this.kr+1.5*b,this.lr+9.5]),this.lfa=D.u,this.FJ=1,b=-this.x3):("alta"==this.D.skin?(b=this.Kb.getParent(),b.removeChild(this.Kb),this.Kb=this.Av,b.k(this.Kb)):this.Kb.gc([this.kr+1.5*b,this.lr+1.5,this.kr+9.5*b,this.lr+1.5,this.kr+5.5*
b,this.lr+9.5]),this.lfa=D.o,this.FJ=0,b=this.x3);if(this.lfa)for(var c=0;c<this.vb.length;c++)this.k(this.vb[c]);else for(c=0;c<this.vb.length;c++)this.removeChild(this.vb[c]);this.Na.update(this,b)};D.E.mR=function(b){var c;c=0==this.FJ?this.FA:this.UA;c!=D.r&&this.e.hd().UH(b.pageX,b.pageY,c,this.Kb,D.o);"alta"==!this.D.skin&&this.Kb.na(this.D.ovr)};D.E.lR=function(){this.e.hd().oc();"alta"==!this.D.skin&&this.Kb.na(this.D.ena)};D.E.kR=function(){"alta"==!this.D.skin&&this.Kb.na(this.D.dwn)};
D.E.ij=function(b){return this.vb.push(b)};
D.E.L=function(b,c,d){b.k(this);b=new D.H(this.e);this.k(b);this.kr=c.x;this.lr=c.y;var e=d?-1:1;if("alta"==this.D.skin){var f=this.Na.$i;this.Av=(0,D.uc)(this,f,this.kr,this.lr,this.D.buttonSize,this.D.buttonSize,0);this.Qx=(0,D.uc)(this,f,this.kr,this.lr,this.D.buttonSize,this.D.buttonSize,1);this.Kb=this.Av}else this.Kb=new D.vc(this.e,[this.kr+1.5*e,this.lr+1.5,this.kr+9.5*e,this.lr+1.5,this.kr+5.5*e,this.lr+9.5]),this.Kb.na(this.D.ena);b.k(this.Kb);D.K.da()?b.P(D.Ta.Rd,this.Bea,D.u,this):(b.P(D.Ua,
this.Bea,D.u,this),b.P(D.Va,this.mR,D.u,this),b.P(D.Wa,this.lR,D.u,this),b.P(D.wc,this.kR,D.u,this));this.FJ=0;c.x+=(("alta"==this.D.skin&&d?0:this.D.buttonSize)+this.D.rowColGap)*e;this.wd&&(e=this.Na.wz()?new D.oc(this.e):new D.pc(this.e),f=c.g-c.x,d&&(f=c.g-f),0<f&&(d&&e.Bi(),this.Xy&&e.Ia(new D.P(this.Xy)),e.od(this.wd),e.fa(c.x),e.ua(c.y),D.qc.Wb(e,f,c.j,b),e.bf()&&this.Na.ld().ma(e,new D.rc(this.wd)),b=e.C(),c.y=c.y+window.Math.max(b?b.j:0,this.D.buttonSize)+this.D.rowColGap));c.x+=(this.D.buttonSize+
this.D.rowColGap)*(d?1:-1);this.Jv=this.C().j};D.bc=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.bc,D.H,"DvtCommonLegendSection");D.bc.prototype.Init=function(b,c,d,e,f){D.bc.q.Init.call(this,b);this.wd=d;this.Xy=e;this.vb=[];this.Na=c;this.D=f};D.bc.prototype.ij=function(b){return this.vb.push(b)};D.bc.prototype.oU=(0,D.C)("vb");
D.bc.prototype.L=function(b,c,d){b.k(this);if(this.wd){b=this.Na.wz()?new D.oc(this.e):new D.pc(this.e);var e=c.g-c.x;d&&(e=c.g-e);0<e&&(d&&b.Bi(),this.Xy&&b.Ia(new D.P(this.Xy)),b.od(this.wd),b.fa(c.x),b.ua(c.y),D.qc.Wb(b,e,c.j,this),b.bf()&&this.Na.ld().ma(b,new D.rc(this.wd)),d=b.C(),c.y=c.y+(d?d.j:0)+this.D.rowColGap)}};D.cc=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.cc,D.H,"DvtCommonLegendRow");D.E=D.cc.prototype;
D.E.Init=function(b,c,d,e,f){D.cc.q.Init.call(this,b);this.Na=c;this.Jo=d;this.jfa=e;this.OP=D.u;this.D=f};D.E.lj=function(){return this.Jo.attributeGroupId};D.E.Aw=function(){return this.Jo.itemId};D.E.Y5=function(){return this.Jo.hideAttrs};D.E.Rg=(0,D.B)("Ya");D.E.setMarker=function(b,c,d,e,f){this.vT=b;this.J=c;this.xg=d?d:"#000000";this.Io=e;this.r2=f};D.sc=function(b){b.OP=!b.OP;b.nn.fD(b.xg);(0,D.xc)(b,"label",b.Ya+". "+(0,D.Na)(b.Na.Bx(),b.OP?"STATE_HIDDEN":"STATE_VISIBLE"))};
D.cc.prototype.L=function(b,c,d){if(this.Jo){var e=this.Na,f=this.Jo.attributeGroupId,g=this.Jo.itemId;e.BP[f]==D.r&&(e.BP[f]={});e.BP[f][g]=this;this.Na.jJ.push(this);e=this.Na;f=this.Jo.hideAttrs;e.I0[f]||(e.I0[f]=this)}b.k(this);b=c.x;d&&(c.x-=this.D.indicatorSize);var h;if(this.vT||this.J!=D.r)h=new D.Lb(this.e,this.vT?[this.vT]:this.J,this.D[D.DvtCommonLegend.uqa],c.x,c.y,this.D.indicatorSize,this.D.indicatorSize),e=D.yc.Aka(this.e,this.J),!this.vT&&!e&&(this.Io?h.G(new D.zc(this.Io,this.xg)):
h.na(this.xg,this.r2)),this.k(h),c.x=d?c.x-this.D.rowColGap:c.x+this.D.indicatorSize+this.D.rowColGap;this.nn=h;h=new D.I;this.Ya&&(this.Na.iT&&((0,D.Ac)(this,"img"),(0,D.xc)(this,"label",this.Ya+". "+(0,D.Na)(this.Na.Bx(),"STATE_VISIBLE"))),e=c.g-c.x,d&&(e=c.g-e),0>e?this.Na.ld().ma(this.nn,new D.rc(this.Ya)):(f=this.Na.wz()?new D.oc(this.e):new D.pc(this.e),d&&f.Bi(),this.jfa&&f.Ia(new D.P(this.jfa)),f.od(this.Ya),f.fa(c.x),f.ua(c.y),D.qc.Wb(f,e,c.j,this)?(h=f.C(),f.bf()&&this.Na.ld().ma(f,new D.rc(this.Ya))):
this.Na.ld().ma(this.nn,new D.rc(this.Ya))));c.y=c.y+window.Math.max(this.D.indicatorSize,h.j)+this.D.rowColGap;c.x=b};D.nc=function(b,c,d){this.Init(b,c,d);this.Na=d};D.F.l(D.nc,D.Bc,"DvtCommonLegendEventManager");D.E=D.nc.prototype;D.E.Vg=function(b){D.nc.q.Vg.call(this,b);this.iy(b)};D.E.ao=function(b){D.nc.q.ao.call(this,b);(0,D.Cc)(this,b)};D.E.dk=function(b){D.nc.q.dk.call(this,b);(0,D.Cc)(this,b)};D.E.Ns=function(b){D.nc.q.Ns.call(this,b);this.iy(b)};
D.E.iy=function(b){if(this.Na.iT){var c=(0,D.Dc)(this,b.target);if(c instanceof D.cc){var d=c.Aw(),e=c.lj();(0,D.sc)(c);b=new D.Ec(d,e,c.OP?"hide":"show",b);this.Na.cc(b)}}};D.Cc=function(b,c){var d=(0,D.Dc)(b,c.target);if(d instanceof D.cc){if(b.Na.$ya){var e=d.Aw(),f=d.lj(),e=new D.Fc(e,f,d.Y5(),c.type,c);b.Na.cc(e)}b.Na.iT&&(0,D.Gc)(b,d)}};
});