define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.po=function(b,c){this.Init(c===D.u?"sunburstRotationInput":"sunburstRotation");this.Nc=b};(0,D.ta)("DvtSunburstRotationEvent",D.po);D.F.l(D.po,D.Jc,"DvtSunburstRotationEvent");D.po.TYPE="sunburstRotation";D.po.TYPE_INPUT="sunburstRotationInput";D.po.prototype.ula=(0,D.C)("Nc");D.po.prototype.getStartAngle=D.po.prototype.ula;
D.lt=function(b,c,d){this.Init(b,c,d)};D.F.l(D.lt,D.Po,"DvtBaseSunburst");D.E=D.lt.prototype;D.E.Init=function(b,c,d){D.lt.q.Init.call(this,b,c,d);this.ef=new D.mt;this.Xc=2*window.Math.PI};D.E.Tu=function(b){return(new D.nt(this)).parse(b)};D.E.aI=function(b){D.lt.q.aI.call(this,b);this.fia=b.rotation;this.eia=D.K.Md()?"url("+this.ih.cursorRotate+"), auto":"url("+this.ih.cursorRotate+") 8 8, auto";this.Nc=(360-b.$V)*D.ot/360;this.Nc>window.Math.PI&&(this.Nc-=D.ot)};
D.E.Zn=function(b){var c=window.Math.max(window.Math.ceil(3*window.Math.min(b.g,b.j)/400),2);b.x+=c;b.y+=c;b.g-=2*c;b.j-=2*c;(0,D.To)(this,b);(0,D.Uo)(this,b);this.Xia=window.Math.floor(window.Math.min(b.g,b.j)/2);this.kb&&D.pt.In(this.Xia,this.kb,this.Nc,this.Xc,this.aP)};
D.E.Vm=function(b,c){this.RO(b,"");this.am&&b.k(this.am);this.Na&&(b.k(this.Na),this.Na=D.r);this.vG=new D.R(c.x+c.g/2,c.y+c.j/2);if("on"==this.fia&&(0,D.Vo)(this)){var d=D.K.da()?60:15,d=new D.Rd(this.e,c.x+c.g/2,c.y+c.j/2,this.Xia+d);(0,D.ed)(d);d.setCursor(this.eia);b.k(d);this.Va().ma(d,new D.qt(D.r,"_rotationShape"))}d=new D.H(this.e);(0,D.Ya)(d,this.vG.x,this.vG.y);b.k(d);if((0,D.Vo)(this)){var e=new D.H(this.e);d.k(e);this.kb.L(e);this.Qt=new D.H(this.e);d.k(this.Qt);this.Lea=new D.H(this.e);
d.k(this.Lea)}else(0,D.Wo)(this,b)};D.E.xW=function(b,c,d,e){return new D.rt(b,c,d,e)};D.E.ZW=function(b,c){if("fan"===this.hW&&(0,D.Vo)(this)){this.qZ(0);var d=new D.Mj(this.e,this,this.tD);(0,D.N)(d.S,"typeNumber",this,this.ova,this.qZ,2*window.Math.PI);return d}return D.lt.q.ZW.call(this,b,c)};D.E.XW=function(){var b=D.lt.q.XW.call(this);b&&(0,D.Ya)(b,this.vG.x,this.vG.y);return b};
D.E.rp=function(){if(!this.iW){this.ga.Mi();var b=new D.I(0,0,this.ub,this.Ob);this.Zn(b);this.Vm(this.ga,b);for(var b=this.Mb?this.Mb.getSelection():[],c=0;c<b.length;c++)b[c].Pb(D.o)}this.Xc<2*window.Math.PI&&this.qZ(2*window.Math.PI);D.lt.q.rp.call(this)};D.E.nP=function(b){this.Qt.k(b);D.K.Yo()||((0,D.df)(this.Qt),(0,D.cf)(this.Qt,D.st))};D.E.ova=(0,D.C)("Xc");D.E.qZ=function(b){this.Xc=b;this.Zn(new D.I(0,0,this.ub,this.Ob));this.kb&&(0,D.tt)(this.kb,D.o)};
D.ut=function(b,c){b.K_=c;b.VF=new D.cd(b.e,0,0,b.ub,b.Ob);(0,D.ed)(b.VF);b.VF.setCursor(b.eia);b.k(b.VF);b.Va().ma(b.VF,new D.qt(D.r,"_rotationShape"))};D.vt=function(b,c){var d=c-b.K_;b.K_=c;b.Nc+=d;b.Nc<-window.Math.PI?b.Nc+=2*window.Math.PI:b.Nc>window.Math.PI&&(b.Nc-=2*window.Math.PI);b.Zn(new D.I(0,0,b.ub,b.Ob));b.kb&&(0,D.tt)(b.kb,D.o);b.ib(new D.po(360-window.Math.round(180*b.Nc/window.Math.PI),D.u))};
D.wt=function(b){b.K_=D.r;b.removeChild(b.VF);b.VF=D.r;var c=360-window.Math.round(180*b.Nc/window.Math.PI);b.ib(new D.po(c,D.u));b.ib(new D.po(c,D.o))};D.xt=function(b,c,d){return window.Math.atan2(d-b.vG.y,c-b.vG.x)};
D.yt=(0,D.z)();(0,D.ta)("DvtSunburst",D.yt);D.F.l(D.yt,D.lt,"DvtSunburst");D.yt.newInstance=function(b,c,d){var e=new D.yt;e.Init(b,c,d);return e};D.yt.getDefaults=function(b){return(0,D.Tb)(new D.mt,b)};D.yt.prototype.L=function(b,c,d){b?(this.X=this.ef.pg(b),D.K.Kh()||(this.X.animationOnDisplay="none",this.X.animationOnDataChange="none")):this.X||(this.X=(0,D.Xb)(this));b=(new D.zt).q8(this.X);D.yt.q.L.call(this,b,c,d)};D.yt.prototype.render=D.yt.prototype.L;
D.nt=function(b){this.Init(b)};D.F.l(D.nt,D.PB,"DvtSunburstParser");D.nt.prototype.Pm=function(b,c,d){return new D.yD(b,c,d)};D.nt.prototype.Ul=function(b){var c=D.nt.q.Ul.call(this,b);c.rotation=b.o("r");c.$V=b.o("sa");if(c.$V===D.r||(0,window.isNaN)(c.$V))c.$V=90;return c};D.nt.prototype.Uu=function(b){var c=D.nt.q.Uu.call(this,b);c.bV=b.o("ha");c.tFa=b.o("r");return c};
D.nt.prototype.RX=function(b,c,d,e){e.NODE_DEFAULT_COLOR_STYLE=b.v("border-color");e.NODE_HOVER_COLOR_STYLE=c.v("border-color");e.NODE_SELECTED_INNER_COLOR_STYLE=d.v("-tr-inner-color");e.NODE_SELECTED_OUTER_COLOR_STYLE=d.v("-tr-outer-color")};
D.yD=function(b,c,d){this.Init(b,c,d);this.zo=c.aV?c.aV:"auto";this.dF=c.bV;this.Mj=c.tFa};D.F.l(D.yD,D.cC,"DvtSunburstNode");D.ot=2*window.Math.PI;D.E=D.yD.prototype;
D.E.L=function(b){if(this.Iv){this.mS=b;this.J=this.H_();b.k(this.J);var c=this.TL;if(!this.Ye&&(0==this.Xh&&this.Xc==D.ot)&&c){var d=window.Math.sqrt(2),e=this.yh*d-4;this.Za=-this.yh/d+2;this.Ja=-this.yh/d+2;d=this.I.lZ;d.ro=this.Sh;0<e&&0<e&&((0,D.nr)(d,e),(0,D.or)(d,e),d.tf((0,D.dC)(this)),this.v_=c=D.hq.aD(d,c,this.J),d=c.C(),(0,D.Ya)(c,this.Za+(e-d.g)/2,this.Ja+(e-d.j)/2))}else this.Ya=this.SJ(this.J),this.Ya!=D.r&&(this.J.k(this.Ya),this.Io&&(d=this.Ya.Vb(),this.Oo=new D.cd(this.I.e,d.x,d.y,
d.g,d.j),this.Oo.na("#FFFFFF"),this.Oo.la(D.u),this.J.k(this.Oo),e=this.Ya.pa(),(0,D.Ue)(e)||this.Oo.qa(e),this.J.k(this.Ya)));(0,D.Ac)(this.J,"img");(0,D.xc)(this.J,"label",this.ay);this.Du(b)}};D.E.Pb=function(b){"off"!=this.VO&&(D.yD.q.Pb.call(this,b),this.lb()?(this.J.Pb(D.o),this.I.nP(this.J)):(this.J.Pb(D.u),this.mS&&this.mS.k(this.J)))};D.E.Bc=function(){this.J&&this.Iv&&(this.J.Bc(),this.lb()?this.I.nP(this.J):this.I.Lea.k(this.J))};
D.E.qc=function(){this.J&&(this.Iv&&!this.ji())&&(this.J.qc(),!this.lb()&&this.mS&&this.mS.k(this.J))};
D.E.lh=function(b){var c,d,e,f;if(b.type==D.Ua)return D.yD.q.lh.call(this,b);c=b.keyCode;if(32==c&&b.ctrlKey)return this;for(f=this;f.Ye;)f=f.Ye;d=(0,D.kC)(this,f,(0,D.jC)(this));a:{for(e=0;e<d.length;e++)if(this===d[e])break a;e=-1}var g=this.Nc+this.Xc/2,g=(0,D.CD)(g);switch(c){case 38:if(this===f||180<g){if(c=this.SR)if(d=c.Nc+c.Xc/2,d=(0,D.CD)(d),180<d)return c;b=(0,D.Tn)(this,b,(0,D.So)(this))}else b=(0,D.DD)(this);break;case 40:if(this===f||0<=g&&180>=g){if(c=this.SR)if(d=c.Nc+c.Xc/2,d=(0,D.CD)(d),
0<=d&&180>=d)return c;b=(0,D.Tn)(this,b,(0,D.So)(this))}else b=(0,D.DD)(this);break;case 37:b=1==d.length?this:0==e?d[d.length-1]:d[e-1];break;case 39:b=1==d.length?this:e==d.length-1?d[0]:d[e+1];break;default:b=this}(0,D.iC)(b);return b};D.DD=function(b){var c=b.Ye;c&&(b=c,(0,D.iC)(c));(0,D.iC)(b);return b};D.CD=function(b){b=D.Ye.J7(b);0>b?b+=360:360<b&&(b-=360);return b};D.E=D.yD.prototype;
D.E.He=function(){if(this.J){var b=this.J.C(),c=new D.R(b.x,b.y),c=(0,D.Ce)(this.J,c);b.x=c.x;b.y=c.y;return b}return new D.I(0,0,0,0)};D.E.iU=function(){return(0,D.Ce)(this.J,(0,D.ED)(0.5*(this.yh+this.Xh),this.Nc+this.Xc/2))};D.E.JN=function(b,c,d,e){this.Xh=b;this.yh=c;this.Nc=d;this.Xc=e;this.Iv=D.o};D.E.BD=function(){return this.wZ?(0,D.Vf)():D.yD.q.BD.call(this)};D.E.al=function(){var b=D.S.gd(this.xg),c=D.S.fd(this.xg),d=D.S.dd(this.xg);return[this.Xh,this.yh,this.Nc,this.Xc,b,c,d]};
D.E.fo=function(b){this.JN(b[0],b[1],b[2],b[3]);this.xg=D.S.Ow(window.Math.round(b[4]),window.Math.round(b[5]),window.Math.round(b[6]));(0,D.tt)(this,D.u)};D.E.Ef=function(b,c){c.Iv&&0<c.Xc?D.yD.q.Ef.call(this,b,c):this.Ig(b)};D.E.contains=function(b,c){var d=(0,D.FD)(b,c);return window.Math.sqrt(b*b+c*c)>=this.Xh&&window.Math.sqrt(b*b+c*c)<=this.yh&&(0,D.GD)(this,d)};D.GD=function(b,c){for(;c<b.Nc;)c+=D.ot;for(;c-b.Nc>D.ot;)c-=D.ot;return c>=b.Nc&&c<=b.Nc+b.Xc};
D.ED=function(b,c){return{x:window.Math.cos(c)*b,y:window.Math.sin(c)*b}};D.FD=function(b,c){var d=window.Math.atan2(c,b);0>d?d+=D.ot:d>D.ot&&(d-=D.ot);return d};
D.yD.prototype.H_=function(){if(!this.Xc||0>=this.Xc)return D.r;var b=(0,D.HD)(this),b=new D.Ra(this.I.e,b);this.I.Va().ma(b,this);b.B(this.Z());b.G(this.BD());var c=(0,D.hC)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR_STYLE"),d=(0,D.hC)(this,"#000000","NODE_SELECTED_OUTER_COLOR_STYLE"),e=(0,D.hC)(this,"#FFFFFF","NODE_HOVER_COLOR_STYLE");b.Y(new D.Vd((0,D.hC)(this,"#FFFFFF","NODE_DEFAULT_COLOR_STYLE"),0.3));b.Mq(new D.Vd(e,1,3));b.Oq(new D.Vd(c,1,1.5),new D.Vd(d,1,3.5));b.Hu(new D.Vd(e,1,3));b.ug(this.I.Z1!=
D.r&&"off"!=this.VO);this.wZ&&(b.B(0.001),b.la(D.u));return b};
D.HD=function(b){var c,d,e,f;b.Xc<D.ot?(c=(0,D.ED)(b.yh,b.Nc),d=(0,D.ED)(b.yh,b.Nc+b.Xc),e=(0,D.ED)(b.Xh,b.Nc+b.Xc),f=(0,D.ED)(b.Xh,b.Nc),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.yh,b.yh,b.Xc,1,d.x,d.y)+window.DvtPathUtils.lineTo(e.x,e.y)+window.DvtPathUtils.arcTo(b.Xh,b.Xh,b.Xc,0,f.x,f.y)+window.DvtPathUtils.closePath()):(c=(0,D.ED)(b.yh,b.Nc),d=(0,D.ED)(b.yh,b.Nc+b.Xc/2),e=(0,D.ED)(b.Xh,b.Nc),f=(0,D.ED)(b.Xh,b.Nc+b.Xc/2),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.yh,
b.yh,b.Xc/2,1,d.x,d.y)+window.DvtPathUtils.arcTo(b.yh,b.yh,b.Xc/2,1,c.x,c.y),0<b.Xh&&(c+=window.DvtPathUtils.moveTo(f.x,f.y)+window.DvtPathUtils.arcTo(b.Xh,b.Xh,b.Xc/2,0,e.x,e.y)+window.DvtPathUtils.arcTo(b.Xh,b.Xh,b.Xc/2,0,f.x,f.y)),c+=window.DvtPathUtils.closePath());return c};
D.yD.prototype.SJ=function(b){if(!this.Wy||!b||!this.zo||"off"==this.zo)return D.r;var c=D.u;"auto"==this.zo?c=!D.K.Md()&&D.K.CCa()==D.K.Laa?D.u:D.o:"rotated"==this.zo&&(c=D.o);if(c&&this.Xc<2*window.Math.PI){var d=window.Math.max(this.Xh,10),e=this.yh-d-6,f=1.1*this.Xc*(d+6);if(6>=f)b=D.r;else if(c=new D.pc(this.I.e,this.Wy,0,0),c.tf((0,D.dC)(this)),(0,D.nC)(this,c),D.qc.Wb(c,e,f,b)){f=(d+this.yh)/2;if("s"==this.dF||"e"==this.dF)b.k(c),b=c.C().g,"s"==this.dF?f=d+4.5+b/2:"e"==this.dF&&(f=d+e-4.5-
b/2);b=(0,D.ED)(f,this.Nc+this.Xc/2);c.of();c.Ce();d=this.Nc+this.Xc/2;d=d>=D.ot?d-D.ot:d;d=0>d?d+D.ot:d;d>0.5*window.Math.PI&&d<1.5*window.Math.PI&&(d+=window.Math.PI);c.Oi(d);(0,D.Ya)(c,b.x,b.y);c.la(D.u);b=c}else b=D.r}else{if(0==this.Xh)c={x:0,y:0};else if(c=(0,D.ED)((this.Xh+this.yh)/2,this.Nc+this.Xc/2),d=3*(0,D.dC)(this)/2,e=(0,D.FD)(c.x+d/2,c.y),!(0,D.GD)(this,(0,D.FD)(c.x-d/2,c.y))||!(0,D.GD)(this,e))c=D.r;if(c){d=new D.pc(this.I.e,this.Wy,c.x,c.y,D.r);d.tf((0,D.dC)(this));(0,D.nC)(this,
d);d.of();d.Ce();d.la(D.u);for(var e=D.qc.Xj(d),g=f=c.x,h=c.y-e.j/2,k=c.y+e.j/2;this.contains(f,h)&&this.contains(f,k);)f--;for(;this.contains(g,h)&&this.contains(g,k);)g++;f+=3;g-=3;c=2*window.Math.min(c.x-f,g-c.x);c<e.g&&(d.fa((f+g)/2),c=g-f);b=D.qc.Wb(d,c,e.j,b)?d:D.r}else b=D.n}return b};
D.yD.prototype.Jw=function(){if(!this.Mc){var b;b=this.J;if(!b||!("i"==this.EE||"ir"==this.EE))b=D.r;else{var c;if(this.eg){c=this.I.e;var d=this.I.ih,e=new D.Ma(c,d.collapseUp,0,0,16,16),f=new D.Ma(c,d.collapseOver,0,0,16,16),d=new D.Ma(c,d.collapseDown,0,0,16,16)}else c=this.I.e,d=this.I.ih,e=new D.Ma(c,d.expandUp,0,0,16,16),f=new D.Ma(c,d.expandOver,0,0,16,16),d=new D.Ma(c,d.expandDown,0,0,16,16);(0,D.ed)(e);(0,D.ed)(f);(0,D.ed)(d);c=new D.tc(c,e,f,d);c.P(D.Ua,this.p5,D.u,this);e=(0,D.ED)(this.yh,
this.Nc+this.Xc/2);(0,D.Ya)(c,e.x-8,e.y-8);b.k(c);b=this.eg?this.I.ih.collapse:this.I.ih.expand;this.I.Va().ma(c,new D.qt(this,this.getId(),b));b=c}this.Mc=b}D.yD.q.Jw.call(this)};D.yD.prototype.Cq=function(){this.Mc&&this.J&&(this.J.removeChild(this.Mc),this.Mc=D.r);D.yD.q.Cq.call(this)};
D.tt=function(b,c){if(b.J){var d=(0,D.HD)(b);b.J.Zj(d);if(b.Ye||!(0==b.Xh&&b.Xc==D.ot))b.Ya&&b.J.removeChild(b.Ya),b.Ya=b.SJ(b.J),b.Oo&&(b.J.removeChild(b.Oo),b.Oo=D.r);b.J.G(b.BD());if(c)for(var d=b.pb(),e=0;e<d.length;e++)(0,D.tt)(d[e],D.o)}};
D.yD.prototype.p5=function(){this.eg=!this.eg;var b=this.I,c=this.eg,d=this.getId();b.$K=d;if(c)b.ib(new D.AD("sunburstExpand",this.getId()));else{var c=b.CX,d=this.getId(),d=c.indexOf('\x3cn id\x3d"'+d),e=c.indexOf("\x3e",d),f=c.substring(d,e),f=-1<f.indexOf("di\x3d")?f.replace('di\x3d"t"','di\x3d"f"'):f+'di\x3d"f"';b.L(c.substring(0,d)+f+c.substring(e),b.ub,b.Ob);b.ib(new D.AD("sunburstCollapse",this.getId()))}};D.yD.prototype.nb=(0,D.C)("eg");
D.BD=function(b){return b.Mj!=D.r?(0,window.Number)(b.Mj):b.Ye?1:b.wZ?0.25:b.TL?1:0.5};
D.pt={};D.F.l(D.pt,D.F,"DvtSunburstLayout");D.pt.In=function(b,c,d,e,f){var g=D.pt.Aca(c);D.pt.Af(b/g,c,d,e,f,0)};D.pt.Af=function(b,c,d,e,f,g){var h=g+(0,D.BD)(c)*b;c.JN(g,h,d,e);g=c.pb();if(g!=D.r&&c.nb()){"on"==f&&(g=g.slice(0),g.sort(function(b,c){return c.vc()-b.vc()}));D.K.R(c.I.e)&&(g=g.slice(0).reverse());var k=0;for(c=0;c<g.length;c++)k+=0<g[c].vc()?g[c].vc():0;for(c=0;c<g.length;c++){var m=g[c];if(!(0>=m.vc())){var p=m.vc()/k*e;D.pt.Af(b,m,d,p,f,h);d+=p}}}};
D.pt.Aca=function(b){var c=0,d=b.pb();if(d&&0<d.length){for(var e=0;e<d.length;e++)var f=D.pt.Aca(d[e]),c=window.Math.max(c,f);return c+(0,D.BD)(b)}return(0,D.BD)(b)};
D.AD=function(b,c){this.Init(b);this.Ra=c?c:D.r};D.F.l(D.AD,D.Jc,"DvtSunburstExpandCollapseEvent");D.AD.prototype.getId=(0,D.C)("Ra");
D.rt=function(b,c,d,e){D.Sp.call(this,b,c,d,e)};D.F.l(D.rt,D.Sp,"DvtSunburstEventManager");D.E=D.rt.prototype;D.E.bl=function(b){var c=(0,D.Dc)(this,b.target);c&&c.getId&&"_rotationShape"==c.getId()&&!this.YP?(this.YP=D.o,b=(0,D.og)(this.e,b.pageX,b.pageY),c=this.I,(0,D.ut)(c,(0,D.xt)(c,b.x,b.y))):D.rt.q.bl.call(this,b)};D.E.Sm=function(b){if(this.YP){b=(0,D.og)(this.e,b.pageX,b.pageY);var c=this.I;(0,D.vt)(c,(0,D.xt)(c,b.x,b.y))}else D.rt.q.Sm.call(this,b)};
D.E.Tm=function(b){this.YP?(this.YP=D.u,(0,D.wt)(this.I)):D.rt.q.Tm.call(this,b)};D.E.Vl=function(b){var c=D.o,d=b.keyCode,e=(0,D.im)(this),f=this.I;("i"==e.EE||"ir"==e.EE)&&((0,D.ui)(b)&&!e.nb()||(0,D.vi)(b)&&e.nb()||b.ctrlKey&&13==d)?(e.p5(),b.preventDefault()):f&&"on"==f.fia&&(37==d||39==d)&&!b.ctrlKey&&b.altKey&&b.shiftKey?(d=37==d?-5*(window.Math.PI/180):5*(window.Math.PI/180),(0,D.ut)(f,0),(0,D.vt)(f,d),(0,D.wt)(f),b.preventDefault()):c=D.rt.q.Vl.call(this,b);return c};
D.E.ED=function(b){var c=(0,D.Dc)(this,b.target);c&&(c.getId&&"_rotationShape"==c.getId())&&(0,D.Di)(b,this.oqa,this)};D.E.yO=function(b){(0,D.Ei)(this.Qb,b,"rotateKey")};D.E.xO=function(b){(0,D.Pi)(this.Qb,b,"rotateKey")};D.E.oqa=function(b,c){if(1>=(0,D.Xi)(this.Qb,"rotateKey").length){(0,D.oh)(this.Qb,c.identifier,"rotateKey",D.r,"rotateKey","rotateKey",this.nqa,this.mqa,this);(0,D.Yi)(this.Qb,c.identifier,D.u);var d=(0,D.og)(this.e,c.pageX,c.pageY),e=this.I;(0,D.ut)(e,(0,D.xt)(e,d.x,d.y));b.Wr()}};
D.E.nqa=function(b,c){var d=(0,D.og)(this.e,c.pageX,c.pageY),e=this.I;(0,D.vt)(e,(0,D.xt)(e,d.x,d.y));b.preventDefault()};D.E.mqa=function(){(0,D.wt)(this.I)};
D.zD=(0,D.z)();D.F.l(D.zD,D.dm,"DvtSunburstBundle");D.zD._defaults={COLOR:"Color",SIZE:"Size"};D.zD.prototype.Fs=function(b){return D.zD._defaults[b]};D.zD.prototype.ax=(0,D.ca)("DvtSunburstBundle");
D.mt=function(){this.Init({skyros:D.ID,alta:{}})};D.F.l(D.mt,D.qC,"DvtSunburstDefaults");D.ID={rotation:"on"};
D.zt=(0,D.z)();D.F.l(D.zt,D.YB,"DvtSunburstJsonUtils");D.E=D.zt.prototype;D.E.qO=(0,D.ca)("sunburst");D.E.UI=function(b){var c=D.zt.q.UI.call(this,b),c=c+this.Ca("r",b.rotation),c=c+this.Ca("sa",(b.startAngle+360)%360);b=b.animationOnDisplay;return c="auto"==b?c+this.Ca("adi","fan"):c+this.Ca("adi",b)};
D.E.VI=function(b,c){var d=D.zt.q.VI.call(this,b,c),d=d+this.Ca("ld",c.labelDisplay?c.labelDisplay:b.nodeDefaults.labelDisplay),e=c.labelHalign?c.labelHalign:b.nodeDefaults.labelHalign;"inner"==e?d+=this.Ca("ha","s"):"outer"==e&&(d+=this.Ca("ha","e"));e=c.radius;e!=D.r&&!(0,window.isNaN)(e)&&(d+=this.Ca("r",e));return d};
D.E.KY=function(b){var c,d=new D.zD;c="\x3cresources"+this.Ca("legendSize",(0,D.Na)(d,"SIZE"));c+=this.Ca("legendColor",(0,D.Na)(d,"COLOR"));c+=this.Ca("cursorRotate",b._resources.rotateCursor);c+=this.Ca("alta","true");return c+"/\x3e\n"};
D.E.WI=function(b){var c=D.zt.q.WI.call(this,b),d=b.animationUpdateColor;d&&(c+=this.Ca("top","-tr-animation-update-color: "+d));(d=b.nodeDefaults.borderColor)&&(c+=this.Ca("node","border-color: "+d));(d=b.nodeDefaults.hoverColor)&&(c+=this.Ca("node-hover","border-color: "+d));(b=b.nodeDefaults.selectedColor)&&(c+=this.Ca("node-selected","border-color: "+b));return c+"/\x3e\n"};
});