define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Pu=(0,D.z)();D.F.o(D.Pu,D.F,"DvtAttrGroups");D.Pu.prototype.get=(0,D.z)();
D.Qu=function(){this.TL=[]};D.F.o(D.Qu,D.Pu,"DvtDiscreteAttrGroups");D.Qu.prototype.add=function(b,c,d){this.TL.push({group:b,qEa:c,g8:d})};D.Qu.prototype.get=function(b){if(window.value===D.r)return D.r;for(var c=0;c<this.TL.length;c++)if(this.TL[c].group==b)return this.TL[c].g8;return D.r};
D.Ru=function(b,c,d,e,f){this.t2=b;this.Dha=c;this.gya=d?d:this.t2;this.aya=e?e:this.Dha;this.bG=f;this.cza=this.Dha-this.t2};D.F.o(D.Ru,D.Pu,"DvtContinuousAttrGroups");D.Ru.prototype.get=function(b){if((0,window.isNaN)(b)||b===D.r)return D.r;b=(b-this.t2)/this.cza;b=window.Math.max(window.Math.min(b,1),0);b*=this.bG.length-1;return b===window.Math.round(b)?this.bG[b]:D.S.xH(this.bG[window.Math.floor(b)],this.bG[window.Math.ceil(b)],b-window.Math.floor(b))};D.Ru.prototype.lH=(0,D.C)("gya");
D.vD=(0,D.z)();D.F.o(D.vD,D.F,"DvtLegendAttrGroupsRenderer");D.vD.Ksa=0.4;D.vD.Tba=1;D.vD.Vba=50;D.vD.Uba=10;D.vD.pZ=5;D.vD.Isa=11;D.vD.kca="#636363";D.vD.dIa="#333333";D.vD.v8=function(b,c,d,e,f,g,h){var k=D.r;g&&(g instanceof D.Ru?k=D.vD.gza(b,c,d,e,g,h):g instanceof D.Qu&&(k=D.vD.hza(b,d,e,f,g,h)));return k};
D.vD.gza=function(b,c,d,e,f,g){var h=D.J.S(b),k=D.vD.Uba/2+D.vD.Tba,m=new D.H(b);d.k(m);d=f.lH();var p=new D.nc(b,d,0,k);p.Ia(g.Eu);p.Fe();m.k(p);var q=new D.td(b,0,D.vD.Tba,D.vD.Vba,D.vD.Uba),t=h?f.bG.slice(0).slice().reverse():f.bG.slice(0);q.G(new D.xd(0,t));g.borderColor&&q.Ma(g.borderColor);m.k(q);t=D.vD.Vba+D.vD.pZ;f=f.aya;b=new D.nc(b,f,0,k);b.Ia(g.Eu);b.Fe();m.k(b);h?(g=b.Ub().g+D.vD.pZ,q.F(g),p.fa(g+t)):(g=p.Ub().g+D.vD.pZ,q.F(g),b.fa(g+t));c.ma(q,new D.pc(d+" - "+f));m.C().g>e&&(m.removeChild(p),
m.removeChild(b),q.F(0));return m};D.vD.hza=function(b,c,d,e,f,g){var h=[];f=f.TL.slice(0);for(var k=0;k<f.length;k++){var m=f[k];h.push({text:m.qEa,color:m.g8.color,pattern:m.g8.pattern,borderColor:g.borderColor})}h={sections:[{items:h}],orientation:"horizontal",layout:{outerGapWidth:0,outerGapHeight:0},textStyle:g.Eu.toString()};g=(0,D.ya)(b);g.setId(D.r);c.k(g);c=g.yz(h,d,e*D.vD.Ksa);g.L(h,d,c.j);d=g.C();b=new D.td(b,0,0,d.g,c.j);(0,D.vd)(b);g.Ha(b,0);return g};
D.iq=function(b){this.Init("breadcrumbsDrill");this.Qa=b};D.F.o(D.iq,D.ed,"DvtBreadcrumbsDrillEvent");D.iq.prototype.getId=(0,D.C)("Qa");
D.Ku=function(b,c,d,e){this.Init(b,c,d,e)};D.F.o(D.Ku,D.H,"DvtBreadcrumbs");D.E=D.Ku.prototype;D.E.Init=function(b,c,d,e){D.Ku.q.Init.call(this,b);this.P8(e);this.wa=new D.Lu(this,b,c,d);this.wa.bf(this);this.setId("breadcrumbs1000"+window.Math.floor(1E9*window.Math.random()));this.tt=-1;this.YQ=this.H1=D.r};D.E.P8=function(b){this.sd=D.Mu.sg(b)};D.E.L=function(b,c){this.ya=b?D.xa.clone(b):this.ya;this.Qi();this.YQ=D.r;D.Nu.L(this,this,c)};D.E.Fa=(0,D.C)("sd");D.E.Sa=(0,D.C)("wa");
D.E.z7=function(b){var c=D.o,d=b.keyCode;if(9==d){var e=d=this.tt;this.tt=!b.shiftKey?0>e||e>=this.ya.Du.length-1?0:++e:0>e||e>=this.ya.Du.length-1?this.ya.Du.length-2:--e;this.Aw(d,this.tt);if(0>this.tt||this.tt==this.ya.Du.length-1)c=D.u}else 13==d&&(d=D.Ce.$G(b,this.wa.e,0,0),d.target=(0,D.Ou)(this,this.tt),this.wa.zg(d));c&&b.preventDefault();return c};D.E.qe=function(){var b=this.tt;this.tt=-1;this.Aw(b,this.tt)};
D.E.Aw=function(b,c){var d=this.H1,e=D.r,f=(0,D.Ou)(this,c);if(f){var g=(0,D.Ac)(this.wa,f);g&&g.zna&&g.Wx?(e=this.e,g=f.C(),f=f.pa(),this.H1=e=new D.li(e,this,g,f)):this.H1=D.r}d&&d.PC();e&&e.show()};D.Ou=function(b,c){var d=b.YQ;return 0>c||!d||c>=d.length?D.r:d[c]};
D.Mu={};D.F.o(D.Mu,D.F,"DvtBreadcrumbsDefaults");D.Mu.iZ={labelStyle:"font-size: 11px; color: #003286;",disabledLabelStyle:"font-size: 11px;",DP:2,vta:"\x3e"};D.Mu.sg=function(b){var c=D.Mu.mB(b);return b?D.xa.zb(b,c):c};D.Mu.mB=function(){return D.xa.clone(D.Mu.iZ)};D.Mu.z6=function(b,c){return window.Math.ceil(c*b.layout.gapRatio)};
D.Lu=function(b,c,d,e){this.Init(c,d,e);this.ur=b};D.F.o(D.Lu,D.xc,"DvtBreadcrumbsEventManager");D.Lu.prototype.zg=function(b){D.Lu.q.zg.call(this,b);b=(0,D.Ac)(this,b.target);(0,D.XJ)(this,b)};D.Lu.prototype.bv=function(b){b=(0,D.Ac)(this,b.target);(0,D.XJ)(this,b)};D.XJ=function(b,c){if(c&&c instanceof D.WJ&&c.Wx){var d=new D.iq(c.getId());b.Yg(d,b.ur)}};
D.WJ=function(b,c){this.Init(c);this.Qa=b;this.Wx=D.u};D.F.o(D.WJ,D.pc,"DvtBreadcrumbsPeer");D.WJ.prototype.getId=(0,D.C)("Qa");D.WJ.prototype.zna=(0,D.C)("Wx");D.WJ.prototype.M8=(0,D.B)("Wx");
D.Nu={};D.F.o(D.Nu,D.F,"DvtBreadcrumbsRenderer");D.Nu.Lx=3;D.Nu.L=function(b,c,d){for(var e=b.e,f=(b.ya?b.ya:{}).Du?(b.ya?b.ya:{}).Du:[],g=b.Fa(),h=b.Sa(),k=[],m=[],p=0;p<f.length;p++){var q=f[p];if(q){var t=D.Nu.XQ(e,q.text?q.text:"",g,p<f.length-1);k.push(t);q=new D.WJ(q.id);h.ma(t,q);m.push(q);p<f.length-1&&(t.setCursor("pointer"),q.M8(D.o))}}b.YQ=k;D.J.S(e)?D.Nu.Tya(b,c,d,k,m):D.Nu.Sya(b,c,d,k,m)};
D.Nu.VQ=function(b,c,d){c=new D.nc(b,c,0,0);c.la(D.u);c.Ia(d);var e=(0,D.Ul)(d,"padding-top"),f=(0,D.Ul)(d,"padding-right"),g=(0,D.Ul)(d,"padding-bottom"),h=(0,D.Ul)(d,"padding-left"),k=(0,D.Zf)(b,c);b=new D.td(b,0,0,k.g+h+f,k.j+e+g);(0,D.vd)(b);b.Ia(d);(0,D.Xa)(c,h,e);b.k(c);return b};
D.Nu.XQ=function(b,c,d,e){if(e&&(d.S7||d.R7)){var f=new D.P(d.Eu);e=new D.P(d.S7);d=new D.P(d.R7);f=D.Nu.VQ(b,c,f);e=D.Nu.VQ(b,c,e);c=D.Nu.VQ(b,c,d);b=new D.rc(b,f,e,c)}else e=new D.P(e?d.Eu:d.ola),(0,D.Ul)(e,"padding-left")||(0,D.Ul)(e,"padding-right")||(0,D.Ul)(e,"padding-top")||(0,D.Ul)(e,"padding-bottom")?b=D.Nu.VQ(b,c,e):(b=new D.nc(b,c,0,0),b.Ia(e));return b};D.Nu.Hfa=function(b){if(b instanceof D.rc)return b=b.Ej.ca(0),b.oe();b instanceof D.td&&(b=b.ca(0));return b.oe()};
D.Nu.Aka=function(b,c){if(b instanceof D.rc){var d=b.Ej.ca(0);D.oc.Vb(d,window.Math.max(c-d.M(),0),window.Infinity,d.getParent());d=b.qh.ca(0);D.oc.Vb(d,window.Math.max(c-d.M(),0),window.Infinity,d.getParent());d=b.Ng.ca(0);D.oc.Vb(d,window.Math.max(c-d.M(),0),window.Infinity,d.getParent())}else b instanceof D.td?(d=b.ca(0),D.oc.Vb(d,window.Math.max(c-d.M(),0),window.Infinity,d.getParent())):D.oc.Vb(b,c,window.Infinity,b.getParent())};
D.Nu.Sya=function(b,c,d,e,f){for(var g=b.Fa(),h=b.Sa(),k=[],m=0,p=0;p<e.length;p++){c.k(e[p]);var q=e[p].C();k[p]=q;m=window.Math.max(q.j,m);c.removeChild(e[p])}for(var t=0,p=0;p<e.length;p++){c.k(e[p]);q=k[p];(0,D.Xa)(e[p],t,0.5*(m-q.j));if(D.J.da()){var v=new D.td(c.e,-D.Nu.Lx,-D.Nu.Lx,q.g+2*D.Nu.Lx,q.j+2*D.Nu.Lx);(0,D.vd)(v);e[p].k(v);p<f.length&&h.ma(v,f[p])}if(t+q.g>d){b=D.Nu.Hfa(e[p]);D.Nu.Aka(e[p],d-t);p<f.length?f[p].kx(b):h.ma(e[p],new D.pc(b));break}else t+=q.g+g.DP;if(p<e.length-1){q=D.Nu.Pha(b);
c.k(q);v=q.C();(0,D.Xa)(q,t,0.5*(m-v.j));v=v.g;if(t+v>d){c.removeChild(q);break}t+=v+g.DP}}};
D.Nu.Tya=function(b,c,d,e,f){for(var g=b.Fa(),h=b.Sa(),k=0;k<e.length;k++){c.k(e[k]);var m=e[k].C();if(D.J.da()){var p=new D.td(c.e,-D.Nu.Lx,-D.Nu.Lx,m.g+2*D.Nu.Lx,m.j+2*D.Nu.Lx);(0,D.vd)(p);e[k].k(p);k<f.length&&h.ma(p,f[k])}if(0>d-m.g){b=D.Nu.Hfa(e[k]);D.Nu.Aka(e[k],d);e[k].F(0);k<f.length?f[k].kx(b):h.ma(e[k],new D.pc(b));break}else e[k].F(d-m.g),d-=m.g+g.DP;if(k<e.length-1)if(m=D.Nu.Pha(b),c.k(m),p=m.C().g,0>d-p){c.removeChild(m);break}else m.F(d-p),d-=p+g.DP}};
D.Nu.Pha=function(b){var c=b.Fa();b=new D.nc(b.e,c.vta,0,0);b.Ia(new D.P(c.Eu));return b};
D.Eu=function(b,c){this.Init("dvtPanelDrawerEvent");this.El=b;this.zta=c};D.F.o(D.Eu,D.ed,"DvtPanelDrawerEvent");D.Eu.prototype.Lh=(0,D.C)("El");
D.Ha=function(b,c,d,e){this.Init(b,c,d,e)};D.F.o(D.Ha,D.H,"DvtPanelDrawer");
D.Ha.prototype.Init=function(b,c,d,e){D.Ha.q.Init.call(this,b,D.r,"panelDrawer"+e);this.Uja=e;this.Ga=new D.wu(b,c,d);this.Ga.bf(this);this.Ga.au.push(D.Ha);this.Ga.ma(this,this);this.Xa=c;this.ka=d;this.Uy={};this.Ur=[];this.zc=this.mg=window.Number.MAX_VALUE;this.Ho=5;this.kL=0;this.sK;this.iw;this.bn=this.vi=D.u;this.$;this.mE;this.he;this.fh;this.W_;this.xh;this.Xh;this.sq={};this.Dr="left";this.py="top";this.aw=D.u;this.D=D.r;d&&(this.D=d.ls());this.Kj=(0,D.Mc)(this.D,"backgroundAlpha",1);this.Fp=
(0,D.Mc)(this.D,"border-color","#bbc7d0");this.uh=(0,window.parseInt)((0,D.Mc)(this.D,"border-radius",2));this.xv=(0,D.Mc)(this.D,"background-color","#ffffff");this.Kda=(0,D.Mc)(this.D,"tab-color-inactive","#dee4e7");this.Lda=(0,D.Mc)(this.D,"tab-border-color-inactive","#c1cede");this.yJ=D.u;this.Gja=D.o;(0,D.ic)(this);this.nm=10};D.Na=function(b,c,d,e,f,g,h){b.Uy[h]={panel:c,iconUp:d,iconOver:e,iconDown:f,tooltip:g};b.Ur.push(h);b.kL=15+42*b.Ur.length};D.Ha.prototype.Yl=(0,D.B)("mg");
D.Ha.prototype.Q6=function(){return this.mg-(2*this.nm+21)};D.Ha.prototype.xD=(0,D.B)("zc");D.Ha.prototype.P6=function(){return this.zc-(2*this.nm+21)};D.xu=function(b,c){return b.Uy[c].panel};D.zu=function(b,c,d,e){b.iw=b.sK;b.sK=c;b.nb()&&(b.qI(),(0,D.yu)(b,c,d,e));b.iw=D.r};D.Au=function(b){var c=b.sK;return!c&&0<b.Ur.length?b.Ur[0]:c};
D.Ha.prototype.Ne=function(b,c,d){if(!this.bn){var e=this.vi;this.vi=b;if(e!=b)if(this.bn=D.o,b){var f=(0,D.xu)(this,(0,D.Au)(this));f&&this.yJ&&f.$a(D.u);(0,D.Cu)(this,(0,D.Au)(this));b=-(0.8*this.he.getWidth());"right"==this.Dr&&(b=-b,this.he.fa((0.8-1)*this.he.getWidth()));if(c)this.$.F(b),f&&this.yJ&&f.$a(D.o),d&&d(),this.bn=D.u;else if(c=new D.tb(this.e,0.25),c.Cj(D.Dj),(0,D.N)(c,"typeNumber",this.$,this.$.M,this.$.F,b),f&&this.yJ?(0,D.Rj)(c,function(){f.$a(D.o);d&&d()}):d&&(0,D.Rj)(c,d),c){var g=
this;(0,D.Rj)(c,function(){g.bn=D.u});c.play()}this.qI()}else if(c)this.$.F(0),this.bba(),d&&d(),this.qI(),this.bn=D.u;else{c=new D.tb(this.e,0.25);c.Cj(D.Cj);(0,D.N)(c,"typeNumber",this.$,this.$.M,this.$.F,0);(0,D.Rj)(c,this.bba,this);(0,D.Rj)(c,this.qI,this);d&&(0,D.Rj)(c,d);var h=this;(0,D.Rj)(c,function(){h.bn=D.u});c.play()}}};D.Ha.prototype.nb=(0,D.C)("vi");
D.Ha.prototype.Ri=function(){this.$||(this.$=new D.H(this.e,"pd_contentPane"),this.k(this.$),this.mE=new D.H(this.e,"pdcp_activeContent"),this.$.k(this.mE));if(!this.aw){var b=-42;"right"==this.Dr&&(b=0);var c=15;if("top"==this.py)for(var d=0;d<this.Ur.length;d++){var e=this.Ur[d],e=(0,D.Du)(this,e);(0,D.Xa)(e,b,c);c+=42}else if("bottom"==this.py){c=-57;for(d=this.Ur.length-1;0<=d;d--)e=this.Ur[d],e=(0,D.Du)(this,e),(0,D.Xa)(e,b,c),c-=42}}};
D.Du=function(b,c){var d,e;switch(b.Dr){case "right":e=["M",0,0,"L",42-b.uh,0,"A",b.uh,b.uh,0,0,1,42,b.uh,"L",42,42-b.uh,"A",b.uh,b.uh,0,0,1,42-b.uh,42,"L",0,42];break;default:e=["M",42,0,"L",b.uh,0,"A",b.uh,b.uh,0,0,0,0,b.uh,"L",0,42-b.uh,"A",b.uh,b.uh,0,0,0,b.uh,42,"L",42,42]}d=e;e=new D.Pa(b.e,d,"pdcp_tab_"+c);(0,D.ic)(e);e.setCursor("pointer");b.$.Ha(e,0);e.na(b.Kda,b.Kj);e.Ma(b.Lda,1,1);var f=b.Uy[c],g=new D.Pa(b.e,d);(0,D.vd)(g);(0,D.Xa)(f.iconUp,9,9);g.k(f.iconUp);var h=new D.Pa(b.e,d);(0,D.vd)(h);
(0,D.Xa)(f.iconOver,9,9);h.k(f.iconOver);d=new D.Pa(b.e,d);(0,D.vd)(d);(0,D.Xa)(f.iconDown,9,9);d.k(f.iconDown);g=new D.rc(b.e,g,h,d);g.OA=D.o;g.setCursor("pointer");f.icon=g;e.k(g);b.sq[c]=e;b.Ga.ma(e,{Sc:function(){b.iw=(0,D.Au)(b);b.sK=c;var d=function(){var c=b.e.kd();c&&c.oc()};b.nb()?b.iw==c?b.Ne(D.u,D.u,d):(b.qI(),(0,D.yu)(b,c,D.u)):(b.Ne(D.o,D.u,d),b.Zz());b.iw=D.r;b.$b(new D.Eu(b.nb()?"show":"hide",b.sK))},fe:function(){return b.Uy[c].tooltip}});b.lz(e,b.Uy[c].tooltip);return e};
D.yu=function(b,c,d,e){var f=D.r;d||(f=new D.tb(b.e,0.25));b.iw&&(d=(0,D.xu)(b,b.iw))&&b.fh.removeChild(d);(0,D.Cu)(b,c,f);f?(b.Zz(),e&&(0,D.Rj)(f,e),f.play()):e&&e()};D.Ha.prototype.bba=function(){this.he&&(this.W_=D.r,this.fh.Qi(),(0,D.cf)(this.mE),this.he.V(),this.mE.removeChild(this.he),this.Xh=this.xh=this.fh=this.he=D.r)};
D.Cu=function(b,c,d){b.he||(b.he=new D.td(b.e,0,0,1,1,"pdcp_expandedContent"),b.mE.k(b.he),b.he.na(b.xv,b.Kj),b.fh=new D.Hd(b.e,0,0,b.mg==window.Number.MAX_VALUE?D.r:b.mg-2*b.nm,b.zc==window.Number.MAX_VALUE?D.r:b.zc-2*b.nm,10,"pdcp_expandedContentPanel"+b.Uja),b.Gja||(b.fh.l1=D.u,b.fh.Gka=D.u),b.fh.bl("alta"),b.fh.D=b.D,b.he.k(b.fh),b.fh.F(b.nm),b.fh.Q(b.nm));var e=(0,D.xu)(b,c);if(e){b.fh.k(e);d&&b.yJ&&(e.$a(D.u),(0,D.Rj)(d,function(){e.$a(D.o)}));if(b.iw){var f=(0,D.xu)(b,b.iw);f&&f.Na("dvtResizeEvent",
b.T$,D.u,b)}e.P("dvtResizeEvent",b.T$,D.u,b)}b.xh||(b.xh=new D.Pa(b.e,["M",0,0,"L",1,1],"pdcp_expandedBorder"),b.Xh=new D.Pa(b.e,["M",0,0,"L",1,1],"pdcp_expandedBorderResizable"),b.he.k(b.xh),b.he.k(b.Xh),b.xh.Ma(b.Fp,1),b.xh.G(D.r),b.Xh.Ma(b.Fp,1),b.Xh.G(D.r),(0,D.ic)(b.xh),(0,D.ic)(b.Xh));var f=2*b.nm,g=2*b.nm,h=0,k=0;(0,D.xu)(b,c)&&(k=b.fh.qu(),f=(0,D.Fu)(b,k.g),g=(0,D.Gu)(b,k.j),h=k.x,k=k.y);(0,D.Hu)(b,c,d,f,g,h,k)};
D.Ha.prototype.T$=function(b){var c=new D.tb(this.e,0.25);this.fh.refresh();var d=b.getWidth(),e=b.getHeight(),f=this.fh.Sj+10;this.fh.Ak!=D.r&&(e+=f);this.fh.Lg!=D.r&&(d+=f);d=(0,D.Fu)(this,d);e=(0,D.Gu)(this,e);f=b.ea()?b.ea():0;b=b.ha()?b.ha():0;(0,D.Hu)(this,(0,D.Au)(this),c,d,e,f,b);c.play()};
D.Hu=function(b,c,d,e,f,g,h){var k=(0,D.xu)(b,c);d?(0,D.N)(d,"typeNumber",k,k.M,k.F,-g):k.F(-g);d?(0,D.N)(d,"typeNumber",k,k.K,k.Q,-h):k.Q(-h);var m=new D.I(b.nm,b.nm,e-2*b.nm,f-2*b.nm);g=1.25*e;d?((0,D.N)(d,"typeNumber",b.he,b.he.getWidth,b.he.ia,g),(0,D.N)(d,"typeNumber",b.he,b.he.getHeight,b.he.va,f),b.yJ?(0,D.Rj)(d,function(){b.k4(m)}):(0,D.N)(d,"typeRectangle",b,b.jwa,b.k4,m),"left"==b.Dr?(0,D.N)(d,"typeNumber",b.$,b.$.M,b.$.F,-e):"right"==b.Dr&&((0,D.N)(d,"typeNumber",b.$,b.$.M,b.$.F,e),(0,D.N)(d,
"typeNumber",b.xh,b.xh.M,b.xh.F,e),(0,D.N)(d,"typeNumber",b.Xh,b.Xh.M,b.Xh.F,e),(0,D.N)(d,"typeNumber",b.he,b.he.M,b.he.F,-e)),"bottom"==b.py&&((0,D.N)(d,"typeNumber",b.xh,b.xh.K,b.xh.Q,f),(0,D.N)(d,"typeNumber",b.Xh,b.Xh.K,b.Xh.Q,f),(0,D.N)(d,"typeNumber",b.he,b.he.K,b.he.Q,-f))):(b.he.ia(g),b.he.va(f),"right"==b.Dr&&(b.he.F(-e),b.xh.F(e),b.Xh.F(e)),"bottom"==b.py&&(b.he.Q(-f),b.xh.Q(f),b.Xh.Q(f)),b.k4(m));g=b.sq[c];var p;c=e;"right"==b.Dr&&(c=-e);"top"==b.py?g?(p=["M",0,0,"L",0,g.K(),"M",0,g.K()+
42],e=b.sq[b.Ur[b.Ur.length-1]],p.push("L",0,e.K()+42),b.xh.Uq(p),p=["M",0,e.K()+42,"L",0,f,"L",1.25*c,f]):(p=["M",0,0,"L",0,f,"L",c,f],b.xh.Uq(p)):"bottom"==b.py&&(g?(p=["M",0,0,"L",0,g.K()+42,"M",0,g.K()],e=b.sq[b.Ur[0]],p.push("L",0,e.K()),b.xh.Uq(p),c*=1.25,p=["M",0,e.K(),"L",0,-f,"L",c,-f]):(p=["M",0,0,"L",0,-f,"L",c,-f],b.xh.Uq(p)));d?(0,D.N)(d,"typePath",b.Xh,b.Xh.RM,b.Xh.Uq,p):b.Xh.Uq(p)};
D.Ha.prototype.k4=function(b){if(this.fh&&b){var c=new D.Sg("pdcp"+this.Uja);(0,D.Tg)(c,b.x,b.y,b.g,b.j);(0,D.sf)(this.fh,c)}this.W_=b};D.Ha.prototype.jwa=(0,D.C)("W_");D.Fu=function(b,c){var d=c+2*b.nm;if((b.Ho||0==b.Ho)&&d<b.Ho)d=b.Ho;b.mg&&d>b.mg&&(d=b.mg);return d};D.Gu=function(b,c){var d=c+2*b.nm;if((b.kL||0==b.kL)&&d<b.kL)d=b.kL;b.zc&&d>b.zc&&(d=b.zc);return d};
D.Iu=function(b,c){if(b.he){var d=b.he.Gc().clone();d.B(c);b.he.G(d)}for(var e in b.sq){var f=b.sq[e];f&&(d=f.Gc().clone(),d.B(c),f.G(d))}};D.Ju=function(b){if(b.xh){var c=b.xh.nc().clone();c.B(1);b.xh.Y(c)}b.Xh&&(c=b.Xh.nc().clone(),c.B(1),b.Xh.Y(c));for(var d in b.sq){var e=b.sq[d];e&&(c=e.nc().clone(),c.B(1),e.Y(c))}};D.E=D.Ha.prototype;D.E.O5=function(){this.la(D.u);(0,D.Iu)(this,1);(0,D.Ju)(this);this.fh&&this.fh.B(1);for(var b in this.sq){var c=this.Uy[b].icon;c&&c.B(1)}};
D.E.N5=function(){this.la(D.o);(0,D.Iu)(this,this.Kj);(0,D.Ju)(this);this.fh&&this.fh.B(1);for(var b in this.sq){var c=this.Uy[b].icon;c&&c.B(1)}this.Wi(D.r)};D.E.Gj=function(){this.Zz()};D.E.Wi=function(){this.LA||this.KW()};D.E.Zz=function(){(0,D.Iu)(this,1)};D.E.KW=function(){(0,D.Iu)(this,this.Kj)};
D.E.qI=function(){for(var b in this.sq){var c=this.sq[b];c&&(b==(0,D.Au)(this)&&this.nb()?(c.na(this.xv,this.Kj),c.Ma(this.Fp,1)):(c.na(this.Kda,this.Kj),c.Ma(this.Lda,1)));var d=this.nb()&&b==(0,D.Au)(this),e=this.Uy[b].icon;e&&(0,D.yd)(e,d);d?this.mE.k(c):this.$.Ha(c,0)}};D.E.lz=function(b,c){b&&c&&((0,D.vf)(b),(0,D.xf)(b,"label",c))};D.Ka=function(b,c){if(!b.l2||b.l2<c)b.l2=c};D.Ha.prototype.C=function(b){b=D.Ha.q.C.call(this,b);b.g/=1.25;return b};
D.wu=function(b,c,d){this.Init(b,c,d)};D.F.o(D.wu,D.xc,"DvtPanelDrawerEventManager");D.E=D.wu.prototype;D.E.zg=function(b){var c=(0,D.Ac)(this,(0,D.Bm)(this,b));D.wu.q.zg.call(this,b);c&&(c.Sc&&c.Sc(b),b.stopPropagation())};D.E.eo=function(b){D.wu.q.eo.call(this,b);var c=(0,D.Ac)(this,(0,D.Bm)(this,b));c&&(c.Pg&&(c.Pg()&&c.Xn)&&c.Xn(b),b.stopPropagation())};D.E.fv=function(b){D.wu.q.fv.call(this,b);var c=(0,D.Ac)(this,(0,D.Bm)(this,b));c&&c.Gj&&c.Gj(b)};
D.E.ev=function(b){D.wu.q.ev.call(this,b);var c=(0,D.Ac)(this,(0,D.Bm)(this,b));c&&c.Wi&&c.Wi(b)};D.E.Zs=function(b){var c=(0,D.Ac)(this,(0,D.Bm)(this,b));D.wu.q.Zs.call(this,b);c&&(c.Sc&&c.Sc(b),b.stopPropagation())};
D.hu=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.o(D.hu,D.H,"DvtAccordion");D.hu.prototype.Init=function(b,c,d,e,f,g,h){D.hu.q.Init.call(this,b,D.r,c);this.ej=g;this.D=(new D.iu).sg(h);this.AT={};this.cu=[];this.mg=d;this.Ho=0;this.zc=e;this.cQ=this.YZ=D.u;this.Ga=f;this.Ga.bf(this);this.Ga.ma(this,this)};D.ku=function(b,c,d,e,f){f||(f="accordion_"+c.replace(/ /g,"_")+window.Math.floor(1E9*window.Math.random()));c=new D.ju(b.e,d,c,e,D.o,b,b.Ga,f,b.ej,b.D);b.AT[f]=c;b.cu.push(f);b.k(c)};
D.hu.prototype.L=function(){for(var b=(0,D.lu)(this),c=D.u,d=0;d<this.cu.length;d++){var e=(0,D.mu)(this,d);e.L(b);c&&!this.cQ&&e.setActive(D.u);e.pn&&e.yB&&(c=D.o)}!c&&(0<this.cu.length&&!this.YZ)&&(0,D.mu)(this,0).setActive(D.o);(0,D.nu)(this)};D.hu.prototype.xD=(0,D.B)("zc");D.hu.prototype.Yl=(0,D.B)("mg");
D.hu.prototype.gZ=function(b){b=this.AT[b];var c=b.pn;if(c){if(c)if(b.yB)if(this.YZ)c=D.o;else{for(var d=0,e=0;e<this.cu.length;e++)c=(0,D.mu)(this,e),c.pn&&d++;c=1<d}else c=D.u;c&&b.setActive(D.u)}else{if(!this.cQ)for(c=0;c<this.cu.length;c++)(0,D.mu)(this,c).setActive(D.u);b.setActive(D.o)}(0,D.nu)(this)};
D.lu=function(b){if(!b.Bha){for(var c=0,d=b.D.paddingX,e=0;e<b.cu.length;e++){var f=(0,D.mu)(b,e),g;g=f;if(!g.AG){var h=new D.nc(g.e,g.xd);h.Ia(g.iz);if(h=h.Ub())h.g=h.g+g.lga+g.mAa;g.AG=h}g=g.AG;g.g>c&&(c=g.g);f=f.dH().g+2*d;f>c&&(c=f)}c=window.Math.min(c,b.mg);c=window.Math.max(c,b.Ho);b.Bha=c}return b.Bha};D.mu=function(b,c){return 0<=c&&c<b.cu.length?b.AT[b.cu[c]]:D.r};
D.nu=function(b){for(var c=0,d=0;d<b.cu.length;d++){var e=(0,D.mu)(b,d);e.Q(c);e.pn?(e.expand(),c+=e.qu().j,c+=b.D.paddingY):(e.collapse(),c+=b.D.sectionHeader.headerHeight)}c=b.qu();b.$b(new D.kc(c.g,c.j,0,0))};
D.ju=function(b,c,d,e,f,g,h,k,m,p){this.Init(b,c,d,e,f,g,h,k,m,p)};D.F.o(D.ju,D.H,"DvtAccordionSection");D.E=D.ju.prototype;
D.E.Init=function(b,c,d,e,f,g,h,k,m,p){D.ju.q.Init.call(this,b,D.r,k);this.$e=g;this.ej=m;this.xd=d;this.Qa=k;this.Xf=c;this.ay=this.Nv=D.r;this.pn=(this.yB=f)?e:D.o;this.Ga=h;this.D=p;this.Wv=this.D.sectionHeader.headerHeight;this.WS=this.D.paddingX;this.XS=this.D.paddingY;this.iz=this.D.sectionHeader.styleEna;this.lga=this.D.sectionHeader.imageWidth;this.rxa=this.D.sectionHeader.imageHeight;this.mAa=this.D.sectionHeader.textPadding};D.E.getId=(0,D.C)("Qa");D.E.hV=(0,D.C)("xd");D.E.setActive=(0,D.B)("pn");
D.E.dH=function(){var b=D.r;0>this.He(this.Xf)?(this.k(this.Xf),b=this.Xf.C(),this.removeChild(this.Xf)):b=this.Xf.C();return b};
D.E.L=function(b){var c=this.Wv;if(this.yB){this.ej.l?(window.ena=(0,D.RJ)(this,0,this.ej.l("sectionExpEna"),this.xd,b,c),window.ovr=(0,D.RJ)(this,1,this.ej.l("sectionExpOvr"),this.xd,b,c),window.dwn=(0,D.RJ)(this,2,this.ej.l("sectionExpDwn"),this.xd,b,c)):(window.ena=(0,D.RJ)(this,0,this.ej.sectionExpEna,this.xd,b,c),window.ovr=(0,D.RJ)(this,1,this.ej.sectionExpOvr,this.xd,b,c),window.dwn=(0,D.RJ)(this,2,this.ej.sectionExpDwn,this.xd,b,c));this.Nv=new D.rc(this.e,window.ena,window.ovr,window.dwn);
this.ej.l?(window.ena=(0,D.RJ)(this,0,this.ej.l("sectionColEna"),this.xd,b,c),window.ovr=(0,D.RJ)(this,1,this.ej.l("sectionColOvr"),this.xd,b,c),window.dwn=(0,D.RJ)(this,2,this.ej.l("sectionColDwn"),this.xd,b,c)):(window.ena=(0,D.RJ)(this,0,this.ej.sectionColEna,this.xd,b,c),window.ovr=(0,D.RJ)(this,1,this.ej.sectionColOvr,this.xd,b,c),window.dwn=(0,D.RJ)(this,2,this.ej.sectionColDwn,this.xd,b,c));this.ay=new D.rc(this.e,window.ena,window.ovr,window.dwn);var d=this;b={Sc:function(){d.$e.gZ(d.getId())}};
this.Ga.ma(this.Nv,b);this.Ga.ma(this.ay,b)}else b=(0,D.SJ)(this,3,b,c),c=(0,D.TJ)(this,this.xd),this.h1=new D.H(this.e),this.h1.k(b),this.h1.k(c);this.yB?this.pn?(this.Ha(this.Nv,0),this.k(this.Xf),this.Xf.F(this.WS),this.Xf.Q(this.Wv+this.XS)):this.k(this.ay):(this.Ha(this.h1,0),this.k(this.Xf),this.Xf.F(this.WS),this.Xf.Q(this.Wv+this.XS))};D.E.collapse=function(){this.yB&&(0<=this.He(this.Nv)&&this.removeChild(this.Nv),0<=this.He(this.Xf)&&this.removeChild(this.Xf),this.k(this.ay),this.setActive(D.u))};
D.E.expand=function(){0<=this.He(this.ay)&&this.removeChild(this.ay);this.k(this.Nv);this.k(this.Xf);this.Xf.F(this.WS);this.Xf.Q(this.Wv+this.XS);this.setActive(D.o)};D.RJ=function(b,c,d,e,f,g){var h=b.lga,k=b.rxa,m=(b.Wv-k)/2,p=new D.H(b.e);c=(0,D.SJ)(b,c,f,g);p.k(c);(d=d?new D.La(b.e,d,0,m,h,k):D.r)&&p.k(d);e=(0,D.TJ)(b,e,f-h-0,g,p);D.J.S(b.e)?(b=e.Ub(),e.F(f-b.g-h),d&&d.F(f-h)):e.F(h);return p};
D.TJ=function(b,c,d,e,f){var g=D.r;if(c){g=new D.nc(b.e,c);g.Ia(b.iz);D.oc.Vb(g,d,e,f);c=g.Ub();if(!b.AG||b.AG.g<c.g||b.AG.j<c.j)b.AG=c;g.Q((b.Wv-c.j)/2)}return g};D.SJ=function(b,c,d,e){var f=D.r;switch(c){case 1:f=b.D.sectionHeader.styleOvr;break;case 2:f=b.D.sectionHeader.styleDwn;break;case 3:f=b.D.sectionHeader.styleDis;break;default:f=b.D.sectionHeader.styleEna}b=new D.td(b.e,0,0,d,e);b.Y((0,D.UJ)(f));b.G((0,D.VJ)(f));return b};
D.VJ=function(b){var c=b.v("background-color");b=(0,D.$l)(b);var d=D.r;if(b&&b instanceof D.Zl){var c=b.ql,d=b.pl,e=b.qv;b=b.Wj();d=new D.xd(b,c,d,e)}else c&&(d=new D.Td(c,1));return d};D.UJ=function(b){b=b.v("border-color");return new D.Ud(b,1,1)};
D.iu=function(){this.Init({skyros:D.YJ,alta:D.ZJ})};D.F.o(D.iu,D.Mg,"DvtAccordionDefaults");
D.YJ={skin:"alta",sectionHeader:{styleEna:new D.P("font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:bold;color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),styleOvr:new D.P("font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:bold;color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),styleDwn:new D.P("font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:bold;color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),styleDis:new D.P("font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:bold;color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),
headerHeight:33,imageWidth:24,imageHeight:24,textPadding:5},paddingX:0,paddingY:0};D.ZJ={};
D.gt=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.gt,D.H,"DvtTrain");D.gt.prototype.Init=function(b,c,d,e,f){D.gt.q.Init.call(this,b,D.r,f);this.mM=b.kd();this.eS=d;this.Zx=e;this.UQ=d.length;this.TJ=(0,window.Array)(this.UQ);this.xn=0;this.sA(c)};D.gt.prototype.uW=function(b){0<=b&&b<this.UQ&&(0,D.ou)(this,this.xn,b)};
D.gt.prototype.Sc=function(b){(0,D.Pc)(b);for(var c=0;c<this.TJ.length;c++)if(b.target.getParent()===this.TJ[c]){b=this.xn;(0,D.ou)(this,b,c);b!=c&&(c=new D.pu(this.xn),this.$b(c,D.u));break}};D.ou=function(b,c,d){b.xn=d;if(c=b.TJ[c])c.qh&&c.qh.setCursor("pointer"),c.Ng&&c.Ng.setCursor("pointer"),(0,D.yd)(c,D.u);if(c=b.TJ[d])c.qh&&c.qh.setCursor("default"),c.Ng&&c.Ng.setCursor("default"),(0,D.yd)(c,D.o)};
D.gt.prototype.sA=function(b){var c=D.J.S(this.e),d;if(!this.zQ){if(this.Zx&&(d=this.Zx[0]))this.zQ=(0,D.Vl)(d.getWidth());this.zQ||(this.zQ=8)}d=this.zQ;for(var e=0;e<this.UQ;e++){var f,g=f=this.Ns(d,e==this.xn,this.eS[e]);g.P(D.Sa.Sd,this.Sc,D.u,this);D.J.da()||g.P(D.Ta,this.Sc,D.u,this);g=e;c&&(g=this.UQ-1-e);b&&b.ma(f,f);(0,D.Xa)(f,g*d+3*(g+1),1);this.k(f);this.TJ[e]=f}};D.gt.prototype.pp=function(b,c){return new D.La(this.e,b,0,0,c,c)};
D.qu=function(b,c,d,e){var f=b.Zx?b.Zx[d]:D.r;if(f=f?f.v("content"):D.r)b=b.pp(f,c);else{var g,h,k;2==d?(k=0,h="#61bde3",f="#0066ff",b.Zx&&(g=b.Zx[2])):(k=1,h="#c0cbd5",f="#5d7891",b.Zx&&(g=b.Zx[0]));g&&(g.v("border-color")&&(f=g.v("border-color")),g.v("background-color")&&(h=g.v("background-color")));b=new D.td(b.e,k,k,c-2*k,c-2*k);b.na(h);b.Ma(f)}b.setCursor(0==d||e?"default":"pointer");return b};
D.gt.prototype.Ns=function(b,c,d){b=new D.rc(this.e,(0,D.qu)(this,b,0,c),(0,D.qu)(this,b,1,c),(0,D.qu)(this,b,2,c),D.r);b.kx(d);b.OA=D.o;c&&(0,D.yd)(b,c);return b};
D.pu=function(b){this.Init("dvtTrain");this.type=this.Ba();this.uB=b};(0,D.ta)("DvtTrainEvent",D.pu);D.F.o(D.pu,D.ed,"DvtTrainEvent");D.pu.TYPE="dvtTrain";D.pu.prototype.Ea=(0,D.C)("uB");D.pu.prototype.getIndex=D.pu.prototype.Ea;
D.DvtOverviewWindow=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.o(D.DvtOverviewWindow,D.H,"DvtOverviewWindow");D.DvtOverviewWindow.jZ="viewport-bg-color";D.DvtOverviewWindow.kZ="viewport-border-color";D.DvtOverviewWindow.qra="isOverviewDisclosed";D.E=D.DvtOverviewWindow.prototype;D.E.Init=function(b,c,d,e,f,g){D.DvtOverviewWindow.q.Init.call(this,b,D.r,c);this.Za=d;this.Ja=e;this.qg=f;this.Eg=g;this.fz=D.r};
D.E.L=function(){this.iL=D.u;this.i3=D.o;this.Ff&&(D.J.da()?(this.Ff.Na(D.Sa.Sd,this.HS,D.u,this),this.Ff.Na(D.Sa.sh,this.IS,D.u,this),this.Ff.Na(D.Sa.eg,this.lL,D.u,this)):(this.Ff.Na(D.uc,this.HS,D.u,this),this.Ff.Na(D.cd,this.IS,D.u,this),this.Ff.Na(D.dd,this.lL,D.u,this),this.Ff.Na(D.Va,this.Kha,D.u,this)),(0,D.sf)(this.Ff,D.r));this.Qi();this.Ff=this.md=D.r;var b=new D.Sg(this.getId());(0,D.Tg)(b,0,0,this.qg,this.Eg);this.Ff=new D.td(this.e,0,0,this.qg,this.Eg);(0,D.sf)(this.Ff,b);(0,D.vd)(this.Ff);
this.k(this.Ff);this.md=new D.td(this.e,0,0,0,0,this.getId()+":viewport");b=this.NC(D.DvtOverviewWindow.jZ);this.md.Ma(this.NC(D.DvtOverviewWindow.kZ),D.r,2);this.md.na(b);this.md.la(D.u);this.Ff.k(this.md);D.J.da()?(this.Ff.P(D.Sa.Sd,this.HS,D.u,this),this.Ff.P(D.Sa.sh,this.IS,D.u,this),this.Ff.P(D.Sa.eg,this.lL,D.u,this)):(this.Ff.P(D.uc,this.HS,D.u,this),this.Ff.P(D.cd,this.IS,D.u,this),this.Ff.P(D.dd,this.lL,D.u,this),this.Ff.P(D.Va,this.Kha,D.u,this))};D.E.nb=(0,D.C)("nF");D.E.Ne=(0,D.B)("nF");
D.E.dH=function(){return new D.I(this.Za,this.Ja,this.qg,this.Eg)};D.su=function(b,c,d){var e=(0,D.ru)(b,c.x,c.y,d),f=(0,D.ru)(b,c.x+c.g,c.y+c.j,d);c=e.x;var g=e.y,h=f.x-e.x,e=f.y-e.y;d?((0,D.N)(d,"typeNumber",b.md,b.md.ea,b.md.fa,c),(0,D.N)(d,"typeNumber",b.md,b.md.ha,b.md.ua,g),(0,D.N)(d,"typeNumber",b.md,b.md.getWidth,b.md.ia,h),(0,D.N)(d,"typeNumber",b.md,b.md.getHeight,b.md.va,e)):(b.md.fa(c),b.md.ua(g),b.md.ia(h),b.md.va(e))};
D.uu=function(b){var c=(0,D.tu)(b,b.md.ea(),b.md.ha());b=(0,D.tu)(b,b.md.ea()+b.md.getWidth(),b.md.ha()+b.md.getHeight());return new D.I(c.x,c.y,b.x-c.x,b.y-c.y)};D.E=D.DvtOverviewWindow.prototype;D.E.HS=function(b){if(!this.iL&&this.i3){this.iL=D.o;var c=this.yl(b);b=new D.wi((0,D.uu)(this),(0,D.vu)(this,c),b);this.$b(b)}};D.E.IS=function(b){if(this.iL&&this.i3){var c=this.yl(b);b=new D.wi((0,D.uu)(this),(0,D.vu)(this,c),b);this.$b(b)}};D.E.lL=function(){this.iL&&this.i3&&(this.iL=D.u)};
D.E.Kha=function(){this.lL()};D.E.yl=function(b){var c,d;D.J.da()?(b=b.touches,0<b.length&&(c=b[0].pageX,d=b[0].pageY)):(c=b.pageX,d=b.pageY);return(0,D.rg)(this.e,c,d)};D.tu=function(b,c,d){var e=0,f=0,g=1,h=1;b.Ai&&(e=b.Ai.M(),f=b.Ai.K(),g=b.Ai.Qb(),h=b.Ai.Tb());return new D.R((c-e)/g,(d-f)/h)};
D.ru=function(b,c,d,e){var f=0,g=0,h=1,k=1;b.Ai&&(f=e?(0,D.mb)(e,b.Ai,b.Ai.M,D.o):b.Ai.M(),g=e?(0,D.mb)(e,b.Ai,b.Ai.K,D.o):b.Ai.K(),h=e?(0,D.mb)(e,b.Ai,b.Ai.Qb,D.o):b.Ai.Qb(),k=e?(0,D.mb)(e,b.Ai,b.Ai.Tb,D.o):b.Ai.Tb());return new D.R(c*h+f,d*k+g)};D.DvtOverviewWindow.prototype.pH=(0,D.C)("fz");D.DvtOverviewWindow.prototype.AD=(0,D.B)("fz");D.DvtOverviewWindow.prototype.NC=function(b){return this.fz&&"undefined"!=this.fz[b]?this.fz[b]:D.r};
D.vu=function(b,c){var d=(0,D.Ae)(b.Ff,new D.R(0,0)),e=b.md.C(),f=c.x-d.x-e.g/2,g=c.y-d.y-e.j/2,d=(0,D.tu)(b,f,g),e=(0,D.tu)(b,f+e.g,g+e.j);return new D.I(d.x,d.y,e.x-d.x,e.y-d.y)};D.DvtOverviewWindow.prototype.lba=function(b){this.md.fa(b.x);this.md.ua(b.y);this.md.ia(b.g);this.md.va(b.j)};D.DvtOverviewWindow.prototype.GX=function(){return new D.I(this.md.ea(),this.md.ha(),this.md.getWidth(),this.md.getHeight())};
D.DvtOverviewWindow.prototype.C=function(b){var c=new D.I(0,0,this.qg,this.Eg);return!b||b===this?c:(0,D.ce)(this,c,b)};
});