define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.zo=function(b,c){this.Init(c===D.u?"sunburstRotationInput":"sunburstRotation");this.Qc=b};(0,D.ta)("DvtSunburstRotationEvent",D.zo);D.F.o(D.zo,D.ed,"DvtSunburstRotationEvent");D.zo.TYPE="sunburstRotation";D.zo.TYPE_INPUT="sunburstRotationInput";D.zo.prototype.Sma=(0,D.C)("Qc");D.zo.prototype.getStartAngle=D.zo.prototype.Sma;
D.rt=function(b,c,d){this.Init(b,c,d)};D.F.o(D.rt,D.Zo,"DvtBaseSunburst");D.E=D.rt.prototype;D.E.Init=function(b,c,d){D.rt.q.Init.call(this,b,c,d);this.hf=new D.st;this.Zc=2*window.Math.PI};D.E.gv=function(b){return(new D.tt(this)).parse(b)};D.E.nI=function(b){D.rt.q.nI.call(this,b);this.Bja=b.rotation;this.Aja=D.J.Nd()?"url("+this.de.cursorRotate+"), auto":"url("+this.de.cursorRotate+") 8 8, auto";this.Qc=(360-b.zW)*D.ut/360;this.Qc>window.Math.PI&&(this.Qc-=D.ut)};
D.E.bo=function(b){var c=window.Math.max(window.Math.ceil(3*window.Math.min(b.g,b.j)/400),2);b.x+=c;b.y+=c;b.g-=2*c;b.j-=2*c;(0,D.cp)(this,b);(0,D.dp)(this,b);this.uka=window.Math.floor(window.Math.min(b.g,b.j)/2);this.kb&&D.vt.Mn(this.uka,this.kb,this.Qc,this.Zc,this.nP)};
D.E.ll=function(b,c){this.dP(b,"");this.ur&&b.k(this.ur);this.Ua&&(b.k(this.Ua),this.Ua=D.r);this.IG=new D.R(c.x+c.g/2,c.y+c.j/2);if("on"==this.Bja&&(0,D.ep)(this)){var d=D.J.da()?60:15,d=new D.Rd(this.e,c.x+c.g/2,c.y+c.j/2,this.uka+d);(0,D.vd)(d);d.setCursor(this.Aja);b.k(d);this.Sa().ma(d,new D.wt(D.r,"_rotationShape"))}d=new D.H(this.e);(0,D.Xa)(d,this.IG.x,this.IG.y);b.k(d);if((0,D.ep)(this)){var e=new D.H(this.e);d.k(e);this.kb.L(e);this.du=new D.H(this.e);d.k(this.du);this.gga=new D.H(this.e);
d.k(this.gga)}else(0,D.fp)(this,b)};D.E.YW=function(b,c,d,e){return new D.xt(b,c,d,e)};D.E.zX=function(b,c){if("fan"===this.IW&&(0,D.ep)(this)){this.RZ(0);var d=new D.Nj(this.e,this,this.HD);(0,D.N)(d.T,"typeNumber",this,this.ewa,this.RZ,2*window.Math.PI);return d}return D.rt.q.zX.call(this,b,c)};D.E.xX=function(){var b=D.rt.q.xX.call(this);b&&(0,D.Xa)(b,this.IG.x,this.IG.y);return b};
D.E.wp=function(){if(!this.JW){this.ga.Qi();var b=new D.I(0,0,this.ub,this.Mb);this.bo(b);this.ll(this.ga,b);for(var b=this.Kb?this.Kb.getSelection():[],c=0;c<b.length;c++)b[c].Ob(D.o)}this.Zc<2*window.Math.PI&&this.RZ(2*window.Math.PI);D.rt.q.wp.call(this)};D.E.EP=function(b){this.du.k(b);D.J.cp()||((0,D.cf)(this.du),(0,D.bf)(this.du,D.yt))};D.E.ewa=(0,D.C)("Zc");D.E.RZ=function(b){this.Zc=b;this.bo(new D.I(0,0,this.ub,this.Mb));this.kb&&(0,D.zt)(this.kb,D.o)};
D.At=function(b,c){b.l0=c;b.hG=new D.td(b.e,0,0,b.ub,b.Mb);(0,D.vd)(b.hG);b.hG.setCursor(b.Aja);b.k(b.hG);b.Sa().ma(b.hG,new D.wt(D.r,"_rotationShape"))};D.Bt=function(b,c){var d=c-b.l0;b.l0=c;b.Qc+=d;b.Qc<-window.Math.PI?b.Qc+=2*window.Math.PI:b.Qc>window.Math.PI&&(b.Qc-=2*window.Math.PI);b.bo(new D.I(0,0,b.ub,b.Mb));b.kb&&(0,D.zt)(b.kb,D.o);b.ib(new D.zo(360-window.Math.round(180*b.Qc/window.Math.PI),D.u))};
D.Ct=function(b){b.l0=D.r;b.removeChild(b.hG);b.hG=D.r;var c=360-window.Math.round(180*b.Qc/window.Math.PI);b.ib(new D.zo(c,D.u));b.ib(new D.zo(c,D.o))};D.Dt=function(b,c,d){return window.Math.atan2(d-b.IG.y,c-b.IG.x)};
D.Et=(0,D.z)();(0,D.ta)("DvtSunburst",D.Et);D.F.o(D.Et,D.rt,"DvtSunburst");D.Et.newInstance=function(b,c,d){var e=new D.Et;e.Init(b,c,d);return e};D.Et.getDefaults=function(b){return(0,D.Sb)(new D.st,b)};D.Et.prototype.L=function(b,c,d){b?(this.W=this.hf.sg(b),D.J.Nh()||(this.W.animationOnDisplay="none",this.W.animationOnDataChange="none")):this.W||(this.W=(0,D.Vb)(this));b=(new D.Ft).b9(this.W);D.Et.q.L.call(this,b,c,d)};D.Et.prototype.render=D.Et.prototype.L;
D.tt=function(b){this.Init(b)};D.F.o(D.tt,D.WB,"DvtSunburstParser");D.tt.prototype.Um=function(b,c,d){return new D.ED(b,c,d)};D.tt.prototype.bm=function(b){var c=D.tt.q.bm.call(this,b);c.rotation=b.l("r");c.zW=b.l("sa");if(c.zW===D.r||(0,window.isNaN)(c.zW))c.zW=90;return c};D.tt.prototype.iv=function(b){var c=D.tt.q.iv.call(this,b);c.zV=b.l("ha");c.rGa=b.l("r");return c};
D.tt.prototype.rY=function(b,c,d,e){e.NODE_DEFAULT_COLOR_STYLE=b.v("border-color");e.NODE_HOVER_COLOR_STYLE=c.v("border-color");e.NODE_SELECTED_INNER_COLOR_STYLE=d.v("-tr-inner-color");e.NODE_SELECTED_OUTER_COLOR_STYLE=d.v("-tr-outer-color")};
D.ED=function(b,c,d){this.Init(b,c,d);this.Eo=c.yV?c.yV:"auto";this.pF=c.zV;this.Qj=c.rGa};D.F.o(D.ED,D.iC,"DvtSunburstNode");D.ut=2*window.Math.PI;D.E=D.ED.prototype;
D.E.L=function(b){if(this.Vv){this.JS=b;this.J=this.i0();b.k(this.J);var c=this.gM;if(!this.$e&&(0==this.$h&&this.Zc==D.ut)&&c){var d=window.Math.sqrt(2),e=this.Ah*d-4;this.Za=-this.Ah/d+2;this.Ja=-this.Ah/d+2;d=this.I.MZ;d.wo=this.Wh;0<e&&0<e&&((0,D.sr)(d,e),(0,D.tr)(d,e),d.wf((0,D.jC)(this)),this.X_=c=D.mq.oD(d,c,this.J),d=c.C(),(0,D.Xa)(c,this.Za+(e-d.g)/2,this.Ja+(e-d.j)/2))}else this.Ya=this.eK(this.J),this.Ya!=D.r&&(this.J.k(this.Ya),this.No&&(d=this.Ya.Ub(),this.To=new D.td(this.I.e,d.x,d.y,
d.g,d.j),this.To.na("#FFFFFF"),this.To.la(D.u),this.J.k(this.To),e=this.Ya.pa(),(0,D.Te)(e)||this.To.qa(e),this.J.k(this.Ya)));(0,D.vf)(this.J);(0,D.xf)(this.J,"label",this.my);this.Ru(b)}};D.E.Ob=function(b){"off"!=this.hP&&(D.ED.q.Ob.call(this,b),this.mb()?(this.J.Ob(D.o),this.I.EP(this.J)):(this.J.Ob(D.u),this.JS&&this.JS.k(this.J)))};D.E.Dc=function(){this.J&&this.Vv&&(this.J.Dc(),this.mb()?this.I.EP(this.J):this.I.gga.k(this.J))};
D.E.sc=function(){this.J&&(this.Vv&&!this.li())&&(this.J.sc(),!this.mb()&&this.JS&&this.JS.k(this.J))};
D.E.nh=function(b){var c,d,e,f;if(b.type==D.Ta)return D.ED.q.nh.call(this,b);c=b.keyCode;if(32==c&&b.ctrlKey)return this;for(f=this;f.$e;)f=f.$e;d=(0,D.qC)(this,f,(0,D.pC)(this));a:{for(e=0;e<d.length;e++)if(this===d[e])break a;e=-1}var g=this.Qc+this.Zc/2,g=(0,D.ID)(g);switch(c){case 38:if(this===f||180<g){if(c=this.hS)if(d=c.Qc+c.Zc/2,d=(0,D.ID)(d),180<d)return c;b=(0,D.co)(this,b,(0,D.bp)(this))}else b=(0,D.JD)(this);break;case 40:if(this===f||0<=g&&180>=g){if(c=this.hS)if(d=c.Qc+c.Zc/2,d=(0,D.ID)(d),
0<=d&&180>=d)return c;b=(0,D.co)(this,b,(0,D.bp)(this))}else b=(0,D.JD)(this);break;case 37:b=1==d.length?this:0==e?d[d.length-1]:d[e-1];break;case 39:b=1==d.length?this:e==d.length-1?d[0]:d[e+1];break;default:b=this}(0,D.oC)(b);return b};D.JD=function(b){var c=b.$e;c&&(b=c,(0,D.oC)(c));(0,D.oC)(b);return b};D.ID=function(b){b=D.Xe.u8(b);0>b?b+=360:360<b&&(b-=360);return b};D.E=D.ED.prototype;
D.E.Je=function(){if(this.J){var b=this.J.C(),c=new D.R(b.x,b.y),c=(0,D.Ae)(this.J,c);b.x=c.x;b.y=c.y;return b}return new D.I(0,0,0,0)};D.E.GU=function(){return(0,D.Ae)(this.J,(0,D.KD)(0.5*(this.Ah+this.$h),this.Qc+this.Zc/2))};D.E.WN=function(b,c,d,e){this.$h=b;this.Ah=c;this.Qc=d;this.Zc=e;this.Vv=D.o};D.E.QD=function(){return this.XZ?(0,D.Wf)():D.ED.q.QD.call(this)};D.E.jl=function(){var b=D.S.jd(this.Bg),c=D.S.hd(this.Bg),d=D.S.fd(this.Bg);return[this.$h,this.Ah,this.Qc,this.Zc,b,c,d]};
D.E.jo=function(b){this.WN(b[0],b[1],b[2],b[3]);this.Bg=D.S.ax(window.Math.round(b[4]),window.Math.round(b[5]),window.Math.round(b[6]));(0,D.zt)(this,D.u)};D.E.If=function(b,c){c.Vv&&0<c.Zc?D.ED.q.If.call(this,b,c):this.Mg(b)};D.E.contains=function(b,c){var d=(0,D.LD)(b,c);return window.Math.sqrt(b*b+c*c)>=this.$h&&window.Math.sqrt(b*b+c*c)<=this.Ah&&(0,D.MD)(this,d)};D.MD=function(b,c){for(;c<b.Qc;)c+=D.ut;for(;c-b.Qc>D.ut;)c-=D.ut;return c>=b.Qc&&c<=b.Qc+b.Zc};
D.KD=function(b,c){return{x:window.Math.cos(c)*b,y:window.Math.sin(c)*b}};D.LD=function(b,c){var d=window.Math.atan2(c,b);0>d?d+=D.ut:d>D.ut&&(d-=D.ut);return d};
D.ED.prototype.i0=function(){if(!this.Zc||0>=this.Zc)return D.r;var b=(0,D.ND)(this),b=new D.Pa(this.I.e,b);this.I.Sa().ma(b,this);b.B(this.Z());b.G(this.QD());var c=(0,D.nC)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR_STYLE"),d=(0,D.nC)(this,"#000000","NODE_SELECTED_OUTER_COLOR_STYLE"),e=(0,D.nC)(this,"#FFFFFF","NODE_HOVER_COLOR_STYLE");b.Y(new D.Ud((0,D.nC)(this,"#FFFFFF","NODE_DEFAULT_COLOR_STYLE"),0.3));b.Vq(new D.Ud(e,1,3));b.Xq(new D.Ud(c,1,1.5),new D.Ud(d,1,3.5));b.Vu(new D.Ud(e,1,3));b.xg(this.I.E2!=
D.r&&"off"!=this.hP);this.XZ&&(b.B(0.001),b.la(D.u));return b};
D.ND=function(b){var c,d,e,f;b.Zc<D.ut?(c=(0,D.KD)(b.Ah,b.Qc),d=(0,D.KD)(b.Ah,b.Qc+b.Zc),e=(0,D.KD)(b.$h,b.Qc+b.Zc),f=(0,D.KD)(b.$h,b.Qc),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.Ah,b.Ah,b.Zc,1,d.x,d.y)+window.DvtPathUtils.lineTo(e.x,e.y)+window.DvtPathUtils.arcTo(b.$h,b.$h,b.Zc,0,f.x,f.y)+window.DvtPathUtils.closePath()):(c=(0,D.KD)(b.Ah,b.Qc),d=(0,D.KD)(b.Ah,b.Qc+b.Zc/2),e=(0,D.KD)(b.$h,b.Qc),f=(0,D.KD)(b.$h,b.Qc+b.Zc/2),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.Ah,
b.Ah,b.Zc/2,1,d.x,d.y)+window.DvtPathUtils.arcTo(b.Ah,b.Ah,b.Zc/2,1,c.x,c.y),0<b.$h&&(c+=window.DvtPathUtils.moveTo(f.x,f.y)+window.DvtPathUtils.arcTo(b.$h,b.$h,b.Zc/2,0,e.x,e.y)+window.DvtPathUtils.arcTo(b.$h,b.$h,b.Zc/2,0,f.x,f.y)),c+=window.DvtPathUtils.closePath());return c};
D.ED.prototype.eK=function(b){if(!this.hz||!b||!this.Eo||"off"==this.Eo)return D.r;var c=D.u;"auto"==this.Eo?c=!D.J.Nd()&&D.J.zDa()==D.J.yba?D.u:D.o:"rotated"==this.Eo&&(c=D.o);if(c&&this.Zc<2*window.Math.PI){var d=window.Math.max(this.$h,10),e=this.Ah-d-6,f=1.1*this.Zc*(d+6);if(6>=f)b=D.r;else if(c=new D.nc(this.I.e,this.hz,0,0),c.wf((0,D.jC)(this)),(0,D.tC)(this,c),D.oc.Vb(c,e,f,b)){f=(d+this.Ah)/2;if("s"==this.pF||"e"==this.pF)b.k(c),b=c.C().g,"s"==this.pF?f=d+4.5+b/2:"e"==this.pF&&(f=d+e-4.5-
b/2);b=(0,D.KD)(f,this.Qc+this.Zc/2);c.rf();c.Fe();d=this.Qc+this.Zc/2;d=d>=D.ut?d-D.ut:d;d=0>d?d+D.ut:d;d>0.5*window.Math.PI&&d<1.5*window.Math.PI&&(d+=window.Math.PI);c.Si(d);(0,D.Xa)(c,b.x,b.y);c.la(D.u);b=c}else b=D.r}else{if(0==this.$h)c={x:0,y:0};else if(c=(0,D.KD)((this.$h+this.Ah)/2,this.Qc+this.Zc/2),d=3*(0,D.jC)(this)/2,e=(0,D.LD)(c.x+d/2,c.y),!(0,D.MD)(this,(0,D.LD)(c.x-d/2,c.y))||!(0,D.MD)(this,e))c=D.r;if(c){d=new D.nc(this.I.e,this.hz,c.x,c.y,D.r);d.wf((0,D.jC)(this));(0,D.tC)(this,
d);d.rf();d.Fe();d.la(D.u);for(var e=D.oc.ak(d),g=f=c.x,h=c.y-e.j/2,k=c.y+e.j/2;this.contains(f,h)&&this.contains(f,k);)f--;for(;this.contains(g,h)&&this.contains(g,k);)g++;f+=3;g-=3;c=2*window.Math.min(c.x-f,g-c.x);c<e.g&&(d.fa((f+g)/2),c=g-f);b=D.oc.Vb(d,c,e.j,b)?d:D.r}else b=D.n}return b};
D.ED.prototype.Ww=function(){if(!this.Pc){var b;b=this.J;if(!b||!("i"==this.QE||"ir"==this.QE))b=D.r;else{var c;if(this.hg){c=this.I.e;var d=this.I.de,e=new D.La(c,d.collapseUp,0,0,16,16),f=new D.La(c,d.collapseOver,0,0,16,16),d=new D.La(c,d.collapseDown,0,0,16,16)}else c=this.I.e,d=this.I.de,e=new D.La(c,d.expandUp,0,0,16,16),f=new D.La(c,d.expandOver,0,0,16,16),d=new D.La(c,d.expandDown,0,0,16,16);(0,D.vd)(e);(0,D.vd)(f);(0,D.vd)(d);c=new D.rc(c,e,f,d);c.P(D.Ta,this.Z5,D.u,this);e=(0,D.KD)(this.Ah,
this.Qc+this.Zc/2);(0,D.Xa)(c,e.x-8,e.y-8);b.k(c);b=this.hg?this.I.de.collapse:this.I.de.expand;this.I.Sa().ma(c,new D.wt(this,this.getId(),b));b=c}this.Pc=b}D.ED.q.Ww.call(this)};D.ED.prototype.Kq=function(){this.Pc&&this.J&&(this.J.removeChild(this.Pc),this.Pc=D.r);D.ED.q.Kq.call(this)};
D.zt=function(b,c){if(b.J){var d=(0,D.ND)(b);b.J.ck(d);if(b.$e||!(0==b.$h&&b.Zc==D.ut))b.Ya&&b.J.removeChild(b.Ya),b.Ya=b.eK(b.J),b.To&&(b.J.removeChild(b.To),b.To=D.r);b.J.G(b.QD());if(c)for(var d=b.pb(),e=0;e<d.length;e++)(0,D.zt)(d[e],D.o)}};
D.ED.prototype.Z5=function(){this.hg=!this.hg;var b=this.I,c=this.hg,d=this.getId();b.nL=d;if(c)b.ib(new D.GD("sunburstExpand",this.getId()));else{var c=b.cY,d=this.getId(),d=c.indexOf('\x3cn id\x3d"'+d),e=c.indexOf("\x3e",d),f=c.substring(d,e),f=-1<f.indexOf("di\x3d")?f.replace('di\x3d"t"','di\x3d"f"'):f+'di\x3d"f"';b.L(c.substring(0,d)+f+c.substring(e),b.ub,b.Mb);b.ib(new D.GD("sunburstCollapse",this.getId()))}};D.ED.prototype.nb=(0,D.C)("hg");
D.HD=function(b){return b.Qj!=D.r?(0,window.Number)(b.Qj):b.$e?1:b.XZ?0.25:b.gM?1:0.5};
D.vt={};D.F.o(D.vt,D.F,"DvtSunburstLayout");D.vt.Mn=function(b,c,d,e,f){var g=D.vt.Tda(c);D.vt.Ef(b/g,c,d,e,f,0)};D.vt.Ef=function(b,c,d,e,f,g){var h=g+(0,D.HD)(c)*b;c.WN(g,h,d,e);g=c.pb();if(g!=D.r&&c.nb()){"on"==f&&(g=g.slice(0),g.sort(function(b,c){return c.xc()-b.xc()}));D.J.S(c.I.e)&&(g=g.slice(0).reverse());var k=0;for(c=0;c<g.length;c++)k+=0<g[c].xc()?g[c].xc():0;for(c=0;c<g.length;c++){var m=g[c];if(!(0>=m.xc())){var p=m.xc()/k*e;D.vt.Ef(b,m,d,p,f,h);d+=p}}}};
D.vt.Tda=function(b){var c=0,d=b.pb();if(d&&0<d.length){for(var e=0;e<d.length;e++)var f=D.vt.Tda(d[e]),c=window.Math.max(c,f);return c+(0,D.HD)(b)}return(0,D.HD)(b)};
D.GD=function(b,c){this.Init(b);this.Qa=c?c:D.r};D.F.o(D.GD,D.ed,"DvtSunburstExpandCollapseEvent");D.GD.prototype.getId=(0,D.C)("Qa");
D.xt=function(b,c,d,e){D.eq.call(this,b,c,d,e)};D.F.o(D.xt,D.eq,"DvtSunburstEventManager");D.E=D.xt.prototype;D.E.kl=function(b){var c=(0,D.Ac)(this,b.target);c&&c.getId&&"_rotationShape"==c.getId()&&!this.nQ?(this.nQ=D.o,b=(0,D.rg)(this.e,b.pageX,b.pageY),c=this.I,(0,D.At)(c,(0,D.Dt)(c,b.x,b.y))):D.xt.q.kl.call(this,b)};D.E.Xm=function(b){if(this.nQ){b=(0,D.rg)(this.e,b.pageX,b.pageY);var c=this.I;(0,D.Bt)(c,(0,D.Dt)(c,b.x,b.y))}else D.xt.q.Xm.call(this,b)};
D.E.Ym=function(b){this.nQ?(this.nQ=D.u,(0,D.Ct)(this.I)):D.xt.q.Ym.call(this,b)};D.E.cm=function(b){var c=D.o,d=b.keyCode,e=(0,D.pm)(this),f=this.I;("i"==e.QE||"ir"==e.QE)&&((0,D.yi)(b)&&!e.nb()||(0,D.zi)(b)&&e.nb()||b.ctrlKey&&13==d)?(e.Z5(),b.preventDefault()):f&&"on"==f.Bja&&(37==d||39==d)&&!b.ctrlKey&&b.altKey&&b.shiftKey?(d=37==d?-5*(window.Math.PI/180):5*(window.Math.PI/180),(0,D.At)(f,0),(0,D.Bt)(f,d),(0,D.Ct)(f),b.preventDefault()):c=D.xt.q.cm.call(this,b);return c};
D.E.TD=function(b){var c=(0,D.Ac)(this,b.target);c&&(c.getId&&"_rotationShape"==c.getId())&&(0,D.Hi)(b,this.Ora,this)};D.E.LO=function(b){(0,D.Pi)(this.Nb,b,"rotateKey")};D.E.KO=function(b){(0,D.Qi)(this.Nb,b,"rotateKey")};D.E.Ora=function(b,c){if(1>=(0,D.Yi)(this.Nb,"rotateKey").length){(0,D.ph)(this.Nb,c.identifier,"rotateKey",D.r,"rotateKey","rotateKey",this.Nra,this.Mra,this);(0,D.Zi)(this.Nb,c.identifier,D.u);var d=(0,D.rg)(this.e,c.pageX,c.pageY),e=this.I;(0,D.At)(e,(0,D.Dt)(e,d.x,d.y));b.gs()}};
D.E.Nra=function(b,c){var d=(0,D.rg)(this.e,c.pageX,c.pageY),e=this.I;(0,D.Bt)(e,(0,D.Dt)(e,d.x,d.y));b.preventDefault()};D.E.Mra=function(){(0,D.Ct)(this.I)};
D.FD=(0,D.z)();D.F.o(D.FD,D.km,"DvtSunburstBundle");D.FD._defaults={COLOR:"Color",SIZE:"Size"};D.FD.prototype.fA=function(b){return D.FD._defaults[b]};D.FD.prototype.eA=(0,D.ca)("DvtSunburstBundle");
D.st=function(){this.Init({skyros:D.OD,alta:{}})};D.F.o(D.st,D.wC,"DvtSunburstDefaults");D.OD={rotation:"on"};
D.Ft=(0,D.z)();D.F.o(D.Ft,D.dC,"DvtSunburstJsonUtils");D.E=D.Ft.prototype;D.E.DO=(0,D.ca)("sunburst");D.E.gJ=function(b){var c=D.Ft.q.gJ.call(this,b),c=c+this.Ca("r",b.rotation),c=c+this.Ca("sa",(b.startAngle+360)%360);b=b.animationOnDisplay;return c="auto"==b?c+this.Ca("adi","fan"):c+this.Ca("adi",b)};
D.E.hJ=function(b,c){var d=D.Ft.q.hJ.call(this,b,c),d=d+this.Ca("ld",c.labelDisplay?c.labelDisplay:b.nodeDefaults.labelDisplay),e=c.labelHalign?c.labelHalign:b.nodeDefaults.labelHalign;"inner"==e?d+=this.Ca("ha","s"):"outer"==e&&(d+=this.Ca("ha","e"));e=c.radius;e!=D.r&&!(0,window.isNaN)(e)&&(d+=this.Ca("r",e));return d};
D.E.lZ=function(b){var c,d=new D.FD;c="\x3cresources"+this.Ca("legendSize",(0,D.Wm)(d,"SIZE"));c+=this.Ca("legendColor",(0,D.Wm)(d,"COLOR"));c+=this.Ca("cursorRotate",b._resources.rotateCursor);c+=this.Ca("alta","true");return c+"/\x3e\n"};
D.E.iJ=function(b){var c=D.Ft.q.iJ.call(this,b),d=b.animationUpdateColor;d&&(c+=this.Ca("top","-tr-animation-update-color: "+d));(d=b.nodeDefaults.borderColor)&&(c+=this.Ca("node","border-color: "+d));(d=b.nodeDefaults.hoverColor)&&(c+=this.Ca("node-hover","border-color: "+d));(b=b.nodeDefaults.selectedColor)&&(c+=this.Ca("node-selected","border-color: "+b));return c+"/\x3e\n"};
});