define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Yo=function(b,c,d){this.Init(b,c,d)};D.F.o(D.Yo,D.Zo,"DvtBaseTreemap");D.E=D.Yo.prototype;D.E.Init=function(b,c,d){D.Yo.q.Init.call(this,b,c,d);this.hf=new D.$o};D.E.gv=function(b){return(new D.ap(this)).parse(b)};D.E.nI=function(b){D.Yo.q.nI.call(this,b);this.Ef=b.Mn;this.Twa=b.v7;this.Ef&&(this.Ef.nP=this.nP);this.bd=[];if((b=b.Hna)&&this.kb){var c=(0,D.bp)(this.kb);c.push(this.kb);for(var d=0;d<c.length;d++)if(c[d].getId()==b){this.bd.push(c[d]);break}}};
D.E.bo=function(b){var c=window.Math.max(window.Math.ceil(7*window.Math.min(b.g,b.j)/400),2);b.x+=c;b.y+=c;b.g-=2*c;b.j-=2*c;c=this.Ef.z6(this,1);b.x+=c;b.g-=2*c;(0,D.cp)(this,b);(0,D.dp)(this,b);b.x-=c;b.g+=2*c;c=this.bd.length;if(0<c&&this.$R)this.Ef.Mn(this,this.bd[c-1],b.x,b.y,b.g,b.j,D.o);else{this.kb&&this.Ef.Mn(this,this.kb,b.x,b.y,b.g,b.j,D.u);for(var d=0;d<c;d++)this.Ef.Mn(this,this.bd[d],b.x,b.y,b.g,b.j,D.o)}};
D.E.ll=function(b){this.dP(b,"background-color:#EBEFF5;border-color:#DBE0EA;border-width:2px");this.ur&&b.k(this.ur);this.Ua&&(b.k(this.Ua),this.Ua=D.r);if((0,D.ep)(this)){this.d1=new D.H(this.e);b.k(this.d1);this.Hxa?this.Hxa.L(b):this.kb.pe()?this.kb.Ru(b):this.kb.L(b);this.G1=new D.H(this.e);b.k(this.G1);this.du=new D.H(this.e);b.k(this.du);b.k(this.d1);this.xy=new D.Ye(this.e,[]);this.xy.$a(D.u);this.xy.la(D.u);(0,D.ic)(this.xy);b.k(this.xy);for(b=0;b<this.bd.length;b++){var c=this.bd[b].La();
this.G1.k(c)}}else(0,D.fp)(this,b)};D.E.wp=function(){this.JW||(this.ga.Qi(),this.bo(new D.I(0,0,this.ub,this.Mb)),this.ll(this.ga),this.QY());D.Yo.q.wp.call(this)};D.E.QY=function(){for(var b=this.Kb?this.Kb.getSelection():[],c=0;c<b.length;c++)if(0<this.bd.length){var d=this.bd[this.bd.length-1];(b[c]==d||b[c].VC(d))&&b[c].Ob(D.o)}else b[c].Ob(D.o)};D.E.ND=function(b){return new D.gp(b)};D.E.YW=function(b,c,d,e){return new D.hp(b,c,d,e)};
D.E.y$=function(b){var c=(0,D.ip)(this);return c?(0,D.jp)(this,(0,D.kp)(c)):b?(0,D.jp)(this,(0,D.kp)(b)):D.r};D.E.EP=function(b){for(var c=0,d=this.du.Aa(),e=0;e<d;e++){var f=this.du.ca(e);b.zIndex>f.zIndex&&(c=e+1)}c<d?this.du.Ha(b,c):this.du.k(b)};D.ip=function(b){return b.bd&&0<b.bd.length?b.bd[b.bd.length-1]:D.r};
D.mp=function(b,c){if(b.lI){for(var d=b.Kb?b.Kb.getSelection():[],e=0;e<d.length;e++)d[e].Ob(D.u);for(var d=[(0,D.lp)(c)],e=(0,D.bp)(c),f=0;f<e.length;f++)d.push((0,D.lp)(e[f]));b.Sm=new D.Nd(b.e,d);b.Sm.Ad(b.wp,b);b.wa.Es(b);b.Sm.play()}else b.L(D.r,b.ub,b.Mb,D.o)};D.jp=function(b,c){var d=b.wa.Hj;return d?d.t6(c):c&&0<c.length?c[0]:D.r};
D.np=(0,D.z)();(0,D.ta)("DvtTreemap",D.np);D.F.o(D.np,D.Yo,"DvtTreemap");D.np.newInstance=function(b,c,d){var e=new D.np;e.Init(b,c,d);return e};D.np.getDefaults=function(b){return(0,D.Sb)(new D.$o,b)};D.np.prototype.L=function(b,c,d,e){b?(this.W=this.hf.sg(b),D.J.Nh()||(this.W.animationOnDisplay="none",this.W.animationOnDataChange="none")):this.W||(this.W=(0,D.Vb)(this));b=e?D.r:(new D.op(this.e)).b9(this.W);D.np.q.L.call(this,b,c,d)};D.np.prototype.render=D.np.prototype.L;
D.ap=function(b){this.Init(b)};D.F.o(D.ap,D.WB,"DvtTreemapParser");D.E=D.ap.prototype;D.E.Um=function(b,c,d){return new D.XB(b,c,d)};D.E.bm=function(b){var c=D.ap.q.bm.call(this,b),d=b.l("layout");c.Mn="h"==d?new D.$B(D.o):"v"==d?new D.$B(D.u):new D.aC;c.v7=b.l("gg");c.v7||(c.v7="o");c.Hna=b.l("irk");this.Fxa=c.Hna;return c};
D.E.iv=function(b){var c=D.ap.q.iv.call(this,b);c.Xma=b.l("gld");c.zV=b.l("ha");c.Kna=b.l("va");c.Gna=b.l("hi");c.PEa=b.l("unc");c.rna=b.l("hha");if(b=b.l("hls"))c.OEa=new D.P(b);this.Fxa==c.id&&(c.Tl=D.o);return c};D.E.rY=function(b,c,d,e){e.NODE_HOVER_COLOR=c.v("border-color");e.NODE_SELECTED_OUTER_COLOR=d.v("-tr-outer-color");e.NODE_SELECTED_INNER_COLOR=d.v("-tr-inner-color")};
D.E.Paa=function(b,c){var d=new D.P(b.l("nodeHeader"));c.HEADER_TEXT_DEFAULT_STYLE=d;c.HEADER_BACKGROUND_STYLE=d;var e=d.clone().zb(new D.P(b.l("nodeHeader-hover")));c.HEADER_TEXT_HOVER_DEFAULT_STYLE=e;c.HEADER_BACKGROUND_HOVER_STYLE=e;var f=d.clone().zb(new D.P(b.l("nodeHeader-selected")));c.HEADER_TEXT_SELECTED_DEFAULT_STYLE=f;c.HEADER_BACKGROUND_SELECTED_STYLE=f;d=d.clone().zb(new D.P(b.l("nodeHeaderDrill")));c.HEADER_DRILL_TEXT_DEFAULT_STYLE=d;c.HEADER_DRILL_TEXT_HOVER_DEFAULT_STYLE=d.clone().zb(new D.P(b.l("nodeHeaderDrill-hover")));
c.HEADER_DRILL_TEXT_SELECTED_DEFAULT_STYLE=d.clone().zb(new D.P(b.l("nodeHeaderDrill-selected")));c.HEADER_HOVER_OUTER_COLOR_STYLE=e.v("-tr-outer-color");c.HEADER_HOVER_INNER_COLOR_STYLE=e.v("-tr-inner-color");c.HEADER_SELECTED_OUTER_COLOR_STYLE=f.v("-tr-outer-color");c.HEADER_SELECTED_INNER_COLOR_STYLE=f.v("-tr-inner-color")};
D.XB=function(b,c,d){this.Init(b,c,d);this.Eo=c.yV?c.yV:"n";this.Uwa=c.Xma?c.Xma:"h";this.pF=c.zV?c.zV:"c";this.L1=c.Kna?c.Kna:"c";this.kxa=c.rna?c.rna:"s";this.aga=c.OEa;this.i1="on"==c.PEa;this.Exa=c.Gna?c.Gna:"on";this.By=c.Tl};D.F.o(D.XB,D.iC,"DvtTreemapNode");D.E=D.XB.prototype;
D.E.L=function(b){if(this.Vv){this.J=this.i0();b.k(this.J);var c;this.pe()?(this.CQ=new D.H(this.I.e),this.J.k(this.CQ),this.Ru(this.CQ)):c=this.gM;if(c){var d=this.I.MZ;d.wo=this.Wh;var e=this.R-8-2,f=this.X-4-2;0<e&&0<f&&((0,D.sr)(d,e),(0,D.tr)(d,f),d.wf((0,D.jC)(this)),this.X_=c=D.mq.oD(d,c,this.J),D.J.S(b.e)?(b=c.C(),b=this.Za+this.R-4-1-b.g):b=this.Za+4+1,(0,D.Xa)(c,b,this.Ja+2+1))}else this.Ya=this.eK(this.J),this.Ya!=D.r&&(this.No&&"h"!=this.lj)&&(b=this.Ya.Ub(),this.To=new D.td(this.I.e,b.x,
b.y,b.g,b.j),this.To.na("#FFFFFF"),this.To.la(D.u),this.J.k(this.To),b=this.Ya,"n"==this.lj&&this.pe()?this.I.d1.k(b):this.J.k(b));(0,D.vf)(this.J);(0,D.xf)(this.J,"label",this.my)}};
D.E.Ob=function(b){if("off"!=this.hP&&(D.XB.q.Ob.call(this,b),this.J))if(this.mb()){b=this.Za;var c=this.Ja+1,d=this.R-1,e=this.X-1;D.J.dp()&&(c-=1);(0,D.kC)(this,this.Hf);(0,D.kC)(this,this.eu);this.eu=this.Hf=D.r;this.Hf=new D.td(this.I.e,b,c,d,e);this.Hf.la(D.u);this.Hf.G(D.r);(0,D.ic)(this.Hf);this.J.k(this.Hf);this.eu=new D.td(this.I.e,b+1,c+1,d-2,e-2);this.eu.la(D.u);this.eu.G(D.r);(0,D.ic)(this.eu);this.J.k(this.eu);"h"==this.lj?(this.JI||this.li()?(0,D.lC)(this,this.J,this.Vp,"background-color:#C4DCFF;",
"HEADER_BACKGROUND_HOVER_STYLE"):((0,D.lC)(this,this.J,this.Vp,"background-color:#9CACC9;","HEADER_BACKGROUND_SELECTED_STYLE"),this.Ya&&(0,D.mC)(this,this.Ya,"HEADER_TEXT_SELECTED_DEFAULT_STYLE","#003D5B")),this.Hf.Ma((0,D.nC)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),1),this.eu.Ma((0,D.nC)(this,"#FFFFFF","HEADER_SELECTED_INNER_COLOR_STYLE"),1)):(this.Hf.Ma((0,D.nC)(this,"#000000","NODE_SELECTED_OUTER_COLOR"),1),this.eu.Ma((0,D.nC)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR"),1),D.J.cp()||
(0,D.bf)(this.J,D.yt),this.I.EP(this.J))}else(0,D.kC)(this,this.eu),this.eu=D.r,"h"==this.lj?(this.JI||this.li()?(0,D.lC)(this,this.J,this.Vp,"background-color:#C4DCFF;","HEADER_BACKGROUND_HOVER_STYLE"):((0,D.lC)(this,this.J,this.Vp,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),this.Ya&&(this.Nq()?(0,D.mC)(this,this.Ya,"HEADER_TEXT_DEFAULT_STYLE","#003286"):(0,D.mC)(this,this.Ya,"HEADER_TEXT_DEFAULT_STYLE","#003D5B"))),this.Hf&&(this.JI||this.li()?this.Hf.Ma((0,D.nC)(this,
"#00AEFF","HEADER_HOVER_OUTER_COLOR_STYLE"),"1"):((0,D.kC)(this,this.Hf),this.Hf=D.r))):((0,D.cf)(this.J),this.Hf&&((0,D.kC)(this,this.Hf),this.Hf=D.r),(b=this.$e)&&b.CQ&&b.CQ.k(this.J))};
D.E.Dc=function(){if(this.J&&this.Vv){var b=(0,D.ip)(this.I);if(!(b!=D.r&&b!=this&&!this.VC(b))){var b=[],c,d,e,f;"h"==this.lj?((0,D.lC)(this,this.J,this.Vp,"background-color:#C4DCFF;","HEADER_BACKGROUND_HOVER_STYLE"),this.Hf||(d=this.Za,c=this.Ja+1,e=this.R-1,f=this.X-1,D.J.dp()&&(c-=1),this.Hf=new D.td(this.I.e,d,c,e,f),this.Hf.la(D.u),this.Hf.G(D.r),(0,D.ic)(this.Hf),this.J.k(this.Hf)),this.mb()?this.Hf.Ma((0,D.nC)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),D.XB.nqa):this.Hf.Ma((0,D.nC)(this,
"#00AEFF","HEADER_HOVER_OUTER_COLOR_STYLE"),"1"),d=this.Za+1.5+1,e=this.Za+this.R-1.5-1,c=this.Ja+this.Gl,f=this.Ja+this.X-1.5-1,b.push(e,c,e,f,d,f,d,c),c=new D.Ud((0,D.nC)(this,"#C4DCFF","HEADER_HOVER_INNER_COLOR_STYLE"),0.8,3),this.Ya&&(this.Nq()?(0,D.mC)(this,this.Ya,"HEADER_DRILL_TEXT_HOVER_DEFAULT_STYLE","#000000"):(0,D.mC)(this,this.Ya,"HEADER_TEXT_HOVER_DEFAULT_STYLE","#000000"))):(d=this.Za+1,e=this.Za+this.R-1,c=this.Ja+1,f=this.Ja+this.X-1,b.push(this.Za,c,e,c,e,f,d,f,d,c),c=new D.Ud((0,D.nC)(this,
"#FFFFFF","NODE_HOVER_COLOR"),1,2));d=this.I;d.xy.fc(b);d.xy.Y(c);d.xy.$a(D.o)}}};
D.E.sc=function(){this.J&&this.Vv&&("h"==this.lj&&(this.mb()?((0,D.lC)(this,this.J,this.Vp,"background-color:#9CACC9;","HEADER_BACKGROUND_SELECTED_STYLE"),this.Hf.Ma((0,D.nC)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),D.XB.nqa),this.Ya&&(this.Nq()?(0,D.mC)(this,this.Ya,"HEADER_DRILL_TEXT_SELECTED_DEFAULT_STYLE","#003D5B"):(0,D.mC)(this,this.Ya,"HEADER_TEXT_SELECTED_DEFAULT_STYLE","#003D5B"))):((0,D.lC)(this,this.J,this.Vp,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),
this.Hf&&(this.J.removeChild(this.Hf),this.Hf=D.r),this.Ya&&(this.Nq()?(0,D.mC)(this,this.Ya,"HEADER_DRILL_TEXT_DEFAULT_STYLE","#003286"):(0,D.mC)(this,this.Ya,"HEADER_TEXT_DEFAULT_STYLE","#003D5B")))),this.I.xy.$a(D.u))};D.E.WC=function(){return"on"==this.Exa&&"h"==this.lj};D.E.JC=function(b){return!b||!b.vC()?D.XB.q.JC.call(this,b):new D.I(this.Za,this.Ja,this.R,this.X)};
D.E.nh=function(b){var c;if(b.type==D.Ta)return D.XB.q.nh.call(this,b);c=b.keyCode;if(32==c&&b.ctrlKey)return this;if(38==c&&b.altKey||221==c)(c=this.$e)&&c.getId()!=this.I.kb.getId()?(b=c,(0,D.oC)(c)):b=this;else if(40==c&&b.altKey||219==c)b=(b=this.hS)?b:this.pe()?(0,D.jp)(this.I,this.pb()):this;else{var d=(0,D.ip)(this.I),e=0;if(d)if(this==d)e=0;else{c=this.$e;for(e=1;d!=c;)e++,c=c.$e}else{for(d=this;d.$e;)d=d.$e;e=(0,D.pC)(this)}c=(0,D.qC)(this,d,e);b=(0,D.$n)(this,b,c)}(0,D.oC)(b);return b};
D.E.Je=function(){return new D.I(this.Za,this.Ja,this.R,this.X)};
D.E.WN=function(b,c,d,e){if(!(0>=d||0>=e)){this.Vv=D.o;this.ria=this.jl();this.Za=b;this.Ja=c;this.R=d?d:0;this.X=e?e:0;this.lj=this.pe()?this.Uwa:this.Eo;this.hz||(this.lj="o");if("h"==this.lj){this.Gl=15;b=new D.nc(this.I.e,this.hz);b.wf((0,D.jC)(this));(0,D.mC)(this,b,"HEADER_TEXT_DEFAULT_STYLE","#003D5B");b=D.oc.ak(b).j;this.Gl=window.Math.max(this.Gl,b);this.WC()&&(this.Gl=window.Math.max(this.Gl,15));b=this.Za;c=this.Ja+this.Gl;d=this.R;e=this.X-this.Gl;if(0<=d&&0<=e)return new D.I(b,c,d,e);
this.lj=D.r}return new D.I(this.Za,this.Ja,this.R,this.X)}};D.E.contains=function(b,c){return b>=this.Za&&b<=this.Za+this.R&&c>=this.Ja&&c<=this.Ja+this.X};D.E.jl=function(){var b=D.S.jd(this.Bg),c=D.S.hd(this.Bg),d=D.S.fd(this.Bg);return[this.Za,this.Ja,this.R,this.X,b,c,d,this.pe()?0:window.Math.random()]};
D.E.jo=function(b){this.WN(b[0],b[1],b[2],b[3]);this.Bg=D.S.ax(window.Math.round(b[4]),window.Math.round(b[5]),window.Math.round(b[6]));this.J&&((0,D.Jf)(this.J,this.Za,this.Ja,this.R,this.X),this.Vp&&(0,D.Jf)(this.Vp,this.Za+1,this.Ja+1,this.R-2,this.X-2),("h"!=this.lj||this.i1)&&this.J.G(this.QD()),this.mb()&&this.Ob(D.u),(0,D.kC)(this,this.Ov),(0,D.kC)(this,this.pM),this.pM=this.Ov=D.r,(0,D.rC)(this),this.gM?((0,D.kC)(this,this.X_),this.X_=D.r):((0,D.kC)(this,this.To),this.To=D.r,this.Ya&&this.Ya.getParent().removeChild(this.Ya),
this.Ya=this.eK(this.J)))};D.lp=function(b){if(b.ria){var c=new D.Nj(b.I.e,b,0.3);(0,D.N)(c.T,"typeNumberArray",b,b.jl,b.jo,b.jl());b.jo(b.ria);return c}return D.r};D.XB.prototype.If=function(b,c){return 0==(0,D.pC)(this)||c.Vv&&0<c.R&&0<c.X?D.XB.q.If.call(this,b,c):this.Mg(b)};
D.XB.prototype.i0=function(){var b=this.I.e,c;if("h"==this.lj)c=new D.td(b,this.Za,this.Ja,this.R,this.X),this.Vp=new D.td(b,this.Za+1,this.Ja+1,this.R-2,this.X-2),(0,D.lC)(this,c,this.Vp,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),this.Vp.la(D.u),c.k(this.Vp),this.By&&(this.ue=(0,D.sC)(this,c));else{var d=this.QD();c=new D.td(b,this.Za,this.Ja,this.R,this.X);if((1E3>this.I.Al||!D.J.da())&&2<=this.R&&2<=this.X){new D.Ud((0,D.nC)(this,"#FFFFFF","LEAF_NODE_TOP_BORDER_COLOR_STYLE"),
0.3);new D.Ud((0,D.nC)(this,"#000000","LEAF_NODE_BOTTOM_BORDER_COLOR_STYLE"),0.3);this.No&&new D.Ud(this.Bg,0.15);var e=this.Lb(),f=(0,D.nC)(this,"#FFFFFF","LEAF_NODE_TOP_BORDER_COLOR_STYLE"),f=D.S.xH(f,e,0.7),g=(0,D.nC)(this,"#000000","LEAF_NODE_BOTTOM_BORDER_COLOR_STYLE"),g=D.S.xH(g,e,0.7),e=window.Math.min(this.R,this.X);4<=e?(c.na(g),this.pM=new D.td(b,this.Za,this.Ja,this.R-1,this.X-1),this.pM.na(f),this.pM.la(D.u),c.k(this.pM),this.Ov=new D.td(b,this.Za+1,this.Ja+1,this.R-2,this.X-2),this.Ov.G(d),
this.Ov.la(D.u),c.k(this.Ov)):2<=e?(c.na(g),this.Ov=new D.td(b,this.Za,this.Ja,this.R-1,this.X-1),this.Ov.G(d),this.Ov.la(D.u),c.k(this.Ov)):c.G(d)}else c.G(d)}this.I.Sa().ma(c,this);this.I.E2!=D.r&&"off"!=this.hP?c.xg(D.o):c.setCursor("default");c.zIndex=this.WT;return c};
D.sC=function(b,c){if("h"!=b.lj||!b.WC())return D.r;var d=D.r,e=b.Za,f=b.Za+b.R-1,g=b.Ja+1,h=b.Ja+b.Gl;if(12<f-e-2){if(b.By){var d=b.I.e,k=b.I.de,m=new D.La(d,k.restoreUp,0,0,12,12),p=new D.La(d,k.restoreOver,0,0,12,12),k=new D.La(d,k.restoreDown,0,0,12,12);(0,D.vd)(m);(0,D.vd)(p);(0,D.vd)(k);d=new D.rc(d,m,p,k);d.P(D.Ta,b.$ca,D.u,b)}else d=b.I.e,k=b.I.de,m=new D.La(d,k.maximizeUp,0,0,12,12),p=new D.La(d,k.maximizeOver,0,0,12,12),k=new D.La(d,k.maximizeDown,0,0,12,12),(0,D.vd)(m),(0,D.vd)(p),(0,D.vd)(k),
d=new D.rc(d,m,p,k),d.P(D.Ta,b.Zca,D.u,b);e=D.J.S(c.e)?e+1:f-12-1;(0,D.Xa)(d,e,(h+g-12)/2);c.k(d);D.J.da()&&(g=new D.td(c.e,-2,-2,16,16),(0,D.vd)(g),d.k(g));"true"==b.I.de.alta?b.I.Sa().ma(d,b):(g=b.By?b.I.de.restore:b.I.de.isolate,b.I.Sa().ma(d,new D.wt(b,b.getId(),g)))}return d};D.rC=function(b){b.ue&&((0,D.kC)(b,b.ue),b.ue=D.r)};
D.XB.prototype.eK=function(b){var c=D.J.S(b.e);if(!this.hz||!b||!this.lj||"o"==this.lj)return D.r;var d=this.X;if((0,D.jC)(this)>d)return D.r;var e="n"==this.lj?this.pF:this.kxa;c&&("s"==e?e="e":"e"==e&&(e="s"));var f=this.R-6,g=0;this.WC()&&(g=13,f="c"==e?f-2*g:f-g);if(0>=f)return D.r;var h=new D.nc(this.I.e,this.hz);h.wf((0,D.jC)(this));"s"==e?(c?h.fa(this.Za+4+g):h.fa(this.Za+4),h.Nk()):"c"==e?(h.fa(this.Za+this.R/2),h.rf()):"e"==e&&(c?h.fa(this.Za+this.R-4):h.fa(this.Za+this.R-4-g),h.Fi());"n"==
this.lj?(d=this.X-4,"t"==this.L1?(h.ua(this.Ja+2),h.Zo()):"c"==this.L1?(h.ua(this.Ja+this.X/2),h.Fe()):"b"==this.L1&&(h.ua(this.Ja+this.X-2),h.Dw()),(0,D.tC)(this,h)):"h"==this.lj&&(c=D.J.dp()?1:0,h.ua(this.Ja+1+this.Gl/2+c),h.Fe(),(0,D.mC)(this,h,"HEADER_TEXT_DEFAULT_STYLE","#003D5B"));if(h!=D.r)return"h"==this.lj&&this.Nq()?((0,D.mC)(this,h,"HEADER_DRILL_TEXT_DEFAULT_STYLE","#003286"),h.setCursor("pointer"),c=new D.wt(this,this.getId(),D.r,this.Jf(),this.sj()),c.M8(D.o),this.I.Sa().ma(h,c)):h.la(D.u),
D.oc.Vb(h,f,d,b)?h:D.r};D.lC=function(b,c,d,e,f){var g=new D.P(e);g.zb(b.I.yn[f]);e=g.v("background-color");g=g.v("border-color");b.i1&&"HEADER_BACKGROUND_STYLE"==f?(b=b.Lb(),d.na(b),g=D.S.xH(g,b,0.5),c.na(g)):(c.na(g),d.na(e))};D.mC=function(b,c,d,e){b.i1&&"HEADER_TEXT_DEFAULT_STYLE"==d?c.na((0,D.uC)(b)):c.na(e);e=[];1>=(0,D.pC)(b)&&b.pe()&&e.push(new D.P("font-weight:bold;"));e.push(b.I.yn[d]);b.aga&&e.push(b.aga);c.Ia((0,D.am)(e))};
D.XB.prototype.Ww=function(){this.ue||(this.ue=(0,D.sC)(this,this.J));D.XB.q.Ww.call(this)};D.XB.prototype.Kq=function(){this.By!==D.o&&(0,D.rC)(this);D.XB.q.Kq.call(this)};D.kC=function(b,c){c&&b.J.removeChild(c)};D.E=D.XB.prototype;D.E.Zca=function(){this.By=D.o;this.sc();var b=this.I,c=(0,D.pm)(b.Sa());c&&c.qe();b.bd.push(this);b.ib(new D.hC(this.getId()));b.$R=D.o;b.bo(new D.I(0,0,b.ub,b.Mb));b.$R=D.u;c=this.La();b.G1.k(c);(0,D.mp)(b,this);(0,D.rC)(this)};
D.E.$ca=function(){this.By=D.u;this.sc();var b=this.I,c=b.bd.pop(),d=(0,D.pm)(b.Sa());d&&d.qe();d=c.getId();b.nL=d;b.ib(new D.hC);b.$R=D.o;b.bo(new D.I(0,0,b.ub,b.Mb));b.$R=D.u;(0,D.mp)(b,c);(0,D.rC)(this)};D.E.Jf=function(b,c,d){return b&&b instanceof D.rc?D.r:D.XB.q.Jf.call(this,b,c,d)};D.E.sj=function(b){return b&&b instanceof D.rc?D.r:D.XB.q.sj.call(this,b)};D.E.fe=function(b){return b&&b instanceof D.rc?this.By?this.I.de.restore:this.I.de.isolate:D.r};
D.bC=function(){this.Init()};D.F.o(D.bC,D.F,"DvtBaseTreemapLayout");D.bC.prototype.Init=function(){this.WT=0};D.bC.prototype.Mn=(0,D.z)();D.cC=function(b,c,d,e,f,g,h){c.WT=b.WT;b.WT++;if(!h||!c.pe()){b=b.z6(c.I,(0,D.pC)(c));h=window.Math.round(d+b);var k=window.Math.round(e+b);if(c=c.WN(h,k,window.Math.round(d+f-b)-h,window.Math.round(e+g-b)-k))return c}return new D.I(d,e,f,g)};D.bC.prototype.z6=function(b,c){var d=b.Twa;return"o"==d?1==c&&2<=b.eq?3:0:"a"==d?c<b.eq?3:0:0};
D.aC=function(){this.Init()};D.F.o(D.aC,D.bC,"DvtSquarifyingLayout");D.aC.prototype.Mn=function(b,c,d,e,f,g,h){this.Ef(c,d,e,f,g,h?D.u:D.o)};D.aC.prototype.Ef=function(b,c,d,e,f,g){c=(0,D.cC)(this,b,c,d,e,f,g);b=b.pb();if(b!=D.r&&0<b.length){d=b;f=c.g*c.j;for(e=e=g=0;e<d.length;e++)g+=0<d[e].xc()?d[e].xc():0;f=0==f?0:f/g;for(e=0;e<d.length;e++)g=d[e],g.wA=g.xc()*f;b=b.slice(0).sort(function(b,c){return b.xc()-c.xc()});d=window.Math.min(c.g,c.j);(0,D.fC)(this,b,d,new D.I(c.x,c.y,c.g,c.j))}};
D.fC=function(b,c,d,e){var f=[],g=window.Infinity;if(c==D.r||0==c.length)(0,D.gC)(b,f,d,e);else for(;0<c.length;){var h=c.pop();if(0>h.wA){(0,D.gC)(b,f,d,e);break}f.push(h);var k,m=f,p=d,q=0;k=window.Infinity;for(var t=-window.Infinity,v=0;v<m.length;v++)q+=m[v].wA,k=window.Math.min(k,m[v].wA),t=window.Math.max(t,m[v].wA);m=q*q;p*=p;k=window.Math.max(p*t/m,m/(p*k));if(k>g){c.push(h);f.pop();e=(0,D.gC)(b,f,d,e);(0,D.fC)(b,c,window.Math.min(e.g,e.j),e);break}else if(0==c.length){(0,D.gC)(b,f,d,e);break}else g=
k}};D.gC=function(b,c,d,e){var f=0,g;for(g=0;g<c.length;g++)f+=c[g].wA;var h=e.x,k=e.y;if(d==e.g){f=0==d?0:f/d;for(g=0;g<c.length;g++)d=c[g].wA/f,b.Ef(c[g],h,k,d,f,D.u),h+=d;return new D.I(e.x,e.y+f,e.g,e.j-f)}d=0==d?0:f/d;for(g=0;g<c.length;g++)f=c[g].wA/d,b.Ef(c[g],h,k,d,f,D.u),k+=f;return new D.I(e.x+d,e.y,e.g-d,e.j)};
D.$B=function(b){this.Init();this.It=b};D.F.o(D.$B,D.bC,"DvtSliceAndDiceLayout");D.$B.prototype.Mn=function(b,c,d,e,f,g,h){this.Ef(this.It,b,c,d,e,f,g,h?D.u:D.o)};
D.$B.prototype.Ef=function(b,c,d,e,f,g,h,k){e=(0,D.cC)(this,d,e,f,g,h,k);d=d.pb();if(d!=D.r){f=e.x;g=e.y;h=e.g;k=e.j;var m=0,p;for(p=0;p<d.length;p++)m+=0<d[p].xc()?d[p].xc():0;"on"==this.nP&&(d=d.slice(0),d.sort(function(b,c){return c.xc()-b.xc()}));b&&D.J.S(c.e)&&(d=d.slice(0).reverse());for(p=0;p<d.length;p++){var q=d[p];if(!(0>=q.xc())){var t=q.xc()/m;b?h=e.g*t:k=e.j*t;this.Ef(!b,c,q,f,g,h,k,D.u);b?f+=h:g+=k}}}};
D.hC=function(b){this.Init("treemapIsolate");this.Qa=b?b:D.r};(0,D.ta)("DvtTreemapIsolateEvent",D.hC);D.F.o(D.hC,D.ed,"DvtTreemapIsolateEvent");D.hC.TYPE="treemapIsolate";D.hC.prototype.getId=(0,D.C)("Qa");D.hC.prototype.getId=D.hC.prototype.getId;
D.gp=function(b){this.Init(b)};D.F.o(D.gp,D.dq,"DvtTreemapKeyboardHandler");D.gp.prototype.bk=function(b){var c=D.gp.q.bk.call(this,b);if(!c&&(b=b.keyCode,219==b||221==b))c=D.o;return c};
D.hp=function(b,c,d,e){D.eq.call(this,b,c,d,e)};D.F.o(D.hp,D.eq,"DvtTreemapEventManager");D.hp.prototype.cm=function(b){var c=D.o;if(13==b.keyCode&&b.ctrlKey){var d=(0,D.pm)(this);d.WC()&&(d.By?d.$ca():d.Zca());b.preventDefault()}else c=D.hp.q.cm.call(this,b);return c};D.hp.prototype.J7=(0,D.ca)(D.u);
D.eC=(0,D.z)();D.F.o(D.eC,D.km,"DvtTreemapBundle");D.eC._defaults={COLOR:"Color",SIZE:"Size"};D.eC.prototype.fA=function(b){return D.eC._defaults[b]};D.eC.prototype.eA=(0,D.ca)("DvtTreemapBundle");
D.$o=function(){this.Init({skyros:D.vC,alta:{}})};D.F.o(D.$o,D.wC,"DvtTreemapDefaults");D.vC={nodeDefaults:{header:{labelStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;")}}};
D.op=(0,D.B)("e");D.F.o(D.op,D.dC,"DvtTreemapJsonUtils");D.E=D.op.prototype;D.E.DO=(0,D.ca)("treemap");D.E.gJ=function(b){var c=D.op.q.gJ.call(this,b),c=c+this.Ca("irk",b.isolatedNode),d=b.groupGaps;"all"==d?c+=this.Ca("gg","a"):"none"==d&&(c+=this.Ca("gg","n"));d=b.layout;"sliceAndDiceHorizontal"==d?c+=this.Ca("layout","h"):"sliceAndDiceVertical"==d&&(c+=this.Ca("layout","v"));b=b.animationOnDisplay;return c="auto"==b?c+this.Ca("adi","alphaFade"):c+this.Ca("adi",b)};
D.E.hJ=function(b,c){var d=D.op.q.hJ.call(this,b,c);if("off"==(c.labelDisplay?c.labelDisplay:b.nodeDefaults.labelDisplay))d+=this.Ca("ld","o");var e=c.groupLabelDisplay?c.groupLabelDisplay:b.nodeDefaults.groupLabelDisplay;"node"==e?d+=this.Ca("gld","n"):"off"==e&&(d+=this.Ca("gld","o"));e=c.labelHalign?c.labelHalign:b.nodeDefaults.labelHalign;"start"==e?d+=this.Ca("ha","s"):"end"==e&&(d+=this.Ca("ha","e"));e=c.labelValign?c.labelValign:b.nodeDefaults.labelValign;"top"==e?d+=this.Ca("va","t"):"bottom"==
e&&(d+=this.Ca("va","b"));var e=c.header,d=d+this.Ca("hls",e&&e.labelStyle?e.labelStyle:b.nodeDefaults.header.labelStyle),f=e&&e.labelHalign?e.labelHalign:b.nodeDefaults.header.labelHalign;"center"==f?d+=this.Ca("hha","c"):"end"==f&&(d+=this.Ca("hha","e"));if("off"==(e&&e.isolate?e.isolate:b.nodeDefaults.header.isolate))d+=this.Ca("hi","off");if("on"==(e&&e.useNodeColor?e.useNodeColor:b.nodeDefaults.header.useNodeColor))d+=this.Ca("unc","on");return d};
D.E.lZ=function(b){var c,d=new D.eC;c="\x3cresources"+this.Ca("legendSize",(0,D.Wm)(d,"SIZE"));c+=this.Ca("legendColor",(0,D.Wm)(d,"COLOR"));b=b._resources;d=D.J.S(this.e);c+=this.Ca("maximizeUp",d&&b.isolateRtl?b.isolateRtl:b.isolate);c+=this.Ca("maximizeDown",d&&b.isolateDownRtl?b.isolateDownRtl:b.isolateDown);c+=this.Ca("maximizeOver",d&&b.isolateOverRtl?b.isolateOverRtl:b.isolateOver);c+=this.Ca("restoreUp",d&&b.restoreRtl?b.restoreRtl:b.restore);c+=this.Ca("restoreDown",d&&b.restoreDownRtl?b.restoreDownRtl:
b.restoreDown);c+=this.Ca("restoreOver",d&&b.restoreOverRtl?b.restoreOverRtl:b.restoreOver);c+=this.Ca("alta","true");return c+"/\x3e\n"};
D.E.iJ=function(b){var c=D.op.q.iJ.call(this,b),d=b.animationUpdateColor;d&&(c+=this.Ca("top","-tr-animation-update-color: "+d));(d=b.nodeDefaults.hoverColor)&&(c+=this.Ca("node-hover","border-color: "+d));var d=b.nodeDefaults.selectedInnerColor,e=b.nodeDefaults.selectedOuterColor;(d=(d?"-tr-inner-color:"+d+";":"")+(e?"-tr-outer-color:"+e:""))&&(c+=this.Ca("node-selected",d));d=b.nodeDefaults.header.backgroundColor;e=b.nodeDefaults.header.borderColor;(d=(d?"background-color:"+d+";":"")+(e?"border-color:"+
e:""))&&(c+=this.Ca("nodeHeader",d));var e=b.nodeDefaults.header.hoverBackgroundColor,f=b.nodeDefaults.header.hoverInnerColor,d=b.nodeDefaults.header.hoverOuterColor,e=(e?"background-color:"+e+";":"")+(f?"-tr-inner-color:"+f+";":"");(e+=d?"-tr-outer-color:"+d:"")&&(c+=this.Ca("nodeHeader-hover",e));d=b.nodeDefaults.header.selectedBackgroundColor;e=b.nodeDefaults.header.selectedInnerColor;b=b.nodeDefaults.header.selectedOuterColor;d=(d?"background-color:"+d+";":"")+(e?"-tr-inner-color:"+e+";":"");
(d+=b?"-tr-outer-color:"+b:"")&&(c+=this.Ca("nodeHeader-selected",d));return c+"/\x3e\n"};
});