define(['./DvtToolkit', './DvtPanZoomCanvas', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.ua=function(b,c,d){this.Init(b,c,d)};(0,D.ta)("DvtAmxThematicMap",D.ua);D.F.l(D.ua,D.H,"DvtAmxThematicMap");D.ua.wx=10;D.ua.prototype.Init=function(b,c,d){D.ua.q.Init.call(this,b);this.N=new D.va(b,c,d);this.sT=new D.H(b);this.sT.k(this.N);this.k(this.sT);this.ef=new D.wa};D.ua.newInstance=function(b,c,d){return new D.ua(b,c,d)};D.ua.newInstance=D.ua.newInstance;D.ua.prototype.L=function(b,c,d){this.X=this.ef.pg(b);this.Q=c;this.W=d;c=new D.I(0,0,c,d);this.zL(this,c);this.N.L(b,c.g,c.j)};
D.ua.prototype.render=D.ua.prototype.L;
D.ua.prototype.zL=function(b,c){this.Na&&(b.removeChild(this.Na),this.Na=D.r);var d=new D.I(D.ua.wx,D.ua.wx,c.g-2*D.ua.wx,c.j-2*D.ua.wx),e=this.X,f=e.legend.rendered,g=e.legend.scrolling,h=D.xa.clone(e.legend);this.iZ(this.X,h);if(f&&!(h.NFa&&0==h.NFa.length)){f=e.legend.position;delete h.position;h.layout.gapRatio=this.fz();h.hideAndShowBehavior="none";h.rolloverBehavior="none";h.scrolling=e.legend.scrolling;var k=(0,D.ya)(this.N.e,D.r,D.r);this.N.getId()!=D.r&&k.setId(this.N.getId()+"legend");b.k(k);
"auto"==f&&"asNeeded"!==g?f="bottom":"auto"==f&&"asNeeded"==g&&(f="end");g=D.K.R(b.e);"start"==f?f=g?"right":"left":"end"==f&&(f=g?"left":"right");h.orientation="left"==f||"right"==f?"vertical":"horizontal";g="top"==f||"bottom"==f;g=k.mz(h,g?d.g:e.layout.legendMaxSize*d.g,g?e.layout.legendMaxSize*d.j:d.j);if(0<g.g&&0<g.j)switch(k.L(h,g.g,g.j),this.Na=k,e=window.Math.ceil(e.layout.legendGap*this.fz()),(0,D.za)(d,f,k,g.g,g.j,e),f){case "top":this.sT.O(g.j+D.ua.wx);case "bottom":c.j-=g.j+D.ua.wx;break;
case "left":this.sT.F(g.g+D.ua.wx);case "right":c.g-=g.g+D.ua.wx}}};D.ua.prototype.fz=function(){if(this.X.layout.gapRatio!==D.r&&!(0,window.isNaN)(this.X.layout.gapRatio))return this.X.layout.gapRatio;var b=window.Math.min(this.Q/400,1),c=window.Math.min(this.W/300,1);return window.Math.min(b,c)};
D.ua.prototype.iZ=function(b,c){c.title=b.legend?b.legend.title:D.r;c.sections=[];if(b&&b.legend&&b.legend.sections)for(var d=0;d<b.legend.sections.length;d++){var e=b.legend.sections[d];e&&c.sections.push({title:e.title,items:e.items,sections:e.sections})}return c};
D.va=function(b,c,d){this.Init(b,c,d)};(0,D.ta)("DvtThematicMap",D.va);D.F.l(D.va,D.Aa,"DvtThematicMap");
D.va.prototype.Init=function(b,c,d){D.va.q.Init.call(this,b);this.Xa=c;this.ka=d;(0,D.Ba)(this);this.ye=[];this.xv=[];this.cxa=this.Ao=this.lc=this.Na=D.r;this.IP=D.u;this.DE=[];this.ZE={};this.KS=D.u;this.UQ={};this.m_={};this.km=[];this.sZ=new D.H(this.e);this.UJ=new D.H(this.e);this.tv=new D.H(this.e);this.wt=new D.H(this.e);this.wR=D.u;this.GF=this.Zy=D.o;this.M1=6;this.Br=D.o;this.ZF={};this.Xi=16777215;this.ef=new D.wa;this.bb=new D.Ca};D.va.newInstance=function(b,c,d){return new D.va(b,c,d)};
D.va.prototype.Yd=function(b){this.X=this.ef.pg(b);D.K.Kh()||(this.X.animationOnDisplay="none",this.X.animationOnMapChange="none",this.X.animationOnDrill="none");this.X.skin||(this.X.skin="alta")};D.va.prototype.L=function(b,c,d){b&&"object"==typeof b&&this.Yd(b);D.va.q.L.call(this,b,c,d)};D.va.prototype.render=D.va.prototype.L;D.Da=function(b,c){for(var d=0;d<b.ye.length;d++)if(b.ye[d].vf==c)return b.ye[d]};D.E=D.va.prototype;D.E.Mn=function(b){this.Ts=(0,window.parseFloat)(b)};D.E.Ta=(0,D.C)("Ts");
D.E.Hz=function(b){this.wh=(0,window.parseInt)(b);D.va.q.Hz.call(this,this.wh);b=this.Xi;if(1==this.wh||3==this.wh||5==this.wh||7==this.wh)b&=-17,this.GF=D.u;if(2==this.wh||3==this.wh||6==this.wh||7==this.wh)b&=-4098,this.Zy=D.u;if(4==this.wh||5==this.wh||6==this.wh||7==this.wh)b&=-257;this.Xi=b};D.E.OV=function(b){this.Jj=b;this.xa.OV(b)};D.E.cN=function(b,c,d,e){"object"==typeof b&&this.X?(new D.Ea(this)).parse(this.X):b==D.r||0==b.length||D.va.q.cN.call(this,b,c,d,e)};
D.E.DX=function(b,c){this.wf=D.u;this.kya&&(this.ye=[],this.DE=[],this.ZE={},this.UQ={},this.m_={},this.km=[],this.removeChild(this.lc),this.cxa=this.Ao=this.Na=this.lc=D.r,this.Hz(0),this.Xi=16777215,this.GF=this.Zy=D.o,this.wF=this.xb,this.sZ=new D.H(this.e),this.UJ=new D.H(this.e),this.tv=new D.H(this.e),this.wt=new D.H(this.e),(0,D.Ba)(this));this.xa.oc();this.Wz().cV(c)};D.Ba=function(b){b.xa=new D.Fa(b.e,b.ib,b);b.xa.$e(b);D.K.da()?b.e1=D.r:(b.e1=new D.Ga(b,b.xa),(0,D.Ha)(b.xa,b.e1))};D.E=D.va.prototype;
D.E.epa=function(b){D.K.R(this.e)||(b=this.Q-5-b.getWidth(),this.lc.F(b))};
D.E.zL=function(){if(this.Ao){this.lc&&(this.lc.V(),this.removeChild(this.lc));var b="true"==this.Ao.o("disclosed"),c="fixed"==this.Ao.o("display")||D.K.ku();if(!c||b){var d=this.Ao.o("maxWidth"),e=d.indexOf("%"),d=-1!=e?(0,window.parseFloat)(d.substring(0,e))/100*this.Q:(0,window.parseFloat)(d),e=this.W-10;if("alta"==this.Tb)this.lc=new D.Ia(this.e,D.r,this,"pd"),this.lc.P("dvtPanelDrawerEvent",this.Y9,D.u,this),this.lc.Ql(d),this.lc.jD(e),this.lc.Ov=c,D.K.R(this.e)?(this.lc.sr="right",this.lc.F(0)):
this.lc.F(this.Q);else{this.lc=new D.Ja(this.e,d,e,f,(0,D.Ka)(this),this.$r(),b,c);this.lc.P("dvtCollapsiblePanelEvent",this.Y9,D.u,this);this.lc.P("dvtResizeEvent",this.epa,D.u,this);var d=this.Ao.o("expandTooltip"),e=this.Ao.o("collapseTooltip"),f=D.K.R(this.e)?"col_northwest":"col_northeast",f=this.lc;f.UA=d;f.FA=e}this.Na=new D.DvtCommonLegend(this.e,this.lc.g6(),this.lc.f6(),(0,D.Ka)(this),this.WR);this.Na.YV(this.Ao);this.k(this.lc);this.k(this.Na);this.Na.L();var g;if("alta"==this.Tb){f=this.Na.C();
(0,D.La)(this.lc,f.j);this.removeChild(this.Na);var f=new D.Ma(this.e,(0,D.Ka)(this).legendEna,0,0,24,24),d=new D.Ma(this.e,(0,D.Ka)(this).legendOvr,0,0,24,24),e=new D.Ma(this.e,(0,D.Ka)(this).legendDwn,0,0,24,24),h=(0,D.Na)(this.bb,"LEGEND");(0,D.Pa)(this.lc,this.Na,f,d,e,h,"legend");this.lc.Ni();b&&this.lc.Le(D.o,D.o)}else g=this.lc,b=this.Na,g.Ed.k(b),b.P("dvtResizeEvent",g.upa,D.u,g),f=g.Ed.C(),b=f.g+10,f=f.j+10,g.W=f,g.Q=b,g.fb?(g.fb.Zj((0,D.Qa)(g,b,f)),b="col_northwest"==g.wi||"col_southwest"==
g.wi,g.bg&&b&&g.bg.F(g.Q)):(b=new D.Ra(g.e,(0,D.Qa)(g,b,f)),f=g.D.borderAlpha,b.na(g.jv,g.Fj),b.Ma(g.Ap,f),g.fb=b,g.Ha(g.fb,0),g.Ov||(g.bg=D.Sa.V4(g.e,25,g.D,D.u),g.bg.B(g.D.borderAlpha),g.k(g.bg),g.Ij=g.isCollapsed()?D.M.QT(g.e,g.Gj,25,g.D,D.u):D.M.OT(g.e,g.Gj,25,g.D,D.u),g.bg.k(g.Ij),"col_northwest"==g.wi||"col_southwest"==g.wi||(g.bg.O(25),g.bg.Oi(-window.Math.PI)),D.K.R(g.e)&&g.bg.F(g.Q),D.K.da()?g.Ij.P(D.Ta.Rd,g.LD,D.u,g):(g.Ij.P(D.Ua,g.LD,D.u,g),g.Ij.P(D.Va,g.NX,D.u,g),g.Ij.P(D.Wa,g.MX,D.u,
g)))),g.nQ&&(0,D.Xa)(g,D.u),g=this.lc.C(),b=D.K.R(this.e)?5:this.Q-5-g.g-g.x,(0,D.Ya)(this.lc,b,5),g.g+=5;if(this.DR=c)g||(g=this.lc.C()),this.MK=g.g}}};D.E.Pu=function(){D.va.q.Pu.call(this)};
D.E.dl=function(){D.va.q.dl.call(this);var b=new D.H(this.e),c=new D.H(this.e);this.xb.k(b);this.xb.$.k(c);this.Bh(b,c);if(this.Rj){(this.dc=this.xb.dc)&&this.xb.k(this.dc);(0,D.Za)(this);var d=new D.I(0,0,this.Q,this.W);if(!this.wf&&!this.wF)D.ab.isSupported(this.rZ)&&(this.qb=D.ab.VG(this.e,this.rZ,this.xb,d,this.Ts));else{var e=D.r;if(this.IP&&!this.Zs)e=this.Qba;else if(this.Rj&&this.Rj.vf!=this.Hxa&&(e=this.Rj.tq(),!e)){var f=this.Rj.Tg,g;for(g in f)if(f[g].tq()){e=f[g].tq();break}}e&&D.ab.isSupported(e)?
(this.qb=D.ab.bz(this.e,e,this.wF,this.xb,d,this.Ts))&&this.k(this.wF):this.xb.$.removeChild(this.sE)}this.qb&&(this.dc&&this.k(this.dc),this.xa.oc(),this.xa.rs(this),this.qb.zd(this.rp,this),this.qb.play());this.kya=b;this.sE=c;this.Rj&&(this.Hxa=this.Rj.vf);this.wf=D.o}};
D.E.Bh=function(b,c){this.zL();c.k(this.sZ);c.k(this.UJ);this.Br?b.k(this.tv):c.k(this.tv);b.k(this.wt);var d=this.xb.$.pa();this.m4=D.u;for(var e=0;e<this.ye.length;e++){var f=this.ye[e];if(!this.m4&&f instanceof D.bb||!(f instanceof D.bb))f.L(d),!this.m4&&f instanceof D.bb&&(this.m4=D.o,this.Rj=f)}this.Rj&&(d=(0,D.cb)(this),0==d.length&&(d=(0,D.db)(this)),this.e1&&(d=d[0])&&D.Fa.q.Pl.call(this.xa,d),this.xb.vs(D.r),this.xb.Gu(D.r),this.xb.xp=D.o,this.xb.Ej=D.o,!this.IP&&!this.Zs&&this.W0!=D.r?(this.xb.bk(this.W0),
this.xb.cp(this.Hwa,this.Iwa)):this.wR?(0,D.fb)(this):this.xb.Yk(D.r,this.Rj.sC()),(0,D.gb)(this),d=this.xb.To,e=this.Rj.sC(),f=this.xb.vc(),f.g=this.DR?f.g-this.MK:f.g,d=window.Math.min((f.g-2*d)/e.g,(f.j-2*d)/e.j),this.xb.vs(d),this.xb.Gu(d*(this.Zy?this.M1:1)),this.xb.xp=this.Zy,this.xb.Ej=this.GF)};D.hb=function(b){(0,D.gb)(b);b.wR?(0,D.fb)(b):b.W0==D.r&&b.xb.Yk(D.r,b.Rj.sC())};D.va.prototype.g8=(0,D.B)("UF");D.va.prototype.Wz=function(){return new D.ib(this)};
D.kb=function(b,c){var d=new D.jb;d.translate(c.Fb,c.yb);b.Br&&b.tv.qa(d);b.wt.qa(d)};D.va.prototype.rI=function(b){D.va.q.rI.call(this,b);var c=new D.lb;(0,D.mb)(c,"controlPanelBehavior","show"==b.hi()?"initExpanded":"initCollapsed");this.ib(c)};D.va.prototype.Y9=function(b){var c=new D.lb;(0,D.mb)(c,D.DvtCommonLegend.F$,"show"==b.hi());this.ib(c)};
D.ob=function(b,c,d){if(c=c.S){var e=b.xb.$,f=(0,D.nb)(c,e,e.pa);d&&(b.jda=e.pa(),(0,D.N)(c,"typeMatrix",b,b.sva,b.jza,f));d=new D.jb(1,0,0,1,f.Fb,f.yb);b.Br&&(0,D.N)(c,"typeMatrix",b.tv,b.tv.pa,b.tv.qa,d);(0,D.N)(c,"typeMatrix",b.wt,b.wt.pa,b.wt.qa,d)}};
D.va.prototype.Yf=function(b){switch(b.hi()){case "adjustPanConstraints":if(this.GF){var c=b.zy;b=this.xb.To;var d=this.xb.vc();b=new D.I(b,b,d.g-2*b,d.j-2*b);var e=this.Rj.sC(),f=e.x*c,d=e.y*c,g=e.g*c,c=e.j*c;g>b.g?(this.xb.aq=b.x+b.g-(f+g),this.xb.Zp=b.x-f):(e=0,this.DR&&(D.K.R(this.e)?e=this.b1?2*-this.MK:-this.MK:this.b1||(e=this.MK)),f=(b.x+b.g-e)/2-(f+g/2),this.xb.aq=f,this.xb.Zp=f);c>b.j?(this.xb.bq=b.y+b.j-(d+c),this.xb.$p=b.y-d):(b=(b.y+b.j)/2-(d+c/2),this.xb.bq=b,this.xb.$p=b)}break;case "zooming":case "elasticAnimBegin":(0,D.ob)(this,
b,D.o);break;case "zoomed":if(b.zy!=D.r){d=this.xb.$.pa();(0,D.mb)(b,"panX",d.Fb);(0,D.mb)(b,"panY",d.yb);b.S=D.r;D.pb.dispatchEvent(this.Xa,this.ka,this,b);(0,D.kb)(this,d);for(c=0;c<this.ye.length;c++)this.ye[c].Yf(b,d)}break;case "zoomAndCenter":(0,D.qb)(this);break;case "zoomToFitBegin":this.b1=D.o;this.DR&&this.xb.$j(this.Q-this.MK,this.W,D.o);break;case "zoomToFitEnd":this.b1=D.u,this.DR&&this.xb.$j(this.Q,this.W,D.o),D.pb.dispatchEvent(this.Xa,this.ka,this,new D.rb)}};
D.va.prototype.Hs=function(b){var c=b.hi();if("elasticAnimBegin"==c)(0,D.ob)(this,b,D.u);else if("panned"==c&&b.uga!=D.r){var d=this.xb.$.pa();(0,D.mb)(b,"zoom",this.xb.Fc());(0,D.mb)(b,"panX",d.Fb);(0,D.mb)(b,"panY",d.yb);b.S=D.r;D.pb.dispatchEvent(this.Xa,this.ka,this,b);(0,D.kb)(this,d);for(b=0;b<this.ye.length;b++)this.ye[b].Hs(d)}this.lc&&("alta"==this.Tb?"dragPanBegin"===c?this.lc.la(D.u):"dragPanEnd"===c&&this.lc.la(D.o):(d=this.$r(),b=this.lc.fb.nc().clone(),"dragPanBegin"===c?(this.Na.B(d.backgroundDragAlpha),
b.B(d.borderDragAlpha),this.lc.fb.Y(b),this.lc.bg&&this.lc.bg.B(d.borderDragAlpha),this.lc.la(D.u)):"dragPanEnd"===c&&(this.Na.B(1),b.B(d.borderAlpha),this.lc.fb.Y(b),this.lc.bg&&this.lc.bg.B(d.borderAlpha),this.lc.la(D.o))))};
D.va.prototype.Qz=function(b,c){if("none"==this.Jj&&(7==this.wh||!this.Zy&&"alta"==this.Tb))this.qv="hidden";this.xb=D.va.q.Qz.call(this,b,c);if("hidden"!=this.qv&&"none"!=this.Jj){var d=[D.F.jj(this,this.k5),D.F.jj(this,this.WT),D.F.jj(this,this.Q7)],d=new D.sb(this.e,this.Jj,(0,D.Ka)(this),d,this.xb,this.bb,this.Xi,this);(0,D.tb)(this.xb,d)}return this.xa.xb=this.xb};
D.gb=function(b){b.KS=D.o;for(var c=0;c<b.ye.length;c++){var d=b.ye[c].vf;d in b.ZE&&(b.ZF[d]=b.ZE[d][1],b.Hj=d,b.ov=b.ZE[d][0],b.WT())}b.KS=D.u};
D.va.prototype.Q7=function(){(0,D.Za)(this);for(var b=[],c=[],d=this.ye.length-1;-1<d;d--)this.ye[d].vf==this.Rj.vf?this.ye[d].reset(c):this.ye[d].reset(b);for(d=0;d<b.length;d++)if(b[d]){var e=b[d].getParent();e&&e.removeChild(b[d])}for(d=0;d<c.length;d++)c[d]&&c[d].B(1);this.DE=[];b=new D.ub(this.e,0.3);this.xb.Yk(b);b.play();this.km=[];this.dc&&"none"!=this.Jj&&((0,D.vb)(this.dc,D.u),(0,D.wb)(this.dc,D.u))};
D.fb=function(b){var c=b.UJ.C(),d=b.tv.C();if(b.Br){var e=b.xb.$.pa();d.g/=e.Ic;d.j/=e.xe;d.x/=e.Ic;d.y/=e.xe}c=(0,D.xb)(c,d);(0,D.Za)(b);D.K.Kh()&&(b.qb=new D.ub(b.e,0.3));0<c.g&&0<c.j?b.xb.Yk(b.qb,c):b.xb.Yk(b.qb,b.Rj.sC());b.qb&&b.qb.play()};D.va.prototype.BG=function(b){var c=new D.ub(this.e,0.3);this.xb.Yk(c,b);c.play()};
D.qb=function(b){if(b.ov){var c=(0,D.Da)(b,b.Hj).mj(b.ov);if(c&&(c=c.Mb)){for(var c=c.getSelection(),d=0;d<c.length;d++)c[d]=c[d].Ka();if(0<c.length){for(var e=c[0].C(),d=1;d<c.length;d++)e=(0,D.xb)(e,c[d].C());b.BG(e)}}}};D.zb=function(b,c){var d=D.yb.JCa(b.ze,c);return(0,D.Da)(b,d)};D.Ab=function(b,c){var d=D.yb.uka(b.ze,c);return(0,D.Da)(b,d)};D.cb=function(b){var c=[];if(b.Rj)for(var d=0;d<b.ye.length;d++){var e=b.ye[d].Tg,f;for(f in e)c=b.Rj.vf==b.ye[d].vf?c.concat((0,D.Bb)(e[f])):c.concat((0,D.Eb)(e[f]))}return c};
D.db=function(b){var c=[];if(b.Rj)for(var d=0;d<b.ye.length;d++){var e=b.ye[d].Tg;if(b.Rj.vf==b.ye[d].vf||!(b.ye[d]instanceof D.bb))for(var f in e)c=c.concat(e[f].th)}return c};D.va.prototype.jza=function(b){this.jda=b;if(this.Br){for(var c=(0,D.db)(this),d=0;d<c.length;d++)c[d].Yf(b);c=this.wt.Aa();for(d=0;d<c;d++)for(var e=this.wt.ca(d),f=e.Aa(),g=0;g<f;g++){var h=e.ca(g);h instanceof D.Fb&&h.update(b)}}};D.va.prototype.sva=(0,D.C)("jda");
D.va.prototype.WT=function(){(0,D.Za)(this);var b=(0,D.Ab)(this,this.Hj),c=(0,D.Da)(this,this.Hj),d=[];if(b){this.UQ[this.Hj]=this.ov;var e=this.ZF[this.Hj];!this.KS&&"single"==this.Jj&&(this.km.pop(),c.reset(d,e),b.reset(this.xv));for(var f=[],g=0;g<e.length;g++){var h=e[g],k=(0,D.Gb)(c,h);f.push(k[0]);for(var m=0;m<k.length;m++)this.m_[k[m]]=e[g];b.i5(k,d);if(k=c.mj(this.ov)){for(var m=h,p=this.xv,q=0;q<k.kc.length;q++)if(k.kc[q].Zk==m){k.kc[q].MH(D.o);k.km.push(m);p.push(k.kc[q].Ka());if(q=k.kc[q].kh())p.push(q),
(q=q.Kj)&&p.push(q);break}for(q=0;q<k.th.length;q++)if(k.th[q].Zk==m){p.push(k.th[q].Ka());break}}this.km.push(h)}(0,D.Hb)(this,this.xv,d,D.u);(0,D.Ib)(this,b.vf);this.Hj=b.vf;this.ZF[this.Hj]=f}};
D.va.prototype.k5=function(){(0,D.Za)(this);for(var b=(0,D.Da)(this,this.Hj),c=(0,D.zb)(this,this.Hj),d=[],e=[],f=this.ZF[this.Hj],g=0;g<f.length;g++){var h=this.m_[f[g]];e.push(h);if(-1!=D.Jb.Fa(this.km,h)){b.VN((0,D.Gb)(c,h),this.xv);for(var k=c.mj(this.UQ[c.vf]),m=h,p=d,q=0;q<k.kc.length;q++)if(k.kc[q].Zk==m){k.km.splice(D.Jb.Fa(k.km,m),1);k.kc[q].MH(D.u);var t=k.kc[q].Ka();k.sk.k(t);p.push(t);if(q=k.kc[q].kh())q.update(k.OF),p.push(q),p.push(q.Kj);break}for(q=0;q<k.th.length;q++)if(k.th[q].Zk==
m){t=k.th[q].Ka();k.qr.k(t);p.push(t);break}h=D.Jb.Fa(this.km,h);-1!=h&&this.km.splice(h,1)}}(0,D.Hb)(this,this.xv,d,D.o);this.Hj=c.vf;this.ov=this.UQ[this.Hj];this.ZF[this.Hj]=e;(0,D.Ib)(this,this.Hj)};D.Za=function(b){b.qb&&(b.qb.stop(D.o),b.qb=D.r)};
D.Hb=function(b,c,d,e){b.xb.$.pa();if(b.bva&&!b.KS){var f=new D.ub(b.e,0.3);D.K.Kh()||(f=D.r);e?b.xb.Yk(f):(0,D.qb)(b);f&&f.play()}(0,D.Za)(b);b.qb=D.ab.bz(b.e,b.lta,c,d,D.r,0.5);D.K.Kh()||(b.qb=D.r);b.qb?(b.xa.oc(),b.xa.rs(b),b.qb.zd(b.Ypa,b),b.qb.play()):(0,D.Kb)(b)};
D.va.prototype.ib=function(b){var c=b.Ba();if("selection"==c)if(this.ov){this.A3=b.getSelection();for(var c=this.ZF,d=this.Hj,e=this.A3,f=[],g=(0,D.Da)(this,this.Hj).mj(this.ov).kc,h=0;h<e.length;h++)for(var k=0;k<g.length;k++)if(g[k].getId()==e[h]){f.push(g[k].Zk);break}c[d]=f;(0,D.Ib)(this,this.Hj);(0,D.mb)(b,"clientId",this.ov);this.mQ&&!(this.mQ instanceof D.Lb)&&(this.lja=this.mQ)}else(0,D.Ib)(this,D.r),this.lja=D.r;else c==D.Mb.Daa?((0,D.mb)(b,"clientId",this.WQ),this.DE="multiple"==this.Jj?
this.DE.concat(this.A3):this.A3,c=b.$ua,c==D.Mb.soa&&this.k5(),c==D.Mb.JW?this.WT():c==D.Mb.iqa&&this.Q7(),b.Le(this.DE)):("showPopup"==c||"hidePopup"==c)&&(0,D.mb)(b,"clientId",this.WQ);D.pb.dispatchEvent(this.Xa,this.ka,this,b)};D.Ib=function(b,c){if(b.dc&&b.Jj&&"none"!=b.Jj){var d=(0,D.Ab)(b,c),e=(0,D.zb)(b,c);d?(0,D.vb)(b.dc,D.o):(0,D.vb)(b.dc,D.u);e?(0,D.wb)(b.dc,D.o):(0,D.wb)(b.dc,D.u)}};D.va.prototype.V=function(){D.va.q.V.call(this);this.xa&&(this.xa.V(),this.xa=D.r)};
D.va.prototype.rp=function(){this.dc&&this.xb.k(this.dc);this.wF&&(this.removeChild(this.wF),this.wF=D.r);this.qb=D.r;this.xa.$e(this)};D.va.prototype.Ypa=function(){(0,D.Kb)(this);this.qb=D.r;this.xa.$e(this)};D.Kb=function(b){if(0<b.xv.length){for(var c=0;c<b.xv.length;c++){var d=b.xv[c];if(d)if(d instanceof D.Fb)d.reset();else if(d.ju&&d.ju())d.B(0);else{var e=d.getParent();e&&e.removeChild(d)}}b.xv=[]}};
D.va.prototype.TS=function(b){this.$Q("mouseover"==b.pga?"categoryRollOver":"categoryRollOut",b.Y5())};D.va.prototype.$Q=function(b,c){var d=new D.Nb(b,c),e=[],f;for(f in this.$g)for(var g in this.$g[f])e.push(this.$g[f][g]);for(f in this.Tv)for(g in this.Tv[f])e.push(this.Tv[f][g]);f=this.Na.I0;for(var h in f)g=new D.Ob(f[h].Ud(),h),e.push(g);(0,D.Pb)(d,e,0.1)};D.va.prototype.vq=function(){this.bI||(this.bI=new D.Qb(this));return this.bI};D.va.prototype.getAutomation=D.va.prototype.vq;
D.wa=function(){this.Init({fusion:D.bv,skyros:D.cv,alta:D.dv})};D.F.l(D.wa,D.Mg,"DvtThematicMapDefaults");
D.bv={skin:D.r,animationDuration:500,animationOnDisplay:"none",animationOnDrill:"none",animationOnMapChange:"none",controlPanelBehavior:"hidden",drilling:"off",initialZooming:"none",maintainDrill:"off",markerZoomBehavior:"fixed",panning:"none",tooltipDisplay:"auto",zooming:"none",styleDefaults:{areaStyle:"background-color:#B8CDEC;border-color:#FFFFFF;",dataAreaDefaults:{borderColor:"#FFFFFF",drilledInnerColor:"#FFFFFF",drilledOuterColor:"#000000",hoverColor:"#FFFFFF",opacity:1,selectedInnerColor:"#FFFFFF",
selectedOuterColor:"#000000"},dataMarkerDefaults:{borderColor:"#FFFFFF",borderStyle:"solid",borderWidth:"0.5px",color:"#000000",height:8,labelStyle:"font-family:Tahoma;font-size:13pt;color:#000000",opacity:0.4,scaleX:1,scaleY:1,shape:"circle",width:8},labelStyle:"font-family:Tahoma;font-size:11pt;"},legend:{position:"auto",rendered:D.o,layout:{gapRatio:1}},layout:{gapRatio:D.r,legendMaxSize:0.3,legendGap:10},resources:{images:{},translations:{}}};D.cv={styleDefaults:{backgroundColor:"#FFFFFF"}};
D.dv={skin:"alta",styleDefaults:{areaStyle:"background-color:#DDDDDD;border-color:#FFFFFF;",backgroundColor:"#FFFFFF",dataAreaDefaults:{drilledOuterColor:"#0572CE"},dataMarkerDefaults:{color:"rgb(51,51,51)",labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;color:#333333',opacity:1},labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;'}};D.ev={animationOnLayerChange:"none",labelDisplay:"auto",labelType:"short"};
D.fv={animationOnDataChange:"none",selection:"none"};
D.hv=function(b){for(var c=0;c<b.ye.length;c++){var d=b.ye[c].Tg,e;for(e in d){var f=d[e].vk;if(f&&f.QA)return f}}return D.r};D.va.prototype.sj=function(b,c,d){this.Tua=D.u;return(b=(0,D.hv)(this))?b.sj(d):D.u};D.va.prototype.Mk=function(b,c){var d=(0,D.hv)(this);return d?d.Mk(b,c):D.r};

D.av=function(b,c){this.tHa=b;this.IHa=c};D.F.l(D.av,D.bi,"DvtThematicMapDropTarget");
D.Qb=(0,D.B)("N");D.F.l(D.Qb,D.gn,"DvtThematicMapAutomation");D.Qb.prototype.bx=function(b){b=(0,D.Dc)(this.N.xa,b);var c;if(b&&(b instanceof D.Nu||b instanceof D.gv))a:{for(var d=this.N.ye,e=0;e<d.length;e++){var f=d[e].Tg;for(c in f)if(b instanceof D.Nu)for(var g=f[c].kc,h=0;h<g.length;h++){if(g[h]===b){c=(0,D.vv)(c)+":area["+b.getId()+"]";break a}}else if(b instanceof D.gv){g=f[c].th;for(h=0;h<g.length;h++)if(g[h]===b){c=(0,D.vv)(c)+":marker["+b.getId()+"]";break a}}}c=D.r}else c=D.r;return c};
D.Qb.prototype.bs=function(b){var c=b.indexOf(":"),d=b.indexOf("[");b=0<c&&0<d?(b=(0,D.wv)(this,b.substring(0,c),b.substring(c+1,d),b.substring(d+1,b.length-1)))?b.Ka().Ea():D.r:D.r;return b};D.Qb.prototype.getData=function(b,c,d){return(c=(0,D.wv)(this,b,c,d))?(b={},b.color=c.nj(),b.tooltip=c.Fe(),c=c.kh(),b.label=c?c.ne():D.r,b):D.r};(0,D.ta)("DvtThematicMapAutomation.prototype.getData",D.Qb.prototype.getData);
D.wv=function(b,c,d,e){b=b.N.ye;for(var f=0;f<b.length;f++){var g=b[f].Tg,h;for(h in g)if((0,D.vv)(h)==c)if("area"==d)for(var k=g[h].kc,m=0;m<k.length;m++){if(k[m].getId()===e)return k[m]}else if("marker"==d){k=g[h].th;for(m=0;m<k.length;m++)if(k[m].getId()===e)return k[m]}}return D.r};D.vv=function(b){var c=b.lastIndexOf(":");return 0<c?b.substring(c+1):b};
D.tv=function(b,c){this.Init(b,c)};D.F.l(D.tv,D.Ra,"DvtDrillablePath");D.E=D.tv.prototype;D.E.Init=function(b,c){D.tv.q.Init.call(this,b);this.ey=this.by=this.NQ=this.MQ=D.r;this.CR=D.u;this.Zoom=1;this.qe=c};D.E.ju=(0,D.C)("CR");
D.E.MH=function(b){this.CR!=b&&(this.CR=b,this.ju()?(this.by=this.Ci(),this.by.G(D.r),this.by.la(D.u),this.ey=this.Ci(),this.ey.G(D.r),this.ey.la(D.u),b=this.getParent(),b.k(this.ey),b.k(this.by),this.by.Y((0,D.yv)(this,this.MQ,2)),this.ey.Y((0,D.yv)(this,this.NQ,4)),this.la(D.u),this.Ks=D.u):(this.Lh()&&(this.qi(),this.vg.Y((0,D.yv)(this,this.Tq,1),2)),this.ey.getParent().removeChild(this.ey),this.by.getParent().removeChild(this.by),this.la(D.o),this.B(1)))};
D.E.Pb=function(b){this.op!=b&&(b&&(this.Lh()?(this.iI(),this.fl=(0,D.yv)(this,this.fl,2),this.hk=(0,D.yv)(this,this.hk,6)):(this.Wq=(0,D.yv)(this,this.Wq,1),this.eo=(0,D.yv)(this,this.eo,4))),D.tv.q.Pb.call(this,b))};D.E.Bc=function(){this.lb()?(this.iI(),this.fl=(0,D.yv)(this,this.fl,2),this.hk=(0,D.yv)(this,this.hk,6)):this.Tq=(0,D.yv)(this,this.Tq,2);D.tv.q.Bc.call(this)};
D.E.iI=function(){this.fl||(this.fl=this.Tq.clone(),this.fl.ia(2),this.qe&&(this.fl.Yc=D.o));this.hk||(this.hk=this.eo.clone(),this.hk.ia(6),this.qe&&(this.hk.Yc=D.o))};D.E.qc=function(){this.lb()&&(this.Wq=(0,D.yv)(this,this.Wq,1),this.eo=(0,D.yv)(this,this.eo,4));D.tv.q.qc.call(this)};D.E.Mq=function(b,c){D.tv.q.Mq.call(this,b,c);this.qe&&(this.Tq&&(this.Tq.Yc=D.o),this.FO&&(this.FO.Yc=D.o));return this};
D.E.Oq=function(b,c){D.tv.q.Oq.call(this,b,c);this.qe&&(this.Wq&&(this.Wq.Yc=D.o),this.eo&&(this.eo.Yc=D.o));return this};D.E.Hu=function(b,c){D.tv.q.Hu.call(this,b,c);this.qe&&(this.fl&&(this.fl.Yc=D.o),this.hk&&(this.hk.Yc=D.o));return this};D.uv=function(b,c,d){b.MQ=c;b.MQ&&b.qe&&(b.MQ.Yc=D.o);b.NQ=d;b.NQ&&b.qe&&(b.NQ.Yc=D.o)};D.zv=function(b,c,d){if(!b.qe){var e=c.nc();e&&(e=e.clone(),e.ia(d/b.Zoom),c.Y(e))}};D.yv=function(b,c,d){b.qe||(c=c.clone(),c.ia(d/b.Zoom));return c};
D.xv=function(b,c){b.Zoom=c.Ic;b.ju()?((0,D.zv)(b,b.by,2),(0,D.zv)(b,b.ey,4)):b.lb()?b.Lh()?((0,D.zv)(b,b.vg,2),(0,D.zv)(b,b,6)):((0,D.zv)(b,b.vg,1),(0,D.zv)(b,b,4)):b.Lh()?(0,D.zv)(b,b.vg,2):(0,D.zv)(b,b,1)};
D.yb=this.DvtBaseMapManager;D.yb?(D.yb.$q=D.yb._UNPROCESSED_MAPS,D.yb.VD=D.yb._UNPROCESSED_PARENT_UPDATES):D.yb={$q:[[],[],[]],VD:[[],[],[]]};"undefined"!=typeof D.DVT_ADVANCED_CLOSURE&&((0,D.ta)("DvtBaseMapManager",D.yb),D.yb._UNPROCESSED_MAPS=D.yb.$q,D.yb._UNPROCESSED_PARENT_UPDATES=D.yb.VD);D.F.l(D.yb,D.F,"DvtBaseMapManager");D.yb.RD=0;D.yb.NI=1;D.yb.BY=2;D.yb.AY=3;D.yb.cP=4;D.yb.Os="__index";D.yb.Yg={};
D.yb.rka=function(b,c){D.yb.rn();var d=D.yb.Yg[b][c];return d&&(d=d[D.yb.cP])?new D.I(d[0],d[1],d[2],d[3]):D.r};D.yb.lka=function(b,c){D.yb.rn();var d=D.yb.Yg[b][c];return d?d[D.yb.AY]:D.r};D.yb.mka=function(b,c){D.yb.rn();var d=D.yb.Yg[b][c];return d?d[D.yb.RD]:D.r};D.yb.Wka=function(b,c,d){D.yb.rn();b=D.yb.Yg[b][c];var e;b&&(e=b[D.yb.RD]);return e&&e[d]?e[d][1]:D.r};D.yb.xka=function(b,c){D.yb.rn();var d=D.yb.Yg[b];if(d&&(d=d.cities))if(d=d[D.yb.NI][c])return new D.R(d[0],d[1]);return D.r};
D.yb.yka=function(b,c){D.yb.rn();var d=D.yb.Yg[b];if(d&&(d=d.cities))if(d=d[D.yb.RD][c])return d[1];return D.r};D.yb.kka=function(b,c,d){D.yb.rn();var e=D.yb.Yg[b];if(e&&(e=e[c])){if((e=e[D.yb.AY])&&e[d])return(0,D.cl)(e[d][0]).ed();b=D.yb.Yg[b][c][D.yb.NI][d];if(!b)return D.r;b=window.DvtPathUtils.RT(b);return window.DvtPathUtils.C(b).ed()}return D.r};D.yb.uka=function(b,c){D.yb.rn();var d=D.yb.Yg[b][c];return d?D.yb.Yg[b][D.yb.Os][d.__index+1]:D.r};
D.yb.JCa=function(b,c){D.yb.rn();return D.yb.Yg[b][c]?D.yb.Yg[b][D.yb.Os][D.yb.Yg[b][c].__index-1]:D.r};D.yb.nka=function(b,c){D.yb.rn();return D.yb.Yg[b][c][D.yb.NI]};D.yb.KCa=function(b,c,d){D.yb.rn();return D.yb.Yg[b][c][D.yb.NI][d]};D.yb.vka=function(b,c){D.yb.rn();var d=D.yb.uka(b,c);return d&&(d=D.yb.Yg[b][d][D.yb.BY])?d:[]};D.yb.vJa=function(b,c){D.yb.rn();return D.yb.Yg[b][D.yb.Os][c]};
D.yb.EV=function(b,c,d,e,f,g,h,k){var m=D.yb.Yg[b];m||(m={},m[D.yb.Os]=[],D.yb.Yg[b]=m);b=m[c];b||(b={},m[c]=b,h!=D.r&&(m[D.yb.Os][h]=c));b[D.yb.RD]=d;b[D.yb.NI]=e;b[D.yb.BY]=f;b[D.yb.AY]=g;b[D.yb.cP]=k;b[D.yb.Os]=h};(0,D.ta)("DvtBaseMapManager.registerBaseMapLayer",D.yb.EV);D.yb.Wma=function(b,c,d){var e=D.yb.Yg[b];e||(e={},D.yb.Yg[b]=e);b=e[c];b||(b={},e[c]=b);(b=e[c])&&(b[D.yb.RD]=d)};(0,D.ta)("DvtBaseMapManager.registerResourceBundle",D.yb.Wma);
D.yb.wna=function(b,c,d){if(b=D.yb.Yg[b])if(c=b[c])for(var e in d)c[D.yb.RD][e]=d[e]};(0,D.ta)("DvtBaseMapManager.updateResourceBundle",D.yb.wna);D.yb.EEa=function(b,c){D.yb.$q=b;D.yb.VD=c;D.yb.rn()};(0,D.ta)("DvtBaseMapManager.loadUnprocessedMaps",D.yb.EEa);
D.yb.rn=function(){var b,c;if(D.yb.$q){for(b=0;b<D.yb.$q[0].length;b++)c=D.yb.$q[0][b],D.yb.EV(c[0],c[1],c[2],c[3],c[4],c[5],c[6],c[7]);for(b=0;b<D.yb.$q[1].length;b++)c=D.yb.$q[1][b],D.yb.Wma(c[0],c[1],c[2]);for(b=0;b<D.yb.$q[2].length;b++)c=D.yb.$q[2][b],D.yb.wna(c[0],c[1],c[2]);D.yb.$q=D.r}if(D.yb.VD)for(b=0;b<D.yb.VD[0].length;b++){c=D.yb.VD[0][b];var d=c[1],e=c[2],f=D.yb.Yg[c[0]],g;if(f){if(d=f[d]){d[D.yb.BY]=c[3];g=d[D.yb.cP];b=d[D.yb.Os];d=f[D.yb.Os];d.splice(b,0,e);f[e][D.yb.Os]=b;for(b+=
1;b<d.length;b++)(e=f[d[b]])&&e[D.yb.Os]++}(d=f[c[2]])&&(d[D.yb.cP]=g)}}};D.yb.cGa=function(b,c,d,e,f,g){if(0<g){c=1/(window.Math.min(e/c,f/d)*g);if(1>=c)return b;d=[];if(b)for(var h in b)e=b[h],(0,window.isNaN)(e)&&(e=window.DvtPathUtils.RT(b[h])),d[h]=window.DvtPathUtils.dGa(e,c);return d}return b};
D.Ob=function(b,c){this.Init(b,c)};D.F.l(D.Ob,D.F,"DvtThematicMapCategoryWrapper");D.Ob.prototype.Init=function(b,c){this.NA=b;this.dm=c};D.Ob.prototype.Kg=(0,D.C)("dm");D.Ob.prototype.Ge=function(){return[this.NA]};
D.Mb=function(b){this.Init(D.Mb.Daa);this.$ua=b};D.F.l(D.Mb,D.Jc,"DvtMapDrillEvent");D.Mb.Daa="drill";D.Mb.soa=0;D.Mb.JW=1;D.Mb.iqa=2;D.Mb.prototype.Le=(0,D.B)("eg");
D.Yu=function(b,c,d){this.Init("action");this.et=b;this.HL=c;this.ag=d};(0,D.ta)("DvtMapActionEvent",D.Yu);D.F.l(D.Yu,D.Jc,"DvtMapActionEvent");D.Yu.TYPE="action";D.Yu.prototype.jh=(0,D.C)("et");D.Yu.prototype.getClientId=D.Yu.prototype.jh;D.Yu.prototype.p6=(0,D.C)("HL");D.Yu.prototype.getRowKey=D.Yu.prototype.p6;D.Yu.prototype.uw=(0,D.C)("ag");D.Yu.prototype.getAction=D.Yu.prototype.uw;
D.Fb=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.l(D.Fb,D.pc,"DvtMapLabel");D.E=D.Fb.prototype;D.E.Init=function(b,c,d,e,f,g){D.Fb.q.Init.call(this,b,c,0,0);this.qe=g;this.lv=[];this.la(D.u);this.of();this.Ce();this.ct=D.r;this.zo=e;this.PB=f;if(d&&(this.lv.push((0,D.cl)(d[0])),1<d.length)){this.o1=[];for(c=1;c<d.length;c++)e=d[c],this.lv.push((0,D.cl)(e[0])),e=new D.Ze(b,e[1]),(0,D.kc)(e),f=new D.Vd("#000000"),this.qe&&(f.Yc=D.o),e.Y(f),this.o1.push(e)}};
D.E.update=function(b){b=b.Ic;for(var c=-1,d=D.qc.Xj(this),e=D.u,f=0;f<this.lv.length;f++){var g=this.lv[f].g*b;if(d.g<=g){c=f;break}else if(this.getParent()||(e=D.o,this.PB.k(this)),this.C().g<=g){c=f;break}}-1==c&&"on"==this.zo&&(c=this.lv.length-1);this.L_!=c?(-1==c?this.reset():(this.getParent()||this.PB.k(this),d=this.lv[c].ed(),this.Nn(d),this.o1&&(this.PB.removeChild(this.Kj),this.Kj=D.r,0<c?(this.Kj=this.o1[c-1],this.PB.k(this.Kj),e=this.Jc(),e.aa("color","#000000"),this.Ia(e),e=this.lv[c],
f=this.Kj.sb(),g=f.length,e.x>f[g-2]?(this.Ik(),this.Ce(),this.Nn(new D.R(e.x,d.y))):e.y>f[g-1]?(this.Uo(),this.of(),this.Nn(new D.R(d.x,e.y))):e.x+e.g<f[g-2]?(this.Bi(),this.Ce(),this.Nn(new D.R(e.x+e.g,d.y))):e.y+e.j<f[g-1]&&(this.qw(),this.of(),this.Nn(new D.R(d.x,e.y+e.j)))):(this.of(),this.Ce(),e=this.Jc(),e.aa("color",this.nfa),this.Ia(e)))),this.L_=c):-1==c&&e&&this.PB.removeChild(this);-1!=this.L_&&(c=new D.jb,c.translate(b*this.ct.x-this.ct.x,b*this.ct.y-this.ct.y),this.qa(c),this.Kj&&(this.Kj.qa(new D.jb(b,
0,0,b)),this.qe||(c=this.Kj.nc().clone(),c.ia(1/b),this.Kj.Y(c))))};D.E.Nn=function(b){this.ct=b;this.fa(b.x);this.ua(b.y)};D.E.ed=(0,D.C)("ct");D.E.Ia=function(b){D.Fb.q.Ia.call(this,b);this.nfa||(this.nfa=b.v("color"))};D.E.reset=function(){this.PB.removeChild(this);this.L_=-1;this.Kj&&(this.PB.removeChild(this.Kj),this.Kj=D.r)};
D.Tu=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.Tu,D.H,"DvtMapDataObject");D.E=D.Tu.prototype;D.E.Init=function(b,c,d,e,f){D.Tu.q.Init.call(this,b,D.r,e);this.an=[];this.Jb=D.r;this.Ra=d;this.et=e;this.Zk=f;this.HIa=D.r;this.WJ="#000000";this.Zoom=1;this.nR=D.u;this.IQ=c;this.bb=c.N.bb};D.E.getId=(0,D.C)("Ra");D.E.jh=(0,D.C)("et");D.E.Qd=function(b){(this.Jb=b)&&(0,D.Ac)(this.Jb,"img")};D.E.Nn=(0,D.B)("ck");D.E.ed=(0,D.C)("ck");D.E.Ka=(0,D.C)("Jb");D.E.On=(0,D.B)("Yn");D.E.kh=(0,D.C)("Yn");
D.E.Gc=(0,D.B)("J$");D.E.uw=(0,D.C)("ag");D.E.$a=function(b){D.Tu.q.$a.call(this,b);this.Yn&&this.Yn.$a(b)};D.E.Ge=function(){return[this.Jb]};D.E.Kg=(0,D.C)("an");D.E.Fe=(0,D.C)("ay");D.E.nj=(0,D.C)("WJ");D.E.Y7=function(b){this.WJ=b;this.Jb&&this.Jb.ep&&this.Jb.ep(b)};D.E.X7=function(b){this.ay=b;this.Jb&&(b&&this.rc()?(0,D.xc)(this.Jb,"label",b+". "+(0,D.Na)(this.bb,this.lb()?"STATE_SELECTED":"STATE_UNSELECTED")):(0,D.xc)(this.Jb,"label",b))};D.E.rc=function(){return this.Jb.rc()};D.E.lb=function(){return this.Jb.lb()};
D.E.Bc=(0,D.z)();D.E.qc=function(){this.Qf||this.AX()};D.E.AX=(0,D.z)();D.E.i8=(0,D.B)("bd");D.E.xd=(0,D.C)("bd");D.E.sj=function(b){for(var c=this.IQ.jh(),d=0;d<b.length&&b[d]!=c;d++);return c};D.E.mj=(0,D.C)("IQ");D.E.Mk=function(){return this.IQ.Dx(this)};D.E.qC=function(){return this.IQ.Cx()};D.E.lh=function(b){return b.type==D.Ua?this:32==b.keyCode&&b.ctrlKey?this:(0,D.Tn)(this,b,this.cX())};D.E.cX=(0,D.ca)(D.r);
D.E.He=function(){return this.Jb&&this.Jb.getParent()?this.Jb.C():new D.I(0,0,0,0)};D.E.li=function(){this.Qf=D.o;this.Bc()};D.E.pe=function(){this.Qf&&(this.Qf=D.u,this.qc())};D.E.ji=(0,D.C)("Qf");D.E.Yf=function(b){this.Jb.getParent()&&(this.Zoom=b.Ic,this.wN())};D.E.sp=(0,D.z)();D.E.wN=(0,D.z)();D.E.vc=(0,D.ca)(0);
D.Nu=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.Nu,D.Tu,"DvtMapDataArea");D.E=D.Nu.prototype;D.E.Init=function(b,c,d,e,f){D.Nu.q.Init.call(this,b,c,d,e,f);this.Y0=D.u};D.E.Qd=function(b){D.Nu.q.Qd.call(this,b)};D.E.Pb=function(b){b&&!this.Y0&&this.sk.k(this.Jb);this.Jb.Pb(b);this.Fe()&&(0,D.xc)(this.Jb,"label",this.Fe()+". "+(0,D.Na)(this.bb,b?"STATE_SELECTED":"STATE_UNSELECTED"))};D.E.Bc=function(){this.sk.k(this.Jb);this.Jb.Bc();this.Y0=D.o};
D.E.AX=function(){this.lb()?this.sk.k(this.Jb):this.sk.Ha(this.Jb,0);this.Jb.qc();this.Y0=D.u};D.E.ju=function(){return this.Jb.ju()};D.E.MH=function(b){(this.CR=b)?this.sk.k(this.Jb):this.sk.Ha(this.Jb,0);this.Jb.MH(b)};D.E.Yf=function(b){this.Jb.getParent()&&(D.Nu.q.Yf.call(this,b),(0,D.xv)(this.Jb,b),this.ju()||this.sp(b))};D.E.sp=function(b){this.Yn&&this.Yn.update(b)};D.E.cX=function(){return(0,D.cb)(this.mj().N)};
D.gv=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.gv,D.Tu,"DvtMapDataMarker");D.E=D.gv.prototype;D.E.Init=function(b,c,d,e,f){D.gv.q.Init.call(this,b,c,d,e,f);this.GGa=1;this.Qj=0};D.E.Pb=function(b){this.Jb.Pb(b);this.Fe()&&(0,D.xc)(this.Jb,"label",this.Fe()+". "+(0,D.Na)(this.bb,b?"STATE_SELECTED":"STATE_UNSELECTED"))};D.E.Bc=function(){this.Jb.Bc()};D.E.AX=function(){this.Jb.qc()};
D.E.sp=function(){if(this.Yn){this.Yn.of();var b=(this.Jb.ea()+(0,D.he)(this.Jb)/2)*this.Zoom,c=this.Jb.ha()*this.Zoom,d=(0,D.je)(this.Jb),e=this.Jb.Ba();"top"==this.J$?(c-=4,this.Yn.qw()):"bottom"==this.J$?(c+=d,this.Yn.Uo()):(c="triangleUp"==e?c+2*d/3:"triangleDown"==e?c+d/3:c+d/2,this.Yn.Ce());this.Yn.fa(b);this.Yn.ua(c)}};
D.E.wN=function(){var b=this.Jb.getParent(),c=(0,D.je)(this.Jb);(0,D.he)(this.Jb)!=D.r&&(c!=D.r&&b)&&(c=this.Jb.xC(),this.Yn&&this.Jb.xC()?((0,D.Ya)(b,this.ck.x*this.Zoom-this.ck.x,this.ck.y*this.Zoom-this.ck.y),D.K.F8(b)):((0,D.Ya)(this.Jb,this.ck.x*this.Zoom-(this.ck.x*window.Math.cos(c)-this.ck.y*window.Math.sin(c)),this.ck.y*this.Zoom-(this.ck.x*window.Math.sin(c)+this.ck.y*window.Math.cos(c))),D.K.F8(this.Jb)))};D.E.cX=function(){return(0,D.db)(this.mj().N)};D.E.$j=(0,D.B)("Qj");D.E.vc=(0,D.C)("Qj");
D.Uu=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.Uu,D.Tu,"DvtMapDataImage");D.E=D.Uu.prototype;D.E.Init=function(b,c,d,e,f){D.Uu.q.Init.call(this,b,c,d,e,f)};D.E.vV=function(b){b&&(b.width&&b.height)&&(this.Jb.getWidth()||this.Jb.ia(b.width),this.Jb.getHeight()||this.Jb.va(b.height),this.$j(b.width*b.height),this.Jb.fa(this.ck.x-b.width/2),this.Jb.ua(this.ck.y-b.height/2),this.wN())};
D.E.wN=function(){var b=this.Jb.getWidth(),c=this.Jb.getHeight();b!=D.r&&(c!=D.r&&this.Jb.getParent())&&(b=this.Jb.ea()+b/2,c=this.Jb.ha()+c/2,(0,D.Ya)(this.Jb,b*this.Zoom-this.ck.x,c*this.Zoom-this.ck.y))};D.E.$j=(0,D.B)("Qj");D.E.vc=(0,D.C)("Qj");
D.$u=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.l(D.$u,D.Tu,"DvtMapDataComponent");D.E=D.$u.prototype;D.E.Init=function(b,c,d,e,f){D.$u.q.Init.call(this,b,c,d,e,f)};D.E.ia=(0,D.B)("Q");D.E.getWidth=(0,D.C)("Q");D.E.va=(0,D.B)("W");D.E.getHeight=(0,D.C)("W");D.E.fa=(0,D.B)("Za");D.E.ua=(0,D.B)("Ja");D.E.wN=function(){if(this.Jb.getParent()){var b=this.Ja+this.W/2;this.Jb.F(this.Za+(this.Za+this.Q/2)*this.Zoom-this.ck.x);this.Jb.O(this.Ja+b*this.Zoom-this.ck.y)}};
D.Uu.prototype.vc=function(){return this.Q*this.W};
D.Zu=function(b,c,d,e){this.Init(b,c,d,e)};D.F.l(D.Zu,D.H,"DvtMapArea");D.E=D.Zu.prototype;D.E.Init=function(b,c,d,e){D.Zu.q.Init.call(this,b);this.CK=this.$P=D.u;this.uHa=d;this.J=c;this.k(this.J);this.qe=e;if(b=c.nc())this.Vba=b.getWidth();this.J&&(0,D.Ac)(this.J,"img")};D.E.ee=(0,D.C)("Pe");D.E.Vw=(0,D.B)("Pe");D.E.nc=function(){return this.J instanceof D.Zd?this.J.nc():D.r};D.E.Y=function(b){this.J instanceof D.Zd&&this.J.Y(b)};D.E.G=function(b){this.J instanceof D.Zd&&this.J.G(b)};
D.E.Ec=function(){return this.J instanceof D.Zd?this.J.Ec():D.r};D.E.lC=function(){return this.J instanceof D.Ra?this.J.lC():D.r};D.E.Zj=function(b){this.J instanceof D.Ra&&this.J.Zj(b)};D.E.nD=function(b){this.J instanceof D.Ma&&this.J.nD(b)};D.E.contains=function(b,c){var d=this.C();return b>=d.x&&b<=d.x+d.g&&c>=d.y&&c<=d.y+d.j};D.E.Yf=function(b){if(!this.qe&&this.J&&this.Vba){var c=this.J.nc().clone();c.ia(this.Vba/b.Ic);this.J.Y(c)}};
D.Vu=function(b,c){this.Init(b,c)};D.F.l(D.Vu,D.F,"DvtMapLayer");D.E=D.Vu.prototype;D.E.Init=function(b,c){this.N=b;this.vf="cities";this.X8=D.r;this.oI=c;this.Tg={};this.Um=new D.jb};D.E.daa=(0,D.z)();D.E.PO=(0,D.z)();
D.E.t8=function(b,c){this.qb&&(this.cJ=D.o,this.qb.stop(D.o));this.Um=c;this.Dt=this.mj(b.jh());this.Tg[b.jh()]=b;b.L(this.Um);b.Yf(new D.rb("zoomed"),this.Um);if(this.Dt){var d=b.tq(),e=b.Ta();if(D.ab.isSupported(d)){for(var f=new D.I(0,0,this.N.Q,this.N.W),g=(0,D.Wu)(this.Dt),h=0;h<g.length;h++){var k=new D.cd(this.N.e,0,0,this.N.Q,this.N.W);k.G(D.r);g[h].k(k)}for(var m=(0,D.Wu)(b),h=0;h<m.length;h++)k=new D.cd(this.N.e,0,0,this.N.Q,this.N.W),k.G(D.r),m[h].k(k);f=D.ab.bz(this.N.e,d,g,m,f,e);g=new D.I(0,
0,this.N.Q/this.Um.Ic,this.N.W/this.Um.Ic);m=[this.Dt.sk];for(h=0;h<m.length;h++)k=new D.cd(this.N.e,0,0,this.N.Q/this.Um.Ic,this.N.W/this.Um.Ic),k.G(D.r),m[h].k(k);for(var p=[b.sk],h=0;h<p.length;h++)k=new D.cd(this.N.e,0,0,this.N.Q/this.Um.Ic,this.N.W/this.Um.Ic),k.G(D.r),p[h].k(k);h=D.ab.bz(this.N.e,d,m,p,g,e);this.qb=new D.Od(this.N.e,[f,h])}else{d=[this.Dt.sk,this.Dt.qr,this.Dt.KA];for(h=0;h<d.length;h++)d[h].getParent().removeChild(d[h]);this.PO()}if(this.qb){this.oI.rs(this.ka);var q=this;
this.qb.zd(function(){q.rp(b)},this);this.daa();this.qb.play()}}else this.PO(),(0,D.hb)(this.N)};D.E.mj=function(b){return this.Tg?this.Tg[b]:D.r};D.E.jh=(0,D.C)("X8");D.E.L=function(b){this.Um=b;for(var c in this.Tg)this.Tg[c].L(b)};D.E.reset=function(b,c){for(var d in this.Tg)this.Tg[d].reset(b,c)};D.E.Yf=function(b,c){this.Um=c;for(var d in this.Tg)this.Tg[d].Yf(b,c)};D.E.Hs=function(b){this.Um=b;for(var c in this.Tg)this.Tg[c].Hs(b)};
D.E.rp=function(b){if(this.Dt)for(var c=[this.Dt.sk,this.Dt.qr,this.Dt.KA],d=0;d<c.length;d++){var e=c[d].getParent();e&&e.removeChild(c[d])}c=(0,D.Wu)(b);for(d=0;d<c.length;d++)c[d].dp(c[d].Aa()-1);b=[b.sk];for(d=0;d<b.length;d++)b[d].dp(b[d].Aa()-1);this.PO();(0,D.hb)(this.N);this.cJ=D.u;this.qb=D.r;this.oI.$e(this.ka)};
D.bb=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.l(D.bb,D.Vu,"DvtMapAreaLayer");D.E=D.bb.prototype;D.E.Init=function(b,c,d,e,f,g){D.bb.q.Init.call(this,b,g);this.zo=e;this.vf=c;this.X8=d;this.g1=f;this.iJ={};this.jp={};this.Om={};this.pB=this.Qn=D.r;this.eg=[];this.cq={};this.Kr={};this.QS={};this.YN=new D.H(this.N.e);this.xI=new D.H(this.N.e);this.N.sZ.Ha(this.YN,0);this.N.wt.Ha(this.xI,0);this.h0=new D.av(this,this.N.ze)};D.E.HH=(0,D.B)("pZ");D.E.tq=(0,D.C)("pZ");D.E.Mn=(0,D.B)("oZ");
D.E.Ta=(0,D.C)("oZ");D.Ru=function(b,c){b.Qn=c;for(var d in b.Qn)b.cq[d]=D.o,b.Kr[d]=D.o};D.bb.prototype.pU=function(b){return!this.pB?D.r:this.pB[b]};D.Gb=function(b,c){return b.Zd[c]?b.Zd[c].split(","):[]};D.bb.prototype.WG=(0,D.C)("zo");D.iv=function(b,c){b.DK=c;b.fF=D.r;for(var d in b.Om)d!=c&&(b.cq[d]=D.u)};
D.bb.prototype.sC=function(){if(!this.fF)if(this.DK)this.fF=window.DvtPathUtils.C(window.DvtPathUtils.RT(D.yb.KCa(this.N.ze,this.vf,this.DK)));else if("world"!=this.N.ze&&"worldRegions"!=this.N.ze&&(this.fF=D.yb.rka(this.N.ze,this.vf)),!this.fF){var b=(0,D.xb)(this.YN.C(),this.N.UJ.C());0<b.g&&0<b.j&&(this.fF=b)}return this.fF};
D.jv=function(b,c,d){var e=b.Om[c];if(e&&((d||!b.jp[c])&&b.vna(c),b.jp[c]||(d=new D.Zu(b.N.e,e,c,b.N.qe),b.jp[c]=d,b.oI.ma(e,d),d.Vw(b.Qn&&b.Qn[c]?b.Qn[c][1]:D.r)),b.Kr[c]&&(d=b.iJ[c],!d&&("off"!=b.zo&&b.Qn)&&(d="short"==b.g1?b.Qn[c][0]:b.Qn[c][1]))))b.pB&&b.pB[c]?d=new D.Fb(b.N.e,d,b.pB[c],b.zo,b.xI,b.N.qe):(e=(0,D.Yf)(b.N.e,e),d=new D.Fb(b.N.e,d,[[e.x,e.y,e.g,e.j]],b.zo,b.xI,b.N.qe)),b.iJ[c]=d,b.TR&&d.Ia(b.TR)};
D.kv=function(b,c,d){if(b.Om[c]){b.YN.k(b.jp[c]);var e=b.iJ[c];e&&(b.Kr[c]?e.update(b.Um):e.reset(),b.QS[c]=b.Kr[c]);d&&(d.push(b.jp[c]),e&&(d.push(e),d.push(e.Kj)))}};D.bb.prototype.vna=function(b){if(!this.qha||this.kca){this.kca=D.u;var c;this.qha=(c="world"==this.N.ze||"worldRegions"==this.N.ze?D.yb.rka(this.N.ze,this.vf):this.sC())?D.yb.cGa(D.yb.nka(this.N.ze,this.vf),c.g,c.j,this.N.Q,this.N.W,this.N.Zy?this.N.M1:1):D.yb.nka(this.N.ze,this.vf)}c=this.qha[b];this.Om[b]&&c?this.Om[b].Zj(c):delete this.Om[b]};
D.lv=function(b){for(var c in b.Qn)b.cq[c]=D.o,b.Kr[c]=D.o};D.E=D.bb.prototype;D.E.t8=function(b,c,d){D.bb.q.t8.call(this,b,c,d);if(d==this.vf)for(var e in this.Om)(0,D.jv)(this,e,D.o),this.cq[e]&&(0,D.kv)(this,e)};D.E.L=function(b){this.kca=D.o;for(var c in this.Om)(0,D.jv)(this,c,D.o),this.cq[c]&&(0,D.kv)(this,c);D.bb.q.L.call(this,b)};D.E.daa=function(){for(var b in this.cq)this.cq[b]||((0,D.jv)(this,b,D.u),(0,D.kv)(this,b))};
D.E.PO=function(){for(var b in this.cq)if(!this.cq[b]){this.YN.removeChild(this.jp[b]);var c=this.iJ[b];c&&(this.QS[b]=D.u,this.xI.removeChild(c),(c=c.Kj)&&this.xI.removeChild(c))}};D.E.i5=function(b,c){for(var d=0;d<b.length;d++)(0,D.jv)(this,b[d],D.u),this.cq[b[d]]&&(0,D.kv)(this,b[d],c);for(var e in this.Tg)this.Tg[e].i5(b,c,this.Um);this.eg=this.eg.concat(b)};
D.E.VN=function(b,c){for(var d in this.Tg)this.Tg[d].VN(b,c);d=(0,D.Ab)(this.N,this.vf);for(var e=0;e<b.length;e++){var f=b[e];if(this.jp[f]){var g=D.Jb.Fa(this.eg,f);-1!==g&&(this.eg.splice(g,1),c.push(this.jp[f]))}d&&d.VN((0,D.Gb)(this,f),c)}};D.E.reset=function(b,c){D.bb.q.reset.call(this,b,c);"none"!=this.N.Jj&&(this.VN(this.eg,b),this.eg=[])};D.E.Yf=function(b,c){D.bb.q.Yf.call(this,b,c);if(!this.N.qe)for(var d in this.jp)this.jp[d].Yf(c);for(d in this.QS)if(this.QS[d]){var e=this.iJ[d];e&&e.update(c)}};
D.Pu=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.l(D.Pu,D.bb,"DvtMapCustomAreaLayer");D.Pu.prototype.Init=function(b,c,d,e,f,g){D.Pu.q.Init.call(this,b,c,d,e,f,g)};D.Pu.prototype.vna=(0,D.z)();D.Pu.prototype.sC=function(){return new D.I(0,0,this.Ywa,this.Xwa)};D.Qu=function(b){var c=b.N.Q,d=b.N.W;b=b.rta;for(var e=0;e<b.length;e++){var f=b[e],g=f.source,h=f.width,f=f.height;if(g&&-1<g.search(".svg")||h>=c&&f>=d||e==b.length-1)return g}};
D.Su=function(b,c){var d=D.r,e=D.K.R(b.N.e);if(c&&0<c.length){var d=c[0].width,f=c[0].height;b.Ywa=d;b.Xwa=f;for(var g=[],h=0;h<c.length;h++)e&&"rtl"==c[h].dir?g.push(c[h]):!e&&"ltr"==c[h].dir&&g.push(c[h]);b.rta=0<g.length?g:c;b.sR=(0,D.Qu)(b);d=new D.Ma(b.N.e,b.sR,0,0,d,f)}d&&((0,D.Ru)(b,{image:[D.r,D.r]}),b.Om={image:d})};D.Pu.prototype.Yf=function(b,c){D.Pu.q.Yf.call(this,b,c);if(this.jp.image){var d=(0,D.Qu)(this);d!=this.sR&&(this.sR=d,this.jp[window.areaName].nD(this.sR))}};
D.pv=function(b,c,d,e){this.Init(b,c,d,e)};D.F.l(D.pv,D.F,"DvtMapDataLayer");D.pv.prototype.Init=function(b,c,d,e){this.N=b;this.et=d;this.kc=[];this.th=[];this.xa=e;this.vk=new D.ci(b.e);(0,D.hm)(this.xa,this.vk);this.sk=new D.H(this.N.e);this.qr=new D.H(this.N.e);this.KA=new D.H(this.N.e);this.N.UJ.Ha(this.sk,0);this.N.tv.Ha(this.qr,0);this.N.wt.Ha(this.KA,0);this.nha=c;this.eg=[];this.km=[]};D.Wu=function(b){var c=[b.KA];b.N.Br&&c.push(b.qr);return c};
D.Bb=function(b){for(var c=[],d=0;d<b.kc.length;d++)b.kc[d].ju()||c.push(b.kc[d]);return c};D.Eb=function(b){for(var c=[],d=0;d<b.kc.length;d++)for(var e=0;e<b.eg.length;e++)b.kc[d].Zk==b.eg[e]&&(b.kc[d].ju()||c.push(b.kc[d]));return c};D.rv=function(b,c){b.kc.push(c);b.xa.ma(c.Ka(),c);c.sk=b.sk};D.E=D.pv.prototype;D.E.jh=(0,D.C)("et");D.E.HH=(0,D.B)("pZ");D.E.tq=(0,D.C)("pZ");D.E.Mn=(0,D.B)("oZ");D.E.Ta=(0,D.C)("oZ");D.E.ys=function(b){if(this.Or=b)this.Mb=new D.In(this.Or),this.xa.Kz(this.et,this.Mb)};
D.E.rc=function(){return this.Or!=D.r};D.Av=function(b,c){var d;d=b.kc[c];var e=d.Ka(),f=b.nha.Om[d.Zk];f?(e.Zj(f.lC()),d=D.o):(d=b.kc.indexOf(d),-1!==d&&b.kc.splice(d,1),d=D.u);if(d){e=b.kc[c].Ka();b.sk.k(e);if(d=b.kc[c].kh())0<d.lv.length||(e=e.C(),d.lv.push(e)),d.update(b.OF);return D.o}return D.u};D.E=D.pv.prototype;
D.E.L=function(b){this.gca=D.o;this.OF=b;var c={};this.th.sort(function(b,c){return b.vc()<c.vc()?1:b.vc()>c.vc()?-1:0});for(var d=0;d<this.th.length;d++){var e=this.th[d],f=e.Ka(),g=e.kh();if(g){if(f.xC()){var h=new D.H(f.e);this.qr.k(h);h.k(f);h.k(g)}else this.qr.k(f),f.k(g);e.sp(b)}else this.qr.k(f);if(e instanceof D.$u)if(g=e.Vwa)f.L(window.JSON.parse(g),e.getWidth(),e.getHeight());else continue;(e=e.Zk)&&(c[e]=D.o)}for(d=0;d<this.kc.length;d++)c[this.kc[d].Zk]&&this.kc[d].On(D.r),(0,D.Av)(this,
d)||d--;this.tR&&this.LF()};D.E.i5=function(b,c,d){this.OF=d;for(var e=[],f=0;f<b.length;f++)for(var g=0;g<this.kc.length;g++)if(this.kc[g].Zk==b[f]){e.push(this.kc[g].Zk);(0,D.Av)(this,g);var h=this.kc[g].Ka();c.push(h);(0,D.xv)(h,d);if(g=this.kc[g].kh())c.push(g),(g=g.Kj)&&c.push(g);break}for(g=0;g<this.th.length;g++)for(f=0;f<b.length;f++)d=this.th[g].Zk,h=this.th[g].Ka(),d!=D.r?d==b[f]&&(this.qr.k(h),c.push(h)):(this.qr.k(h),c.push(h));this.eg=this.eg.concat(e)};
D.E.VN=function(b,c){for(var d=0;d<b.length;d++)for(var e=0;e<this.kc.length;e++)if(this.kc[e].Zk==b[d]){this.kc[e].ju()&&this.kc[e].MH(D.u);this.kc[e].lb()&&this.Mb.yN(this.kc[e]);var f=D.Jb.Fa(this.eg,b[d]);if(-1<f&&(this.eg.splice(f,1),c.push(this.kc[e].Ka()),e=this.kc[e].kh()))c.push(e),c.push(e.Kj);break}};
D.E.reset=function(b,c){if(this.Mb)for(var d=this.Mb.getSelection(),e=0;e<d.length;e++)(!c||c&&-1==D.Jb.Fa(c,d[e].Zk))&&this.Mb.yN(d[e]);if("none"!=this.N.Jj)for(d=0;d<this.km.length;d++){for(e=0;e<this.kc.length;e++)if(this.kc[e].Zk==this.km[d]){this.kc[e].MH(D.u);var f=this.kc[e].Ka();this.sk.k(f);b.push(f);if(e=this.kc[e].kh())e.update(this.OF),b.push(e),b.push(e.Kj);break}for(e=0;e<this.th.length;e++)if(this.th[e].Zk==this.km[d]){f=this.th[e].Ka();this.qr.k(f);b.push(f);break}}this.km=[]};
D.E.Yf=function(b,c){this.OF=c;var d=c.Ic,e=b.hi();if(this.gca&&"zoomed"==e){this.gca=D.u;for(e=0;e<this.kc.length;e++){var f=this.kc[e].Ka(),g=f.Hha;if(g){var h=new D.zc;g.yd(h);h.qa(new D.jb(1/d,D.r,D.r,1/d));f.G(h)}}}e=this.kc;for(d=0;d<e.length;d++)e[d].Yf(c);if(this.N.Br){e=this.th;for(d=0;d<e.length;d++)e[d].Yf(c)}};D.E.Hs=(0,D.B)("OF");D.E.LF=function(){this.Mb&&((0,D.Kn)(this.Mb,this.tR,this.th.concat(this.kc)),this.tR=D.r)};
D.E.Dx=function(b){if(this.Mb){b.lb()||(this.Mb.Li(b,D.u),this.xa.Bl(b));b=[];for(var c=this.Mb.getSelection(),d=0;d<c.length;d++)b.push(c[d].getId());return b}return D.r};D.E.Cx=function(){for(var b=[],c=this.Mb.getSelection(),d=0;d<c.length;d++)b.push(c[d].Ka());return b};
D.Ga=function(b,c){this.Init(b,c)};D.F.l(D.Ga,D.Mu,"DvtThematicMapKeyboardHandler");D.E=D.Ga.prototype;D.E.Init=function(b,c){D.Ga.q.Init(b,c);this.N=b};D.E.pH=function(b){return this.Yj(b)&&!b.ctrlKey};
D.E.qs=function(b){var c=b.keyCode;if(221==c){var c=(0,D.im)(this.Ga),d=(0,D.db)(this.N);c instanceof D.Nu&&0<d.length&&(c=(0,D.Tn)(c,b,d));this.Ga.Pl(c);(0,D.Ou)(this.Ga,c)}else 219==c?(c=(0,D.im)(this.Ga),d=(0,D.cb)(this.N),!(c instanceof D.Nu)&&0<d.length&&(c=(0,D.Tn)(c,b,d)),this.Ga.Pl(c),(0,D.Ou)(this.Ga,c)):(c=D.Ga.q.qs.call(this,b),this.Yj(b)&&!b.ctrlKey&&(0,D.Ou)(this.Ga,c));return c};D.E.KC=function(b){return 32==b.keyCode&&b.ctrlKey};
D.E.Yj=function(b){var c=D.Ga.q.Yj.call(this,b);if(!c&&(b=b.keyCode,219==b||221==b))c=D.o;return c};
D.Fa=function(b,c,d){this.Init(b,c,d)};D.F.l(D.Fa,D.Bc,"DvtThematicMapEventManager");D.E=D.Fa.prototype;D.E.Init=function(b,c,d){D.Fa.q.Init.call(this,b,c,d);this.gw={};this.N=d;this.Xs=D.u};D.E.rf=function(b){if(b&&b.mj)return this.gw[b.mj().jh()]};D.E.Kz=function(b,c){this.gw[b]=c};D.E.OV=(0,D.B)("Jj");D.E.yN=function(b,c){var d=this.gw[b];d&&d.yN(c)};D.E.oM=function(b){(b=this.gw[b])&&b.oM()};
D.E.ao=function(b){var c=(0,D.Dc)(this,b.target);c&&(c.xd&&c.mj)&&(this.N.WQ=c.mj().jh());D.Fa.q.ao.call(this,b)};D.E.bl=function(b){this.Xs=D.u;D.Fa.q.bl.call(this,b)};D.E.Sm=function(b){this.Xs=D.o;D.Fa.q.Sm.call(this,b)};D.E.Vg=function(b){if(!this.Xs){var c=(0,D.Dc)(this,b.target);(0,D.Ou)(this,c);if(!c||!c.rc||!c.rc())for(var d in this.gw)if(this.gw[d].Li(D.r,b.ctrlKey)){var e=new D.rm([]);(0,D.mb)(e,"clientId",d);this.Xa.call(this.ka,e)}D.Fa.q.Vg.call(this,b);this.iy(c)}};
D.E.iy=function(b){b instanceof D.Tu&&(b.nR?(0,D.Xu)(this,b):b.xd()&&(this.N.WQ=b.mj().jh()))};D.Xu=function(b,c){var d=new D.Yu(c.jh(),c.getId(),c.ag);(0,D.mb)(d,"clientId",c.mj().jh());b.oc();b.Xa.call(b.ka,d)};D.Ou=function(b,c){var d=D.r,e=D.r,f=D.r;c&&(c instanceof D.Tu?f=c.Ka():c instanceof D.Zu&&(f=c),c.mj&&(e=c.mj(),d=e.jh(),e=e.nha.vf));var g=b.N;g.Hj=e;g.ov=d;g.mQ=f};D.E=D.Fa.prototype;
D.E.$n=function(b){D.Fa.q.$n.call(this,b);b=(0,D.Dc)(this,b.target);this.rf(b)&&(this.Jj&&"none"!=this.Jj)&&(b=new D.Mb(D.Mb.JW),this.Xa.call(this.ka,b))};
D.E.Vl=function(b){var c=D.o,d=b.keyCode;if((48==d||96==d)&&b.ctrlKey&&b.shiftKey)this.N.Q7(),b.preventDefault();else if(220==d)(d=this.N.lc)&&(d instanceof D.Ja?(0,D.Kd)(d,!d.isCollapsed()):d instanceof D.Ia&&d.Le(!d.nb())),b.preventDefault();else if(13==d)d=(0,D.im)(this),d instanceof D.Tu&&d.nR?(0,D.Xu)(this,d):(b.shiftKey?this.N.k5():this.N.WT(),b.preventDefault());else if(32==d&&b.ctrlKey)d=(0,D.im)(this),(0,D.Ou)(this,d),(0,D.vm)(this,d,D.o),b.preventDefault();else if((48==d||96==d)&&b.ctrlKey){var e=
(0,D.im)(this);b.altKey?(d=this.N,e=e.Ka(),e||(e=d.lja),e||(e=d.mQ),d.BG(e.C())):(0,D.qb)(this.N);b.preventDefault()}else c=D.Fa.q.Vl.call(this,b);return c};D.E.Ns=function(b){var c=(0,D.Dc)(this,b.target);(0,D.Ou)(this,c);if(!c||c.MJa)for(var d in this.gw)if(this.gw[d].Li(D.r,b.ctrlKey)){for(var e=this.gw[d].getSelection(),f=[],g=0;g<e.length;g++)f.push(e[g].getId());e=new D.rm(f);this.Xa.call(this.ka,e)}D.Fa.q.Ns.call(this,b);this.iy(c)};
D.E.EO=function(b){if((b=(0,D.Dc)(this,b.target))&&b.xd&&b.mj)this.N.WQ=b.mj().jh()};D.E.$z=function(b){var c=(0,D.Dc)(this,b.target);c&&(this.rf(c)&&this.Jj&&"none"!=this.Jj)&&((0,D.vm)(this,c,b.ctrlKey),b=new D.Mb(D.Mb.JW),this.Xa.call(this.ka,b))};
D.ib=function(b){this.Init(b)};D.F.l(D.ib,D.F,"DvtThematicMapParser");D.mv="inlineStyle";D.nv="animationOnMapChange";D.nv="animationOnMapChange";D.mv="inlineStyle";D.E=D.ib.prototype;D.E.Init=function(b){this.N=b;this.nda={};this.uP=this.wP=this.vP=this.Vs=D.r;this.dfa=D.K.da()};
D.E.cV=function(b){b=b.pb();for(var c,d,e=0;e<b.length;e++)if(c=b[e],d=c.getName(),"mapProperties"==d)this.aY(c);else if("customLayer"==d)this.SGa(c);else if("layers"==d)this.EI(c);else if("legend"==d)this.OO(c);else if("childResources"==d){c=c.pb();for(d=0;d<c.length;d++){var f=c[d].getTextContent();f&&(0,D.Wm)(window.JSON.parse(f))}}};
D.E.aY=function(b){var c;if(c=b.o("source"))this.Nv=D.o;if(c=b.o("baseMapName")){var d=this.N;c=this.Nv?"$"+c:c;d.IP=d.ze&&d.ze!=c;d.ze=c}if(c=b.o("animationOnDisplay"))this.N.rZ=c;if(c=b.o(D.nv))this.N.Qba=c;(c=b.o("animationDuration"))&&this.N.Mn(c);if(c=b.o("displayTooltips"))this.N.b0=c;if(c=b.o("dropTargetStyle"))this.qta=new D.P(c);if(c=b.o("controlPanelBehavior"))this.N.qv=c;(c=b.o("featuresOff"))&&this.N.Hz(c);if(c=b.o("centerX"))this.N.Hwa=(0,window.parseFloat)(c);if(c=b.o("centerY"))this.N.Iwa=
(0,window.parseFloat)(c);if(c=b.o("curZoom"))this.N.W0=(0,window.parseFloat)(c);if((c=b.o("animationOnDrill"))&&"alphaFade"==c)this.N.lta=c;(c=b.o("drillMode"))&&this.N.OV(c);if(c=b.o("drillZoomToFit"))this.N.bva="true"==c;c=b.o("initialZooming");"auto"==c&&(this.N.wR=D.o);c=b.o("zooming");"none"==c&&(this.N.Zy=D.u);c=b.o("panning");"none"==c&&(this.N.GF=D.u);c=(0,window.parseFloat)(b.o("maxZoom"));(0,window.isNaN)(c)||(this.N.M1=c);if(c=b.o("markerZoomBehavior"))this.N.Br="fixed"==c;(0,D.ov)(this.N,
b);b=b.pb();for(var e,d=0;d<b.length;d++)if(c=b[d],e=c.getName(),"mapHierarchy"==e){c=c.pb();e=this.N.ze;for(var f=D.n,g=D.n,h=D.n,k=D.n,g=D.n,m=0;m<c.length;m++){var p=c[m];if("pointLayer"!=p.getName()){var f=p.o("layerName"),g=p.o("labelDisplay"),h=p.o("clientId"),k=p.o("labelType"),q=p.o("areaStyle");q&&this.Vs.zb(new D.P(q));(q=p.o("labelStyle"))&&this.Vs.zb(new D.P(q));this.Nv?g=new D.Pu(this.N,f,h,g,k,this.N.xa):(g=new D.bb(this.N,f,h,g,k,this.N.xa),q=D.yb.mka(e,f),h=this.F_(q),g.Om=h,(0,D.Ru)(g,
q),q=D.yb.lka(e,f),g.pB=q,f=D.yb.vka(this.N.ze,f),g.Zd=f,g.vP=this.vP,g.wP=this.wP,g.uP=this.uP);g.TR=this.Vs;g.UHa=this.qta;if(q=p.o("animationOnLayerChange")){(p=p.o("animationDuration"))&&(p=(0,window.parseFloat)(p));if(!p||(0,window.isNaN)(p))p=1;g.HH(q);g.Mn(p)}g&&this.N.ye.push(g)}}}else if("regionLayer"==e){if(e=c.o(D.mv))this.Vs=new D.P(e);if(e=c.o("hoverStyle"))this.vP=new D.P(e);if(e=c.o("selectStyle"))this.wP=new D.P(e);if(e=c.o("disclosedStyle"))this.uP=new D.P(e)}else"markerStyle"==e?
(c=new D.P(c.o(D.mv)),this.N.ega=c):"basemap"==e&&this.N.ze=="$"+c.o("id")&&this.SX(c)};
D.E.EI=function(b,c,d){var e=b.getElementsByTagName("layer");b=b.getElementsByTagName("legend");c&&(b&&b[0])&&this.OO(b[0]);for(b=0;b<e.length;b++){var f=e[b].o("clientId"),g=e[b].o("id"),h=(0,D.Da)(this.N,g);h?h instanceof D.bb&&(0,D.lv)(h):(h=e[b].o("showWith"))?h=(0,D.Da)(this.N,h):(h=new D.Vu(this.N,this.N.xa),this.N.ye.push(h));var f=new D.pv(this.N,h,f,this.N.xa),k=e[b].o("selectionMode");"single"==k?f.ys("s"):"multiple"==k&&f.ys("m");if(k=e[b].o("animationDataChange")){var m=e[b].o("animationDuration");
m&&(m=(0,window.parseFloat)(m));if(!m||(0,window.isNaN)(m))m=1;f.HH(k);f.Mn(m)}k=D.r;h instanceof D.bb&&(k=e[b].o("isolatedRowKey"));for(var m=[],p=[],q=this.P2(e[b].getElementsByTagName("styles")),t=e[b].getElementsByTagName("row"),v=this.O2(e[b],q),w=0;w<t.length;w++){var A=t[w].o("styleId"),D$;a:{var J=h,G=f;D$=g;var L=t[w],O=q[A],T=m,Q=p,V=k,aa=this.N.e,oa=L.o("rowKey"),qa=L.o("clientId"),A=L.o("id"),ra=D.n,$a=O.getName();if("colorStyles"==$a){if(V){if(V!=oa){D$=D.r;break a}this.DK=A}J.cq[A]=
D.u;ra=new D.Nu(aa,G,oa,qa,A);this.K2(aa,A,J,L,ra)}else if("graduatedSymbol"==$a)ra=new D.gv(aa,G,oa,qa,A),this.L2(aa,O,D$,L,ra);else if("image"==$a){var ra=new D.Uu(aa,G,oa,qa,A),O=aa,Oa=D$,eb=L,V=ra,qa=eb.o("url"),Cb=D.r;if(Oa=(0,D.qv)(this,Oa,eb,"cities"!=Oa)){Cb=new D.Ma(O,qa);V.Nn(Oa);V.Qd(Cb);var Db=D.n,Cd=D.n;if(eb=eb.o(D.mv))eb=new D.P(eb),(Db=eb.v("width").substring(0,eb.v("width").indexOf("px")))&&Cb.ia(Db),(Cd=eb.v("height").substring(0,eb.v("height").indexOf("px")))&&Cb.va(Cd),Db!=D.r&&
Cd!=D.r&&(Cb.fa(Oa.x-Db/2),Cb.ua(Oa.y-Cd/2),V.$j(Db*Cd));(!Db||!Cd)&&D.Qd.tj(O,qa,D.F.jj(V,V.vV))}}else if(ra=new D.$u(aa,G,oa,qa,A),Cb=aa,V=L,O=ra,Oa=$a,qa=(0,D.qv)(this,D$,V,"cities"!=D$)){"statusMeterGauge"==Oa?window.gauge=(0,D.qp)(Cb,D.r,D.r):"ledGauge"==Oa?window.gauge=(0,D.mp)(Cb,D.r,D.r):"dialGauge"==Oa?window.gauge=(0,D.yp)(Cb,D.r,D.r):"ratingGauge"==Oa&&(window.gauge=(0,D.Cp)(Cb,D.r,D.r));O.Nn(qa);O.Qd(window.gauge);Oa=Cb=D.n;if(Cb=V.o(D.mv))Oa=new D.P(Cb),Cb=Oa.width?(0,window.parseInt)(Oa.width.substring(0,
Oa.width.indexOf("px"))):50,O.ia(Cb),Oa=Oa.height?(0,window.parseInt)(Oa.height.substring(0,Oa.height.indexOf("px"))):50,O.va(Oa),O.fa(qa.x-Cb/2),O.ua(qa.y-Oa/2);if(V=V.o("json"))O.Vwa=V}if(O=ra.Ka()){if(V=(0,window.parseInt)(L.o("rotation")))V=V*window.Math.PI/180,O.Oi(V),qa=ra.ed(),(0,D.Ya)(O,qa.x-(qa.x*window.Math.cos(V)-qa.y*window.Math.sin(V)),qa.y-(qa.x*window.Math.sin(V)+qa.y*window.Math.cos(V)));A&&J instanceof D.bb&&(J.Kr[A]=D.u);V="true"==L.o("hasAction");if(ra.nR=V)V=L.o("action"),ra.ag=
V;if(V=L.o("destination"))qa=[],qa.destination=V,qa.targetFrame="_blank",qa.focusable=D.o,(0,D.Gf)(O,qa);"true"==L.o("selected")&&T.push(oa);"true"==L.o("drilled")&&(Q.push(L.o("id")),this.N.DE.push(oa));T=L.o("label");Q="off";T?Q="on":"colorStyles"==$a&&(Q=J.WG());!T&&(A&&"off"!=Q)&&(T="long"==J.g1?J.Qn[A][1]:J.Qn[A][0]);if(T){oa=D.n;J.pU&&(oa=J.pU(A));var Xc=D.n,Xc=oa?new D.Fb(aa,T,oa,Q,G.KA,this.N.qe):"colorStyles"!=$a?new D.pc(aa,T,0,0):new D.Fb(aa,T,D.r,Q,G.KA,this.N.qe);(G=L.o("labelPosition"))&&
ra.Gc(G);G=new D.P;"colorStyles"==$a?G.zb(J.TR):"graduatedSymbol"==$a&&G.zb(this.N.ega);(J=L.o("labelStyle"))&&G.zb(new D.P(J));Xc instanceof D.Fb&&(G.v("color")||G.aa("color",D.S.Cl(ra.nj())));Xc.Ia(G)}ra.On(Xc);J=this.N.b0;"none"!=J&&(L=L.o("shortDesc"),"auto"==J&&(J=D.n,A&&(J="cities"==D$||this.Nv?D.yb.yka(this.N.ze,A):D.yb.Wka(this.N.ze,D$,A)),J&&(L=L?J+": "+L:J)),L&&ra.X7(L));D$=ra}else D$=D.r}D$&&(A=D$.Ka(),A.ug&&A.ug(f.rc()&&!(D$ instanceof D.Uu)),0<v.length&&D$.i8(v),D$ instanceof D.Nu?(0,D.rv)(f,
D$):(A=f,A.th.push(D$),A.xa.ma(D$.Ka(),D$)))}k&&this.DK&&(f.Qwa=k,(0,D.iv)(h,this.DK));f.rc()&&0<m.length&&(f.tR=m);0<p.length&&(this.N.ZE[h.vf]=[f.jh(),p]);c||h.mj(f.jh())?h.t8(f,c,d):h.Tg[f.jh()]=f}};D.E.OO=function(b){this.N.Ao=b};D.E.SX=function(b){b=b.pb();for(var c,d,e=0;e<b.length;e++)c=b[e],d=c.getName(),"layer"==d?this.I2(c):"points"==d&&this.J2(c)};
D.E.I2=function(b){var c=b.pb();b=b.o("id");for(var d,e,f=[],g=0;g<c.length;g++)if(d=c[g],e=d.getName(),"image"==e){e={};e.source=d.o("source");e.width=d.o("width");e.height=d.o("height");var h=d.o("bidi");d=d.o("dir");e.dir="true"==h||"rtl"==d?"rtl":"ltr";f.push(e)}(0,D.Su)((0,D.Da)(this.N,b),f)};
D.E.J2=function(b){b=b.pb();for(var c,d,e={},f={},g=0;g<b.length;g++)c=b[g],d=c.getName(),"point"==d&&(e[c.o("name")]=[c.o("x"),c.o("y")],f[c.o("name")]=[D.r,c.o("longLabel")]);D.yb.EV(this.N.ze,"cities",f,e,D.r,D.r,1)};D.E.F_=function(b){var c={},d=this.N.e,e;for(e in b)c[e]=new D.Ra(d),(0,D.sv)(this,"colorStyles",this.Vs,c[e]);return c};D.E.P2=function(b){var c={};if(b&&0<b.length){b=b[0].pb();for(var d=0;d<b.length;d++){var e=b[d].o("id");c[e]=b[d]}}return c};
D.E.O2=function(b,c){for(var d=b.getElementsByTagName("spb"),e=[],f=0;f<d.length;f++){var g=d[f].o("alignId"),h=(0,D.Bg)(d[f]),k;for(k in c)if(g==k){h=new D.Ag(h.kz(),h.Jh(),D.r,h.iC());break}e.push(h)}return e};D.qv=function(b,c,d,e){b=b.N.ze;var f=d.o("id");if(f)return e?D.yb.kka(b,c,f):D.yb.xka(b,f);c=(0,window.parseFloat)(d.o("x"));d=(0,window.parseFloat)(d.o("y"));return new D.R(c,d)};
D.ib.prototype.K2=function(b,c,d,e,f){if(d.Om[c]){c=new D.P(e.o(D.mv));b=new D.tv(b,this.N.qe);var g=d.wP;e=d.uP;d=new D.Vd(d.vP.v("border-color"),1,2);var h=new D.Vd(g.v("-tr-inner-color"),1,1),g=new D.Vd(g.v("-tr-outer-color"),1,4);b.Mq(d,D.r).Oq(h,g);e&&(d=new D.Vd(e.v("-tr-inner-color"),1,2),e=new D.Vd(e.v("-tr-outer-color"),1,4),(0,D.uv)(b,d,e));f.Qd(b);(0,D.sv)(this,"colorStyles",c,b,f)}};
D.ib.prototype.L2=function(b,c,d,e,f){var g=D.r;if(d=(0,D.qv)(this,d,e,"cities"!=d)){if(g=e.o("source"))g=[g,e.o("sourceSelected"),e.o("sourceHover"),e.o("sourceHoverSelected")];else if((g=e.o("shapeType"))||(g="c"),!(0,D.fe)(g)){c=c.getElementsByTagName("markerDef");for(var h=0;h<c.length;h++)!this.nda[g]&&c[h].o("id")==g&&(this.nda[g]=D.yc.Ija(b,c[h]))}c=e.o("scaleX");c=(0,window.isNaN)(c)?1:(0,window.parseFloat)(c);var h=e.o("scaleY"),h=(0,window.isNaN)(h)?1:(0,window.parseFloat)(h),k=e.o("width"),
m=e.o("height"),k=!k||(0,window.isNaN)(k)?8:(0,window.parseInt)(k),m=!m||(0,window.isNaN)(m)?8:(0,window.parseInt)(m),g=new D.Lb(b,g,this.N.Tb,d.x-k*c/2,d.y-m*h/2,k,m,D.r,c,h);f.Nn(d);f.Qd(g);f.$j(k*c*m*h);if(b=e.o(D.mv))b=new D.P(b),(0,D.sv)(this,"graduatedSymbol",b,g,f)}};
D.sv=function(b,c,d,e,f){d||(d={});var g=d.v("pattern"),h=d.v("pattern-color"),k=d.v("background-color"),m=b.dfa||"alta"==b.N.Tb?D.u:d.v("gradient");k&&f?f.an.push(k):h&&f&&f.an.push(h);var p;p=d.v("opacity")?(0,window.parseFloat)(d.v("opacity")):1;f&&f.Y7(k?k:h);if("graduatedSymbol"==c&&(0,D.fe)(e.Ba())){c=b.N.ega;f=d.v("border-style")?d.v("border-style"):c.v("border-style");if("none"!=f){var q=d.v("border-color")?d.v("border-color"):c.v("border-color");(d=d.v("border-width")?d.v("border-width"):
c.v("border-width"))&&(d=(0,window.parseFloat)(d.substring(0,d.indexOf("px"))));d=new D.Vd(q,1,d);d.Pi((0,D.ii)(f));b.N.Br||(d.Yc=D.o);e.Y(d)}"true"==m&&k?e.G(new D.eg.Y4(k,e,p)):g?e.G(new D.zc(g,h,k)):k?e.na(k,p):e.na(c.v("background-color"),p)}else if("colorStyles"==c){if((m=d.v("border-color"))&&"transparent"!=m)d=new D.Vd(m),b.N.qe&&(d.Yc=D.o),e.Y(d);g?(b=new D.zc(g,h,k),e.Hha=b):k&&"transparent"!=k?e.na(k,p):e.G(D.r)}};
D.Ea=function(b){this.Init(b)};D.F.l(D.Ea,D.F,"DvtThematicMapJsonParser");D.E=D.Ea.prototype;D.E.Init=function(b){this.N=b;this.Nv=D.u;this.Vs=D.r;this.dfa=D.K.da();this.lda={}};
D.E.parse=function(b){b.skin="alta";this.aY(b);var c=b.styleDefaults;this.Vs=new D.P(c.areaStyle+c.labelStyle);var d=new D.P("fill-type:solid;background-color:"+c.backgroundColor);this.N.OJ=d;this.N.Sr=c;this.Nv&&(c=(new D.jl).parse(b.sourceXml))&&this.SX(c);for(var c=b.areaLayers,d=this.N.ze,e=0;e<c.length;e++){var f=D.xa.zb(c[e],D.ev),g=f.layer;if(g){var h;f.areaStyle&&(0,D.ql)(this.Vs,f.areaStyle);if(this.Nv)h=new D.Pu(this.N,g,D.r,f.labelDisplay,f.labelType,this.N.xa),(0,D.Su)(h,this.lda[g]);
else{h=new D.bb(this.N,g,D.r,f.labelDisplay,f.labelType,this.N.xa);var k=D.yb.mka(d,g),m=this.F_(k);h.Om=m;(0,D.Ru)(h,k);k=D.yb.lka(d,g);h.pB=k;g=D.yb.vka(this.N.ze,g);h.Zd=g}h.TR=this.Vs;h.HH("auto"==f.animationOnLayerChange?"alphaFade":f.animationOnLayerChange);h.Mn(this.N.Ta());this.N.ye.push(h);f.areaDataLayer&&this.EI([f.areaDataLayer],h,D.o);f.pointDataLayers&&this.EI(f.pointDataLayers,h,D.u)}}this.EI(b.pointDataLayers,D.r,D.u)};
D.E.aY=function(b){this.N.Mn(b.animationDuration/1E3);this.N.rZ="auto"==b.animationOnDisplay?"alphaFade":b.animationOnDisplay;this.N.Qba="auto"==b.animationOnMapChange?"alphaFade":b.animationOnMapChange;this.Nv=b.source!=D.r;var c=this.N,d=this.Nv?"$"+b.basemap:b.basemap;c.IP=c.ze&&c.ze!=d;c.ze=d;this.N.qv=b.controlPanelBehavior;this.N.OV("none");this.N.wR="auto"==b.initialZooming;this.N.Br="fixed"==b.markerZoomBehavior;this.N.GF="auto"==b.panning;c=b.tooltipDisplay;"shortDesc"==c?c="shortDescOnly":
"labelAndShortDesc"==c&&(c="auto");this.N.b0=c;this.N.Zy="auto"==b.zooming};
D.E.EI=function(b,c,d){if(b)for(var e=0;e<b.length;e++){var f=D.xa.zb(b[e],D.fv);c?c instanceof D.bb&&(0,D.lv)(c):(c=new D.Vu(this.N,this.N.xa),this.N.ye.push(c));var g=new D.pv(this.N,c,f.id,this.N.xa),h=f.selection;"single"==h?g.ys("s"):"multiple"==h&&g.ys("m");g.HH("auto"==f.animationOnDataChange?"alphaFade":f.animationOnDataChange);g.Mn(this.N.Ta());var k=D.r;c instanceof D.bb&&(k=f.isolatedItem);var m=f.disclosedItems,h=[],p,q=f.areas;if(q)for(var t=0;t<q.length;t++){var v=q[t].location;if(k)if(k!=
q[t].id)continue;else p=v;m&&-1!=m.indexOf(q[t].id)&&h.push(v);if(v=this.K2(c,g,q[t])){if(g.rc()){var w=v.Ka();w.ug(D.o)}(0,D.rv)(g,v)}}if(m=f.markers)for(t=0;t<m.length;t++){v=m[t].location;if(d&&k)if(k!=m[t].id)continue;else p=v;if(v=this.L2(c,g,m[t],d))g.rc()&&(w=v.Ka(),w.ug(D.o)),q=g,q.th.push(v),q.xa.ma(v.Ka(),v)}p&&(g.Qwa=k,(0,D.iv)(c,p));if((f=f.selectedItems)&&0<f.length)g.tR=f;h&&0<h.length&&(this.N.ZE[c.vf]=[g.jh(),h]);c.Tg[g.jh()]=g}};
D.E.SX=function(b){b=b.pb();for(var c,d,e=0;e<b.length;e++)c=b[e],d=c.getName(),"layer"==d?this.I2(c):"points"==d&&this.J2(c)};D.E.I2=function(b){var c=b.pb();b=b.o("id");for(var d,e,f=[],g=0;g<c.length;g++)if(d=c[g],e=d.getName(),"image"==e){e={};e.source=d.o("source");e.width=d.o("width");e.height=d.o("height");var h=d.o("bidi");d=d.o("dir");e.dir="true"==h||"rtl"==d?"rtl":"ltr";f.push(e)}this.lda[b]=f};
D.E.J2=function(b){b=b.pb();for(var c,d,e={},f={},g=0;g<b.length;g++)c=b[g],d=c.getName(),"point"==d&&(e[c.o("name")]=[c.o("x"),c.o("y")],f[c.o("name")]=[D.r,c.o("longLabel")]);D.yb.EV(this.N.ze,"cities",f,e,D.r,D.r,1)};D.E.F_=function(b){var c={},d=this.N.e,e;for(e in b)c[e]=new D.Ra(d),(0,D.Bv)(this,this.Vs,c[e]);return c};
D.E.K2=function(b,c,d){var e=d.location;if(b.Om[e]&&d.color){b.cq[e]=D.u;var f=this.N.e,g=new D.tv(f,this.N.qe);d=D.xa.zb(d,this.N.Sr.dataAreaDefaults);d.labelStyle||(d.labelStyle=this.N.Sr.labelStyle);var h=new D.Vd(d.hoverColor,1,2),k=new D.Vd(d.selectedInnerColor,1,1),m=new D.Vd(d.selectedOuterColor,1,4);g.Mq(h,D.r).Oq(k,m);h=new D.Vd(d.drilledInnerColor,1,2);k=new D.Vd(d.drilledOuterColor,1,4);(0,D.uv)(g,h,k);e=new D.Nu(f,c,d.id,d.clientId,e);e.Qd(g);(0,D.Cv)(this,b,c,d,g,e,D.o);return e}return D.r};
D.E.L2=function(b,c,d,e){var f;f=d;var g=this.N.ze,h=f.location;f=h?e?D.yb.kka(g,b.vf,h):D.yb.xka(g,h):D.Z.sFa(f.x,f.y,this.N.ze);if(!f)return D.r;g=this.N.e;window.dataObj=new D.gv(g,c,d.id,d.clientId,d.location);window.dataObj.Nn(f);d=D.xa.zb(d,this.N.Sr.dataMarkerDefaults);(h=d.source)?h=[h,d.sourceSelected,d.sourceHover,d.sourceHoverSelected]:(h=d.shape)||(h="c");var k=d.scaleX;(0,window.isNaN)(k)&&(k=1);var m=d.scaleY;(0,window.isNaN)(m)&&(m=1);var p=d.width,q=d.height;if(!p||(0,window.isNaN)(p))p=
8;if(!q||(0,window.isNaN)(q))q=8;window.marker=new D.Lb(g,h,"alta",f.x-p*k/2,f.y-q*m/2,p,q,D.r,k,m);window.dataObj.Qd(window.marker);window.dataObj.$j(p*k*q*m);window.dataObj.Gc(d.labelPosition);if(f=d.rotation)g=f*window.Math.PI/180,window.marker.Oi(g),f=window.dataObj.ed(),(0,D.Ya)(window.marker,f.x-(f.x*window.Math.cos(g)-f.y*window.Math.sin(g)),f.y-(f.x*window.Math.sin(g)+f.y*window.Math.cos(g)));(0,D.Cv)(this,b,c,d,window.marker,window.dataObj,e);return window.dataObj};
D.Cv=function(b,c,d,e,f,g,h){var k=e.location;h&&"auto"==c.WG()&&(c.Kr[k]=D.u);e.action&&(g.nR=D.o,g.ag=e.action);if(k=e.destination){var m=[];m.destination=k;m.targetFrame="_blank";m.focusable=D.o;(0,D.Gf)(f,m)}m=b.N.b0;if("none"!=m){k=e.shortDesc;if("auto"==m){var p;(m=e.location)&&(p=!h||b.Nv?D.yb.yka(b.N.ze,m):D.yb.Wka(b.N.ze,c.vf,m));p&&(k=k?p+": "+k:p)}k&&g.X7(k)}p=new D.P;p.aa("background-color",e.color);p.aa("pattern",e.pattern);p.aa("border-color",e.borderColor);p.aa("border-style",e.borderStyle);
e.borderWidth&&p.aa("border-width",e.borderWidth);p.aa("opacity",e.opacity);(0,D.Bv)(b,p,f,g);f=e.location;k=(p=e.label)?"on":"off";h&&(k=c.WG());!p&&(g instanceof D.Nu&&"off"!=k)&&(p="long"==c.g1?c.Qn[f][1]:c.Qn[f][0]);if(p){var q=b.N.e,q=g instanceof D.gv?new D.pc(q,p,0,0):new D.Fb(q,p,c.pU?c.pU(f):D.r,k,d.KA,b.N.qe);b=new D.P(e.labelStyle);q instanceof D.Fb&&(b.v("color")||b.aa("color",D.S.Cl(g.nj())));q.Ia(b)}g.On(q)};
D.Bv=function(b,c,d,e){c||(c={});var f=c.v("pattern"),g=c.v("background-color");e&&e.Y7(g);if(d instanceof D.Lb&&(0,D.fe)(d.Ba())){"none"!=c.v("border-style")&&(e=new D.Vd(c.v("border-color"),1,c.v("border-width")),b.N.Br||(e.Yc=D.o),e.Pi((0,D.ii)(c.v("border-style"))),d.Y(e));var h=c.v("opacity");"true"==D.u&&g?d.G(new D.eg.Y4(g,d,h)):f?d.G(new D.zc(f,g,"#FFFFFF")):g?d.na(g,h):d.na(c.v("background-color"),h)}else if(d instanceof D.Ra){if((c=c.v("border-color"))&&"transparent"!=c)e=new D.Vd(c),b.N.qe&&
(e.Yc=D.o),d.Y(e);f?(b=new D.zc(f,g,"#FFFFFF"),d.Hha=b):"transparent"!=g?d.na(g,h):d.G(D.r)}};
D.Z={};D.F.l(D.Z,D.F,"DvtThematicMapProjections");D.Z.Xu=new D.I(0,0,800,500);D.Z.kP=6378206.4;D.Z.UY=new D.I(500,200,200,200);D.Z.TY=new D.I(163,-49,17,17);D.Z.Saa=new D.I(-17.379205428479874,-37.201510854305546,68.66391442808313,77.50071544582713);D.Z.Vaa=new D.I(-0.8436866097568272,-0.7626456732012923,1.8336308036296942,1.5748427214611724);D.Z.Waa=new D.I(113.29667079927977,-52.89550592498755,65.25257389065216,42.123114617504626);
D.Z.hba=new D.I(-0.47944476148667076,-0.0014669405958800579,0.7364925893845453,0.6293972741802124);D.Z.qba=new D.I(-0.6154469465354344,-0.24589767758847714,1.2448236795108683,1.2631535127174947);D.Z.wba=new D.I(-80.60817722658722,-60.796273249672765,46.608687602908056,66.96595767361796);D.Z.Uaa=new D.I(68.20516856593524,-52.89892708045518,111.65739821771903,116.55460214469134);D.Z.fba=new D.I(-24.543831069368586,-37.202500659225905,204.54283106936856,164.9634493690208);
D.Z.pba=new D.I(-117.12451221229134,-54.95921623126266,82.33223251442891,87.67786623127876);D.Z.Aba=new D.I(-0.6154656300926513,0.0507209798775865,1.0153104799231851,0.966537441082997);D.Z.Bba=new D.I(-171.9,-62.6,349.8,150.8);D.Z.Sqa=new D.I(172,51,8,3);D.Z.Tqa=new D.I(-180,51,51,21);D.Z.ura=new D.I(-178.5,18.9,35,11);D.Z.ssa=new D.I(-124.8,24.4,58,25.5);D.Z.Taa=new D.I(-187.5517578125,59.82610321044922,57.562225341796875,43.83738708496094);
D.Z.lba=new D.I(-160.23606872558594,18.91549301147461,5.4374847412109375,3.3189010620117188);D.Z.zba=new D.I(-2386803.25,-1183550.5,4514111,2908402);D.Z.RY=new D.I(165,400,100,100);D.Z.NY=new D.I(-75,350,240,150);D.Z.hl=[[1,0],[0.9986,0.0314],[0.9954,0.0629],[0.99,0.0943],[0.9822,0.1258],[0.973,0.1572],[0.96,0.1887],[0.9427,0.2201],[0.9216,0.2515],[0.8962,0.2826],[0.8679,0.3132],[0.835,0.3433],[0.7986,0.3726],[0.7597,0.4008],[0.6732,0.4532],[0.6213,0.4765],[0.5722,0.4951],[0.5322,0.5072]];
D.Z.sFa=function(b,c,d){var e;switch(d){case "africa":e=D.Z.Ev(D.Z.Saa,D.Z.tK(b,c));break;case "asia":e=D.Z.Ev(D.Z.Vaa,D.Z.bR(40,95,20,60,b,c),D.Z.Sg(5));break;case "australia":e=D.Z.qva(b,c);break;case "europe":e=D.Z.Ev(D.Z.hba,D.Z.bR(35,25,40,65,b,c),D.Z.Sg(10));break;case "northAmerica":e=D.Z.Ev(D.Z.qba,D.Z.bR(23,-96,20,60,b,c));break;case "southAmerica":e=D.Z.Ev(D.Z.wba,new D.R(b,c),D.Z.Sg(5));break;case "apac":e=D.Z.Ev(D.Z.Uaa,D.Z.tK(b,c));break;case "emea":e=D.Z.Ev(D.Z.fba,D.Z.tK(b,c));break;
case "latinAmerica":e=D.Z.Ev(D.Z.pba,new D.R(b,c));break;case "usaAndCanada":e=D.Z.Ev(D.Z.Aba,D.Z.bR(23,-96,20,60,b,c));break;case "worldRegions":e=D.Z.uea(b,c);break;case "usa":e=D.Z.awa(b,c);break;case "world":e=D.Z.uea(b,c)}return e?new D.R(10*e.x,10*e.y):new D.R(b,c)};
D.Z.awa=function(b,c){var d;return(0,D.ph)(D.Z.Sqa,b,c)||(0,D.ph)(D.Z.Tqa,b,c)?(d=D.Z.jn(D.Z.Taa,D.Z.NY),D.Z.dJ(d,D.Z.tK(b,c))):(0,D.ph)(D.Z.ura,b,c)?(d=D.Z.jn(D.Z.lba,D.Z.RY),D.Z.dJ(d,new D.R(b,c))):(0,D.ph)(D.Z.ssa,b,c)?(d=D.Z.jn(D.Z.zba,D.Z.Xu),D.Z.dJ(d,D.Z.Rva(new D.R(-95,36),b,c))):new D.R(b,c)};D.Z.uea=function(b,c){var d=D.Z.jn(D.Z.Bba,D.Z.Xu);return D.Z.dJ(d,D.Z.Vva(b,c))};
D.Z.qva=function(b,c){var d;d=(0,D.ph)(D.Z.TY,b,c)?D.Z.jn(D.Z.TY,D.Z.UY):D.Z.jn(D.Z.Waa,D.Z.Xu);return D.Z.dJ(d,D.Z.tK(b,c))};D.Z.Ev=function(b,c,d){b=D.Z.jn(b,D.Z.Xu);if(d){var e=new D.jb;e.rotate(d);b=D.Z.Qca(b,e)}return(0,D.yf)(b,c)};
D.Z.bR=function(b,c,d,e,f,g){c=D.Z.Sg(c);b=D.Z.Sg(b);d=D.Z.Sg(d);e=D.Z.Sg(e);e=0.5*(window.Math.sin(d)+window.Math.sin(e));d=window.Math.pow(window.Math.cos(d),2)+2*e*window.Math.sin(d);b=d-2*e*window.Math.sin(b);b=window.Math.sqrt(b)/e;f=e*(D.Z.Sg(f)-c);g=d-2*e*window.Math.sin(D.Z.Sg(g));g=window.Math.sqrt(g)/e;return new D.R(g*window.Math.sin(f),b-g*window.Math.cos(f))};D.Z.tK=function(b,c){var d=window.Math.log(window.Math.tan(0.25*window.Math.PI+0.5*D.Z.Sg(c)));return new D.R(b,D.Z.XH(d))};
D.Z.Rva=function(b,c,d){c=D.Z.Sg(c);d=D.Z.Sg(d);var e=D.Z.Sg(b.x);b=D.Z.Sg(b.y);return new D.R(window.Math.cos(d)*window.Math.sin(c-e)*D.Z.kP,(window.Math.cos(b)*window.Math.sin(d)-window.Math.sin(b)*window.Math.cos(d)*window.Math.cos(c-e))*D.Z.kP)};
D.Z.Vva=function(b,c){var d=window.Math.floor(window.Math.abs(c)/5);d>=D.Z.hl.length-1&&(d=D.Z.hl.length-2);var e=(window.Math.abs(c)-5*d)/5,f=b*(D.Z.hl[d][0]+e*(D.Z.hl[d+1][0]-D.Z.hl[d][0])),d=D.Z.hl[d][1]+e*(D.Z.hl[d+1][1]-D.Z.hl[d][1]);0>c&&(d*=-1);return new D.R(f,180*d)};D.Z.dJ=function(b,c){return new D.R(c.x*b.Ic+b.Fb,c.y*b.xe+b.yb)};D.Z.Qca=function(b,c){var d=b.Ic,e=b.xe;return new D.jb(c.Ic*d,c.Nf*d,c.jf*e,c.xe*e,b.Fb+c.Fb*d,b.yb+c.yb*e)};
D.Z.jn=function(b,c){var d=c.x,e=c.y,f=b.g,g=b.j,h=0,h=c.g/f,k=c.j/g,h=h<=k?h:k,d=d-b.x*h,e=e+b.y*h,d=d+(c.g-f*h)/2,e=e+(c.j-(c.j-g*h)/2);return new D.jb(h,0,0,-h,d,e)};D.Z.Sg=function(b){return b*(window.Math.PI/180)};D.Z.XH=function(b){return b*(180/window.Math.PI)};
D.Z.LJa=function(b,c,d){var e;b/=10;c/=10;switch(d){case "africa":e=D.Z.Fv(D.Z.Saa,new D.R(b,c));e=D.Z.sK(e.x,e.y);break;case "asia":e=D.Z.Fv(D.Z.Vaa,new D.R(b,c),D.Z.Sg(5));e=D.Z.dR(40,95,20,60,e.x,e.y);break;case "australia":e=D.Z.Gva(b,c);break;case "europe":e=D.Z.Fv(D.Z.hba,new D.R(b,c),D.Z.Sg(10));e=D.Z.dR(35,25,40,65,e.x,e.y);break;case "northAmerica":e=D.Z.Fv(D.Z.qba,new D.R(b,c));e=D.Z.dR(23,-96,20,60,e.x,e.y);break;case "southAmerica":e=D.Z.Fv(D.Z.wba,new D.R(b,c),D.Z.Sg(5));break;case "apac":e=
D.Z.Fv(D.Z.Uaa,new D.R(b,c));e=D.Z.sK(e.x,e.y);break;case "emea":e=D.Z.Fv(D.Z.fba,new D.R(b,c));e=D.Z.sK(e.x,e.y);break;case "latinAmerica":e=D.Z.Fv(D.Z.pba,new D.R(b,c));break;case "usaAndCanada":e=D.Z.Fv(D.Z.Aba,new D.R(b,c));e=D.Z.dR(23,-96,20,60,e.x,e.y);break;case "worldRegions":e=D.Z.jea(b,c);break;case "usa":e=D.Z.Jva(b,c);break;case "world":e=D.Z.jea(b,c)}return e?e:new D.R(b,c)};
D.Z.Jva=function(b,c){var d;return(0,D.ph)(D.Z.NY,b,c)?(d=D.Z.jn(D.Z.Taa,D.Z.NY),d.hu(),d=(0,D.yf)(d,new D.R(b,c)),D.Z.sK(d.x,d.y)):(0,D.ph)(D.Z.RY,b,c)?(d=D.Z.jn(D.Z.lba,D.Z.RY),d.hu(),(0,D.yf)(d,new D.R(b,c))):(0,D.ph)(D.Z.Xu,b,c)?(d=D.Z.jn(D.Z.zba,D.Z.Xu),d.hu(),d=(0,D.yf)(d,new D.R(b,c)),D.Z.Hva(new D.R(-95,36),d.x,d.y)):new D.R(b,c)};D.Z.jea=function(b,c){var d=D.Z.jn(D.Z.Bba,D.Z.Xu);d.hu();d=(0,D.yf)(d,new D.R(b,c));return D.Z.Iva(d.x,d.y)};
D.Z.Gva=function(b,c){var d;d=(0,D.ph)(D.Z.UY,b,c)?D.Z.jn(D.Z.TY,D.Z.UY):D.Z.jn(D.Z.Waa,D.Z.Xu);d.hu();d=(0,D.yf)(d,new D.R(b,c));return D.Z.sK(d.x,d.y)};D.Z.Fv=function(b,c,d){b=D.Z.jn(b,D.Z.Xu);if(d){var e=new D.jb;e.rotate(d);b=D.Z.Qca(b,e)}b.hu();return(0,D.yf)(b,c)};
D.Z.dR=function(b,c,d,e,f,g){c=D.Z.Sg(c);b=D.Z.Sg(b);d=D.Z.Sg(d);e=D.Z.Sg(e);e=0.5*(window.Math.sin(d)+window.Math.sin(e));d=window.Math.pow(window.Math.cos(d),2)+2*e*window.Math.sin(d);b=d-2*e*window.Math.sin(b);b=window.Math.sqrt(b)/e;var h=window.Math.sqrt(f*f+(b-g)*(b-g));return new D.R(D.Z.XH(c+window.Math.atan(f/(b-g))/e),D.Z.XH(window.Math.asin((d-h*h*e*e)/(2*e))))};D.Z.sK=function(b,c){return new D.R(b,D.Z.XH(2*window.Math.atan(window.Math.exp(D.Z.Sg(c)))-0.5*window.Math.PI))};
D.Z.Hva=function(b,c,d){c/=D.Z.kP;d/=D.Z.kP;var e=D.Z.Sg(b.y),f=window.Math.sqrt(c*c+d*d),g=window.Math.asin(f);return new D.R(D.Z.XH(D.Z.Sg(b.x)+window.Math.atan(c*window.Math.sin(g)/(f*window.Math.cos(e)*window.Math.cos(g)-d*window.Math.sin(e)*window.Math.sin(g)))),D.Z.XH(window.Math.asin(window.Math.cos(g)*window.Math.sin(e)+d*window.Math.sin(g)*window.Math.cos(e)/f)))};
D.Z.Iva=function(b,c){var d=window.Math.floor(window.Math.abs(c)/5);d>=D.Z.hl.length-1&&(d=D.Z.hl.length-2);var e=(window.Math.abs(c/180)-D.Z.hl[d][1])/(D.Z.hl[d+1][1]-D.Z.hl[d][1]),f=5*e+5*d,d=b/(D.Z.hl[d][0]+e*(D.Z.hl[d+1][0]-D.Z.hl[d][0]));0>c&&(f*=-1);return new D.R(d,f)};
D.Pd=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.l(D.Pd,D.Lc,"DvtMapControlButton");
D.Pd.prototype.Init=function(b,c,d,e,f,g,h){D.Pd.q.Init.call(this,b,e,g);this.XZ=f;this.Kb=c;this.Ga=h;(0,D.Mc)(this.Kb,this.gpa,this);this.Kb.setCursor("pointer");b=new D.Nc(this,D.r,D.r,D.r,D.r,D.r,0==this.XZ?(0,D.Na)(this.bb,"CONTROL_PANEL_DRILLUP"):1==this.XZ?(0,D.Na)(this.bb,"CONTROL_PANEL_DRILLDOWN"):2==this.XZ?(0,D.Na)(this.bb,"CONTROL_PANEL_RESET"):D.r);this.Ga.ma(this.Kb,b);this.k(this.Kb);this.Zfa=d;this.Xea=D.o};
D.Pd.prototype.Pg=function(b){this.B(b?1:0.4);this.Kb.setCursor(b?"pointer":D.r);this.Xea=b;this.Kb.Pg(b);(0,D.Rc)(this.Kb)};D.Pd.prototype.gpa=function(b){(0,D.Vc)(b);this.Xea&&this.Zfa&&this.Zfa()};
D.sb=function(b,c,d,e,f,g,h,k){this.Init(b,c,d,e,f,g,h,k)};D.F.l(D.sb,D.ud,"DvtThematicMapControlPanel");D.sb.prototype.Init=function(b,c,d,e,f,g,h,k){D.sb.q.Init.call(this,b,f,d,g,h,k);this.Jj=c;this.Gj=d;this.ava=e[0];this.Zua=e[1];this.Xya=e[2];this.BE=this.CE=this.aia=D.r;this.Bda=this.Ada=D.u;this.D=k.$r()};D.vb=function(b,c){b.Ada=c;b.BE&&b.BE.Pg(c)};D.wb=function(b,c){b.Bda=c;b.CE&&b.CE.Pg(c)};
D.sb.prototype.II=function(b){if(this.Jj&&"none"!=this.Jj){var c=(0,D.id)(this.D,"buttonWidth",0);this.aia=D.M.RAa(this.e,this.Xya,this.ba,this.bb,this.Gj,this.Ga,this.D);b.k(this.aia);this.BE=D.M.EAa(this.e,this.Zua,this.ba,this.bb,this.Gj,this.Ga,this.D);this.BE.F(c);this.BE.Pg(this.Ada);b.k(this.BE);this.CE=D.M.FAa(this.e,this.ava,this.ba,this.bb,this.Gj,this.Ga,this.D);this.CE.F(2*c);this.CE.Pg(this.Bda);b.k(this.CE)}};
});