define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Db=function(b,c,d){this.Init(b,c,d)};D.E.l(D.Db,D.Eb,"DvtBaseTreemap");D.D=D.Db.prototype;D.D.Init=function(b,c,d){D.Db.n.Init.call(this,b,c,d);this.Fe=new D.Fb};D.D.Ot=function(b){return(new D.Gb(this)).parse(b)};D.D.bG=function(b){D.Db.n.bG.call(this,b);this.ef=b.$n;this.ota=b.O3;this.ef&&(this.ef.aN=this.aN);this.kd=[];if((b=b.vja)&&this.Za){var c=(0,D.Hb)(this.Za);c.push(this.Za);for(var d=0;d<c.length;d++)if(c[d].getId()==b){this.kd.push(c[d]);break}}};
D.D.hn=function(b){var c=window.Math.max(window.Math.ceil(7*window.Math.min(b.f,b.g)/400),2);b.x+=c;b.y+=c;b.f-=2*c;b.g-=2*c;c=this.ef.Q2(this,1);b.x+=c;b.f-=2*c;(0,D.Ib)(this,b);(0,D.Jb)(this,b);b.x-=c;b.f+=2*c;c=this.kd.length;if(0<c&&this.GP)this.ef.$n(this,this.kd[c-1],b.x,b.y,b.f,b.g,D.o);else{this.Za&&this.ef.$n(this,this.Za,b.x,b.y,b.f,b.g,D.t);for(var d=0;d<c;d++)this.ef.$n(this,this.kd[d],b.x,b.y,b.f,b.g,D.o)}};
D.D.zk=function(b){this.RM(b,"background-color:#EBEFF5;border-color:#DBE0EA;border-width:2px");this.pq&&b.j(this.pq);this.eb&&(b.j(this.eb),this.eb=D.r);if((0,D.Kb)(this)){this.fZ=new D.K(this.e);b.j(this.fZ);this.aua?this.aua.H(b):this.Za.Nd()?this.Za.wt(b):this.Za.H(b);this.HZ=new D.K(this.e);b.j(this.HZ);this.Os=new D.K(this.e);b.j(this.Os);b.j(this.fZ);this.Pw=new D.Lb(this.e,[]);this.Pw.Qa(D.t);this.Pw.ea(D.t);(0,D.Mb)(this.Pw);b.j(this.Pw);for(b=0;b<this.kd.length;b++){var c=this.kd[b].nb();
this.HZ.j(c)}}else(0,D.Nb)(this,b)};D.D.Co=function(){this.fU||(this.ba.bi(),this.hn(new D.L(0,0,this.Ob,this.Ab)),this.zk(this.ba),this.dW());D.Db.n.Co.call(this)};D.D.dW=function(){for(var b=this.Db?this.Db.getSelection():[],c=0;c<b.length;c++)if(0<this.kd.length){var d=this.kd[this.kd.length-1];(b[c]==d||(0,D.Ob)(b[c],d))&&b[c].Gb(D.o)}else b[c].Gb(D.o)};D.D.KB=function(b){return new D.Pb(b)};D.D.uU=function(b,c,d,e){return new D.Qb(b,c,d,e)};
D.D.I6=function(b){var c=(0,D.Rb)(this);return c?(0,D.Sb)(this,(0,D.Tb)(c)):b?(0,D.Sb)(this,(0,D.Tb)(b)):D.r};D.D.oN=function(b){for(var c=0,d=this.Os.xa(),e=0;e<d;e++){var f=this.Os.da(e);b.zIndex>f.zIndex&&(c=e+1)}c<d?this.Os.ya(b,c):this.Os.j(b)};D.Rb=function(b){return b.kd&&0<b.kd.length?b.kd[b.kd.length-1]:D.r};
D.Wb=function(b,c){if(b.aM){for(var d=b.Db?b.Db.getSelection():[],e=0;e<d.length;e++)d[e].Gb(D.t);for(var d=[(0,D.Vb)(c)],e=(0,D.Hb)(c),f=0;f<e.length;f++)d.push((0,D.Vb)(e[f]));b.cm=new D.Fa(b.e,d);b.cm.gd(b.Co,b);b.pa.ky(b);b.cm.play()}else b.H(D.r,b.Ob,b.Ab,D.o)};D.Sb=function(b,c){var d=b.pa.zo;return d?d.Pha(c):c&&0<c.length?c[0]:D.r};
D.Xb=(0,D.w)();(0,D.sa)("DvtTreemap",D.Xb);D.E.l(D.Xb,D.Db,"DvtTreemap");D.Xb.newInstance=function(b,c,d){var e=new D.Xb;e.Init(b,c,d);return e};D.Xb.getDefaults=function(b){return(0,D.Yb)(new D.Fb,b)};D.Xb.prototype.H=function(b,c,d,e){b?(this.S=this.Fe.Gg(b),D.I.Zh()||(this.S.animationOnDisplay="none",this.S.animationOnDataChange="none")):this.S||(this.S=(0,D.Zb)(this));b=e?D.r:(new D.$b(this.e)).YT(this.S);D.Xb.n.H.call(this,b,c,d)};D.Xb.prototype.render=D.Xb.prototype.H;
D.Gb=function(b){this.Init(b)};D.E.l(D.Gb,D.Uu,"DvtTreemapParser");D.D=D.Gb.prototype;D.D.em=function(b,c,d){return new D.Vu(b,c,d)};D.D.jl=function(b){var c=D.Gb.n.jl.call(this,b),d=b.k("layout");c.$n="h"==d?new D.Qu(D.o):"v"==d?new D.Qu(D.t):new D.Wu;c.O3=b.k("gg");c.O3||(c.O3="o");c.vja=b.k("irk");this.Zta=c.vja;return c};
D.D.Pt=function(b){var c=D.Gb.n.Pt.call(this,b);c.Oia=b.k("gld");c.WS=b.k("ha");c.yja=b.k("va");c.uja=b.k("hi");c.BBa=b.k("unc");c.hja=b.k("hha");if(b=b.k("hls"))c.ABa=new D.P(b);this.Zta==c.id&&(c.Rm=D.o);return c};D.D.NV=function(b,c,d,e){e.NODE_HOVER_COLOR=c.q("border-color");e.NODE_SELECTED_OUTER_COLOR=d.q("-tr-outer-color");e.NODE_SELECTED_INNER_COLOR=d.q("-tr-inner-color")};
D.D.W7=function(b,c){var d=new D.P(b.k("nodeHeader"));c.HEADER_TEXT_DEFAULT_STYLE=d;c.HEADER_BACKGROUND_STYLE=d;var e=d.clone().qb(new D.P(b.k("nodeHeader-hover")));c.HEADER_TEXT_HOVER_DEFAULT_STYLE=e;c.HEADER_BACKGROUND_HOVER_STYLE=e;var f=d.clone().qb(new D.P(b.k("nodeHeader-selected")));c.HEADER_TEXT_SELECTED_DEFAULT_STYLE=f;c.HEADER_BACKGROUND_SELECTED_STYLE=f;d=d.clone().qb(new D.P(b.k("nodeHeaderDrill")));c.HEADER_DRILL_TEXT_DEFAULT_STYLE=d;c.HEADER_DRILL_TEXT_HOVER_DEFAULT_STYLE=d.clone().qb(new D.P(b.k("nodeHeaderDrill-hover")));
c.HEADER_DRILL_TEXT_SELECTED_DEFAULT_STYLE=d.clone().qb(new D.P(b.k("nodeHeaderDrill-selected")));c.HEADER_HOVER_OUTER_COLOR_STYLE=e.q("-tr-outer-color");c.HEADER_HOVER_INNER_COLOR_STYLE=e.q("-tr-inner-color");c.HEADER_SELECTED_OUTER_COLOR_STYLE=f.q("-tr-outer-color");c.HEADER_SELECTED_INNER_COLOR_STYLE=f.q("-tr-inner-color")};
D.Vu=function(b,c,d){this.Init(b,c,d);this.En=c.VS?c.VS:"n";this.pta=c.Oia?c.Oia:"h";this.hD=c.WS?c.WS:"c";this.MZ=c.yja?c.yja:"c";this.Gta=c.hja?c.hja:"s";this.Oba=c.ABa;this.kZ="on"==c.BBa;this.Yta=c.uja?c.uja:"on";this.Rw=c.Rm};D.E.l(D.Vu,D.$u,"DvtTreemapNode");
D.Vu.prototype.H=function(b){if(this.Du){this.D=this.hY();b.j(this.D);var c;this.Nd()?(this.mO=new D.K(this.C.e),this.D.j(this.mO),this.wt(this.mO)):c=this.VJ;if(c){var d=this.C.WW;d.Jk=this.Bg;var e=this.O-8-2,f=this.T-4-2;0<e&&0<f&&((0,D.pl)(d,e),(0,D.ql)(d,f),d.Af((0,D.av)(this)),this.WX=c=D.ui.nB(d,c,this.D),D.I.N(b.e)?(b=c.v(),b=this.Wa+this.O-4-1-b.f):b=this.Wa+4+1,(0,D.nc)(c,b,this.Da+2+1))}else this.Ua=this.LH(this.D),this.Ua!=D.r&&(this.Nn&&"h"!=this.xi)&&(b=this.Ua.Lb(),this.Rn=new D.Ja(this.C.e,
b.x,b.y,b.f,b.g),this.Rn.ga("#FFFFFF"),this.Rn.ea(D.t),this.D.j(this.Rn),b=this.Ua,"n"==this.xi&&this.Nd()?this.C.fZ.j(b):this.D.j(b));(0,D.Na)(this.D);(0,D.Oa)(this.D,"label",this.Ew)}};
D.Vu.prototype.Gb=function(b){if("off"!=this.VM&&(D.Vu.n.Gb.call(this,b),this.D))if(this.ib()){b=this.Wa;var c=this.Da+1,d=this.O-1,e=this.T-1;D.I.qr()&&(c-=1);(0,D.bv)(this,this.hf);(0,D.bv)(this,this.Ps);this.Ps=this.hf=D.r;this.hf=new D.Ja(this.C.e,b,c,d,e);this.hf.ea(D.t);this.hf.B(D.r);(0,D.Mb)(this.hf);this.D.j(this.hf);this.Ps=new D.Ja(this.C.e,b+1,c+1,d-2,e-2);this.Ps.ea(D.t);this.Ps.B(D.r);(0,D.Mb)(this.Ps);this.D.j(this.Ps);"h"==this.xi?(this.xG||this.bl()?(0,D.cv)(this,this.D,this.Xo,"background-color:#C4DCFF;",
"HEADER_BACKGROUND_HOVER_STYLE"):((0,D.cv)(this,this.D,this.Xo,"background-color:#9CACC9;","HEADER_BACKGROUND_SELECTED_STYLE"),this.Ua&&(0,D.dv)(this,this.Ua,"HEADER_TEXT_SELECTED_DEFAULT_STYLE","#003D5B")),this.hf.Ga((0,D.ev)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),1),this.Ps.Ga((0,D.ev)(this,"#FFFFFF","HEADER_SELECTED_INNER_COLOR_STYLE"),1)):(this.hf.Ga((0,D.ev)(this,"#000000","NODE_SELECTED_OUTER_COLOR"),1),this.Ps.Ga((0,D.ev)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR"),1),D.I.Qm()||
(0,D.qc)(this.D,D.rc),this.C.oN(this.D))}else(0,D.bv)(this,this.Ps),this.Ps=D.r,"h"==this.xi?(this.xG||this.bl()?(0,D.cv)(this,this.D,this.Xo,"background-color:#C4DCFF;","HEADER_BACKGROUND_HOVER_STYLE"):((0,D.cv)(this,this.D,this.Xo,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),this.Ua&&(this.Hp()?(0,D.dv)(this,this.Ua,"HEADER_TEXT_DEFAULT_STYLE","#003286"):(0,D.dv)(this,this.Ua,"HEADER_TEXT_DEFAULT_STYLE","#003D5B"))),this.hf&&(this.xG||this.bl()?this.hf.Ga((0,D.ev)(this,
"#00AEFF","HEADER_HOVER_OUTER_COLOR_STYLE"),"1"):((0,D.bv)(this,this.hf),this.hf=D.r))):((0,D.pc)(this.D),this.hf&&((0,D.bv)(this,this.hf),this.hf=D.r),(b=this.ye)&&b.mO&&b.mO.j(this.D))};
D.Vu.prototype.wc=function(){if(this.D&&this.Du){var b=(0,D.Rb)(this.C);if(!(b!=D.r&&b!=this&&!(0,D.Ob)(this,b))){var b=[],c,d,e,f;"h"==this.xi?((0,D.cv)(this,this.D,this.Xo,"background-color:#C4DCFF;","HEADER_BACKGROUND_HOVER_STYLE"),this.hf||(d=this.Wa,c=this.Da+1,e=this.O-1,f=this.T-1,D.I.qr()&&(c-=1),this.hf=new D.Ja(this.C.e,d,c,e,f),this.hf.ea(D.t),this.hf.B(D.r),(0,D.Mb)(this.hf),this.D.j(this.hf)),this.ib()?this.hf.Ga((0,D.ev)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),D.Vu.Sla):
this.hf.Ga((0,D.ev)(this,"#00AEFF","HEADER_HOVER_OUTER_COLOR_STYLE"),"1"),d=this.Wa+1.5+1,e=this.Wa+this.O-1.5-1,c=this.Da+this.Sk,f=this.Da+this.T-1.5-1,b.push(e,c,e,f,d,f,d,c),c=new D.re((0,D.ev)(this,"#C4DCFF","HEADER_HOVER_INNER_COLOR_STYLE"),0.8,3),this.Ua&&(this.Hp()?(0,D.dv)(this,this.Ua,"HEADER_DRILL_TEXT_HOVER_DEFAULT_STYLE","#000000"):(0,D.dv)(this,this.Ua,"HEADER_TEXT_HOVER_DEFAULT_STYLE","#000000"))):(d=this.Wa+1,e=this.Wa+this.O-1,c=this.Da+1,f=this.Da+this.T-1,b.push(this.Wa,c,e,c,e,
f,d,f,d,c),c=new D.re((0,D.ev)(this,"#FFFFFF","NODE_HOVER_COLOR"),1,2));d=this.C;d.Pw.Vb(b);d.Pw.Q(c);d.Pw.Qa(D.o)}}};
D.Vu.prototype.hc=function(){this.D&&this.Du&&("h"==this.xi&&(this.ib()?((0,D.cv)(this,this.D,this.Xo,"background-color:#9CACC9;","HEADER_BACKGROUND_SELECTED_STYLE"),this.hf.Ga((0,D.ev)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),D.Vu.Sla),this.Ua&&(this.Hp()?(0,D.dv)(this,this.Ua,"HEADER_DRILL_TEXT_SELECTED_DEFAULT_STYLE","#003D5B"):(0,D.dv)(this,this.Ua,"HEADER_TEXT_SELECTED_DEFAULT_STYLE","#003D5B"))):((0,D.cv)(this,this.D,this.Xo,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),
this.hf&&(this.D.removeChild(this.hf),this.hf=D.r),this.Ua&&(this.Hp()?(0,D.dv)(this,this.Ua,"HEADER_DRILL_TEXT_DEFAULT_STYLE","#003286"):(0,D.dv)(this,this.Ua,"HEADER_TEXT_DEFAULT_STYLE","#003D5B")))),this.C.Pw.Qa(D.t))};D.fv=function(b){return"on"==b.Yta&&"h"==b.xi};D.D=D.Vu.prototype;D.D.UA=function(b){return!b||!b.IA()?D.Vu.n.UA.call(this,b):new D.L(this.Wa,this.Da,this.O,this.T)};
D.D.Di=function(b){var c;if(b.type==D.ed)return D.Vu.n.Di.call(this,b);c=b.keyCode;if(32==c&&b.ctrlKey)return this;if(38==c&&b.altKey||221==c)(c=this.ye)&&c.getId()!=this.C.Za.getId()?(b=c,(0,D.gv)(c)):b=this;else if(40==c&&b.altKey||219==c)b=(b=this.NP)?b:this.Nd()?(0,D.Sb)(this.C,this.fb()):this;else{var d=(0,D.Rb)(this.C),e=0;if(d)if(this==d)e=0;else{c=this.ye;for(e=1;d!=c;)e++,c=c.ye}else{for(d=this;d.ye;)d=d.ye;e=(0,D.Tu)(this)}c=(0,D.hv)(this,d,e);b=(0,D.rt)(this,b,c)}(0,D.gv)(b);return b};
D.D.Jg=function(){return new D.L(this.Wa,this.Da,this.O,this.T)};
D.D.NL=function(b,c,d,e){if(!(0>=d||0>=e)){this.Du=D.o;this.Tda=this.xk();this.Wa=b;this.Da=c;this.O=d?d:0;this.T=e?e:0;this.xi=this.Nd()?this.pta:this.En;this.xx||(this.xi="o");if("h"==this.xi){this.Sk=15;b=new D.le(this.C.e,this.xx);b.Af((0,D.av)(this));(0,D.dv)(this,b,"HEADER_TEXT_DEFAULT_STYLE","#003D5B");b=D.me.Gi(b).g;this.Sk=window.Math.max(this.Sk,b);(0,D.fv)(this)&&(this.Sk=window.Math.max(this.Sk,15));b=this.Wa;c=this.Da+this.Sk;d=this.O;e=this.T-this.Sk;if(0<=d&&0<=e)return new D.L(b,c,
d,e);this.xi=D.r}return new D.L(this.Wa,this.Da,this.O,this.T)}};D.D.contains=function(b,c){return b>=this.Wa&&b<=this.Wa+this.O&&c>=this.Da&&c<=this.Da+this.T};D.D.xk=function(){var b=D.R.Nc(this.Gf),c=D.R.Mc(this.Gf),d=D.R.Lc(this.Gf);return[this.Wa,this.Da,this.O,this.T,b,c,d,this.Nd()?0:window.Math.random()]};
D.D.nn=function(b){this.NL(b[0],b[1],b[2],b[3]);this.Gf=D.R.Fv(window.Math.round(b[4]),window.Math.round(b[5]),window.Math.round(b[6]));this.D&&((0,D.mo)(this.D,this.Wa,this.Da,this.O,this.T),this.Xo&&(0,D.mo)(this.Xo,this.Wa+1,this.Da+1,this.O-2,this.T-2),("h"!=this.xi||this.kZ)&&this.D.B(this.MB()),this.ib()&&this.Gb(D.t),(0,D.bv)(this,this.wu),(0,D.bv)(this,this.dK),this.dK=this.wu=D.r,(0,D.iv)(this),this.VJ?((0,D.bv)(this,this.WX),this.WX=D.r):((0,D.bv)(this,this.Rn),this.Rn=D.r,this.Ua&&this.Ua.getParent().removeChild(this.Ua),
this.Ua=this.LH(this.D)))};D.Vb=function(b){if(b.Tda){var c=new D.Da(b.C.e,b,0.3);(0,D.G)(c.M,"typeNumberArray",b,b.xk,b.nn,b.xk());b.nn(b.Tda);return c}return D.r};D.Vu.prototype.kf=function(b,c){return 0==(0,D.Tu)(this)||c.Du&&0<c.O&&0<c.T?D.Vu.n.kf.call(this,b,c):this.ig(b)};
D.Vu.prototype.hY=function(){var b=this.C.e,c;if("h"==this.xi)c=new D.Ja(b,this.Wa,this.Da,this.O,this.T),this.Xo=new D.Ja(b,this.Wa+1,this.Da+1,this.O-2,this.T-2),(0,D.cv)(this,c,this.Xo,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),this.Xo.ea(D.t),c.j(this.Xo),this.Rw&&(this.Oe=(0,D.jv)(this,c));else{var d=this.MB();c=new D.Ja(b,this.Wa,this.Da,this.O,this.T);if((1E3>this.C.Mk||!D.I.$())&&2<=this.O&&2<=this.T){new D.re((0,D.ev)(this,"#FFFFFF","LEAF_NODE_TOP_BORDER_COLOR_STYLE"),
0.3);new D.re((0,D.ev)(this,"#000000","LEAF_NODE_BOTTOM_BORDER_COLOR_STYLE"),0.3);this.Nn&&new D.re(this.Gf,0.15);var e=this.Fb(),f=(0,D.ev)(this,"#FFFFFF","LEAF_NODE_TOP_BORDER_COLOR_STYLE"),f=D.R.nF(f,e,0.7),g=(0,D.ev)(this,"#000000","LEAF_NODE_BOTTOM_BORDER_COLOR_STYLE"),g=D.R.nF(g,e,0.7),e=window.Math.min(this.O,this.T);4<=e?(c.ga(g),this.dK=new D.Ja(b,this.Wa,this.Da,this.O-1,this.T-1),this.dK.ga(f),this.dK.ea(D.t),c.j(this.dK),this.wu=new D.Ja(b,this.Wa+1,this.Da+1,this.O-2,this.T-2),this.wu.B(d),
this.wu.ea(D.t),c.j(this.wu)):2<=e?(c.ga(g),this.wu=new D.Ja(b,this.Wa,this.Da,this.O-1,this.T-1),this.wu.B(d),this.wu.ea(D.t),c.j(this.wu)):c.B(d)}else c.B(d)}this.C.Ca().ha(c,this);this.C.B_!=D.r&&"off"!=this.VM?c.di(D.o):c.setCursor("default");c.zIndex=this.sR;return c};
D.jv=function(b,c){if("h"!=b.xi||!(0,D.fv)(b))return D.r;var d=D.r,e=b.Wa,f=b.Wa+b.O-1,g=b.Da+1,h=b.Da+b.Sk;if(12<f-e-2){if(b.Rw){var d=b.C.e,k=b.C.Fd,m=new D.Xc(d,k.restoreUp,0,0,12,12),p=new D.Xc(d,k.restoreOver,0,0,12,12),k=new D.Xc(d,k.restoreDown,0,0,12,12);(0,D.Ka)(m);(0,D.Ka)(p);(0,D.Ka)(k);d=new D.Ae(d,m,p,k);d.J(D.ed,b.G9,D.t,b)}else d=b.C.e,k=b.C.Fd,m=new D.Xc(d,k.maximizeUp,0,0,12,12),p=new D.Xc(d,k.maximizeOver,0,0,12,12),k=new D.Xc(d,k.maximizeDown,0,0,12,12),(0,D.Ka)(m),(0,D.Ka)(p),
(0,D.Ka)(k),d=new D.Ae(d,m,p,k),d.J(D.ed,b.F9,D.t,b);e=D.I.N(c.e)?e+1:f-12-1;(0,D.nc)(d,e,(h+g-12)/2);c.j(d);D.I.$()&&(g=new D.Ja(c.e,-2,-2,16,16),(0,D.Ka)(g),d.j(g));"true"==b.C.Fd.alta?b.C.Ca().ha(d,b):(g=b.Rw?b.C.Fd.restore:b.C.Fd.isolate,b.C.Ca().ha(d,new D.mc(b,b.getId(),g)))}return d};D.iv=function(b){b.Oe&&((0,D.bv)(b,b.Oe),b.Oe=D.r)};
D.Vu.prototype.LH=function(b){var c=D.I.N(b.e);if(!this.xx||!b||!this.xi||"o"==this.xi)return D.r;var d=this.T;if((0,D.av)(this)>d)return D.r;var e="n"==this.xi?this.hD:this.Gta;c&&("s"==e?e="e":"e"==e&&(e="s"));var f=this.O-6,g=0;(0,D.fv)(this)&&(g=13,f="c"==e?f-2*g:f-g);if(0>=f)return D.r;var h=new D.le(this.C.e,this.xx);h.Af((0,D.av)(this));"s"==e?(c?h.aa(this.Wa+4+g):h.aa(this.Wa+4),h.hj()):"c"==e?(h.aa(this.Wa+this.O/2),h.jf()):"e"==e&&(c?h.aa(this.Wa+this.O-4):h.aa(this.Wa+this.O-4-g),h.zi());
"n"==this.xi?(d=this.T-4,"t"==this.MZ?(h.qa(this.Da+2),h.Wn()):"c"==this.MZ?(h.qa(this.Da+this.T/2),h.Zd()):"b"==this.MZ&&(h.qa(this.Da+this.T-2),h.lv()),(0,D.kv)(this,h)):"h"==this.xi&&(c=D.I.qr()?1:0,h.qa(this.Da+1+this.Sk/2+c),h.Zd(),(0,D.dv)(this,h,"HEADER_TEXT_DEFAULT_STYLE","#003D5B"));if(h!=D.r)return"h"==this.xi&&this.Hp()?((0,D.dv)(this,h,"HEADER_DRILL_TEXT_DEFAULT_STYLE","#003286"),h.setCursor("pointer"),c=new D.mc(this,this.getId(),D.r,this.Ig(),this.Ci()),c.c5(D.o),this.C.Ca().ha(h,c)):
h.ea(D.t),D.me.Yb(h,f,d,b)?h:D.r};D.cv=function(b,c,d,e,f){var g=new D.P(e);g.qb(b.C.Bm[f]);e=g.q("background-color");g=g.q("border-color");b.kZ&&"HEADER_BACKGROUND_STYLE"==f?(b=b.Fb(),d.ga(b),g=D.R.nF(g,b,0.5),c.ga(g)):(c.ga(g),d.ga(e))};D.dv=function(b,c,d,e){b.kZ&&"HEADER_TEXT_DEFAULT_STYLE"==d?c.ga((0,D.lv)(b)):c.ga(e);e=[];1>=(0,D.Tu)(b)&&b.Nd()&&e.push(new D.P("font-weight:bold;"));e.push(b.C.Bm[d]);b.Oba&&e.push(b.Oba);c.Ka((0,D.Fs)(e))};
D.Vu.prototype.Av=function(){this.Oe||(this.Oe=(0,D.jv)(this,this.D));D.Vu.n.Av.call(this)};D.Vu.prototype.Ep=function(){this.Rw!==D.o&&(0,D.iv)(this);D.Vu.n.Ep.call(this)};D.bv=function(b,c){c&&b.D.removeChild(c)};D.D=D.Vu.prototype;D.D.F9=function(){this.Rw=D.o;this.hc();var b=this.C,c=(0,D.qt)(b.Ca());c&&c.nf();b.kd.push(this);b.Ra(new D.mv(this.getId()));b.GP=D.o;b.hn(new D.L(0,0,b.Ob,b.Ab));b.GP=D.t;c=this.nb();b.HZ.j(c);(0,D.Wb)(b,this);(0,D.iv)(this)};
D.D.G9=function(){this.Rw=D.t;this.hc();var b=this.C,c=b.kd.pop(),d=(0,D.qt)(b.Ca());d&&d.nf();d=c.getId();b.SI=d;b.Ra(new D.mv);b.GP=D.o;b.hn(new D.L(0,0,b.Ob,b.Ab));b.GP=D.t;(0,D.Wb)(b,c);(0,D.iv)(this)};D.D.Ig=function(b,c,d){return b&&b instanceof D.Ae?D.r:D.Vu.n.Ig.call(this,b,c,d)};D.D.Ci=function(b){return b&&b instanceof D.Ae?D.r:D.Vu.n.Ci.call(this,b)};D.D.Gd=function(b){return b&&b instanceof D.Ae?this.Rw?this.C.Fd.restore:this.C.Fd.isolate:D.r};
D.Ru=function(){this.Init()};D.E.l(D.Ru,D.E,"DvtBaseTreemapLayout");D.Ru.prototype.Init=function(){this.sR=0};D.Ru.prototype.$n=(0,D.w)();D.Su=function(b,c,d,e,f,g,h){c.sR=b.sR;b.sR++;if(!h||!c.Nd()){b=b.Q2(c.C,(0,D.Tu)(c));h=window.Math.round(d+b);var k=window.Math.round(e+b);if(c=c.NL(h,k,window.Math.round(d+f-b)-h,window.Math.round(e+g-b)-k))return c}return new D.L(d,e,f,g)};D.Ru.prototype.Q2=function(b,c){var d=b.ota;return"o"==d?1==c&&2<=b.ep?3:0:"a"==d?c<b.ep?3:0:0};
D.Wu=function(){this.Init()};D.E.l(D.Wu,D.Ru,"DvtSquarifyingLayout");D.Wu.prototype.$n=function(b,c,d,e,f,g,h){this.ef(c,d,e,f,g,h?D.t:D.o)};D.Wu.prototype.ef=function(b,c,d,e,f,g){c=(0,D.Su)(this,b,c,d,e,f,g);b=b.fb();if(b!=D.r&&0<b.length){d=b;f=c.f*c.g;for(e=e=g=0;e<d.length;e++)g+=0<d[e].nc()?d[e].nc():0;f=0==f?0:f/g;for(e=0;e<d.length;e++)g=d[e],g.Ny=g.nc()*f;b=b.slice(0).sort(function(b,c){return b.nc()-c.nc()});d=window.Math.min(c.f,c.g);(0,D.nv)(this,b,d,new D.L(c.x,c.y,c.f,c.g))}};
D.nv=function(b,c,d,e){var f=[],g=window.Infinity;if(c==D.r||0==c.length)(0,D.ov)(b,f,d,e);else for(;0<c.length;){var h=c.pop();if(0>h.Ny){(0,D.ov)(b,f,d,e);break}f.push(h);var k,m=f,p=d,q=0;k=window.Infinity;for(var s=-window.Infinity,u=0;u<m.length;u++)q+=m[u].Ny,k=window.Math.min(k,m[u].Ny),s=window.Math.max(s,m[u].Ny);m=q*q;p*=p;k=window.Math.max(p*s/m,m/(p*k));if(k>g){c.push(h);f.pop();e=(0,D.ov)(b,f,d,e);(0,D.nv)(b,c,window.Math.min(e.f,e.g),e);break}else if(0==c.length){(0,D.ov)(b,f,d,e);break}else g=
k}};D.ov=function(b,c,d,e){var f=0,g;for(g=0;g<c.length;g++)f+=c[g].Ny;var h=e.x,k=e.y;if(d==e.f){f=0==d?0:f/d;for(g=0;g<c.length;g++)d=c[g].Ny/f,b.ef(c[g],h,k,d,f,D.t),h+=d;return new D.L(e.x,e.y+f,e.f,e.g-f)}d=0==d?0:f/d;for(g=0;g<c.length;g++)f=c[g].Ny/d,b.ef(c[g],h,k,d,f,D.t),k+=f;return new D.L(e.x+d,e.y,e.f-d,e.g)};
D.Qu=function(b){this.Init();this.rs=b};D.E.l(D.Qu,D.Ru,"DvtSliceAndDiceLayout");D.Qu.prototype.$n=function(b,c,d,e,f,g,h){this.ef(this.rs,b,c,d,e,f,g,h?D.t:D.o)};
D.Qu.prototype.ef=function(b,c,d,e,f,g,h,k){e=(0,D.Su)(this,d,e,f,g,h,k);d=d.fb();if(d!=D.r){f=e.x;g=e.y;h=e.f;k=e.g;var m=0,p;for(p=0;p<d.length;p++)m+=0<d[p].nc()?d[p].nc():0;"on"==this.aN&&(d=d.slice(0),d.sort(function(b,c){return c.nc()-b.nc()}));b&&D.I.N(c.e)&&(d=d.slice(0).reverse());for(p=0;p<d.length;p++){var q=d[p];if(!(0>=q.nc())){var s=q.nc()/m;b?h=e.f*s:k=e.g*s;this.ef(!b,c,q,f,g,h,k,D.t);b?f+=h:g+=k}}}};
D.mv=function(b){this.Init("treemapIsolate");this.za=b?b:D.r};(0,D.sa)("DvtTreemapIsolateEvent",D.mv);D.E.l(D.mv,D.fb,"DvtTreemapIsolateEvent");D.mv.TYPE="treemapIsolate";D.mv.prototype.getId=(0,D.B)("za");D.mv.prototype.getId=D.mv.prototype.getId;
D.Pb=function(b){this.Init(b)};D.E.l(D.Pb,D.ne,"DvtTreemapKeyboardHandler");D.Pb.prototype.Jp=function(b){var c=D.Pb.n.Jp.call(this,b);if(!c&&(b=b.keyCode,219==b||221==b))c=D.o;return c};
D.Qb=function(b,c,d,e){D.oe.call(this,b,c,d,e)};D.E.l(D.Qb,D.oe,"DvtTreemapEventManager");D.Qb.prototype.Eo=function(b){var c=D.o;if(13==b.keyCode&&b.ctrlKey){var d=(0,D.qt)(this);(0,D.fv)(d)&&(d.Rw?d.G9():d.F9());b.preventDefault()}else c=D.Qb.n.Eo.call(this,b);return c};D.Qb.prototype.b4=(0,D.ba)(D.t);
D.Zu=(0,D.w)();D.E.l(D.Zu,D.kp,"DvtTreemapBundle");D.Zu._defaults={COLOR:"Color",SIZE:"Size"};D.Zu.prototype.zy=function(b){return D.Zu._defaults[b]};D.Zu.prototype.yy=(0,D.ba)("DvtTreemapBundle");
D.Fb=function(){this.Init({skyros:D.Xu,alta:{}})};D.E.l(D.Fb,D.Yu,"DvtTreemapDefaults");D.Xu={nodeDefaults:{header:{labelStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;")}}};
D.$b=(0,D.A)("e");D.E.l(D.$b,D.pv,"DvtTreemapJsonUtils");D.D=D.$b.prototype;D.D.sM=(0,D.ba)("treemap");D.D.QG=function(b){var c=D.$b.n.QG.call(this,b),c=c+this.wa("irk",b.isolatedNode),d=b.groupGaps;"all"==d?c+=this.wa("gg","a"):"none"==d&&(c+=this.wa("gg","n"));d=b.layout;"sliceAndDiceHorizontal"==d?c+=this.wa("layout","h"):"sliceAndDiceVertical"==d&&(c+=this.wa("layout","v"));b=b.animationOnDisplay;return c="auto"==b?c+this.wa("adi","alphaFade"):c+this.wa("adi",b)};
D.D.RG=function(b,c){var d=D.$b.n.RG.call(this,b,c);if("off"==(c.labelDisplay?c.labelDisplay:b.nodeDefaults.labelDisplay))d+=this.wa("ld","o");var e=c.groupLabelDisplay?c.groupLabelDisplay:b.nodeDefaults.groupLabelDisplay;"node"==e?d+=this.wa("gld","n"):"off"==e&&(d+=this.wa("gld","o"));e=c.labelHalign?c.labelHalign:b.nodeDefaults.labelHalign;"start"==e?d+=this.wa("ha","s"):"end"==e&&(d+=this.wa("ha","e"));e=c.labelValign?c.labelValign:b.nodeDefaults.labelValign;"top"==e?d+=this.wa("va","t"):"bottom"==
e&&(d+=this.wa("va","b"));var e=c.header,d=d+this.wa("hls",e&&e.labelStyle?e.labelStyle:b.nodeDefaults.header.labelStyle),f=e&&e.labelHalign?e.labelHalign:b.nodeDefaults.header.labelHalign;"center"==f?d+=this.wa("hha","c"):"end"==f&&(d+=this.wa("hha","e"));if("off"==(e&&e.isolate?e.isolate:b.nodeDefaults.header.isolate))d+=this.wa("hi","off");if("on"==(e&&e.useNodeColor?e.useNodeColor:b.nodeDefaults.header.useNodeColor))d+=this.wa("unc","on");return d};
D.D.uW=function(b){var c,d=new D.Zu;c="\x3cresources"+this.wa("legendSize",(0,D.ct)(d,"SIZE"));c+=this.wa("legendColor",(0,D.ct)(d,"COLOR"));b=b._resources;d=D.I.N(this.e);c+=this.wa("maximizeUp",d&&b.isolateRtl?b.isolateRtl:b.isolate);c+=this.wa("maximizeDown",d&&b.isolateDownRtl?b.isolateDownRtl:b.isolateDown);c+=this.wa("maximizeOver",d&&b.isolateOverRtl?b.isolateOverRtl:b.isolateOver);c+=this.wa("restoreUp",d&&b.restoreRtl?b.restoreRtl:b.restore);c+=this.wa("restoreDown",d&&b.restoreDownRtl?b.restoreDownRtl:
b.restoreDown);c+=this.wa("restoreOver",d&&b.restoreOverRtl?b.restoreOverRtl:b.restoreOver);c+=this.wa("alta","true");return c+"/\x3e\n"};
D.D.SG=function(b){var c=D.$b.n.SG.call(this,b),d=b.animationUpdateColor;d&&(c+=this.wa("top","-tr-animation-update-color: "+d));(d=b.nodeDefaults.hoverColor)&&(c+=this.wa("node-hover","border-color: "+d));var d=b.nodeDefaults.selectedInnerColor,e=b.nodeDefaults.selectedOuterColor;(d=(d?"-tr-inner-color:"+d+";":"")+(e?"-tr-outer-color:"+e:""))&&(c+=this.wa("node-selected",d));d=b.nodeDefaults.header.backgroundColor;e=b.nodeDefaults.header.borderColor;(d=(d?"background-color:"+d+";":"")+(e?"border-color:"+
e:""))&&(c+=this.wa("nodeHeader",d));var e=b.nodeDefaults.header.hoverBackgroundColor,f=b.nodeDefaults.header.hoverInnerColor,d=b.nodeDefaults.header.hoverOuterColor,e=(e?"background-color:"+e+";":"")+(f?"-tr-inner-color:"+f+";":"");(e+=d?"-tr-outer-color:"+d:"")&&(c+=this.wa("nodeHeader-hover",e));d=b.nodeDefaults.header.selectedBackgroundColor;e=b.nodeDefaults.header.selectedInnerColor;b=b.nodeDefaults.header.selectedOuterColor;d=(d?"background-color:"+d+";":"")+(e?"-tr-inner-color:"+e+";":"");
(d+=b?"-tr-outer-color:"+b:"")&&(c+=this.wa("nodeHeader-selected",d));return c+"/\x3e\n"};
});