define(['./DvtToolkit', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Eb=(0,D.w)();D.E.l(D.Eb,D.Ha,"DvtBaseTreeView");D.D=D.Eb.prototype;D.D.Init=function(b,c,d){D.Eb.n.Init.call(this,b,c,d);this.pa=this.uU(this,b,this.Ra,this);this.pa.Re(this);this.Sj=new D.Ud(b);this.KY=new D.Vd(this);(0,D.$d)(this.pa,this.Sj);this.U8=new D.ae(this);this.xV=this.eb=D.r;this.Nba=D.t;this.SI=D.r};
D.D.H=function(b,c,d){this.Ob=c;this.Ab=d;this.pa&&this.pa.dc();this.cm&&!b&&(b=this.xV);b&&(this.xV=b);b&&(c=this.Ot(b),this.bG(c));d=new D.L(0,0,this.Ob,this.Ab);this.hn(d);c=new D.K(this.e);this.j(c);this.g1&&(this.WW=new D.be(this.e,this.pa),this.WW.XD=D.o);this.zk(c,d);this.cm&&(this.fU=D.o,this.cm.stop());var e=new D.L(0,0,this.Ob,this.Ab);d=D.t;if(this.ba){if(this.aM&&b)if(D.Ma.isSupported(this.aM))this.cm=D.Ma.Dx(this.e,this.aM,this.ba,c,e,this.EB),d=D.o;else if(this.$I){this.mi=this.TU();
this.j(this.mi);var e=new D.ce(this.e,this.mi),f=this.$I,g=this.Za,h=this.mQ,k=this.lw;e.iH=D.t;e.$I=f;e.mQ=h;(0,D.de)(k,f)||(0,D.de)(h,g)?(e.iH=D.o,h=(0,D.Hb)(f),k=(0,D.Hb)(g),h.push(f),k.push(g),(0,D.ee)(e,h,k)):(0,D.ee)(e,[f],[g]);this.cm=e.yp()}}else this.cm=this.VU(c,e);this.mQ=this.$I=D.r;this.cm&&(this.pa.ky(this),this.cm.gd(this.Co,this),this.cm.play());d?this.Nk=this.ba:this.ba&&this.removeChild(this.ba);this.ba=c;b?(this.PD(),(0,D.fe)(this,!this.cm)):this.dW()};D.D.Ot=(0,D.ba)(D.r);
D.D.hn=(0,D.w)();D.D.zk=(0,D.w)();D.D.RM=function(b){var c=new D.Ja(this.e,0,0,this.Ob,this.Ab);(0,D.Ka)(c);b.j(c)};D.Ib=function(b,c){if(b.lw&&0<b.lw.length){var d=b.Za?b.Za.uh():D.r;b.pq&&(0,D.ge)(b.pa,b.pq);b.pq=D.he.H(b,c,b.lw,d);(0,D.ie)(b.pa,b.pq)}else(0,D.ge)(b.pa,b.pq),b.pq=D.r};D.Jb=function(b,c){var d=D.r;if(b.Ica&&b.fX)for(var e=0;e<b.fX.length;e++){var f=b.fX[e];if(f.id==b.Ica){d=f.Ys;break}}if(b.Dfa||b.V$||d)b.eb=D.je.H(b,c,b.Fd.legendSize,b.Fd.legendColor,b.Dfa,b.V$,d)};
D.Nb=function(b,c){if(b.xz){var d=new D.le(b.e,b.xz,b.Ob/2,b.Ab/2);d.jf();d.Zd();D.me.Yb(d,b.Ob-4,b.Ab-4,b);c.j(d)}};D.Kb=function(b){return b.Za&&0<b.Za.nc()};D.D=D.Eb.prototype;D.D.VU=function(b,c){return D.Ma.isSupported(this.eU)?D.Ma.ZE(this.e,this.eU,b,c,this.EB):D.r};D.D.Co=function(){this.mi&&(this.removeChild(this.mi),this.mi=D.r);this.Nk&&(this.removeChild(this.Nk),this.Nk=D.r);this.fU=D.t;this.cm=D.r;this.pa.Re(this);(0,D.fe)(this,D.o)};D.D.TU=function(){return new D.K(this.e)};D.D.KB=function(b){return new D.ne(b)};
D.D.uU=function(b,c,d,e){return new D.oe(b,c,d,e)};D.D.I6=(0,D.aa)();D.D.Ca=(0,D.B)("pa");D.pe=function(b,c){var d=c,e=b.fb();if(e)for(var f=0;f<e.length;f++)var g=(0,D.pe)(e[f],c+1),d=window.Math.max(d,g);return d};
D.Eb.prototype.bG=function(b){this.$I=this.Za;this.mQ=this.lw;this.Mk=b.BCa;this.Fd=b.lka?b.lka:{};this.Za=b.root;this.xz=b.Wya;this.lw=b.Mxa;this.CFa=new D.qe(b.Mya,b.Nya);this.DFa=new D.re(b.Lya);this.eU=b.O1;this.aM=b.Pxa;this.EB=b.Nxa;this.aN=b.LDa;this.Bm=b.ODa;this.B_=b.Uja;b.r5&&(this.g1=b.r5);this.B_?(this.Db=new D.se(b.Uja),this.Mz=b.tDa):this.Db=D.r;this.pa.oy(this.Db);this.pa.JB=b.U1;this.Db?(0,D.Rc)(this.pa,this.KB(this.pa)):(0,D.Rc)(this.pa,D.r);this.Za&&(this.ep=(0,D.pe)(this.Za,0));
this.fX=b.Ys;this.Ica=b.hCa;this.Dfa=b.JDa;this.V$=b.eya};D.Eb.prototype.dW=function(){for(var b=this.Db?this.Db.getSelection():[],c=0;c<b.length;c++)b[c].Gb(D.o)};D.Eb.prototype.PD=function(){if(this.Db&&this.Mz){var b=[];(0,D.te)(this,this.Za,b);(0,D.ue)(this.Db,this.Mz,b);this.Mz=D.r}};D.fe=function(b,c){var d=D.r,e=b.SI;e&&(d=(0,D.ve)(b.Za,e),b.pa.mo(d));c&&(b.SI=D.r);d||(d=b.I6(b.Za),b.pa.mo(d));c&&b.no(b.NS())};D.Eb.prototype.no=function(b){this.Nba=b;this.pa.no(b)};D.Eb.prototype.NS=(0,D.B)("Nba");
D.te=function(b,c,d){if(c&&(d.push(c),c=c.fb()))for(var e=0;e<c.length;e++)(0,D.te)(b,c[e],d)};D.Eb.prototype.fC=function(b){return this.Db?b[0]:D.r};D.Eb.prototype.jw=function(b){b.ib()||(this.Db.ai(b,D.t),this.pa.Ml());b=[];for(var c=this.Db.getSelection(),d=0;d<c.length;d++)b.push(c[d].getId());return b};D.Eb.prototype.iw=function(){for(var b=[],c=this.Db.getSelection(),d=0;d<c.length;d++)b.push(c[d].MW());return b};
D.Eb.prototype.Mpa=function(b){b instanceof D.we?(0,D.xe)(this,b.getId(),D.t):this.Ra(b)};D.xe=function(b,c,d){d&&b.Za&&c==b.Za.getId()&&b.lw&&0<b.lw.length?(b.SI=c,b.Ra(new D.ob(b.lw[0].id))):d||b.Ra(new D.ob(c));b.e.Oc().dc()};D.Eb.prototype.$R=(0,D.B)("U8");D.Eb.prototype.kia=function(b){return(0,D.ye)(this.pa,b)};
D.Eb.prototype.Hi=function(b,c,d){return this.Sj.Hi(d)};D.Eb.prototype.mk=function(b,c){return this.Sj.mk(b,c)};

D.ce=function(b,c){this.Init(b,c)};D.E.l(D.ce,D.iu,"DvtBaseTreeAnimationHandler");D.de=function(b,c){if(!c||!b)return D.t;for(var d=0;d<b.length;d++)if(b[d].id==c.getId())return D.o;return D.t};
D.Vd=(0,D.A)("C");D.E.l(D.Vd,D.Gp,"DvtBaseTreeDropTarget");
D.oe=function(b,c,d,e){this.Init(c,d,e);this.C=b};D.E.l(D.oe,D.Bc,"DvtBaseTreeEventManager");D.D=D.oe.prototype;D.D.jn=function(b){D.oe.n.jn.call(this,b);var c=(0,D.ye)(this,b.target);c&&(b=b.shiftKey,c.Hp&&c.Hp()&&(0,D.xe)(this.C,c.getId(),b))};D.D.Zf=function(b){D.oe.n.Zf.call(this,b);b=(0,D.ye)(this,b.target);(0,D.AC)(this,b)};D.D.kn=function(b){D.oe.n.kn.call(this,b);(b=(0,D.ye)(this,b.target))&&b.Av&&b.Av()};
D.D.xj=function(b){D.oe.n.xj.call(this,b);var c=(0,D.ye)(this,b.target);c&&c.Ep&&(b=(0,D.ye)(this,b.relatedTarget),(b&&b.getId?b.getId():D.r)!=c.getId()&&c.Ep())};D.D.Eo=function(b){var c=D.t,c=(0,D.qt)(this);13==b.keyCode&&!b.ctrlKey?(c=(0,D.qt)(this),c.Hp&&c.Hp()&&(b.shiftKey&&(c=this.C.Za),(0,D.xe)(this.C,c.getId(),b.shiftKey)),b.preventDefault(),c=D.o):c=D.oe.n.Eo.call(this,b);return c};
D.D.Ht=function(b){b=(0,D.ye)(this,b.target);(0,D.AC)(this,b);this.MH&&this.MH!=b&&(this.MH.Ep(),this.MH=D.r);b&&b instanceof D.$u&&this.MH!=b&&(this.MH=b,b.Av())};D.D.Gy=function(b){(b=(0,D.ye)(this,b.target))&&b.Hp&&b.Hp()&&(0,D.xe)(this.C,b.getId(),D.t)};D.AC=function(b,c){c&&(c instanceof D.mc&&c.qw)&&(0,D.xe)(b.C,c.getId(),D.t)};
D.Uu=(0,D.w)();D.E.l(D.Uu,D.E,"DvtBaseTreeParser");D.D=D.Uu.prototype;D.D.Init=function(b){this.C=b;this.Ln=new D.Ek;this.s_=window.Infinity;this.l_=-window.Infinity};
D.D.parse=function(b){var c=this.Ln.parse(b);b=this.jl(c);var c=c.fb(),d;d=(0,D.JC)(c,"f");var e=d.length;if(0<e){for(var f,g,h={},k=0;k<e;k++)f=d[k],g=f.k("name"),h[g]=D.ui.sk(f);d=h}else d=D.r;b.r5=d;this.Mk=0;f=(0,D.JC)(c,"n");e=[];for(d=0;d<f.length;d++)(g=this.ND(f[d],b.r5))&&e.push(g);b.BCa=this.Mk;if(1==e.length)d=e[0];else{d=this.C;for(g=f=0;g<e.length;g++)f+=e[g].nc();d=this.em(d,{size:f,Vxa:D.o,bha:D.o});(0,D.IC)(d,e)}b.root=d;for(d=0;d<c.length;d++)if(e=c[d],f=b,e)if(g=e.getName(),"spb"==
g)e=this.e0(e,f),f.wka||(f.wka=[]),f.wka.push(e);else if("menus"==g)f.U1||(f.U1=new D.Us(this.C.e)),f.U1.add(e);else if("ag"==g){k=e;e=f;h=D.n;f=k.k("id");g=k.k("T");if("continuous"==k.k("t")){var h=k.k("minValue"),m=k.k("maxValue"),p=k.k("minLabel"),q=k.k("maxLabel"),k=k.k("ramp").split(";");h==D.r&&(h=this.s_);m==D.r&&(m=this.l_);h=new D.gh(h,m,p,q,k)}else{h=new D.ih;k=k.fb();for(m=0;m<k.length;m++){var s=k[m];s&&(p=s.k("g"),q=s.k("l"),s={color:s.k("c"),pattern:s.k("p")},h.add(p,q,s))}}e.Ys||(e.Ys=
[]);e.Ys.push({Ys:h,q5:g,id:f})}else if("styles"==g)f.ODa=this.f0(e,f);else if("a"==g){g=[];e=e.fb();for(h=0;h<e.length;h++)k=e[h].k("id"),m=e[h].k("l"),g.push({id:k,text:m});f.Mxa=g}else if("resources"==g){g={};e=e.getAttributes();for(h=0;h<e.length;h++)g[e[h].name]=e[h].value;f.lka=g}this.un(b.root,b);return b};D.D.em=(0,D.ba)(D.r);
D.D.jl=function(b){var c={},d=b.k("sel");c.Uja="none"==d?D.r:"single"==d?"s":"m";c.LDa=b.k("sort");if(d=b.k("selIds"))c.tDa=d.split(",");c.Wya=b.k("emptyText");c.hCa=b.k("ls");c.JDa=b.k("sv");c.eya=b.k("cv");if(d=b.k("adu"))c.Nxa=d/1E3;c.Pxa=b.k("adc");c.O1=b.k("adi");return c};
D.D.Pt=function(b){var c={};c.q5=b.k("T");c.xCa=b.k("M");c.DR=b.k("ag");c.id=b.k("id");c.size=(0,window.Number)(b.k("s"));c.color=b.k("c");c.pattern=b.k("p");c.label=b.k("l");c.QDa=b.k("tt");c.VS=b.k("ld");c.Kya=b.k("d");c.EBa=b.k("iip");c.bha="t"==b.k("di")?D.o:D.t;c.sDa=b.k("nsel");var d=b.k("tn");d&&(c.Bka=d);if(b=b.k("ls"))c.lt=new D.P(b);c.DR!=D.r&&(this.l_=window.Math.max(this.l_,c.DR),this.s_=window.Math.min(this.s_,c.DR));return c};
D.D.ND=function(b,c){if(!b||"n"!=b.getName())return D.r;this.Mk++;var d=this.Pt(b),d=this.em(this.C,d,c);(0,D.IC)(d,this.AQ(b,d,c));return d};D.D.AQ=function(b,c,d){var e=[];b=b.fb();for(var f=0;f<b.length;f++){var g=b[f];g&&("el"==g.getName()?d&&c.s8&&c.s8((0,D.gp)(g)):c.bb()&&e.push(this.ND(g,d)))}return e};D.D.e0=function(b,c){var d=(0,D.Zq)(b),e=b.k("T");c.XF||(c.XF={});c.XF[e]||(c.XF[e]=[]);c.XF[e].push(d)};
D.D.un=function(b,c){if(b){var d=b.Qn;if(c.XF){var e=c.XF[d];e&&b.k5(e)}if(c.Ys)for(var f=0;f<c.Ys.length;f++)if(e=c.Ys[f],e.q5==d){if(e.Ys instanceof D.gh&&(d=b,e=e.Ys.get(d.$pa)))d.Gf=e;break}if(d=b.fb())for(e=0;e<d.length;e++)this.un(d[e],c)}};D.JC=function(b,c){for(var d=[],e=0;e<b.length;e++){var f=b[e];f&&f.getName()==c&&d.push(f)}return d};
D.Uu.prototype.f0=function(b,c){var d={},e=new D.P(b.k("top"));d.BACKGROUND_STYLE=e;d.ANIMATION_UPDATE_COLOR_STYLE=e.q("-tr-animation-update-color");e=new D.P(b.k("node"));d.LABEL_TEXT_DEFAULT_STYLE=e;var f=e.clone().qb(new D.P(b.k("node-hover"))),g=e.clone().qb(new D.P(b.k("node-selected")));c.Mya=b.k("dsf");c.Lya=b.k("dsb");c.Nya=b.k("dso");this.NV(e,f,g,d);this.W7(b,d);e=new D.P(b.k("rootText"));d.TEXT_STYLE=e;e=new D.P(b.k("attrType"));d.ATTRIBUTE_TYPE_STYLE=e;e=new D.P(b.k("attrValue"));d.ATTRIBUTE_VALUE_STYLE=
e;e=new D.P(b.k("drillText"));d.DRILL_TEXT_STYLE=e;e=new D.P(b.k("currentText"));d.CURRENT_TEXT_STYLE=e;return d};D.Uu.prototype.NV=(0,D.w)();D.Uu.prototype.W7=(0,D.w)();
D.$u=(0,D.w)();D.E.l(D.$u,D.E,"DvtBaseTreeNode");D.rc=new D.vn("#000000",2,5,5,45,0.5);
D.$u.prototype.Init=function(b,c,d){this.C=b;this.Qn=c.q5;this.r_=c.xCa;this.$pa=c.DR;this.za=c.id;this.fj=c.size;this.Gf=c.color?c.color:"#000000";this.Nn=c.pattern;this.xx=c.label;this.Ew=c.QDa;this.us=c.lt;this.JC=c.Kya;this.If=c.bha;this.Qta=c.EBa;this.hX=c.Vxa;this.Rr=1;this.NP=D.r;this.vm=D.t;this.g1=d;c.Bka?(0,D.HC)(this,c.Bka):d&&d.content?(0,D.HC)(this,"content"):d&&d.rootContent&&(0,D.HC)(this,"rootContent");this.xG=D.t;this.VM=c.sDa};
D.IC=function(b,c){if(c!=D.r)for(var d=0;d<c.length;d++)c[d].ye=b;b.fe=c};D.$u.prototype.fb=(0,D.B)("fe");D.Hb=function(b){var c=[],d,e;if(!b.Nd())return c;for(var f=0;f<b.fe.length;f++)e=b.fe[f],d=(0,D.Hb)(e),c.push(e),c=c.concat(d);return c};D.gv=function(b){var c=b.ye;c&&(c.NP=b)};D.Ob=function(b,c){return!c||!b.ye?D.t:b.ye==c?D.o:(0,D.Ob)(b.ye,c)};D.hv=function(b,c,d){var e=[];if(0>d)return e;if(0==d)return[b];if(c.Nd()){b=c.fb();for(var f=0;f<b.length;f++)c=b[f],e=e.concat((0,D.hv)(c,c,d-1))}return e};
D.Tb=function(b){var c=[],d;if(!b.Nd())return[b];for(var e=0;e<b.fe.length;e++)d=b.fe[e],d=(0,D.Tb)(d),c=c.concat(d);return c};D.ve=function(b,c){if(b.getId()==c)return b;for(var d=D.r,e=b.fb(),f=e.length,d=D.r,g=0;g<f;g++)if(d=e[g],d=(0,D.ve)(d,c))return d;return D.r};D.D=D.$u.prototype;D.D.getId=(0,D.B)("za");D.D.nc=(0,D.B)("fj");D.D.Fb=(0,D.B)("Gf");D.D.Ig=(0,D.B)("Ew");D.D.Ci=(0,D.B)("Gf");D.D.U=(0,D.B)("Rr");D.D.u=function(b){this.Rr=b;this.D&&this.D.u(this.Rr)};D.D.bb=(0,D.B)("If");
D.D.Hp=function(){return"r"==this.JC||"ir"==this.JC};D.D.k5=(0,D.A)("xd");D.D.od=(0,D.B)("xd");D.D.sv=(0,D.B)("r_");D.D.H=(0,D.w)();D.D.wt=function(b){var c=this.fb();if(c!=D.r)for(var d=0;d<c.length;d++)c[d].H(b)};D.D.Di=function(){(0,D.gv)(this);return this};D.D.Jg=function(){return new D.L(0,0,0,0)};D.D.el=function(){this.wc();this.Av&&this.Av();this.vm=D.o};D.D.nf=function(){this.bl()&&this.hc();this.Ep&&this.Ep();this.vm=D.t};D.D.bl=(0,D.B)("vm");D.D.Av=function(){this.xG=D.o};
D.D.Ep=function(){this.xG=D.t};D.D.ic=(0,D.ba)(D.o);D.D.ib=(0,D.B)("ed");D.D.Gb=(0,D.A)("ed");D.D.wc=(0,D.w)();D.D.hc=(0,D.w)();D.D.Hi=function(b){return this.C.fC(b)};D.D.mk=function(){return this.C.jw(this)};D.D.NA=function(){return this.C.iw()};D.D.MW=(0,D.B)("D");D.D.UA=(0,D.ba)(D.r);D.D.contains=(0,D.ba)(D.t);D.D.xk=function(){return[]};D.D.nn=(0,D.w)();
D.D.kf=function(b,c){b.iH||(0,D.ee)(b,c.fb(),this.fb());var d=c.xk(),e=this.xk(),f;if(!D.Nd.Uh(d,e)&&(f=new D.Da(this.C.e,this,this.C.EB),(0,D.G)(f.M,"typeNumberArray",this,this.xk,this.nn,e),b.add(f,1),e=this.fj!=c.fj,f=D.R.BS(this.Gf)!=D.R.BS(c.Gf),this.nn(d),(d=(0,D.ev)(this,D.r,"ANIMATION_UPDATE_COLOR_STYLE"))&&(e||f)))this.Gf=d};D.D.ig=function(b){if(!b.iH||!b.iH||!(b.$I.getId()==this.getId()||(0,D.de)(b.mQ,this))){this.u(0);var c=new D.Aq(this.C.e,this,this.C.EB);b.add(c,2);for(c=0;c<this.fe.length;c++)this.fe[c].ig(b)}};
D.D.sh=function(b,c){c.j(this.D);var d=new D.xq(this.C.e,this,this.C.EB);b.add(d,0);if(!b.iH)for(d=0;d<this.fe.length;d++)this.fe[d].sh(b,c)};D.D.Nd=function(){return this.fe!=D.r&&0<this.fe.length};D.Tu=function(b){var c=0;for(b=b.ye;b;)c++,b=b.ye;return c};D.$u.prototype.MB=function(){return this.Nn?new D.cf(this.Nn,this.Gf):new D.qe(this.Gf)};D.lv=function(b){if(b.Nn)return"#000000";var c=b.Gf;b=D.R.Nc(c);var d=D.R.Mc(c),c=D.R.Lc(c);return 128<=(299*b+587*d+114*c)/1E3?"#000000":"#FFFFFF"};
D.kv=function(b,c){var d=(0,D.lv)(b);c.ga(d);d=[];d.push(b.C.Bm.LABEL_TEXT_DEFAULT_STYLE);b.us&&d.push(b.us);c.Ka((0,D.Fs)(d))};D.ev=function(b,c,d){(b=b.C.Bm[d])&&(c=b);return c};D.av=function(b){var c=11;(b=b.C.Bm.LABEL_TEXT_DEFAULT_STYLE.YE())&&(c=(0,window.parseFloat)(b));return c};D.$u.prototype.nb=(0,D.B)("D");D.$u.prototype.uh=(0,D.B)("xx");D.$u.prototype.s8=function(b){b&&!this.VJ&&(0,D.HC)(this,"content");this.Bg=b};D.HC=function(b,c){c&&(b.VJ=b.g1[c])};D.$u.prototype.lg=function(){return this.Hp()};
D.mc=function(b,c,d,e,f){this.Init(d,e,f);this.wb=b;this.za=c;this.qw=D.t};D.E.l(D.mc,D.Ec,"DvtBaseTreePeer");D.mc.prototype.getId=(0,D.B)("za");D.mc.prototype.nja=(0,D.B)("qw");D.mc.prototype.c5=(0,D.A)("qw");D.mc.prototype.Ep=function(){this.wb&&this.wb.Ep&&this.wb.Ep()};
D.he=(0,D.w)();D.E.l(D.he,D.E,"DvtTreeBreadcrumbsRenderer");D.he.koa=6;D.he.voa="color: #003286;";
D.he.H=function(b,c,d,e){var f=b.e,g=[];g.push(b.Bm.TEXT_STYLE);g.push(new D.P(D.he.voa));g.push(b.Bm.DRILL_TEXT_STYLE);var g=(0,D.Fs)(g).toString(),h=g+"text-decoration: underline;",k=[];k.push(b.Bm.TEXT_STYLE);k.push(b.Bm.CURRENT_TEXT_STYLE);k=(0,D.Fs)(k).toString();f=new D.$g(f,b.Mpa,b,{lt:g,i4:h,h4:h,aha:k});b.j(f);d=d.slice(0).reverse();d.push({text:e});f.H({items:d},c.f);e=f.v();(0,D.nc)(f,c.x,c.y);e=e.g+D.he.koa;c.y+=e;c.g-=e;b.removeChild(f);return f};
D.je=(0,D.w)();D.E.l(D.je,D.E,"DvtTreeLegendRenderer");D.je.Doa=4;D.je.Or=7;D.je.kN=24;D.je.Coa=11;D.je.k9="#636363";D.je.HEa="color:"+D.je.k9+";";
D.je.H=function(b,c,d,e,f,g,h){var k=b.e,m=b.Ca(),p=new D.K(k);b.j(p);var q=D.je.wJ(k,b,p,c.f,d,e,f,g,h),s=b.Fd.alta?D.r:"#000000",u=[];u.push(b.Bm.TEXT_STYLE);var u={borderColor:s,lt:(0,D.Fs)(u)},s=D.yC.J4(k,m,p,c.f,c.g,h,u),v=q?q.v():D.r,z=s?s.v():D.r;if(q&&!s)q.F(c.y+(c.f-v.f)/2);else if(s&&!q)s.F(c.y+(c.f-z.f)/2);else if(s&&q){var C=c.f-D.je.kN;v.f+z.f>C&&(v.f>C/2&&z.f>C/2?(p.removeChild(q),p.removeChild(s),q=D.je.wJ(k,b,p,C/2,d,e,f,g,h),s=D.yC.J4(k,m,p,C/2,c.g,h,u)):v.f>z.f?(m=C-z.f,p.removeChild(q),
q=D.je.wJ(k,b,p,m,d,e,f,g,h)):(d=C-v.f,p.removeChild(s),s=D.yC.J4(k,m,p,d,c.g,h,u)),v=q.v(),z=s.v());D.I.N(k)?(s.F(c.x),q.F(c.x+c.f-v.f)):(q.F(c.x),s.F(c.x+c.f-z.f))}h=p.v();p.R(c.y+c.g-h.g);c.g-=h.g+D.je.Doa;b.removeChild(p);return p};
D.je.wJ=function(b,c,d,e,f,g,h,k){var m=D.I.N(b),p=c.Ca(),q=D.r;if(h||k){q=new D.K(b);d.j(q);var s=[];s.push(c.Bm.TEXT_STYLE);s.push(c.Bm.ATTRIBUTE_TYPE_STYLE);d=(0,D.Fs)(s);s=[];s.push(c.Bm.TEXT_STYLE);s.push(c.Bm.ATTRIBUTE_VALUE_STYLE);var s=(0,D.Fs)(s),u,v,z,C;c=0;h&&(u=new D.le(b,f,0,0),u.Ka(d),q.j(u),z=u.Lb().f,v=new D.le(b,h,0,0),v.Ka(s),q.j(v),C=v.Lb().f,c=z+C+D.je.Or);var F,H,J,M;f=0;k&&(F=new D.le(b,g,0,0),F.Ka(d),q.j(F),J=F.Lb().f,H=new D.le(b,k,0,0),H.Ka(s),q.j(H),M=H.Lb().f,f=J+M+D.je.Or);
e-=D.je.kN;c+f>e&&(b=e/2,c>b&&f>b?(D.me.Yb(v,b-z-D.je.Or,window.Infinity,q)?(C=v.Lb().f,p.ha(v,new D.Ec(h))):(q.removeChild(u),q.removeChild(v),v=D.r,C=0),D.me.Yb(H,b-J-D.je.Or,window.Infinity,q)?(M=H.Lb().f,p.ha(H,new D.Ec(k))):(q.removeChild(F),q.removeChild(H),H=D.r,M=0)):c>f?D.me.Yb(v,e-f-z-D.je.Or,window.Infinity,q)?(C=v.Lb().f,p.ha(v,new D.Ec(h))):(q.removeChild(u),q.removeChild(v),v=D.r,C=0):D.me.Yb(H,e-c-J-D.je.Or,window.Infinity,q)?(M=H.Lb().f,p.ha(H,new D.Ec(k))):(q.removeChild(F),q.removeChild(H),
H=D.r,M=0));e=0;m?(H&&(H.aa(e),e+=M+D.je.Or,F.aa(e),e+=J+D.je.kN),v&&(v.aa(e),e+=C+D.je.Or,u.aa(e))):(v&&(u.aa(e),e+=z+D.je.Or,v.aa(e),e+=C+D.je.kN),H&&(F.aa(e),e+=J+D.je.Or,H.aa(e)))}return q};
D.ne=function(b){this.Init(b)};D.E.l(D.ne,D.nt,"DvtBaseTreeKeyboardHandler");D.ne.prototype.jL=function(b){return this.Jp(b)&&!b.ctrlKey};D.ne.prototype.rF=function(b){return 32==b.keyCode&&b.ctrlKey};
D.Yu=(0,D.w)();D.E.l(D.Yu,D.tr,"DvtBaseTreeDefaults");D.EC={skin:"skyros",emptyText:"No data to display",nodeDefaults:{labelStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px;")},styleDefaults:{_attributeTypeTextStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;font-weight:bold;color:#4F4F4F"),_attributeValueTextStyle:new D.P("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;")},_resources:{}};
D.Yu.prototype.Init=function(b){b={skyros:D.Ic.qb(b.skyros,D.EC),alta:D.Ic.qb(b.alta,{})};D.Yu.n.Init.call(this,b)};
D.pv=(0,D.w)();D.E.l(D.pv,D.E,"DvtBaseTreeJsonUtils");
D.pv.prototype.YT=function(b){var c;c="\x3c"+this.sM();c+=this.QG(b);c+="\x3e\n";if(b&&b.nodes)for(var d=b.nodes,e=0;e<d.length;e++)c+=(0,D.zC)(this,b,d[e]);d="\x3ca/\x3e\n"+this.uW(b);d+=this.SG(b);if(e=b.attributeGroups?b.attributeGroups[0]:D.r)if(b='\x3cag id\x3d"'+e.id+'"',"continuous"==e.attributeType)b+=this.wa("t","continuous"),b+=this.wa("ramp",e.colors.join(";")),b+=this.wa("minValue",e.min),b+=this.wa("maxValue",e.max),b+=this.wa("minLabel",e.minLabel),b+=this.wa("maxLabel",e.maxLabel),
b+="/\x3e";else{b+="\x3e\n";for(var e=e.groups,f=0;f<e.length;f++)b+="\x3ci",b+=this.wa("g",e[f].id),b+=this.wa("l",e[f].label),b+=this.wa("c",e[f].color),b+=this.wa("p",e[f].pattern),b+="/\x3e\n";b+="\x3c/ag\x3e\n"}else b="";d=d+b+("\x3c/"+this.sM()+"\x3e");return c+=d};D.pv.prototype.wa=function(b,c){return c!=D.r?" "+b+'\x3d"'+c+'"':""};D.pv.prototype.sM=(0,D.ba)(D.r);
D.pv.prototype.QG=function(b){var c;c=""+this.wa("sv",b.sizeLabel);c+=this.wa("cv",b.colorLabel);var d=b.attributeGroups?b.attributeGroups[0]:D.r;d&&(c+=this.wa("ls",d.id));for(var d=b.selectedNodes?b.selectedNodes:[],e="",f=0;f<d.length;f++)0<e.length&&(e+=","),e+=d[f];0<e.length&&(c+=this.wa("selIds",e));c+=this.wa("adu",b.animationDuration);c+=this.wa("adc",b.animationOnDataChange);c+=this.wa("emptyText",b.emptyText);c+=this.wa("sel",b.selection);return c+=this.wa("sort",b.sorting)};
D.zC=function(b,c,d){var e;e="\x3cn"+b.RG(c,d);if(d&&d.nodes&&0<d.nodes.length){e+=b.wa("di","t");e+="\x3e\n";d=d.nodes;for(var f=0;f<d.length;f++)e+=(0,D.zC)(b,c,d[f]);e+="\x3c/n\x3e\n"}else e+="/\x3e\n";return e};
D.pv.prototype.RG=function(b,c){var d;d=""+this.wa("id",c.id);d+=this.wa("s",c.value);d+=this.wa("c",c.color);d+=this.wa("l",c.label);d+=this.wa("p",c.pattern);d+=this.wa("tt",c.shortDesc?c.shortDesc:c.tooltip);d+=this.wa("ls",c.labelStyle?c.labelStyle:b.nodeDefaults.labelStyle);var e=c.drilling?c.drilling:b.nodeDefaults.drilling;"insert"==e?d+=this.wa("d","i"):"replace"==e?d+=this.wa("d","r"):"insertAndReplace"==e&&(d+=this.wa("d","ir"));return d+=this.wa("nsel",c.selectable?c.selectable:"auto")};
D.pv.prototype.uW=(0,D.w)();D.pv.prototype.SG=function(b){var c;c="\x3cstyles "+this.wa("attrType",b.styleDefaults._attributeTypeTextStyle);return c+=this.wa("attrValue",b.styleDefaults._attributeValueTextStyle)};
D.ae=function(b){this.$a(b)};D.E.l(D.ae,D.E,"DvtTreeAutomation");D.ae.prototype.$a=(0,D.A)("gga");D.ae.prototype.click=function(b){this.G4(b,0)};
D.ae.prototype.G4=function(b,c){c===D.n&&(c=-1);if(b==D.r)return D.r;var d;if(-1!=c){if(0==c){var e=(0,D.FC)(b);e&&"node"==e[0]&&(e=(0,D.GC)(this.gga.Za,e,1))&&(0,D.jk)(e.nb(),D.ed)}}else if((e=(0,D.FC)(b))&&"node"==e[0]){var f=e.length-1,g=e[f];0<=g.indexOf("#")&&(e[f]=D.r,(e=(0,D.GC)(this.gga.Za,e,1))&&("#label"==g?d=e.uh():"#size"==g?d=e.nc():"#color"==g?d=e.Fb():"#tooltip"==g&&(d=e.Ig())))}return d};
D.GC=function(b,c,d){var e=D.r;if(b.Qta==c[d])if(c[d+1]==D.r)e=b;else if(b=b.fb())for(var f=0;f<b.length&&!(e=(0,D.GC)(b[f],c,d+1));f++);return e};D.FC=function(b){b=b.split("[");var c;c=D.r;if(b&&0<=b.length){var d=b.length-1,e=b[d],f=e.indexOf("#");0<f&&(b[d]=e.substr(0,f),c=e.substr(f))}d=b.length;for(e=1;e<d;e++)f=b[e],f=f.substr(0,f.length-1),window.tempIdAsNumber=(0,window.parseFloat)(f),f=(0,window.isNaN)(window.tempIdAsNumber)?f:window.tempIdAsNumber,b[e]=f;c&&(b[d]=c);return b};
});