define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.ib=function(b,c){this.Init(c===D.t?"sunburstRotationInput":"sunburstRotation");this.yc=b};(0,D.sa)("DvtSunburstRotationEvent",D.ib);D.E.l(D.ib,D.fb,"DvtSunburstRotationEvent");D.ib.TYPE="sunburstRotation";D.ib.TYPE_INPUT="sunburstRotationInput";D.ib.prototype.Jia=(0,D.B)("yc");D.ib.prototype.getStartAngle=D.ib.prototype.Jia;
D.gc=function(b,c,d){this.Init(b,c,d)};D.E.l(D.gc,D.Eb,"DvtBaseSunburst");D.D=D.gc.prototype;D.D.Init=function(b,c,d){D.gc.n.Init.call(this,b,c,d);this.Fe=new D.hc;this.Rc=2*window.Math.PI};D.D.Ot=function(b){return(new D.ic(this)).parse(b)};D.D.bG=function(b){D.gc.n.bG.call(this,b);this.gfa=b.rotation;this.ffa=D.I.zd()?"url("+this.Fd.cursorRotate+"), auto":"url("+this.Fd.cursorRotate+") 8 8, auto";this.yc=(360-b.XT)*D.jc/360;this.yc>window.Math.PI&&(this.yc-=D.jc)};
D.D.hn=function(b){var c=window.Math.max(window.Math.ceil(3*window.Math.min(b.f,b.g)/400),2);b.x+=c;b.y+=c;b.f-=2*c;b.g-=2*c;(0,D.Ib)(this,b);(0,D.Jb)(this,b);this.bga=window.Math.floor(window.Math.min(b.f,b.g)/2);this.Za&&D.kc.$n(this.bga,this.Za,this.yc,this.Rc,this.aN)};
D.D.zk=function(b,c){this.RM(b,"");this.pq&&b.j(this.pq);this.eb&&(b.j(this.eb),this.eb=D.r);this.AE=new D.N(c.x+c.f/2,c.y+c.g/2);if("on"==this.gfa&&(0,D.Kb)(this)){var d=D.I.$()?60:15,d=new D.lc(this.e,c.x+c.f/2,c.y+c.g/2,this.bga+d);(0,D.Ka)(d);d.setCursor(this.ffa);b.j(d);this.Ca().ha(d,new D.mc(D.r,"_rotationShape"))}d=new D.K(this.e);(0,D.nc)(d,this.AE.x,this.AE.y);b.j(d);if((0,D.Kb)(this)){var e=new D.K(this.e);d.j(e);this.Za.H(e);this.Os=new D.K(this.e);d.j(this.Os);this.Uba=new D.K(this.e);
d.j(this.Uba)}else(0,D.Nb)(this,b)};D.D.uU=function(b,c,d,e){return new D.oc(b,c,d,e)};D.D.VU=function(b,c){if("fan"===this.eU&&(0,D.Kb)(this)){this.O9(0);var d=new D.Da(this.e,this,this.EB);(0,D.G)(d.M,"typeNumber",this,this.Asa,this.O9,2*window.Math.PI);return d}return D.gc.n.VU.call(this,b,c)};D.D.TU=function(){var b=D.gc.n.TU.call(this);b&&(0,D.nc)(b,this.AE.x,this.AE.y);return b};
D.D.Co=function(){if(!this.fU){this.ba.bi();var b=new D.L(0,0,this.Ob,this.Ab);this.hn(b);this.zk(this.ba,b);for(var b=this.Db?this.Db.getSelection():[],c=0;c<b.length;c++)b[c].Gb(D.o)}D.gc.n.Co.call(this)};D.D.oN=function(b){this.Os.j(b);D.I.Qm()||((0,D.pc)(this.Os),(0,D.qc)(this.Os,D.rc))};D.D.Asa=(0,D.B)("Rc");D.D.O9=function(b){this.Rc=b;this.hn(new D.L(0,0,this.Ob,this.Ab));this.Za&&(0,D.sc)(this.Za,D.o)};
D.tc=function(b,c){b.lY=c;b.ZD=new D.Ja(b.e,0,0,b.Ob,b.Ab);(0,D.Ka)(b.ZD);b.ZD.setCursor(b.ffa);b.j(b.ZD);b.Ca().ha(b.ZD,new D.mc(D.r,"_rotationShape"))};D.uc=function(b,c){var d=c-b.lY;b.lY=c;b.yc+=d;b.yc<-window.Math.PI?b.yc+=2*window.Math.PI:b.yc>window.Math.PI&&(b.yc-=2*window.Math.PI);b.hn(new D.L(0,0,b.Ob,b.Ab));b.Za&&(0,D.sc)(b.Za,D.o);b.Ra(new D.ib(360-window.Math.round(180*b.yc/window.Math.PI),D.t))};
D.vc=function(b){b.lY=D.r;b.removeChild(b.ZD);b.ZD=D.r;var c=360-window.Math.round(180*b.yc/window.Math.PI);b.Ra(new D.ib(c,D.t));b.Ra(new D.ib(c,D.o))};D.wc=function(b,c,d){return window.Math.atan2(d-b.AE.y,c-b.AE.x)};
D.xc=(0,D.w)();(0,D.sa)("DvtSunburst",D.xc);D.E.l(D.xc,D.gc,"DvtSunburst");D.xc.newInstance=function(b,c,d){var e=new D.xc;e.Init(b,c,d);return e};D.xc.getDefaults=function(b){return(0,D.Yb)(new D.hc,b)};D.xc.prototype.H=function(b,c,d){b?(this.S=this.Fe.Gg(b),D.I.Zh()||(this.S.animationOnDisplay="none",this.S.animationOnDataChange="none")):this.S||(this.S=(0,D.Zb)(this));b=(new D.yc).YT(this.S);D.xc.n.H.call(this,b,c,d)};D.xc.prototype.render=D.xc.prototype.H;
D.ic=function(b){this.Init(b)};D.E.l(D.ic,D.Uu,"DvtSunburstParser");D.ic.prototype.em=function(b,c,d){return new D.BB(b,c,d)};D.ic.prototype.jl=function(b){var c=D.ic.n.jl.call(this,b);c.rotation=b.k("r");c.XT=b.k("sa");if(c.XT===D.r||(0,window.isNaN)(c.XT))c.XT=90;return c};D.ic.prototype.Pt=function(b){var c=D.ic.n.Pt.call(this,b);c.WS=b.k("ha");c.ZCa=b.k("r");return c};
D.ic.prototype.NV=function(b,c,d,e){e.NODE_DEFAULT_COLOR_STYLE=b.q("border-color");e.NODE_HOVER_COLOR_STYLE=c.q("border-color");e.NODE_SELECTED_INNER_COLOR_STYLE=d.q("-tr-inner-color");e.NODE_SELECTED_OUTER_COLOR_STYLE=d.q("-tr-outer-color")};
D.BB=function(b,c,d){this.Init(b,c,d);this.En=c.VS?c.VS:"auto";this.hD=c.WS;this.cj=c.ZCa};D.E.l(D.BB,D.$u,"DvtSunburstNode");D.jc=2*window.Math.PI;D.D=D.BB.prototype;
D.D.H=function(b){if(this.Du){this.iQ=b;this.D=this.hY();b.j(this.D);var c=this.VJ;if(!this.ye&&(0==this.nh&&this.Rc==D.jc)&&c){var d=window.Math.sqrt(2),e=this.Vg*d-4;this.Wa=-this.Vg/d+2;this.Da=-this.Vg/d+2;d=this.C.WW;d.Jk=this.Bg;0<e&&0<e&&((0,D.pl)(d,e),(0,D.ql)(d,e),d.Af((0,D.av)(this)),this.WX=c=D.ui.nB(d,c,this.D),d=c.v(),(0,D.nc)(c,this.Wa+(e-d.f)/2,this.Da+(e-d.g)/2))}else this.Ua=this.LH(this.D),this.Ua!=D.r&&(this.D.j(this.Ua),this.Nn&&(d=this.Ua.Lb(),this.Rn=new D.Ja(this.C.e,d.x,d.y,
d.f,d.g),this.Rn.ga("#FFFFFF"),this.Rn.ea(D.t),this.D.j(this.Rn),e=this.Ua.ja(),(0,D.In)(e)||this.Rn.na(e),this.D.j(this.Ua)));(0,D.Na)(this.D);(0,D.Oa)(this.D,"label",this.Ew);this.wt(b)}};D.D.Gb=function(b){"off"!=this.VM&&(D.BB.n.Gb.call(this,b),this.ib()?(this.D.Gb(D.o),this.C.oN(this.D)):(this.D.Gb(D.t),this.iQ&&this.iQ.j(this.D)))};D.D.wc=function(){this.D&&this.Du&&(this.D.wc(),this.ib()?this.C.oN(this.D):this.C.Uba.j(this.D))};
D.D.hc=function(){this.D&&(this.Du&&!this.bl())&&(this.D.hc(),!this.ib()&&this.iQ&&this.iQ.j(this.D))};
D.D.Di=function(b){var c,d,e,f;if(b.type==D.ed)return D.BB.n.Di.call(this,b);c=b.keyCode;if(32==c&&b.ctrlKey)return this;for(f=this;f.ye;)f=f.ye;d=(0,D.hv)(this,f,(0,D.Tu)(this));a:{for(e=0;e<d.length;e++)if(this===d[e])break a;e=-1}var g=this.yc+this.Rc/2,g=(0,D.CB)(g);switch(c){case 38:if(this===f||180<g){if(c=this.NP)if(d=c.yc+c.Rc/2,d=(0,D.CB)(d),180<d)return c;b=(0,D.ut)(this,b,(0,D.Hb)(this))}else b=(0,D.DB)(this);break;case 40:if(this===f||0<=g&&180>=g){if(c=this.NP)if(d=c.yc+c.Rc/2,d=(0,D.CB)(d),
0<=d&&180>=d)return c;b=(0,D.ut)(this,b,(0,D.Hb)(this))}else b=(0,D.DB)(this);break;case 37:b=1==d.length?this:0==e?d[d.length-1]:d[e-1];break;case 39:b=1==d.length?this:e==d.length-1?d[0]:d[e+1];break;default:b=this}(0,D.gv)(b);return b};D.DB=function(b){var c=b.ye;c&&(b=c,(0,D.gv)(c));(0,D.gv)(b);return b};D.CB=function(b){b=D.Ga.H4(b);0>b?b+=360:360<b&&(b-=360);return b};D.D=D.BB.prototype;
D.D.Jg=function(){if(this.D){var b=this.D.v(),c=new D.N(b.x,b.y),c=(0,D.Yg)(this.D,c);b.x=c.x;b.y=c.y;return b}return new D.L(0,0,0,0)};D.D.fS=function(){return(0,D.Yg)(this.D,(0,D.EB)(0.5*(this.Vg+this.nh),this.yc+this.Rc/2))};D.D.NL=function(b,c,d,e){this.nh=b;this.Vg=c;this.yc=d;this.Rc=e;this.Du=D.o};D.D.MB=function(){return this.hX?(0,D.co)():D.BB.n.MB.call(this)};D.D.xk=function(){var b=D.R.Nc(this.Gf),c=D.R.Mc(this.Gf),d=D.R.Lc(this.Gf);return[this.nh,this.Vg,this.yc,this.Rc,b,c,d]};
D.D.nn=function(b){this.NL(b[0],b[1],b[2],b[3]);this.Gf=D.R.Fv(window.Math.round(b[4]),window.Math.round(b[5]),window.Math.round(b[6]));(0,D.sc)(this,D.t)};D.D.kf=function(b,c){c.Du&&0<c.Rc?D.BB.n.kf.call(this,b,c):this.ig(b)};D.D.contains=function(b,c){var d=(0,D.FB)(b,c);return window.Math.sqrt(b*b+c*c)>=this.nh&&window.Math.sqrt(b*b+c*c)<=this.Vg&&(0,D.GB)(this,d)};D.GB=function(b,c){for(;c<b.yc;)c+=D.jc;for(;c-b.yc>D.jc;)c-=D.jc;return c>=b.yc&&c<=b.yc+b.Rc};
D.EB=function(b,c){return{x:window.Math.cos(c)*b,y:window.Math.sin(c)*b}};D.FB=function(b,c){var d=window.Math.atan2(c,b);0>d?d+=D.jc:d>D.jc&&(d-=D.jc);return d};
D.BB.prototype.hY=function(){if(!this.Rc||0>=this.Rc)return D.r;var b=(0,D.HB)(this),b=new D.ad(this.C.e,b);this.C.Ca().ha(b,this);b.u(this.U());b.B(this.MB());var c=(0,D.ev)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR_STYLE"),d=(0,D.ev)(this,"#000000","NODE_SELECTED_OUTER_COLOR_STYLE"),e=(0,D.ev)(this,"#FFFFFF","NODE_HOVER_COLOR_STYLE");b.Q(new D.re((0,D.ev)(this,"#FFFFFF","NODE_DEFAULT_COLOR_STYLE"),0.3));b.Qp(new D.re(e,1,3));b.Tp(new D.re(c,1,1.5),new D.re(d,1,3.5));b.Ct(new D.re(e,1,3));b.di(this.C.B_!=
D.r&&"off"!=this.VM);this.hX&&(b.u(0.001),b.ea(D.t));return b};
D.HB=function(b){var c,d,e,f;b.Rc<D.jc?(c=(0,D.EB)(b.Vg,b.yc),d=(0,D.EB)(b.Vg,b.yc+b.Rc),e=(0,D.EB)(b.nh,b.yc+b.Rc),f=(0,D.EB)(b.nh,b.yc),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.Vg,b.Vg,b.Rc,1,d.x,d.y)+window.DvtPathUtils.lineTo(e.x,e.y)+window.DvtPathUtils.arcTo(b.nh,b.nh,b.Rc,0,f.x,f.y)+window.DvtPathUtils.closePath()):(c=(0,D.EB)(b.Vg,b.yc),d=(0,D.EB)(b.Vg,b.yc+b.Rc/2),e=(0,D.EB)(b.nh,b.yc),f=(0,D.EB)(b.nh,b.yc+b.Rc/2),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.Vg,
b.Vg,b.Rc/2,1,d.x,d.y)+window.DvtPathUtils.arcTo(b.Vg,b.Vg,b.Rc/2,1,c.x,c.y),0<b.nh&&(c+=window.DvtPathUtils.moveTo(f.x,f.y)+window.DvtPathUtils.arcTo(b.nh,b.nh,b.Rc/2,0,e.x,e.y)+window.DvtPathUtils.arcTo(b.nh,b.nh,b.Rc/2,0,f.x,f.y)),c+=window.DvtPathUtils.closePath());return c};
D.BB.prototype.LH=function(b){if(!this.xx||!b||!this.En||"off"==this.En)return D.r;var c=D.t;"auto"==this.En?c=!D.I.zd()&&D.I.lAa()==D.I.I8?D.t:D.o:"rotated"==this.En&&(c=D.o);if(c&&this.Rc<2*window.Math.PI){var d=window.Math.max(this.nh,10),e=this.Vg-d-6,f=1.1*this.Rc*(d+6);if(6>=f)b=D.r;else if(c=new D.le(this.C.e,this.xx,0,0),c.Af((0,D.av)(this)),(0,D.kv)(this,c),D.me.Yb(c,e,f,b)){e=(d+this.Vg)/2;if("s"==this.hD||"e"==this.hD)b.j(c),b=c.v().f,"s"==this.hD?e=d+4.5+b/2:"e"==this.hD&&(e=d-4.5-b/2);
b=(0,D.EB)(e,this.yc+this.Rc/2);c.jf();c.Zd();d=this.yc+this.Rc/2;d=d>=D.jc?d-D.jc:d;d=0>d?d+D.jc:d;d>0.5*window.Math.PI&&d<1.5*window.Math.PI&&(d+=window.Math.PI);c.Ni(d);(0,D.nc)(c,b.x,b.y);c.ea(D.t);b=c}else b=D.r}else{if(0==this.nh)c={x:0,y:0};else if(c=(0,D.EB)((this.nh+this.Vg)/2,this.yc+this.Rc/2),d=3*(0,D.av)(this)/2,e=(0,D.FB)(c.x+d/2,c.y),!(0,D.GB)(this,(0,D.FB)(c.x-d/2,c.y))||!(0,D.GB)(this,e))c=D.r;if(c){d=new D.le(this.C.e,this.xx,c.x,c.y,D.r);d.Af((0,D.av)(this));(0,D.kv)(this,d);d.jf();
d.Zd();d.ea(D.t);for(var e=D.me.Gi(d),g=f=c.x,h=c.y-e.g/2,k=c.y+e.g/2;this.contains(f,h)&&this.contains(f,k);)f--;for(;this.contains(g,h)&&this.contains(g,k);)g++;f+=3;g-=3;c=2*window.Math.min(c.x-f,g-c.x);c<e.f&&(d.aa((f+g)/2),c=g-f);b=D.me.Yb(d,c,e.g,b)?d:D.r}else b=D.n}return b};
D.BB.prototype.Av=function(){if(!this.Uc){var b;b=this.D;if(!b||!("i"==this.JC||"ir"==this.JC))b=D.r;else{var c;if(this.If){c=this.C.e;var d=this.C.Fd,e=new D.Xc(c,d.collapseUp,0,0,16,16),f=new D.Xc(c,d.collapseOver,0,0,16,16),d=new D.Xc(c,d.collapseDown,0,0,16,16)}else c=this.C.e,d=this.C.Fd,e=new D.Xc(c,d.expandUp,0,0,16,16),f=new D.Xc(c,d.expandOver,0,0,16,16),d=new D.Xc(c,d.expandDown,0,0,16,16);(0,D.Ka)(e);(0,D.Ka)(f);(0,D.Ka)(d);c=new D.Ae(c,e,f,d);c.J(D.ed,this.q2,D.t,this);e=(0,D.EB)(this.Vg,
this.yc+this.Rc/2);(0,D.nc)(c,e.x-8,e.y-8);b.j(c);b=this.If?this.C.Fd.collapse:this.C.Fd.expand;this.C.Ca().ha(c,new D.mc(this,this.getId(),b));b=c}this.Uc=b}D.BB.n.Av.call(this)};D.BB.prototype.Ep=function(){this.Uc&&this.D&&(this.D.removeChild(this.Uc),this.Uc=D.r);D.BB.n.Ep.call(this)};
D.sc=function(b,c){if(b.D){var d=(0,D.HB)(b);b.D.tj(d);if(b.ye||!(0==b.nh&&b.Rc==D.jc))b.Ua&&b.D.removeChild(b.Ua),b.Ua=b.LH(b.D),b.Rn&&(b.D.removeChild(b.Rn),b.Rn=D.r);b.D.B(b.MB());if(c)for(var d=b.fb(),e=0;e<d.length;e++)(0,D.sc)(d[e],D.o)}};
D.BB.prototype.q2=function(){this.If=!this.If;var b=this.C,c=this.If,d=this.getId();b.SI=d;if(c)b.Ra(new D.xB("sunburstExpand",this.getId()));else{var c=b.xV,d=this.getId(),d=c.indexOf('\x3cn id\x3d"'+d),e=c.indexOf("\x3e",d),f=c.substring(d,e),f=-1<f.indexOf("di\x3d")?f.replace('di\x3d"t"','di\x3d"f"'):f+'di\x3d"f"';b.H(c.substring(0,d)+f+c.substring(e),b.Ob,b.Ab);b.Ra(new D.xB("sunburstCollapse",this.getId()))}};D.BB.prototype.bb=(0,D.B)("If");
D.AB=function(b){return b.cj!=D.r?(0,window.Number)(b.cj):b.ye?1:b.hX?0.25:b.VJ?1:0.5};
D.kc={};D.E.l(D.kc,D.E,"DvtSunburstLayout");D.kc.$n=function(b,c,d,e,f){var g=D.kc.C$(c);D.kc.ef(b/g,c,d,e,f,0)};D.kc.ef=function(b,c,d,e,f,g){var h=g+(0,D.AB)(c)*b;c.NL(g,h,d,e);g=c.fb();if(g!=D.r&&c.bb()){"on"==f&&(g=g.slice(0),g.sort(function(b,c){return c.nc()-b.nc()}));D.I.N(c.C.e)&&(g=g.slice(0).reverse());var k=0;for(c=0;c<g.length;c++)k+=0<g[c].nc()?g[c].nc():0;for(c=0;c<g.length;c++){var m=g[c];if(!(0>=m.nc())){var p=m.nc()/k*e;D.kc.ef(b,m,d,p,f,h);d+=p}}}};
D.kc.C$=function(b){var c=0,d=b.fb();if(d&&0<d.length){for(var e=0;e<d.length;e++)var f=D.kc.C$(d[e]),c=window.Math.max(c,f);return c+(0,D.AB)(b)}return(0,D.AB)(b)};
D.xB=function(b,c){this.Init(b);this.za=c?c:D.r};D.E.l(D.xB,D.fb,"DvtSunburstExpandCollapseEvent");D.xB.prototype.getId=(0,D.B)("za");
D.oc=function(b,c,d,e){D.oe.call(this,b,c,d,e)};D.E.l(D.oc,D.oe,"DvtSunburstEventManager");D.D=D.oc.prototype;D.D.yk=function(b){var c=(0,D.ye)(this,b.target);c&&c.getId&&"_rotationShape"==c.getId()&&!this.XN?(this.XN=D.o,b=(0,D.Xg)(this.e,b.pageX,b.pageY),c=this.C,(0,D.tc)(c,(0,D.wc)(c,b.x,b.y))):D.oc.n.yk.call(this,b)};D.D.Mr=function(b){if(this.XN){b=(0,D.Xg)(this.e,b.pageX,b.pageY);var c=this.C;(0,D.uc)(c,(0,D.wc)(c,b.x,b.y))}else D.oc.n.Mr.call(this,b)};
D.D.gm=function(b){this.XN?(this.XN=D.t,(0,D.vc)(this.C)):D.oc.n.gm.call(this,b)};D.D.Eo=function(b){var c=D.o,d=b.keyCode,e=(0,D.qt)(this),f=this.C;("i"==e.JC||"ir"==e.JC)&&((0,D.so)(b)&&!e.bb()||(0,D.to)(b)&&e.bb()||b.ctrlKey&&13==d)?(e.q2(),b.preventDefault()):f&&"on"==f.gfa&&(37==d||39==d)&&!b.ctrlKey&&b.altKey&&b.shiftKey?(d=37==d?-5*(window.Math.PI/180):5*(window.Math.PI/180),(0,D.tc)(f,0),(0,D.uc)(f,d),(0,D.vc)(f),b.preventDefault()):c=D.oc.n.Eo.call(this,b);return c};
D.D.PB=function(b){var c=(0,D.ye)(this,b.target);c&&(c.getId&&"_rotationShape"==c.getId())&&(0,D.Co)(b,this.xna,this)};D.D.AM=function(b){(0,D.Do)(this.Eb,b,"rotateKey")};D.D.zM=function(b){(0,D.Eo)(this.Eb,b,"rotateKey")};D.D.xna=function(b,c){if(1>=(0,D.So)(this.Eb,"rotateKey").length){(0,D.No)(this.Eb,c.identifier,"rotateKey",D.r,"rotateKey","rotateKey",this.wna,this.vna,this);(0,D.Uo)(this.Eb,c.identifier,D.t);var d=(0,D.Xg)(this.e,c.pageX,c.pageY),e=this.C;(0,D.tc)(e,(0,D.wc)(e,d.x,d.y));b.dr()}};
D.D.wna=function(b,c){var d=(0,D.Xg)(this.e,c.pageX,c.pageY),e=this.C;(0,D.uc)(e,(0,D.wc)(e,d.x,d.y));b.preventDefault()};D.D.vna=function(){(0,D.vc)(this.C)};
D.yB=(0,D.w)();D.E.l(D.yB,D.kp,"DvtSunburstBundle");D.yB._defaults={COLOR:"Color",SIZE:"Size"};D.yB.prototype.zy=function(b){return D.yB._defaults[b]};D.yB.prototype.yy=(0,D.ba)("DvtSunburstBundle");
D.hc=function(){this.Init({skyros:D.zB,alta:{}})};D.E.l(D.hc,D.Yu,"DvtSunburstDefaults");D.zB={rotation:"on"};
D.yc=(0,D.w)();D.E.l(D.yc,D.pv,"DvtSunburstJsonUtils");D.D=D.yc.prototype;D.D.sM=(0,D.ba)("sunburst");D.D.QG=function(b){var c=D.yc.n.QG.call(this,b),c=c+this.wa("r",b.rotation),c=c+this.wa("sa",(b.startAngle+360)%360);b=b.animationOnDisplay;return c="auto"==b?c+this.wa("adi","fan"):c+this.wa("adi",b)};
D.D.RG=function(b,c){var d=D.yc.n.RG.call(this,b,c),d=d+this.wa("ld",c.labelDisplay?c.labelDisplay:b.nodeDefaults.labelDisplay),e=c.labelHalign?c.labelHalign:b.nodeDefaults.labelHalign;"inner"==e?d+=this.wa("ha","s"):"outer"==e&&(d+=this.wa("ha","e"));e=c.radius;e!=D.r&&!(0,window.isNaN)(e)&&(d+=this.wa("r",e));return d};
D.D.uW=function(b){var c,d=new D.yB;c="\x3cresources"+this.wa("legendSize",(0,D.ct)(d,"SIZE"));c+=this.wa("legendColor",(0,D.ct)(d,"COLOR"));c+=this.wa("cursorRotate",b._resources.rotateCursor);c+=this.wa("alta","true");return c+"/\x3e\n"};
D.D.SG=function(b){var c=D.yc.n.SG.call(this,b),d=b.animationUpdateColor;d&&(c+=this.wa("top","-tr-animation-update-color: "+d));(d=b.nodeDefaults.borderColor)&&(c+=this.wa("node","border-color: "+d));(d=b.nodeDefaults.hoverColor)&&(c+=this.wa("node-hover","border-color: "+d));(b=b.nodeDefaults.selectedColor)&&(c+=this.wa("node-selected","border-color: "+b));return c+"/\x3e\n"};
});