define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(a){a.Bb=function(e,d,b,c,f,h){a.f.qb(e,null);a.f.qb(d,null);a.f.qb(b,null);a.f.qb(c,null);a.f.sk(h);this.pe=e;this.lh=d;this.Vd=b;this.nf=c;this.Td=f;this.Xb=h};o_("CollectionCellSet",a.Bb,a);a.Bb.prototype.getData=function(e){var d=this;this.da(e);this.da(e).done(function(a){d.Fc=a});if(null==d.Fc)return null;e=e.column;a.f.assert(e>=this.Vd&&e<=this.nf);return d.Fc.get(this.Xb[e])};a.a.c("CollectionCellSet.prototype.getData",
{getData:a.Bb.prototype.getData});a.Bb.prototype.getMetadata=function(e){var d=this;this.da(e);this.da(e).done(function(a){d.Fc=a});if(null==d.Fc)return null;e=e.column;a.f.assert(e>=this.Vd&&e<=this.nf);return{keys:{row:d.Fc.ve(),column:this.Xb[e]}}};a.a.c("CollectionCellSet.prototype.getMetadata",{getMetadata:a.Bb.prototype.getMetadata});a.Bb.prototype.da=function(e){var d;a.f.bd(e);d=e.row;null!=this.Td.offset&&(d+=this.Td.offset);e=e.column;a.f.assert(d>=this.pe&&d<=this.lh&&e>=this.Vd&&e<=this.nf);
return this.Td.at(d,{deferred:!0})};a.Bb.prototype.S=function(a){return"row"===a?Math.max(0,this.lh-this.pe):"column"===a?Math.max(0,this.nf-this.Vd):0};a.a.c("CollectionCellSet.prototype.getCount",{S:a.Bb.prototype.S});a.Bb.prototype.Ck=o_c("pe");a.a.c("CollectionCellSet.prototype.getStartRow",{Ck:a.Bb.prototype.Ck});a.Bb.prototype.Sz=o_c("lh");a.a.c("CollectionCellSet.prototype.getEndRow",{Sz:a.Bb.prototype.Sz});a.Bb.prototype.Bk=o_c("Vd");a.a.c("CollectionCellSet.prototype.getStartColumn",{Bk:a.Bb.prototype.Bk});
a.Bb.prototype.Rz=o_c("nf");a.a.c("CollectionCellSet.prototype.getEndColumn",{Rz:a.Bb.prototype.Rz});a.Bb.prototype.hg=o_c("Td");a.a.c("CollectionCellSet.prototype.getCollection",{hg:a.Bb.prototype.hg});a.Bb.prototype.ig=o_c("Xb");a.a.c("CollectionCellSet.prototype.getColumns",{ig:a.Bb.prototype.ig});a.Qb=function(e,d,b,c,f){a.f.qb(e,null);a.f.qb(d,null);a.f.sk(b);this.Yb=e;this.ne=d;this.Nn=b;this.Td=c;this.Ud=f};o_("CollectionHeaderSet",a.Qb,a);a.Qb.prototype.getData=function(e){a.f.assert(e<=this.ne&&
e>=this.Yb);var d=this;return null!=this.Ud&&null!=this.Td?(null!=this.Td.offset&&(e+=this.Td.offset),this.Td.at(e,{deferred:!0}).done(function(a){d.Fc=a}),d.Fc.get(this.Ud)):this.Nn[e]};a.a.c("CollectionHeaderSet.prototype.getData",{getData:a.Qb.prototype.getData});a.Qb.prototype.getMetadata=function(a){var d;return null!=this.Ud&&null!=this.Td?(d=this,this.Td.at(a,{deferred:!0}).done(function(a){d.Fc=a}),null==d.Fc?null:{key:d.Fc.ve()}):{key:this.getData(a)}};a.a.c("CollectionHeaderSet.prototype.getMetadata",
{getMetadata:a.Qb.prototype.getMetadata});a.Qb.prototype.S=function(){return Math.max(0,this.ne-this.Yb)};a.a.c("CollectionHeaderSet.prototype.getCount",{S:a.Qb.prototype.S});a.Qb.prototype.wa=o_c("Yb");a.a.c("CollectionHeaderSet.prototype.getStart",{wa:a.Qb.prototype.wa});a.Qb.prototype.Qz=o_c("ne");a.a.c("CollectionHeaderSet.prototype.getEnd",{Qz:a.Qb.prototype.Qz});a.Qb.prototype.Xz=o_c("Nn");a.a.c("CollectionHeaderSet.prototype.getHeaders",{Xz:a.Qb.prototype.Xz});a.Qb.prototype.zk=o_c("Ud");a.a.c("CollectionHeaderSet.prototype.getRowHeader",
{zk:a.Qb.prototype.zk});a.Qb.prototype.hg=o_c("Td");a.a.c("CollectionHeaderSet.prototype.getCollection",{hg:a.Qb.prototype.hg});a.T=function(e,d){this.V=e;null!=d&&(this.qh=d.rowHeader,this.columns=d.columns);this.N=0;this.Ld=this.Hb=-1;this.Yk=this.Gk=!1;a.T.q.constructor.call(this)};o_("CollectionDataGridDataSource",a.T,a);a.a.ea(a.T,a.tb,"oj.CollectionDataGridDataSource");a.T.prototype.i=function(){a.T.q.i.call(this);this.Oe={};this.Pw()?(this.Gk=!0,this.V.fetch({success:this.uw.bind(this,!0)})):
null==this.columns&&0<this.V.length&&(this.columns=this.V.first().keys(),-1!=this.columns.indexOf(this.qh)&&this.columns.splice(this.columns.indexOf(this.qh),1));this.HI()};a.a.c("CollectionDataGridDataSource.prototype.Init",{i:a.T.prototype.i});a.T.prototype.HI=function(){this.V.on("add",this.LG.bind(this));this.V.on("remove",this.NG.bind(this));this.V.on("change",this.MG.bind(this));this.V.on("sync",this.VG.bind(this))};a.T.prototype.Pw=function(){return null!=this.V.url};a.T.prototype.hq=function(){return this.Pw()?
null!=this.data:!0};a.T.prototype.uw=function(e,d,b){var c;this.data=b;!0===e?this.Gk=!1:this.Yk=!1;this.Ld=void 0===d.Zk?d.length:d.Zk;a.tb.q.handleEvent.call(this,"sync",!0);null==this.columns&&0<this.V.models.length&&(this.columns=this.V.models[0].keys(),-1!=this.columns.indexOf(this.qh)&&this.columns.splice(this.columns.indexOf(this.qh),1));for(c in this.Oe)this.Oe.hasOwnProperty(c)&&null!=this.Oe[c]&&this.Bc(this.Oe[c].RK,this.Oe[c].callbacks,this.Oe[c].er);null!=this.Ne&&this.Ac(this.Ne.nK,
this.Ne.callbacks,this.Ne.er)};a.T.prototype.S=function(a){if(!this.hq())return this.precision="estimate",100;this.precision="exact";return"row"==a?this.size():"column"==a?this.columns.length:0};a.a.c("CollectionDataGridDataSource.prototype.getCount",{S:a.T.prototype.S});a.T.prototype.Qd=function(a){null==this.precision&&this.S(a);return this.precision};a.a.c("CollectionDataGridDataSource.prototype.getCountPrecision",{Qd:a.T.prototype.Qd});a.T.prototype.Bc=function(e,d,b){var c,f,h,g;c=e.axis;this.hq()?
(f=e.start,h=e.count,a.f.assert("row"===c||"column"===c),a.f.assert(f<this.S(c)),a.f.assert(0<h),"column"===c?(h=Math.min(this.columns.length,f+h),g=new a.Qb(f,h,this.columns)):"row"===c&&(null!=this.qh?(h=Math.min(this.size(),f+h),0<this.Hb&&(h=Math.min(h,this.N+this.Hb),h=Math.min(h,this.totalSize()-this.N)),g=new a.Qb(f,h,this.columns,this.V,this.qh)):g=new a.zd(f,f,c,null)),null!=d&&null!=d.success&&(null==b&&(b={}),d.success.call(b.success,g,e)),this.Oe[c]=null):null!=d&&null==this.Oe[c]&&(f=
{},f.RK=e,f.callbacks=d,f.er=b,this.Oe[c]=f)};a.a.c("CollectionDataGridDataSource.prototype.fetchHeaders",{Bc:a.T.prototype.Bc});a.T.prototype.Ac=function(e,d,b){var c,f,h,g,l,k;k=g=0;if(this.hq()){for(c=0;c<e.length;c+=1)f=e[c],a.f.assert("row"===f.axis||"column"===f.axis),a.f.assert(f.start<this.S(f.axis)),a.f.assert(0<f.count),"row"===f.axis?(h=f.start,g=Math.min(this.size(),h+f.count),0<this.Hb&&(g=Math.min(g,this.N+this.Hb),g=Math.min(g,this.totalSize()-this.N))):"column"===f.axis&&(l=f.start,
k=Math.min(this.columns.length,l+f.count));c=new a.Bb(h,g,l,k,this.V,this.columns);null!=d&&null!=d.success&&(null!=d&&null==b&&(b={}),d.success.call(b.success,c,e),this.cF=0);this.Ne=null}else null!=d&&null==this.Ne&&(this.Ne={},this.Ne.nK=e,this.Ne.callbacks=d,this.Ne.er=b)};a.a.c("CollectionDataGridDataSource.prototype.fetchCells",{Ac:a.T.prototype.Ac});a.T.prototype.keys=function(a){var d=a.row;return{row:void 0===this.V.models[d]?void 0:this.V.models[d].cid,column:this.columns[a.column]}};a.a.c("CollectionDataGridDataSource.prototype.keys",
{keys:a.T.prototype.keys});a.T.prototype.Oc=function(a){var d=a.column;return{row:this.V.models.indexOf(this.V.gh(a.row)),column:void 0===this.columns?this.V.first().keys().indexOf(d):this.columns.indexOf(d)}};a.a.c("CollectionDataGridDataSource.prototype.indexes",{Oc:a.T.prototype.Oc});a.T.prototype.bb=function(a){return"sort"===a?"column":"move"===a?"row":null};a.a.c("CollectionDataGridDataSource.prototype.getCapability",{bb:a.T.prototype.bb});a.T.prototype.sort=function(a,d,b){var c,f=a.direction,
h=a.key;a=a.axis;null==b&&(b={});"column"===a?("ascending"===f&&(c=function(a,b){var c,d;a=a.get(h);b=b.get(h);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString(),c=!0);b instanceof Date&&(b=b.toISOString(),d=!0);return c&&d?a<b?-1:a===b?0:1:c?1:d?-1:a-b}),"descending"===f&&(c=function(a,b){var c,d;a=a.get(h);b=b.get(h);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString());b instanceof Date&&(b=b.toISOString());return c&&d?a>b?-1:a===b?0:1:c?-1:d?1:b-a}),void 0!==c?(this.V.comparator=
c,this.V.sort(),null!=d&&null!=d.success&&d.success.call(b.success)):null!=d&&null!=d.error&&d.error.call(b.error,"Direction value was invalid")):null!=d&&null!=d.error&&d.error.call(b.error,"Axis value not supported")};a.a.c("CollectionDataGridDataSource.prototype.sort",{sort:a.T.prototype.sort});a.T.prototype.move=function(a,d){var b,c;b=this.V.gh(a);null===d?(this.V.remove(b),this.V.add(b)):(a===d?(c=this.V.indexOf(this.V.gh(d)),this.V.remove(b)):(this.V.remove(b),c=this.V.indexOf(this.V.gh(d))),
this.V.add(b,{at:c}))};a.a.c("CollectionDataGridDataSource.prototype.move",{move:a.T.prototype.move});a.T.prototype.Op=function(a,d){var b={source:this};b.operation=a;b.keys={row:d,column:null};return b};a.T.prototype.LG=function(a){!1===this.Yk&&!1===this.Gk&&(a=a.ve(),a=this.Op("insert",a),this.handleEvent("change",a))};a.T.prototype.NG=function(a){!1===this.Yk&&!1===this.Gk&&(a=a.ve(),a=this.Op("delete",a),this.handleEvent("change",a))};a.T.prototype.MG=function(a){!1===this.Yk&&!1===this.Gk&&
(a=a.ve(),a=this.Op("update",a),this.handleEvent("change",a))};a.T.prototype.VG=function(){0<this.Hb&&(this.Oe={},this.Ne=null,this.handleEvent("change",{operation:"sync",pageSize:this.Hb,rowIndex:this.N}))};a.T.prototype.qe=o_b("Hb");a.a.c("CollectionDataGridDataSource.prototype.setPageSize",{qe:a.T.prototype.qe});a.T.prototype.size=function(){return 0===this.V.length?-1:null!=this.Hb&&0<this.Hb&&this.V.size()>this.Hb?this.Hb:this.V.size()};a.a.c("CollectionDataGridDataSource.prototype.size",{size:a.T.prototype.size});
a.T.prototype.totalSize=function(){return null!=this.V&&0>this.Ld?this.V.totalResults:this.Ld};a.a.c("CollectionDataGridDataSource.prototype.totalSize",{totalSize:a.T.prototype.totalSize});a.T.prototype.hasMore=function(){return null!=this.V?this.V.hasMore:!1};a.a.c("CollectionDataGridDataSource.prototype.hasMore",{hasMore:a.T.prototype.hasMore});a.T.prototype.fetch=function(a){this.Yk=!0;this.N=null!=a?null!=a.startIndex?a.startIndex:0:0;this.V.fetch({success:this.uw.bind(this,!1),startIndex:this.N})};
a.a.c("CollectionDataGridDataSource.prototype.fetch",{fetch:a.T.prototype.fetch});a.T.prototype.hg=o_c("V");a.a.c("CollectionDataGridDataSource.prototype.getCollection",{hg:a.T.prototype.hg});a.T.prototype.ig=o_c("columns");a.a.c("CollectionDataGridDataSource.prototype.getColumns",{ig:a.T.prototype.ig});a.T.prototype.zk=o_c("qh");a.a.c("CollectionDataGridDataSource.prototype.getRowHeader",{zk:a.T.prototype.zk});a.T.prototype.aA=o_c("N");a.a.c("CollectionDataGridDataSource.prototype.getStartIndex",
{aA:a.T.prototype.aA});a.T.prototype.Yz=o_c("Hb");a.a.c("CollectionDataGridDataSource.prototype.getPageSize",{Yz:a.T.prototype.Yz});a.T.prototype.bA=o_c("Ld");a.a.c("CollectionDataGridDataSource.prototype.getTotalSize",{bA:a.T.prototype.bA});a.T.prototype.Uz=o_c("cF");a.a.c("CollectionDataGridDataSource.prototype.getFetchCalls",{Uz:a.T.prototype.Uz});a.T.prototype.getData=o_c("data");a.a.c("CollectionDataGridDataSource.prototype.getData",{getData:a.T.prototype.getData})});
//# sourceMappingURL=oj-modular.map