define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,e){function d(a,b){this.fI=b;this.XI=a;this.PE="/"}a.Uc=function(a){this.i(a)};o_("AttributeGroupHandler",a.Uc,a);a.a.ea(a.Uc,a.a,"oj.AttributeGroupHandler");a.Uc.prototype.i=function(b){a.Uc.q.i.call(this);this.Uj=b?b:{};this.ij={};this.xn=0;this.ol=this.Ek();for(var d in this.Uj)b=this.ol.indexOf(this.Uj[d]),-1!==b&&this.ol.splice(b,1)};a.Uc.prototype.Ek=function(){return[]};a.a.c("AttributeGroupHandler.prototype.getValueRamp",{Ek:a.Uc.prototype.Ek});
a.Uc.prototype.Hn=function(a){if(this.Uj[a])return this.Uj[a];this.ij[a]||(this.ij[a]=this.ol[this.xn],this.xn==this.ol.length-1?this.xn=0:this.xn++);return this.ij[a]};a.a.c("AttributeGroupHandler.prototype.getValue",{Hn:a.Uc.prototype.Hn});a.Uc.prototype.Lz=function(){var a=[],b;for(b in this.ij)a.push({category:b,value:this.ij[b]});return a};a.a.c("AttributeGroupHandler.prototype.geCategoryAssignments",{Lz:a.Uc.prototype.Lz});a.Uc.prototype.tz=function(a,b){this.Uj[a]=b};a.a.c("AttributeGroupHandler.prototype.addMatchRule",
{tz:a.Uc.prototype.tz});var b={CSS_TEXT_PROPERTIES:function(a,d){var e={};a&&(a.hasClass("oj-gaugeMetricLabel")&&a.hasClass(a.parentNode,"oj-ledGauge")&&(e["font-size"]=!0,e.color=!0),a.hasClass(a,"oj-chartSliceLabel")&&(e.color=!0));return b.ex(a,d,!1,e)},CSS_BACKGROUND_PROPERTIES:function(a,d){return b.ex(a,d,!0,{})},CSS_URL:function(a){return b.eI(a)},Vs:"rgb(254, 0, 254)",Ws:"Times",Xs:"1px",Zs:"1",Ys:"normal",vK:function(a,b){return a.css(b)},eI:function(a){return(a=a.css("content"))&&-1!==a.indexOf("url(")?
a.slice(a.indexOf("url(")+4,a.length-1).replace(/"/g,""):a},GD:function(a){var b="";a.css("border-top-color")&&(b+="border-color: "+a.css("border-top-color")+";");a.css("border-width")&&(a.css("border-style")&&"none"!=a.css("border-style"))&&(b+="border-width: "+a.css("border-width")+";");a.css("background-color")&&(b+="background-color: "+a.css("background-color")+";");return b},KD:function(a,d){var e="",g=a.css("font-family");g&&g!==b.Ws&&(e+="font-family: "+g.replace(/"/g,"'")+";");(g=a.css("font-size"))&&
(g!==b.Xs&&!d["font-size"])&&(e+="font-size: "+g+";");(g=a.css("font-weight"))&&g!==b.Zs&&(e+="font-weight: "+g+";");(g=a.css("color"))&&(g!==b.Vs&&!d.color)&&(e+="color: "+g+";");(g=a.css("font-style"))&&g!==b.Ys&&(e+="font-style: "+g+";");return e},ex:function(a,b,d,e){e||(e={});if(!a)return b;var l;b&&(l=a.attr("style"),a.attr("style",l+b));b="";!0!==d&&(b+=this.KD(a,e));!1!==d&&(b+=this.GD(a));l&&a.attr("style",l);return b}};a.ga("oj.dvtBaseComponent",e.oj.baseComponent,{nq:[],yu:[],GJ:"ar cs da de el es fi fr hu it iw ja ko nl no pl pt pt_BR ro ru sk sv th tr zh_CN zh_TW".split(" "),
_create:function(){this.$l=new DvtContext(this.element[0]);this.$l.setReadingDirection(this._GetReadingDirection());this.element.attr("tabIndex",0);this.wb=this.$d(this.$l,this.Ia,this);this.$l.getStage().addChild(this.wb);this.rI(this.Lh());this.yx();this.Xm();this.nD();this.ce()},nD:function(){var a=e(document.createElement("div"));a.attr("style","display:none;");a.text(JSON.stringify(this.options));this.element.append(a)},Be:function(){return["oj-dvtbase"]},Lh:function(){return{}},rI:function(a){for(var d=
this.Be(),h=this.element.attr("class"),g="",l=0;l<d.length;l++)g=g+d[l]+" ";h&&(g+=h);this.element.attr("class",g);d=e(document.createElement("div"));d.attr("style","display:none;");this.element.append(d);d.css("font-family",b.Ws);d.css("font-size",b.Xs);d.css("color",b.Vs);d.css("font-weight",b.Zs);d.css("font-style",b.Ys);for(var k in a)h=e(document.createElement("div")),h.addClass(k),d.append(h),this.qI(h,a[k])},qI:function(a,b){if(b instanceof Array)for(var d=0;d<b.length;d++)this.ly(a,b[d]);
else this.ly(a,b)},ly:function(a,e){var h=new d(this.options,e.path),g;e.property&&(g=(g=b[e.property])?g(a,h.Hn()):b.vK(a,e.property));null==g||"string"==typeof g&&""==g.replace(/^\s+/g,"")||h.BL(g)},Kj:function(){return{"oj-ojDvtCommon.labelClearSelection":"DvtUtilBundle.CLEAR_SELECTION","oj-ojDvtCommon.labelMonthShortJanuary":"DvtUtilBundle.MONTH_SHORT_JANUARY","oj-ojDvtCommon.labelMonthShortFebruary":"DvtUtilBundle.MONTH_SHORT_FEBRUARY","oj-ojDvtCommon.labelMonthShortMarch":"DvtUtilBundle.MONTH_SHORT_MARCH",
"oj-ojDvtCommon.labelMonthShortApril":"DvtUtilBundle.MONTH_SHORT_APRIL","oj-ojDvtCommon.labelMonthShortMay":"DvtUtilBundle.MONTH_SHORT_MAY","oj-ojDvtCommon.labelMonthShortJune":"DvtUtilBundle.MONTH_SHORT_JUNE","oj-ojDvtCommon.labelMonthShortJuly":"DvtUtilBundle.MONTH_SHORT_JULY","oj-ojDvtCommon.labelMonthShortAugust":"DvtUtilBundle.MONTH_SHORT_AUGUST","oj-ojDvtCommon.labelMonthShortSeptember":"DvtUtilBundle.MONTH_SHORT_SEPTEMBER","oj-ojDvtCommon.labelMonthShortOctober":"DvtUtilBundle.MONTH_SHORT_OCTOBER",
"oj-ojDvtCommon.labelMonthShortNovember":"DvtUtilBundle.MONTH_SHORT_NOVEMBER","oj-ojDvtCommon.labelMonthShortDecember":"DvtUtilBundle.MONTH_SHORT_DECEMBER","oj-ojDvtCommon.labelScalingSuffixThousand":"DvtUtilBundle.SCALING_SUFFIX_THOUSAND","oj-ojDvtCommon.labelScalingSuffixMillion":"DvtUtilBundle.SCALING_SUFFIX_MILLION","oj-ojDvtCommon.labelScalingSuffixBillion":"DvtUtilBundle.SCALING_SUFFIX_BILLION","oj-ojDvtCommon.labelScalingSuffixTrillion":"DvtUtilBundle.SCALING_SUFFIX_TRILLION","oj-ojDvtCommon.labelScalingSuffixQuadrillion":"DvtUtilBundle.SCALING_SUFFIX_QUADRILLION"}},
yx:function(){var b=this.Kj(),d={},e;for(e in b){var g=b[e],l=a.Q.yr(e);d[g]=l}DvtBundle.addLocalizedStrings(d)},_destroy:function(){this.element.children().remove()},_setOptions:function(a){this._superApply(arguments);this.ce()},$d:o_d(null),Ia:function(a){if((a&&a.getType?a.getType():null)==DvtActiveElementChangeEvent.TYPE)a=a.getId(),this.element.attr("aria-activedescendant",a);else return null},Xm:o_a(),LH:function(b){var d=a.Ea.ed();if(0===d.indexOf("en"))this.Xw(b+".js");else{for(var e=d.split("_"),
d=[],g=0;g<e.length;g++){for(var l="",k=0;k<g+1;k++)0!=k&&(l+="_"),l+=e[k];d.push(l)}for(e=d.length-1;0<=e;e++)-1!==this.GJ.indexOf(d[e])&&this.Xw(b+"_"+d[e]+".js")}},Xw:function(b){if(!this.nq[b]){var d=a.Ea.hh(b),h=this,g=this.nq;e.getScript(d,function(){g[b]=!0;h.ce()})}},ce:function(){for(var a=0;a<this.yu.length;a++)if(!this.nq[this.yu[a]])return;this.wb.render(this.options,this.element.width(),this.element.height())},refresh:function(){this.$l.setReadingDirection(this._GetReadingDirection());
this.yx();this.ce()},getNodeBySubId:function(a){var b;this.wb&&this.wb.getAutomation&&(b=this.wb.getAutomation());return b?b.fN(a):null}});a.Zi=function(a){this.i(a)};o_("ShapeAttributeGroupHandler",a.Zi,a);a.a.ea(a.Zi,a.Uc,"oj.ShapeAttributeGroupHandler");a.Zi.Rl="square circle diamond plus triangleDown triangleUp human".split(" ");a.Zi.prototype.Ek=function(){return a.Zi.Rl.slice()};a.uh=function(b){this.Rl=[];var d=e(document.createElement("div"));d.attr("style","display:none;");d.attr("id","attrGps");
e(document.body).append(d);for(var h=0;h<a.uh.Vy.length;h++){var g=e(document.createElement("div"));g.addClass(a.uh.Vy[h]);d.append(g);this.Rl.push(g.css("color"))}d.remove();this.i(b)};o_("ColorAttributeGroupHandler",a.uh,a);a.a.ea(a.uh,a.Uc,"oj.ColorAttributeGroupHandler");a.uh.Vy="oj-dvt-category-index1 oj-dvt-category-index2 oj-dvt-category-index3 oj-dvt-category-index4 oj-dvt-category-index5 oj-dvt-category-index6 oj-dvt-category-index7 oj-dvt-category-index8 oj-dvt-category-index9 oj-dvt-category-index10 oj-dvt-category-index11 oj-dvt-category-index12".split(" ");
a.uh.prototype.Ek=function(){return this.Rl.slice()};d.prototype.UI=function(a,b,d,e){for(var l={};a&&-1<b.indexOf(d);){var k=b.substring(0,b.indexOf(d));e&&void 0===a[k]&&(a[k]={});a=a[k];b=b.substring(b.indexOf(d)+1,b.length)}a&&(l.object=a,l.parameter=b);return l};d.prototype.ky=function(a){void 0===this.Tj&&(a=this.UI(this.XI,this.fI,this.PE,a),this.Tj=a.object,this.vq=a.parameter)};d.prototype.Hn=function(){this.ky(!1);return void 0===this.Tj?void 0:this.Tj[this.vq]};d.prototype.BL=function(a){this.ky(!0);
this.Tj[this.vq]!==a&&(this.Tj[this.vq]=a)}});
//# sourceMappingURL=oj-modular.map