define(["ojs/ojcore","jquery","knockout"],function(a,e,d){function b(b,a){var c={};c.value=a.value;return c}function c(b,a){var c={},d=a.optionMetadata;d&&"shouldWrite"===d.writeback&&(c[a.option]=a.value);return c}function f(){this.i()}function h(b,a){this.i(b,a)}function g(b,a,c,f){var e={};(function(a,c){e.renderer=function(f){var e=null;"header"==c?e=b.extend({$column:f.column}):"cell"==c&&(e=b.createChildContext(f.row,null,function(b){b.$column=f.column;b.$status=f.status}));d.renderTemplate(a,
e,null,f.parentElement,"replaceNode")}})(f,c);e.type=c;e.columnId=a;return e}function l(b,a){return function(c){d.renderTemplate(a,b,null,c.parentElement,"replaceNode")}}function k(b,a){return function(c){var f=b.createChildContext(c.row,null,function(b){b.$column=c.column;b.$status=c.status});d.renderTemplate(a,f,null,c.parentElement,"replaceNode")}}function m(b,a){return function(c){var f,e;f=c.parentElement;e=b.createChildContext(c.data,null,function(b){b.$key=c.key;b.$metadata=c.metadata;b.$headerContext=
c});d.renderTemplate(a,e,null,f);return null}}function n(b,a){return function(c){var f,e;f=c.parentElement;e=b.createChildContext(c.data,null,function(b){b.$keys=c.keys;b.$metadata=c.metadata;b.$cellContext=c});d.renderTemplate(a,e,null,f);return null}}a.O=function(b,a){this.i(b,a)};o_("ComponentBinding",a.O,a);a.a.ea(a.O,a.a,"oj.ComponentBinding");a.O.create=function(b,c){if(null==b)throw"Binding name is required!";var f=new a.O(b,c),e=d.bindingHandlers,h,n=Array.isArray(b)?b:[b];for(h=0;h<n.length;h++)e[n[h]]=
f;return f};o_("ComponentBinding.create",a.O.create,a);a.O.Cc=function(){return a.O.YB};o_("ComponentBinding.getDefaultInstance",a.O.Cc,a);a.O.prototype.Gc=function(b){var c=b["for"],c=null==c?"@global":c;a.u.option("level")>=a.u.jl&&this.Ym[c]&&a.u.error("Managed Attributes for '%s' are redefined",c);this.Ym[c]=b};a.a.c("ComponentBinding.prototype.setupManagedAttributes",{Gc:a.O.prototype.Gc});a.O.nr=function(){a.O.wu.nr()};o_("ComponentBinding.deliverChanges",a.O.nr,a);a.O.prototype.i=function(b,
c){a.O.q.i.call(this);"string"===typeof c&&(c={componentName:c});this.Lo=c||{};this.FD=Array.isArray(b)?b:[b];this.init=a.a.uk(this,this._init);this.update=a.a.uk(this,this.TJ);this.Ym={}};a.O.to="_ojNeedsJUIBInit";a.O.prototype._init=function(b,c,f,h,n){d.applyBindingsToDescendants(n,b);e(b).data(a.O.to,!0);return{controlsDescendantBindings:!0}};a.O.prototype.TJ=function(b,c,d,f,h){f=e(b);f.data(a.O.to)&&(f.data(a.O.to,null),this.Dw(b,f,c,d,h))};a.O.prototype.Dw=function(f,e,n,g,k){var l=n(),m=null,
A=!1,C=[],K=null,E=null,B=a.O.pF(this.FD,f,k),I=0,x={},w=this.Lo.componentName;if(null==w){m="component";if(!B[m]&&(m="role",!B[m])){a.u.error("component attribute is required for the ojComponent binding");return}var u=l[m];if(null==u){a.u.error("non-null component attribute is required for the ojComponent binding");return}d.computed(function(){a.O.vp(B[m],m,x,k);if(0==I)w=d.utils.unwrapObservable(u);else{A=!0;B=null;a.O.SJ(e);if(E){K.Hz();K=null;var b=this.Lo.beforeDestroy;b&&b(f,E,n,g,k);E("destroy");
E=null;for(b=0;b<C.length;b++)C[b].Hz();C=null}this.Dw(f,e,n,g,k)}return null},this,{disposeWhenNodeIsRemoved:f})}if(null!=w)if(E=e[w],"function"===typeof E){var E=E.bind(e),L=a.O.jy(this.Ym,B,w),D=a.O.Cc();this!==D&&(D=D.KF(B,w),a.Rb.kf(D,L),L=D);var z={},K=new h(E,a.O.wu),D={"^slider$":[{event:"slidechange",getter:b}],"^oj*":[{event:"ojoptionchange",getter:c}]},F=function(){var b=this.sI,c=B[b];c&&a.O.vp(c,b,x,k);if(0===I){var d=a.O.un(l[b]);null!=L[b]?(c=L[b].WK,null!=c&&(b=c(b,d,f,E,n,g,k)||{},
a.Rb.kf(z,b))):z[b]=d}else if(!A)if(c=a.O.un(n()[b]),null!=L[b]){var e=L[b].update;if(null!=e)for(d in b=e(b,c,f,E,n,g,k)||{},b)b.hasOwnProperty(d)&&K.sz(d,b[d])}else K.sz(b,c);return null},J;for(J in l)l.hasOwnProperty(J)&&J!==m&&C.push(d.computed(F,{sI:J},{disposeWhenNodeIsRemoved:f}));a.O.JI(e,w,D,n,B,K,k);E(z);(J=this.Lo.afterCreate)&&J(f,E,n,g,k);z=null}else a.u.error("Component %s is not found",w);I=1};a.O.pF=function(b,a,c){var f={},e=null,e=d.bindingProvider.instance,h;h=null;var n,e=e.DK?
e.DK(a,c):a.getAttribute("data-bind");if(!e)return f;a=d.jsonExpressionRewriting.parseObjectLiteral(e);c=/^(\s|\u00A0)+|(\s|\u00A0)+$/g;for(e=0;e<a.length;e+=1){n=a[e];var g=n.key.replace(c,"");if(0<=b.indexOf(g)){h=n.value;break}}if(!h)return f;a=d.jsonExpressionRewriting.parseObjectLiteral(h);for(b=0;b<a.length;b+=1)h=a[b],f[h.key.replace(c,"")]=h.value.replace(c,"");return f};a.O.vp=function(b,a,c,d){var f=c[a];void 0===f&&("string"!==typeof b&&(b=b()),f=null,null!==b&&(f=new Function("$context",
"with($context){with($data||{}){return "+b+";}}")),c[a]=f);return f?f(d):null};a.O.prototype.KF=function(b,c){return a.O.jy(this.Ym,b,c)};a.O.jy=function(b,a,c){function d(a){a=b[a];if(null!=a){e.push(a);a=a.use;var c;if(null!=a)for(a=Array.isArray(a)?a:[a],c=0;c<a.length;c++)d(a[c])}}var f={},e=[];d(c);c=b["@global"];var h;c&&e.push(c);if(0<e.length)for(h in a)if(a.hasOwnProperty(h))for(c=0;c<e.length;c++){var n=e[c],g=n.attributes;if(null!=g&&0<=g.indexOf(h)){f[h]={WK:n.init,update:n.update};break}}return f};
a.O.Us=".ojWriteback";a.O.SJ=function(b){b&&b.off(a.O.Us)};a.O.JI=function(b,c,d,f,e,h,n){var g={},k;for(k in d)if(c.match(k)){c=d[k];for(d=0;d<c.length;d++)k=c[d],b.on(k.event+a.O.Us,{PK:k.getter},function(b,c){b.stopPropagation();var d=b.data.PK(b,c);h.HL();try{for(var k in d)a.O.aK(k,f()[k],d[k],e[k],n,g)}finally{h.tL()}});break}};a.O.YF=function(b){var a=["true","false","null","undefined"];if(null==b||0<=a.indexOf(b))return null;a=b.match(/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i);
return null===a?null:"function(v){"+(a[1]?"Object("+a[1]+")"+a[2]:b)+"\x3dv;}"};a.O.aK=function(b,c,f,e,h,n){null!=c&&d.isObservable(c)?d.isWriteableObservable(c)&&c(f):(b=a.O.vp(function(){return a.O.YF(e)},b,n,h))&&b(f)};a.O.un=function(b){b=d.utils.unwrapObservable(b);(Array.isArray(b)||a.Rb.isPlainObject(b))&&b.ojConvertToJS&&(b=d.toJS(b));return b};a.a.ea(f,a.a,"ComponentBinding.GlobalChangeQueue");f.prototype.i=function(){f.q.i.call(this);this.yg=[]};f.prototype.pL=function(b){-1===this.yg.indexOf(b)&&
(this.yg.push(b),this.gm||(this.gm=setTimeout(a.a.uk(this,this.ev),1)))};f.prototype.qL=function(b){b=this.yg.indexOf(b);0<=b&&this.yg.splice(b,1)};f.prototype.nr=function(){this.gm&&clearTimeout(this.gm);this.ev()};f.prototype.ev=function(){var b;this.gm=null;try{for(b=0;b<this.yg.length;b+=1)this.yg[b]()}finally{this.yg=[]}};a.a.ea(h,a.a,"ComponentBinding.ComponentChangeTracker");h.prototype.i=function(b,c){h.q.i.call(this);this.wb=b;this.Cx=c;this.kz=a.a.uk(this,this.uD);this.Wo={};this.oi=0};
h.prototype.sz=function(b,a){this.EH()||this.TE||(this.Wo[b]=a,this.Cx.pL(this.kz))};h.prototype.Hz=function(){this.Cx.qL(this.kz);this.TE=!0};h.prototype.tL=function(){a.f.assert(0<this.oi,"ComponentChangeTracker._suspendCount underflow");this.oi-=1};h.prototype.HL=function(){this.oi-=1};h.prototype.EH=function(){return 1<=this.oi};h.prototype.uD=function(){try{this.wb("option",this.Wo)}finally{this.Wo={}}};a.O.wu=new f;a.O.YB=a.O.create(["ojComponent","jqueryUI"]);a.O.Cc().Gc({attributes:["columnTemplates",
"footerTemplate","rowTemplate"],init:function(b,a,c,d,f,e,h){var n;if("columnTemplates"==b){f=[];for(e=0;e<a.length;e++)n=a[e],b=n.columnId,c=n.template,n=n.type,null!=c&&(null!=b&&null!=n)&&(f[e]=g(h,b,n,c));0<f.length&&d({columnRenderers:f})}else"rowTemplate"==b?(c=a.template,d({rowRenderer:k(h,c)})):"footerTemplate"==b&&(c=a.template,d({footerRenderer:l(h,c)}))},update:function(b,a,c,d,f,e,h){if("columnTemplates"==b){d=[];for(f=0;f<a.length;f++)e=a[f],b=e.columnId,c=e.template,e=e.type,null!=c&&
(null!=b&&null!=e)&&(d[f]=g(h,b,e,c));if(0<d.length)return{columnRenderers:d}}else{if("rowTemplate"==b)return c=a.template,{rowRenderer:k(h,c)};if("footerTemplate"==b)return c=a.template,{footerRenderer:l(h,c)}}return null},"for":"ojTable"});a.Mr={};o_("koStringTemplateEngine",a.Mr,a);a.Mr.YK=function(){function b(d){this.pi=d;this.text=function(b){if(!b)return a[this.pi];a[this.pi]=b};this.data=function(b,a){c[this.pi]||(c[this.pi]={});if(1===arguments.length)return c[this.pi][b];c[this.pi][b]=a}}
var a={},c={},f=new d.nativeTemplateEngine;f.makeTemplateSource=function(a,c){if("string"==typeof a){c=c||document;var f=c.getElementById(a);return f?new d.templateSources.domElement(f):new b(a)}if(a&&1==a.nodeType||8==a.nodeType)return new d.templateSources.anonymousTemplate(a)};d.templates=a;d.setTemplateEngine(f)};o_("koStringTemplateEngine.install",a.Mr.YK,a);a.O.Cc().Gc({attributes:["header","cell"],init:function(b,a,c,d,f,e,h){"header"===b?(b=a.row,null!=b&&(c=b.template,null!=c&&(b.renderer=
m(h,c))),b=a.column,null!=b&&(c=b.template,null!=c&&(b.renderer=m(h,c))),d({header:a})):"cell"===b&&(b=a.template,null!=b&&(a.renderer=n(h,b)),d({cell:a}))},update:function(b,a,c,d,f,e,h){return"header"===b?(b=a.row,null!=b&&(c=b.template,null!=c&&(b.renderer=m(h,c))),b=a.column,null!=b&&(c=b.template,null!=c&&(b.renderer=m(h,c))),{header:a}):"cell"===b?(b=a.template,null!=b&&(a.renderer=n(h,b)),{cell:a}):null},"for":"ojDataGrid"});d.bindingHandlers.ojContextMenu={update:function(b,a){e(b).off(".ojContextMenu");
var c=d.utils.unwrapObservable(a());c&&(c=d.utils.unwrapObservable(c.menu));c||(c=b.getAttribute("contextmenu"));if(c&&(c=e("#"+c).data("oj-ojMenu"))){var f=e(b);f.on("keydown.ojContextMenu contextmenu.ojContextMenu",function(b){return"contextmenu"===b.type||121==b.which&&b.shiftKey?(c.show(b,{launcher:f,focus:"menu"}),!1):!0})}}}});
//# sourceMappingURL=oj-modular.map