define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojmodel","ojs/ojdatacollection-common"],function(a,e){(function(){a.ga("oj.ojPagingControl",e.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{data:null,pageSize:25,pageOptions:{layout:["auto"],maxPageLinks:6},loadMoreOptions:{maxCount:500},mode:"page"},Z:{gC:"labelAccPaging",bC:"labelAccNavFirstPage",cC:"labelAccNavLastPage",dC:"labelAccNavNextPage",fC:"labelAccNavPreviousPage",eC:"labelAccNavPage",
hC:"labelLoadMore",iC:"labelNavInputPage",jC:"labelNavInputPageMax",kC:"labelNavInputPageSummary",lt:"msgItemRange",vC:"msgItemRangeUnknown",VC:"tipNavInputPage",YC:"tipNavPageLink",XC:"tipNavNextPage",ZC:"tipNavPreviousPage",UC:"tipNavFirstPage",WC:"tipNavLastPage",OB:"pageInvalid.summary",NB:"pageInvalid.detail",ro:"dataInvalidType.summary",qo:"dataInvalidType.detail",MB:"maxPageLinksInvalid.summary",LB:"maxPageLinksInvalid.detail"},G:{Bo:"oj-widget",mo:"oj-active",rg:"oj-clickable-icon",Eb:"oj-disabled",
Kc:"oj-enabled",Yd:"oj-focus",Al:"oj-hover",Fb:"oj-checked"},l:{yC:"oj-pagingcontrol",nt:"oj-pagingcontrol-acc-label",ot:"oj-pagingcontrol-content",pt:"oj-pagingcontrol-loadmore",qt:"oj-pagingcontrol-loadmore-link",rt:"oj-pagingcontrol-loadmore-range",tt:"oj-pagingcontrol-nav",st:"oj-pagingcontrol-nav-arrow-section",JC:"oj-pagingcontrol-nav-page",IC:"oj-pagingcontrol-nav-page-acc-label",CC:"oj-pagingcontrol-nav-label",wt:"oj-pagingcontrol-nav-input-section",vt:"oj-pagingcontrol-nav-input",BC:"oj-pagingcontrol-nav-input-max",
xt:"oj-pagingcontrol-nav-input-summary",HC:"oj-pagingcontrol-nav-pages-section",At:"oj-pagingcontrol-nav-pages-links",ut:"oj-pagingcontrol-nav-first",zC:"oj-pagingcontrol-nav-first-acc-label",Bt:"oj-pagingcontrol-nav-previous",KC:"oj-pagingcontrol-nav-previous-acc-label",zt:"oj-pagingcontrol-nav-next",FC:"oj-pagingcontrol-nav-next-acc-label",yt:"oj-pagingcontrol-nav-last",DC:"oj-pagingcontrol-nav-last-acc-label",AC:"oj-pagingcontrol-nav-first-icon",LC:"oj-pagingcontrol-nav-previous-icon",GC:"oj-pagingcontrol-nav-next-icon",
EC:"oj-pagingcontrol-nav-last-icon",ug:"oj-widget-icon"},WL:"data-oj-pagenum",Ve:"enabled",uo:"disabled",kt:{jt:"loadMore",xC:"page"},Zd:{xh:"auto",XB:"input",MC:"rangeText",ZL:"pages",mt:"nav"},firstPage:function(){var a=this.ra();if(null!=a){try{a.fetch({startIndex:0}),this.N=0}catch(b){return!1}return!0}return!1},previousPage:function(){var a=this.ra();if(null!=a){var b=this.af();try{this.N=this.Dm(b-1),a.fetch({startIndex:this.N})}catch(c){return!1}return!0}return!1},nextPage:function(){var a=
this.ra();if(null!=a){var b=this.af();try{this.N=this.Dm(b+1),a.fetch({startIndex:this.N})}catch(c){return!1}return!0}return!1},lastPage:function(){var a=this.ra();if(null!=a){try{this.N=this.Dm(this.Ng()),a.fetch({startIndex:this.N})}catch(b){return!1}return!0}return!1},page:function(a){try{this.N=this.Dm(a),this.ra().fetch({startIndex:this.N})}catch(b){return!1}return!0},loadNext:function(){if(null!=this.ra()){try{this.ra().next()}catch(a){return!1}return!0}return!1},refresh:function(){this._super();
this.mc()},_init:function(){this._super();this.N=0;this.ek();this.mc()},_create:function(){this._super();this.ek();this.qj();this._on(this.md)},_destroy:o_a(),qj:function(){var a=this.options;this.element.addClass(this.l.yC);this.element.addClass(this.G.Bo);this.element.attr("tabindex","0");this.N=0;this.lE();this.rE();a.mode==this.kt.jt?(this.sE(),this.tE(),this.Qu()):this.Ru();null!=this.ra()&&0==this.ra().size()&&(this.ra().qe(a.pageSize),this.ra().fetch({startIndex:this.N}))},md:{"click .oj-pagingcontrol-loadmore-link":function(a){this.loadNext();
a.preventDefault()},"click .oj-pagingcontrol-nav-page":function(a){var b=e(a.target).attr("data-oj-pagenum");this.page(b);a.preventDefault()},"click .oj-pagingcontrol-nav-first":function(a){this.firstPage();a.preventDefault()},"click .oj-pagingcontrol-nav-previous":function(a){this.previousPage();a.preventDefault()},"click .oj-pagingcontrol-nav-next":function(a){this.nextPage();a.preventDefault()},"click .oj-pagingcontrol-nav-last":function(a){this.lastPage();a.preventDefault()},"change .oj-pagingcontrol-nav-input":function(d){try{var b=
parseInt(e(d.target).val(),10);this.page(b)}catch(c){throw d=this.n(this.Z.OB),b=this.n(this.Z.NB),new a.v(d,b,a.v.Aa.ERROR);}}},mc:function(){if(this.options.mode==this.kt.jt){var a=this.ra(),b=this.Ej();null!=a&&a.size()==a.totalSize()?b.css("display","none"):(b.css("display",""),this.yI())}else this.zI()},_setOption:o_a(),SD:function(){this.Po=null},TD:function(){this.So=this.Ro=this.Qo=null},af:function(){return 0==this.N?1:Math.ceil((this.N+1)/this.options.pageSize)},ra:function(){if(!this.b&&
null!=this.options.data){var d=this.options.data;if(d instanceof a.Wa||d instanceof a.na)this.b=d;else{var d=this.n(this.Z.ro),b=this.n(this.Z.qo);throw new a.v(d,b,a.v.Aa.ERROR);}this.b.qe(this.options.pageSize);this.$u=this.options.data}return this.b},Uv:function(){var a=this.ra(),b=this.n(this.Z.lt,this.N);null!=a&&(b=-1!=a.totalSize()?this.n(this.Z.lt,this.N+1,this.N+a.size(),a.totalSize()):this.n(this.Z.vC,this.N+1,this.N+a.size()));return b},LF:function(){return this.options.pageOptions.maxPageLinks},
Dm:function(a){var b=(a-1)*this.options.pageSize,c=this.Ng();if(0>b)throw"Value must be greater than 0";if(0<c&&a>c)throw"Value cannot be greater than the total number of pages";return b},Ng:function(){var a=this.ra(),b=-1;null!=a&&(b=a.totalSize());return-1==b?-1:Math.ceil(b/this.options.pageSize)},bq:function(){this.mc()},yI:function(){var a=this.SF();a[0].parentNode.removeChild(a[0]);this.Qu();this.SD()},zI:function(){var a=this.options.pageOptions.layout;this.Dj().empty();this.TD();this.Ru();
this.AI();if(-1<e.inArray(this.Zd.xh,a)){var a=this.element.width(),b=this.$v(),c=this.TF(),f=this.VF(),h=this.UF(),c=b[0].offsetWidth+c[0].offsetWidth;c>a?c-f.width()<=a?f.css("display","none"):c-f.width()-h.width()<=a?(f.css("display","none"),h.css("display","none")):(f.css("display","none"),h.css("display","none"),b.css("display","none")):0<c&&(f.css("display",""),h.css("display",""),b.css("display",""))}},AI:function(){var a=this.$v(),b=a.children("."+this.l.ut);b&&0<b.length&&(b=e(b[0]),1==this.af()?
(b.addClass(this.G.Eb),b.removeClass(this.G.Kc)):(b.addClass(this.G.Kc),b.removeClass(this.G.Eb)));(b=a.children("."+this.l.Bt))&&0<b.length&&(b=e(b[0]),1==this.af()?(b.addClass(this.G.Eb),b.removeClass(this.G.Kc)):(b.addClass(this.G.Kc),b.removeClass(this.G.Eb)));(b=a.children("."+this.l.yt))&&0<b.length&&(b=e(b[0]),this.af()==this.Ng()?(b.addClass(this.G.Eb),b.removeClass(this.G.Kc)):(b.addClass(this.G.Kc),b.removeClass(this.G.Eb)));(a=a.children("."+this.l.zt))&&0<a.length&&(a=e(a[0]),this.af()==
this.Ng()?(a.addClass(this.G.Eb),a.removeClass(this.G.Kc)):(a.addClass(this.G.Kc),a.removeClass(this.G.Eb)))},ek:function(){var d=this.ra();if(null!=d){this.Kb=[];this.Kb.push({eventType:a.Wa.t.SYNC,eventHandler:this.bq.bind(this)});var b;for(b=0;b<this.Kb.length;b++)d.on(this.Kb[b].eventType,this.Kb[b].eventHandler)}},Gh:function(a,b){var c=e(document.createElement("span"));c.addClass(b);c.css("position","absolute");"rtl"===this._GetReadingDirection()?c.css("right","-999em"):c.css("left","-999em");
c.append(a);return c},lE:function(){var a=this.ym(),b=this.n(this.Z.gC),b=this.Gh(b,this.l.nt),c=this.element.attr("id")+"_oj_pgCtrl_acc_label";b.attr("id",c);a.append(b);return b},pE:function(){var a=this.n(this.Z.eC);return this.Gh(a,this.l.IC)},mE:function(){var a=this.n(this.Z.bC);return this.Gh(a,this.l.zC)},nE:function(){var a=this.n(this.Z.cC);return this.Gh(a,this.l.DC)},oE:function(){var a=this.n(this.Z.dC);return this.Gh(a,this.l.FC)},qE:function(){var a=this.n(this.Z.fC);return this.Gh(a,
this.l.KC)},rE:function(){var a=this.ym(),b=e(document.createElement("div"));b.addClass(this.l.ot);var c=this.RF().attr("id");b.attr("role","navigation");b.attr("aria-labelledby",c);a.append(b);return b},sE:function(){var a=this.Dj(),b=e(document.createElement("div"));b.addClass(this.l.pt);a.append(b);return b},tE:function(){var a=this.Ej(),b=e(document.createElement("a"));b.addClass(this.l.qt);var c=this.n(this.Z.hC);b.append(c);b.attr("tabindex","0");b.attr("href","#");a.append(b);return b},Qu:function(){this.ra();
var a=this.Ej(),b=e(document.createElement("span"));b.addClass(this.l.rt);var c=this.Uv();b.append(c);a.append(b);return b},Ru:function(){var a=this.options.pageOptions.layout,b=this.Dj(),c=e(document.createElement("div"));c.addClass(this.l.tt);b.append(c);if(e.inArray(this.Zd.xh,a)||e.inArray(this.Zd.XB,a)){b=e(document.createElement("div"));b.addClass(this.l.wt);c.append(b);var f=e(document.createElement("label"));f.addClass(this.l.CC);var h=this.n(this.Z.iC);f.append(h);b.append(f);h=e(document.createElement("input"));
h.addClass(this.l.vt);var g=this.n(this.Z.VC);this._focusable(this.element);h.attr("title",g);h.attr("tabindex","0");h.val(this.af());f.append(h);0<this.Ng()&&(f=e(document.createElement("span")),f.addClass(this.l.BC),h=this.n(this.Z.jC,this.Ng()),f.append(h),b.append(f));if(e.inArray(this.Zd.xh,a)||e.inArray(this.Zd.MC,a))f=e(document.createElement("span")),f.addClass(this.l.xt),h=this.Uv(),h=this.n(this.Z.kC,h),f.append(h),b.append(f)}if(e.inArray(this.Zd.xh,a)||e.inArray(this.Zd.mt,a)){var l=e(document.createElement("div"));
l.addClass(this.l.st);c.append(l);b=e(document.createElement("a"));b.addClass(this.l.ut);b.addClass(this.l.AC);b.addClass(this.l.ug);b.addClass(this.G.rg);b.addClass(this.G.Eb);f=this.n(this.Z.UC);this._hoverable(b);this._focusable(b);b.attr("title",f);b.attr("tabindex","0");b.attr("href","#");f=this.mE();b.append(f);l.append(b);b=e(document.createElement("a"));b.addClass(this.l.Bt);b.addClass(this.l.LC);b.addClass(this.l.ug);b.addClass(this.G.rg);b.addClass(this.G.Eb);f=this.n(this.Z.ZC);this._hoverable(b);
this._focusable(b);b.attr("title",f);b.attr("tabindex","0");b.attr("href","#");f=this.qE();b.append(f);l.append(b)}if(e.inArray(this.Zd.xh,a)||e.inArray(this.Zd.xC,a))b=e(document.createElement("div")),b.addClass(this.l.HC),l.append(b),this.uE(b,this.LF());if(e.inArray(this.Zd.xh,a)||e.inArray(this.Zd.mt,a))a=e(document.createElement("a")),a.addClass(this.l.zt),a.addClass(this.l.GC),a.addClass(this.l.ug),a.addClass(this.G.rg),a.addClass(this.G.Eb),b=this.n(this.Z.XC),this._hoverable(a),this._focusable(a),
a.attr("title",b),a.attr("tabindex","0"),a.attr("href","#"),b=this.oE(),a.append(b),l.append(a),a=e(document.createElement("a")),a.addClass(this.l.yt),a.addClass(this.l.EC),a.addClass(this.l.ug),a.addClass(this.G.rg),a.addClass(this.G.Eb),b=this.n(this.Z.WC),this._hoverable(a),this._focusable(a),a.attr("title",b),a.attr("tabindex","0"),a.attr("href","#"),b=this.nE(),a.append(b),l.append(a);return c},uE:function(d,b){if(5>b){var c=this.n(this.Z.MB),f=this.n(this.Z.LB);throw new a.v(c,f,a.v.Aa.ERROR);
}c=e(document.createElement("div"));c.addClass(this.l.At);d.append(c);var f=this.Ng(),h=this.af(),g=b,l=[];if(1<=h){if(-1!=f&&f<=g)for(g=0;g<f;g++)l[g]=g+1;else{l.push(1);1!=h&&l.push(h);h!=f&&-1!=f&&l.push(f);var g=g-l.length,k=h-1,m=1;if(h==f||h==f-1)m=0;for(;g>m&&1<k;)l.push(k),k--,g--;h+=1;for(-1==f&&(g=1);0<g&&(h<=f||-1==f);)l.push(h),h++,g--}l.sort(function(a,b){return a-b});for(g=0;g<l.length;g++)h=l[g],this.gp(c,h),g!=l.length-1&&h!=l[g+1]-1&&this.gp(c,-1);-1==f&&this.gp(c,-1)}return c},gp:function(a,
b){var c=this.af(),f=null;-1==b?(f=e(document.createElement("span")),f.append("...")):(c==b?(f=e(document.createElement("div")),f.addClass(this.G.Fb),f.addClass(this.G.mo),f.addClass(this.G.Eb),f.removeClass(this.G.Kc)):(f=e(document.createElement("a")),f.removeClass(this.G.Fb),f.removeClass(this.G.mo),f.removeClass(this.G.Eb),f.addClass(this.G.Kc)),f.attr("data-oj-pagenum",b),f.addClass(this.l.JC),c=this.n(this.Z.YC,b.toString()),this._hoverable(f),this._focusable(f),f.attr("title",c),f.attr("tabindex",
"0"),f.attr("href","#"),c=this.pE(),f.append(c),f.append(b.toString()),this._hoverable(f));a.append(f);return f},RF:function(){var a=this.ym(),b=null;a&&(b=a.find("."+this.l.nt))&&0<b.length&&(b=e(b.get(0)));return b},ym:function(){return e(this.element)},Dj:function(){if(!this.gu){var a=this.ym(),b=null;a&&(b=a.find("."+this.l.ot))&&0<b.length&&(this.gu=e(b.get(0)))}return this.gu},Ej:function(){if(!this.hu){var a=this.Dj(),b=null;a&&(b=a.children("."+this.l.pt))&&0<b.length&&(this.hu=e(b.get(0)))}return this.hu},
uM:function(){if(!this.iu){var a=this.Ej(),b=null;a&&(b=a.children("."+this.l.qt))&&0<b.length&&(this.iu=e(b.get(0)))}return this.iu},SF:function(){if(!this.Po){var a=this.Ej(),b=null;a&&(b=a.children("."+this.l.rt))&&0<b.length&&(this.Po=e(b.get(0)))}return this.Po},Fj:function(){if(!this.Qo){var a=this.Dj(),b=null;a&&(b=a.children("."+this.l.tt))&&0<b.length&&(this.Qo=e(b.get(0)))}return this.Qo},vM:function(){if(!this.Ro){var a=this.Fj(),b=null;a&&(b=a.find("."+this.l.vt))&&0<b.length&&(this.Ro=
e(b.get(0)))}return this.Ro},UF:function(){if(!this.So){var a=this.Fj(),b=null;a&&(b=a.find("."+this.l.xt))&&0<b.length&&(this.So=e(b.get(0)))}return this.So},VF:function(){var a=this.Fj(),b=null;a&&(b=a.find("."+this.l.At))&&0<b.length&&(b=e(b.get(0)));return b},$v:function(){var a=this.Fj(),b=null;a&&(b=a.find("."+this.l.st))&&0<b.length&&(b=e(b.get(0)));return b},TF:function(){var a=this.Fj(),b=null;a&&(b=a.find("."+this.l.wt))&&0<b.length&&(b=e(b.get(0)));return b}})})();a.Wa=function(a){this.ta=
a;this.i()};o_("PagingDataSource",a.Wa,a);a.a.ea(a.Wa,a.sc,"oj.PagingDataSource");a.Wa.prototype.i=function(){a.Wa.q.i.call(this)};a.a.c("PagingDataSource.prototype.Init",{i:a.Wa.prototype.i});a.Wa.prototype.fetch=function(){a.f.va()};a.a.c("PagingDataSource.prototype.fetch",{fetch:a.Wa.prototype.fetch});a.Wa.prototype.hasMore=function(){a.f.va();return!1};a.a.c("PagingDataSource.prototype.hasMore",{hasMore:a.Wa.prototype.hasMore});a.Wa.prototype.next=function(){a.f.va()};a.a.c("PagingDataSource.prototype.next",
{next:a.Wa.prototype.next});a.Wa.prototype.previous=function(){a.f.va()};a.a.c("PagingDataSource.prototype.previous",{previous:a.Wa.prototype.previous});a.Wa.prototype.qe=function(){a.f.va()};a.Wa.prototype.startIndex=function(){a.f.va();return 0};a.a.c("PagingDataSource.prototype.startIndex",{startIndex:a.Wa.prototype.startIndex});a.Wa.prototype.size=function(){a.f.va();return 0};a.a.c("PagingDataSource.prototype.size",{size:a.Wa.prototype.size});a.Wa.prototype.totalSize=function(){a.f.va();return 0};
a.a.c("PagingDataSource.prototype.totalSize",{totalSize:a.Wa.prototype.totalSize});a.Wa.t={SYNC:"sync"};o_("PagingDataSource.EventType",a.Wa.t,a)});
//# sourceMappingURL=oj-modular.map