define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(a,e){a.$=function(d){d=d||{};this.Wk=d.root;this.oK=d.childCollectionCallback;this.Ki=d.parseMetadata;this.sh=null;this.Ni="none";this.Nb={};a.$.q.constructor.call(this)};o_("CollectionTreeDataSource",a.$,a);a.$.prototype.Ki=function(a){return{key:a.idAttribute+"\x3d"+a.id}};a.a.ea(a.$,a.Db,"oj.CollectionTreeDataSource");a.$.prototype.i=function(){a.$.q.i.call(this)};a.a.c("CollectionTreeDataSource.prototype.Init",
{i:a.$.prototype.i});a.$.prototype.mf=function(a){var b=this.Nb[a];if(b&&0<b.length)return b.length;this.qr(a,{success:function(a){return a.length}});return-1};a.a.c("CollectionTreeDataSource.prototype.getChildCount",{mf:a.$.prototype.mf});a.$.prototype.qr=function(a,b){this.dd(a,null,{success:function(a){b.success(a.V)},error:b.error})};a.a.c("CollectionTreeDataSource.prototype.getChildCollection",{qr:a.$.prototype.qr});a.$.prototype.dd=function(a,b,c){b=b||{};var e=b.start?b.start:0,h=b.count?b.count:
-1;if(null===a)this.Si(null,e,h,c,null);else{var g=this;this.Pp(this.Wk,a,0).done(function(b){b?(b=g.hl(b.Fc),g.Si(b,e,h,c,a)):c&&c.error&&c.error(a)})}};a.a.c("CollectionTreeDataSource.prototype.fetchChildren",{dd:a.$.prototype.dd});a.$.prototype.lB=function(a,b,c){var e=0;c&&c.at&&(e=c.at);a=this.cm(this,"insert",e,this.zm(b),this.Bx(a));this.handleEvent("insert",a)};a.$.prototype.mB=function(a,b,c){var e=0;c&&c.index&&(e=c.index);this.MI(a);a=this.cm(this,"delete",e,this.zm(b),null);this.handleEvent("delete",
a)};a.$.prototype.nB=function(a){var b=this.rF(a),c=null,e=null;b&&(c=b.index,e=this.zm(b.V));a=this.cm(this,"update",c,e,this.Bx(a));this.handleEvent("update",a)};a.$.prototype.YA=function(a){a=this.cm(this,"refresh",null,this.zm(a),null);this.handleEvent("refresh",a)};a.$.prototype.Bx=function(d){var b=[];b.push(d.attributes);var c={};c.idAttribute=d.idAttribute;d=new a.k(b,c);d.fetch();return d};a.$.prototype.zm=function(d){var b=[],c=null;do c=this.WF(d),null!==c&&(c!==a.$.Bs&&b.unshift(c),d=
this.sF(c));while(null!=c);return b};a.$.Bs="%!@ROOT%#@!";a.$.prototype.qm=function(d){var b=d instanceof a.h?this.Ki(d).key:d;return d?b:a.$.Bs};a.$.prototype.Lt=function(a){return this.Nb[this.qm(a)]};a.$.prototype.uy=function(d,b){b.on(a.L.t.ADD,this.lB,this);b.on(a.L.t.REMOVE,this.mB,this);b.on(a.L.t.CHANGE,this.nB,this);b.on(a.L.t.SYNC,this.YA,this);this.Nb[this.qm(d)]=b};a.$.prototype.MI=function(a){a=this.qm(a);for(var b in this.Nb)if(this.Nb.hasOwnProperty(b)&&b===a){this.Nb[a].off(null,null,
this);delete this.Nb[a];break}};a.$.prototype.IH=function(a,b){for(var c=b.length,e=0;e<c;e++){var h=this.qm(b.at(e));if(a===h)return!0}return!1};a.$.prototype.rF=function(a){for(var b in this.Nb)if(this.Nb.hasOwnProperty(b))for(var c=this.Nb[b],e=0;e<c.length;e++)if(c.at(e)===a)return{index:e,V:c};return null};a.$.prototype.sF=function(a){for(var b in this.Nb)if(this.Nb.hasOwnProperty(b)){var c=this.Nb[b];if(this.IH(a,c))return c}return null};a.$.prototype.WF=function(a){for(var b in this.Nb)if(this.Nb.hasOwnProperty(b)&&
this.Nb[b]===a)return b;return null};a.$.prototype.hl=function(a){var b=!0,c=this.Lt(a);c||(b=!1,c=this.oK(this.Wk,a),null!=c&&(this.$t(c),this.uy(a,c)));return{V:c,dr:b}};a.$.prototype.cm=function(a,b,c,e,h){return{source:a,operation:b,index:c,parent:e,data:h}};a.$.prototype.Si=function(a,b,c,e,h){var g=this;null===a&&((a=this.Lt(null))?a={V:a,dr:!0}:(a={V:g.Wk,dr:!1},g.uy(null,this.Wk)));a&&g.uv(a,function(a){e.success&&e.success(g.QF(a,h,b,c))},e.error)};a.$.prototype.QF=function(d,b,c,e){return new a.Zb(b,
d,this,c,e)};a.$.prototype.bJ=function(a,b){function c(a,b,d){a<b.length?b.at(a,{deferred:!0}).done(function(e){if(e){var n=h.Ki(e);if(d===n.key)return f.resolve(e),f}a++;c(a,b,d)}):f.resolve(null)}var f=e.Deferred(),h=this;c(0,a,b);return f};a.$.prototype.Pp=function(a,b,c){var f=e.Deferred(),h=this;this.bJ(a,b).done(function(e){function l(e,n){if(e<k){var g=n.hl(a.at(e));g.V?n.uv(g,function(a){n.Pp(a,b,c+1).done(function(a){a?f.resolve(a):(e++,l(e,n))})},null):(e++,l(e,n))}else f.resolve(null)}
if(e)return f.resolve({Fc:e,depth:c}),f;var k=a.length;l(0,h)});return f.promise()};a.$.prototype.uv=function(a,b,c){a.dr?b(a.V):(this.sh&&"none"!==this.sh&&(a.V.jf=this.sh,a.V.wf=this.Ni),0<a.V.length?b(a.V):a.V.fetch({success:function(a){b(a)},error:c}))};a.$.prototype.lf=function(a,b){var c=this;null===a?this.Si(null,0,-1,{success:function(a){a.qs({success:function(){b.success&&b.success(a)}})}},null):this.Pp(this.Wk,a,0).done(function(e){e&&(e=c.hl(e.Fc),c.Si(e,0,-1,{success:function(a){a.qs({success:function(){b.success&&
b.success(a)}})}},a))})};a.a.c("CollectionTreeDataSource.prototype.fetchDescendents",{lf:a.$.prototype.lf});a.$.prototype.sort=function(a,b){var c=a.key,e=a.direction,h=!1;c!==this.sh&&(this.sh=c,h=!0);e!==this.Ni&&(this.Ni=e,h=!0);if(h){"none"===this.Ni&&(this.Nb={});for(var g in this.Nb)this.Nb.hasOwnProperty(g)&&this.$t(this.Nb[g])}b&&b.success&&b.success()};a.a.c("CollectionTreeDataSource.prototype.sort",{sort:a.$.prototype.sort});a.$.prototype.$t=function(a){a.comparator=this.sh;a.sortDirection=
"ascending"===this.Ni?1:-1;a.sort()};a.$.prototype.Ak=function(){return{key:this.sh,direction:this.Ni}};a.a.c("CollectionTreeDataSource.prototype.getSortCriteria",{Ak:a.$.prototype.Ak});a.$.prototype.move=function(){a.f.va()};a.a.c("CollectionTreeDataSource.prototype.move",{move:a.$.prototype.move});a.$.prototype.Uk=o_d("invalid");a.a.c("CollectionTreeDataSource.prototype.moveOK",{Uk:a.$.prototype.Uk});a.$.prototype.bb=function(a){return"sort"===a?"default":"move"===a?"none":"batchFetch"===a||"fetchDescendants"===
a?"disable":null};a.a.c("CollectionTreeDataSource.prototype.getCapability",{bb:a.$.prototype.bb});a.Zb=function(a,b,c,e,h){this.mL=a;this.V=b;this.ir=[];this.$k=c;this.start=e<b.length?e:b.length-1;this.count=-1===h?b.length:Math.min(b.length,h)};o_("CollectionNodeSet",a.Zb,a);a.Zb.prototype.qs=function(a){this.wv(this).done(function(){a.success&&a.success()})};a.Zb.prototype.wv=function(a){function b(e){e<f?a.cB(e,{success:function(c){null!==c?a.wv(c).done(function(){b(e+1)}):b(e+1)}}):c.resolve()}
var c=e.Deferred(),f=a.S();b(0);return c.promise()};a.Zb.prototype.cB=function(a,b){var c=this.V.at(a);if(this.$k.Ki(c).leaf)this.ir[a]=null,b.success(null);else{var e=this.$k.hl(c),c=this.$k.Ki(c).key,h=this;this.$k.Si(e,0,-1,{success:function(c){h.ir[a]=c;b.success(c)}},c)}};a.Zb.prototype.getParent=o_c("mL");a.a.c("CollectionNodeSet.prototype.getParent",{getParent:a.Zb.prototype.getParent});a.Zb.prototype.wa=o_c("start");a.a.c("CollectionNodeSet.prototype.getStart",{wa:a.Zb.prototype.wa});a.Zb.prototype.S=
o_c("count");a.a.c("CollectionNodeSet.prototype.getCount",{S:a.Zb.prototype.S});a.Zb.prototype.getData=function(a){this.Zo(a);return this.V.at(a).attributes};a.a.c("CollectionNodeSet.prototype.getData",{getData:a.Zb.prototype.getData});a.Zb.prototype.Zo=function(a){if(a<this.start||a>this.start+this.count)throw"Out of range";};a.Zb.prototype.getMetadata=function(a){this.Zo(a);var b={};a=this.V.at(a);a=this.$k.Ki(a);b.key=a.key;b.leaf=a.leaf;b.depth=a.depth;return b};a.a.c("CollectionNodeSet.prototype.getMetadata",
{getMetadata:a.Zb.prototype.getMetadata});a.Zb.prototype.gg=function(a){this.Zo(a);return this.ir[a]};a.a.c("CollectionNodeSet.prototype.getChildNodeSet",{gg:a.Zb.prototype.gg})});
//# sourceMappingURL=oj-modular.map