define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(a,e){a.ea=function(d){d=d||{};this.Fl=d.root;this.nM=d.childCollectionCallback;this.mj=d.parseMetadata;this.Vh=null;this.qj="none";this.Xb={};a.ea.j.constructor.call(this)};o_("CollectionTreeDataSource",a.ea,a);a.ea.prototype.mj=function(a){return{key:a.idAttribute+"\x3d"+a.id}};a.a.aa(a.ea,a.Rb,"oj.CollectionTreeDataSource");a.ea.prototype.h=function(){a.ea.j.h.call(this)};a.a.b("CollectionTreeDataSource.prototype.Init",
{h:a.ea.prototype.h});a.ea.prototype.Me=function(a){var b=this.Xb[a];if(b&&0<b.length)return b.length;this.ss(a,{success:function(a){return a.length}});return-1};a.a.b("CollectionTreeDataSource.prototype.getChildCount",{Me:a.ea.prototype.Me});a.ea.prototype.ss=function(a,b){this.dd(a,null,{success:function(a){b.success(a.Z)},error:b.error})};a.a.b("CollectionTreeDataSource.prototype.getChildCollection",{ss:a.ea.prototype.ss});a.ea.prototype.dd=function(a,b,c){b=b||{};var e=b.start?b.start:0,h=b.count?
b.count:-1;if(null===a)this.vj(null,e,h,c,null);else{var g=this;this.Hq(this.Fl,a,0).done(function(b){b?(b=g.Rl(b.Vc),g.vj(b,e,h,c,a)):c&&c.error&&c.error(a)})}};a.a.b("CollectionTreeDataSource.prototype.fetchChildren",{dd:a.ea.prototype.dd});a.ea.prototype.RC=function(a,b,c){var e=0;c&&c.at&&(e=c.at);a=this.Sm(this,"insert",e,this.qn(b),this.Wy(a));this.handleEvent("insert",a)};a.ea.prototype.SC=function(a,b,c){var e=0;c&&c.index&&(e=c.index);this.FK(a);a=this.Sm(this,"delete",e,this.qn(b),null);
this.handleEvent("delete",a)};a.ea.prototype.TC=function(a){var b=this.YG(a),c=null,e=null;b&&(c=b.index,e=this.qn(b.Z));a=this.Sm(this,"update",c,e,this.Wy(a));this.handleEvent("update",a)};a.ea.prototype.CC=function(a){a=this.Sm(this,"refresh",null,this.qn(a),null);this.handleEvent("refresh",a)};a.ea.prototype.Wy=function(d){var b=[];b.push(d.attributes);var c={};c.idAttribute=d.idAttribute;d=new a.L(b,c);d.fetch();return d};a.ea.prototype.qn=function(d){var b=[],c=null;do c=this.CH(d),null!==c&&
(c!==a.ea.Gt&&b.unshift(c),d=this.ZG(c));while(null!=c);return b};a.ea.Gt="%!@ROOT%#@!";a.ea.prototype.gn=function(d){var b=d instanceof a.i?this.mj(d).key:d;return d?b:a.ea.Gt};a.ea.prototype.Su=function(a){return this.Xb[this.gn(a)]};a.ea.prototype.Rz=function(d,b){b.on(a.H.q.ADD,this.RC,this);b.on(a.H.q.REMOVE,this.SC,this);b.on(a.H.q.CHANGE,this.TC,this);b.on(a.H.q.SYNC,this.CC,this);this.Xb[this.gn(d)]=b};a.ea.prototype.FK=function(a){a=this.gn(a);for(var b in this.Xb)if(this.Xb.hasOwnProperty(b)&&
b===a){this.Xb[a].off(null,null,this);delete this.Xb[a];break}};a.ea.prototype.sJ=function(a,b){for(var c=b.length,e=0;e<c;e++){var h=this.gn(b.at(e));if(a===h)return!0}return!1};a.ea.prototype.YG=function(a){for(var b in this.Xb)if(this.Xb.hasOwnProperty(b))for(var c=this.Xb[b],e=0;e<c.length;e++)if(c.at(e)===a)return{index:e,Z:c};return null};a.ea.prototype.ZG=function(a){for(var b in this.Xb)if(this.Xb.hasOwnProperty(b)){var c=this.Xb[b];if(this.sJ(a,c))return c}return null};a.ea.prototype.CH=
function(a){for(var b in this.Xb)if(this.Xb.hasOwnProperty(b)&&this.Xb[b]===a)return b;return null};a.ea.prototype.Rl=function(a){var b=!0,c=this.Su(a);c||(b=!1,c=this.nM(this.Fl,a),null!=c&&(this.fv(c),this.Rz(a,c)));return{Z:c,fs:b}};a.ea.prototype.Sm=function(a,b,c,e,h){return{source:a,operation:b,index:c,parent:e,data:h}};a.ea.prototype.vj=function(a,b,c,e,h){var g=this;null===a&&((a=this.Su(null))?a={Z:a,fs:!0}:(a={Z:g.Fl,fs:!1},g.Rz(null,this.Fl)));a&&g.Ew(a,function(a){e.success&&e.success(g.wH(a,
h,b,c))},e.error)};a.ea.prototype.wH=function(d,b,c,e){return new a.ic(b,d,this,c,e)};a.ea.prototype.WK=function(a,b){function c(a,b,d){a<b.length?b.at(a,{deferred:!0}).done(function(e){if(e){var m=h.mj(e);if(d===m.key)return f.resolve(e),f}a++;c(a,b,d)}):f.resolve(null)}var f=e.Deferred(),h=this;c(0,a,b);return f};a.ea.prototype.Hq=function(a,b,c){var f=e.Deferred(),h=this;this.WK(a,b).done(function(e){function l(e,m){if(e<k){var g=m.Rl(a.at(e));g.Z?m.Ew(g,function(a){m.Hq(a,b,c+1).done(function(a){a?
f.resolve(a):(e++,l(e,m))})},null):(e++,l(e,m))}else f.resolve(null)}if(e)return f.resolve({Vc:e,depth:c}),f;var k=a.length;l(0,h)});return f.promise()};a.ea.prototype.Ew=function(a,b,c){a.fs?b(a.Z):(this.Vh&&"none"!==this.Vh&&(a.Z.ee=this.Vh,a.Z.oe=this.qj),0<a.Z.length?b(a.Z):a.Z.fetch({success:function(a){b(a)},error:c}))};a.ea.prototype.Kf=function(a,b){var c=this;null===a?this.vj(null,0,-1,{success:function(a){a.ut({success:function(){b.success&&b.success(a)}})}},null):this.Hq(this.Fl,a,0).done(function(e){e&&
(e=c.Rl(e.Vc),c.vj(e,0,-1,{success:function(a){a.ut({success:function(){b.success&&b.success(a)}})}},a))})};a.a.b("CollectionTreeDataSource.prototype.fetchDescendents",{Kf:a.ea.prototype.Kf});a.ea.prototype.sort=function(a,b){var c=a.key,e=a.direction,h=!1;c!==this.Vh&&(this.Vh=c,h=!0);e!==this.qj&&(this.qj=e,h=!0);if(h){"none"===this.qj&&(this.Xb={});for(var g in this.Xb)this.Xb.hasOwnProperty(g)&&this.fv(this.Xb[g])}b&&b.success&&b.success()};a.a.b("CollectionTreeDataSource.prototype.sort",{sort:a.ea.prototype.sort});
a.ea.prototype.fv=function(a){a.comparator=this.Vh;a.sortDirection="ascending"===this.qj?1:-1;a.sort()};a.ea.prototype.il=function(){return{key:this.Vh,direction:this.qj}};a.a.b("CollectionTreeDataSource.prototype.getSortCriteria",{il:a.ea.prototype.il});a.ea.prototype.move=function(){a.f.Q()};a.a.b("CollectionTreeDataSource.prototype.move",{move:a.ea.prototype.move});a.ea.prototype.Dl=o_d("invalid");a.a.b("CollectionTreeDataSource.prototype.moveOK",{Dl:a.ea.prototype.Dl});a.ea.prototype.Ua=function(a){return"sort"===
a?"default":"move"===a?"none":"batchFetch"===a||"fetchDescendants"===a?"disable":null};a.a.b("CollectionTreeDataSource.prototype.getCapability",{Ua:a.ea.prototype.Ua});a.ic=function(a,b,c,e,h){this.pN=a;this.Z=b;this.ks=[];this.Ll=c;this.start=e<b.length?e:b.length-1;this.count=-1===h?b.length:Math.min(b.length,h)};o_("CollectionNodeSet",a.ic,a);a.ic.prototype.ut=function(a){this.Gw(this).done(function(){a.success&&a.success()})};a.ic.prototype.Gw=function(a){function b(e){e<f?a.IC(e,{success:function(c){null!==
c?a.Gw(c).done(function(){b(e+1)}):b(e+1)}}):c.resolve()}var c=e.Deferred(),f=a.R();b(0);return c.promise()};a.ic.prototype.IC=function(a,b){var c=this.Z.at(a);if(this.Ll.mj(c).leaf)this.ks[a]=null,b.success(null);else{var e=this.Ll.Rl(c),c=this.Ll.mj(c).key,h=this;this.Ll.vj(e,0,-1,{success:function(c){h.ks[a]=c;b.success(c)}},c)}};a.ic.prototype.getParent=o_c("pN");a.a.b("CollectionNodeSet.prototype.getParent",{getParent:a.ic.prototype.getParent});a.ic.prototype.pa=o_c("start");a.a.b("CollectionNodeSet.prototype.getStart",
{pa:a.ic.prototype.pa});a.ic.prototype.R=o_c("count");a.a.b("CollectionNodeSet.prototype.getCount",{R:a.ic.prototype.R});a.ic.prototype.getData=function(a){this.Op(a);return this.Z.at(a).attributes};a.a.b("CollectionNodeSet.prototype.getData",{getData:a.ic.prototype.getData});a.ic.prototype.Op=function(a){if(a<this.start||a>this.start+this.count)throw"Out of range";};a.ic.prototype.getMetadata=function(a){this.Op(a);var b={};a=this.Z.at(a);a=this.Ll.mj(a);b.key=a.key;b.leaf=a.leaf;b.depth=a.depth;
return b};a.a.b("CollectionNodeSet.prototype.getMetadata",{getMetadata:a.ic.prototype.getMetadata});a.ic.prototype.Sc=function(a){this.Op(a);return this.ks[a]};a.a.b("CollectionNodeSet.prototype.getChildNodeSet",{Sc:a.ic.prototype.Sc})});
//# sourceMappingURL=oj-modular.map