define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){window.adf||(window.adf={});var a=window.adf;a.D=a.D||{};a.D.G=a.D.G||{};a.D.G.J=a.D.G.J||{};a.D.G.J.K=function(a,b,f,e,g,k){this.Kg=a;this.kM=b;this.gr=f;this.Mn=e;g&&(g.uQ&&(this.vM=g.uQ),g.mQ&&(this.gM=g.mQ),g.iE&&(this.wM=g.iE),g.bE&&(this.hM=g.bE),g.hE&&(this.uM=g.hE),g.aE&&(this.fM=g.aE));k&&(k.oE&&(this.qB=k.oE),k.oP&&(this.Ir=k.oP),k.PO&&(this.Oh=k.PO),k.eh&&(this.Hn=k.eh),k.Lm&&(this.ep=k.Lm));this.Nq=!0;this.hj=0;a=navigator.userAgent.toLowerCase();
if(-1!==a.indexOf("gecko/"))this.rH=!0;else if(-1!==a.indexOf("opera"))this.sH=!0;else if(-1!==a.indexOf("applewebkit")||-1!==a.indexOf("safari"))this.tH=!0};a.D.G.J.K.prototype.NQ=function(b){var c=this,f=a.D.G.J.K;if(b){this.cI();this.rI(this.vM,this.wM,this.uM);this.eI(this.gM,this.hM,this.fM);var e=this.$o,g=this.np;g?(this.Pn=g.offsetWidth,this.On=e.offsetHeight):(g=this.tp,this.Pn=e.offsetWidth,this.On=g.offsetHeight);this.Io();this.Ho();this.Gl=function(a){c.PK(a)};f.Rf(this.Kg,"mousewheel",
this.Gl);f.Rf(this.Kg,"wheel",this.Gl);this.wt=function(a){c.WK(a)};f.Rf(this.pc,"touchstart",this.wt);this.vt=function(a){c.VK(a)};f.Rf(this.pc,"touchmove",this.vt);this.Wl=function(){c.UK()};f.Rf(this.pc,"touchend",this.Wl);f.Rf(this.pc,"touchcancel",this.Wl);this.Ss=0}else this.WA();this.cr();this.Rw(b);this.bi(!0);b&&this.Hn&&(this.tj=function(){c.bi(!1)},this.Hn.call(this.Oh,this.Kg,this.tj),this.Hn.call(this.Oh,this.Hg,this.tj))};a.D.G.J.K.prototype.destroy=function(){var b=this.Kg,c=a.D.G.J.K;
c.Gj(b,"mousewheel",this.Gl);c.Gj(b,"wheel",this.Gl);c.Gj(this.pc,"touchstart",this.wt);c.Gj(this.pc,"touchmove",this.vt);c.Gj(this.pc,"touchend",this.Wl);c.Gj(this.pc,"touchcancel",this.Wl);this.Wl=this.vt=this.wt=this.Gl=null;this.ep&&this.tj&&(this.ep.call(this.Oh,b,this.tj),this.ep.call(this.Oh,this.Hg,this.tj));this.tj=null;c.kN(this.hr,b);this.Zw=null;this.tt?b.removeChild(this.tt):(b.removeChild(this.pc),b.removeChild(this.tp),b.removeChild(this.Bt));this.tp=this.Bt=this.Os=this.Ws=this.np=
this.st=this.tt=this.hr=this.pc=this.Hg=this.Vs=this.$o=null;this.cr();this.Oh=this.ep=this.Hn=this.Ir=this.qB=this.Kg=null};a.D.G.J.K.lN=function(b,c,f){var e=a.D.G.J.K,g=null;f&&(g=e.mr(),c.appendChild(g));var k=null;for(b=b.childNodes;0<b.length;){k||(k=[]);var l=b[0];if(1===l.nodeType){f||(g=e.mr(),c.appendChild(g));var m=e.Yn();m.appendChild(l);g.appendChild(m);k.push(l)}else f?g.appendChild(l):c.appendChild(l)}return k};a.D.G.J.K.kN=function(a,b){if(a)for(var f=a.childNodes;0<f.length;){var e=
f[0];if(1===e.nodeType){for(var g=e.childNodes;0<g.length;){var k=g[0];1===k.nodeType?(b.appendChild(k.firstChild),e.removeChild(k)):b.appendChild(k)}a.removeChild(e)}else b.appendChild(e)}};a.D.G.J.K.Ly=function(a){var b=a.ownerDocument.defaultView,f=null;return f=b?b.getComputedStyle(a,null):a.currentStyle};a.D.G.J.K.uJ=function(b){var c=a.D.G.J.K;b=c.Ly(b);return c.Hy(b.width)};a.D.G.J.K.tJ=function(b){var c=a.D.G.J.K;b=c.Ly(b);return c.Hy(b.height)};a.D.G.J.K.Hy=function(a){return 0<a.length&&
"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0};a.D.G.J.K.Rf=function(a,b,f){a.addEventListener?a.addEventListener(b,f,!1):a.attachEvent&&a.attachEvent("on"+b,f)};a.D.G.J.K.Gj=function(a,b,f){a.removeEventListener?a.removeEventListener(b,f,!1):a.detachEvent&&a.detachEvent("on"+b,f)};a.D.G.J.K.hK=function(a){var b=0;return b=null!=a.wheelDelta?a.wheelDelta:null!=a.deltaY?-a.deltaY:-a.detail};a.D.G.J.K.Tx=function(){var a=document.createElement("div");a.style.display="table";return a};a.D.G.J.K.mr=
function(){var a=document.createElement("div");a.style.display="table-row";return a};a.D.G.J.K.Yn=function(){var a=document.createElement("div");a.style.display="table-cell";return a};a.D.G.J.K.uC=function(a,b,f,e){var g=document.createElement("div"),k=g.style;k.display="inline-block";g.appendChild(a);b.appendChild(g);f&&(k.maxWidth=g.offsetWidth+"px");e&&(k.maxHeight=g.offsetHeight+"px");return g};a.D.G.J.K.prototype.Oc=function(){return"horizontal"===this.kM};a.D.G.J.K.prototype.vL=function(){return!this.My().hasChildNodes()};
a.D.G.J.K.prototype.WA=function(){this.Ss=this.Td();this.Gx();this.lt(0);this.Io();this.Ho()};a.D.G.J.K.prototype.cr=function(){this.lp=this.Ue=null};a.D.G.J.K.prototype.bi=function(a){a||this.WA();this.cr();this.Ue&&this.lp||(this.Ue=this.dA());a||this.Rw();a=this.Ue;this.gH(a.Ec,a.jg)};a.D.G.J.K.prototype.gH=function(a,b){var f=this.$o.style,e=this.Vs.style;if(this.Oc()){var g=0.5*(b-this.On);f.top=g+"px";e.top=g+"px"}else g=0.5*(a-this.Pn),this.Mn?(f.left=-g+"px",e.left=-g+"px"):(f.left=g+"px",
e.left=g+"px")};a.D.G.J.K.prototype.Rw=function(b){var c=this.Hg,f=this.Oc(),e=a.D.G.J.K,e=f?e.uJ(this.Kg):e.tJ(this.Kg);(f?c.offsetWidth:c.offsetHeight)>e&&this.IB(e);this.Fl=0;this.Cl=f?c.offsetWidth-e+this.Pn:c.offsetHeight-e+this.On;0>this.Cl&&(this.Cl=0);this.Io();this.Ho();this.Kj(b?this.Fl:this.Ss,!0);this.Ss=0};a.D.G.J.K.prototype.cI=function(){var b=this,c=this.Oc(),f=document.createElement("div");this.pc=f;var e=f.style;e.overflow="hidden";e.display=this.fl();e.position="relative";c&&(e.verticalAlign=
"top");var g=this.Kg,k=a.D.G.J.K,l=document.createElement("div");this.Hg=l;var m=l.style;m.position="relative";c&&(m.display="inline-block");f.appendChild(l);m=null;if(c){this.tt=m=k.Tx();var n=k.mr(),q=k.Yn();this.st=q;var r=k.Yn(),p=k.Yn();this.np=p;r.appendChild(f);n.appendChild(q);n.appendChild(r);n.appendChild(p);m.appendChild(n)}n=k.Tx();q=k.lN(g,n,c);if(this.gr)for(var q=[],r=this.gr.children,p=r.length,s=0;s<p;s++){var v=r[s];1===v.nodeType&&q.push(v)}(this.Zw=q)&&0<q.length&&(this.hr=n,l.appendChild(n));
m?g.appendChild(m):(this.Bt=m=document.createElement("div"),this.tp=n=document.createElement("div"),g.appendChild(m),g.appendChild(f),g.appendChild(n));c&&(c=f.offsetHeight,l=l.offsetHeight,c>l&&(e.marginBottom=l-c+"px"));k.Rf(f,"scroll",function(a){b.ps(a)})};a.D.G.J.K.prototype.fl=function(){return this.Oc()?"inline-block":"block"};a.D.G.J.K.prototype.rI=function(b,c,f){var e=this,g=document.createElement("div");this.Vs=g;b&&g.setAttribute("id",b);g.setAttribute("class",c);g.setAttribute("aria-hidden",
"true");c=g.style;c.display=this.fl();c.position="relative";if(b=this.Oc())c.verticalAlign="top";c=a.D.G.J.K;c.Rf(g,"click",function(){e.sB()});this.st?this.Ws=c.uC(g,this.st,b,!b):this.Bt.appendChild(g);f&&g.appendChild(f)};a.D.G.J.K.prototype.eI=function(b,c,e){var h=this,g=document.createElement("div");this.$o=g;b&&g.setAttribute("id",b);g.setAttribute("class",c);g.setAttribute("aria-hidden","true");c=g.style;c.display=this.fl();c.position="relative";if(b=this.Oc())c.verticalAlign="top";c=a.D.G.J.K;
c.Rf(g,"click",function(){h.rB()});this.np?this.Os=c.uC(g,this.np,b,!b):this.tp.appendChild(g);e&&g.appendChild(e)};a.D.G.J.K.prototype.My=function(){var a=this.gr;a||(a=this.Hg);return a};a.D.G.J.K.prototype.dA=function(){var a=this.hr,b=this.Zw,e={Ec:0,jg:0},h=[];if(this.My().hasChildNodes()&&a&&b&&0<b.length)for(var a=this.Oc(),g=0,g=this.Hg.offsetWidth,k=0,l=null,m=0;m<b.length;m++){var n=b[m];if(1===n.nodeType){var q=n.offsetWidth,r=n.offsetHeight,p={Ec:q,jg:r,id:n.id};a?(p.start=this.Mn?g-(n.offsetLeft+
q):n.offsetLeft,0===m&&(k=p.start),p.start-=k,e.Ec=p.start+q,e.jg=Math.max(e.jg,r),p.end=e.Ec-1):(p.start=n.offsetTop,e.Ec=Math.max(e.Ec,q),e.jg=p.start+r,p.end=e.jg-1);l&&l.end>=p.start&&(n=l.end-(p.start-1),l.end-=n,a?l.Ec-=n:l.jg-=n);h.push(p);l=p}}this.lp=h;return e};a.D.G.J.K.prototype.qj=function(){if(!this.lp){var a=this.dA();this.Ue||(this.Ue=a)}return this.lp};a.D.G.J.K.prototype.Zr=function(){return this.Os?this.Os:this.$o};a.D.G.J.K.prototype.cs=function(){return this.Ws?this.Ws:this.Vs};
a.D.G.J.K.prototype.TN=function(){this.Zr().style.display=this.fl()};a.D.G.J.K.prototype.VN=function(){this.cs().style.display=this.fl()};a.D.G.J.K.prototype.Ho=function(){this.Zr().style.display="none"};a.D.G.J.K.prototype.Io=function(){this.cs().style.display="none"};a.D.G.J.K.prototype.Qo=function(){return"none"!==this.Zr().style.display};a.D.G.J.K.prototype.As=function(){return"none"!==this.cs().style.display};a.D.G.J.K.prototype.Lr=function(){return this.Oc()?this.Pn:this.On};a.D.G.J.K.prototype.rO=
function(a){var b=this.Lr(),e=this.Td(),h=this.kj(),g=this.Zo();a<=this.Fl?(this.As()&&(h+=b,e-=b),this.Io()):g&&(this.As()||(h-=b,e+=b),this.VN());a>=this.Cl?(this.Qo()&&(h+=b),this.Ho()):g&&(this.Qo()||(h-=b),this.TN());this.lt(e);g?this.IB(h):this.Gx()};a.D.G.J.K.prototype.IB=function(a){var b=this.pc.style;a+="px";this.Oc()?b.maxWidth=a:b.maxHeight=a};a.D.G.J.K.prototype.Gx=function(){var a=this.pc.style;this.Oc()?a.maxWidth="":a.maxHeight=""};a.D.G.J.K.prototype.lt=function(a){var b=this.pc;
this.Oc()?b.scrollLeft=this.ir(a):b.scrollTop=a};a.D.G.J.K.prototype.kj=function(){var a=this.pc;return this.Oc()?a.offsetWidth:a.offsetHeight};a.D.G.J.K.prototype.Kj=function(a,b){this.Fg||(this.Nq=!1,this.BB(a,b))};a.D.G.J.K.prototype.BB=function(b,c){if(!this.vL()){this.Fg=!0;b=this.YH(b);this.rO(b);var e=this.qB;if(c||!e||b===this.Td())this.nA(b);else{var h=this;e.call(this.Oh,this.pc,this.ir(b),Math.abs(this.Td()-b)/a.D.G.J.K.AG,function(){h.nA(b)})}}};a.D.G.J.K.prototype.Td=function(){var a=
this.pc;return this.Oc()?this.ZH(a.scrollLeft):a.scrollTop};a.D.G.J.K.prototype.Zo=function(){var a=this.Hg,b=this.pc;return this.Oc()?a.offsetWidth>b.offsetWidth:a.offsetHeight>b.offsetHeight};a.D.G.J.K.prototype.YH=function(a){!this.Zo()||a<this.Fl?a=this.Fl:a>this.Cl&&(a=this.Cl);return a};a.D.G.J.K.prototype.PK=function(b){var c=this.Fg;if(this.Zo()&&!this.Fg){var e=a.D.G.J.K.hK(b);0>e&&this.Qo()?(c=!0,this.rB()):0<e&&this.As()&&(c=!0,this.sB())}c&&(b.preventDefault(),b.stopPropagation())};a.D.G.J.K.prototype.WK=
function(a){a=a.touches;this.Zo()&&(!this.Fg&&1===a.length)&&(this.Nn=!0,a=a[0],this.jO=this.Oc()?a.pageX:a.pageY,this.fC=this.Td(),this.kO=this.rx(),this.lO=this.sx())};a.D.G.J.K.prototype.VK=function(b){if(this.Nn){var c=this.Oc();b=b.touches[0];b=(c?b.pageX:b.pageY)-this.jO;var e=this.pc;Math.abs(b)<a.D.G.J.K.BG*(c?e.offsetWidth:e.offsetHeight)?this.Kj(this.fC-b,!0):(this.Kj((c&&this.Mn?0<b:0>b)?this.kO:this.lO),this.Nn=!1)}};a.D.G.J.K.prototype.UK=function(){this.Nn&&this.Kj(this.fC);this.Nn=
!1};a.D.G.J.K.prototype.ps=function(){this.Nq&&!this.Fg&&this.BB(this.Td(),!0)};a.D.G.J.K.prototype.nA=function(a){this.lt(a);this.AN();this.Fg=!1;if(this.Ir){this.hj=this.px();a=this.qx();var b=this.qj(),e=b[this.hj];this.hj!==a&&(this.Td()>e.start&&this.hj<b.length-2)&&(this.hj++,e=b[this.hj]);this.dJ=e.id;this.Ir.call(this.Oh,this.dJ)}};a.D.G.J.K.prototype.AN=function(){var a=this;window.setTimeout(function(){a&&(a.Nq=!0)},0)};a.D.G.J.K.prototype.rB=function(){this.Fg||this.Kj(this.rx())};a.D.G.J.K.prototype.sB=
function(){this.Fg||this.Kj(this.sx())};a.D.G.J.K.prototype.rx=function(){var a=this.GH(),b=0;return b=a===this.px()?this.Td()+this.kj():this.IH(a)};a.D.G.J.K.prototype.sx=function(){var a=this.HH(),b=0,b=a===this.qx()?this.Td()-this.kj():this.FH(a);this.Qo()||(b+=this.Lr());b<this.Lr()&&(b=this.Fl);return b};a.D.G.J.K.prototype.IH=function(a){return this.qj()[a].start};a.D.G.J.K.prototype.FH=function(a){return this.qj()[a].end-this.kj()+1};a.D.G.J.K.prototype.px=function(){var a=this.Qn(this.Td());
return 0>a?0:a};a.D.G.J.K.prototype.qx=function(){var a=this.Qn(this.Td()+this.kj()-1),b=this.qj();return 0>a?b.length-1:a};a.D.G.J.K.prototype.HH=function(){var a=this.Qn(this.Td()-1);return 0>a?0:a};a.D.G.J.K.prototype.GH=function(){var a=this.Qn(this.Td()+this.kj()),b=this.qj();return 0>a?b.length-1:a};a.D.G.J.K.prototype.Qn=function(a){for(var b=this.qj(),e=0;e<b.length;e++)if(a<=b[e].end)return e;return-1};a.D.G.J.K.prototype.ir=function(a){var b=a;if(this.Mn&&this.Oc())if(this.rH)b=-a;else if(this.tH||
this.sH)b=this.Hg.offsetWidth-this.pc.offsetWidth-a;return b};a.D.G.J.K.prototype.ZH=function(a){return this.ir(a)};a.D.G.J.K.AG=1.1;a.D.G.J.K.BG=0.33;(function(){b.ta("oj.ojConveyorBelt",e.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{orientation:"horizontal",contentParent:null},Kc:function(){this._super();this.element.addClass("oj-conveyorbelt oj-component")},_init:function(){this.mb(!0)},refresh:function(){this._super();var a="rtl"===this.xc()!==
this.bx;a&&this.ur();this.mb(a)},mb:function(a){this.bx="rtl"===this.xc();var c=this.element,f=this.options;if(a&&!this.Rn){var h=f.orientation,g=null,k=null,l=null,m=null,n=null;"vertical"!==h?(g="oj-enabled oj-conveyorbelt-overflow-indicator oj-start oj-default",k="oj-enabled oj-conveyorbelt-overflow-indicator oj-end oj-default",l=this.Wn("oj-conveyorbelt-overflow-icon oj-start"),m=this.Wn("oj-conveyorbelt-overflow-icon oj-end"),n=this.iH):(g="oj-enabled oj-conveyorbelt-overflow-indicator oj-top oj-default",
k="oj-enabled oj-conveyorbelt-overflow-indicator oj-bottom oj-default",l=this.Wn("oj-conveyorbelt-overflow-icon oj-top"),m=this.Wn("oj-conveyorbelt-overflow-icon oj-bottom"),n=this.jH);var q={};q.iE=g;q.bE=k;q.hE=l;q.aE=m;g={};g.eh=b.xa.eh;g.Lm=b.xa.Lm;"true"!==c.attr("_ojConveyorBeltTesting")&&(g.oE=n);n=null;f.contentParent&&(n=e(f.contentParent)[0]);this.Rn=new window.adf.D.G.J.K(c[0],h,n,this.bx,q,g)}this.Rn.NQ(a);if(a)for(a=c.find(".oj-conveyorbelt-overflow-indicator"),c=a.size(),f=0;f<c;f++)h=
a.get(f),this.RN(h)},_destroy:function(){this.ur();this.element.removeClass("oj-conveyorbelt oj-component");this._super()},_setOption:function(a,b){var e=!1;switch(a){case "containerParent":case "orientation":e=!0}e&&this.ur();this._super(a,b);e&&this.mb(!0)},ur:function(){var a=this.Rn;a&&a.destroy();this.Rn=null},RN:function(a){this._on(a,{mousedown:function(a){e(a.currentTarget).addClass("oj-active")},mouseup:function(a){e(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){a=a.currentTarget;
e(a).addClass("oj-hover");e(a).removeClass("oj-default")},mouseleave:function(a){a=a.currentTarget;e(a).removeClass("oj-hover");e(a).removeClass("oj-active");e(a).addClass("oj-default")}})},Wn:function(a){var b=document.createElement("span");b.setAttribute("class","oj-component-icon oj-clickable-icon "+a);return b},iH:function(a,b,f,h){var g={};g.scrollLeft=b;e(a).animate(g,f,"swing",h)},jH:function(a,b,f,h){var g={};g.scrollTop=b;e(a).animate(g,f,"swing",h)},getNodeBySubId:function(a){if(null==a)return this.element?
this.element[0]:null;a=a.subId;return"oj-conveyorbelt-start-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-start")[0]:"oj-conveyorbelt-end-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-end")[0]:"oj-conveyorbelt-top-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-top")[0]:"oj-conveyorbelt-bottom-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-bottom")[0]:null}})})()});
//# sourceMappingURL=oj-modular.map