define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){(function(){var a=0;b.ta("oj.ojCollapsible",e.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{expanded:!1,disabled:null,expandOn:"click",expandArea:"disclosureIcon",beforeExpand:null,afterExpand:null,beforeCollapse:null,afterCollapse:null,optionChange:null},Kc:function(){this._super();this.wC=e();this.element.addClass("oj-collapsible oj-component");this.AA();this.Ob()},eg:function(a,b){a.show(b,{launcher:this.element.find(".oj-collapsible-header-icon").first(),
focus:"menu"})},dI:function(){var a=this.options.expanded?"oj-collapsible-open-icon":"oj-collapsible-close-icon";(this.Vd()?e("\x3cspan\x3e"):e("\x3ca href\x3d'#'\x3e")).addClass("oj-component-icon oj-clickable-icon oj-collapsible-header-icon "+a).attr("aria-labelledby",this.header.attr("id")).prependTo(this.header);this.header.addClass("oj-collapsible-icons ")},ey:function(){this.header.removeClass("oj-collapsible-icons").children(".oj-collapsible-header-icon").remove()},_destroy:function(){this.Bx();
this.element.removeClass("oj-collapsible oj-component oj-collapsible-collapsed oj-disabled");this.Vd()&&this.cl(this.header).removeAttr("tabIndex");this.header.removeClass("oj-collapsible-header").each(function(){/^oj-collapsible/.test(this.id)&&this.removeAttribute("id")});this.bl().removeAttr("role").removeAttr("aria-controls").removeAttr("aria-expanded").removeAttr("aria-disabled");this.ey();this.cl(this.content).removeAttr("tabIndex");this.content.css("display","").removeAttr("aria-hidden").removeAttr("tabIndex").removeClass("oj-component-content oj-collapsible-content").each(function(){/^oj-collapsible/.test(this.id)&&
this.removeAttribute("id")})},Bx:function(){this.Tl();this.content&&(this.content.unwrap(),this.Ff=null)},Vd:function(){return this.element.hasClass("oj-disabled")},Sy:function(){return"header"==this.options.expandArea?"\x3e .oj-collapsible-header":"\x3e .oj-collapsible-header \x3e .oj-collapsible-header-icon"},_setOption:function(a,b){"expanded"===a?this.AN(b):("expandOn"===a||"expandArea"===a?(this.Tl(),this._super(a,b),this.ti()):this._super(a,b),"disabled"===a&&(this.header.add(this.header.next()),
this.element.toggleClass("oj-disabled",!!b)))},ii:function(a){if(!a.altKey&&!a.ctrlKey){var b=e.ui.keyCode;switch(a.keyCode){case b.SPACE:case b.ENTER:this.fC(a)}}},refresh:function(){this._super();this.Bx();this.AA();this.ey();this.Ob()},AA:function(){this.header=this.element.children(":first-child").addClass("oj-collapsible-header");this.content=this.header.next().addClass("oj-collapsible-content oj-component-content");this.content.wrap("\x3cdiv\x3e\x3c/div\x3e");this.Ff=this.content.parent().addClass("oj-collapsible-wrapper");
this.options.disabled&&this.element.addClass("oj-disabled");this.Vd()&&this.cl(this.header).attr("tabIndex",-1)},Ob:function(){var b=this.header,c=this.content,e=this.options,h=this.qS="oj-collapsible-"+(this.element.attr("id")||++a),g=b.attr("id"),k=c.attr("id");g||b.attr("id",h+"-header");k||(k=h+"-content",c.attr("id",k));this.dI();b=this.bl();b.attr("role","button").attr("aria-controls",k);this.Vd()&&b.attr("aria-disabled",!0);this.Vd()||this.BB(e.expanded?"0":"-1");this.element.toggleClass("oj-collapsible-collapsed",
!e.expanded);e.expanded?(c.attr({"aria-hidden":"false"}),b.attr("aria-expanded","true")):(this.Ff.css({"max-height":0,"overflow-y":"hidden",display:"none"}),this.Ff.css("max-height",0),c.attr({"aria-hidden":"true"}),b.attr("aria-expanded","false"));this.ti()},AN:function(a){a!==this.options.expanded&&(a?this.expand(!0):this.collapse(!0))},ti:function(){var a={keydown:this.ii},b=this.options.expandOn;if(b){var f=this;e.each(b.split(" "),function(b,c){a[c]=f.fC})}b=this.element.find(this.Sy());this._on(b,
a);this._on(this.Ff,{transitionend:this.pp,webkitTransitionEnd:this.pp,otransitionend:this.pp,oTransitionEnd:this.pp});this.Vd()||(this._on(this.element,{ojafterexpand:this.uy,ojaftercollapse:this.uy,ojfocus:this.Ey,ojfocusout:this.Ey}),this._hoverable(b),this._focusable(b),this.YG(b))},Tl:function(){this._off(this.element.find(this.Sy()));this.Ff&&this._off(this.Ff);this._off(this.element.add(this.content))},fC:function(a){this.Vd()||(this.options.expanded?this.collapse(!0,a):this.expand(!0,a),a.preventDefault(),
a.stopPropagation(),this.header.find(".oj-collapsible-header-icon").focus())},uy:function(a){if(!this.Vd()&&a.target===this.element[0]&&!a.isDefaultPrevented()){var b=this.element,e=this.options,h=this.content,g=this.Ff,k="ojaftercollapse"===a.type;a.preventDefault();e.expanded=!k;g.xp=g.outerHeight();k?(g.removeClass("oj-collapsible-transition"),g.css({"max-height":g.xp,"overflow-y":"hidden"}),setTimeout(function(){g.addClass("oj-collapsible-transition").css({"max-height":0});b.addClass("oj-collapsible-collapsed")},
10)):(g.show(),setTimeout(function(){g.xp+=h.outerHeight();g.addClass("oj-collapsible-transition").css({"max-height":g.xp});b.removeClass("oj-collapsible-collapsed")},1));this.header.find(".oj-collapsible-header-icon").toggleClass("oj-collapsible-open-icon",!k).toggleClass("oj-collapsible-close-icon",k||!1).end();this.content.attr("aria-hidden",k);this.bl().attr("aria-expanded",!k);this.BB(k?"-1":"0")}},Ey:function(a){if(this.Vd())return null;"ojfocusout"==a.type?(this.bl().attr("tabIndex",-1),a.preventDefault(),
a.stopPropagation()):"ojfocus"==a.type&&(this.bl().attr("tabIndex",0).focus(),a.preventDefault(),a.stopPropagation())},bl:function(){return this.cl(this.header).first()},BB:function(a){return this.cl(this.content).attr("tabIndex",a)},cl:function(a){return this.Vd()?a.find("span"):a.find("a,:input")},expand:function(a,b){if(!this.Vd()){var e={header:this.header,content:this.content};a&&!1===this._trigger("beforeExpand",b,e)||(this._trigger("afterExpand",b,e),this.Qe("expanded",!1,!0,b?!0:!1))}},collapse:function(a,
b){if(!this.Vd()){var e={header:this.header,content:this.content};a&&!1===this._trigger("beforeCollapse",b,e)||(this._trigger("afterCollapse",b,e),this.Qe("expanded",!0,!1,b?!0:!1))}},pp:function(a){this.Vd()||("max-height"==(a.originalEvent?a.originalEvent.propertyName:null)&&(a.preventDefault(),a.stopPropagation()),this.options.expanded?this.Ff.css({"max-height":9999,"overflow-y":""}):this.Ff.hide(),this.Ff.removeClass("oj-collapsible-transition"))},YG:function(a){this.wC=this.wC.add(a);this._on(a,
{mousedown:function(a){e(a.currentTarget).addClass("oj-active")},mouseup:function(a){e(a.currentTarget).removeClass("oj-active")}})},Qe:function(a,b,e,h){this._trigger("optionChange",h,{option:a,previousValue:b,value:e,optionMetadata:{writeback:h?"shouldWrite":"shouldNotWrite"}})},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-collapsible-content":return this.content;case "oj-collapsible-header":return this.header;case "oj-collapsible-header-icon":return this.header.find("."+
a)[0]}return null}})})()});
//# sourceMappingURL=oj-modular.map