define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){window.adf||(window.adf={});var a=window.adf;a.D=a.D||{};a.D.G=a.D.G||{};a.D.G.H=a.D.G.H||{};a.D.G.H.J=function(a,b,f,e,g,k){this.Gg=a;this.RL=b;this.Wq=f;this.Fn=e;g&&(g.aQ&&(this.cM=g.aQ),g.SP&&(this.ML=g.SP),g.UD&&(this.dM=g.UD),g.ND&&(this.NL=g.ND),g.TD&&(this.bM=g.TD),g.MD&&(this.LL=g.MD));k&&(k.aE&&(this.fB=k.aE),k.VO&&(this.yr=k.VO),k.vO&&(this.Hh=k.vO),k.$g&&(this.An=k.$g),k.Cm&&(this.Wo=k.Cm));this.Dq=!0;this.Zi=0;a=navigator.userAgent.toLowerCase();
if(-1!==a.indexOf("gecko/"))this.dH=!0;else if(-1!==a.indexOf("opera"))this.eH=!0;else if(-1!==a.indexOf("applewebkit")||-1!==a.indexOf("safari"))this.fH=!0};a.D.G.H.J.prototype.sQ=function(b){var c=this,f=a.D.G.H.J;if(b){this.OH();this.bI(this.cM,this.dM,this.bM);this.PH(this.ML,this.NL,this.LL);var e=this.So,g=this.ep;g?(this.In=g.offsetWidth,this.Hn=e.offsetHeight):(g=this.kp,this.In=e.offsetWidth,this.Hn=g.offsetHeight);this.Bo();this.Ao();this.ul=function(a){c.vK(a)};f.Pf(this.Gg,"mousewheel",
this.ul);f.Pf(this.Gg,"wheel",this.ul);this.kt=function(a){c.CK(a)};f.Pf(this.pc,"touchstart",this.kt);this.jt=function(a){c.BK(a)};f.Pf(this.pc,"touchmove",this.jt);this.Kl=function(){c.AK()};f.Pf(this.pc,"touchend",this.Kl);f.Pf(this.pc,"touchcancel",this.Kl);this.Hs=0}else this.LA();this.Tq();this.Ew(b);this.Wh(!0);b&&this.An&&(this.jj=function(){c.Wh(!1)},this.An.call(this.Hh,this.Gg,this.jj),this.An.call(this.Hh,this.Dg,this.jj))};a.D.G.H.J.prototype.destroy=function(){var b=this.Gg,c=a.D.G.H.J;
c.yj(b,"mousewheel",this.ul);c.yj(b,"wheel",this.ul);c.yj(this.pc,"touchstart",this.kt);c.yj(this.pc,"touchmove",this.jt);c.yj(this.pc,"touchend",this.Kl);c.yj(this.pc,"touchcancel",this.Kl);this.Kl=this.jt=this.kt=this.ul=null;this.Wo&&this.jj&&(this.Wo.call(this.Hh,b,this.jj),this.Wo.call(this.Hh,this.Dg,this.jj));this.jj=null;c.RM(this.Xq,b);this.Mw=null;this.ht?b.removeChild(this.ht):(b.removeChild(this.pc),b.removeChild(this.kp),b.removeChild(this.pt));this.kp=this.pt=this.Ds=this.Ls=this.ep=
this.gt=this.ht=this.Xq=this.pc=this.Dg=this.Ks=this.So=null;this.Tq();this.Hh=this.Wo=this.An=this.yr=this.fB=this.Gg=null};a.D.G.H.J.SM=function(b,c,f){var e=a.D.G.H.J,g=null;f&&(g=e.br(),c.appendChild(g));var k=null;for(b=b.childNodes;0<b.length;){k||(k=[]);var l=b[0];if(1===l.nodeType){f||(g=e.br(),c.appendChild(g));var m=e.Rn();m.appendChild(l);g.appendChild(m);k.push(l)}else f?g.appendChild(l):c.appendChild(l)}return k};a.D.G.H.J.RM=function(a,b){if(a)for(var f=a.childNodes;0<f.length;){var e=
f[0];if(1===e.nodeType){for(var g=e.childNodes;0<g.length;){var k=g[0];1===k.nodeType?(b.appendChild(k.firstChild),e.removeChild(k)):b.appendChild(k)}a.removeChild(e)}else b.appendChild(e)}};a.D.G.H.J.zy=function(a){var b=a.ownerDocument.defaultView,f=null;return f=b?b.getComputedStyle(a,null):a.currentStyle};a.D.G.H.J.dJ=function(b){var c=a.D.G.H.J;b=c.zy(b);return c.vy(b.width)};a.D.G.H.J.cJ=function(b){var c=a.D.G.H.J;b=c.zy(b);return c.vy(b.height)};a.D.G.H.J.vy=function(a){return 0<a.length&&
"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0};a.D.G.H.J.Pf=function(a,b,f){a.addEventListener?a.addEventListener(b,f,!1):a.attachEvent&&a.attachEvent("on"+b,f)};a.D.G.H.J.yj=function(a,b,f){a.removeEventListener?a.removeEventListener(b,f,!1):a.detachEvent&&a.detachEvent("on"+b,f)};a.D.G.H.J.PJ=function(a){var b=0;return b=null!=a.wheelDelta?a.wheelDelta:null!=a.deltaY?-a.deltaY:-a.detail};a.D.G.H.J.Ix=function(){var a=document.createElement("div");a.style.display="table";return a};a.D.G.H.J.br=
function(){var a=document.createElement("div");a.style.display="table-row";return a};a.D.G.H.J.Rn=function(){var a=document.createElement("div");a.style.display="table-cell";return a};a.D.G.H.J.jC=function(a,b,f,e){var g=document.createElement("div"),k=g.style;k.display="inline-block";g.appendChild(a);b.appendChild(g);f&&(k.maxWidth=g.offsetWidth+"px");e&&(k.maxHeight=g.offsetHeight+"px");return g};a.D.G.H.J.prototype.Mc=function(){return"horizontal"===this.RL};a.D.G.H.J.prototype.bL=function(){return!this.Ay().hasChildNodes()};
a.D.G.H.J.prototype.LA=function(){this.Hs=this.Rd();this.ux();this.Zs(0);this.Bo();this.Ao()};a.D.G.H.J.prototype.Tq=function(){this.cp=this.Ue=null};a.D.G.H.J.prototype.Wh=function(a){a||this.LA();this.Tq();this.Ue&&this.cp||(this.Ue=this.Tz());a||this.Ew();a=this.Ue;this.UG(a.lc,a.fg)};a.D.G.H.J.prototype.UG=function(a,b){var f=this.So.style,e=this.Ks.style;if(this.Mc()){var g=0.5*(b-this.Hn);f.top=g+"px";e.top=g+"px"}else g=0.5*(a-this.In),this.Fn?(f.left=-g+"px",e.left=-g+"px"):(f.left=g+"px",
e.left=g+"px")};a.D.G.H.J.prototype.Ew=function(b){var c=this.Dg,f=this.Mc(),e=a.D.G.H.J,e=f?e.dJ(this.Gg):e.cJ(this.Gg);(f?c.offsetWidth:c.offsetHeight)>e&&this.xB(e);this.tl=0;this.ql=f?c.offsetWidth-e+this.In:c.offsetHeight-e+this.Hn;0>this.ql&&(this.ql=0);this.Bo();this.Ao();this.Cj(b?this.tl:this.Hs,!0);this.Hs=0};a.D.G.H.J.prototype.OH=function(){var b=this,c=this.Mc(),f=document.createElement("div");this.pc=f;var e=f.style;e.overflow="hidden";e.display=this.Uk();e.position="relative";c&&(e.verticalAlign=
"top");var g=this.Gg,k=a.D.G.H.J,l=document.createElement("div");this.Dg=l;var m=l.style;m.position="relative";c&&(m.display="inline-block");f.appendChild(l);m=null;if(c){this.ht=m=k.Ix();var n=k.br(),q=k.Rn();this.gt=q;var r=k.Rn(),p=k.Rn();this.ep=p;r.appendChild(f);n.appendChild(q);n.appendChild(r);n.appendChild(p);m.appendChild(n)}n=k.Ix();q=k.SM(g,n,c);if(this.Wq)for(var q=[],r=this.Wq.children,p=r.length,s=0;s<p;s++){var v=r[s];1===v.nodeType&&q.push(v)}(this.Mw=q)&&0<q.length&&(this.Xq=n,l.appendChild(n));
m?g.appendChild(m):(this.pt=m=document.createElement("div"),this.kp=n=document.createElement("div"),g.appendChild(m),g.appendChild(f),g.appendChild(n));c&&(c=f.offsetHeight,l=l.offsetHeight,c>l&&(e.marginBottom=l-c+"px"));k.Pf(f,"scroll",function(a){b.es(a)})};a.D.G.H.J.prototype.Uk=function(){return this.Mc()?"inline-block":"block"};a.D.G.H.J.prototype.bI=function(b,c,f){var e=this,g=document.createElement("div");this.Ks=g;b&&g.setAttribute("id",b);g.setAttribute("class",c);g.setAttribute("aria-hidden",
"true");c=g.style;c.display=this.Uk();c.position="relative";if(b=this.Mc())c.verticalAlign="top";c=a.D.G.H.J;c.Pf(g,"click",function(){e.hB()});this.gt?this.Ls=c.jC(g,this.gt,b,!b):this.pt.appendChild(g);f&&g.appendChild(f)};a.D.G.H.J.prototype.PH=function(b,c,f){var e=this,g=document.createElement("div");this.So=g;b&&g.setAttribute("id",b);g.setAttribute("class",c);g.setAttribute("aria-hidden","true");c=g.style;c.display=this.Uk();c.position="relative";if(b=this.Mc())c.verticalAlign="top";c=a.D.G.H.J;
c.Pf(g,"click",function(){e.gB()});this.ep?this.Ds=c.jC(g,this.ep,b,!b):this.kp.appendChild(g);f&&g.appendChild(f)};a.D.G.H.J.prototype.Ay=function(){var a=this.Wq;a||(a=this.Dg);return a};a.D.G.H.J.prototype.Tz=function(){var a=this.Xq,b=this.Mw,f={lc:0,fg:0},e=[];if(this.Ay().hasChildNodes()&&a&&b&&0<b.length)for(var a=this.Mc(),g=0,g=this.Dg.offsetWidth,k=0,l=null,m=0;m<b.length;m++){var n=b[m];if(1===n.nodeType){var q=n.offsetWidth,r=n.offsetHeight,p={lc:q,fg:r,id:n.id};a?(p.start=this.Fn?g-(n.offsetLeft+
q):n.offsetLeft,0===m&&(k=p.start),p.start-=k,f.lc=p.start+q,f.fg=Math.max(f.fg,r),p.end=f.lc-1):(p.start=n.offsetTop,f.lc=Math.max(f.lc,q),f.fg=p.start+r,p.end=f.fg-1);l&&l.end>=p.start&&(n=l.end-(p.start-1),l.end-=n,a?l.lc-=n:l.fg-=n);e.push(p);l=p}}this.cp=e;return f};a.D.G.H.J.prototype.gj=function(){if(!this.cp){var a=this.Tz();this.Ue||(this.Ue=a)}return this.cp};a.D.G.H.J.prototype.Pr=function(){return this.Ds?this.Ds:this.So};a.D.G.H.J.prototype.Tr=function(){return this.Ls?this.Ls:this.Ks};
a.D.G.H.J.prototype.zN=function(){this.Pr().style.display=this.Uk()};a.D.G.H.J.prototype.BN=function(){this.Tr().style.display=this.Uk()};a.D.G.H.J.prototype.Ao=function(){this.Pr().style.display="none"};a.D.G.H.J.prototype.Bo=function(){this.Tr().style.display="none"};a.D.G.H.J.prototype.Io=function(){return"none"!==this.Pr().style.display};a.D.G.H.J.prototype.qs=function(){return"none"!==this.Tr().style.display};a.D.G.H.J.prototype.Br=function(){return this.Mc()?this.In:this.Hn};a.D.G.H.J.prototype.YN=
function(a){var b=this.Br(),f=this.Rd(),e=this.bj(),g=this.Ro();a<=this.tl?(this.qs()&&(e+=b,f-=b),this.Bo()):g&&(this.qs()||(e-=b,f+=b),this.BN());a>=this.ql?(this.Io()&&(e+=b),this.Ao()):g&&(this.Io()||(e-=b),this.zN());this.Zs(f);g?this.xB(e):this.ux()};a.D.G.H.J.prototype.xB=function(a){var b=this.pc.style;a+="px";this.Mc()?b.maxWidth=a:b.maxHeight=a};a.D.G.H.J.prototype.ux=function(){var a=this.pc.style;this.Mc()?a.maxWidth="":a.maxHeight=""};a.D.G.H.J.prototype.Zs=function(a){var b=this.pc;
this.Mc()?b.scrollLeft=this.Yq(a):b.scrollTop=a};a.D.G.H.J.prototype.bj=function(){var a=this.pc;return this.Mc()?a.offsetWidth:a.offsetHeight};a.D.G.H.J.prototype.Cj=function(a,b){this.Ag||(this.Dq=!1,this.qB(a,b))};a.D.G.H.J.prototype.qB=function(b,c){if(!this.bL()){this.Ag=!0;b=this.JH(b);this.YN(b);var e=this.fB;if(c||!e||b===this.Rd())this.bA(b);else{var h=this;e.call(this.Hh,this.pc,this.Yq(b),Math.abs(this.Rd()-b)/a.D.G.H.J.nG,function(){h.bA(b)})}}};a.D.G.H.J.prototype.Rd=function(){var a=
this.pc;return this.Mc()?this.KH(a.scrollLeft):a.scrollTop};a.D.G.H.J.prototype.Ro=function(){var a=this.Dg,b=this.pc;return this.Mc()?a.offsetWidth>b.offsetWidth:a.offsetHeight>b.offsetHeight};a.D.G.H.J.prototype.JH=function(a){!this.Ro()||a<this.tl?a=this.tl:a>this.ql&&(a=this.ql);return a};a.D.G.H.J.prototype.vK=function(b){var c=this.Ag;if(this.Ro()&&!this.Ag){var e=a.D.G.H.J.PJ(b);0>e&&this.Io()?(c=!0,this.gB()):0<e&&this.qs()&&(c=!0,this.hB())}c&&(b.preventDefault(),b.stopPropagation())};a.D.G.H.J.prototype.CK=
function(a){a=a.touches;this.Ro()&&(!this.Ag&&1===a.length)&&(this.Gn=!0,a=a[0],this.QN=this.Mc()?a.pageX:a.pageY,this.VB=this.Rd(),this.RN=this.dx(),this.SN=this.ex())};a.D.G.H.J.prototype.BK=function(b){if(this.Gn){var c=this.Mc();b=b.touches[0];b=(c?b.pageX:b.pageY)-this.QN;var e=this.pc;Math.abs(b)<a.D.G.H.J.oG*(c?e.offsetWidth:e.offsetHeight)?this.Cj(this.VB-b,!0):(this.Cj((c&&this.Fn?0<b:0>b)?this.RN:this.SN),this.Gn=!1)}};a.D.G.H.J.prototype.AK=function(){this.Gn&&this.Cj(this.VB);this.Gn=
!1};a.D.G.H.J.prototype.es=function(){this.Dq&&!this.Ag&&this.qB(this.Rd(),!0)};a.D.G.H.J.prototype.bA=function(a){this.Zs(a);this.gN();this.Ag=!1;if(this.yr){this.Zi=this.bx();a=this.cx();var b=this.gj(),e=b[this.Zi];this.Zi!==a&&(this.Rd()>e.start&&this.Zi<b.length-2)&&(this.Zi++,e=b[this.Zi]);this.MI=e.id;this.yr.call(this.Hh,this.MI)}};a.D.G.H.J.prototype.gN=function(){var a=this;window.setTimeout(function(){a&&(a.Dq=!0)},0)};a.D.G.H.J.prototype.gB=function(){this.Ag||this.Cj(this.dx())};a.D.G.H.J.prototype.hB=
function(){this.Ag||this.Cj(this.ex())};a.D.G.H.J.prototype.dx=function(){var a=this.sH(),b=0;return b=a===this.bx()?this.Rd()+this.bj():this.uH(a)};a.D.G.H.J.prototype.ex=function(){var a=this.tH(),b=0,b=a===this.cx()?this.Rd()-this.bj():this.rH(a);this.Io()||(b+=this.Br());b<this.Br()&&(b=this.tl);return b};a.D.G.H.J.prototype.uH=function(a){return this.gj()[a].start};a.D.G.H.J.prototype.rH=function(a){return this.gj()[a].end-this.bj()+1};a.D.G.H.J.prototype.bx=function(){var a=this.Jn(this.Rd());
return 0>a?0:a};a.D.G.H.J.prototype.cx=function(){var a=this.Jn(this.Rd()+this.bj()-1),b=this.gj();return 0>a?b.length-1:a};a.D.G.H.J.prototype.tH=function(){var a=this.Jn(this.Rd()-1);return 0>a?0:a};a.D.G.H.J.prototype.sH=function(){var a=this.Jn(this.Rd()+this.bj()),b=this.gj();return 0>a?b.length-1:a};a.D.G.H.J.prototype.Jn=function(a){for(var b=this.gj(),e=0;e<b.length;e++)if(a<=b[e].end)return e;return-1};a.D.G.H.J.prototype.Yq=function(a){var b=a;if(this.Fn&&this.Mc())if(this.dH)b=-a;else if(this.fH||
this.eH)b=this.Dg.offsetWidth-this.pc.offsetWidth-a;return b};a.D.G.H.J.prototype.KH=function(a){return this.Yq(a)};a.D.G.H.J.nG=1.1;a.D.G.H.J.oG=0.33;(function(){b.ta("oj.ojConveyorBelt",e.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{orientation:"horizontal",contentParent:null},Ic:function(){this._super();this.element.addClass("oj-conveyorbelt oj-component")},_init:function(){this.kb(!0)},refresh:function(){this._super();var a="rtl"===this.xc()!==
this.Pw;a&&this.jr();this.kb(a)},kb:function(a){this.Pw="rtl"===this.xc();var c=this.element,f=this.options;if(a&&!this.Kn){var h=f.orientation,g=null,k=null,l=null,m=null,n=null;"vertical"!==h?(g="oj-enabled oj-conveyorbelt-overflow-indicator oj-start oj-default",k="oj-enabled oj-conveyorbelt-overflow-indicator oj-end oj-default",l=this.Pn("oj-conveyorbelt-overflow-icon oj-start"),m=this.Pn("oj-conveyorbelt-overflow-icon oj-end"),n=this.WG):(g="oj-enabled oj-conveyorbelt-overflow-indicator oj-top oj-default",
k="oj-enabled oj-conveyorbelt-overflow-indicator oj-bottom oj-default",l=this.Pn("oj-conveyorbelt-overflow-icon oj-top"),m=this.Pn("oj-conveyorbelt-overflow-icon oj-bottom"),n=this.XG);var q={};q.UD=g;q.ND=k;q.TD=l;q.MD=m;g={};g.$g=b.xa.$g;g.Cm=b.xa.Cm;"true"!==c.attr("_ojConveyorBeltTesting")&&(g.aE=n);n=null;f.contentParent&&(n=e(f.contentParent)[0]);this.Kn=new window.adf.D.G.H.J(c[0],h,n,this.Pw,q,g)}this.Kn.sQ(a);if(a)for(a=c.find(".oj-conveyorbelt-overflow-indicator"),c=a.size(),f=0;f<c;f++)h=
a.get(f),this.xN(h)},_destroy:function(){this.jr();this.element.removeClass("oj-conveyorbelt oj-component");this._super()},_setOption:function(a,b){var e=!1;switch(a){case "containerParent":case "orientation":e=!0}e&&this.jr();this._super(a,b);e&&this.kb(!0)},jr:function(){var a=this.Kn;a&&a.destroy();this.Kn=null},xN:function(a){this._on(a,{mousedown:function(a){e(a.currentTarget).addClass("oj-active")},mouseup:function(a){e(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){a=a.currentTarget;
e(a).addClass("oj-hover");e(a).removeClass("oj-default")},mouseleave:function(a){a=a.currentTarget;e(a).removeClass("oj-hover");e(a).removeClass("oj-active");e(a).addClass("oj-default")}})},Pn:function(a){var b=document.createElement("span");b.setAttribute("class","oj-component-icon oj-clickable-icon "+a);return b},WG:function(a,b,f,h){var g={};g.scrollLeft=b;e(a).animate(g,f,"swing",h)},XG:function(a,b,f,h){var g={};g.scrollTop=b;e(a).animate(g,f,"swing",h)},getNodeBySubId:function(a){if(null==a)return this.element?
this.element[0]:null;a=a.subId;return"oj-conveyorbelt-start-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-start")[0]:"oj-conveyorbelt-end-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-end")[0]:"oj-conveyorbelt-top-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-top")[0]:"oj-conveyorbelt-bottom-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-bottom")[0]:null}})})()});
//# sourceMappingURL=oj-modular.map