define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){window.adf||(window.adf={});var a=window.adf;a.D=a.D||{};a.D.G=a.D.G||{};a.D.G.J=a.D.G.J||{};a.D.G.J.K=function(a,b,f,e,g,k){this.Kg=a;this.mM=b;this.gr=f;this.Mn=e;g&&(g.wQ&&(this.xM=g.wQ),g.oQ&&(this.iM=g.oQ),g.jE&&(this.yM=g.jE),g.cE&&(this.jM=g.cE),g.iE&&(this.wM=g.iE),g.bE&&(this.hM=g.bE));k&&(k.pE&&(this.rB=k.pE),k.qP&&(this.Ir=k.qP),k.RO&&(this.Oh=k.RO),k.eh&&(this.Hn=k.eh),k.Lm&&(this.ep=k.Lm));this.Nq=!0;this.hj=0;a=navigator.userAgent.toLowerCase();
if(-1!==a.indexOf("gecko/"))this.tH=!0;else if(-1!==a.indexOf("opera"))this.uH=!0;else if(-1!==a.indexOf("applewebkit")||-1!==a.indexOf("safari"))this.vH=!0};a.D.G.J.K.prototype.PQ=function(b){var c=this,f=a.D.G.J.K;if(b){this.eI();this.tI(this.xM,this.yM,this.wM);this.gI(this.iM,this.jM,this.hM);var e=this.$o,g=this.np;g?(this.Pn=g.offsetWidth,this.On=e.offsetHeight):(g=this.tp,this.Pn=e.offsetWidth,this.On=g.offsetHeight);this.Io();this.Ho();this.Gl=function(a){c.RK(a)};f.Rf(this.Kg,"mousewheel",
this.Gl);f.Rf(this.Kg,"wheel",this.Gl);this.xt=function(a){c.YK(a)};f.Rf(this.pc,"touchstart",this.xt);this.wt=function(a){c.XK(a)};f.Rf(this.pc,"touchmove",this.wt);this.Wl=function(){c.WK()};f.Rf(this.pc,"touchend",this.Wl);f.Rf(this.pc,"touchcancel",this.Wl);this.Ts=0}else this.XA();this.cr();this.Sw(b);this.bi(!0);b&&this.Hn&&(this.tj=function(){c.bi(!1)},this.Hn.call(this.Oh,this.Kg,this.tj),this.Hn.call(this.Oh,this.Hg,this.tj))};a.D.G.J.K.prototype.destroy=function(){var b=this.Kg,c=a.D.G.J.K;
c.Gj(b,"mousewheel",this.Gl);c.Gj(b,"wheel",this.Gl);c.Gj(this.pc,"touchstart",this.xt);c.Gj(this.pc,"touchmove",this.wt);c.Gj(this.pc,"touchend",this.Wl);c.Gj(this.pc,"touchcancel",this.Wl);this.Wl=this.wt=this.xt=this.Gl=null;this.ep&&this.tj&&(this.ep.call(this.Oh,b,this.tj),this.ep.call(this.Oh,this.Hg,this.tj));this.tj=null;c.mN(this.hr,b);this.$w=null;this.ut?b.removeChild(this.ut):(b.removeChild(this.pc),b.removeChild(this.tp),b.removeChild(this.Ct));this.tp=this.Ct=this.Ps=this.Xs=this.np=
this.tt=this.ut=this.hr=this.pc=this.Hg=this.Ws=this.$o=null;this.cr();this.Oh=this.ep=this.Hn=this.Ir=this.rB=this.Kg=null};a.D.G.J.K.nN=function(b,c,f){var e=a.D.G.J.K,g=null;f&&(g=e.mr(),c.appendChild(g));var k=null;for(b=b.childNodes;0<b.length;){k||(k=[]);var l=b[0];if(1===l.nodeType){f||(g=e.mr(),c.appendChild(g));var m=e.Yn();m.appendChild(l);g.appendChild(m);k.push(l)}else f?g.appendChild(l):c.appendChild(l)}return k};a.D.G.J.K.mN=function(a,b){if(a)for(var f=a.childNodes;0<f.length;){var e=
f[0];if(1===e.nodeType){for(var g=e.childNodes;0<g.length;){var k=g[0];1===k.nodeType?(b.appendChild(k.firstChild),e.removeChild(k)):b.appendChild(k)}a.removeChild(e)}else b.appendChild(e)}};a.D.G.J.K.My=function(a){var b=a.ownerDocument.defaultView,f=null;return f=b?b.getComputedStyle(a,null):a.currentStyle};a.D.G.J.K.wJ=function(b){var c=a.D.G.J.K;b=c.My(b);return c.Iy(b.width)};a.D.G.J.K.vJ=function(b){var c=a.D.G.J.K;b=c.My(b);return c.Iy(b.height)};a.D.G.J.K.Iy=function(a){return 0<a.length&&
"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0};a.D.G.J.K.Rf=function(a,b,f){a.addEventListener?a.addEventListener(b,f,!1):a.attachEvent&&a.attachEvent("on"+b,f)};a.D.G.J.K.Gj=function(a,b,f){a.removeEventListener?a.removeEventListener(b,f,!1):a.detachEvent&&a.detachEvent("on"+b,f)};a.D.G.J.K.jK=function(a){var b=0;return b=null!=a.wheelDelta?a.wheelDelta:null!=a.deltaY?-a.deltaY:-a.detail};a.D.G.J.K.Ux=function(){var a=document.createElement("div");a.style.display="table";return a};a.D.G.J.K.mr=
function(){var a=document.createElement("div");a.style.display="table-row";return a};a.D.G.J.K.Yn=function(){var a=document.createElement("div");a.style.display="table-cell";return a};a.D.G.J.K.vC=function(a,b,f,e){var g=document.createElement("div"),k=g.style;k.display="inline-block";g.appendChild(a);b.appendChild(g);f&&(k.maxWidth=g.offsetWidth+"px");e&&(k.maxHeight=g.offsetHeight+"px");return g};a.D.G.J.K.prototype.Oc=function(){return"horizontal"===this.mM};a.D.G.J.K.prototype.xL=function(){return!this.Ny().hasChildNodes()};
a.D.G.J.K.prototype.XA=function(){this.Ts=this.Td();this.Hx();this.mt(0);this.Io();this.Ho()};a.D.G.J.K.prototype.cr=function(){this.lp=this.Ue=null};a.D.G.J.K.prototype.bi=function(a){a||this.XA();this.cr();this.Ue&&this.lp||(this.Ue=this.eA());a||this.Sw();a=this.Ue;this.iH(a.Ec,a.jg)};a.D.G.J.K.prototype.iH=function(a,b){var f=this.$o.style,e=this.Ws.style;if(this.Oc()){var g=0.5*(b-this.On);f.top=g+"px";e.top=g+"px"}else g=0.5*(a-this.Pn),this.Mn?(f.left=-g+"px",e.left=-g+"px"):(f.left=g+"px",
e.left=g+"px")};a.D.G.J.K.prototype.Sw=function(b){var c=this.Hg,f=this.Oc(),e=a.D.G.J.K,e=f?e.wJ(this.Kg):e.vJ(this.Kg);(f?c.offsetWidth:c.offsetHeight)>e&&this.JB(e);this.Fl=0;this.Cl=f?c.offsetWidth-e+this.Pn:c.offsetHeight-e+this.On;0>this.Cl&&(this.Cl=0);this.Io();this.Ho();this.Kj(b?this.Fl:this.Ts,!0);this.Ts=0};a.D.G.J.K.prototype.eI=function(){var b=this,c=this.Oc(),f=document.createElement("div");this.pc=f;var e=f.style;e.overflow="hidden";e.display=this.fl();e.position="relative";c&&(e.verticalAlign=
"top");var g=this.Kg,k=a.D.G.J.K,l=document.createElement("div");this.Hg=l;var m=l.style;m.position="relative";c&&(m.display="inline-block");f.appendChild(l);m=null;if(c){this.ut=m=k.Ux();var n=k.mr(),q=k.Yn();this.tt=q;var r=k.Yn(),p=k.Yn();this.np=p;r.appendChild(f);n.appendChild(q);n.appendChild(r);n.appendChild(p);m.appendChild(n)}n=k.Ux();q=k.nN(g,n,c);if(this.gr)for(var q=[],r=this.gr.children,p=r.length,s=0;s<p;s++){var v=r[s];1===v.nodeType&&q.push(v)}(this.$w=q)&&0<q.length&&(this.hr=n,l.appendChild(n));
m?g.appendChild(m):(this.Ct=m=document.createElement("div"),this.tp=n=document.createElement("div"),g.appendChild(m),g.appendChild(f),g.appendChild(n));c&&(c=f.offsetHeight,l=l.offsetHeight,c>l&&(e.marginBottom=l-c+"px"));k.Rf(f,"scroll",function(a){b.ps(a)})};a.D.G.J.K.prototype.fl=function(){return this.Oc()?"inline-block":"block"};a.D.G.J.K.prototype.tI=function(b,c,f){var e=this,g=document.createElement("div");this.Ws=g;b&&g.setAttribute("id",b);g.setAttribute("class",c);g.setAttribute("aria-hidden",
"true");c=g.style;c.display=this.fl();c.position="relative";if(b=this.Oc())c.verticalAlign="top";c=a.D.G.J.K;c.Rf(g,"click",function(){e.tB()});this.tt?this.Xs=c.vC(g,this.tt,b,!b):this.Ct.appendChild(g);f&&g.appendChild(f)};a.D.G.J.K.prototype.gI=function(b,c,f){var e=this,g=document.createElement("div");this.$o=g;b&&g.setAttribute("id",b);g.setAttribute("class",c);g.setAttribute("aria-hidden","true");c=g.style;c.display=this.fl();c.position="relative";if(b=this.Oc())c.verticalAlign="top";c=a.D.G.J.K;
c.Rf(g,"click",function(){e.sB()});this.np?this.Ps=c.vC(g,this.np,b,!b):this.tp.appendChild(g);f&&g.appendChild(f)};a.D.G.J.K.prototype.Ny=function(){var a=this.gr;a||(a=this.Hg);return a};a.D.G.J.K.prototype.eA=function(){var a=this.hr,b=this.$w,f={Ec:0,jg:0},e=[];if(this.Ny().hasChildNodes()&&a&&b&&0<b.length)for(var a=this.Oc(),g=0,g=this.Hg.offsetWidth,k=0,l=null,m=0;m<b.length;m++){var n=b[m];if(1===n.nodeType){var q=n.offsetWidth,r=n.offsetHeight,p={Ec:q,jg:r,id:n.id};a?(p.start=this.Mn?g-(n.offsetLeft+
q):n.offsetLeft,0===m&&(k=p.start),p.start-=k,f.Ec=p.start+q,f.jg=Math.max(f.jg,r),p.end=f.Ec-1):(p.start=n.offsetTop,f.Ec=Math.max(f.Ec,q),f.jg=p.start+r,p.end=f.jg-1);l&&l.end>=p.start&&(n=l.end-(p.start-1),l.end-=n,a?l.Ec-=n:l.jg-=n);e.push(p);l=p}}this.lp=e;return f};a.D.G.J.K.prototype.qj=function(){if(!this.lp){var a=this.eA();this.Ue||(this.Ue=a)}return this.lp};a.D.G.J.K.prototype.Zr=function(){return this.Ps?this.Ps:this.$o};a.D.G.J.K.prototype.cs=function(){return this.Xs?this.Xs:this.Ws};
a.D.G.J.K.prototype.VN=function(){this.Zr().style.display=this.fl()};a.D.G.J.K.prototype.XN=function(){this.cs().style.display=this.fl()};a.D.G.J.K.prototype.Ho=function(){this.Zr().style.display="none"};a.D.G.J.K.prototype.Io=function(){this.cs().style.display="none"};a.D.G.J.K.prototype.Qo=function(){return"none"!==this.Zr().style.display};a.D.G.J.K.prototype.Bs=function(){return"none"!==this.cs().style.display};a.D.G.J.K.prototype.Lr=function(){return this.Oc()?this.Pn:this.On};a.D.G.J.K.prototype.tO=
function(a){var b=this.Lr(),e=this.Td(),h=this.kj(),g=this.Zo();a<=this.Fl?(this.Bs()&&(h+=b,e-=b),this.Io()):g&&(this.Bs()||(h-=b,e+=b),this.XN());a>=this.Cl?(this.Qo()&&(h+=b),this.Ho()):g&&(this.Qo()||(h-=b),this.VN());this.mt(e);g?this.JB(h):this.Hx()};a.D.G.J.K.prototype.JB=function(a){var b=this.pc.style;a+="px";this.Oc()?b.maxWidth=a:b.maxHeight=a};a.D.G.J.K.prototype.Hx=function(){var a=this.pc.style;this.Oc()?a.maxWidth="":a.maxHeight=""};a.D.G.J.K.prototype.mt=function(a){var b=this.pc;
this.Oc()?b.scrollLeft=this.ir(a):b.scrollTop=a};a.D.G.J.K.prototype.kj=function(){var a=this.pc;return this.Oc()?a.offsetWidth:a.offsetHeight};a.D.G.J.K.prototype.Kj=function(a,b){this.Fg||(this.Nq=!1,this.CB(a,b))};a.D.G.J.K.prototype.CB=function(b,c){if(!this.xL()){this.Fg=!0;b=this.$H(b);this.tO(b);var e=this.rB;if(c||!e||b===this.Td())this.oA(b);else{var h=this;e.call(this.Oh,this.pc,this.ir(b),Math.abs(this.Td()-b)/a.D.G.J.K.CG,function(){h.oA(b)})}}};a.D.G.J.K.prototype.Td=function(){var a=
this.pc;return this.Oc()?this.aI(a.scrollLeft):a.scrollTop};a.D.G.J.K.prototype.Zo=function(){var a=this.Hg,b=this.pc;return this.Oc()?a.offsetWidth>b.offsetWidth:a.offsetHeight>b.offsetHeight};a.D.G.J.K.prototype.$H=function(a){!this.Zo()||a<this.Fl?a=this.Fl:a>this.Cl&&(a=this.Cl);return a};a.D.G.J.K.prototype.RK=function(b){var c=this.Fg;if(this.Zo()&&!this.Fg){var e=a.D.G.J.K.jK(b);0>e&&this.Qo()?(c=!0,this.sB()):0<e&&this.Bs()&&(c=!0,this.tB())}c&&(b.preventDefault(),b.stopPropagation())};a.D.G.J.K.prototype.YK=
function(a){a=a.touches;this.Zo()&&(!this.Fg&&1===a.length)&&(this.Nn=!0,a=a[0],this.lO=this.Oc()?a.pageX:a.pageY,this.gC=this.Td(),this.mO=this.sx(),this.nO=this.tx())};a.D.G.J.K.prototype.XK=function(b){if(this.Nn){var c=this.Oc();b=b.touches[0];b=(c?b.pageX:b.pageY)-this.lO;var e=this.pc;Math.abs(b)<a.D.G.J.K.DG*(c?e.offsetWidth:e.offsetHeight)?this.Kj(this.gC-b,!0):(this.Kj((c&&this.Mn?0<b:0>b)?this.mO:this.nO),this.Nn=!1)}};a.D.G.J.K.prototype.WK=function(){this.Nn&&this.Kj(this.gC);this.Nn=
!1};a.D.G.J.K.prototype.ps=function(){this.Nq&&!this.Fg&&this.CB(this.Td(),!0)};a.D.G.J.K.prototype.oA=function(a){this.mt(a);this.CN();this.Fg=!1;if(this.Ir){this.hj=this.qx();a=this.rx();var b=this.qj(),e=b[this.hj];this.hj!==a&&(this.Td()>e.start&&this.hj<b.length-2)&&(this.hj++,e=b[this.hj]);this.fJ=e.id;this.Ir.call(this.Oh,this.fJ)}};a.D.G.J.K.prototype.CN=function(){var a=this;window.setTimeout(function(){a&&(a.Nq=!0)},0)};a.D.G.J.K.prototype.sB=function(){this.Fg||this.Kj(this.sx())};a.D.G.J.K.prototype.tB=
function(){this.Fg||this.Kj(this.tx())};a.D.G.J.K.prototype.sx=function(){var a=this.IH(),b=0;return b=a===this.qx()?this.Td()+this.kj():this.KH(a)};a.D.G.J.K.prototype.tx=function(){var a=this.JH(),b=0,b=a===this.rx()?this.Td()-this.kj():this.HH(a);this.Qo()||(b+=this.Lr());b<this.Lr()&&(b=this.Fl);return b};a.D.G.J.K.prototype.KH=function(a){return this.qj()[a].start};a.D.G.J.K.prototype.HH=function(a){return this.qj()[a].end-this.kj()+1};a.D.G.J.K.prototype.qx=function(){var a=this.Qn(this.Td());
return 0>a?0:a};a.D.G.J.K.prototype.rx=function(){var a=this.Qn(this.Td()+this.kj()-1),b=this.qj();return 0>a?b.length-1:a};a.D.G.J.K.prototype.JH=function(){var a=this.Qn(this.Td()-1);return 0>a?0:a};a.D.G.J.K.prototype.IH=function(){var a=this.Qn(this.Td()+this.kj()),b=this.qj();return 0>a?b.length-1:a};a.D.G.J.K.prototype.Qn=function(a){for(var b=this.qj(),e=0;e<b.length;e++)if(a<=b[e].end)return e;return-1};a.D.G.J.K.prototype.ir=function(a){var b=a;if(this.Mn&&this.Oc())if(this.tH)b=-a;else if(this.vH||
this.uH)b=this.Hg.offsetWidth-this.pc.offsetWidth-a;return b};a.D.G.J.K.prototype.aI=function(a){return this.ir(a)};a.D.G.J.K.CG=1.1;a.D.G.J.K.DG=0.33;(function(){b.ta("oj.ojConveyorBelt",e.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{orientation:"horizontal",contentParent:null},Kc:function(){this._super();this.element.addClass("oj-conveyorbelt oj-component")},_init:function(){this.mb(!0)},refresh:function(){this._super();var a="rtl"===this.xc()!==
this.cx;a&&this.ur();this.mb(a)},mb:function(a){this.cx="rtl"===this.xc();var c=this.element,f=this.options;if(a&&!this.Rn){var h=f.orientation,g=null,k=null,l=null,m=null,n=null;"vertical"!==h?(g="oj-enabled oj-conveyorbelt-overflow-indicator oj-start oj-default",k="oj-enabled oj-conveyorbelt-overflow-indicator oj-end oj-default",l=this.Wn("oj-conveyorbelt-overflow-icon oj-start"),m=this.Wn("oj-conveyorbelt-overflow-icon oj-end"),n=this.kH):(g="oj-enabled oj-conveyorbelt-overflow-indicator oj-top oj-default",
k="oj-enabled oj-conveyorbelt-overflow-indicator oj-bottom oj-default",l=this.Wn("oj-conveyorbelt-overflow-icon oj-top"),m=this.Wn("oj-conveyorbelt-overflow-icon oj-bottom"),n=this.lH);var q={};q.jE=g;q.cE=k;q.iE=l;q.bE=m;g={};g.eh=b.xa.eh;g.Lm=b.xa.Lm;"true"!==c.attr("_ojConveyorBeltTesting")&&(g.pE=n);n=null;f.contentParent&&(n=e(f.contentParent)[0]);this.Rn=new window.adf.D.G.J.K(c[0],h,n,this.cx,q,g)}this.Rn.PQ(a);if(a)for(a=c.find(".oj-conveyorbelt-overflow-indicator"),c=a.size(),f=0;f<c;f++)h=
a.get(f),this.TN(h)},_destroy:function(){this.ur();this.element.removeClass("oj-conveyorbelt oj-component");this._super()},_setOption:function(a,b){var e=!1;switch(a){case "containerParent":case "orientation":e=!0}e&&this.ur();this._super(a,b);e&&this.mb(!0)},ur:function(){var a=this.Rn;a&&a.destroy();this.Rn=null},TN:function(a){this._on(a,{mousedown:function(a){e(a.currentTarget).addClass("oj-active")},mouseup:function(a){e(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){a=a.currentTarget;
e(a).addClass("oj-hover");e(a).removeClass("oj-default")},mouseleave:function(a){a=a.currentTarget;e(a).removeClass("oj-hover");e(a).removeClass("oj-active");e(a).addClass("oj-default")}})},Wn:function(a){var b=document.createElement("span");b.setAttribute("class","oj-component-icon oj-clickable-icon "+a);return b},kH:function(a,b,f,h){var g={};g.scrollLeft=b;e(a).animate(g,f,"swing",h)},lH:function(a,b,f,h){var g={};g.scrollTop=b;e(a).animate(g,f,"swing",h)},getNodeBySubId:function(a){if(null==a)return this.element?
this.element[0]:null;a=a.subId;return"oj-conveyorbelt-start-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-start")[0]:"oj-conveyorbelt-end-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-end")[0]:"oj-conveyorbelt-top-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-top")[0]:"oj-conveyorbelt-bottom-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-bottom")[0]:null}})})()});
//# sourceMappingURL=oj-modular.map