define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){(function(){var a=0;b.ta("oj.ojCollapsible",e.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{expanded:!1,disabled:null,expandOn:"click",expandArea:"disclosureIcon",beforeExpand:null,afterExpand:null,beforeCollapse:null,afterCollapse:null,optionChange:null},Ic:function(){this._super();this.kC=e();this.element.addClass("oj-collapsible oj-component");this.nA();this.Nb()},ag:function(a,b){a.show(b,{launcher:this.element.find(".oj-collapsible-header-icon").first(),
focus:"menu"})},NH:function(){var a=this.options.expanded?"oj-collapsible-open-icon":"oj-collapsible-close-icon";(this.Td()?e("\x3cspan\x3e"):e("\x3ca href\x3d'#'\x3e")).addClass("oj-component-icon oj-clickable-icon oj-collapsible-header-icon "+a).attr("aria-labelledby",this.header.attr("id")).prependTo(this.header);this.header.addClass("oj-collapsible-icons ")},Sx:function(){this.header.removeClass("oj-collapsible-icons").children(".oj-collapsible-header-icon").remove()},_destroy:function(){this.ox();
this.element.removeClass("oj-collapsible oj-component oj-collapsible-collapsed oj-disabled");this.Td()&&this.Rk(this.header).removeAttr("tabIndex");this.header.removeClass("oj-collapsible-header").each(function(){/^oj-collapsible/.test(this.id)&&this.removeAttribute("id")});this.Qk().removeAttr("role").removeAttr("aria-controls").removeAttr("aria-expanded").removeAttr("aria-disabled");this.Sx();this.Rk(this.content).removeAttr("tabIndex");this.content.css("display","").removeAttr("aria-hidden").removeAttr("tabIndex").removeClass("oj-component-content oj-collapsible-content").each(function(){/^oj-collapsible/.test(this.id)&&
this.removeAttribute("id")})},ox:function(){this.Hl();this.content&&(this.content.unwrap(),this.Df=null)},Td:function(){return this.element.hasClass("oj-disabled")},Fy:function(){return"header"==this.options.expandArea?"\x3e .oj-collapsible-header":"\x3e .oj-collapsible-header \x3e .oj-collapsible-header-icon"},_setOption:function(a,b){"expanded"===a?this.eN(b):("expandOn"===a||"expandArea"===a?(this.Hl(),this._super(a,b),this.mi()):this._super(a,b),"disabled"===a&&(this.header.add(this.header.next()),
this.element.toggleClass("oj-disabled",!!b)))},bi:function(a){if(!a.altKey&&!a.ctrlKey){var b=e.ui.keyCode;switch(a.keyCode){case b.SPACE:case b.ENTER:this.UB(a)}}},refresh:function(){this._super();this.ox();this.nA();this.Sx();this.Nb()},nA:function(){this.header=this.element.children(":first-child").addClass("oj-collapsible-header");this.content=this.header.next().addClass("oj-collapsible-content oj-component-content");this.content.wrap("\x3cdiv\x3e\x3c/div\x3e");this.Df=this.content.parent().addClass("oj-collapsible-wrapper");
this.options.disabled&&this.element.addClass("oj-disabled");this.Td()&&this.Rk(this.header).attr("tabIndex",-1)},Nb:function(){var b=this.header,c=this.content,e=this.options,h=this.VR="oj-collapsible-"+(this.element.attr("id")||++a),g=b.attr("id"),k=c.attr("id");g||b.attr("id",h+"-header");k||(k=h+"-content",c.attr("id",k));this.NH();b=this.Qk();b.attr("role","button").attr("aria-controls",k);this.Td()&&b.attr("aria-disabled",!0);this.Td()||this.pB(e.expanded?"0":"-1");this.element.toggleClass("oj-collapsible-collapsed",
!e.expanded);e.expanded?(c.attr({"aria-hidden":"false"}),b.attr("aria-expanded","true")):(this.Df.css({"max-height":0,"overflow-y":"hidden",display:"none"}),this.Df.css("max-height",0),c.attr({"aria-hidden":"true"}),b.attr("aria-expanded","false"));this.mi()},eN:function(a){a!==this.options.expanded&&(a?this.expand(!0):this.collapse(!0))},mi:function(){var a={keydown:this.bi},b=this.options.expandOn;if(b){var f=this;e.each(b.split(" "),function(b,c){a[c]=f.UB})}b=this.element.find(this.Fy());this._on(b,
a);this._on(this.Df,{transitionend:this.gp,webkitTransitionEnd:this.gp,otransitionend:this.gp,oTransitionEnd:this.gp});this.Td()||(this._on(this.element,{ojafterexpand:this.gy,ojaftercollapse:this.gy,ojfocus:this.ry,ojfocusout:this.ry}),this._hoverable(b),this._focusable(b),this.JG(b))},Hl:function(){this._off(this.element.find(this.Fy()));this.Df&&this._off(this.Df);this._off(this.element.add(this.content))},UB:function(a){this.Td()||(this.options.expanded?this.collapse(!0,a):this.expand(!0,a),a.preventDefault(),
a.stopPropagation(),this.header.find(".oj-collapsible-header-icon").focus())},gy:function(a){if(!this.Td()&&a.target===this.element[0]&&!a.isDefaultPrevented()){var b=this.element,e=this.options,h=this.content,g=this.Df,k="ojaftercollapse"===a.type;a.preventDefault();e.expanded=!k;g.np=g.outerHeight();k?(g.removeClass("oj-collapsible-transition"),g.css({"max-height":g.np,"overflow-y":"hidden"}),setTimeout(function(){g.addClass("oj-collapsible-transition").css({"max-height":0});b.addClass("oj-collapsible-collapsed")},
10)):(g.show(),setTimeout(function(){g.np+=h.outerHeight();g.addClass("oj-collapsible-transition").css({"max-height":g.np});b.removeClass("oj-collapsible-collapsed")},1));this.header.find(".oj-collapsible-header-icon").toggleClass("oj-collapsible-open-icon",!k).toggleClass("oj-collapsible-close-icon",k||!1).end();this.content.attr("aria-hidden",k);this.Qk().attr("aria-expanded",!k);this.pB(k?"-1":"0")}},ry:function(a){if(this.Td())return null;"ojfocusout"==a.type?(this.Qk().attr("tabIndex",-1),a.preventDefault(),
a.stopPropagation()):"ojfocus"==a.type&&(this.Qk().attr("tabIndex",0).focus(),a.preventDefault(),a.stopPropagation())},Qk:function(){return this.Rk(this.header).first()},pB:function(a){return this.Rk(this.content).attr("tabIndex",a)},Rk:function(a){return this.Td()?a.find("span"):a.find("a,:input")},expand:function(a,b){if(!this.Td()){var e={header:this.header,content:this.content};a&&!1===this._trigger("beforeExpand",b,e)||(this._trigger("afterExpand",b,e),this.Qe("expanded",!1,!0,b?!0:!1))}},collapse:function(a,
b){if(!this.Td()){var e={header:this.header,content:this.content};a&&!1===this._trigger("beforeCollapse",b,e)||(this._trigger("afterCollapse",b,e),this.Qe("expanded",!0,!1,b?!0:!1))}},gp:function(a){this.Td()||("max-height"==(a.originalEvent?a.originalEvent.propertyName:null)&&(a.preventDefault(),a.stopPropagation()),this.options.expanded?this.Df.css({"max-height":9999,"overflow-y":""}):this.Df.hide(),this.Df.removeClass("oj-collapsible-transition"))},JG:function(a){this.kC=this.kC.add(a);this._on(a,
{mousedown:function(a){e(a.currentTarget).addClass("oj-active")},mouseup:function(a){e(a.currentTarget).removeClass("oj-active")}})},Qe:function(a,b,e,h){this._trigger("optionChange",h,{option:a,previousValue:b,value:e,optionMetadata:{writeback:h?"shouldWrite":"shouldNotWrite"}})},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-collapsible-content":return this.content;case "oj-collapsible-header":return this.header;case "oj-collapsible-header-icon":return this.header.find("."+
a)[0]}return null}})})()});
//# sourceMappingURL=oj-modular.map