define(["ojs/ojcore","jquery","jqueryui"],function(b,e){function a(a,b){this.ZO=function(){return a};this.FP=function(){return b}}function d(a,b,c,d,l){var m=void 0;Object.defineProperty(b,c,{get:function(){if(c===a.zB)return m||{};if(void 0!==m&&!e.isPlainObject(m))return m;var b=d(l?l():c);return e.isPlainObject(b)?e.widget.extend({},b||{},m||{}):void 0===m?b:m},set:function(a){m=a},enumerable:!0})}b.Components={};o_("Components",b.Components,b);b.Components.dE=function(a){b.Components.Px=e.widget.extend(b.Components.Px||
{},a)};o_("Components.setDefaultOptions",b.Components.dE,b);b.Components.VC=function(){return b.Components.Px||{}};o_("Components.getDefaultOptions",b.Components.VC,b);b.Components.BC=function(b){return new a(b,!0)};o_("Components.createDynamicPropertyGetter",b.Components.BC,b);b.Components.Vt=function(a,b){var d=e(a);if(null==b){var k=d.data(c);k&&(b=k[0])}return null!=b&&(k=d[b],"function"===typeof k)?k.bind(d):null};o_("Components.getWidgetConstructor",b.Components.Vt,b);b.Components.nn="data-oj-container";
var c="oj-component-names";e.widget("oj.baseComponent",{options:{contextMenu:null,rootAttributes:void 0},refresh:function(){this.Ns=null},pG:function(){var a=this.options.rootAttributes;if(a){var b=this.widget();if(null!=b){var c=a["class"];c&&b.addClass(c);if(c=a.style){var d=b.attr("style");d?b.attr("style",d+";"+c):b.attr("style",c)}a=e.extend({},a);delete a["class"];delete a.style;b.attr(a)}}},_create:function(){this.iw(this.element);this.Mf();this.Ic();this.xh()},_getCreateOptions:function(){var c=
{},d={};this.hw(d);for(var g in d)c[g]=new a(d[g]);d=[];for(g=this.constructor.prototype;null!=g&&g.widgetName;)d.push(g.widgetName),g=Object.getPrototypeOf(g);d.push("default");g=b.Components.VC();for(var k=d.length;0<=k;k--){var l=g[d[k]];void 0!==l&&(c=e.widget.extend(c,l))}return c},Mf:function(){this.BB()},Ic:function(){this.activeable=e();this.BB();var a=this.element,b=this.widgetName,d=a.data(c);d||(d=[],a.data(c,d));0>d.indexOf(b)&&d.push(b)},xh:function(){this.pG();this.Bt=this.eventNamespace+
"contextMenu";this.AB()},iw:function(a){var b=this;this.Vs=[];e.each(a,function(a,c){var d={},f=c.attributes;b.Vs.push({element:c,attributes:d});e.each(f,function(a,b){var f=b.name,h={attr:b.value};h.prop=e(c).prop(f);d[f]=h})})},cn:function(a){var b=this.Vs;a=a[0];for(var c=0,d=b.length;c<d;c++){var e=b[c];if(e.element===a)return e.attributes}return{}},TQ:function(){e.each(this.Vs,function(a,b){var c=e(b.element),d=b.attributes;if(1===c.length){for(var l=b.element.attributes,m=[],n=0,q=l.length;n<
q;n++)l[n].name in d||m.push(l[n].name);n=0;for(q=m.length;n<q;n++)c.removeAttr(m[n]);for(var r in d)c.attr(r,d[r].attr)}})},hw:function(a){var c=this.uv(),d=b.L.Kt(c)||{},e;for(e in d)a[e]=function(a){return b.L.Kt(c)[a]}},uv:o_c("widgetFullName"),q:function(a,c){var d={},e;2<arguments.length?d=Array.prototype.slice.call(arguments,1):2==arguments.length&&(d=arguments[1],"object"===typeof d||d instanceof Array||(d=[d]));e=this.options[a];return null==e?a:b.L.lb(e.toString(),d)},getNodeBySubId:function(a){return null==
a||a.subId?this.element?this.element[0]:null:null},destroy:function(){this.XB();this._super();this.widget().removeClass("oj-disabled");this.hoverable.removeClass("oj-hover");this.focusable.removeClass("oj-focus");this.activeable.removeClass("oj-active");var a=this.element,b=this.widgetName,d=a.data(c);d&&(b=d.indexOf(b),0<=b&&(d.splice(b,1),0===d.length&&a.removeData(c)))},option:function(a,b){var c;if(0<arguments.length&&"string"===typeof a&&void 0!==b){var d=a.indexOf(".");0<d&&(this.zB=a.substring(0,
d))}try{c=this._superApply(arguments)}finally{return this.zB=null,c}},_setOption:function(a,b){"disabled"===a?(this.options[a]=b,this.widget().toggleClass("oj-disabled",!!b).attr("aria-disabled",b),b&&(this.hoverable.removeClass("oj-hover"),this.focusable.removeClass("oj-focus"),this.activeable||(this.activeable=e()),this.activeable.removeClass("oj-active"))):(this._super(a,b),"contextMenu"===a&&this.AB());return this},AB:function(){this.XB();var a=this.options.contextMenu;a||(a=this.element.attr("contextmenu"))&&
(a="#"+a);a&&(a=e(a).data("oj-ojMenu"));if(a){var b=this;this.Iz().on("keydown"+this.Bt+" contextmenu"+this.Bt,function(c){return"contextmenu"===c.type||121==c.which&&c.shiftKey?(b.ag(a,c),!1):!0})}},XB:function(){this.Iz().off(this.Bt)},ag:function(a,b){a.show(b,{launcher:this.element,focus:"menu"})},Iz:function(){var a=this.widget();return a?a:e()},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(a){e(a.currentTarget).addClass("oj-hover")},mouseleave:function(a){e(a.currentTarget).removeClass("oj-hover")}})},
_focusable:function(a){this.focusable=this.focusable.add(a);this._on(a,{focusin:function(a){e(a.currentTarget).addClass("oj-focus")},focusout:function(a){e(a.currentTarget).removeClass("oj-focus")}})},xq:function(a){this.activeable=this.activeable.add(a);this._on(a,{mousedown:function(a){e(a.currentTarget).addClass("oj-active")},mouseup:function(a){e(a.currentTarget).removeClass("oj-active")}})},Wj:function(a){return this.options[a]},xc:function(){return"rtl"===document.documentElement.dir?"rtl":
"ltr"},bJ:function(){if(!this.Ns){var a={};this.Ns=a;for(var c=this.element[0],d=[];c;){var e=c.getAttribute,e=e?e.call(c,b.Components.nn):null;null!=e&&d.push(e);c=c.parentNode}a.containers=d}return this.Ns},BB:function(){function c(){return h.bJ()}var h=this,g=this.options,k;for(k in g){var l=g[k];if("undefined"!==typeof l&&l instanceof a){var m=l.ZO();e.isFunction(m)?(delete g[k],d(this,g,k,m,l.FP()?c:void 0)):b.F.error("Dynamic getter for property %s is not a function",k)}}}});b.ta=function(a,
b,c){e.widget(a,b,c);if("oj.oj"===a.substring(0,5)||"oj._oj"===a.substring(0,6)){b=a.split(".");a=b[0];b=b[1];var d=a+"-"+b;e.expr[":"][("_"===b.substring(0,1)?"_"+a+"-"+b.substring(3):a+"-"+b.substring(2)).toLowerCase()]=function(a){return!!e.data(a,d)}}};b.xa={};b.xa.qF="\\x3chtml\\x3e";b.xa.pF="\\x3c/html\\x3e";b.xa.KF={SPAN:1,B:1,A:1,I:1,EM:1,BR:1,HR:1,LI:1,OL:1,UL:1,P:1,TT:1,BIG:1,SMALL:1,PRE:1};b.xa.JF={"class":1,style:1,href:1};b.xa.HP=function(a){return 0===a.indexOf(b.xa.qF)&&a.lastIndexOf(b.xa.pF)===
a.length-7?!0:!1};b.xa.yO=function(a){var c=e(document.createElement("span")).get(0);(c.innerHTML=a)&&0<=a.indexOf("\\x3c")&&b.xa.nx(c);return c};b.xa.nx=function(a){for(var c=a.childNodes,d,k,l,m,n,q=c.length-1;0<=q;)if(d=c.item(q),1===d.nodeType){if(b.xa.KF[d.nodeName])for(k=d.attributes,n=k.length-1;0<=n;n--)l=k[n],(m=void 0!==e(d).attr(l))&&(b.xa.JF[l.name]||d.removeAttribute(l.nodeName));b.xa.nx(d)}else a.removeChild(d)};b.xa.EP=function(a,c){b.f.re(a);b.f.re(c);for(var d=c.parentNode;d;){if(d==
a)return!0;d=d.parentNode}return!1};b.xa.im=function(a,c){b.f.re(a);b.f.re(c);return c==a?!0:b.xa.EP(a,c)};b.xa.$g=function(a,c){var d=e(a),k=d.data(b.xa.qn);null==k&&(k=new b.xa.mG(a),d.data(b.xa.qn,k),k.start());k.addListener(c)};b.xa.Cm=function(a,c){var d=e(a),k=d.data(b.xa.qn);null!=k&&(k.removeListener(c),k.isEmpty()&&(k.stop(),d.removeData(b.xa.qn)))};b.xa.YK=(window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||function(a){return window.setTimeout(a,
0)}).bind(window);b.xa.mG=function(a){this.Ko=jQuery.Callbacks();this.addListener=function(a){this.Ko.add(a)};this.removeListener=function(a){this.Ko.remove(a)};this.isEmpty=function(){return this.Ko.empty()};this.start=function(){var b=a.childNodes[0];this.pe=document.createElement("div");this.pe.className="oj-helper-detect-resize";var c=document.createElement("div");this.pe.appendChild(c);a.insertBefore(this.pe,b);this.Xo=this.es.bind(this);this.pe.addEventListener("scroll",this.Xo,!1);this.Eg=
document.createElement("div");this.Eg.className="oj-helper-detect-resize";c=document.createElement("div");c.style.width="200%";c.style.height="200%";this.Eg.appendChild(c);a.insertBefore(this.Eg,b);this.Eg.addEventListener("scroll",this.Xo,!1);this.Aq(this.pe.offsetWidth,this.pe.offsetHeight)};this.stop=function(){this.pe.removeEventListener("scroll",this.Xo);this.Eg.removeEventListener("scroll",this.Xo);a.removeChild(this.pe);a.removeChild(this.Eg)};this.es=function(a){a.stopPropagation();a=this.pe;
var c=a.offsetWidth,d=a.offsetHeight;if(this.QL!=c||this.PL!=d){this.eB=2;this.Aq(c,d);var f=this.Ko;b.xa.YK(function(){f.fire(c,d)})}else 0<this.eB&&(0==a.scrollLeft||0==a.scrollTop)&&(this.eB--,this.Aq(c,d))};this.Aq=function(a,b){this.QL=a;this.PL=b;var c=this.pe.firstChild;c.style.width=a+1+"px";c.style.height=b+1+"px";this.pe.scrollLeft=1;this.pe.scrollTop=1;this.Eg.scrollLeft=a;this.Eg.scrollTop=b}};b.xa.qn="_ojResizeTracker";b.Ja=function(a){this.Init(a)};b.a.fa(b.Ja,b.a,"oj.ComponentMessaging");
b.Ja.jd={NONE:"none",Rm:"notewindow",nk:"placeholder"};b.Ja.hq={};b.Ja.uu=function(a,c){a&&"function"===typeof c&&(b.Ja.hq[a]=c)};b.Ja.prototype.Init=function(a){b.Ja.j.Init.call(this);this.Cb=a;this.Bk=!1;this.WK()};b.Ja.prototype.Zg=function(a,c){var d=this;b.f.pd(c);this.Bk?this.oM(a,c):(e.each(this.ni,function(b,e){e.Zg(d.Cb,a,c)}),this.Bk=!0)};b.Ja.prototype.update=function(a){b.f.pd(a);b.f.pC(this.Bk);this.Bk&&e.each(this.ni,function(b,c){c.update(a)})};b.Ja.prototype.eh=function(a){b.f.pd(a);
e.each(this.ni,function(b,c){c.eh(a)});this.Bk=!1;this.ni={}};b.Ja.prototype.Qn=function(a,c){return new (b.Ja.hq[a]||b.Ja.hq.none)(c)};b.Ja.prototype.Sy=function(){var a={},c=!1,d=this.Cb.options.placeholder,k,l={},m=this;e.each(this.Cb.options.messagingDisplayOptions||{},function(a,f){c=!1;k=a+"";Array.isArray(f)?e.each(f,function(a,b){c||(c=m.aB(k,b,d,l))}):"string"===typeof f&&(c||(c=m.aB(k,f,d,l)));c||(l[k]=b.Ja.jd.NONE)});e.each(b.Ja.jd,function(b,c){a[c]=[]});e.each(l,function(b,c){a[c].push(b)});
return a};b.Ja.prototype.aB=function(a,c,d,e){var l=!1;switch(c){case b.Ja.jd.nk:"converterHint"!==a||(l||d)||(e[a]=c,l=!0);break;default:l||(e[a]=c,l=!0)}return l};b.Ja.prototype.WK=function(){var a=this.Sy(),c=a[b.Ja.jd.Rm],d=a[b.Ja.jd.NONE],a=a[b.Ja.jd.nk],e={};0<c.length&&(e[b.Ja.jd.Rm]=this.Qn(b.Ja.jd.Rm,c));0<a.length&&(e[b.Ja.jd.nk]=this.Qn(b.Ja.jd.nk,a));0<d.length&&(e[b.Ja.jd.NONE]=this.Qn(b.Ja.jd.NONE,d));this.ni=e};b.Ja.prototype.oM=function(a,b){var c=this.Sy(),d,l=this;e.each(c,function(c,
e){d=l.ni[c];e&&0<e.length?d?d&&d.bQ(e,b):(d=l.Qn(c,e),l.ni[c]=d,d.Zg(l.Cb,a,b)):d&&(d.eh(b),delete l.ni[c])})};b.Qa=function(a){this.Init(a)};b.Ja.uu(b.Ja.jd.NONE,b.Qa);b.Qa.rn="oj-invalid";b.Qa.sn="oj-warning";b.a.fa(b.Qa,b.a,"oj.MessagingStrategy");b.Qa.prototype.Init=function(a){b.f.st(a);b.Qa.j.Init.call(this);this.Un=a};b.Qa.prototype.Zg=function(a,b,c){this.bb=b;this.Cb=a;this.dC(c)};b.Qa.prototype.update=function(a){this.dC(a);a=this.bb;var c=this.Uu(),d=[],e=[],l=!1,m=this.Cb.widget();a&&
(this.IE()?this.Xu()&&c===b.C.Ha.WARNING?(d.push(b.Qa.rn),e.push(b.Qa.sn)):(d.push(b.Qa.rn),d.push(b.Qa.sn)):(d.push(b.Qa.sn),e.push(b.Qa.rn),l=!0),m.removeClass(d.join(" ")).addClass(e.join(" ")),a.attr({"aria-invalid":l}))};b.Qa.prototype.eh=function(){this.Cb.widget().removeClass(b.Qa.rn).removeClass(b.Qa.sn);this.bb.removeAttr("aria-invalid").removeAttr("aria-describedby");this.Cb=this.bb=null};b.Qa.prototype.bQ=function(a,b){this.Init(a);this.update(b)};b.Qa.prototype.Vu=function(){return this.Vp().hP()};
b.Qa.prototype.Uu=function(){return this.Vp().Xl()};b.Qa.prototype.Tu=function(){var a=[],b=this.sl.converterHint;b&&a.push(b);return a};b.Qa.prototype.HE=function(){var a=[];e.each(this.sl.validatorHint||[],function(b,c){a.push(c)});return a};b.Qa.prototype.GE=function(){return this.sl.title||""};b.Qa.prototype.Vp=function(){return this.sl.validityState};b.Qa.prototype.Xu=function(){var a=this.Vu();return a&&0<a.length?!0:!1};b.Qa.prototype.VE=function(){return-1!==this.Un.indexOf("messages")?!0:
!1};b.Qa.prototype.Yp=function(){return-1!==this.Un.indexOf("converterHint")?!0:!1};b.Qa.prototype.cv=function(){return-1!==this.Un.indexOf("validatorHint")?!0:!1};b.Qa.prototype.XE=function(){return-1!==this.Un.indexOf("title")?!0:!1};b.Qa.prototype.IE=function(){return this.Vp().isValid()};b.Qa.prototype.dC=function(a){this.sl=e.extend(this.sl||{},a)};b.je=function(a){this.Init(a)};b.Ja.uu(b.Ja.jd.nk,b.je);b.a.fa(b.je,b.Qa,"oj.PlaceholderMessagingStrategy");b.je.prototype.Init=function(a){b.je.j.Init.call(this,
a)};b.je.prototype.Zg=function(a,c,d){b.je.j.Zg.call(this,a,c,d);this.DA()};b.je.prototype.update=function(a){b.je.j.update.call(this,a);this.DA()};b.je.prototype.eh=function(a){b.je.j.eh.call(this,a)};b.je.prototype.DA=function(){var a=this.bb;this.Cb.widget();if(this.WE()&&a&&(a=this.Tu(),a=a.length?a[0]:"")){var b={};b.placeholder=a;b._oj_messaging_update=!0;this.Cb.option(b)}};b.je.prototype.WE=function(){return this.Yp()};b.tg=function(a,b,c){this.Init(a,b,c)};b.a.fa(b.tg,b.a,"oj.ComponentValidity");
b.tg.prototype.Init=function(a,c,d){b.tg.j.Init.call(this);this.iC=a;this.Bs=c;this.Sz=d};b.tg.prototype.isValid=o_c("iC");b.tg.prototype.hP=function(){return this.Bs?this.Bs:[]};b.tg.prototype.Xl=o_c("Sz");b.tg.prototype.update=function(a,b,c){this.iC=a;this.Bs=b;this.Sz=c};b.qk={};o_("Test",b.qk,b);b.qk.ready=!1;o_("Test.ready",b.qk.ready,b);b.qk.SO=function(a){var c=a;if(b.nb.Ae(a))try{c=e.parseJSON(a)}catch(d){return null}return c&&c.element&&(a=e(c.element))?b.Components.Vt(a[0],c.component)("getNodeBySubId",
{subId:c.subId}):null};o_("Test.domNodeForLocator",b.qk.SO,b);e(document).ready(function(){var a=e("\x3cdiv style\x3d'border: 1px solid;border-color:red green;position: absolute;top: -999px;background-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs\x3d);'\x3e\x3c/div\x3e"),b;a.appendTo("body");b=a.css("backgroundImage");a.css("borderTopColor")!=a.css("borderRightColor")&&(null==b||"none"!=b&&"url (invalid-url:)"!=b)||e("body").addClass("oj-hicontrast");a.remove()});
e(document).ready(function(){"Microsoft Internet Explorer"==navigator.appName&&e("html").addClass("oj-slow-borderradius oj-slow-cssgradients oj-slow-boxshadow")});b.Hi={};b.Hi.OD=function(a,c){b.f.pd(a,"position");for(var d=e.extend({},a),k=0;k<b.Hi.gv.length;k++){var l=b.Hi.gv[k],m=d[l];m&&(d[l]=m.replace("start",c?"right":"left").replace("end",c?"left":"right"))}return d};b.Hi.gv=["my","at"]});
//# sourceMappingURL=oj-modular.map