define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(b){b.Jb=function(e,a,d,c,f,h,g){b.f.Eb(e,null);b.f.Eb(a,null);b.f.Eb(d,null);b.f.Eb(c,null);b.f.Ql(h);this.bf=e;this.wi=a;this.De=d;this.hg=c;this.lh=f;this.rc=h;this.xi=g};o_("CollectionCellSet",b.Jb,b);b.Jb.prototype.getData=function(e){var a=this;this.sa(e);this.sa(e).done(function(b){a.ed=b});if(null==a.ed)return null;e=e.column;b.f.assert(e>=this.De&&e<=this.hg);return a.ed.get(this.rc[e])};b.a.b("CollectionCellSet.prototype.getData",
{getData:b.Jb.prototype.getData});b.Jb.prototype.getMetadata=function(e){var a=this;this.sa(e);this.sa(e).done(function(b){a.ed=b});if(null==a.ed)return null;e=e.column;b.f.assert(e>=this.De&&e<=this.hg);return{keys:{row:b.uh.fj(a.ed),column:this.rc[e]}}};b.a.b("CollectionCellSet.prototype.getMetadata",{getMetadata:b.Jb.prototype.getMetadata});b.Jb.prototype.sa=function(e){var a;b.f.pd(e);a=e.row;null!=this.xi&&(a+=this.xi);e=e.column;b.f.assert(a>=this.bf&&a<=this.wi&&e>=this.De&&e<=this.hg);return this.lh.at(a,
{deferred:!0})};b.Jb.prototype.V=function(b){return"row"===b?Math.max(0,this.wi-this.bf):"column"===b?Math.max(0,this.hg-this.De):0};b.a.b("CollectionCellSet.prototype.getCount",{V:b.Jb.prototype.V});b.Jb.prototype.bm=o_c("bf");b.a.b("CollectionCellSet.prototype.getStartRow",{bm:b.Jb.prototype.bm});b.Jb.prototype.YC=o_c("wi");b.a.b("CollectionCellSet.prototype.getEndRow",{YC:b.Jb.prototype.YC});b.Jb.prototype.$l=o_c("De");b.a.b("CollectionCellSet.prototype.getStartColumn",{$l:b.Jb.prototype.$l});
b.Jb.prototype.XC=o_c("hg");b.a.b("CollectionCellSet.prototype.getEndColumn",{XC:b.Jb.prototype.XC});b.Jb.prototype.getCollection=o_c("lh");b.a.b("CollectionCellSet.prototype.getCollection",{getCollection:b.Jb.prototype.getCollection});b.Jb.prototype.fh=o_c("rc");b.a.b("CollectionCellSet.prototype.getColumns",{fh:b.Jb.prototype.fh});b.uh=o_a();b.uh.fj=function(b){var a;a=b.he();null==a&&(a=b.Gi());return a};b.$b=function(e,a,d,c,f,h){b.f.Eb(e,null);b.f.Eb(a,null);b.f.Ql(d);this.sc=e;this.af=a;this.Bp=
d;this.lh=c;this.Ce=f;this.xi=h};o_("CollectionHeaderSet",b.$b,b);b.$b.prototype.getData=function(e){b.f.assert(e<=this.af&&e>=this.sc);var a=this;return null!=this.Ce&&null!=this.lh?(null!=this.xi&&(e+=this.xi),this.lh.at(e,{deferred:!0}).done(function(b){a.ed=b}),a.ed.get(this.Ce)):this.Bp[e]};b.a.b("CollectionHeaderSet.prototype.getData",{getData:b.$b.prototype.getData});b.$b.prototype.getMetadata=function(e){var a;return null!=this.Ce&&null!=this.lh?(a=this,null!=this.xi&&(e+=this.xi),this.lh.at(e,
{deferred:!0}).done(function(b){a.ed=b}),null==a.ed?null:{key:b.uh.fj(a.ed)}):{key:this.getData(e)}};b.a.b("CollectionHeaderSet.prototype.getMetadata",{getMetadata:b.$b.prototype.getMetadata});b.$b.prototype.V=function(){return Math.max(0,this.af-this.sc)};b.a.b("CollectionHeaderSet.prototype.getCount",{V:b.$b.prototype.V});b.$b.prototype.Ba=o_c("sc");b.a.b("CollectionHeaderSet.prototype.getStart",{Ba:b.$b.prototype.Ba});b.$b.prototype.WC=o_c("af");b.a.b("CollectionHeaderSet.prototype.getEnd",{WC:b.$b.prototype.WC});
b.$b.prototype.cD=o_c("Bp");b.a.b("CollectionHeaderSet.prototype.getHeaders",{cD:b.$b.prototype.cD});b.$b.prototype.Yl=o_c("Ce");b.a.b("CollectionHeaderSet.prototype.getRowHeader",{Yl:b.$b.prototype.Yl});b.$b.prototype.getCollection=o_c("lh");b.a.b("CollectionHeaderSet.prototype.getCollection",{getCollection:b.$b.prototype.getCollection});b.W=function(e,a){this.ba=e;null!=a&&(this.qg=a.rowHeader,this.columns=a.columns);this.S=0;this.Ue=this.Mb=-1;b.W.j.constructor.call(this)};o_("CollectionDataGridDataSource",
b.W,b);b.a.fa(b.W,b.Kb,"oj.CollectionDataGridDataSource");b.W.prototype.Init=function(){b.W.j.Init.call(this);this.Hp={};!this.rs()&&(null==this.columns&&0<this.ba.length)&&(this.columns=this.ba.first().keys(),-1!=this.columns.indexOf(this.qg)&&this.columns.splice(this.columns.indexOf(this.qg),1));this.BM()};b.a.b("CollectionDataGridDataSource.prototype.Init",{Init:b.W.prototype.Init});b.W.prototype.BM=function(){this.ba.on("add",this.rK.bind(this));this.ba.on("remove",this.tK.bind(this));this.ba.on("change",
this.sK.bind(this));this.ba.on("refresh",this.UJ.bind(this))};b.W.prototype.rs=function(){return null!=this.ba.url};b.W.prototype.aL=function(){return this.rs()?null!=this.data:!0};b.W.prototype.Bz=function(b){if(this.rs()){if("column"===b)return null!=this.columns;if("row"===b&&null!=this.qg)return null!=this.data}return!0};b.W.prototype.V=function(b){if(!this.Bz(b))return this.precision="estimate",-1;this.precision="exact";return"row"==b?this.size():"column"==b?this.columns.length:0};b.a.b("CollectionDataGridDataSource.prototype.getCount",
{V:b.W.prototype.V});b.W.prototype.xe=function(b){null==this.precision&&this.V(b);return this.precision};b.a.b("CollectionDataGridDataSource.prototype.getCountPrecision",{xe:b.W.prototype.xe});b.W.prototype.td=function(b,a,d){var c,f;c=b.axis;this.Bz(c)?this.gz(b,a,d):null!=a&&(f={},f.rP=b,f.callbacks=a,f.vt=d,this.Hp[c]=f)};b.a.b("CollectionDataGridDataSource.prototype.fetchHeaders",{td:b.W.prototype.td});b.W.prototype.gz=function(e,a,d){var c,f,h,g;c=e.axis;f=e.start;h=e.count;b.f.assert("row"===
c||"column"===c);b.f.assert(0<h);"column"===c?null!=this.columns?(h=Math.min(this.columns.length,f+h),g=new b.$b(f,h,this.columns)):g=new b.Md(f,f,c,null):"row"===c&&(null!=this.qg?(h=Math.min(this.size(),f+h),0<this.Mb?(h=Math.min(h,this.S+this.Mb),h=Math.min(h,this.totalSize()-this.S),g=new b.$b(f,h,this.columns,this.ba,this.qg,this.S)):g=new b.$b(f,h,this.columns,this.ba,this.qg)):g=new b.Md(f,f,c,null));null!=a&&a.success&&a.success.call(d.success,g,e);this.Hp[c]=null};b.W.prototype.Qy=function(e){var a,
d,c,f,h,g;for(a=0;a<e.length;a+=1)d=e[a],b.f.assert("row"===d.axis||"column"===d.axis),b.f.assert(0<d.count),"row"===d.axis?(c=d.start,f=d.count):"column"===d.axis&&(h=d.start,g=d.count);return{rowStart:c,rowCount:f,colStart:h,colCount:g}};b.W.prototype.fz=function(e,a,d){var c,f,h,g;c=this.Qy(e);f=c.rowStart;h=Math.min(this.size(),f+c.rowCount);g=c.colStart;c=Math.min(this.columns.length,g+c.colCount);0<this.Mb?(h=Math.min(this.Mb,this.totalSize()-this.S),f=new b.Jb(f,h,g,c,this.ba,this.columns,
this.S)):f=new b.Jb(f,h,g,c,this.ba,this.columns);null!=a&&null!=a.success&&(null!=a&&null==d&&(d={}),a.success.call(d.success,f,e),this.CI=0);this.oh=null};b.W.prototype.rd=function(b,a,d){this.aL()?this.fz(b,a,d):(null!=a&&(this.oh={},this.oh.wO=b,this.oh.callbacks=a,this.oh.vt=d),this.DI(b))};b.a.b("CollectionDataGridDataSource.prototype.fetchCells",{rd:b.W.prototype.rd});b.W.prototype.oA=function(b){var a,d;a=this.Hp[b];null!=a&&(b=a.rP,d=a.callbacks,a=a.vt,this.gz(b,d,a))};b.W.prototype.hM=function(){this.fz(this.oh.wO,
this.oh.callbacks,this.oh.vt)};b.W.prototype.DI=function(e){var a;e=this.Qy(e);a=e.rowStart;0<this.Mb&&(a+=this.S);this.ba.Np(a,e.rowCount).done(function(){var d=this.ba.at(a,{deferred:!0});null!=d&&void 0===this.columns&&d.done(function(a){this.columns=a.keys();-1!=this.columns.indexOf(this.qg)&&this.columns.splice(this.columns.indexOf(this.qg),1)}.bind(this));null!=this.Hp&&(this.oA("column"),this.oA("row"));null!=this.oh&&this.hM();0<this.Mb&&b.Kb.j.handleEvent.call(this,"sync",!0)}.bind(this))};
b.W.prototype.keys=function(e){var a=e.row+this.S;return{row:void 0===this.ba.models[a]?void 0:b.uh.fj(this.ba.models[a]),column:this.columns[e.column]}};b.a.b("CollectionDataGridDataSource.prototype.keys",{keys:b.W.prototype.keys});b.W.prototype.vd=function(b){var a=b.column;return{row:this.ba.models.indexOf(this.ba.get(b.row)),column:void 0===this.columns?this.ba.first().keys().indexOf(a):this.columns.indexOf(a)}};b.a.b("CollectionDataGridDataSource.prototype.indexes",{vd:b.W.prototype.vd});b.W.prototype.getCapability=
function(b){return"sort"===b?"column":"move"===b?"row":null};b.a.b("CollectionDataGridDataSource.prototype.getCapability",{getCapability:b.W.prototype.getCapability});b.W.prototype.sort=function(b,a,d){var c,f=b.direction,h=b.key;b=b.axis;null==d&&(d={});"column"===b?(-1<this.ba.Ht&&this.ba.hasMore?(this.ba.comparator=h,this.ba.sortDirection="ascending"===f?1:-1):("ascending"===f&&(c=function(a,b){var c,d;a=a.get(h);b=b.get(h);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString(),c=!0);b instanceof
Date&&(b=b.toISOString(),d=!0);return c&&d?a<b?-1:a===b?0:1:c?1:d?-1:a-b}),"descending"===f&&(c=function(a,b){var c,d;a=a.get(h);b=b.get(h);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString());b instanceof Date&&(b=b.toISOString());return c&&d?a>b?-1:a===b?0:1:c?-1:d?1:b-a}),this.ba.comparator=c),this.ba.sort(),null!=a&&null!=a.success&&a.success.call(d.success)):null!=a&&null!=a.error&&a.error.call(d.error,"Axis value not supported")};b.a.b("CollectionDataGridDataSource.prototype.sort",{sort:b.W.prototype.sort});
b.W.prototype.move=function(b,a){var d,c;d=this.ba.get(b);null===a?(this.ba.remove(d),this.ba.add(d)):(b===a?(c=this.ba.indexOf(this.ba.get(a)),this.ba.remove(d)):(this.ba.remove(d),c=this.ba.indexOf(this.ba.get(a))),this.ba.add(d,{at:c}))};b.a.b("CollectionDataGridDataSource.prototype.move",{move:b.W.prototype.move});b.W.prototype.oo=function(b,a){var d={source:this};d.operation=b;d.keys={row:a,column:null};return d};b.W.prototype.rK=function(e){this.handleEvent("change",this.oo("insert",b.uh.fj(e)))};
b.W.prototype.tK=function(e){this.handleEvent("change",this.oo("delete",b.uh.fj(e)))};b.W.prototype.sK=function(e){this.handleEvent("change",this.oo("update",b.uh.fj(e)))};b.W.prototype.UJ=function(){this.handleEvent("change",this.oo("refresh",null))};b.W.prototype.setPageSize=o_b("Mb");b.a.b("CollectionDataGridDataSource.prototype.setPageSize",{setPageSize:b.W.prototype.setPageSize});b.W.prototype.size=function(){return 0===this.ba.length?-1:null!=this.Mb&&0<this.Mb&&this.ba.size()>this.Mb?this.Mb:
this.ba.size()};b.a.b("CollectionDataGridDataSource.prototype.size",{size:b.W.prototype.size});b.W.prototype.totalSize=function(){return null!=this.ba&&0>this.Ue?this.ba.length:this.Ue};b.a.b("CollectionDataGridDataSource.prototype.totalSize",{totalSize:b.W.prototype.totalSize});b.W.prototype.hasMore=function(){return null!=this.ba?this.ba.hasMore:!1};b.a.b("CollectionDataGridDataSource.prototype.hasMore",{hasMore:b.W.prototype.hasMore});b.W.prototype.fetch=function(b){this.S=null!=b?null!=b.startIndex?
b.startIndex:0:0;this.handleEvent("change",{operation:"sync",pageSize:this.Mb})};b.W.prototype.getCollection=o_c("ba");b.a.b("CollectionDataGridDataSource.prototype.getCollection",{getCollection:b.W.prototype.getCollection});b.W.prototype.fh=o_c("columns");b.a.b("CollectionDataGridDataSource.prototype.getColumns",{fh:b.W.prototype.fh});b.W.prototype.Yl=o_c("qg");b.a.b("CollectionDataGridDataSource.prototype.getRowHeader",{Yl:b.W.prototype.Yl});b.W.prototype.jD=o_c("S");b.a.b("CollectionDataGridDataSource.prototype.getStartIndex",
{jD:b.W.prototype.jD});b.W.prototype.dD=o_c("Mb");b.a.b("CollectionDataGridDataSource.prototype.getPageSize",{dD:b.W.prototype.dD});b.W.prototype.pD=o_c("Ue");b.a.b("CollectionDataGridDataSource.prototype.getTotalSize",{pD:b.W.prototype.pD});b.W.prototype.$C=o_c("CI");b.a.b("CollectionDataGridDataSource.prototype.getFetchCalls",{$C:b.W.prototype.$C});b.W.prototype.getData=o_c("data");b.a.b("CollectionDataGridDataSource.prototype.getData",{getData:b.W.prototype.getData})});
//# sourceMappingURL=oj-modular.map