define("ojs/ojcore jquery ojs/internal-deps/datagrid/DvtDataGrid ojs/ojcomponentcore ojs/ojdatacollection-common ojs/ojinputnumber ojs/ojmenu ojs/ojdialog".split(" "),function(b,e,a){b.Ha=function(a,c){null!=c&&(this.Ii=c.rowHeader);b.Ha.j.constructor.call(this,a)};o_("ArrayDataGridDataSource",b.Ha,b);b.a.ga(b.Ha,b.Lb,"oj.ArrayDataGridDataSource");b.Ha.prototype.Init=function(){this.columns=this.oJ(this.data);this.qL();b.Ha.j.Init.call(this)};b.a.c("ArrayDataGridDataSource.prototype.Init",{Init:b.Ha.prototype.Init});
b.Ha.prototype.qL=function(){var a;this.Ad=[];for(a=0;a<this.data.length;a+=1)this.Ad[a]=a.toString()};b.Ha.prototype.oJ=function(a){var b,f;if("number"!==typeof a.length||0===a.length)return[];f=[];for(b in a[0])a[0].hasOwnProperty(b)&&(void 0!=this.Ii&&b==this.Ii||f.push(b));return f};b.Ha.prototype.W=function(a){return"row"===a?this.data.length:"column"===a?this.columns.length:0};b.a.c("ArrayDataGridDataSource.prototype.getCount",{W:b.Ha.prototype.W});b.Ha.prototype.mD=function(a,b){if("row"===
a)return void 0!=this.Ii?this.data[b][this.Ii]:0<this.data.length&&this.data[0]instanceof Array?void 0===this.Ad[b]?b.toString():this.Ad[b]:null;if("column"===a)return this.columns[b]};b.Ha.prototype.AP=function(a,b){return"row"===a&&void 0!=this.Ii?{key:b.toString()}:{key:this.mD(a,b)}};b.Ha.prototype.wd=function(a,c,f){var e,g,k;e=a.axis;g=a.start;k=a.count;b.f.assert("row"===e||"column"===e);b.f.assert(g<this.W(e));b.f.assert(0<k);g=Math.max(0,g);k="column"===e?Math.min(this.columns.length,g+k):
void 0!==this.Ii||0<this.data.length&&this.data[0]instanceof Array?Math.min(this.data.length,g+k):g;e=new b.Od(g,k,e,this);null!=c&&null!=c.success&&(null==f&&(f={}),c.success.call(f.success,e,a))};b.a.c("ArrayDataGridDataSource.prototype.fetchHeaders",{wd:b.Ha.prototype.wd});b.Ha.prototype.tP=function(a,b){return this.data[a][this.columns[b]]};b.Ha.prototype.uP=function(a,b){return{keys:{row:this.Ad[a],column:this.columns[b]}}};b.Ha.prototype.ud=function(a,c,f){var e,g,k,l,m,n;for(e=0;e<a.length;e+=
1)g=a[e],b.f.assert("row"===g.axis||"column"===g.axis),b.f.assert(g.start<this.W(g.axis)),b.f.assert(0<g.count),"row"===g.axis?(k=g.start,l=Math.min(this.data.length,k+g.count)):"column"===g.axis&&(m=g.start,n=Math.min(this.columns.length,m+g.count));void 0===l||void 0===n?null!=c&&null!=c.error&&(null==f&&(f={}),c.error.call(f.error)):(e=new b.Cd(k,l,m,n,this),null!=c&&null!=c.success&&(null==f&&(f={}),c.success.call(f.success,e,a)))};b.a.c("ArrayDataGridDataSource.prototype.fetchCells",{ud:b.Ha.prototype.ud});
b.Ha.prototype.keys=function(a){return{row:this.Ad[a.row],column:this.columns[a.column]}};b.a.c("ArrayDataGridDataSource.prototype.keys",{keys:b.Ha.prototype.keys});b.Ha.prototype.yd=function(a){var b=a.column;return{row:this.Ad.indexOf(a.row),column:this.columns.indexOf(b)}};b.a.c("ArrayDataGridDataSource.prototype.indexes",{yd:b.Ha.prototype.yd});b.Ha.prototype.sort=function(a,b,f){var e=[],g=[],k=[],l=[],m=[],n,q;n=a.axis;q=a.key;a=a.direction;null!=b&&null==f&&(f={});if("column"===n){q=this.columns.indexOf(q);
for(n=0;n<this.data.length;n+=1)e[n]=this.data[n][this.columns[q]],g[n]=n;g.sort(this.mA(e,a));for(n=0;n<this.data.length;n+=1)k[n]=this.data[g[n]],m[n]=this.Ad[g[n]];this.data=k;this.Ad=m;null!=b&&null!=b.success&&b.success.call(f.success)}else if("row"===n){q=this.Ad.indexOf(q);for(n=0;n<this.columns.length;n+=1)e[n]=this.data[q][this.columns[n]],g[n]=n;g.sort(this.mA(e,a));for(n=0;n<this.columns.length;n+=1)l[n]=this.columns[g[n]];this.columns=l;null!==b&&null!=b.success&&b.success.call(f.success)}else null!==
b&&null!=b.error&&b.error.call(f.error,"Invalid axis value")};b.a.c("ArrayDataGridDataSource.prototype.sort",{sort:b.Ha.prototype.sort});b.Ha.prototype.getCapability=function(a){return"sort"===a?"column":"move"===a?"row":null};b.a.c("ArrayDataGridDataSource.prototype.getCapability",{getCapability:b.Ha.prototype.getCapability});b.Ha.prototype.mA=function(a,b){if("ascending"===b)return function(b,c){var e,k;b=a[b];c=a[c];e=isNaN(b);k=isNaN(c);b instanceof Date&&(b=b.toISOString(),e=!0);c instanceof
Date&&(c=c.toISOString(),k=!0);return e&&k?b<c?-1:b===c?0:1:e?1:k?-1:b-c};if("descending"===b)return function(b,c){var e,k;b=a[b];c=a[c];e=isNaN(b);k=isNaN(c);b instanceof Date&&(b=b.toISOString(),e=!0);c instanceof Date&&(c=c.toISOString(),k=!0);return e&&k?b>c?-1:b===c?0:1:e?-1:k?1:c-b}};b.Ha.prototype.move=function(a,b){var f,e;f=this.Ad.indexOf(a);this.Ad.splice(f,1);f=this.data.splice(f,1)[0];e={source:this,operation:"delete",keys:{row:a,column:null}};this.handleEvent("change",e);null===b?(this.Ad.push(a),
this.data.push(f)):(e=this.Ad.indexOf(b),this.Ad.splice(e,0,a),this.data.splice(e,0,f));e={source:this,operation:"insert",keys:{row:a,column:null}};this.handleEvent("change",e)};b.a.c("ArrayDataGridDataSource.prototype.move",{move:b.Ha.prototype.move});b.Ha.prototype.pD=o_c("Ii");b.a.c("ArrayDataGridDataSource.prototype.getRowHeaderKey",{pD:b.Ha.prototype.pD});b.Ha.prototype.lh=o_c("columns");b.a.c("ArrayDataGridDataSource.prototype.getColumns",{lh:b.Ha.prototype.lh});b.Ha.prototype.qD=o_c("Ad");
b.a.c("ArrayDataGridDataSource.prototype.getRowKeys",{qD:b.Ha.prototype.qD});b.Ha.prototype.getData=o_c("data");b.a.c("ArrayDataGridDataSource.prototype.getData",{getData:b.Ha.prototype.getData});b.he=function(a,c){this.FQ=a;this.VQ=c;this.Ga={};this.Ga.datagrid="oj-datagrid";this.Ga.cell="oj-datagrid-cell";this.Ga.banded="oj-datagrid-banded";this.Ga.row="oj-datagrid-row";this.Ga.databody="oj-datagrid-databody";this.Ga.topcorner="oj-datagrid-top-corner";this.Ga.bottomcorner="oj-datagrid-bottom-corner";
this.Ga.rowheaderspacer="oj-datagrid-row-header-spacer";this.Ga.colheaderspacer="oj-datagrid-column-header-spacer";this.Ga.status="oj-datagrid-status";this.Ga.emptytext="oj-datagrid-empty-text";this.Ga.header="oj-datagrid-header";this.Ga.headercell="oj-datagrid-header-cell";this.Ga.headercellcontent="oj-datagrid-header-cell-content";this.Ga.rowheader="oj-datagrid-row-header";this.Ga.colheader="oj-datagrid-column-header";this.Ga.colheadercell="oj-datagrid-column-header-cell";this.Ga.rowheadercell=
"oj-datagrid-row-header-cell";this.Ga["scroller-mobile"]="oj-datagrid-scroller-touch";this.Ga.scroller="oj-datagrid-scroller";this.Ga.scrollers="oj-datagrid-scrollers";this.Ga.hover="oj-hover";this.Ga.active="oj-active";this.Ga.selected="oj-selected";this.Ga.disabled="oj-disabled";this.Ga.enabled="oj-enabled";this.Ga["default"]="oj-default";this.Ga.sortcontainer="oj-datagrid-sort-icon-container";this.Ga.sortascending="oj-datagrid-sort-ascending-icon";this.Ga.sortdescending="oj-datagrid-sort-descending-icon";
this.Ga.icon="oj-component-icon";this.Ga.clickableicon="oj-clickable-icon-nocontext";this.Ga.info="oj-helper-hidden-accessible";this.Ga.rowexpander="oj-rowexpander";this.Ga.cut="oj-datagrid-cut";this.Ga.move="oj-datagrid-move";this.Ga.droptarget="oj-datagrid-drop-target";this.Yd={};this.Yd.sortCol="oj-datagrid-sortCol";this.Yd.sortColAsc="oj-datagrid-sortColAsc";this.Yd.sortColDsc="oj-datagrid-sortColDsc";this.Yd.sortRow="oj-datagrid-sortRow";this.Yd.sortRowAsc="oj-datagrid-sortRowAsc";this.Yd.sortRowDsc=
"oj-datagrid-sortRowDsc";this.Yd.resize="oj-datagrid-resize";this.Yd.resizeWidth="oj-datagrid-resizeWidth";this.Yd.resizeHeight="oj-datagrid-resizeHeight";this.Yd.cut="oj-datagrid-cut";this.Yd.paste="oj-datagrid-paste";this.attributes={};this.attributes.key="data-oj-key";this.attributes.resizable="data-oj-resizable";this.attributes.sortable="data-oj-sortable";this.attributes.sortDir="data-oj-sortdir";this.attributes.expander="data-oj-expander";this.attributes.expanderIndex="data-oj-expander-index";
this.attributes.container=b.Components.wn};o_("DataGridResources",b.he,b);b.he.prototype.UD=function(){return"rtl"===this.FQ?!0:!1};b.a.c("DataGridResources.prototype.isRTLMode",{UD:b.he.prototype.UD});b.he.prototype.DD=function(a,b){return this.VQ(a,b)};b.a.c("DataGridResources.prototype.getTranslatedText",{DD:b.he.prototype.DD});b.he.prototype.cu=function(a){return null!=a?this.Ga[a]:null};b.a.c("DataGridResources.prototype.getMappedStyle",{cu:b.he.prototype.cu});b.he.prototype.Cp=function(a){return null!=
a?this.Yd[a]:null};b.a.c("DataGridResources.prototype.getMappedCommand",{Cp:b.he.prototype.Cp});b.he.prototype.bu=function(a){return null!=a?this.attributes[a]:null};b.a.c("DataGridResources.prototype.getMappedAttribute",{bu:b.he.prototype.bu});b.ta("oj.ojDataGrid",e.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{bandingInterval:{row:0,column:0},data:null,emptyText:null,gridlines:{horizontal:"visible",vertical:"visible"},scrollPosition:null,selectionMode:null,dnd:{ok:"disable"},
header:{row:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null},column:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null}},cell:{className:null,renderer:null,style:null},select:null,resize:null,sort:null},_create:function(){e(this.root).addClass("oj-component");this._super();this.root=this.element[0];this.Md=this.root.getAttribute("id");this.grid=new a;this.Gu={data:"all",header:["className","renderer",
"style","template"]}},_init:function(){var a=this;e(this.root).empty();this._super();this.Hi=new b.he(this.xc(),this.pz.bind(a));this.CB();this.YG();null!=this.jc&&this.grid.SetDataSource(this.jc);this.grid.SetOptions(this.options);this.grid.SetResources(this.Hi);this.grid.SetCreateContextCallback(this.XL.bind(a));this.grid.addListener("resize",function(b){a._trigger("resize",b.event,b.ui)});this.grid.addListener("select",function(b){a._trigger("select",b.event,b.ui)});this.grid.addListener("sort",
function(b){a._trigger("sort",b.event,b.ui)});this.grid.addListener("keydown",function(b){a._trigger("keydown",b.event,b.ui)});this.grid.addListener("active",function(b){a._trigger("active",b.event,b.ui)});this.grid.render(this.root)},refresh:function(){this._super();e(this.root).empty();this.CB();null!=this.jc&&this.grid.SetDataSource(this.jc);this.grid.SetOptions(this.options);this.grid.SetResources(this.Hi);this.grid.refresh(this.root)},_destroy:function(){this.grid.destroy();e(this.root).empty()},
_setOptions:function(a){var b;if(this.jc)this.PN(a);else for(b in a)this._setOption(b,a[b])},PN:function(a){var b,f,e,g,k;e=!1;for(f in a)if(f in this.Gu)if("header"==f)for(g in a.header){if("column"==g||"row"==g||"cell"==g)for(k in a.header[g]){for(b=0;b<this.Gu.header.length;b++)if(k==this.Gu.header[b]){e=!0;break}if(e)break}if(e)break}else e=!0;for(f in a)this._setOption(f,a[f]);e?this.refresh():this.grid.UpdateOptions(a)},_setOption:function(a,b){this._super(a,b)},yj:function(a,b){return"disable"!==
this.options.header[a].resizable[b]},YG:function(){var a,b,f=null,h=null,g=null;a=this;if(null==this.options.contextMenu){if(null!=this.jc){b=e("\x3cul\x3e");b.css("display","none").attr("id",this.Md+"contextmenu");e(this.root).append(b);if(this.yj("column","width")||this.yj("column","height")||this.yj("row","width")||this.yj("row","height"))f=this.Gg("resize");switch(this.jc.getCapability("sort")){case "none":break;case "column":h=this.Gg("sortCol");break;case "row":h=this.Gg("sortRow");break;default:h=
this.Gg("sortCol"),h=h.add(this.Gg("sortRow"))}if("enable"===this.options.dnd.reorder)switch(this.jc.getCapability("move")){case "none":break;default:g=e(this.Fd("cut")).add(e(this.Fd("paste")))}b.append(f).append(h).append(g);b.ojMenu();this._setOption("contextMenu","#"+b.attr("id"));b.on("ojbeforeshow",this.rj.bind(this));b.on("ojselect",this.sj.bind(this))}}else b=e(this.options.contextMenu),f=b.find("[data-oj-command]"),f.each(function(){var b;0===e(this).children("a").length&&(b=e(this).attr("data-oj-command").split("-"),
e(this).replaceWith(a.Gg(b[b.length-1])))}),b.ojMenu("refresh"),b.on("ojbeforeshow",this.rj.bind(this)),b.on("ojselect",this.sj.bind(this))},Gg:function(a){if("resize"===a)return e(this.Fd("resize")).append(e("\x3cul\x3e\x3c/ul\x3e").append(e(this.Fd("resizeWidth"))).append(e(this.Fd("resizeHeight"))));if("sortCol"===a)return e(this.Fd("sortCol")).append(e("\x3cul\x3e\x3c/ul\x3e").append(e(this.Fd("sortColAsc"))).append(e(this.Fd("sortColDsc"))));if("sortRow"===a)return e(this.Fd("sortRow")).append(e("\x3cul\x3e\x3c/ul\x3e").append(e(this.Fd("sortRowAsc"))).append(e(this.Fd("sortRowDsc"))));
if(-1!=Object.keys(this.Hi.Yd).indexOf(a))return e(this.Fd(a))},Fd:function(a){return"\x3cli data-oj-command\x3d"+this.Zf(a)+"\x3e"+this.Pq(a)+"\x3c/li\x3e"},Pq:function(a){a="label"+a.charAt(0).toUpperCase()+a.slice(1);return'\x3ca href\x3d"#"\x3e'+this.pz(a)+"\x3c/a\x3e"},Nr:function(){return e(this.options.contextMenu).get(0)},pz:function(a,b){return this.l(a,b)},RK:function(){var a=e("#"+this.Md+"spinner").ojInputNumber("option","value");e("#"+this.Md+"dialog").ojDialog("destroy");e("#"+this.Md+
"spinner").ojInputNumber("destroy");this.grid.handleContextMenuReturn(this.We,this.Df,a);this.We.target.focus()},CH:function(a,b){var f,h,g,k,l;f=e("#"+this.Md+"dialog");g=e("#"+this.Md+"spinner");if(0===f.length||0===g.length)f=e("\x3cdiv\x3e"),f.attr("id",this.Md+"dialog"),f.attr("title",a),h=e('\x3cdiv class\x3d"oj-dialog-body"\x3e\x3c/div\x3e'),k=e('\x3cdiv class\x3d"oj-dialog-footer"\x3e\x3c/div\x3e'),f.append(h).append(k),g=e('\x3cinput id\x3d"'+this.Md+'spinner"/\x3e'),l=e("\x3cbutton\x3e"),
h.append(g),k.append(l),e(this.root).append(f),l.ojButton({ja:"ojButton",label:"OK"}),l.on("click",this.RK.bind(this));g.ojInputNumber({ja:"ojInputNumber",max:1E3,min:20,step:1,value:b});f.ojDialog({initialVisibility:"show",position:{my:"center center",at:"center center",collision:"none",of:e(this.root)}})},sj:function(a,b){var f;this.Df=b.item.attr("data-oj-command");if(this.Df===this.Zf("sortColAsc")||this.Df===this.Zf("sortColDsc")||this.Df===this.Zf("cut")||this.Df===this.Zf("paste"))this.grid.handleContextMenuReturn(this.We,
this.Df,null);else if(this.Df===this.Zf("resizeWidth")||this.Df===this.Zf("resizeHeight"))f=this.Gr(e(this.We.target),"oj-datagrid-headercell"),f=null!=f?this.Df===this.Zf("resizeWidth")?f.outerWidth():f.outerHeight():this.Df===this.Zf("resizeWidth")?e(this.We.target).outerWidth():e(this.We.target).outerHeight(),this.CH(b.item.text(),f)},rj:function(a){var b;b=e(this.Nr());this.We=a.originalEvent.originalEvent;"keydown"===this.We.type?b.ojMenu("option","menuPosition",{my:"left top",at:"left bottom",
of:this.We.target}):b.ojMenu("option","menuPosition",{my:"left top",at:"left bottom"});a=this.Gr(e(this.We.target).eq(0),this.mj("cell"));null!=a?a=this.kJ(a):(a=this.Gr(e(this.We.target).eq(0),this.mj("headercell")),a=this.yJ(a));this.TL(a)},ZG:function(a){var b;b=e(this.Nr());b.find("[data-oj-command\x3d"+a+"]").hasClass("oj-disabled")||b.find("[data-oj-command\x3d"+a+"]").addClass("oj-disabled")},ZM:function(a){e(this.Nr()).find("[data-oj-command\x3d"+a+"]").removeClass("oj-disabled")},TL:function(a){var b,
f;for(b in a)a.hasOwnProperty(b)&&(f=this.Hi.Cp(b),"disable"===a[b]?this.ZG(f):this.ZM(f))},Gr:function(a,b){var f;if(a.hasClass(b))return a;f=a.parents("."+b);return 0!=f.length?f.eq(0):null},aJ:function(a){var b;b=a.parent();a=b.children().index(a);return{rowIndex:b.parent().children().index(b)-1,columnIndex:a}},bJ:function(a){var b;b=this.VJ().children().eq(0).children().eq(a.rowIndex+1);a=this.nJ().children().eq(0).children().eq(a.columnIndex);return{rowHeader:b,columnHeader:a}},CR:function(){return e(this.root)},
nJ:function(){return e("#"+this.Md+"\\:columnHeader")},VJ:function(){return e("#"+this.Md+"\\:rowHeader")},AR:function(){return e("#"+this.Md+"\\:databody")},qJ:function(){return e("#"+this.Md+"\\:databody ."+this.mj("row"))},kJ:function(a){var b,f;a=this.aJ(a);b=this.bJ(a);a={CQ:"disable",BQ:"disable",PQ:"disable",OQ:"disable"};f=b.rowHeader;b=b.columnHeader;0!==b.length&&("true"===b.attr(this.Mg("resizable"))&&(a.resizeWidth="enable"),"true"===b.attr(this.Mg("sortable"))&&(a.sortCol="enable"));
0!==f.length&&("true"===f.attr(this.Mg("resizable"))&&(a.resizeHeight="enable"),"true"===f.attr(this.Mg("sortable"))&&(a.sortRow="enable"));return a},yJ:function(a){var b;b={CQ:"disable",BQ:"disable",PQ:"disable",OQ:"disable"};null!==a&&(a.hasClass(this.mj("colheadercell"))?("true"===a.attr(this.Mg("resizable"))&&(b.resizeWidth="enable"),b.resizeHeight=this.yj("column","height")?"enable":"disable","true"===a.attr(this.Mg("sortable"))&&(b.sortCol="enable")):("true"===a.attr(this.Mg("resizable"))&&
(b.resizeHeight="enable"),b.resizeWidth=this.yj("row","width")?"enable":"disable","true"===a.attr(this.Mg("sortable"))&&(b.sortRow="enable")));return b},CB:function(){this.jc=null!=this.options.data?this.options.data:null},XL:function(a){a.component=this},wB:function(a){this.grid.SetAccessibleContext(a)},selection:function(a){if(void 0===a)return this.grid.GetSelection();this.grid.SetSelection(a)},getNodeBySubId:function(a){var b,f;if(null==a)return this.element?this.element[0]:null;b=a.subId;switch(b){case "oj-datagrid-cell":f=
this.mj("cell");break;case "oj-datagrid-header":f=this.mj("headercell");break;case "oj-datagrid-sort-ascending":f="oj-datagrid-sort-ascending-icon";break;case "oj-datagrid-sort-descending":f="oj-datagrid-sort-descending-icon";break;default:return null}if("oj-datagrid-cell"===b)return f=a.rowIndex,a=a.columnIndex,this.qJ().eq(f).children().eq(a);b=a.axis;a=a.index;return"column"===b?e("#"+this.Md+"\\:columnHeader ."+f).eq(a):"row"===b?e("#"+this.Md+"\\:rowHeader ."+f).eq(a):null},mj:function(a){return this.Hi.cu(a)},
Mg:function(a){return this.Hi.bu(a)},Zf:function(a){return this.Hi.Cp(a)}});b.ie=function(a,c,f,e,g,k){b.f.Gb(a,null);b.f.Gb(c,null);b.f.Gb(f,null);b.f.Gb(e,null);b.f.cm(k);this.bf=a;this.Di=c;this.Fe=f;this.lg=e;this.Qa=g;this.rc=k};o_("FlattenedTreeCellSet",b.ie,b);b.ie.prototype.getData=function(a){var c;c=this.cz(a);if(null==c)return null;a=c[0];c=c[1];b.f.assert(a<this.Qa.Ba()+this.Qa.W()&&c<this.rc.length);c=this.rc[c];a=this.Qa.getData(a);return null!=a?a.get?a.get(c):a[c]:null};b.a.c("FlattenedTreeCellSet.prototype.getData",
{getData:b.ie.prototype.getData});b.ie.prototype.getMetadata=function(a){var c;c=this.cz(a);if(null==c)return null;a=c[0];c=c[1];b.f.assert(a<this.Qa.Ba()+this.Qa.W()&&c<this.rc.length);c=this.rc[c];a=this.Qa.getMetadata(a);a.keys={row:a.key,column:c};return a};b.a.c("FlattenedTreeCellSet.prototype.getMetadata",{getMetadata:b.ie.prototype.getMetadata});b.ie.prototype.cz=function(a){var c;b.f.sd(a);if(null==this.Qa||0==this.Qa.length)return null;c=a.row-this.bf+this.Qa.Ba();a=a.column;b.f.Gb(c,null);
b.f.Gb(a,null);b.f.assert(0<=c&&0<=a);return[c,a]};b.ie.prototype.Ba=function(a){return"row"===a?this.bf:"column"===a?this.Fe:0};b.a.c("FlattenedTreeCellSet.prototype.getStart",{Ba:b.ie.prototype.Ba});b.ie.prototype.W=function(a){return"row"===a?Math.min(this.Di-this.bf,this.Qa.W()):"column"===a?this.lg-this.Fe:0};b.a.c("FlattenedTreeCellSet.prototype.getCount",{W:b.ie.prototype.W});b.Jf=function(a,c,f,e,g){b.f.Gb(a,null);b.f.Gb(c,null);b.f.cm(f);this.sc=a;this.af=c;this.Jp=f;this.Qa=e;this.Ee=g};
o_("FlattenedTreeHeaderSet",b.Jf,b);b.Jf.prototype.getData=function(a){b.f.assert(a<=this.af&&a>=this.sc);return null!=this.Ee&&null!=this.Qa?(a=this.Qa.getData(a),null!=a?a.get(this.Ee):null):this.Jp[a]};b.a.c("FlattenedTreeHeaderSet.prototype.getData",{getData:b.Jf.prototype.getData});b.Jf.prototype.getMetadata=function(a){return null!=this.Ee&&null!=this.Qa?this.Qa.getMetadata(a):{key:this.getData(a)}};b.a.c("FlattenedTreeHeaderSet.prototype.getMetadata",{getMetadata:b.Jf.prototype.getMetadata});
b.Jf.prototype.W=function(){return null!=this.Ee&&null!=this.Qa?Math.min(this.Qa.W(),this.af-this.sc):Math.max(0,this.af-this.sc)};b.a.c("FlattenedTreeHeaderSet.prototype.getCount",{W:b.Jf.prototype.W});b.Cd=function(a,c,f,e,g){b.f.Gb(a,null);b.f.Gb(c,null);b.f.Gb(f,null);b.f.Gb(e,null);this.bf=a;this.Di=c;this.Fe=f;this.lg=e;this.$e=g};o_("ArrayCellSet",b.Cd,b);b.Cd.prototype.getData=function(a){return this.$e.tP(a.row,a.column)};b.a.c("ArrayCellSet.prototype.getData",{getData:b.Cd.prototype.getData});
b.Cd.prototype.getMetadata=function(a){return this.$e.uP(a.row,a.column)};b.a.c("ArrayCellSet.prototype.getMetadata",{getMetadata:b.Cd.prototype.getMetadata});b.Cd.prototype.Ba=function(a){return"row"==a?this.bf:"column"==a?this.Fe:-1};b.a.c("ArrayCellSet.prototype.getStart",{Ba:b.Cd.prototype.Ba});b.Cd.prototype.W=function(a){return"row"===a?Math.max(0,this.Di-this.bf):"column"===a?Math.max(0,this.lg-this.Fe):0};b.a.c("ArrayCellSet.prototype.getCount",{W:b.Cd.prototype.W});b.Cd.prototype.lm=o_c("bf");
b.a.c("ArrayCellSet.prototype.getStartRow",{lm:b.Cd.prototype.lm});b.Cd.prototype.km=o_c("Fe");b.a.c("ArrayCellSet.prototype.getStartColumn",{km:b.Cd.prototype.km});b.ya=function(a,c){b.ya.j.constructor.call(this,a,c)};o_("FlattenedTreeDataGridDataSource",b.ya,b);b.a.ga(b.ya,b.Y,"oj.FlattenedTreeDataGridDataSource");b.ya.prototype.Init=function(){b.ya.j.Init.call(this);this.rc=b.ya.j.Dp.call(this,"columns");this.Ee=b.ya.j.Dp.call(this,"rowHeader")};b.a.c("FlattenedTreeDataGridDataSource.prototype.Init",
{Init:b.ya.prototype.Init});b.ya.prototype.ze=function(a){return"row"===a?"estimate":"actual"};b.a.c("FlattenedTreeDataGridDataSource.prototype.getCountPrecision",{ze:b.ya.prototype.ze});b.ya.prototype.W=function(a){return"row"===a?-1:"column"===a?this.rc.length:0};b.a.c("FlattenedTreeDataGridDataSource.prototype.getCount",{W:b.ya.prototype.W});b.ya.prototype.wd=function(a,c,f){var e,g;e=a.axis;if("column"===e)g=new b.Jf(a.start,a.start+a.count,this.rc);else if("row"===e){if(null!=this.Ee){this.Cf=
{range:a,callbacks:c,callbackObjects:f};return}g=new b.Od(a.start,a.start,e,null)}null!=g&&(null!=c&&null!=c.success)&&(null==f&&(f={}),c.success.call(f.success,g,a))};b.a.c("FlattenedTreeDataGridDataSource.prototype.fetchHeaders",{wd:b.ya.prototype.wd});b.ya.prototype.ud=function(a,c,f){var e,g,k,l;for(e=0;e<a.length;e++)if(g=a[e],"row"==g.axis){k=g.start;l=g.count;break}b.ya.j.YC.call(this,{start:k,count:l},{success:function(b){this.ns(b,a,c,f,0)}.bind(this),error:function(a){this.yK(a,{start:k,
count:l},c,f)}.bind(this)})};b.a.c("FlattenedTreeDataGridDataSource.prototype.fetchCells",{ud:b.ya.prototype.ud});b.ya.prototype.keys=function(a){var c;c=a.row;a=a.column;return c>b.ya.j.zP.call(this).end||a>this.rc.length?null:{row:b.ya.j.getKey.call(this,c),column:this.rc[a]}};b.a.c("FlattenedTreeDataGridDataSource.prototype.keys",{keys:b.ya.prototype.keys});b.ya.prototype.yd=function(a){var c,f,e;c=a.row;a=a.column;c=b.ya.j.ck.call(this,c);for(e=0;e<this.rc.length;e++)if(this.rc[e]===a){f=e;break}return 0<=
c&&0<=f?{row:c,column:f}:null};b.a.c("FlattenedTreeDataGridDataSource.prototype.indexes",{yd:b.ya.prototype.yd});b.ya.prototype.sort=function(a,c,f){return b.ya.j.om.call(this).sort(a,{success:function(){this.TK(c,f)}.bind(this),error:c.error})};b.a.c("FlattenedTreeDataGridDataSource.prototype.sort",{sort:b.ya.prototype.sort});b.ya.prototype.TK=function(a,b){this.refresh();a.success&&(null==b&&(b={}),a.success.call(b.success))};b.ya.prototype.getCapability=function(a){return b.ya.j.om.call(this).getCapability(a)};
b.a.c("FlattenedTreeDataGridDataSource.prototype.getCapability",{getCapability:b.ya.prototype.getCapability});b.ya.prototype.rm=function(a,c){b.ya.j.rm.call(this,a,c)};b.ya.prototype.ns=function(a,c,f,e){var g,k,l,m,n,q;for(g=0;g<c.length;g++)k=c[g],"row"==k.axis?(l=k.start,m=k.count):"column"==k.axis&&(n=k.start,q=k.count);this.Cf&&(g=this.Cf.range,g.start==l&&g.count==m&&this.SK(a,g,this.Cf.callbacks,this.Cf.callbackObjects),this.Cf=null);a=new b.ie(l,l+m,n,n+q,a,this.rc);f.success&&(null==e&&(e=
{}),f.success.call(e.success,a,c))};b.ya.prototype.yK=function(a,b,f,e){var g;this.Cf&&(g=this.Cf.range,g.start==b.start&&g.count==b.count&&(b=this.Cf.callbacks,g=this.Cf.callbackObjects,b.error&&(null==g&&(g={}),b.error.call(g.error,a))),this.Cf=null);f.error&&(null==e&&(e={}),f.success.call(e.error,a))};b.ya.prototype.SK=function(a,c,f,e){a=new b.Jf(c.start,c.start+c.count,this.rc,a,this.Ee);f.success&&(null==e&&(e={}),f.success.call(e.success,a,c))};b.ya.prototype.pu=function(a,c,f){a=new b.ie(a,
a+f.W(),0,this.rc.length,f,this.rc);f={source:this,operation:"insert"};f.result=a;f.keys={row:c};b.ya.j.handleEvent.call(this,"change",f)};b.ya.prototype.Up=function(a){var c,f;c=[];for(f=0;f<a.length;f++)c.push({row:a[f].key});a={source:this,operation:"delete"};a.keys=c;b.ya.j.handleEvent.call(this,"change",a)};b.ya.prototype.ju=function(a,c){c.success.call(null,new b.jd(null,a.start))};b.za=function(a){if(!(a instanceof b.X))throw new b.C("Not a datagridatasource","Not a datagridatasource",b.C.Ja.ERROR);
this.Na=a;this.S=0;this.Init()};o_("PagingDataGridDataSource",b.za,b);b.a.ga(b.za,b.rb,"oj.PagingDataGridDataSource");b.za.prototype.Init=function(){b.za.j.Init.call(this)};b.a.c("PagingDataGridDataSource.prototype.Init",{Init:b.za.prototype.Init});b.za.prototype.fetch=function(a){this.S=a.startIndex;this.Na.setPageSize(this.mc);this.Na.fetch(a)};b.a.c("PagingDataGridDataSource.prototype.fetch",{fetch:b.za.prototype.fetch});b.za.prototype.hasMore=function(){return this.Na.hasMore()};b.a.c("PagingDataGridDataSource.prototype.hasMore",
{hasMore:b.za.prototype.hasMore});b.za.prototype.next=function(){this.Na.totalSize()>this.S&&(this.mc+=this.Nb,this.Na.setPageSize(this.mc),this.fetch({startIndex:this.S}))};b.a.c("PagingDataGridDataSource.prototype.next",{next:b.za.prototype.next});b.za.prototype.previous=function(){if(0!=this.S||-1!=this.S)this.S-=this.Nb,this.S=0>this.S?0:this.S,this.mc+=this.Nb,this.Na.setPageSize(this.mc),this.fetch({startIndex:this.S})};b.a.c("PagingDataGridDataSource.prototype.previous",{previous:b.za.prototype.previous});
b.za.prototype.setPageSize=function(a){this.Nb=a;this.mc=this.S+a;this.Na.setPageSize(this.mc)};b.za.prototype.startIndex=o_c("S");b.a.c("PagingDataGridDataSource.prototype.startIndex",{startIndex:b.za.prototype.startIndex});b.za.prototype.W=function(a){return this.Na.W(a)};b.a.c("PagingDataGridDataSource.prototype.getCount",{W:b.za.prototype.W});b.za.prototype.ze=function(a){return this.Na.ze(a)};b.a.c("PagingDataGridDataSource.prototype.getCountPrecision",{ze:b.za.prototype.ze});b.za.prototype.wd=
function(a,b,f){return this.Na.wd(a,b,f)};b.a.c("PagingDataGridDataSource.prototype.fetchHeaders",{wd:b.za.prototype.wd});b.za.prototype.ud=function(a,b,f){return this.Na.ud(a,b,f)};b.a.c("PagingDataGridDataSource.prototype.fetchCells",{ud:b.za.prototype.ud});b.za.prototype.keys=function(a){return this.Na.keys(a)};b.a.c("PagingDataGridDataSource.prototype.keys",{keys:b.za.prototype.keys});b.za.prototype.yd=function(a){return this.Na.yd(a)};b.a.c("PagingDataGridDataSource.prototype.indexes",{yd:b.za.prototype.yd});
b.za.prototype.on=function(a,b){return this.Na.on(a,b)};b.a.c("PagingDataGridDataSource.prototype.on",{on:b.za.prototype.on});b.za.prototype.off=function(a,b){return this.Na.off(a,b)};b.a.c("PagingDataGridDataSource.prototype.off",{off:b.za.prototype.off});b.za.prototype.getCapability=function(a){return"move"===a?"none":this.Na.getCapability(a)};b.a.c("PagingDataGridDataSource.prototype.getCapability",{getCapability:b.za.prototype.getCapability});b.za.prototype.size=function(){return this.Na.size()};
b.a.c("PagingDataGridDataSource.prototype.size",{size:b.za.prototype.size});b.za.prototype.sort=function(a,b,f){this.Na.sort(a,b,f)};b.a.c("PagingDataGridDataSource.prototype.sort",{sort:b.za.prototype.sort});b.za.prototype.totalSize=function(){return this.Na.totalSize()};b.a.c("PagingDataGridDataSource.prototype.totalSize",{totalSize:b.za.prototype.totalSize});b.za.prototype.move=function(a,b){return this.Na.move(a,b)};b.Od=function(a,c,f,e){b.f.Gb(a,null);b.f.Gb(c,null);this.sc=a;this.af=c;this.XD=
f;this.$e=e};o_("ArrayHeaderSet",b.Od,b);b.Od.prototype.getData=function(a){if(null==this.$e)return null;b.f.assert(a<=this.af&&a>=this.sc);return this.$e.mD(this.XD,a)};b.a.c("ArrayHeaderSet.prototype.getData",{getData:b.Od.prototype.getData});b.Od.prototype.getMetadata=function(a){if(null==this.$e)return null;b.f.assert(a<=this.af&&a>=this.sc);return this.$e.AP(this.XD,a)};b.a.c("ArrayHeaderSet.prototype.getMetadata",{getMetadata:b.Od.prototype.getMetadata});b.Od.prototype.W=function(){return null==
this.$e?0:Math.max(0,this.af-this.sc)};b.a.c("ArrayHeaderSet.prototype.getCount",{W:b.Od.prototype.W});b.Od.prototype.Ba=o_c("sc");b.a.c("ArrayHeaderSet.prototype.getStart",{Ba:b.Od.prototype.Ba})});
//# sourceMappingURL=oj-modular.map