define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){(function(){var a=!1;e(document).mouseup(function(){a=!1});b.ta("oj.ojResizable",e.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancel:"input,textarea,button,select,option",distance:1,delay:0,alsoResize:!1,animate:!1,animateDuration:"slow",animateEasing:"swing",aspectRatio:!1,autoHide:!1,containment:!1,ghost:!1,grid:!1,handles:"e,s,se",helper:!1,resize:null,start:null,stop:null},aM:function(){var a=this;this.element.bind("mousedown."+
this.widgetName,function(b){return a.$L(b)}).bind("click."+this.widgetName,function(b){if(!0===e.data(b.target,a.widgetName+".preventClickEvent"))return e.removeData(b.target,a.widgetName+".preventClickEvent"),b.stopImmediatePropagation(),!1});this.VS=!1},ZL:function(){this.element.unbind("."+this.widgetName);this.Vo&&this.document.unbind("mousemove."+this.widgetName,this.Vo).unbind("mouseup."+this.widgetName,this.Ns)},$L:function(b){if(!a){this.Vg&&this.Wo(b);this.Uo=b;var c=this,f=1===b.which,h=
"string"===typeof this.options.cancel&&b.target.nodeName?e(b.target).closest(this.options.cancel).length:!1;if(!f||h||!this.YL(b))return!0;this.Gm=!this.options.delay;this.Gm||(this.iS=setTimeout(function(){c.Gm=!0},this.options.delay));if(this.iA(b)&&this.Gm&&(this.Vg=!1!==this.kA(b),!this.Vg))return b.preventDefault(),!0;!0===e.data(b.target,this.widgetName+".preventClickEvent")&&e.removeData(b.target,this.widgetName+".preventClickEvent");this.Vo=function(a){return c.bM(a)};this.Ns=function(a){return c.Wo(a)};
this.document.bind("mousemove."+this.widgetName,this.Vo).bind("mouseup."+this.widgetName,this.Ns);b.preventDefault();return a=!0}},bM:function(a){if(e.ui.FS&&(!document.documentMode||9>document.documentMode)&&!a.button||!a.which)return this.Wo(a);if(this.Vg)return this.jA(a),a.preventDefault();this.iA(a)&&this.Gm&&((this.Vg=!1!==this.kA(this.Uo,a))?this.jA(a):this.Wo(a));return!this.Vg},Wo:function(b){this.document.unbind("mousemove."+this.widgetName,this.Vo).unbind("mouseup."+this.widgetName,this.Ns);
this.Vg&&(this.Vg=!1,b.target===this.Uo.target&&e.data(b.target,this.widgetName+".preventClickEvent",!0),this.cM(b));return a=!1},iA:function(a){return Math.max(Math.abs(this.Uo.pageX-a.pageX),Math.abs(this.Uo.pageY-a.pageY))>=this.options.distance},hS:o_c("Gm"),Ps:function(a){return parseInt(a,10)||0},tf:function(a){return!isNaN(parseInt(a,10))},Go:function(a,b){if("hidden"===e(a).css("overflow"))return!1;var f=b&&"left"===b?"scrollLeft":"scrollTop",h=!1;if(0<a[f])return!0;a[f]=1;h=0<a[f];a[f]=0;
return h},_create:function(){var a,b,f,h,g,k=this,l=this.options;this.element.addClass("oj-resizable");e.extend(this,{Lq:!!l.aspectRatio,aspectRatio:l.aspectRatio,Bc:this.element,ni:[],Nc:l.helper||l.ghost||l.animate?l.helper||"oj-resizable-helper":null});this.element[0].nodeName.match(/canvas|textarea|input|select|button|img/i)&&(this.element.wrap(e("\x3cdiv class\x3d'ui-wrapper' style\x3d'overflow: hidden;'\x3e\x3c/div\x3e").css({position:this.element.css("position"),width:this.element.outerWidth(),
height:this.element.outerHeight(),top:this.element.css("top"),left:this.element.css("left")})),this.element=this.element.parent().data("oj-resizable",this.element.resizable("instance")),this.VC=!0,this.element.css({marginLeft:this.Bc.css("marginLeft"),marginTop:this.Bc.css("marginTop"),marginRight:this.Bc.css("marginRight"),marginBottom:this.Bc.css("marginBottom")}),this.Bc.css({marginLeft:0,marginTop:0,marginRight:0,marginBottom:0}),this.rQ=this.Bc.css("resize"),this.Bc.css("resize","none"),this.ni.push(this.Bc.css({position:"static",
zoom:1,display:"block"})),this.Bc.css({margin:this.Bc.css("margin")}),this.cp());this.handles=l.handles||(e(".oj-resizable-handle",this.element).length?{LS:".oj-resizable-n",wS:".oj-resizable-e",SS:".oj-resizable-s",Ec:".oj-resizable-w",US:".oj-resizable-se",YS:".oj-resizable-sw",MS:".oj-resizable-ne",NS:".oj-resizable-nw"}:"e,s,se");if(this.handles.constructor===String)for("all"===this.handles&&(this.handles="n,e,s,w,se,sw,ne,nw"),a=this.handles.split(","),this.handles={},b=0;b<a.length;b++)f=e.trim(a[b]),
g="oj-resizable-"+f,h=e("\x3cdiv class\x3d'oj-resizable-handle "+g+"'\x3e\x3c/div\x3e"),this.handles[f]=".oj-resizable-"+f,this.element.append(h);this.gN=function(a){var b,c,d;a=a||this.element;for(b in this.handles)this.handles[b].constructor===String&&(this.handles[b]=this.element.children(this.handles[b]).first().show()),this.VC&&this.Bc[0].nodeName.match(/textarea|input|select|button/i)&&(c=e(this.handles[b],this.element),d=/sw|ne|nw|se|n|s/.test(b)?c.outerHeight():c.outerWidth(),c=["padding",
/ne|nw|n/.test(b)?"Top":/se|sw|s/.test(b)?"Bottom":/^e$/.test(b)?"Right":"Left"].join(""),a.css(c,d),this.cp()),e(this.handles[b])};this.gN(this.element);this.Eo=e(".oj-resizable-handle",this.element);this.Eo.mouseover(function(){k.Ju||(this.className&&(h=this.className.match(/oj-resizable-(se|sw|ne|nw|n|e|s|w)/i)),k.axis=h&&h[1]?h[1]:"se")});l.autoHide&&(this.Eo.hide(),e(this.element).addClass("oj-resizable-autohide").mouseenter(function(){l.disabled||(e(this).removeClass("oj-resizable-autohide"),
k.Eo.show())}).mouseleave(function(){l.disabled||k.Ju||(e(this).addClass("oj-resizable-autohide"),k.Eo.hide())}));this.aM()},_destroy:function(){function a(b){e(b).removeClass("oj-resizable oj-resizable-disabled oj-resizable-resizing").removeData("resizable").removeData("oj-resizable").unbind(".resizable").find(".oj-resizable-handle").remove()}this.ZL();var b;this.VC&&(a(this.element),b=this.element,this.Bc.css({position:b.css("position"),width:b.outerWidth(),height:b.outerHeight(),top:b.css("top"),
left:b.css("left")}).insertAfter(b),b.remove());this.Bc.css("resize",this.rQ);a(this.Bc);return this},YL:function(a){var b,f,h=!1;for(b in this.handles)if(f=e(this.handles[b])[0],f===a.target||e.contains(f,a.target))h=!0;return!this.options.disabled&&h},kA:function(a){var b,f,h;h=this.options;b=this.element.position();var g=this.element;this.Ju=!0;/absolute/.test(g.css("position"))?g.css({position:"absolute",top:g.css("top"),left:g.css("left")}):g.is(".ui-draggable")&&g.css({position:"absolute",top:b.top,
left:b.left});this.hN();b=this.Ps(this.helper.css("left"));f=this.Ps(this.helper.css("top"));h.containment&&(b+=e(h.containment).scrollLeft()||0,f+=e(h.containment).scrollTop()||0);this.offset=this.helper.offset();this.position={left:b,top:f};this.size=this.Nc?{width:this.helper.width(),height:this.helper.height()}:{width:g.width(),height:g.height()};this.ge=this.Nc?{width:g.outerWidth(),height:g.outerHeight()}:{width:g.width(),height:g.height()};this.zd={left:b,top:f};this.zh={width:g.outerWidth()-
g.width(),height:g.outerHeight()-g.height()};this.qQ={left:a.pageX,top:a.pageY};this.aspectRatio="number"===typeof h.aspectRatio?h.aspectRatio:this.ge.width/this.ge.height||1;h=e(".oj-resizable-"+this.axis).css("cursor");e("body").css("cursor","auto"===h?this.axis+"-resize":h);g.addClass("oj-resizable-resizing");this.bp("start",a);return!0},jA:function(a){var b,f=this.helper,h={},g=this.qQ;b=a.pageX-g.left||0;var g=a.pageY-g.top||0,k=this.Uf[this.axis];this.lk={top:this.position.top,left:this.position.left};
this.mk={width:this.size.width,height:this.size.height};if(!k)return!1;b=k.apply(this,[a,b,g]);this.wO(a.shiftKey);if(this.Lq||a.shiftKey)b=this.uO(b,a);b=this.oN(b,a);this.lC(b);this.bp("resize",a);this.position.top!==this.lk.top&&(h.top=this.position.top+"px");this.position.left!==this.lk.left&&(h.left=this.position.left+"px");this.size.width!==this.mk.width&&(h.width=this.size.width+"px");this.size.height!==this.mk.height&&(h.height=this.size.height+"px");f.css(h);!this.Nc&&this.ni.length&&this.cp();
e.isEmptyObject(h)||this._trigger("resize",a,this.ui());return!1},cM:function(a){this.Ju=!1;var b,f,h,g=this.options;this.Nc&&(b=this.ni,b=(f=b.length&&/textarea/i.test(b[0].nodeName))&&this.Go(b[0],"left")?0:this.zh.height,f=f?0:this.zh.width,f={width:this.helper.width()-f,height:this.helper.height()-b},b=parseInt(this.element.css("left"),10)+(this.position.left-this.zd.left)||null,h=parseInt(this.element.css("top"),10)+(this.position.top-this.zd.top)||null,g.animate||this.element.css(e.extend(f,
{top:h,left:b})),this.helper.height(this.size.height),this.helper.width(this.size.width),this.Nc&&!g.animate&&this.cp());e("body").css("cursor","auto");this.element.removeClass("oj-resizable-resizing");this.bp("stop",a);this.Nc&&this.helper.remove();return!1},wO:function(a){var b,e,h,g;g={minWidth:0,maxWidth:Infinity,minHeight:0,maxHeight:Infinity};if(this.Lq||a)a=g.minHeight*this.aspectRatio,e=g.minWidth/this.aspectRatio,b=g.maxHeight*this.aspectRatio,h=g.maxWidth/this.aspectRatio,a>g.minWidth&&
(g.minWidth=a),e>g.minHeight&&(g.minHeight=e),b<g.maxWidth&&(g.maxWidth=b),h<g.maxHeight&&(g.maxHeight=h);this.yO=g},lC:function(a){this.offset=this.helper.offset();this.tf(a.left)&&(this.position.left=a.left);this.tf(a.top)&&(this.position.top=a.top);this.tf(a.height)&&(this.size.height=a.height);this.tf(a.width)&&(this.size.width=a.width)},uO:function(a){var b=this.position,e=this.size,h=this.axis;this.tf(a.height)?a.width=a.height*this.aspectRatio:this.tf(a.width)&&(a.height=a.width/this.aspectRatio);
"sw"===h&&(a.left=b.left+(e.width-a.width),a.top=null);"nw"===h&&(a.top=b.top+(e.height-a.height),a.left=b.left+(e.width-a.width));return a},oN:function(a){var b=this.yO,e=this.axis,h=this.tf(a.width)&&b.maxWidth&&b.maxWidth<a.width,g=this.tf(a.height)&&b.maxHeight&&b.maxHeight<a.height,k=this.tf(a.width)&&b.minWidth&&b.minWidth>a.width,l=this.tf(a.height)&&b.minHeight&&b.minHeight>a.height,m=this.zd.left+this.ge.width,n=this.position.top+this.size.height,q=/sw|nw|w/.test(e),e=/nw|ne|n/.test(e);k&&
(a.width=b.minWidth);l&&(a.height=b.minHeight);h&&(a.width=b.maxWidth);g&&(a.height=b.maxHeight);k&&q&&(a.left=m-b.minWidth);h&&q&&(a.left=m-b.maxWidth);l&&e&&(a.top=n-b.minHeight);g&&e&&(a.top=n-b.maxHeight);a.width||a.height||a.left||!a.top?a.width||(a.height||a.top||!a.left)||(a.left=null):a.top=null;return a},cp:function(){if(this.ni.length){var a,b,e,h,g,k=this.helper||this.element;for(a=0;a<this.ni.length;a++){g=this.ni[a];if(!this.Sj)for(this.Sj=[],e=[g.css("borderTopWidth"),g.css("borderRightWidth"),
g.css("borderBottomWidth"),g.css("borderLeftWidth")],h=[g.css("paddingTop"),g.css("paddingRight"),g.css("paddingBottom"),g.css("paddingLeft")],b=0;b<e.length;b++)this.Sj[b]=(parseInt(e[b],10)||0)+(parseInt(h[b],10)||0);g.css({height:k.height()-this.Sj[0]-this.Sj[2]||0,width:k.width()-this.Sj[1]-this.Sj[3]||0})}}},hN:function(){this.WC=this.element.offset();this.Nc?(this.helper=this.helper||e("\x3cdiv style\x3d'overflow:hidden;'\x3e\x3c/div\x3e"),this.helper.addClass(this.Nc).css({width:this.element.outerWidth()-
1,height:this.element.outerHeight()-1,position:"absolute",left:this.WC.left+"px",top:this.WC.top+"px"}),this.helper.appendTo("body").tS()):this.helper=this.element},Uf:{e:function(a,b){return{width:this.ge.width+b}},w:function(a,b){return{left:this.zd.left+b,width:this.ge.width-b}},n:function(a,b,e){return{top:this.zd.top+e,height:this.ge.height-e}},s:function(a,b,e){return{height:this.ge.height+e}},se:function(a,b,f){return e.extend(this.Uf.s.apply(this,arguments),this.Uf.e.apply(this,[a,b,f]))},
sw:function(a,b,f){return e.extend(this.Uf.s.apply(this,arguments),this.Uf.w.apply(this,[a,b,f]))},ne:function(a,b,f){return e.extend(this.Uf.n.apply(this,arguments),this.Uf.e.apply(this,[a,b,f]))},nw:function(a,b,f){return e.extend(this.Uf.n.apply(this,arguments),this.Uf.w.apply(this,[a,b,f]))}},bp:function(a,b){e.ui.plugin.call(this,a,[b,this.ui()]);"resize"!==a&&this._trigger(a,b,this.ui())},plugins:{},ui:function(){return{Bc:this.Bc,element:this.element,helper:this.helper,position:this.position,
size:this.size,ge:this.ge,zd:this.zd,mk:this.mk,lk:this.lk}}});e.ui.plugin.add("resizable","animate",{stop:function(a){var b=e(this).data("oj-resizable"),f=b.options,h=b.ni,g=h.length&&/textarea/i.test(h[0].nodeName),k=g&&b.Go(h[0],"left")?0:b.zh.height,g={width:b.size.width-(g?0:b.zh.width),height:b.size.height-k},k=parseInt(b.element.css("left"),10)+(b.position.left-b.zd.left)||null,l=parseInt(b.element.css("top"),10)+(b.position.top-b.zd.top)||null;b.element.animate(e.extend(g,l&&k?{top:l,left:k}:
{}),{duration:f.animateDuration,xS:f.animateEasing,step:function(){var f={width:parseInt(b.element.css("width"),10),height:parseInt(b.element.css("height"),10),top:parseInt(b.element.css("top"),10),left:parseInt(b.element.css("left"),10)};h&&h.length&&e(h[0]).css({width:f.width,height:f.height});b.lC(f);b.bp("resize",a)}})}});e.ui.plugin.add("resizable","containment",{start:function(){var a,b,f,h,g,k=e(this).data("oj-resizable"),l=k.element;f=k.options.containment;if(l=f instanceof e?f.get(0):/parent/.test(f)?
l.parent().get(0):f)k.vp=e(l),/document/.test(f)||f===document?(k.wp={left:0,top:0},k.JC={left:0,top:0},k.vh={element:e(document),left:0,top:0,width:e(document).width(),height:e(document).height()||document.body.parentNode.scrollHeight}):(a=e(l),b=[],e(["Top","Right","Left","Bottom"]).each(function(e,f){b[e]=k.Ps(a.css("padding"+f))}),k.wp=a.offset(),k.JC=a.position(),k.KC={height:a.innerHeight()-b[3],width:a.innerWidth()-b[1]},f=k.wp,h=k.KC.height,g=k.KC.width,g=k.Go(l,"left")?l.scrollWidth:g,h=
k.Go(l)?l.scrollHeight:h,k.vh={element:l,left:f.left,top:f.top,width:g,height:h})},resize:function(a,b){var f,h,g,k,l=e(this).data("oj-resizable");f=l.options;h=l.wp;k=l.position;var m=l.Lq||a.shiftKey;g={top:0,left:0};var n=l.vp,q=!0;n[0]!==document&&/static/.test(n.css("position"))&&(g=h);k.left<(l.Nc?h.left:0)&&(l.size.width+=l.Nc?l.position.left-h.left:l.position.left-g.left,m&&(l.size.height=l.size.width/l.aspectRatio,q=!1),l.position.left=f.helper?h.left:0);k.top<(l.Nc?h.top:0)&&(l.size.height+=
l.Nc?l.position.top-h.top:l.position.top,m&&(l.size.width=l.size.height*l.aspectRatio,q=!1),l.position.top=l.Nc?h.top:0);l.offset.left=l.vh.left+l.position.left;l.offset.top=l.vh.top+l.position.top;f=Math.abs((l.Nc?l.offset.left-g.left:l.offset.left-h.left)+l.zh.width);h=Math.abs((l.Nc?l.offset.top-g.top:l.offset.top-h.top)+l.zh.height);g=l.vp.get(0)===l.element.parent().get(0);k=/relative|absolute/.test(l.vp.css("position"));g&&k&&(f-=Math.abs(l.vh.left));f+l.size.width>=l.vh.width&&(l.size.width=
l.vh.width-f,m&&(l.size.height=l.size.width/l.aspectRatio,q=!1));h+l.size.height>=l.vh.height&&(l.size.height=l.vh.height-h,m&&(l.size.width=l.size.height*l.aspectRatio,q=!1));q||(l.position.left=b.lk.left,l.position.top=b.lk.top,l.size.width=b.mk.width,l.size.height=b.mk.height)},stop:function(){var a=e(this).data("oj-resizable"),b=a.options,f=a.wp,h=a.JC,g=a.vp,k=e(a.helper),l=k.offset(),m=k.outerWidth()-a.zh.width,k=k.outerHeight()-a.zh.height;a.Nc&&(!b.animate&&/relative/.test(g.css("position")))&&
e(this).css({left:l.left-h.left-f.left,width:m,height:k});a.Nc&&(!b.animate&&/static/.test(g.css("position")))&&e(this).css({left:l.left-h.left-f.left,width:m,height:k})}});e.ui.plugin.add("resizable","alsoResize",{start:function(){function a(b){e(b).each(function(){var a=e(this);a.data("oj-resizable-alsoresize",{width:parseInt(a.width(),10),height:parseInt(a.height(),10),left:parseInt(a.css("left"),10),top:parseInt(a.css("top"),10)})})}var b=e(this).data("oj-resizable").options;"object"!==typeof b.alsoResize||
b.alsoResize.parentNode?a(b.alsoResize):b.alsoResize.length?(b.alsoResize=b.alsoResize[0],a(b.alsoResize)):e.each(b.alsoResize,function(b){a(b)})},resize:function(a,b){function f(a,d){e(a).each(function(){var a=e(this),f=e(this).data("oj-resizable-alsoresize"),g={};e.each(d&&d.length?d:a.parents(b.Bc[0]).length?["width","height"]:["width","height","top","left"],function(a,b){var c=(f[b]||0)+(m[b]||0);c&&0<=c&&(g[b]=c||null)});a.css(g)})}var h=e(this).data("oj-resizable"),g=h.options,k=h.ge,l=h.zd,
m={height:h.size.height-k.height||0,width:h.size.width-k.width||0,top:h.position.top-l.top||0,left:h.position.left-l.left||0};"object"!==typeof g.alsoResize||g.alsoResize.nodeType?f(g.alsoResize,null):e.each(g.alsoResize,function(a,b){f(a,b)})},stop:function(){e(this).removeData("resizable-alsoresize")}});e.ui.plugin.add("resizable","ghost",{start:function(){var a=e(this).data("oj-resizable"),b=a.options,f=a.size;a.ghost=a.Bc.clone();a.ghost.css({opacity:0.25,display:"block",position:"relative",height:f.height,
width:f.width,margin:0,left:0,top:0}).addClass("oj-resizable-ghost").addClass("string"===typeof b.ghost?b.ghost:"");a.ghost.appendTo(a.helper)},resize:function(){var a=e(this).data("oj-resizable");a.ghost&&a.ghost.css({position:"relative",height:a.size.height,width:a.size.width})},stop:function(){var a=e(this).data("oj-resizable");a.ghost&&a.helper&&a.helper.get(0).removeChild(a.ghost.get(0))}});e.ui.plugin.add("resizable","grid",{resize:function(){var a=e(this).data("oj-resizable"),b=a.options,f=
a.size,h=a.ge,g=a.zd,k=a.axis,l="number"===typeof b.grid?[b.grid,b.grid]:b.grid,m=l[0]||1,n=l[1]||1,q=Math.round((f.width-h.width)/m)*m,f=Math.round((f.height-h.height)/n)*n,r=h.width+q,p=h.height+f,s=b.maxWidth&&b.maxWidth<r,v=b.maxHeight&&b.maxHeight<p,u=b.minWidth&&b.minWidth>r,y=b.minHeight&&b.minHeight>p;b.grid=l;u&&(r+=m);y&&(p+=n);s&&(r-=m);v&&(p-=n);/^(se|s|e)$/.test(k)?(a.size.width=r,a.size.height=p):/^(ne)$/.test(k)?(a.size.width=r,a.size.height=p,a.position.top=g.top-f):/^(sw)$/.test(k)?
(a.size.width=r,a.size.height=p,a.position.left=g.left-q):(0<p-n?(a.size.height=p,a.position.top=g.top-f):(a.size.height=n,a.position.top=g.top+h.height-n),0<r-m?(a.size.width=r,a.position.left=g.left-q):(a.size.width=m,a.position.left=g.left+h.width-m))}})})();(function(){var a={buttons:!0,height:!0,width:!0},d={};b.ta("oj.ojDialog",e.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancelBehavior:"icon",dragAffordance:"title-bar",height:"auto",initialVisibility:"show",modality:"modal",
position:{my:"center",at:"center",of:window,collision:"fit",cT:function(a){var b=e(this).css(a).offset().top;0>b&&e(this).css("top",a.top-b)}},resizeBehavior:"resizable",role:"dialog",title:null,width:"300",beforeClose:null,beforeOpen:null,close:null,focus:null,open:null,resize:null,resizeStart:null,resizeStop:null},_create:function(){this.pQ={display:this.element[0].style.display,width:this.element[0].style.width,minHeight:this.element[0].style.minHeight,maxHeight:this.element[0].style.maxHeight,
height:this.element[0].style.height};this.zd={parent:this.element.parent(),index:this.element.parent().children().index(this.element)};this.Du=this.element.attr("title");this.options.title=this.options.title||this.Du;this.tI();this.element.show().removeAttr("title").addClass("oj-dialog-content oj-dialog-default-content").appendTo(this.wa);this.cq=!1;var a=this.element.find(".oj-dialog");a.length?a.parents(".oj-dialog-header").length&&(this.cq=!0):this.element.find(".oj-dialog-header").length&&(this.cq=
!0);this.cq&&(a=this.element.find(".oj-dialog-header"),a.prependTo(this.wa),"icon"===this.options.cancelBehavior&&this.Ox(a));this.cq||this.sI();"title-bar"===this.options.dragAffordance&&e.fn.draggable&&this.$z();"resizable"===this.options.resizeBehavior&&e.fn.resizable&&this.bA();this.xl=!1;this._super()},_init:function(){"show"===this.options.initialVisibility&&this.open()},Sw:function(){return this.document.find("body").eq(0)},_destroy:function(){var a,b=this.zd;this.ey();this.element.removeUniqueId().removeClass("oj-dialog-content").css(this.pQ).detach();
this.wa.stop(!0,!0).remove();this.Du&&this.element.attr("title",this.Du);a=b.parent.children().eq(b.index);a.length&&a[0]!==this.element[0]?a.before(this.element):b.parent.append(this.element)},widget:o_c("wa"),disable:e.noop,enable:e.noop,close:function(a){var b=this;this.xl&&!1!==this._trigger("beforeClose",a)&&(this.xl=!1,this.ey(),this.opener.filter(":focusable").focus().length||e(this.document[0].activeElement).blur(),this._hide(this.wa,null,function(){b._trigger("close",a)}),e("#"+this.wA).replaceWith(e("#"+
this.Dt)))},isOpen:o_c("xl"),KS:function(){this.Yo()},Yo:function(a,b){if(null===this.options.appendTo){var d=!1,g=parseInt(this.wa.css("zIndex"),10);e(".oj-dialog").each(function(){if(e(this)!=this.wa){d=!0;var a=parseInt(e(this).css("zIndex"),10);g>a&&(g=a)}});var k=!1;d&&e(".oj-dialog").each(function(){e(this)!=this.wa&&(e(this).css({position:"absolute",zIndex:g}),k=!0)});d&&this.wa.css({position:"absolute",zIndex:g+1});return k}var l=!!this.wa.nextAll(":visible").insertBefore(this.wa).length;
l&&!b&&this._trigger("focus",a);return l},open:function(a){if(!1!==this._trigger("beforeOpen",a)){var b=this;this.xl?this.Yo()&&this.el():(this.xl=!0,this.opener=e(this.document[0].activeElement),this.SB(),this.WM(),this.gI(),this.Us(),this.Yo(null,!0),this._show(this.wa,null,function(){b.el();b._trigger("focus")}),this._trigger("open"))}},el:function(){var a=this.element.find("[autofocus]");a.length||(a=this.element.find(":tabbable"));a.length||this.XQ&&(a=this.XQ.find(":tabbable"));a.length||this.Xu&&
(a=this.Xu.filter(":tabbable"));a.length||(a=this.wa);a.eq(0).focus()},fS:function(a){function b(){var a=this.document[0].activeElement;this.wa[0]===a||e.contains(this.wa[0],a)||this.el()}a.preventDefault();b.call(this);this._delay(b)},tI:function(){this.element.uniqueId();this.ry=this.element.attr("id");this.Dt="ojDialogWrapper-"+this.ry;this.wa=e("\x3cdiv\x3e").addClass("oj-dialog oj-helper-reset-inheritable oj-component oj-dialog-front ").hide().attr({tabIndex:-1,role:this.options.role,id:this.Dt});
this.qr=this.element.css("min-width");this.wa.css("min-width",this.qr);this.zI=this.element.css("max-width");this.wa.css("max-width",this.zI);this.Zn=this.element.css("min-height");this.wa.css("min-height",this.Zn);this.pr=this.element.css("max-height");this.wa.css("max-height",this.pr);this.wa.insertBefore(this.element);this._on(this.wa,{keydown:function(a){if("none"!=this.options.cancelBehavior&&!a.isDefaultPrevented()&&a.keyCode&&a.keyCode===e.ui.keyCode.ESCAPE)a.preventDefault(),this.close(a);
else if(a.keyCode===e.ui.keyCode.TAB){var b=this.wa.find(":tabbable"),d=b.filter(":first"),b=b.filter(":last");a.target!==b[0]&&a.target!==this.wa[0]||a.shiftKey?a.target!==d[0]&&a.target!==this.wa[0]||!a.shiftKey||(b.focus(1),a.preventDefault()):(d.focus(1),a.preventDefault())}},mousedown:function(a){this.Yo(a)&&this.el()}});this.element.find("[aria-describedby]").length||this.wa.attr({"aria-describedby":this.element.uniqueId().attr("id")})},Ox:function(a){this.Xu=e("\x3cbutton\x3e\x3c/button\x3e").ojButton({display:"icons",
icons:{start:"oj-component-icon oj-dialog-close-icon"},text:!1}).addClass("oj-dialog-header-close oj-button-no-chrome").appendTo(a);this._on(this.Xu,{click:function(a){a.preventDefault();this.close(a)}})},sI:function(){var a;this.aq=e("\x3cdiv\x3e").addClass("oj-dialog-header oj-helper-clearfix").prependTo(this.wa);this._on(this.aq,{mousedown:function(a){e(a.target).closest(".oj-dialog-close-icon")||this.wa.focus()}});"icon"===this.options.cancelBehavior&&this.Ox(this.aq);a=e("\x3cspan\x3e").uniqueId().addClass("oj-dialog-title").prependTo(this.aq);
this.dC(a);this.wa.attr({"aria-labelledby":a.attr("id")})},dC:function(a){this.options.title||a.html("\x26#160;");a.text(this.options.title)},$z:function(){function a(b){return{position:b.position,offset:b.offset}}var b=this,d=this.options;this.wa.draggable({cancel:".oj-dialog-content, .oj-dialog-header-close",handle:".oj-dialog-header",containment:"document",start:function(d,h){e(this).addClass("oj-dialog-dragging");b.cx();b._trigger("dragStart",d,a(h))},uS:function(d,e){b._trigger("drag",d,a(e))},
stop:function(g,k){d.position=[k.position.left-b.document.scrollLeft(),k.position.top-b.document.scrollTop()];e(this).removeClass("oj-dialog-dragging");b.iC();b._trigger("dragStop",g,a(k))}})},bA:function(){function a(b){return{zd:b.zd,ge:b.ge,position:b.position,size:b.size}}var b=this,d=this.options,g=this.wa.css("position");this.Ql=this.wa.ojResizable.bind(this.wa);this.Ql({cancel:".oj-dialog-content",containment:"document",alsoResize:this.element,minHeight:this.hA(),handles:"n,e,s,w,se,sw,ne,nw",
start:function(d,g){e(this).addClass("oj-dialog-resizing");b.cx();b._trigger("ojstart",d,a(g))},resize:function(d,e){b._trigger("ojresize",d,a(e))},stop:function(g,l){d.height=e(this).height();d.width=e(this).width();e(this).removeClass("oj-dialog-resizing");b.iC();b._trigger("ojstop",g,a(l))}}).css("position",g)},hA:function(){var a=this.options;return"auto"===a.height?this.Zn:Math.min(this.Zn,a.height)},Us:function(){var a=this.wa.is(":visible");a||this.wa.show();this.wa.position(this.options.position);
a||this.wa.hide()},_setOptions:function(b){var f=this,h=!1,g={};e.each(b,function(b,c){f._setOption(b,c);b in a&&(h=!0);b in d&&(g[b]=c)});h&&(this.SB(),this.Us());this.wa.is(":data(oj-resizable)")&&this.Ql("option",g)},_setOption:function(a,b){var d,e=this.wa;"disabled"!==a&&(this._super(a,b),"draggable"===a&&((d=e.is(":data(oj-draggable)"))&&!b&&e.draggable("destroy"),!d&&b&&this.$z()),"position"===a&&this.Us(),"resizable"===a&&((d=e.is(":data(oj-resizable)"))&&!b&&e.Ql("destroy"),d&&"string"===
typeof b&&e.Ql("option","handles",b),d||!1===b||this.bA()),"title"===a&&this.dC(this.aq.find(".oj-dialog-title")))},SB:function(){var a,b,d,e=this.options;this.element.show().css({width:"auto",minHeight:0,maxHeight:"none",height:0});this.qr>e.width&&(e.width=this.qr);a=this.wa.css({height:"auto",width:e.width}).outerHeight();b=Math.max(0,this.Zn-a);d="number"===typeof this.pr?Math.max(0,this.pr-a):"none";"auto"===e.height?this.element.css({minHeight:b,maxHeight:d,height:"auto"}):this.element.height(Math.max(0,
e.height-a));this.wa.is(":data(oj-resizable)")&&this.wa.Ql("option","minHeight",this.hA())},cx:function(){this.mu=this.document.find("iframe").map(function(){var a=e(this),b=a.offset();return e("\x3cdiv\x3e").css({position:"absolute",width:a.outerWidth(),height:a.outerHeight()}).appendTo(a.parent()).offset(b)[0]})},iC:function(){this.mu&&(this.mu.remove(),delete this.mu)},hH:function(a){return e(a.target).closest(".oj-dialog").length?!0:!!e(a.target).closest(".oj-datepicker").length},WM:function(){this.wA=
"ojDialogPlaceHolder-"+this.ry;this.qM=e("\x3cdiv\x3e").hide().attr({id:this.wA});this.qM.insertBefore(e("#"+this.Dt));this.wa.appendTo(this.Sw())},gI:function(){if("modeless"!==this.options.modality){var a=this,b=this.widgetFullName;e.ui.dialog.overlayInstances||this._delay(function(){e.ui.dialog.overlayInstances&&this.document.bind("focusin.dialog",function(d){a.hH(d)||(d.preventDefault(),e(".oj-dialog:visible:last .oj-dialog-content").data(b).el())})});this.Jm=e("\x3cdiv\x3e").addClass("oj-component-overlay oj-dialog-front");
this.Jm.appendTo(this.Sw());this._on(this.Jm,{mousedown:"_keepFocus"});e.ui.dialog.overlayInstances++}},ey:function(){"modeless"!==this.options.modality&&this.Jm&&(e.ui.dialog.overlayInstances--,e.ui.dialog.overlayInstances||this.document.unbind("focusin.dialog"),this.Jm.remove(),this.Jm=null)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-dialog":case "oj-dialog-header":case "oj-dialog-body":case "oj-dialog-footer":case "oj-dialog-content":case "oj-dialog-header-close":case "oj-resizable-n":case "oj-resizable-e":case "oj-resizable-s":case "oj-resizable-w":case "oj-resizable-se":case "oj-resizable-sw":case "oj-resizable-ne":case "oj-resizable-nw":return a=
"."+a,this.widget().find(a)[0]}return null}});e.ui.dialog.overlayInstances=0})()});
//# sourceMappingURL=oj-modular.map