define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){function a(a,b){this.WL=b;this.XM=a;this.nI="/"}b.Ad=function(a){this.Init(a)};o_("AttributeGroupHandler",b.Ad,b);b.a.fa(b.Ad,b.a,"oj.AttributeGroupHandler");b.Ad.prototype.Init=function(a){b.Ad.j.Init.call(this);this.ol=a?a:{};this.Ek={};this.jp=0;this.Vm=this.em();for(var d in this.ol)a=this.Vm.indexOf(this.ol[d]),-1!==a&&this.Vm.splice(a,1)};b.Ad.prototype.em=function(){return[]};b.a.b("AttributeGroupHandler.prototype.getValueRamp",
{em:b.Ad.prototype.em});b.Ad.prototype.xp=function(a){if(this.ol[a])return this.ol[a];this.Ek[a]||(this.Ek[a]=this.Vm[this.jp],this.jp==this.Vm.length-1?this.jp=0:this.jp++);return this.Ek[a]};b.a.b("AttributeGroupHandler.prototype.getValue",{xp:b.Ad.prototype.xp});b.Ad.prototype.RC=function(){var a=[],b;for(b in this.Ek)a.push({category:b,value:this.Ek[b]});return a};b.a.b("AttributeGroupHandler.prototype.geCategoryAssignments",{RC:b.Ad.prototype.RC});b.Ad.prototype.mC=function(a,b){this.ol[a]=b};
b.a.b("AttributeGroupHandler.prototype.addMatchRule",{mC:b.Ad.prototype.mC});var d={CSS_TEXT_PROPERTIES:function(a,b){var e={};a&&(a.hasClass("oj-gaugeMetricLabel")&&a.hasClass(a.parentNode,"oj-ledGauge")&&(e["font-size"]=!0,e.color=!0),a.hasClass(a,"oj-chartSliceLabel")&&(e.color=!0));return d.Wz(a,b,!1,e)},CSS_BACKGROUND_PROPERTIES:function(a,b){return d.Wz(a,b,!0,{})},CSS_URL:function(a){return d.VL(a)},wv:"rgb(254, 0, 254)",xv:"Times",yv:"1px",Av:"1",zv:"normal",PO:function(a,b){return a.css(b)},
VL:function(a){return(a=a.css("content"))&&-1!==a.indexOf("url(")?a.slice(a.indexOf("url(")+4,a.length-1).replace(/"/g,""):a},kH:function(a){var b="";a.css("border-top-color")&&(b+="border-color: "+a.css("border-top-color")+";");a.css("border-width")&&(a.css("border-style")&&"none"!=a.css("border-style"))&&(b+="border-width: "+a.css("border-width")+";");a.css("background-color")&&(b+="background-color: "+a.css("background-color")+";");return b},pH:function(a,b){var e="",g=a.css("font-family");g&&
g!==d.xv&&(e+="font-family: "+g.replace(/"/g,"'")+";");(g=a.css("font-size"))&&(g!==d.yv&&!b["font-size"])&&(e+="font-size: "+g+";");(g=a.css("font-weight"))&&g!==d.Av&&(e+="font-weight: "+g+";");(g=a.css("color"))&&(g!==d.wv&&!b.color)&&(e+="color: "+g+";");(g=a.css("font-style"))&&g!==d.zv&&(e+="font-style: "+g+";");return e},Wz:function(a,b,d,e){e||(e={});if(!a)return b;var k;b&&(k=a.attr("style"),a.attr("style",k+b));b="";!0!==d&&(b+=this.pH(a,e));!1!==d&&(b+=this.kH(a));k&&a.attr("style",k);
return b}};b.ta("oj.dvtBaseComponent",e.oj.baseComponent,{xs:[],jx:[],GN:"ar cs da de el es fi fr hu it iw ja ko nl no pl pt pt_BR ro ru sk sv th tr zh_CN zh_TW".split(" "),_create:function(){this._super();this.Jk=new DvtContext(this.element[0]);this.Jk.setReadingDirection(this.xc());this.element.attr("tabIndex",0);this.Cb=this.Je(this.Jk,this.Bh,this);this.Jk.getStage().addChild(this.Cb);this.jM(this.zh());this.rA();this.ln();this.RG();this.Me();b.xa.$g(this.element[0],e.proxy(this.Wh,this))},refresh:function(){this._super();
this.Jk.setReadingDirection(this.xc());this.rA();this.Me()},getNodeBySubId:function(a){var b;this.Cb&&this.Cb.getAutomation&&(b=this.Cb.getAutomation());return b?b.iS(a):null},RG:function(){var a=e(document.createElement("div"));a.attr("style","display:none;");a.text(JSON.stringify(this.options));this.element.append(a)},nf:function(){return["oj-dvtbase"]},zh:function(){return{}},jM:function(a){for(var b=this.nf(),h=this.element.attr("class"),g="",k=0;k<b.length;k++)g=g+b[k]+" ";h&&(g+=h);this.element.attr("class",
g);b=e(document.createElement("div"));b.attr("style","display:none;");this.element.append(b);b.css("font-family",d.xv);b.css("font-size",d.yv);b.css("color",d.wv);b.css("font-weight",d.Av);b.css("font-style",d.zv);for(var l in a)h=e(document.createElement("div")),h.addClass(l),b.append(h),this.iM(h,a[l])},iM:function(a,b){if(b instanceof Array)for(var d=0;d<b.length;d++)this.dB(a,b[d]);else this.dB(a,b)},dB:function(b,f){var e=new a(this.options,f.path),g;f.property&&(g=(g=d[f.property])?g(b,e.xp()):
d.PO(b,f.property));null==g||"string"==typeof g&&""==g.replace(/^\s+/g,"")||e.rQ(g)},uk:function(){var a={"oj-ojDvtCommon.labelClearSelection":"DvtUtilBundle.CLEAR_SELECTION","oj-dvtBaseComponent.labelMonthShortJanuary":"DvtUtilBundle.MONTH_SHORT_JANUARY","oj-dvtBaseComponent.labelMonthShortFebruary":"DvtUtilBundle.MONTH_SHORT_FEBRUARY","oj-dvtBaseComponent.labelMonthShortMarch":"DvtUtilBundle.MONTH_SHORT_MARCH","oj-dvtBaseComponent.labelMonthShortApril":"DvtUtilBundle.MONTH_SHORT_APRIL","oj-dvtBaseComponent.labelMonthShortMay":"DvtUtilBundle.MONTH_SHORT_MAY",
"oj-dvtBaseComponent.labelMonthShortJune":"DvtUtilBundle.MONTH_SHORT_JUNE","oj-dvtBaseComponent.labelMonthShortJuly":"DvtUtilBundle.MONTH_SHORT_JULY","oj-dvtBaseComponent.labelMonthShortAugust":"DvtUtilBundle.MONTH_SHORT_AUGUST","oj-dvtBaseComponent.labelMonthShortSeptember":"DvtUtilBundle.MONTH_SHORT_SEPTEMBER","oj-dvtBaseComponent.labelMonthShortOctober":"DvtUtilBundle.MONTH_SHORT_OCTOBER","oj-dvtBaseComponent.labelMonthShortNovember":"DvtUtilBundle.MONTH_SHORT_NOVEMBER","oj-dvtBaseComponent.labelMonthShortDecember":"DvtUtilBundle.MONTH_SHORT_DECEMBER",
"oj-dvtBaseComponent.labelScalingSuffixThousand":"DvtUtilBundle.SCALING_SUFFIX_THOUSAND","oj-dvtBaseComponent.labelScalingSuffixMillion":"DvtUtilBundle.SCALING_SUFFIX_MILLION","oj-dvtBaseComponent.labelScalingSuffixBillion":"DvtUtilBundle.SCALING_SUFFIX_BILLION","oj-dvtBaseComponent.labelScalingSuffixTrillion":"DvtUtilBundle.SCALING_SUFFIX_TRILLION","oj-dvtBaseComponent.labelScalingSuffixQuadrillion":"DvtUtilBundle.SCALING_SUFFIX_QUADRILLION","oj-dvtBaseComponent.stateSelected":"DvtUtilBundle.STATE_SELECTED",
"oj-dvtBaseComponent.stateUnselected":"DvtUtilBundle.STATE_UNSELECTED","oj-dvtBaseComponent.stateMaximized":"DvtUtilBundle.STATE_MAXIMIZED","oj-dvtBaseComponent.stateMinimized":"DvtUtilBundle.STATE_MINIMIZED","oj-dvtBaseComponent.stateExpanded":"DvtUtilBundle.STATE_EXPANDED","oj-dvtBaseComponent.stateCollapsed":"DvtUtilBundle.STATE_COLLAPSED","oj-dvtBaseComponent.stateIsolated":"DvtUtilBundle.STATE_ISOLATED","oj-dvtBaseComponent.stateHidden":"DvtUtilBundle.STATE_HIDDEN","oj-dvtBaseComponent.stateVisible":"DvtUtilBundle.STATE_VISIBLE"},
d={},e;for(e in a){var g=a[e],k=b.L.Wj(e);d[g]=k}return d},cc:function(a,d){var e=this.options[a];if(d){for(var g={},k=0;k<d.length;k++)g[d[k]]="{"+k+"}";e=b.L.lb(e,g)}return e},rA:function(){var a=this.uk();DvtBundle.addLocalizedStrings(a)},_destroy:function(){this.element.children().remove();this._super()},_setOptions:function(a){this._superApply(arguments);this.Me()},Je:o_d(null),Bh:o_a(),Wh:function(){var a=this.element.width(),b=this.element.height();5<=Math.abs(a-this.qt)+Math.abs(b-this.fs)&&
(this.Cb.render(null,a,b),this.qt=a,this.fs=b)},ln:o_a(),LF:function(a){var d=b.Wa.Jd();if(0===d.indexOf("en"))this.Mz(a+".js");else{for(var e=d.split("_"),d=[],g=0;g<e.length;g++){for(var k="",l=0;l<g+1;l++)0!=l&&(k+="_"),k+=e[l];d.push(k)}for(e=d.length-1;0<=e;e++)-1!==this.GN.indexOf(d[e])&&this.Mz(a+"_"+d[e]+".js")}},Mz:function(a){if(!this.xs[a]){var d=b.Wa.ri(a),h=this,g=this.xs;e.getScript(d,function(){g[a]=!0;h.Me()})}},Me:function(){for(var a=0;a<this.jx.length;a++)if(!this.xs[this.jx[a]])return;
this.Jk.isReadyToRender()?(this.qt=this.element.width(),this.fs=this.element.height(),this.Cb.render(this.options,this.qt,this.fs)):b.F.error(b.L.Wj("oj-dvtBaseComponent.notReadyToRender").summary)}});b.pk=function(a){this.Init(a)};o_("ShapeAttributeGroupHandler",b.pk,b);b.a.fa(b.pk,b.Ad,"oj.ShapeAttributeGroupHandler");b.pk.En="square circle diamond plus triangleDown triangleUp human".split(" ");b.pk.prototype.em=function(){return b.pk.En.slice()};b.Fi=function(a){this.En=[];var d=e(document.createElement("div"));
d.attr("style","display:none;");d.attr("id","attrGps");e(document.body).append(d);for(var h=0;h<b.Fi.MB.length;h++){var g=e(document.createElement("div"));g.addClass(b.Fi.MB[h]);d.append(g);this.En.push(g.css("color"))}d.remove();this.Init(a)};o_("ColorAttributeGroupHandler",b.Fi,b);b.a.fa(b.Fi,b.Ad,"oj.ColorAttributeGroupHandler");b.Fi.MB="oj-dvt-category-index1 oj-dvt-category-index2 oj-dvt-category-index3 oj-dvt-category-index4 oj-dvt-category-index5 oj-dvt-category-index6 oj-dvt-category-index7 oj-dvt-category-index8 oj-dvt-category-index9 oj-dvt-category-index10 oj-dvt-category-index11 oj-dvt-category-index12".split(" ");
b.Fi.prototype.em=function(){return this.En.slice()};a.prototype.TM=function(a,b,d,e){for(var k={};a&&-1<b.indexOf(d);){var l=b.substring(0,b.indexOf(d));e&&void 0===a[l]&&(a[l]={});a=a[l];b=b.substring(b.indexOf(d)+1,b.length)}a&&(k.object=a,k.parameter=b);return k};a.prototype.cB=function(a){void 0===this.nl&&(a=this.TM(this.XM,this.WL,this.nI,a),this.nl=a.object,this.Is=a.parameter)};a.prototype.xp=function(){this.cB(!1);return void 0===this.nl?void 0:this.nl[this.Is]};a.prototype.rQ=function(a){this.cB(!0);
this.nl[this.Is]!==a&&(this.nl[this.Is]=a)}});
//# sourceMappingURL=oj-modular.map