define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojbutton"],function(b,e){b.ta("oj.ojInputNumber",e.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{converter:b.R.gh(b.gf.CONVERTER_TYPE_NUMBER).createConverter(),max:void 0,min:void 0,readOnly:void 0,placeholder:void 0,step:void 0},stepUp:function(a){this.WB(a,!0)},stepDown:function(a){this.WB(a,!1)},option:function(a,b){var c=this._superApply(arguments);if("max"===a||"min"===a||"object"===typeof a&&
(void 0!==a.min||void 0!==a.max)){var e=void 0,h=void 0;"max"===a?h=null!=b?b:void 0:"min"===a?e=null!=b?b:void 0:(void 0!==a.max&&(h=null!=a.max?a.max:void 0),void 0!==a.min&&(e=null!=a.min?a.min:void 0));e={min:e,max:h,converter:this.Ed()};this.Tx(e);this.Hk()}return c},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-inputnumber-up"===a?this.widget().find(".oj-inputnumber-up")[0]:"oj-inputnumber-down"===a?this.widget().find(".oj-inputnumber-down")[0]:
"oj-inputnumber-input"===a?this.widget().find(".oj-inputnumber-input")[0]:null},Of:function(){this._super();void 0===this.options.readOnly&&(this.options.readOnly=void 0!==this.element.attr("readonly")?!!this.element.prop("readonly"):!1);if("boolean"!==typeof this.options.readOnly)throw Error("InputNumber's option 'readOnly' has a invalid value set; \n            it should be a boolean: "+this.options.readOnly);null==this.options.value&&(this.options.value=""!==this.element.val()?this.element.val():
null);this.options.value=this.er(this.options.value);var a=this;e.each(["min","max","step"],function(b,c){void 0===a.options[c]&&(a.options[c]=a.element.attr(c),null==a.options[c]&&(a.options[c]="step"===c?1:null));null!=a.options[c]&&(a.options[c]="step"===c?a.vA(a.options[c]):a.ap(a.options[c]))})},Kc:function(){var a=this.element;this._super();"boolean"===typeof this.options.readOnly&&a.prop("readonly",this.options.readOnly);this.Yk();this._on(this.Pe);this._on(this.window,{beforeunload:function(){a.removeAttr("autocomplete")}});
a.removeAttr("pattern");this.Hz={}},Bk:function(){this._super();this.NA();this.Ll("readOnly",this.options.readOnly);this.lC()},_setOption:function(a,b){"value"===a&&(b=this.er(b));"max"!==a&&"min"!==a||"string"!==typeof b||(b=this.ap(b));"step"===a&&(b=this.vA(b));this._super(a,b);"disabled"===a&&(b?this.element.prop("disabled",!0):this.element.prop("disabled",!1));"readOnly"===a&&(this.element.prop("readonly",!!b),this.Ll("readOnly",this.options.readOnly))},_destroy:function(){this.element.removeClass("oj-inputnumber-input").prop("disabled",
!1).removeAttr("autocomplete").removeAttr("aria-valuemin").removeAttr("aria-valuemax").removeAttr("aria-valuenow").removeAttr("aria-valuetext").removeAttr("aria-disabled");this.element.attr("type",this.saveType);this._super();this._off(this.element,"keydown keyup focus blur mousedown mouseup mouseenter mouseleave");this.Sm.replaceWith(this.element);clearTimeout(this.ef)},wq:function(a,b){this._super(a,b);"value"!==a&&"max"!==a&&"min"!==a||this.NA();this.lC()},Cv:function(){return!this._super()||this.options.readOnly?
!1:!0},ln:function(){var a=this._superApply(arguments),b=null!=this.options.min?this.options.min:void 0,c=null!=this.options.max?this.options.max:void 0,f={};if(null!=b||null!=c)f={min:b,max:c,converter:this.Ed()},this.Tx(f);return e.extend(this.Hz,a)},_GetDefaultStyleClass:o_d("oj-inputnumber"),Pe:{keydown:function(a){a.keyCode===e.ui.keyCode.ENTER?(this.ex(a),a.preventDefault()):this.Nj()&&this.ii(a)&&a.preventDefault()},keyup:function(a){this.Sl(a)},focus:function(){this.previous=this.element.val()},
blur:function(a){this.Jt?delete this.Jt:this.ex(a)},"mousedown .oj-inputnumber-button":function(a){function b(){this.element[0]!==this.document[0].activeElement&&(this.element.focus(),this.previous=c,this._delay(function(){this.previous=c}))}var c;c=this.element[0]===this.document[0].activeElement?this.previous:this.element.val();a.preventDefault();b.call(this);this.Jt=!0;this._delay(function(){delete this.Jt;b.call(this)});this.Nj();this.Pl(null,e(a.currentTarget).hasClass("oj-inputnumber-up")?1:
-1,a)},"mouseup .oj-inputnumber-button":function(a){this.Sl(a)},"mouseenter .oj-inputnumber-button":function(a){e(a.currentTarget).hasClass("oj-active")&&(this.Nj(),this.Pl(null,e(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a))},"mouseleave .oj-inputnumber-button":function(a){this.Sl(a)}},Aa:{QG:"tooltipDecrement",SG:"tooltipIncrement"},qf:{readOnly:"oj-read-only"},Yk:function(){var a=this.Sm=this.element.addClass("oj-inputnumber-input").attr("autocomplete","off").wrap("\x3cspan class\x3d'oj-inputnumber oj-component'\x3e\x3c/span\x3e").parent().append("\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/a\x3e\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/a\x3e");
this.saveType=this.element.prop("type");this.element.attr("type","text");var b=this.l(this.Aa.SG),c=this.l(this.Aa.QG);a.find(".oj-inputnumber-up").ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-up-icon"},label:b});a.find(".oj-inputnumber-down").ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-down-icon"},label:c});this.buttons=a.find(".oj-inputnumber-button").attr("tabIndex","-1").attr("aria-hidden",!0)},ii:function(a){var b=e.ui.keyCode;switch(a.keyCode){case b.UP:return this.Pl(null,
1,a),!0;case b.DOWN:return this.Pl(null,-1,a),!0}return!1},lS:o_d("\x3cspan class\x3d'oj-inputnumber oj-component'\x3e\x3c/span\x3e"),tR:o_d("\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/a\x3e\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/a\x3e"),Nj:function(){return this.wE=!0},Pl:function(a,b,c){a=a||500;clearTimeout(this.ef);this.ef=this._delay(function(){this.Pl(40,b,c)},a);this.rt(b*this.options.step,c)},rt:function(a,b){var c=this.Hh()||0,c=this.wA(c),
c=this.hH(c,a);this.Ne(c,b,this.Pf.cn)},vM:function(){var a=this.yA(this.options.step);null!=this.options.min&&(a=Math.max(a,this.yA(this.options.min)));return a},yA:function(a){a=a.toString();var b=a.indexOf(".");return-1===b?0:a.length-b-1},hH:function(a,b){var c,e,h=this.options,g=this.vM();e=null!=h.min?h.min:0;c=a-e;var k=Math.round(c/h.step)*h.step,k=parseFloat(k.toFixed(g));k!==c?(c=0>b?Math.ceil(c/h.step)*h.step:Math.floor(c/h.step)*h.step,c=e+c+b):c=a+b;c=parseFloat(c.toFixed(g));return null!=
h.min&&c<h.min?h.min:null!=h.max&&c>h.max?(e=Math.floor((h.max-e)/h.step)*h.step+e,e=parseFloat(e.toFixed(g))):c},Sl:function(){this.wE&&(clearTimeout(this.ef),this.wE=!1)},lC:function(){var a=this.Hh()||0,b=this.options.min,c=this.options.max;if(this.Sm){var e=this.Sm.find(".oj-inputnumber-down").ojButton(),h=this.Sm.find(".oj-inputnumber-up").ojButton();this.options.disabled?(e.ojButton("disable"),h.ojButton("disable")):null!=c&&a>=c?(e.ojButton("enable"),h.ojButton("disable")):(null!=b&&a<=b?e.ojButton("disable"):
e.ojButton("enable"),h.ojButton("enable"))}},ex:function(a){this.Sl();this.previous!==this.element.val()&&this.Ne(this.element.val(),a)},Tx:function(a){this.Hz[b.Sb.VALIDATOR_TYPE_NUMBERRANGE]=b.R.vg(b.Sb.VALIDATOR_TYPE_NUMBERRANGE).createValidator(a)},er:function(a){return null!==a?+a:a},ap:function(a){if(null===a)return a;a="string"===typeof a&&""!==a?+a:parseFloat(a);return isNaN(a)?(b.F.error("min or max or step is not a number"),null):a},vA:function(a){if(null===a)return 1;a=this.ap(a);if(null===
a||0>=a)a=1;return a},Ll:function(a,b){this.qf.hasOwnProperty(a)&&this.widget().toggleClass(this.qf[a],!!b)},NA:function(){var a=this.er(this.options.value),b=this.element.val();this.element.attr({"aria-valuemin":this.options.min,"aria-valuemax":this.options.max,"aria-valuenow":a});this.Cq(""+a,b)||this.element.attr({"aria-valuetext":b})},WB:function(a,b){this.Nj();b?this.rt((a||1)*this.options.step):this.rt((a||1)*-this.options.step);this.Sl()},widget:o_c("Sm")})});
//# sourceMappingURL=oj-modular.map