define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(b,e){b.ta("oj.ojInputNumber",e.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{converter:b.R.bh(b.gf.CONVERTER_TYPE_NUMBER).createConverter(),max:void 0,min:void 0,readOnly:null,placeholder:void 0,step:void 0},Aa:{BG:"tooltipDecrement",DG:"tooltipIncrement"},Ic:function(){this._super();this.Mk();this._on(this.Pe);this._on(this.window,{beforeunload:function(){this.element.removeAttr("autocomplete")}});
this.element.removeAttr("pattern");this.uz={}},xh:function(){this._super();this._setOption("step",this.options.step);"boolean"!==typeof this.options.readOnly?this.options.readOnly=!!this.element.prop("readonly"):this.element.prop("readonly",this.options.readOnly);this.AA();this.$B()},Mf:function(){this._super();null==this.options.value&&(this.options.value=""!==this.element.val()?this.element.val():null);this.options.value=this.yx(this.options.value);var a=this;e.each(["min","max","step"],function(b,
c){void 0===a.options[c]&&(a.options[c]=a.element.attr(c),null==a.options[c]&&(a.options[c]="step"===c?1:null));null!=a.options[c]&&(a.options[c]="step"===c?a.iA(a.options[c]):a.wl(a.options[c]))})},bn:function(){var a=this._superApply(arguments),b=null!=this.options.min?this.options.min:void 0,c=null!=this.options.max?this.options.max:void 0,f={};if(null!=b||null!=c)f={min:b,max:c,converter:this.Bd()},this.Hx(f);return e.extend(this.uz,a)},Pe:{keydown:function(a){a.keyCode===e.ui.keyCode.ENTER?(this.Rw(a),
a.preventDefault()):this.Fj()&&this.bi(a)&&a.preventDefault()},keyup:function(a){this.Gl(a)},focus:function(){this.previous=this.element.val()},blur:function(a){this.wt?delete this.wt:this.Rw(a)},"mousedown .oj-inputnumber-button":function(a){function b(){this.element[0]!==this.document[0].activeElement&&(this.element.focus(),this.previous=c,this._delay(function(){this.previous=c}))}var c;c=this.element[0]===this.document[0].activeElement?this.previous:this.element.val();a.preventDefault();b.call(this);
this.wt=!0;this._delay(function(){delete this.wt;b.call(this)});this.Fj();this.Dl(null,e(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a)},"mouseup .oj-inputnumber-button":function(a){this.Gl(a)},"mouseenter .oj-inputnumber-button":function(a){e(a.currentTarget).hasClass("oj-active")&&(this.Fj(),this.Dl(null,e(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a))},"mouseleave .oj-inputnumber-button":function(a){this.Gl(a)}},Mk:function(){var a=this.Jm=this.element.addClass("oj-inputnumber-input").attr("autocomplete",
"off").wrap("\x3cspan class\x3d'oj-inputnumber oj-component'\x3e\x3c/span\x3e").parent().append("\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/a\x3e\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/a\x3e");this.saveType=this.element.prop("type");this.element.attr("type","text");var b=this.q(this.Aa.DG),c=this.q(this.Aa.BG);a.find(".oj-inputnumber-up").ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-up-icon"},label:b});a.find(".oj-inputnumber-down").ojButton({display:"icons",
icons:{start:"oj-component-icon oj-inputnumber-down-icon"},label:c});this.buttons=a.find(".oj-inputnumber-button").attr("tabIndex","-1").attr("aria-hidden",!0);this.options.disabled&&this.disable();this.options.readOnly&&this._setOption("readOnly",!0)},bi:function(a){var b=e.ui.keyCode;switch(a.keyCode){case b.UP:return this.Dl(null,1,a),!0;case b.DOWN:return this.Dl(null,-1,a),!0}return!1},QR:o_d("\x3cspan class\x3d'oj-inputnumber oj-component'\x3e\x3c/span\x3e"),YQ:o_d("\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/a\x3e\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/a\x3e"),
Fj:function(){return this.hE=!0},Dl:function(a,b,c){a=a||500;clearTimeout(this.ef);this.ef=this._delay(function(){this.Dl(40,b,c)},a);this.et(b*this.options.step,c)},et:function(a,b){var c=this.Ah()||0,c=this.jA(c),c=this.TG(c,a);this.Ne(c,b,this.Nf.Um)},aM:function(){var a=this.lA(this.options.step);null!=this.options.min&&(a=Math.max(a,this.lA(this.options.min)));return a},lA:function(a){a=a.toString();var b=a.indexOf(".");return-1===b?0:a.length-b-1},TG:function(a,b){var c,e,h=this.options,g=this.aM();
e=null!=h.min?h.min:0;c=a-e;var k=Math.round(c/h.step)*h.step,k=parseFloat(k.toFixed(g));k!==c?(c=0>b?Math.ceil(c/h.step)*h.step:Math.floor(c/h.step)*h.step,c=e+c+b):c=a+b;c=parseFloat(c.toFixed(g));return null!=h.min&&c<h.min?h.min:null!=h.max&&c>h.max?(e=Math.floor((h.max-e)/h.step)*h.step+e,e=parseFloat(e.toFixed(g))):c},Gl:function(){this.hE&&(clearTimeout(this.ef),this.hE=!1)},$B:function(){var a=this.Ah()||0,b=this.options.min,c=this.options.max;if(this.Jm){var e=this.Jm.find(".oj-inputnumber-down").ojButton(),
h=this.Jm.find(".oj-inputnumber-up").ojButton();this.options.disabled?(e.ojButton("disable"),h.ojButton("disable")):null!=c&&a>=c?(e.ojButton("enable"),h.ojButton("disable")):(null!=b&&a<=b?e.ojButton("disable"):e.ojButton("enable"),h.ojButton("enable"))}},Rw:function(a){this.Gl();this.previous!==this.element.val()&&this.Ne(this.element.val(),a)},_setOption:function(a,b){"value"===a&&(b=this.yx(b));"max"!==a&&"min"!==a||"string"!==typeof b||(b=this.wl(b));"step"===a&&(b=this.iA(b));this._super(a,
b);"disabled"===a&&(b?this.element.prop("disabled",!0):this.element.prop("disabled",!1));"readOnly"===a&&(b?this.element.prop("readonly",!0):this.element.prop("readonly",!1))},option:function(a,b){var c=this._superApply(arguments);if("max"===a||"min"===a||"object"===typeof a&&(void 0!==a.min||void 0!==a.max)){var e=void 0,h=void 0;"max"===a?h=null!=b?b:void 0:"min"===a?e=null!=b?b:void 0:(void 0!==a.max&&(h=null!=a.max?a.max:void 0),void 0!==a.min&&(e=null!=a.min?a.min:void 0));e={min:e,max:h,converter:this.Bd()};
this.Hx(e);this.vk()}return c},Hx:function(a){this.uz[b.Rb.VALIDATOR_TYPE_NUMBERRANGE]=b.R.rg(b.Rb.VALIDATOR_TYPE_NUMBERRANGE).createValidator(a)},yx:function(a){if(null!==a)return+a},wl:function(a){if(null===a)return a;a="string"===typeof a&&""!==a?+a:parseFloat(a);return isNaN(a)?(b.F.error("min or max or step is not a number"),null):a},iA:function(a){if(null===a)return 1;a=this.wl(a);if(null===a||0>=a)a=1;return a},AA:function(){var a=this.wl(this.options.value),b=this.element.val();this.element.attr({"aria-valuemin":this.options.min,
"aria-valuemax":this.options.max,"aria-valuenow":a});this.sq(""+a,b)||this.element.attr({"aria-valuetext":b})},mq:function(a,b){this._super(a,b);"value"!==a&&"max"!==a&&"min"!==a||this.AA();this.$B()},_GetDefaultStyleClass:o_d("oj-inputnumber"),_destroy:function(){this.element.removeClass("oj-inputnumber-input").prop("disabled",!1).removeAttr("autocomplete").removeAttr("aria-valuemin").removeAttr("aria-valuemax").removeAttr("aria-valuenow").removeAttr("aria-valuetext").removeAttr("aria-disabled");
this.element.attr("type",this.saveType);this._super();this._off(this.element,"keydown keyup focus blur mousedown mouseup mouseenter mouseleave");this.Jm.replaceWith(this.element);clearTimeout(this.ef)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-inputnumber-up"===a?this.widget().find(".oj-inputnumber-up")[0]:"oj-inputnumber-down"===a?this.widget().find(".oj-inputnumber-down")[0]:"oj-inputnumber-input"===a?this.widget().find(".oj-inputnumber-input")[0]:
null},pv:function(){return!this._super()||this.options.readOnly?!1:!0},stepUp:function(a){this.KB(a,!0)},stepDown:function(a){this.KB(a,!1)},KB:function(a,b){this.Fj();b?this.et((a||1)*this.options.step):this.et((a||1)*-this.options.step);this.Gl()},widget:o_c("Jm")})});
//# sourceMappingURL=oj-modular.map