define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){(function(){b.ta("oj.ojMenu",e.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cul\x3e",delay:300,role:"menu",widgetEventPrefix:"oj",vn:"ojMenuClickAwayHandler",options:{menuPosition:{my:"left top",at:"left bottom"},menuSelector:"ul",submenuPosition:{my:"left top",at:"right top"},beforeShow:null,blur:null,focus:null,select:null},_create:function(){this.$l=this.element;this.Bu=!1;this.element.uniqueId().addClass("oj-menu oj-component").toggleClass("oj-menu-icons",
!!this.element.find(".oj-component-icon").length).attr({role:this.role,tabIndex:"0"});this._on(!0,{"mousedown .oj-menu-item":function(a){this.options.disabled&&a.preventDefault()},click:function(a){this.options.disabled&&a.preventDefault()},keydown:function(a){this.options.disabled&&a.keyCode===e.ui.keyCode.ESCAPE&&this.Xa&&this.Jr(a)}});this.options.disabled&&this.element.addClass("oj-disabled").attr("aria-disabled","true");this._on({"mousedown .oj-menu-item \x3e a":function(a){a.preventDefault()},
"click .oj-disabled \x3e a":function(a){a.preventDefault()},click:function(){this.Bu=!1},"click .oj-menu-item:has(a)":function(a){var b=e(a.target).closest(".oj-menu-item");!this.Bu&&b.not(".oj-disabled").length&&(this.Bu=!0,this.$&&this.$.closest(b).length&&this.$.get(0)!=b.get(0)||(b.has(".oj-menu").length?this.expand(a):(this.select(a),this.element.is(":focus")||(this.element.trigger("focus",[!0]),this.$&&1===this.$.parents(".oj-menu").length&&clearTimeout(this.ef)))))},"mouseenter .oj-menu-item":function(a){var b=
e(a.currentTarget);b.siblings().children(".oj-active").removeClass("oj-active");this.focus(a,b)},mouseleave:this.collapseAll,"mouseleave .oj-menu":this.collapseAll,focus:function(a,b){var f=this.$||this.element.children(".oj-menu-item").eq(0);b||this.focus(a,f)},keydown:this.ii,keyup:function(a){if(a.keyCode==e.ui.keyCode.ENTER||a.keyCode==e.ui.keyCode.SPACE)this.Dn=!1}});this.mb();this.TM();this._super()},TM:function(){var b=this.document.data(this.vn);b||(b=function(b){if("focus"===b.type||"mousedown"===
b.type||93==b.which||121==b.which&&b.shiftKey||93==b.keyCode){var d=a.slice(0,a.length);e.each(d,function(a,d){e(b.target).closest(d.element).length||"keydown"!==b.type&&("mousedown"!==b.type||3!==b.which)&&e(b.target).closest(d.Xa).length||(d.collapseAll(b),d.Xa&&d.Cn(b))})}},this.document.data(this.vn,b),this.document[0].addEventListener("keydown",b,!0),this.document[0].addEventListener("mousedown",b,!0),this.document[0].addEventListener("focus",b,!0))},qO:function(){var a=this.document.data(this.vn);
a&&1===e(":oj-menu").length&&(this.document[0].removeEventListener("keydown",a,!0),this.document[0].removeEventListener("mousedown",a,!0),this.document[0].removeEventListener("focus",a,!0),this.document.removeData(this.vn))},_destroy:function(){this.element.removeAttr("aria-activedescendant").find(".oj-menu").addBack().removeClass("oj-menu oj-component oj-menu-icons").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();
this.element.find(".oj-menu-item").removeClass("oj-menu-item").removeAttr("role").children("a").removeAttr("aria-disabled").removeUniqueId().removeClass("oj-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var a=e(this);a.data("oj-ojMenu-submenu-icon")&&a.remove()});this.element.find("a").removeAttr("aria-expanded");this.element.find(".oj-menu-divider").removeClass("oj-menu-divider").removeAttr("role");this.qO();0<=a.indexOf(this)&&a.splice(a.indexOf(this),
1)},ii:function(a){function b(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26")}var f,h,g,k,l=!0;switch(a.keyCode){case e.ui.keyCode.HOME:this.Xo("first","first",a);break;case e.ui.keyCode.END:this.Xo("last","last",a);break;case e.ui.keyCode.UP:this.previous(a);break;case e.ui.keyCode.DOWN:this.next(a);break;case e.ui.keyCode.LEFT:case e.ui.keyCode.RIGHT:a.keyCode===e.ui.keyCode.RIGHT^this.Am?this.$&&!this.$.is(".oj-disabled")&&this.expand(a):this.collapse(a);break;case e.ui.keyCode.ENTER:case e.ui.keyCode.SPACE:this.Eg(a);
this.Dn=!0;var m=this;setTimeout(function(){m.Dn=!1},100);break;case e.ui.keyCode.ESCAPE:this.Xa?(h=this.element.attr("aria-activedescendant"),g="#"+this.element.attr("id")+"\x3e*\x3ea",h&&!e("#"+h).is(g)?this.collapse(a):this.Jr(a)):this.collapse(a);break;default:l=!1,f=this.Sp||"",h=String.fromCharCode(a.keyCode),g=!1,clearTimeout(this.pP),h===f?g=!0:h=f+h,k=RegExp("^"+b(h),"i"),f=this.$l.children(".oj-menu-item").filter(function(){return k.test(e(this).children("a").text())}),f=g&&-1!==f.index(this.$.next())?
this.$.nextAll(".oj-menu-item"):f,f.length||(h=String.fromCharCode(a.keyCode),k=RegExp("^"+b(h),"i"),f=this.$l.children(".oj-menu-item").filter(function(){return k.test(e(this).children("a").text())})),f.length?(this.focus(a,f),1<f.length?(this.Sp=h,this.pP=this._delay(function(){delete this.Sp},1E3)):delete this.Sp):delete this.Sp}l&&a.preventDefault()},Eg:function(a){this.$.is(".oj-disabled")||(this.$.children("a[aria-haspopup\x3d'true']").length?this.expand(a):this.select(a))},refresh:function(){this._super();
this.mb()},mb:function(){this.Am="rtl"===this.xc();var a=this,b=this.element.find(this.options.menuSelector);b.filter(":not(.oj-menu)").addClass("oj-menu oj-component").hide().attr({role:this.role,"aria-hidden":"true"}).each(function(){var b=e(this),c=a.gs(b),g=e("\x3cspan\x3e");g.addClass("oj-menu-submenu-icon oj-component-icon").data("oj-ojMenu-submenu-icon",!0);c.attr("aria-haspopup","true").attr("aria-expanded","false").prepend(g);c=c.attr("id");b.attr("aria-labelledby",c)});b=b.add(this.element).children();
b.filter(".oj-menu-divider").has("a").removeClass("oj-menu-divider oj-menu-item").removeAttr("role");b.filter(":not(.oj-menu-item):has(a)").addClass("oj-menu-item").attr("role","presentation").children("a").uniqueId().attr({tabIndex:"-1",role:"menuitem"});b.filter(":not(.oj-menu-item)").each(function(){var a=e(this);/[^\-\u2014\u2013\s]/.test(a.text())||a.addClass("oj-menu-divider").attr("role","separator")});b.filter(".oj-disabled").children("a").attr("aria-disabled","true");b.filter(":not(.oj-disabled)").children("a").removeAttr("aria-disabled");
this.$&&!e.contains(this.element[0],this.$[0])&&this.blur()},gs:function(a){return a.prev("a")},fS:o_d("menuitem"),focus:function(a,b){var f;this.blur(a,a&&"focus"===a.type);this.$=b.first();f=this.$.children("a").addClass("oj-focus");this.role&&this.element.attr("aria-activedescendant",f.attr("id"));this.$.parent().closest(".oj-menu-item").children("a:first").addClass("oj-active");a&&"keydown"===a.type?this.Uk():this.ef=this._delay(function(){this.Uk()},this.delay);f=b.children(".oj-menu");f.length&&
(a&&/^mouse/.test(a.type)&&!this.$.hasClass("oj-disabled"))&&this.$N(f);this.$l=b.parent();this._trigger("focus",a,{item:b})},blur:function(a,b){b||clearTimeout(this.ef);this.$&&(this.$.children("a").removeClass("oj-focus"),this.$=null,this._trigger("blur",a,{item:this.$}))},Jr:function(a){this.Xa.focus();this.Cn(a)},Cn:function(b){this.element.hide().attr("aria-hidden","true");this.Xa=void 0;this._trigger("__dismiss",b,{});0<=a.indexOf(this)&&a.splice(a.indexOf(this),1)},show:function(b,c){this.uM||
(this.tM(),this.uM=!0);if(c&&c.launcher){var f=c.launcher;if(this._trigger("beforeShow",b,{launcher:f})){var f="string"===e.type(f)?e("#"+f):f,h=this.element[0],g=a.slice(0,a.length);e.each(g,function(a,c){c.element[0]!==h&&(c.collapseAll(b),c.Xa&&c.Cn(b))});g=e.extend({},this.options.menuPosition);null==g.of&&(g.of=b&&"contextmenu"===b.type?b:f);this.element.show().removeAttr("aria-hidden").position(g);((g="firstItem"===c.focus)||"menu"===c.focus)&&this.element.focus();g?this.focus(b,this.element.children().first()):
this.blur(b);this.Xa=f;a.push(this)}}},tM:function(){this.element.css({position:"absolute",zIndex:999})},$N:function(a){clearTimeout(this.ef);"true"===a.attr("aria-hidden")&&(this.ef=this._delay(function(){this.Uk();this.rA(a)},this.delay))},rA:function(b){var c=e.extend({of:this.$},this.options.submenuPosition);clearTimeout(this.ef);this.element.find(".oj-menu").not(b.parents(".oj-menu")).hide().attr("aria-hidden","true");b.show().removeAttr("aria-hidden").position(c);this.gs(b).attr("aria-expanded",
"true");!this.Xa&&0>a.indexOf(this)&&a.push(this)},collapseAll:function(a,b){this.Lx(a,b,this.delay)},Lx:function(a,b,f){function h(){var f=b?g.element:e(a&&a.target).closest(g.element.find(".oj-menu"));f.length||(f=g.element);g.Uk(f);g.blur(a);g.$l=f}clearTimeout(this.ef);var g=this;f?this.ef=this._delay(h,f):h()},Uk:function(b){b||(b=this.$?this.$.parent():this.element);var c=b.find(".oj-menu");c.hide().attr("aria-hidden","true");this.gs(c).attr("aria-expanded","false");b.find("a.oj-active").removeClass("oj-active");
this.Xa||0<=a.indexOf(this)&&b===this.element&&a.splice(a.indexOf(this),1)},collapse:function(a){var b=this.$&&this.$.parent().closest(".oj-menu-item",this.element);b&&b.length&&(this.Uk(),this.focus(a,b))},expand:function(a){var b=this.$&&this.$.children(".oj-menu ").children(".oj-menu-item").first();b&&b.length&&(this.rA(b.parent()),this._delay(function(){this.focus(a,b)}))},next:function(a){this.Xo("next","first",a)},previous:function(a){this.Xo("prev","last",a)},aS:function(){return this.$&&!this.$.prevAll(".oj-menu-item").length},
cS:function(){return this.$&&!this.$.nextAll(".oj-menu-item").length},Xo:function(a,b,f){var e;this.$&&(e="first"===a||"last"===a?this.$["first"===a?"prevAll":"nextAll"](".oj-menu-item").eq(-1):this.$[a+"All"](".oj-menu-item").eq(0));e&&e.length&&this.$||(e=this.$l.children(".oj-menu-item")[b]());this.focus(f,e)},select:function(a){if(!this.$&&a&&a.target){var b=e(a.target).closest(".oj-menu-item");b.closest(this.element).length&&(this.$=b)}this.$&&(b={item:this.$},this.$.has(".oj-menu").length||
this.Lx(a,!0),this.Xa&&(b.item.children(this.options.menuSelector).length||this.Jr(a)),this._trigger("select",a,b))}});var a=[]})()});
//# sourceMappingURL=oj-modular.map