define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojmodel","ojs/ojdatacollection-common"],function(b,e){(function(){b.ta("oj.ojPagingControl",e.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{data:null,pageSize:25,pageOptions:{layout:["auto"],maxPageLinks:6},loadMoreOptions:{maxCount:500},mode:"page"},Aa:{DF:"labelAccPaging",yF:"labelAccNavFirstPage",zF:"labelAccNavLastPage",AF:"labelAccNavNextPage",CF:"labelAccNavPreviousPage",BF:"labelAccNavPage",
EF:"labelLoadMore",FF:"labelNavInputPage",GF:"labelNavInputPageMax",HF:"labelNavInputPageSummary",Ov:"msgItemRange",SF:"msgItemRangeUnknown",wG:"tipNavInputPage",zG:"tipNavPageLink",yG:"tipNavNextPage",AG:"tipNavPreviousPage",vG:"tipNavFirstPage",xG:"tipNavLastPage",iF:"pageInvalid.summary",hF:"pageInvalid.detail",sv:"dataInvalidType.summary",rv:"dataInvalidType.detail",gF:"maxPageLinksInvalid.summary",fF:"maxPageLinksInvalid.detail"},Ra:{tq:"oj-component",$p:"oj-active",yh:"oj-clickable-icon",Sb:"oj-disabled",
kd:"oj-enabled",Ke:"oj-focus",dn:"oj-hover",Db:"oj-selected"},la:{XF:"oj-pagingcontrol",Rv:"oj-pagingcontrol-acc-label",Sv:"oj-pagingcontrol-content",Tv:"oj-pagingcontrol-loadmore",Uv:"oj-pagingcontrol-loadmore-link",Vv:"oj-pagingcontrol-loadmore-range",Xv:"oj-pagingcontrol-nav",Wv:"oj-pagingcontrol-nav-arrow-section",hG:"oj-pagingcontrol-nav-page",gG:"oj-pagingcontrol-nav-page-acc-label",aG:"oj-pagingcontrol-nav-label",$v:"oj-pagingcontrol-nav-input-section",Zv:"oj-pagingcontrol-nav-input",$F:"oj-pagingcontrol-nav-input-max",
aw:"oj-pagingcontrol-nav-input-summary",fG:"oj-pagingcontrol-nav-pages-section",dw:"oj-pagingcontrol-nav-pages-links",Yv:"oj-pagingcontrol-nav-first",YF:"oj-pagingcontrol-nav-first-acc-label",ew:"oj-pagingcontrol-nav-previous",iG:"oj-pagingcontrol-nav-previous-acc-label",cw:"oj-pagingcontrol-nav-next",dG:"oj-pagingcontrol-nav-next-acc-label",bw:"oj-pagingcontrol-nav-last",bG:"oj-pagingcontrol-nav-last-acc-label",ZF:"oj-pagingcontrol-nav-first-icon",jG:"oj-pagingcontrol-nav-previous-icon",eG:"oj-pagingcontrol-nav-next-icon",
cG:"oj-pagingcontrol-nav-last-icon",Dh:"oj-component-icon",Le:"oj-helper-hidden-accessible"},JQ:"data-oj-pagenum",Od:"enabled",Qv:"disabled",Nv:{Lv:"loadMore",SQ:"page"},ke:{wh:"auto",sF:"input",kG:"rangeText",WF:"pages",Pv:"nav"},firstPage:function(){var a=this.Va();if(null!=a){try{this.S=0,a.fetch({startIndex:0})}catch(b){return!1}return!0}return!1},previousPage:function(){var a=this.Va();if(null!=a){var b=this.Vf();try{this.S=this.to(b-1),a.fetch({startIndex:this.S})}catch(c){return!1}return!0}return!1},
nextPage:function(){var a=this.Va();if(null!=a){var b=this.Vf();try{this.S=this.to(b+1),a.fetch({startIndex:this.S})}catch(c){return!1}return!0}return!1},lastPage:function(){var a=this.Va();if(null!=a){try{this.S=this.to(this.Vh()),a.fetch({startIndex:this.S})}catch(b){return!1}return!0}return!1},page:function(a){try{this.S=this.to(a),this.Va().fetch({startIndex:this.S})}catch(b){return!1}return!0},loadNext:function(){if(null!=this.Va()){try{this.Va().next()}catch(a){return!1}return!0}return!1},refresh:function(){this._super();
this.Nb()},_init:function(){this._super();this.S=0;this.Bl();this.Nb()},_create:function(){this._super();this.Bl();this.Mk();this.Qs(this.Zk());this._on(this.Pe)},_destroy:o_a(),Mk:function(){var a=this.options;this.element.addClass(this.la.XF);this.element.addClass(this.Ra.tq);this.S=0;this.SH();this.YH();a.mode==this.Nv.Lv?(this.ZH(),this.$H(),this.Ex()):this.Fx();null!=this.Va()&&0==this.Va().size()&&(this.Va().setPageSize(a.pageSize),this.Va().fetch({startIndex:this.S}))},Pe:{"click .oj-pagingcontrol-loadmore-link":function(a){this.loadNext();
a.preventDefault()},"click .oj-pagingcontrol-nav-page":function(a){var b=e(a.target).attr("data-oj-pagenum");this.page(b);a.preventDefault()},"click .oj-pagingcontrol-nav-first":function(a){this.firstPage();a.preventDefault()},"click .oj-pagingcontrol-nav-previous":function(a){this.previousPage();a.preventDefault()},"click .oj-pagingcontrol-nav-next":function(a){this.nextPage();a.preventDefault()},"click .oj-pagingcontrol-nav-last":function(a){this.lastPage();a.preventDefault()},"change .oj-pagingcontrol-nav-input":function(a){try{var d=
parseInt(e(a.target).val(),10);this.page(d)}catch(c){throw a=this.q(this.Aa.iF),d=this.q(this.Aa.hF),new b.C(a,d,b.C.Ha.ERROR);}}},Nb:function(){if(this.options.mode==this.Nv.Lv){var a=this.Va(),b=this.al();null!=a&&a.size()==a.totalSize()?b.css("display","none"):(b.css("display",""),this.sM())}else this.tM()},_setOption:function(a,b){this._super(a,b);this.Nb()},AH:function(){this.Hq=null},BH:function(){this.Kq=this.Jq=this.Iq=null},Vf:function(){return 0==this.S?1:Math.ceil((this.S+1)/this.options.pageSize)},
Va:function(){if(!this.c&&null!=this.options.data){var a=this.options.data;if(a instanceof b.ob||a instanceof b.Ga)this.c=a;else{var a=this.q(this.Aa.sv),d=this.q(this.Aa.rv);throw new b.C(a,d,b.C.Ha.ERROR);}this.c.setPageSize(this.options.pageSize);this.kI=this.options.data}return this.c},Jy:function(){var a=this.Va(),b=this.q(this.Aa.Ov,{pageFrom:this.S,pageTo:0,pageTotal:0});null!=a&&(b=-1!=a.totalSize()?this.q(this.Aa.Ov,{pageFrom:this.S+1,pageTo:this.S+a.size(),pageTotal:a.totalSize()}):this.q(this.Aa.SF,
{pageFrom:this.S+1,pageTo:this.S+a.size()}));return b},oJ:function(){return this.options.pageOptions.maxPageLinks},to:function(a){var b=(a-1)*this.options.pageSize,c=this.Vh();if(0>b)throw"Value must be greater than 0";if(0<c&&a>c)throw"Value cannot be greater than the total number of pages";return b},Vh:function(){var a=this.Va(),b=0;null!=a&&(b=a.totalSize());return-1==b?-1:Math.ceil(b/this.options.pageSize)},bs:function(){this.Nb()},sM:function(){var a=this.vJ();a[0].parentNode.removeChild(a[0]);
this.Ex();this.AH()},tM:function(){var a=this.options.pageOptions.layout;this.$k().empty();this.BH();this.Fx();this.uM();if(-1<e.inArray(this.ke.wh,a)){var a=this.element.width(),b=this.Py(),c=this.wJ(),f=this.yJ(),h=this.xJ(),c=b[0].offsetWidth+c[0].offsetWidth;c>a?c-f.width()<=a?f.css("display","none"):c-f.width()-h.width()<=a?(f.css("display","none"),h.css("display","none")):(f.css("display","none"),h.css("display","none"),b.css("display","none")):0<c&&(f.css("display",""),h.css("display",""),
b.css("display",""))}},uM:function(){var a=this.Py(),b=a.children("."+this.la.Yv);b&&0<b.length&&(b=e(b[0]),1==this.Vf()?(b.addClass(this.Ra.Sb),b.removeClass(this.Ra.kd),b.attr("tabindex","-1")):(b.addClass(this.Ra.kd),b.removeClass(this.Ra.Sb),b.attr("tabindex","0")));(b=a.children("."+this.la.ew))&&0<b.length&&(b=e(b[0]),1==this.Vf()?(b.addClass(this.Ra.Sb),b.removeClass(this.Ra.kd),b.attr("tabindex","-1")):(b.addClass(this.Ra.kd),b.removeClass(this.Ra.Sb),b.attr("tabindex","0")));(b=a.children("."+
this.la.bw))&&0<b.length&&(b=e(b[0]),this.Vf()==this.Vh()?(b.addClass(this.Ra.Sb),b.removeClass(this.Ra.kd),b.attr("tabindex","-1")):(b.addClass(this.Ra.kd),b.removeClass(this.Ra.Sb),b.attr("tabindex","0")));(a=a.children("."+this.la.cw))&&0<a.length&&(a=e(a[0]),this.Vf()==this.Vh()?(a.addClass(this.Ra.Sb),a.removeClass(this.Ra.kd),a.attr("tabindex","-1")):(a.addClass(this.Ra.kd),a.removeClass(this.Ra.Sb),a.attr("tabindex","0")))},Bl:function(){var a=this.Va();if(null!=a){this.dc=[];this.dc.push({eventType:b.ob.l.SYNC,
eventHandler:this.bs.bind(this)});var d;for(d=0;d<this.dc.length;d++)a.on(this.dc[d].eventType,this.dc[d].eventHandler)}},Qs:function(a){if(!this.ss){var d=this;b.xa.$g(a[0],function(){d.Nb()});this.ss=!0}},Vi:function(a,b){var c=e(document.createElement("span"));c.addClass(b);c.addClass(this.la.Le);c.append(a);return c},SH:function(){var a=this.Zk(),b=this.q(this.Aa.DF),b=this.Vi(b,this.la.Rv),c=this.element.attr("id")+"_oj_pgCtrl_acc_label";b.attr("id",c);a.append(b);return b},WH:function(){var a=
this.q(this.Aa.BF);return this.Vi(a,this.la.gG)},TH:function(){var a=this.q(this.Aa.yF);return this.Vi(a,this.la.YF)},UH:function(){var a=this.q(this.Aa.zF);return this.Vi(a,this.la.bG)},VH:function(){var a=this.q(this.Aa.AF);return this.Vi(a,this.la.dG)},XH:function(){var a=this.q(this.Aa.CF);return this.Vi(a,this.la.iG)},YH:function(){var a=this.Zk(),b=e(document.createElement("div"));b.addClass(this.la.Sv);var c=this.uJ().attr("id");b.attr("role","navigation");b.attr("aria-labelledby",c);a.append(b);
return b},ZH:function(){var a=this.$k(),b=e(document.createElement("div"));b.addClass(this.la.Tv);a.append(b);return b},$H:function(){var a=this.al(),b=e(document.createElement("a"));b.addClass(this.la.Uv);var c=this.q(this.Aa.EF);b.append(c);b.attr("tabindex","0");b.attr("href","#");a.append(b);return b},Ex:function(){this.Va();var a=this.al(),b=e(document.createElement("span"));b.addClass(this.la.Vv);var c=this.Jy();b.append(c);a.append(b);return b},Fx:function(){var a=this.options.pageOptions.layout;
null==a&&(a=[this.ke.wh]);var b=this.$k(),c=e(document.createElement("div"));c.addClass(this.la.Xv);b.append(c);if(-1!=e.inArray(this.ke.wh,a)||-1!=e.inArray(this.ke.sF,a)){b=e(document.createElement("div"));b.addClass(this.la.$v);c.append(b);var f=e(document.createElement("label"));f.addClass(this.la.aG);var h=this.q(this.Aa.FF);f.append(h);b.append(f);h=e(document.createElement("input"));h.addClass(this.la.Zv);var g=this.q(this.Aa.wG);this._focusable(this.element);h.attr("title",g);h.attr("tabindex",
"0");h.val(this.Vf());f.append(h);0<this.Vh()&&(f=e(document.createElement("span")),f.addClass(this.la.$F),h=this.q(this.Aa.GF,{pageMax:this.Vh()}),f.append(h),b.append(f));if(-1!=e.inArray(this.ke.wh,a)||-1!=e.inArray(this.ke.kG,a))f=e(document.createElement("span")),f.addClass(this.la.aw),h=this.Jy(),h=this.q(this.Aa.HF,{pageSummary:h}),f.append(h),b.append(f)}b=e(document.createElement("div"));b.addClass(this.la.Wv);c.append(b);if(-1!=e.inArray(this.ke.wh,a)||-1!=e.inArray(this.ke.Pv,a))f=e(document.createElement("a")),
f.addClass(this.la.Yv),f.addClass(this.la.ZF),f.addClass(this.la.Dh),f.addClass(this.Ra.yh),f.addClass(this.Ra.Sb),h=this.q(this.Aa.vG),this._hoverable(f),this._focusable(f),f.attr("title",h),f.attr("tabindex","0"),f.attr("href","#"),h=this.TH(),f.append(h),b.append(f),f=e(document.createElement("a")),f.addClass(this.la.ew),f.addClass(this.la.jG),f.addClass(this.la.Dh),f.addClass(this.Ra.yh),f.addClass(this.Ra.Sb),h=this.q(this.Aa.AG),this._hoverable(f),this._focusable(f),f.attr("title",h),f.attr("tabindex",
"0"),f.attr("href","#"),h=this.XH(),f.append(h),b.append(f);if(-1!=e.inArray(this.ke.wh,a)||-1!=e.inArray(this.ke.WF,a))f=e(document.createElement("div")),f.addClass(this.la.fG),b.append(f),this.aI(f,this.oJ());if(-1!=e.inArray(this.ke.wh,a)||-1!=e.inArray(this.ke.Pv,a))a=e(document.createElement("a")),a.addClass(this.la.cw),a.addClass(this.la.eG),a.addClass(this.la.Dh),a.addClass(this.Ra.yh),a.addClass(this.Ra.Sb),f=this.q(this.Aa.yG),this._hoverable(a),this._focusable(a),a.attr("title",f),a.attr("tabindex",
"0"),a.attr("href","#"),f=this.VH(),a.append(f),b.append(a),a=e(document.createElement("a")),a.addClass(this.la.bw),a.addClass(this.la.cG),a.addClass(this.la.Dh),a.addClass(this.Ra.yh),a.addClass(this.Ra.Sb),f=this.q(this.Aa.xG),this._hoverable(a),this._focusable(a),a.attr("title",f),a.attr("tabindex","0"),a.attr("href","#"),f=this.UH(),a.append(f),b.append(a);return c},aI:function(a,d){if(5>d){var c=this.q(this.Aa.gF),f=this.q(this.Aa.fF);throw new b.C(c,f,b.C.Ha.ERROR);}c=e(document.createElement("div"));
c.addClass(this.la.dw);a.append(c);var f=this.Vh(),h=this.Vf(),g=d,k=[];if(1<=h){if(-1!=f&&f<=g)for(g=k[0]=1;g<f;g++)k[g]=g+1;else{k.push(1);1!=h&&k.push(h);h!=f&&-1!=f&&k.push(f);var g=g-k.length,l=h-1,m=1;if(h==f||h==f-1)m=0;for(;g>m&&1<l;)k.push(l),l--,g--;h+=1;for(-1==f&&(g=1);0<g&&(h<=f||-1==f);)k.push(h),h++,g--}k.sort(function(a,b){return a-b});for(g=0;g<k.length;g++)h=k[g],this.ar(c,h),g!=k.length-1&&h!=k[g+1]-1&&this.ar(c,-1);-1==f&&this.ar(c,-1)}return c},ar:function(a,b){var c=this.Vf(),
f=null;-1==b?(f=e(document.createElement("span")),f.append("...")):(c==b?(f=e(document.createElement("div")),f.addClass(this.Ra.Db),f.addClass(this.Ra.$p),f.addClass(this.Ra.Sb),f.removeClass(this.Ra.kd)):(f=e(document.createElement("a")),f.removeClass(this.Ra.Db),f.removeClass(this.Ra.$p),f.removeClass(this.Ra.Sb),f.addClass(this.Ra.kd)),f.attr("data-oj-pagenum",b),f.addClass(this.la.hG),c=this.q(this.Aa.zG,{pageNum:b.toString()}),this._hoverable(f),this._focusable(f),f.attr("title",c),f.attr("tabindex",
"0"),f.attr("href","#"),c=this.WH(),f.append(c),f.append(b.toString()),this._hoverable(f));a.append(f);return f},uJ:function(){var a=this.Zk(),b=null;a&&(b=a.find("."+this.la.Rv))&&0<b.length&&(b=e(b.get(0)));return b},Zk:function(){return e(this.element)},$k:function(){if(!this.Sw){var a=this.Zk(),b=null;a&&(b=a.find("."+this.la.Sv))&&0<b.length&&(this.Sw=e(b.get(0)))}return this.Sw},al:function(){if(!this.Tw){var a=this.$k(),b=null;a&&(b=a.children("."+this.la.Tv))&&0<b.length&&(this.Tw=e(b.get(0)))}return this.Tw},
oR:function(){if(!this.Uw){var a=this.al(),b=null;a&&(b=a.children("."+this.la.Uv))&&0<b.length&&(this.Uw=e(b.get(0)))}return this.Uw},vJ:function(){if(!this.Hq){var a=this.al(),b=null;a&&(b=a.children("."+this.la.Vv))&&0<b.length&&(this.Hq=e(b.get(0)))}return this.Hq},bl:function(){if(!this.Iq){var a=this.$k(),b=null;a&&(b=a.children("."+this.la.Xv))&&0<b.length&&(this.Iq=e(b.get(0)))}return this.Iq},pR:function(){if(!this.Jq){var a=this.bl(),b=null;a&&(b=a.find("."+this.la.Zv))&&0<b.length&&(this.Jq=
e(b.get(0)))}return this.Jq},xJ:function(){if(!this.Kq){var a=this.bl(),b=null;a&&(b=a.find("."+this.la.aw))&&0<b.length&&(this.Kq=e(b.get(0)))}return this.Kq},yJ:function(){var a=this.bl(),b=null;a&&(b=a.find("."+this.la.dw))&&0<b.length&&(b=e(b.get(0)));return b},Py:function(){var a=this.bl(),b=null;a&&(b=a.find("."+this.la.Wv))&&0<b.length&&(b=e(b.get(0)));return b},wJ:function(){var a=this.bl(),b=null;a&&(b=a.find("."+this.la.$v))&&0<b.length&&(b=e(b.get(0)));return b}})})();b.ob=function(a){this.Ma=
a;this.Init()};o_("PagingDataSource",b.ob,b);b.a.fa(b.ob,b.Sc,"oj.PagingDataSource");b.ob.prototype.Init=function(){b.ob.j.Init.call(this)};b.a.b("PagingDataSource.prototype.Init",{Init:b.ob.prototype.Init});b.ob.prototype.fetch=function(){b.f.U()};b.a.b("PagingDataSource.prototype.fetch",{fetch:b.ob.prototype.fetch});b.ob.prototype.hasMore=function(){b.f.U();return!1};b.a.b("PagingDataSource.prototype.hasMore",{hasMore:b.ob.prototype.hasMore});b.ob.prototype.next=function(){b.f.U()};b.a.b("PagingDataSource.prototype.next",
{next:b.ob.prototype.next});b.ob.prototype.previous=function(){b.f.U()};b.a.b("PagingDataSource.prototype.previous",{previous:b.ob.prototype.previous});b.ob.prototype.setPageSize=function(){b.f.U()};b.ob.prototype.startIndex=function(){b.f.U();return 0};b.a.b("PagingDataSource.prototype.startIndex",{startIndex:b.ob.prototype.startIndex});b.ob.prototype.size=function(){b.f.U();return 0};b.a.b("PagingDataSource.prototype.size",{size:b.ob.prototype.size});b.ob.prototype.totalSize=function(){b.f.U();
return 0};b.a.b("PagingDataSource.prototype.totalSize",{totalSize:b.ob.prototype.totalSize});b.ob.l={SYNC:"sync"};o_("PagingDataSource.EventType",b.ob.l,b)});
//# sourceMappingURL=oj-modular.map