define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojmodel","ojs/ojdatacollection-common"],function(b,e){(function(){b.ta("oj.ojPagingControl",e.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{data:null,pageSize:25,pageOptions:{layout:["auto"],maxPageLinks:6},loadMoreOptions:{maxCount:500},mode:"page"},Aa:{RF:"labelAccPaging",MF:"labelAccNavFirstPage",NF:"labelAccNavLastPage",OF:"labelAccNavNextPage",QF:"labelAccNavPreviousPage",PF:"labelAccNavPage",
SF:"labelLoadMore",TF:"labelNavInputPage",UF:"labelNavInputPageMax",VF:"labelNavInputPageSummary",$v:"msgItemRange",eG:"msgItemRangeUnknown",JG:"tipNavInputPage",MG:"tipNavPageLink",LG:"tipNavNextPage",NG:"tipNavPreviousPage",IG:"tipNavFirstPage",KG:"tipNavLastPage",wF:"pageInvalid.summary",vF:"pageInvalid.detail",Ev:"dataInvalidType.summary",Dv:"dataInvalidType.detail",uF:"maxPageLinksInvalid.summary",tF:"maxPageLinksInvalid.detail"},Sa:{Dq:"oj-component",kq:"oj-active",Fh:"oj-clickable-icon",Tb:"oj-disabled",
md:"oj-enabled",Le:"oj-focus",nn:"oj-hover",Fb:"oj-selected"},la:{jG:"oj-pagingcontrol",cw:"oj-pagingcontrol-acc-label",dw:"oj-pagingcontrol-content",ew:"oj-pagingcontrol-loadmore",fw:"oj-pagingcontrol-loadmore-link",gw:"oj-pagingcontrol-loadmore-range",iw:"oj-pagingcontrol-nav",hw:"oj-pagingcontrol-nav-arrow-section",uG:"oj-pagingcontrol-nav-page",tG:"oj-pagingcontrol-nav-page-acc-label",nG:"oj-pagingcontrol-nav-label",lw:"oj-pagingcontrol-nav-input-section",kw:"oj-pagingcontrol-nav-input",mG:"oj-pagingcontrol-nav-input-max",
mw:"oj-pagingcontrol-nav-input-summary",sG:"oj-pagingcontrol-nav-pages-section",qw:"oj-pagingcontrol-nav-pages-links",jw:"oj-pagingcontrol-nav-first",kG:"oj-pagingcontrol-nav-first-acc-label",rw:"oj-pagingcontrol-nav-previous",vG:"oj-pagingcontrol-nav-previous-acc-label",pw:"oj-pagingcontrol-nav-next",qG:"oj-pagingcontrol-nav-next-acc-label",ow:"oj-pagingcontrol-nav-last",oG:"oj-pagingcontrol-nav-last-acc-label",lG:"oj-pagingcontrol-nav-first-icon",wG:"oj-pagingcontrol-nav-previous-icon",rG:"oj-pagingcontrol-nav-next-icon",
pG:"oj-pagingcontrol-nav-last-icon",Kh:"oj-component-icon",Me:"oj-helper-hidden-accessible"},dR:"data-oj-pagenum",Qd:"enabled",bw:"disabled",Zv:{Xv:"loadMore",mR:"page"},me:{Eh:"auto",GF:"input",xG:"rangeText",iG:"pages",aw:"nav"},firstPage:function(){var a=this.Wa();if(null!=a){try{this.S=0,a.fetch({startIndex:0})}catch(b){return!1}return!0}return!1},previousPage:function(){var a=this.Wa();if(null!=a){var b=this.Yf();try{this.S=this.Ao(b-1),a.fetch({startIndex:this.S})}catch(c){return!1}return!0}return!1},
nextPage:function(){var a=this.Wa();if(null!=a){var b=this.Yf();try{this.S=this.Ao(b+1),a.fetch({startIndex:this.S})}catch(c){return!1}return!0}return!1},lastPage:function(){var a=this.Wa();if(null!=a){try{this.S=this.Ao(this.ai()),a.fetch({startIndex:this.S})}catch(b){return!1}return!0}return!1},page:function(a){try{this.S=this.Ao(a),this.Wa().fetch({startIndex:this.S})}catch(b){return!1}return!0},loadNext:function(){if(null!=this.Wa()){try{this.Wa().next()}catch(a){return!1}return!0}return!1},refresh:function(){this._super();
this.Ob()},_init:function(){this._super();this.S=0;this.Nl();this.Ob()},_create:function(){this._super();this.Nl();this.Yk();this.ct(this.kl());this._on(this.Pe)},_destroy:o_a(),Yk:function(){var a=this.options;this.element.addClass(this.la.jG);this.element.addClass(this.Sa.Dq);this.S=0;this.hI();this.nI();a.mode==this.Zv.Xv?(this.oI(),this.pI(),this.Px()):this.Qx();null!=this.Wa()&&0==this.Wa().size()&&(this.Wa().setPageSize(a.pageSize),this.Wa().fetch({startIndex:this.S}))},Pe:{"click .oj-pagingcontrol-loadmore-link":function(a){this.loadNext();
a.preventDefault()},"click .oj-pagingcontrol-nav-page":function(a){var b=e(a.target).attr("data-oj-pagenum");this.page(b);a.preventDefault()},"click .oj-pagingcontrol-nav-first":function(a){this.firstPage();a.preventDefault()},"click .oj-pagingcontrol-nav-previous":function(a){this.previousPage();a.preventDefault()},"click .oj-pagingcontrol-nav-next":function(a){this.nextPage();a.preventDefault()},"click .oj-pagingcontrol-nav-last":function(a){this.lastPage();a.preventDefault()},"change .oj-pagingcontrol-nav-input":function(a){try{var d=
parseInt(e(a.target).val(),10);this.page(d)}catch(c){throw a=this.l(this.Aa.wF),d=this.l(this.Aa.vF),new b.C(a,d,b.C.Ja.ERROR);}}},Ob:function(){if(this.options.mode==this.Zv.Xv){var a=this.Wa(),b=this.ml();null!=a&&a.size()==a.totalSize()?b.css("display","none"):(b.css("display",""),this.LM())}else this.MM()},_setOption:function(a,b){this._super(a,b);this.Ob()},OH:function(){this.Rq=null},PH:function(){this.Uq=this.Tq=this.Sq=null},Yf:function(){return 0==this.S?1:Math.ceil((this.S+1)/this.options.pageSize)},
Wa:function(){if(!this.b&&null!=this.options.data){var a=this.options.data;if(a instanceof b.rb||a instanceof b.Ia)this.b=a;else{var a=this.l(this.Aa.Ev),d=this.l(this.Aa.Dv);throw new b.C(a,d,b.C.Ja.ERROR);}this.b.setPageSize(this.options.pageSize);this.AI=this.options.data}return this.b},Vy:function(){var a=this.Wa(),b=this.l(this.Aa.$v,{pageFrom:this.S,pageTo:0,pageTotal:0});null!=a&&(b=-1!=a.totalSize()?this.l(this.Aa.$v,{pageFrom:this.S+1,pageTo:this.S+a.size(),pageTotal:a.totalSize()}):this.l(this.Aa.eG,
{pageFrom:this.S+1,pageTo:this.S+a.size()}));return b},FJ:function(){return this.options.pageOptions.maxPageLinks},Ao:function(a){var b=(a-1)*this.options.pageSize,c=this.ai();if(0>b)throw"Value must be greater than 0";if(0<c&&a>c)throw"Value cannot be greater than the total number of pages";return b},ai:function(){var a=this.Wa(),b=0;null!=a&&(b=a.totalSize());return-1==b?-1:Math.ceil(b/this.options.pageSize)},ms:function(){this.Ob()},LM:function(){var a=this.MJ();a[0].parentNode.removeChild(a[0]);
this.Px();this.OH()},MM:function(){var a=this.options.pageOptions.layout;this.ll().empty();this.PH();this.Qx();this.NM();if(-1<e.inArray(this.me.Eh,a)){var a=this.element.width(),b=this.az(),c=this.NJ(),f=this.PJ(),h=this.OJ(),c=b[0].offsetWidth+c[0].offsetWidth;c>a?c-f.width()<=a?f.css("display","none"):c-f.width()-h.width()<=a?(f.css("display","none"),h.css("display","none")):(f.css("display","none"),h.css("display","none"),b.css("display","none")):0<c&&(f.css("display",""),h.css("display",""),
b.css("display",""))}},NM:function(){var a=this.az(),b=a.children("."+this.la.jw);b&&0<b.length&&(b=e(b[0]),1==this.Yf()?(b.addClass(this.Sa.Tb),b.removeClass(this.Sa.md),b.attr("tabindex","-1")):(b.addClass(this.Sa.md),b.removeClass(this.Sa.Tb),b.attr("tabindex","0")));(b=a.children("."+this.la.rw))&&0<b.length&&(b=e(b[0]),1==this.Yf()?(b.addClass(this.Sa.Tb),b.removeClass(this.Sa.md),b.attr("tabindex","-1")):(b.addClass(this.Sa.md),b.removeClass(this.Sa.Tb),b.attr("tabindex","0")));(b=a.children("."+
this.la.ow))&&0<b.length&&(b=e(b[0]),this.Yf()==this.ai()?(b.addClass(this.Sa.Tb),b.removeClass(this.Sa.md),b.attr("tabindex","-1")):(b.addClass(this.Sa.md),b.removeClass(this.Sa.Tb),b.attr("tabindex","0")));(a=a.children("."+this.la.pw))&&0<a.length&&(a=e(a[0]),this.Yf()==this.ai()?(a.addClass(this.Sa.Tb),a.removeClass(this.Sa.md),a.attr("tabindex","-1")):(a.addClass(this.Sa.md),a.removeClass(this.Sa.Tb),a.attr("tabindex","0")))},Nl:function(){var a=this.Wa();if(null!=a){this.ec=[];this.ec.push({eventType:b.rb.q.SYNC,
eventHandler:this.ms.bind(this)});var d;for(d=0;d<this.ec.length;d++)a.on(this.ec[d].eventType,this.ec[d].eventHandler)}},ct:function(a){if(!this.Cs){var d=this;b.xa.eh(a[0],function(){d.Ob()});this.Cs=!0}},dj:function(a,b){var c=e(document.createElement("span"));c.addClass(b);c.addClass(this.la.Me);c.append(a);return c},hI:function(){var a=this.kl(),b=this.l(this.Aa.RF),b=this.dj(b,this.la.cw),c=this.element.attr("id")+"_oj_pgCtrl_acc_label";b.attr("id",c);a.append(b);return b},lI:function(){var a=
this.l(this.Aa.PF);return this.dj(a,this.la.tG)},iI:function(){var a=this.l(this.Aa.MF);return this.dj(a,this.la.kG)},jI:function(){var a=this.l(this.Aa.NF);return this.dj(a,this.la.oG)},kI:function(){var a=this.l(this.Aa.OF);return this.dj(a,this.la.qG)},mI:function(){var a=this.l(this.Aa.QF);return this.dj(a,this.la.vG)},nI:function(){var a=this.kl(),b=e(document.createElement("div"));b.addClass(this.la.dw);var c=this.LJ().attr("id");b.attr("role","navigation");b.attr("aria-labelledby",c);a.append(b);
return b},oI:function(){var a=this.ll(),b=e(document.createElement("div"));b.addClass(this.la.ew);a.append(b);return b},pI:function(){var a=this.ml(),b=e(document.createElement("a"));b.addClass(this.la.fw);var c=this.l(this.Aa.SF);b.append(c);b.attr("tabindex","0");b.attr("href","#");a.append(b);return b},Px:function(){this.Wa();var a=this.ml(),b=e(document.createElement("span"));b.addClass(this.la.gw);var c=this.Vy();b.append(c);a.append(b);return b},Qx:function(){var a=this.options.pageOptions.layout;
null==a&&(a=[this.me.Eh]);var b=this.ll(),c=e(document.createElement("div"));c.addClass(this.la.iw);b.append(c);if(-1!=e.inArray(this.me.Eh,a)||-1!=e.inArray(this.me.GF,a)){b=e(document.createElement("div"));b.addClass(this.la.lw);c.append(b);var f=e(document.createElement("label"));f.addClass(this.la.nG);var h=this.l(this.Aa.TF);f.append(h);b.append(f);h=e(document.createElement("input"));h.addClass(this.la.kw);var g=this.l(this.Aa.JG);this._focusable(this.element);h.attr("title",g);h.attr("tabindex",
"0");h.val(this.Yf());f.append(h);0<this.ai()&&(f=e(document.createElement("span")),f.addClass(this.la.mG),h=this.l(this.Aa.UF,{pageMax:this.ai()}),f.append(h),b.append(f));if(-1!=e.inArray(this.me.Eh,a)||-1!=e.inArray(this.me.xG,a))f=e(document.createElement("span")),f.addClass(this.la.mw),h=this.Vy(),h=this.l(this.Aa.VF,{pageSummary:h}),f.append(h),b.append(f)}b=e(document.createElement("div"));b.addClass(this.la.hw);c.append(b);if(-1!=e.inArray(this.me.Eh,a)||-1!=e.inArray(this.me.aw,a))f=e(document.createElement("a")),
f.addClass(this.la.jw),f.addClass(this.la.lG),f.addClass(this.la.Kh),f.addClass(this.Sa.Fh),f.addClass(this.Sa.Tb),h=this.l(this.Aa.IG),this._hoverable(f),this._focusable(f),f.attr("title",h),f.attr("tabindex","0"),f.attr("href","#"),h=this.iI(),f.append(h),b.append(f),f=e(document.createElement("a")),f.addClass(this.la.rw),f.addClass(this.la.wG),f.addClass(this.la.Kh),f.addClass(this.Sa.Fh),f.addClass(this.Sa.Tb),h=this.l(this.Aa.NG),this._hoverable(f),this._focusable(f),f.attr("title",h),f.attr("tabindex",
"0"),f.attr("href","#"),h=this.mI(),f.append(h),b.append(f);if(-1!=e.inArray(this.me.Eh,a)||-1!=e.inArray(this.me.iG,a))f=e(document.createElement("div")),f.addClass(this.la.sG),b.append(f),this.qI(f,this.FJ());if(-1!=e.inArray(this.me.Eh,a)||-1!=e.inArray(this.me.aw,a))a=e(document.createElement("a")),a.addClass(this.la.pw),a.addClass(this.la.rG),a.addClass(this.la.Kh),a.addClass(this.Sa.Fh),a.addClass(this.Sa.Tb),f=this.l(this.Aa.LG),this._hoverable(a),this._focusable(a),a.attr("title",f),a.attr("tabindex",
"0"),a.attr("href","#"),f=this.kI(),a.append(f),b.append(a),a=e(document.createElement("a")),a.addClass(this.la.ow),a.addClass(this.la.pG),a.addClass(this.la.Kh),a.addClass(this.Sa.Fh),a.addClass(this.Sa.Tb),f=this.l(this.Aa.KG),this._hoverable(a),this._focusable(a),a.attr("title",f),a.attr("tabindex","0"),a.attr("href","#"),f=this.jI(),a.append(f),b.append(a);return c},qI:function(a,d){if(5>d){var c=this.l(this.Aa.uF),f=this.l(this.Aa.tF);throw new b.C(c,f,b.C.Ja.ERROR);}c=e(document.createElement("div"));
c.addClass(this.la.qw);a.append(c);var f=this.ai(),h=this.Yf(),g=d,k=[];if(1<=h){if(-1!=f&&f<=g)for(g=k[0]=1;g<f;g++)k[g]=g+1;else{k.push(1);1!=h&&k.push(h);h!=f&&-1!=f&&k.push(f);var g=g-k.length,l=h-1,m=1;if(h==f||h==f-1)m=0;for(;g>m&&1<l;)k.push(l),l--,g--;h+=1;for(-1==f&&(g=1);0<g&&(h<=f||-1==f);)k.push(h),h++,g--}k.sort(function(a,b){return a-b});for(g=0;g<k.length;g++)h=k[g],this.lr(c,h),g!=k.length-1&&h!=k[g+1]-1&&this.lr(c,-1);-1==f&&this.lr(c,-1)}return c},lr:function(a,b){var c=this.Yf(),
f=null;-1==b?(f=e(document.createElement("span")),f.append("...")):(c==b?(f=e(document.createElement("div")),f.addClass(this.Sa.Fb),f.addClass(this.Sa.kq),f.addClass(this.Sa.Tb),f.removeClass(this.Sa.md)):(f=e(document.createElement("a")),f.removeClass(this.Sa.Fb),f.removeClass(this.Sa.kq),f.removeClass(this.Sa.Tb),f.addClass(this.Sa.md)),f.attr("data-oj-pagenum",b),f.addClass(this.la.uG),c=this.l(this.Aa.MG,{pageNum:b.toString()}),this._hoverable(f),this._focusable(f),f.attr("title",c),f.attr("tabindex",
"0"),f.attr("href","#"),c=this.lI(),f.append(c),f.append(b.toString()),this._hoverable(f));a.append(f);return f},LJ:function(){var a=this.kl(),b=null;a&&(b=a.find("."+this.la.cw))&&0<b.length&&(b=e(b.get(0)));return b},kl:function(){return e(this.element)},ll:function(){if(!this.ex){var a=this.kl(),b=null;a&&(b=a.find("."+this.la.dw))&&0<b.length&&(this.ex=e(b.get(0)))}return this.ex},ml:function(){if(!this.gx){var a=this.ll(),b=null;a&&(b=a.children("."+this.la.ew))&&0<b.length&&(this.gx=e(b.get(0)))}return this.gx},
LR:function(){if(!this.hx){var a=this.ml(),b=null;a&&(b=a.children("."+this.la.fw))&&0<b.length&&(this.hx=e(b.get(0)))}return this.hx},MJ:function(){if(!this.Rq){var a=this.ml(),b=null;a&&(b=a.children("."+this.la.gw))&&0<b.length&&(this.Rq=e(b.get(0)))}return this.Rq},nl:function(){if(!this.Sq){var a=this.ll(),b=null;a&&(b=a.children("."+this.la.iw))&&0<b.length&&(this.Sq=e(b.get(0)))}return this.Sq},MR:function(){if(!this.Tq){var a=this.nl(),b=null;a&&(b=a.find("."+this.la.kw))&&0<b.length&&(this.Tq=
e(b.get(0)))}return this.Tq},OJ:function(){if(!this.Uq){var a=this.nl(),b=null;a&&(b=a.find("."+this.la.mw))&&0<b.length&&(this.Uq=e(b.get(0)))}return this.Uq},PJ:function(){var a=this.nl(),b=null;a&&(b=a.find("."+this.la.qw))&&0<b.length&&(b=e(b.get(0)));return b},az:function(){var a=this.nl(),b=null;a&&(b=a.find("."+this.la.hw))&&0<b.length&&(b=e(b.get(0)));return b},NJ:function(){var a=this.nl(),b=null;a&&(b=a.find("."+this.la.lw))&&0<b.length&&(b=e(b.get(0)));return b}})})();b.rb=function(a){this.Na=
a;this.Init()};o_("PagingDataSource",b.rb,b);b.a.ga(b.rb,b.Vc,"oj.PagingDataSource");b.rb.prototype.Init=function(){b.rb.j.Init.call(this)};b.a.c("PagingDataSource.prototype.Init",{Init:b.rb.prototype.Init});b.rb.prototype.fetch=function(){b.f.V()};b.a.c("PagingDataSource.prototype.fetch",{fetch:b.rb.prototype.fetch});b.rb.prototype.hasMore=function(){b.f.V();return!1};b.a.c("PagingDataSource.prototype.hasMore",{hasMore:b.rb.prototype.hasMore});b.rb.prototype.next=function(){b.f.V()};b.a.c("PagingDataSource.prototype.next",
{next:b.rb.prototype.next});b.rb.prototype.previous=function(){b.f.V()};b.a.c("PagingDataSource.prototype.previous",{previous:b.rb.prototype.previous});b.rb.prototype.setPageSize=function(){b.f.V()};b.rb.prototype.startIndex=function(){b.f.V();return 0};b.a.c("PagingDataSource.prototype.startIndex",{startIndex:b.rb.prototype.startIndex});b.rb.prototype.size=function(){b.f.V();return 0};b.a.c("PagingDataSource.prototype.size",{size:b.rb.prototype.size});b.rb.prototype.totalSize=function(){b.f.V();
return 0};b.a.c("PagingDataSource.prototype.totalSize",{totalSize:b.rb.prototype.totalSize});b.rb.q={SYNC:"sync"};o_("PagingDataSource.EventType",b.rb.q,b)});
//# sourceMappingURL=oj-modular.map