define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){(function(){var a="oj-left oj-center oj-right oj-top oj-middle oj-bottom".split(" "),d={"right-top":"oj-right oj-top","right-middle":"oj-right oj-middle","right-bottom":"oj-right oj-bottom","left-top":"oj-left oj-top","left-middle":"oj-left oj-middle","left-bottom":"oj-left oj-bottom","center-top":"oj-center oj-top","center-middle":"oj-left oj-middle","center-bottom":"oj-center oj-bottom"};b.ta("oj.ojPopup",e.oj.baseComponent,{version:"1.0.0",
widgetEventPrefix:"oj",options:{autoDismiss:"none",chrome:"default",initialFocus:"firstFocusable",position:{my:"start top",at:"start bottom",of:"",collision:"flip"},tail:"none",beforeOpen:null,open:null,beforeClose:null,close:null,focus:null},Kc:function(){this._super();var a=e("\x3cdiv\x3e");this.Pc=a.hide().addClass("oj-popup").attr("aria-hidden","true");a.addClass("oj-helper-reset-inheritable oj-component");var b=e("\x3cdiv\x3e").addClass("oj-popup-content");b.appendTo(a);this.element.after(a);
this.element.appendTo(b);this.element.show();this.Vx();this.zB();this.fI();this.tC=e.proxy(this.zO,this)},_destroy:function(){this._super();this.isOpen()&&this.close();this.hy();this.JI();delete this.tC;this.Pc.replaceWith(this.element);this.element.hide()},widget:o_c("Pc"),open:function(a,d){if(this.isOpen()&&(this.close(),this.isOpen()))return;this.LN(a);var h=this.Pc;a=this.Xa;b.f.$a(h,jQuery);b.f.$a(a,jQuery);b.pb.cQ(h.attr("id"))&&h.uniqueId();if(!1!==this._trigger("beforeOpen")){this.KB(d);
var g=this.options;this.jt(g.autoDismiss);this._on(!0,e(window),{resize:this.gt});this._on(!0,h,{keydown:this.Tz});this._on(!0,a,{keydown:this.Tz});this.cH();h.removeAttr("aria-hidden");h.attr("role","tooltip");d=g.position;h.show();h.position(b.Qi.dE(d,"rtl"===this.xc()));this._trigger("open");this.Kz();h=this.l("none"===g.initialFocus?"ariaLiveRegionInitialFocusNone":"ariaLiveRegionInitialFocusFirstFocusable");this.mH(h)}},close:function(){if(this.isOpen()&&!1!==this._trigger("beforeClose")){this.rN();
var a=this.Xa,d=this.Pc;b.f.$a(d,jQuery);b.f.$a(a,jQuery);d.hide();d.attr("aria-hidden","true");this.bN();this.jt();this._off(e(window),"resize");this._off(d,"keydown");this._off(a,"keydown");delete this.Xa;a=this.options.position;a._ofo&&(delete a._ofo,delete a.of);this._trigger("close")}},isOpen:function(){return this.Pc.is(":visible")},_setOption:function(a,b){var d=this.options;switch(a){case "tail":b!==d.tail&&this.PN(b);break;case "chrome":b!==d.chrome&&this.zB(b);break;case "position":this.KB(b);
this.isOpen()&&this.gt();return;case "autoDismiss":this.isOpen()&&b!==d.autoDismiss&&this.jt(b)}this._super(a,b)},OR:o_d("oj-popup"),PN:function(a){this.hy();this.Vx(a);this.gt()},Vx:function(a){a=a?a:this.options.tail;if("none"!==a){a=["oj-popup-tail",a].join("-");var d=e("\x3cdiv\x3e").hide().addClass("oj-popup-tail").addClass(a);this.aC="#"+d.uniqueId().attr("id");var h=this.Pc;b.f.$a(h,jQuery);d.appendTo(h);h.addClass(a)}},oz:function(){var a=this.aC;return a?e(a):null},hy:function(){var a=this.oz();
a&&a.remove();delete this.aC;var a=["oj-popup-tail",this.options.tail].join("-"),d=this.Pc;b.f.$a(d,jQuery);d.removeClass(a)},zB:function(a){a=a?a:this.options.chrome;var d=this.Pc;b.f.$a(d,jQuery);"default"===a&&d.hasClass("oj-popup-no-chrome")?d.removeClass("oj-popup-no-chrome"):"none"!==a||d.hasClass("oj-popup-no-chrome")||d.addClass("oj-popup-no-chrome")},LN:function(a){a?"string"===e.type(a)?a=e(a):1!==a.nodeType&&(a=e(a)):a=e(document.activeElement);if(a instanceof jQuery&&1<a.length){var d=
this.Pc;b.f.$a(d,jQuery);for(var h=0;h<a.length;h++){var g=a[0];if(!b.xa.sm(d[0],g)){a=e(g);break}}}else if(!(a instanceof jQuery)||a instanceof jQuery&&0===a.length)a=e(document.activeElement);b.f.$a(a,jQuery);this.Xa=a},KB:function(a){var d=this.options;a&&(d.position=e.extend(d[a],a));a=d.position;d=this.tC;b.f.fh(d);e.isFunction(a.using)&&a.using!==d&&(a.origUsing=a.using);a.using=d;d=this.Xa;b.f.$a(d,jQuery);a.of||(a.of=d,a._ofo=!0)},zO:function(c,e){var h=e.element.element;b.f.$a(h,jQuery);
var g=this.oz();if(g){g.hide();for(var k=0;k<a.length;k++)g.removeClass(a[k]),h.removeClass(a[k]);g.removeAttr("style");k=d[[e.horizontal,e.vertical].join("-")];b.f.Rj(k);g.addClass(k);h.addClass(k);g.show();"left"===e.horizontal||"right"===e.horizontal?(k=(g.outerWidth()-1)*("left"===e.horizontal?1:-1),c.left+=k):"center"===e.horizontal&&(k=(g.outerHeight()-1)*("top"===e.vertical?1:-1),c.top+=k);h.css(c);"middle"===e.vertical?(h=h.height(),h=Math.round(100*((h/2-g.outerHeight()/2)/h)),g.css({top:h+
"%"})):"center"===e.horizontal&&(h=h.width(),h=Math.round(100*((h/2-g.outerWidth()/2)/h)),g.css({left:h+"%"}));(g=this.options.position.origUsing)&&g(c,e)}else h.css(c)},gt:function(){var a=this.Pc;b.f.$a(a,jQuery);var d=this.options.position;b.f.sd(d);a.position(b.Qi.dE(d,"rtl"===this.xc()))},Kz:function(a){var d=this.options;if(a||"none"!==d.initialFocus)if(a||"firstFocusable"===d.initialFocus)a=this.element.find(":focusable"),0<a.length?(a=a[0],b.f.ue(a),e(a).focus()):(a=this.Pc,b.f.$a(a,jQuery),
a.attr("tabindex","-1"),a.focus()),this._trigger("focus")},xs:function(a){a||(a=document.activeElement);b.f.ue(a);var d=this.Pc;b.f.$a(d,jQuery);return b.xa.sm(d[0],a)},yL:function(a){a||(a=document.activeElement);b.f.ue(a);var d=this.Xa;b.f.$a(d,jQuery);return b.xa.sm(d[0],a)},rN:function(){if(this.xs()){var a=this.Xa;b.f.$a(a,jQuery);a.focus()}},Tz:function(a){if(!a.isDefaultPrevented()){var d=a.target;b.f.ue(d);if(27===a.keyCode)a.preventDefault(),this.close();else if(117===a.keyCode)this.xs(d)?
(a.preventDefault(),a=this.Xa,b.f.$a(a,jQuery),a.focus()):this.yL(d)&&(a.preventDefault(),this.Kz(!0));else if(9===a.keyCode&&this.xs(d)){var h=this.element.find(":tabbable");if(0<h.length){var g=h[0];b.f.ue(g);h=h[h.length-1];b.f.ue(h);g===d&&a.shiftKey?(a.preventDefault(),e(h).focus()):h!==d||a.shiftKey||(a.preventDefault(),e(g).focus())}}}},jt:function(a){var b=document.documentElement,d=this.Fy;d&&(b.removeEventListener("mousedown",d,!0),b.removeEventListener("focus",d,!0),delete this.Fy);"focusLoss"===
a&&(d=this.Fy=e.proxy(this.MI,this),b.addEventListener("mousedown",d,!0),b.addEventListener("focus",d,!0))},MI:function(a){var d=this.Xa,e=this.Pc;b.f.$a(d,jQuery);b.f.$a(e,jQuery);a=a.target;b.f.ue(a);b.xa.sm(d[0],a)||b.xa.sm(e[0],a)||this.close()},cH:function(){var a=this.Xa,d=this.Pc;b.f.$a(a,jQuery);b.f.$a(d,jQuery);var d=d.attr("id"),h=a.attr("aria-describedby"),h=h?h.split(/\s+/):[];h.push(d);h=e.trim(h.join(" "));a.attr("aria-describedby",h)},bN:function(){var a=this.Xa,d=this.Pc;b.f.$a(a,
jQuery);b.f.$a(d,jQuery);var d=d.attr("id"),h=a.attr("aria-describedby"),h=h?h.split(/\s+/):[],d=e.inArray(d,h);-1!==d&&h.splice(d,1);(h=e.trim(h.join(" ")))?a.attr("aria-describedby",h):a.removeAttr("aria-describedby")},fI:function(){var a=this.Pc;b.f.$a(a,jQuery);a.attr("id");var d=this.eK("ariaLive"),h=this.Is=e("\x3cdiv\x3e");h.attr({id:d,role:"log","aria-live":"assertive","aria-relevant":"additions"});h.addClass("oj-helper-hidden-accessible");h.appendTo(document.body);a.attr("aria-controls",
d)},mH:function(a){var d=this.Is;b.f.$a(d,jQuery);d.children().remove();e("\x3cdiv\x3e").text(a).appendTo(d)},JI:function(){var a=this.Is;b.f.$a(a,jQuery);a.remove();delete this.Is;a=this.Pc;b.f.$a(a,jQuery);a.removeAttr("aria-controls")},eK:function(a){return this.uuid+"_"+a}})})()});
//# sourceMappingURL=oj-modular.map