define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){(function(){var a="oj-left oj-center oj-right oj-top oj-middle oj-bottom".split(" "),d={"right-top":"oj-right oj-top","right-middle":"oj-right oj-middle","right-bottom":"oj-right oj-bottom","left-top":"oj-left oj-top","left-middle":"oj-left oj-middle","left-bottom":"oj-left oj-bottom","center-top":"oj-center oj-top","center-middle":"oj-left oj-middle","center-bottom":"oj-center oj-bottom"};b.ta("oj.ojPopup",e.oj.baseComponent,{version:"1.0.0",
widgetEventPrefix:"oj",options:{autoDismiss:"none",chrome:"default",initialFocus:"firstFocusable",position:{my:"start top",at:"start bottom",of:"",collision:"flip"},tail:"none",beforeOpen:null,open:null,beforeClose:null,close:null,focus:null},Ic:function(){this._super();var a=e("\x3cdiv\x3e");this.Ud=a.hide().addClass("oj-popup").attr("aria-hidden","true");a.addClass("oj-helper-reset-inheritable oj-component");var b=e("\x3cdiv\x3e").addClass("oj-popup-content");b.appendTo(a);this.element.after(a);
this.element.appendTo(b);this.element.show();this.Jx();this.nB();this.hC=e.proxy(this.dO,this)},_destroy:function(){this._super();this.isOpen()&&this.close();this.Vx();delete this.hC;this.Ud.replaceWith(this.element);this.element.hide()},widget:o_c("Ud"),open:function(a,d){if(this.isOpen()&&(this.close(),this.isOpen()))return;if(!1!==this._trigger("beforeOpen")){var h=this.options;this.pN(a);this.yB(d);var g=this.Ud;b.f.Fb(g,jQuery);a=this.bb;b.f.Fb(a,jQuery);this.Ws(h.autoDismiss);this._on(!0,e(window),
{resize:this.Ts});this._on(!0,g,{keydown:this.Gz});this._on(!0,a,{keydown:this.Gz});b.nb.GP(g.attr("id"))&&g.uniqueId();var k=g.attr("id");a.attr("aria-describedby",k);g.removeAttr("aria-hidden");g.attr("role","tooltip");d=h.position;g.show();g.position(b.Hi.OD(d,"rtl"===this.xc()));this._trigger("open");this.xz()}},close:function(){if(this.isOpen()&&!1!==this._trigger("beforeClose")){this.WM();var a=this.Ud;b.f.Fb(a,jQuery);a.hide();a.attr("aria-hidden","true");var d=this.bb;b.f.Fb(d,jQuery);d.removeAttr("aria-describedby");
this.Ws();this._off(e(window),"resize");this._off(a,"keydown");this._off(d,"keydown");delete this.bb;a=this.options.position;a._ofo&&(delete a._ofo,delete a.of);this._trigger("close")}},isOpen:function(){return this.Ud.is(":visible")},_setOption:function(a,b){var d=this.options;switch(a){case "tail":b!==d.tail&&this.tN(b);break;case "chrome":b!==d.chrome&&this.nB(b);break;case "position":this.yB(b);this.isOpen()&&this.Ts();return;case "autoDismiss":this.isOpen()&&b!==d.autoDismiss&&this.Ws(b)}this._super(a,
b)},qR:o_d("oj-popup"),tN:function(a){this.Vx();this.Jx(a);this.Ts()},Jx:function(a){a=a?a:this.options.tail;if("none"!==a){a=["oj-popup-tail",a].join("-");var d=e("\x3cdiv\x3e").hide().addClass("oj-popup-tail").addClass(a);this.PB="#"+d.uniqueId().attr("id");var h=this.Ud;b.f.Fb(h,jQuery);d.appendTo(h);h.addClass(a)}},bz:function(){var a=this.PB;return a?e(a):null},Vx:function(){var a=this.bz();a&&a.remove();delete this.PB;var a=["oj-popup-tail",this.options.tail].join("-"),d=this.Ud;b.f.Fb(d,jQuery);
d.removeClass(a)},nB:function(a){a=a?a:this.options.chrome;var d=this.Ud;b.f.Fb(d,jQuery);"default"===a&&d.hasClass("oj-popup-no-chrome")?d.removeClass("oj-popup-no-chrome"):"none"!==a||d.hasClass("oj-popup-no-chrome")||d.addClass("oj-popup-no-chrome")},pN:function(a){a?"string"===e.type(a)?a=e(a):1!==a.nodeType&&(a=e(a)):a=e(document.activeElement);if(a instanceof jQuery&&1<a.length){var d=this.Ud;b.f.Fb(d,jQuery);for(var h=0;h<a.length;h++){var g=a[0];if(!b.xa.im(d[0],g)){a=e(g);break}}}else if(!(a instanceof
jQuery)||a instanceof jQuery&&0===a.length)a=e(document.activeElement);b.f.Fb(a,jQuery);this.bb=a},yB:function(a){var d=this.options;a&&(d.position=e.extend(d[a],a));a=d.position;d=this.hC;b.f.ah(d);e.isFunction(a.using)&&a.using!==d&&(a.origUsing=a.using);a.using=d;d=this.bb;b.f.Fb(d,jQuery);a.of||(a.of=d,a._ofo=!0)},dO:function(c,e){var h=e.element.element;b.f.Fb(h,jQuery);var g=this.bz();if(g){g.hide();for(var k=0;k<a.length;k++)g.removeClass(a[k]),h.removeClass(a[k]);g.removeAttr("style");k=d[[e.horizontal,
e.vertical].join("-")];b.f.Jj(k);g.addClass(k);h.addClass(k);g.show();"left"===e.horizontal||"right"===e.horizontal?(k=(g.outerWidth()-1)*("left"===e.horizontal?1:-1),c.left+=k):"center"===e.horizontal&&(k=(g.outerHeight()-1)*("top"===e.vertical?1:-1),c.top+=k);h.css(c);"middle"===e.vertical?(h=h.height(),h=Math.round(100*((h/2-g.outerHeight()/2)/h)),g.css({top:h+"%"})):"center"===e.horizontal&&(h=h.width(),h=Math.round(100*((h/2-g.outerWidth()/2)/h)),g.css({left:h+"%"}));(g=this.options.position.origUsing)&&
g(c,e)}else h.css(c)},Ts:function(){var a=this.Ud;b.f.Fb(a,jQuery);var d=this.options.position;b.f.pd(d);a.position(b.Hi.OD(d,"rtl"===this.xc()))},xz:function(a){var d=this.options;if(a||"none"!==d.initialFocus)if(a||"firstFocusable"===d.initialFocus)a=this.element.find(":focusable"),0<a.length?(a=a[0],b.f.re(a),e(a).focus()):(a=this.Ud,b.f.Fb(a,jQuery),a.attr("tabindex","-1"),a.focus()),this._trigger("focus")},ms:function(a){a||(a=document.activeElement);b.f.re(a);var d=this.Ud;b.f.Fb(d,jQuery);
return b.xa.im(d[0],a)},cL:function(a){a||(a=document.activeElement);b.f.re(a);var d=this.bb;b.f.Fb(d,jQuery);return b.xa.im(d[0],a)},WM:function(){if(this.ms()){var a=this.bb;b.f.Fb(a,jQuery);a.focus()}},Gz:function(a){if(!a.isDefaultPrevented()){var d=a.target;b.f.re(d);if(27===a.keyCode)a.preventDefault(),this.close();else if(117===a.keyCode)this.ms(d)?(a.preventDefault(),a=this.bb,b.f.Fb(a,jQuery),a.focus()):this.cL(d)&&(a.preventDefault(),this.xz(!0));else if(9===a.keyCode&&this.ms(d)){var h=
this.element.find(":tabbable");if(0<h.length){var g=h[0];b.f.re(g);h=h[h.length-1];b.f.re(h);g===d&&a.shiftKey?(a.preventDefault(),e(h).focus()):h!==d||a.shiftKey||(a.preventDefault(),e(g).focus())}}}},Ws:function(a){var b=document.documentElement,d=this.sy;d&&(b.removeEventListener("mousedown",d,!0),b.removeEventListener("focus",d,!0),delete this.sy);"focusLoss"===a&&(d=this.sy=e.proxy(this.sI,this),b.addEventListener("mousedown",d,!0),b.addEventListener("focus",d,!0))},sI:function(a){var d=this.bb,
e=this.Ud;b.f.Fb(d,jQuery);b.f.Fb(e,jQuery);a=a.target;b.f.re(a);b.xa.im(d[0],a)||b.xa.im(e[0],a)||this.close()}})})()});
//# sourceMappingURL=oj-modular.map