define(["ojs/ojcore","jquery","ojs/ojmodel","ojs/ojdatacollection-common","ojs/ojtable"],function(b,e){b.Ya=function(a,d){b.Ya._init(this,a,d,null)};o_("ModelRow",b.Ya,b);b.a.ga(b.Ya,b.Va,"ModelRow.ModelRow");b.Ya.prototype.Init=function(){b.Va.j.Init.call(this)};b.Ya.prototype.attributes={};b.a.c("ModelRow.prototype.attributes",{attributes:b.Ya.prototype.attributes});b.Ya.prototype.id=null;b.a.c("ModelRow.prototype.id",{id:b.Ya.prototype.id});b.Ya.prototype.be=null;b.a.c("ModelRow.prototype.idAttribute",
{be:b.Ya.prototype.be});b.Ya._init=function(a,b,c,f){var e=null;a.Init();a.ki=b;a.id=b.id;a.be=b.be;a.attributes=b.attributes;a.index=b.index;c=c||{};for(e in f)f.hasOwnProperty(e)&&(a[e]=f[e]);a.context=c.context};b.Ya.prototype.clone=function(){return this.ki.clone()};b.a.c("ModelRow.prototype.clone",{clone:b.Ya.prototype.clone});b.Ya.prototype.get=function(a){return this.ki.get(a)};b.a.c("ModelRow.prototype.get",{get:b.Ya.prototype.get});b.Ya.prototype.eu=o_c("ki");b.a.c("ModelRow.prototype.getModel",
{eu:b.Ya.prototype.eu});b.Ya.prototype.set=function(a,b,c){return this.ki.set(a,b,c)};b.a.c("ModelRow.prototype.set",{set:b.Ya.prototype.set});b.Ya.prototype.keys=function(){return this.ki.keys()};b.a.c("ModelRow.prototype.keys",{keys:b.Ya.prototype.keys});b.Ya.prototype.Ie=function(){return this.ki.Ie()};b.a.c("ModelRow.prototype.values",{Ie:b.Ya.prototype.Ie});b.Ya.prototype.Rc=function(){return this.ki.Rc()};b.a.c("ModelRow.prototype.pairs",{Rc:b.Ya.prototype.Rc});b.ra=function(a,d){b.ra._init(this,
a,d,null)};o_("CollectionRowSet",b.ra,b);b.ra.prototype.we=null;b.a.c("CollectionRowSet.prototype.comparator",{we:b.ra.prototype.we});b.ra.prototype.df=!0;b.a.c("CollectionRowSet.prototype.sortSupported",{df:b.ra.prototype.df});b.a.ga(b.ra,b.t,"CollectionRowSet.CollectionRowSet");b.ra.prototype.Init=function(){b.ra.j.Init.call(this)};b.ra._init=function(a,b,c,f){var e;a.zb=[];a.S=0;a.Init();if(f)for(e in f)f.hasOwnProperty(e)&&(a[e]=f[e]);a.Eb=b;a.ZG()};b.ra.prototype.at=function(a,d){var c=this.Eb.at(a,
d);if(null!=c){if(c instanceof b.i)return new b.Ya(c);var f=e.Deferred();e.when(c).done(function(a){f.resolve(new b.Ya(a))});return f}return null};b.a.c("CollectionRowSet.prototype.at",{at:b.ra.prototype.at});b.ra.prototype.fetch=function(a){if(this.NH.call(this)){this.st.call(this);a=a||{};var b=this,c=null!=a.startIndex?!0:!1;this.S=c?a.startIndex:0;a=0<a.pageSize?a.pageSize:-1;c?this.Eb.Wp(this.S,a).done(function(){b.al.call(b,!0)}):this.Eb.fetch({success:function(a){b.Eb=a;b.al.call(b,!0)}})}};
b.a.c("CollectionRowSet.prototype.fetch",{fetch:b.ra.prototype.fetch});b.ra.prototype.get=function(a,d){return new b.Ya(this.Eb.get(a,d))};b.a.c("CollectionRowSet.prototype.get",{get:b.ra.prototype.get});b.ra.prototype.getCollection=o_c("Eb");b.a.c("CollectionRowSet.prototype.getCollection",{getCollection:b.ra.prototype.getCollection});b.ra.prototype.hasMore=function(){return this.Eb.hasMore};b.a.c("CollectionRowSet.prototype.hasMore",{hasMore:b.ra.prototype.hasMore});b.ra.prototype.indexOf=function(a,
b){return this.Eb.indexOf(a.eu(),b)};b.a.c("CollectionRowSet.prototype.indexOf",{indexOf:b.ra.prototype.indexOf});b.ra.prototype.isEmpty=function(){return this.Eb.isEmpty()};b.a.c("CollectionRowSet.prototype.isEmpty",{isEmpty:b.ra.prototype.isEmpty});b.ra.prototype.size=function(){return this.Eb.size()};b.a.c("CollectionRowSet.prototype.size",{size:b.ra.prototype.size});b.ra.prototype.sort=function(){this.Eb.comparator=this.comparator;return this.Eb.sort(null)};b.a.c("CollectionRowSet.prototype.sort",
{sort:b.ra.prototype.sort});b.ra.prototype.totalSize=function(){return this.Eb.Xu};b.a.c("CollectionRowSet.prototype.totalSize",{totalSize:b.ra.prototype.totalSize});b.ra.prototype.ZG=function(){var a=this;this.Eb.on(b.N.q.ADD,function(d){b.ra.j.nc.call(a,b.t.q.ADD,{rowIdx:a.Eb.indexOf(d),row:new b.Ya(d)})});this.Eb.on(b.N.q.REMOVE,function(d){b.ra.j.nc.call(a,b.t.q.REMOVE,{rowIdx:a.Eb.indexOf(d),row:new b.Ya(d)})});this.Eb.on(b.N.q.RESET,function(d){b.ra.j.nc.call(a,b.t.q.RESET,d)});this.Eb.on(b.N.q.SORT,
function(d,c){c.add||b.ra.j.nc.call(a,b.t.q.SORT,d)});this.Eb.on(b.N.q.CHANGE,function(d){b.ra.j.nc.call(a,b.t.q.CHANGE,{rowIdx:a.Eb.indexOf(d),row:new b.Ya(d)})});this.Eb.on(b.N.q.DESTROY,function(d){b.ra.j.nc.call(a,b.t.q.DESTROY,d)});this.Eb.on(b.N.q.SYNC,function(d){b.ra.j.nc.call(a,b.t.q.SYNC,d)});this.Eb.on(b.N.q.ERROR,function(d){b.ra.j.nc.call(a,b.t.q.ERROR,d);a.al.call(a,!1)})};b.ra.prototype.NH=function(){return!this.Nz};b.ra.prototype.st=function(){this.Nz=!0;b.ra.j.nc.call(this,b.t.q.REQUEST,
null)};b.ra.prototype.al=function(a){this.Nz=!1;b.ra.j.nc.call(this,b.t.q.SYNC,a)};b.Cb=function(a,d){if(!(a instanceof b.g)){var c=b.L.l("oj-ojTable.dataInvalidType.summary"),f=b.L.l("oj-ojTable.dataInvalidType.detail");throw new b.C(c,f,b.C.Ja.ERROR);}b.Cb.j.constructor.call(this,a,d);this.Q=new b.ra(a,this.options);this.Pk();this.Init();if(null!=d&&("enabled"==d.startFetch||null==d.startFetch)||null==d){var e=this;setTimeout(function(){e.fetch({startFetch:"enabled"})},0)}};o_("CollectionTableDataSource",
b.Cb,b);b.a.ga(b.Cb,b.ca,"oj.CollectionTableDataSource");b.Cb.prototype.Init=function(){b.Cb.j.Init.call(this)};b.a.c("CollectionTableDataSource.prototype.Init",{Init:b.Cb.prototype.Init});b.Cb.prototype.at=function(a){return this.Q.at(a)};b.a.c("CollectionTableDataSource.prototype.at",{at:b.Cb.prototype.at});b.Cb.prototype.fetch=function(a){a=a||{};null!=a.startIndex&&b.Cb.j.startIndex.call(this,a.startIndex);"enabled"==a.startFetch?(this.Q.isEmpty()||"undefined"===typeof this.Q.size())&&this.Q.fetch(a):
this.Q.fetch(a)};b.a.c("CollectionTableDataSource.prototype.fetch",{fetch:b.Cb.prototype.fetch});b.Cb.prototype.get=function(a){return this.Q.get(a)};b.a.c("CollectionTableDataSource.prototype.get",{get:b.Cb.prototype.get});b.Cb.prototype.hasMore=function(){return null!=this.Q?this.Q.hasMore():!1};b.a.c("CollectionTableDataSource.prototype.hasMore",{hasMore:b.Cb.prototype.hasMore});b.Cb.prototype.indexOf=function(a){return this.Q.indexOf(a)};b.a.c("CollectionTableDataSource.prototype.indexOf",{indexOf:b.Cb.prototype.indexOf});
b.Cb.prototype.size=function(){return this.Q.size()};b.a.c("CollectionTableDataSource.prototype.size",{size:b.Cb.prototype.size});b.Cb.prototype.sort=function(a){var b=a.key;a=a.direction;var c=null;"ascending"==a?c=function(a){return e.isFunction(a.get)?a.get(b):a[b]()}:"descending"==a&&(c=function(a,c){var g,k;e.isFunction(a.get)?(g=a.get(b),k=c.get(b)):(g=a[b](),k=c[b]());return g===k?0:g>k?-1:1});this.Q.comparator=c;this.Q.sort()};b.a.c("CollectionTableDataSource.prototype.sort",{sort:b.Cb.prototype.sort});
b.Cb.prototype.totalSize=function(){return this.Q.totalSize()};b.a.c("CollectionTableDataSource.prototype.totalSize",{totalSize:b.Cb.prototype.totalSize});b.Cb.prototype.Pk=function(){var a=this;this.Q.on(b.t.q.ADD,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.q.ADD,d)});this.Q.on(b.t.q.REMOVE,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.q.REMOVE,d)});this.Q.on(b.t.q.REQUEST,function(d){a.qc=!0;b.ca.j.handleEvent.call(a,b.t.q.REQUEST,d)});this.Q.on(b.t.q.RESET,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,
b.t.q.RESET,d)});this.Q.on(b.t.q.SORT,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.q.SORT,d)});this.Q.on(b.t.q.CHANGE,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.q.CHANGE,d)});this.Q.on(b.t.q.DESTROY,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.q.DESTROY,d)});this.Q.on(b.t.q.SYNC,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.q.SYNC,d)});this.Q.on(b.t.q.ERROR,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.q.ERROR,d)})}});
//# sourceMappingURL=oj-modular.map