define(["ojs/ojcore","jquery","ojs/ojmodel","ojs/ojdatacollection-common","ojs/ojtable"],function(b,e){b.Xa=function(a,d){b.Xa._init(this,a,d,null)};o_("ModelRow",b.Xa,b);b.a.fa(b.Xa,b.Ua,"ModelRow.ModelRow");b.Xa.prototype.Init=function(){b.Ua.j.Init.call(this)};b.Xa.prototype.attributes={};b.a.b("ModelRow.prototype.attributes",{attributes:b.Xa.prototype.attributes});b.Xa.prototype.id=null;b.a.b("ModelRow.prototype.id",{id:b.Xa.prototype.id});b.Xa.prototype.$d=null;b.a.b("ModelRow.prototype.idAttribute",
{$d:b.Xa.prototype.$d});b.Xa._init=function(a,b,c,f){var e=null;a.Init();a.di=b;a.id=b.id;a.$d=b.$d;a.attributes=b.attributes;a.index=b.index;c=c||{};for(e in f)f.hasOwnProperty(e)&&(a[e]=f[e]);a.context=c.context};b.Xa.prototype.clone=function(){return this.di.clone()};b.a.b("ModelRow.prototype.clone",{clone:b.Xa.prototype.clone});b.Xa.prototype.get=function(a){return this.di.get(a)};b.a.b("ModelRow.prototype.get",{get:b.Xa.prototype.get});b.Xa.prototype.Qt=o_c("di");b.a.b("ModelRow.prototype.getModel",
{Qt:b.Xa.prototype.Qt});b.Xa.prototype.set=function(a,b,c){return this.di.set(a,b,c)};b.a.b("ModelRow.prototype.set",{set:b.Xa.prototype.set});b.Xa.prototype.keys=function(){return this.di.keys()};b.a.b("ModelRow.prototype.keys",{keys:b.Xa.prototype.keys});b.Xa.prototype.He=function(){return this.di.He()};b.a.b("ModelRow.prototype.values",{He:b.Xa.prototype.He});b.Xa.prototype.Oc=function(){return this.di.Oc()};b.a.b("ModelRow.prototype.pairs",{Oc:b.Xa.prototype.Oc});b.ra=function(a,d){b.ra._init(this,
a,d,null)};o_("CollectionRowSet",b.ra,b);b.ra.prototype.ue=null;b.a.b("CollectionRowSet.prototype.comparator",{ue:b.ra.prototype.ue});b.ra.prototype.df=!0;b.a.b("CollectionRowSet.prototype.sortSupported",{df:b.ra.prototype.df});b.a.fa(b.ra,b.t,"CollectionRowSet.CollectionRowSet");b.ra.prototype.Init=function(){b.ra.j.Init.call(this)};b.ra._init=function(a,b,c,f){var e;a.wb=[];a.S=0;a.Init();if(f)for(e in f)f.hasOwnProperty(e)&&(a[e]=f[e]);a.Bb=b;a.LG()};b.ra.prototype.at=function(a,d){var c=this.Bb.at(a,
d);if(null!=c){if(c instanceof b.i)return new b.Xa(c);var f=e.Deferred();e.when(c).done(function(a){f.resolve(new b.Xa(a))});return f}return null};b.a.b("CollectionRowSet.prototype.at",{at:b.ra.prototype.at});b.ra.prototype.fetch=function(a){if(this.xH.call(this)){this.ft.call(this);a=a||{};var b=this,c=null!=a.startIndex?!0:!1;this.S=c?a.startIndex:0;a=0<a.pageSize?a.pageSize:-1;c?this.Bb.Np(this.S,a).done(function(){b.Pk.call(b,!0)}):this.Bb.fetch({success:function(a){b.Bb=a;b.Pk.call(b,!0)}})}};
b.a.b("CollectionRowSet.prototype.fetch",{fetch:b.ra.prototype.fetch});b.ra.prototype.get=function(a,d){return new b.Xa(this.Bb.get(a,d))};b.a.b("CollectionRowSet.prototype.get",{get:b.ra.prototype.get});b.ra.prototype.getCollection=o_c("Bb");b.a.b("CollectionRowSet.prototype.getCollection",{getCollection:b.ra.prototype.getCollection});b.ra.prototype.hasMore=function(){return this.Bb.hasMore};b.a.b("CollectionRowSet.prototype.hasMore",{hasMore:b.ra.prototype.hasMore});b.ra.prototype.indexOf=function(a,
b){return this.Bb.indexOf(a.Qt(),b)};b.a.b("CollectionRowSet.prototype.indexOf",{indexOf:b.ra.prototype.indexOf});b.ra.prototype.isEmpty=function(){return this.Bb.isEmpty()};b.a.b("CollectionRowSet.prototype.isEmpty",{isEmpty:b.ra.prototype.isEmpty});b.ra.prototype.size=function(){return this.Bb.size()};b.a.b("CollectionRowSet.prototype.size",{size:b.ra.prototype.size});b.ra.prototype.sort=function(){this.Bb.comparator=this.comparator;return this.Bb.sort(null)};b.a.b("CollectionRowSet.prototype.sort",
{sort:b.ra.prototype.sort});b.ra.prototype.totalSize=function(){return this.Bb.Ju};b.a.b("CollectionRowSet.prototype.totalSize",{totalSize:b.ra.prototype.totalSize});b.ra.prototype.LG=function(){var a=this;this.Bb.on(b.N.l.ADD,function(d){b.ra.j.nc.call(a,b.t.l.ADD,{rowIdx:a.Bb.indexOf(d),row:new b.Xa(d)})});this.Bb.on(b.N.l.REMOVE,function(d){b.ra.j.nc.call(a,b.t.l.REMOVE,{rowIdx:a.Bb.indexOf(d),row:new b.Xa(d)})});this.Bb.on(b.N.l.RESET,function(d){b.ra.j.nc.call(a,b.t.l.RESET,d)});this.Bb.on(b.N.l.SORT,
function(d,c){c.add||b.ra.j.nc.call(a,b.t.l.SORT,d)});this.Bb.on(b.N.l.CHANGE,function(d){b.ra.j.nc.call(a,b.t.l.CHANGE,{rowIdx:a.Bb.indexOf(d),row:new b.Xa(d)})});this.Bb.on(b.N.l.DESTROY,function(d){b.ra.j.nc.call(a,b.t.l.DESTROY,d)});this.Bb.on(b.N.l.SYNC,function(d){b.ra.j.nc.call(a,b.t.l.SYNC,d)});this.Bb.on(b.N.l.ERROR,function(d){b.ra.j.nc.call(a,b.t.l.ERROR,d);a.Pk.call(a,!1)})};b.ra.prototype.xH=function(){return!this.Az};b.ra.prototype.ft=function(){this.Az=!0;b.ra.j.nc.call(this,b.t.l.REQUEST,
null)};b.ra.prototype.Pk=function(a){this.Az=!1;b.ra.j.nc.call(this,b.t.l.SYNC,a)};b.zb=function(a,d){if(!(a instanceof b.g)){var c=b.L.q("oj-ojTable.dataInvalidType.summary"),f=b.L.q("oj-ojTable.dataInvalidType.detail");throw new b.C(c,f,b.C.Ha.ERROR);}b.zb.j.constructor.call(this,a,d);this.Q=new b.ra(a,this.options);this.Dk();this.Init();if(null!=d&&("enabled"==d.startFetch||null==d.startFetch)||null==d){var e=this;setTimeout(function(){e.fetch({startFetch:"enabled"})},0)}};o_("CollectionTableDataSource",
b.zb,b);b.a.fa(b.zb,b.ca,"oj.CollectionTableDataSource");b.zb.prototype.Init=function(){b.zb.j.Init.call(this)};b.a.b("CollectionTableDataSource.prototype.Init",{Init:b.zb.prototype.Init});b.zb.prototype.at=function(a){return this.Q.at(a)};b.a.b("CollectionTableDataSource.prototype.at",{at:b.zb.prototype.at});b.zb.prototype.fetch=function(a){a=a||{};null!=a.startIndex&&b.zb.j.startIndex.call(this,a.startIndex);"enabled"==a.startFetch?(this.Q.isEmpty()||"undefined"===typeof this.Q.size())&&this.Q.fetch(a):
this.Q.fetch(a)};b.a.b("CollectionTableDataSource.prototype.fetch",{fetch:b.zb.prototype.fetch});b.zb.prototype.get=function(a){return this.Q.get(a)};b.a.b("CollectionTableDataSource.prototype.get",{get:b.zb.prototype.get});b.zb.prototype.hasMore=function(){return null!=this.Q?this.Q.hasMore():!1};b.a.b("CollectionTableDataSource.prototype.hasMore",{hasMore:b.zb.prototype.hasMore});b.zb.prototype.indexOf=function(a){return this.Q.indexOf(a)};b.a.b("CollectionTableDataSource.prototype.indexOf",{indexOf:b.zb.prototype.indexOf});
b.zb.prototype.size=function(){return this.Q.size()};b.a.b("CollectionTableDataSource.prototype.size",{size:b.zb.prototype.size});b.zb.prototype.sort=function(a){var b=a.key;a=a.direction;var c=null;"ascending"==a?c=function(a){return e.isFunction(a.get)?a.get(b):a[b]()}:"descending"==a&&(c=function(a,c){var g,k;e.isFunction(a.get)?(g=a.get(b),k=c.get(b)):(g=a[b](),k=c[b]());return g===k?0:g>k?-1:1});this.Q.comparator=c;this.Q.sort()};b.a.b("CollectionTableDataSource.prototype.sort",{sort:b.zb.prototype.sort});
b.zb.prototype.totalSize=function(){return this.Q.totalSize()};b.a.b("CollectionTableDataSource.prototype.totalSize",{totalSize:b.zb.prototype.totalSize});b.zb.prototype.Dk=function(){var a=this;this.Q.on(b.t.l.ADD,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.l.ADD,d)});this.Q.on(b.t.l.REMOVE,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.l.REMOVE,d)});this.Q.on(b.t.l.REQUEST,function(d){a.qc=!0;b.ca.j.handleEvent.call(a,b.t.l.REQUEST,d)});this.Q.on(b.t.l.RESET,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,
b.t.l.RESET,d)});this.Q.on(b.t.l.SORT,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.l.SORT,d)});this.Q.on(b.t.l.CHANGE,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.l.CHANGE,d)});this.Q.on(b.t.l.DESTROY,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.l.DESTROY,d)});this.Q.on(b.t.l.SYNC,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.l.SYNC,d)});this.Q.on(b.t.l.ERROR,function(d){a.qc=!1;b.ca.j.handleEvent.call(a,b.t.l.ERROR,d)})}});
//# sourceMappingURL=oj-modular.map