define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojconveyorbelt"],function(b,e){(function(){b.ta("oj.ojTabs",e.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",delay:300,options:{selected:0,disabled:!1,truncation:"auto",selectOn:"click",orientation:"horizontal",removable:!1,removeCueText:"Tab is removable",reorderable:!1,beforeSelect:null,afterSelect:null,beforeDeselect:null,afterDeselect:null,beforeRemove:null,afterRemove:null,optionChange:null},Ic:function(){var a=this,b=this.options;
this._super();this.yu=!1;this.DB(b.orientation);this.pA();if(Array.isArray(b.disabled)){var c=this.Na.filter(".oj-disabled");b.disabled=e.unique(b.disabled.concat(e.map(c,function(b){return a.Na.index(b)}))).sort()}this.jl=b.selected;b.selected=-1;this.Nb()},ag:function(a,b){a.show(b,{launcher:this.element.children(".oj-tabs-nav").children("[tabindex\x3d0]"),focus:"menu"})},HN:function(a){var b=e(this.document[0].activeElement).closest("li"),c=this.Na.index(b),f=!0;if(!this.hz(a)){switch(a.keyCode){case e.ui.keyCode.RIGHT:case e.ui.keyCode.DOWN:c++;
break;case e.ui.keyCode.UP:case e.ui.keyCode.LEFT:f=!1;c--;break;case e.ui.keyCode.END:c=this.Na.length-1;break;case e.ui.keyCode.HOME:c=0;break;case 46:if(b=this.aa.find(".oj-tabs-close-icon"))a.preventDefault(),this.XA({target:b,currentTarget:b,preventDefault:e.noop});return;default:return}a.preventDefault();clearTimeout(this.jO);c=this.Ar(c,f);a.ctrlKey||(b.attr("aria-selected","false"),this.Na.eq(c).attr("aria-selected","true"),this.jO=this._delay(function(){this.option("selected",c)},this.delay))}},
TL:function(a){!this.hz(a)&&(a.ctrlKey&&a.keyCode===e.ui.keyCode.UP)&&(a.preventDefault(),this.aa.focus())},hz:function(a){if(a.ctrlKey&&a.keyCode===e.ui.keyCode.PAGE_UP)return this.zg(this.Ar(this.options.selected-1,!1)),!0;if(a.ctrlKey&&a.keyCode===e.ui.keyCode.PAGE_DOWN)return this.zg(this.Ar(this.options.selected+1,!0)),!0},ts:function(a){return-1!=e.inArray(a,this.options.disabled)},KI:function(a,b){function c(){a>e&&(a=0);0>a&&(a=e);return a}for(var e=this.Na.length-1;this.ts(c());)a=b?a+1:
a-1;return a},Ar:function(a,b){a=this.KI(a,b);this.Na.eq(a).focus();return a},KG:function(a){for(var b=this.Na.length-1,c=a+1;c<=b;){if(!this.ts(c))return this.zg(c),c-1;c++}for(c=a-1;0<=c;){if(!this.ts(c))return this.zg(c),c;c--}return-1},_setOption:function(a,b){"selected"===a?("string"===typeof b&&(b=this.wl(b)),this.zg(b)):"disabled"===a?this.ap(b):"removable"===a?this.sN(b):"reorderable"===a?b!==this.options.reorderable&&(this.options.reorderable=b,this.EB()):"orientation"===a?(this.DB(b),this.refresh()):
(this._super(a,b),"selectOn"===a&&(this.Hl(),this._super(a,b),this.mi()))},refresh:function(){this._super();this.qI();this.pA();this.Nb()},Nb:function(){this.aa=this.Na.length&&-1!=this.options.selected?this.ny(this.options.selected):e();this.ap(this.options.disabled);this.MH();this.Hl();this.mi();this.Na.not(this.aa).attr({"aria-selected":"false",tabIndex:"-1"});this.Ee.not(this.Sh(this.aa)).hide().attr({"aria-expanded":"false","aria-hidden":"true"});this.aa.length?(this.aa.addClass("oj-tabs-active").attr({"aria-selected":"true",
tabIndex:"0"}),this.Sh(this.aa).show().attr({"aria-expanded":"true","aria-hidden":"false"})):this.Na.eq(0).attr("tabIndex","0");if(void 0!==this.jl){var a=this.jl;this.options.selected=0!=a&&(0>a||a>this.Na.length)?0:a;this.zg(a);this.jl=void 0}"horizontal"==this.options.orientation&&(this.TN(),this.OG());this.EB()},OG:function(){if("horizontal"==this.options.orientation){var a=this.Gm.uniqueId().attr("id"),b=this.$y().wrap("\x3cdiv\x3e").parent();b.uniqueId().attr("id");b.addClass("oj-tabs-conveyorbelt");
this.dh=b.ojConveyorBelt({orientation:"horizontal",contentParent:"#"+a})}},pA:function(){var a=this;this.Ux();this.Gm=e("\x3cul\x3e").addClass("oj-tabs-nav oj-helper-clearfix").attr("role","tablist").prependTo(this.element);this.Na=e();this.Ee=e();this.Hm=e();this.element.children(":not(.oj-tabs-nav)").each(function(b){var c=e(this).find("\x3e :first-child"),d=c.clone();d.addClass("oj-tabs-title").css({display:""}).attr({"aria-hidden":"false"});a.VA(d);a.Hm=a.Hm.add(d);var f=c[0];f.id&&a.Aw(f);c.find("[id]").each(function(){a.Aw(this)});
f=d.wrap("\x3cli\x3e\x3cdiv\x3e\x3ca href\x3d'#'\x3e\x3c/a\x3e\x3c/div\x3e\x3c/li\x3e").parent();f.addClass("oj-tabs-anchor").attr({role:"presentation",tabIndex:"-1"});d=f.parent().addClass("oj-tabs-tab-content").parent().addClass("oj-tabs-default").attr({role:"tab","aria-hidden":"false",tabIndex:"-1"});d.appendTo(a.Gm);a.Na=a.Na.add(d);c.hide().attr({"aria-hidden":"true"});var c=f.uniqueId().attr("id"),f=d.attr("aria-controls"),m=e(this);m.hasClass("oj-disabled")&&a.disable(b);f&&d.data("oj-tabs-aria-controls",
f);d.attr({"aria-controls":m.uniqueId().attr("id"),"aria-labelledby":c});a.Ee=a.Ee.add(m);m.attr("aria-labelledby",c)});if("vertical"==this.options.orientation){var b=0,c=0;this.Na.addClass("oj-tabs-active").each(function(){var a=e(this);b=Math.max(b,a.width());c+=a.outerHeight(!0)}).removeClass("oj-tabs-active");this.options.removable&&(b+=28);this.Na.css({width:b+"px"});var f=this.Gm.outerWidth(!0);"rtl"==this.xc()?this.Ee.css({"margin-right":f-1+"px","min-height":c+"px"}):this.Ee.css({"margin-left":f-
1+"px","min-height":c+"px"})}this.Ee.addClass("oj-tabs-panel").attr("role","tabpanel")},ap:function(a){Array.isArray(a)&&(a.length?a.length===this.Na.length&&(a=!0):a=!1);this.Na.each(function(b){!0===a||-1!==e.inArray(b,a)?e(this).addClass("oj-disabled").attr("aria-disabled","true"):e(this).removeClass("oj-disabled").removeAttr("aria-disabled")});this.options.disabled=a},mi:function(){this.element.on("mousedown"+this.eventNamespace,".oj-tabs-nav \x3e li",function(a){e(this).is(".oj-disabled")&&a.preventDefault()});
var a={keydown:this.HN},b=this.options.selectOn;if(b){var c=this;e.each(b.split(" "),function(b,d){a[d]=c.fy})}b=this.Na.not(".oj-disabled");this._on(b,a);this._on(this.Ee,{keydown:this.TL});if(this.options.removable){var f={click:this.XA};this._on(b.find(".oj-tabs-close-icon"),f)}this._focusable(b);this._hoverable(b);this.xq(b)},Hl:function(){var a=this.Na.not(".oj-disabled");this._off(a);this._off(this.Ee);this.element.off("mousedown"+this.eventNamespace)},fy:function(a){var b=this.options,c=this.aa,
f=e(a.currentTarget).closest("li"),h=f[0]===c[0],g=this.Sh(f),k=c.length?this.Sh(c):e(),c={oldHeader:c,oldContent:k,newHeader:f,newContent:g};a.preventDefault();f.hasClass("oj-disabled")||(this.yu||h||!this.jl&&!1===this._trigger("beforeDeselect",a,c)||!1===this._trigger("beforeSelect",a,c))||(b.selected=this.Na.index(f),this.aa=h?e():f,k.length||g.length||e.error("OJ Tabs: Mismatching fragment identifier."),this.ON(a,c))},ON:function(a,b){var c=this,f=b.newContent,h=b.oldContent;this.yu=!0;b.oldHeader.closest("li").removeClass("oj-tabs-active");
h.hide();b.newHeader.closest("li").addClass("oj-tabs-active");f.show();(function(){c.yu=!1;this.jl||c._trigger("afterDeselect",a,b);c._trigger("afterSelect",a,b);var e=-1,f=-1;if(b){var h=b.oldHeader;h&&(e=c.Na.index(h));(h=b.newHeader)&&(f=c.Na.index(h))}c.Qe("selected",e,f,a?!0:!1)})();h.attr({"aria-expanded":"false","aria-hidden":"true"});b.oldHeader.attr("aria-selected","false");f.length&&h.length?b.oldHeader.attr("tabIndex","-1"):f.length&&this.Na.filter(function(){return"0"===e(this).attr("tabIndex")}).attr("tabIndex",
"-1");f.attr({"aria-expanded":"true","aria-hidden":"false"});b.newHeader.attr({"aria-selected":"true",tabIndex:"0"})},zg:function(a){var b=this.ny(a);b[0]!==this.aa[0]&&(b.length||(b=this.aa),this.options.selected=a,a=b.find(".oj-tabs-anchor")[0],this.fy({target:a,currentTarget:a,preventDefault:e.noop}))},ny:function(a){return this.Na.eq(a)},MH:function(){if(this.options.removable){var a=this.options.removeCueText;this.Na.not(".oj-disabled").each(function(){var b=e(this).find("\x3e :first-child"),
c=e(b).find("\x3e :first-child");e("\x3cspan\x3e").addClass("oj-helper-hidden-accessible").attr({role:"presentation"}).text(a).appendTo(c);e("\x3ca href\x3d'#'\x3e").addClass("oj-tabs-icon oj-component-icon oj-clickable-icon oj-tabs-close-icon").attr({tabIndex:"-1","aria-labelledby":e(this).attr("id"),role:"presentation"}).appendTo(b)})}},qI:function(){this.Na.find("oj-tabs-close-icon").remove()},Ux:function(){this.dp=!1;this.kz&&(b.xa.Cm(this.element[0],e.proxy(this.Wh,this)),this.kz=!1,this.hA=
void 0);this.dh?(this.dh.ojConveyorBelt("destroy"),this.dh.remove(),this.aa=this.dh=null):this.element.children(".oj-tabs-nav").remove()},_destroy:function(){var a=this.options.orientation;"vertical"==a?this.element.removeClass("oj-tabs-vertical oj-component oj-helper-clearfix"):this.element.removeClass("oj-tabs oj-component ");this.Ux();var b=this;this.Ee.each(function(){e(this).removeAttr("tabIndex").removeAttr("aria-expanded").removeAttr("aria-selected").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("role").removeClass("oj-active oj-disabled oj-tabs-panel").css("display",
"");"vertical"==a&&e(this).css("margin-left","").css("min-height","");var c=e(this).find("\x3e :first-child");c.css("display","").removeAttr("aria-hidden");b.VA(c)})},enable:function(a){var b=this.options.disabled;!1!==b&&(b=void 0===a?!1:Array.isArray(b)?e.map(b,function(b){return b!==a?b:null}):e.map(this.Na,function(b,d){return d!==a?d:null}),this.ap(b))},disable:function(a){var b=this.options.disabled;if(!0!==b){if(void 0===a)b=!0;else{if(-1!==e.inArray(a,b))return;b=Array.isArray(b)?e.merge([a],
b).sort():[a]}this.ap(b)}},sN:function(a){a!==this.options.removable&&(this.options.removable=a,this.refresh())},XA:function(a){var b=e(a.currentTarget).closest("li"),c=this.Sh(b),f={tab:b,panel:c};if(b&&!1!==this._trigger("beforeRemove",a,f)){var h=this.Na.index(b);b.hasClass("oj-tabs-active")?this.options.selected=this.KG(h):h<this.options.selected&&(this.options.selected=Math.max(0,this.options.selected-1));if(Array.isArray(this.options.disabled))for(var g=this.options.disabled,k=g.length-1;0<=
k;k--)h==g[k]?this.options.disabled=g=g.splice(k,1):h<g[k]&&(g[k]-=1);c.remove();b.remove();this.refresh();this._trigger("afterRemove",a,f)}},addTab:function(a){this.element.append(a);a=this.options;if(-1==a.selected){a.selected=this.Na.length;var b=this.Na.filter(".oj-disabled"),c=this;a.disabled=e.map(b,function(a){return c.Na.index(a)})}this.refresh()},EB:function(){var a=this.dh?this.dh.find(".oj-tabs-nav"):this.element.children(".oj-tabs-nav");if(this.options.reorderable){var b=this;a.sortable({axis:"horizontal"==
b.options.orientation?"x":"y",stop:function(c,e){var h=e.item,g=b.Sh(h),h=h.prev();h.length?b.Sh(h).after(g):a.after(g)}})}else a.sortable({disabled:!0})},DB:function(a){a||(a=this.options.orientation);if("horizontal"==a)"vertical"==this.options.orientation&&this.Ee&&this.Ee.each(function(){e(this).css("margin-left","").css("min-height","")}),this.element.addClass("oj-tabs oj-component");else if("vertical"==a)this.element.addClass("oj-tabs-vertical oj-component oj-helper-clearfix");else return;this.options.orientation=
a},ZM:function(a){return a?a.replace(/[!"$%&'()*+,.\/:;<=>?@\[\]\^`{|}~]/g,"\\$\x26"):""},Sh:function(a){a=e(a).attr("aria-controls");return this.element.find(this.ZM("#"+a))},Aw:function(a){0>a.id.indexOf("ojtabs-id_")&&e(a).attr("id","ojtabs-id_"+a.id)},UA:function(a){0==a.id.indexOf("ojtabs-id_")&&e(a).attr("id",a.id.substring(10))},VA:function(a){var b=this,c=a[0];c.id&&this.UA(c);a.find("[id]").each(function(){b.UA(this)})},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:
null;var b=a.subId;a=a.index;switch(b){case "oj-conveyorbelt":return this.dh?this.dh[0]:null;case "oj-tabs-panel":return this.Ee[a];case "oj-tabs-title":return this.Hm[a];case "oj-tabs-close-icon":return this.Na.eq(a).find("."+b)[0]}return null},az:function(){return this.element[0].clientWidth},Dz:function(){return this.hA>this.az()},IR:o_c("dp"),wB:o_b("dp"),LJ:function(){var a=Math.floor(this.az()/this.Na.length);this.options.removable&&(a-=28);return a},Lw:function(){if(!this.dp){var a=this.LJ();
this.Hm.each(function(){e(this).css("max-width",""+a+"px").addClass("oj-tabs-title-overflow")});this.wB(!0)}},LM:function(){this.dp&&(this.Hm.each(function(){e(this).css("max-width","").removeClass("oj-tabs-title-overflow")}),this.wB(!1))},MR:o_a(),Wh:function(){this.Dz()?this.Lw():this.LM()},$y:function(){var a=this.Gm.parent();a.hasClass("oj-tabs-conveyor")||(a=this.Gm.wrap("\x3cdiv\x3e").parent().addClass("oj-tabs-conveyor"));return a},eL:function(){return"auto"==this.options.truncation||"progressive"==
this.options.truncation},TN:function(){"horizontal"==this.options.orientation&&(0<this.Na.length&&this.eL())&&(b.xa.$g(this.element[0],e.proxy(this.Wh,this)),this.kz=!0,this.hA=this.$y()[0].scrollWidth,this.Dz()&&this.Lw())},Qe:function(a,b,c,e){this._trigger("optionChange",e,{option:a,previousValue:b,value:c,optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}})}})})()});
//# sourceMappingURL=oj-modular.map