define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(b,e){b.ha=function(a){a=a||{};this.Dm=a.root;this.xO=a.childCollectionCallback;this.ak=a.parseMetadata;this.Ci=null;this.gk="none";this.hc={};b.ha.j.constructor.call(this)};o_("CollectionTreeDataSource",b.ha,b);b.ha.prototype.ak=function(a){return{key:a.idAttribute+"\x3d"+a.id}};b.a.fa(b.ha,b.bc,"oj.CollectionTreeDataSource");b.ha.prototype.Init=function(){b.ha.j.Init.call(this)};b.a.b("CollectionTreeDataSource.prototype.Init",
{Init:b.ha.prototype.Init});b.ha.prototype.we=function(a){var b=this.hc[a];if(b&&0<b.length)return b.length;this.Jt(a,{success:function(a){return a.length}});return-1};b.a.b("CollectionTreeDataSource.prototype.getChildCount",{we:b.ha.prototype.we});b.ha.prototype.Jt=function(a,b){this.sd(a,null,{success:function(a){b.success(a.ba)},error:b.error})};b.a.b("CollectionTreeDataSource.prototype.getChildCollection",{Jt:b.ha.prototype.Jt});b.ha.prototype.sd=function(a,b,c){b=b||{};var e=b.start?b.start:
0,h=b.count?b.count:-1;if(null===a)this.kk(null,e,h,c,null);else{var g=this;this.Or(this.Dm,a,0).done(function(b){b?(b=g.Nm(b.ed),g.kk(b,e,h,c,a)):c&&c.error&&c.error(a)})}};b.a.b("CollectionTreeDataSource.prototype.fetchChildren",{sd:b.ha.prototype.sd});b.ha.prototype.ME=function(a,b,c){var e=0;c&&c.at&&(e=c.at);a=this.On(this,"insert",e,this.qo(b),this.uA(a));this.handleEvent("insert",a)};b.ha.prototype.NE=function(a,b,c){var e=0;c&&c.index&&(e=c.index);this.GM(a);a=this.On(this,"delete",e,this.qo(b),
null);this.handleEvent("delete",a)};b.ha.prototype.OE=function(a){var b=this.VI(a),c=null,e=null;b&&(c=b.index,e=this.qo(b.ba));a=this.On(this,"update",c,e,this.uA(a));this.handleEvent("update",a)};b.ha.prototype.xE=function(a){a=this.On(this,"refresh",null,this.qo(a),null);this.handleEvent("refresh",a)};b.ha.prototype.uA=function(a){var d=[];d.push(a.attributes);var c={};c.idAttribute=a.idAttribute;a=new b.Z(d,c);a.fetch();return a};b.ha.prototype.qo=function(a){var d=[],c=null;do c=this.zJ(a),null!==
c&&(c!==b.ha.bv&&d.unshift(c),a=this.WI(c));while(null!=c);return d};b.ha.bv="%!@ROOT%#@!";b.ha.prototype.ho=function(a){var d=a instanceof b.i?this.ak(a).key:a;return a?d:b.ha.bv};b.ha.prototype.vw=function(a){return this.hc[this.ho(a)]};b.ha.prototype.oB=function(a,d){d.on(b.N.l.ADD,this.ME,this);d.on(b.N.l.REMOVE,this.NE,this);d.on(b.N.l.CHANGE,this.OE,this);d.on(b.N.l.SYNC,this.xE,this);this.hc[this.ho(a)]=d};b.ha.prototype.GM=function(a){a=this.ho(a);for(var b in this.hc)if(this.hc.hasOwnProperty(b)&&
b===a){this.hc[a].off(null,null,this);delete this.hc[a];break}};b.ha.prototype.mL=function(a,b){for(var c=b.length,e=0;e<c;e++){var h=this.ho(b.at(e));if(a===h)return!0}return!1};b.ha.prototype.VI=function(a){for(var b in this.hc)if(this.hc.hasOwnProperty(b))for(var c=this.hc[b],e=0;e<c.length;e++)if(c.at(e)===a)return{index:e,ba:c};return null};b.ha.prototype.WI=function(a){for(var b in this.hc)if(this.hc.hasOwnProperty(b)){var c=this.hc[b];if(this.mL(a,c))return c}return null};b.ha.prototype.zJ=
function(a){for(var b in this.hc)if(this.hc.hasOwnProperty(b)&&this.hc[b]===a)return b;return null};b.ha.prototype.Nm=function(a){var b=!0,c=this.vw(a);c||(b=!1,c=this.xO(this.Dm,a),null!=c&&(this.Kw(c),this.oB(a,c)));return{ba:c,ut:b}};b.ha.prototype.On=function(a,b,c,e,h){return{source:a,operation:b,index:c,parent:e,data:h}};b.ha.prototype.kk=function(a,b,c,e,h){var g=this;null===a&&((a=this.vw(null))?a={ba:a,ut:!0}:(a={ba:g.Dm,ut:!1},g.oB(null,this.Dm)));a&&g.iy(a,function(a){e.success&&e.success(g.tJ(a,
h,b,c))},e.error)};b.ha.prototype.tJ=function(a,d,c,e){return new b.tc(d,a,this,c,e)};b.ha.prototype.bN=function(a,b){function c(a,b,d){a<b.length?b.at(a,{deferred:!0}).done(function(e){if(e){var n=h.ak(e);if(d===n.key)return f.resolve(e),f}a++;c(a,b,d)}):f.resolve(null)}var f=e.Deferred(),h=this;c(0,a,b);return f};b.ha.prototype.Or=function(a,b,c){var f=e.Deferred(),h=this;this.bN(a,b).done(function(e){function k(e,g){if(e<l){var h=g.Nm(a.at(e));h.ba?g.iy(h,function(a){g.Or(a,b,c+1).done(function(a){a?
f.resolve(a):(e++,k(e,g))})},null):(e++,k(e,g))}else f.resolve(null)}if(e)return f.resolve({ed:e,depth:c}),f;var l=a.length;k(0,h)});return f.promise()};b.ha.prototype.iy=function(a,b,c){a.ut?b(a.ba):(this.Ci&&"none"!==this.Ci&&(a.ba.ue=this.Ci,a.ba.Eu=this.gk),0<a.ba.length?b(a.ba):a.ba.fetch({success:function(a){b(a)},error:c}))};b.ha.prototype.dg=function(a,b){var c=this;null===a?this.kk(null,0,-1,{success:function(a){a.Su({success:function(){b.success&&b.success(a)}})}},null):this.Or(this.Dm,
a,0).done(function(e){e&&(e=c.Nm(e.ed),c.kk(e,0,-1,{success:function(a){a.Su({success:function(){b.success&&b.success(a)}})}},a))})};b.a.b("CollectionTreeDataSource.prototype.fetchDescendents",{dg:b.ha.prototype.dg});b.ha.prototype.sort=function(a,b){var c=a.key,e=a.direction,h=!1;c!==this.Ci&&(this.Ci=c,h=!0);e!==this.gk&&(this.gk=e,h=!0);if(h){"none"===this.gk&&(this.hc={});for(var g in this.hc)this.hc.hasOwnProperty(g)&&this.Kw(this.hc[g])}b&&b.success&&b.success()};b.a.b("CollectionTreeDataSource.prototype.sort",
{sort:b.ha.prototype.sort});b.ha.prototype.Kw=function(a){a.comparator=this.Ci;a.sortDirection="ascending"===this.gk?1:-1;a.sort()};b.ha.prototype.Zl=function(){return{key:this.Ci,direction:this.gk}};b.a.b("CollectionTreeDataSource.prototype.getSortCriteria",{Zl:b.ha.prototype.Zl});b.ha.prototype.move=function(){b.f.U()};b.a.b("CollectionTreeDataSource.prototype.move",{move:b.ha.prototype.move});b.ha.prototype.ym=o_d("invalid");b.a.b("CollectionTreeDataSource.prototype.moveOK",{ym:b.ha.prototype.ym});
b.ha.prototype.getCapability=function(a){return"sort"===a?"default":"move"===a?"none":"batchFetch"===a||"fetchDescendants"===a?"disable":null};b.a.b("CollectionTreeDataSource.prototype.getCapability",{getCapability:b.ha.prototype.getCapability});b.tc=function(a,b,c,e,h){this.ZP=a;this.ba=b;this.yt=[];this.Im=c;this.start=e<b.length?e:b.length-1;this.count=-1===h?b.length:Math.min(b.length,h)};o_("CollectionNodeSet",b.tc,b);b.tc.prototype.Su=function(a){this.ky(this).done(function(){a.success&&a.success()})};
b.tc.prototype.ky=function(a){function b(e){e<f?a.DE(e,{success:function(c){null!==c?a.ky(c).done(function(){b(e+1)}):b(e+1)}}):c.resolve()}var c=e.Deferred(),f=a.V();b(0);return c.promise()};b.tc.prototype.DE=function(a,b){var c=this.ba.at(a);if(this.Im.ak(c).leaf)this.yt[a]=null,b.success(null);else{var e=this.Im.Nm(c),c=this.Im.ak(c).key,h=this;this.Im.kk(e,0,-1,{success:function(c){h.yt[a]=c;b.success(c)}},c)}};b.tc.prototype.getParent=o_c("ZP");b.a.b("CollectionNodeSet.prototype.getParent",{getParent:b.tc.prototype.getParent});
b.tc.prototype.Ba=o_c("start");b.a.b("CollectionNodeSet.prototype.getStart",{Ba:b.tc.prototype.Ba});b.tc.prototype.V=o_c("count");b.a.b("CollectionNodeSet.prototype.getCount",{V:b.tc.prototype.V});b.tc.prototype.getData=function(a){this.Sq(a);return this.ba.at(a).attributes};b.a.b("CollectionNodeSet.prototype.getData",{getData:b.tc.prototype.getData});b.tc.prototype.Sq=function(a){if(a<this.start||a>this.start+this.count)throw"Out of range";};b.tc.prototype.getMetadata=function(a){this.Sq(a);var b=
{};a=this.ba.at(a);a=this.Im.ak(a);b.key=a.key;b.leaf=a.leaf;b.depth=a.depth;return b};b.a.b("CollectionNodeSet.prototype.getMetadata",{getMetadata:b.tc.prototype.getMetadata});b.tc.prototype.Zc=function(a){this.Sq(a);return this.yt[a]};b.a.b("CollectionNodeSet.prototype.getChildNodeSet",{Zc:b.tc.prototype.Zc})});
//# sourceMappingURL=oj-modular.map