define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){(function(){b.ta("oj.ojTrain",e.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{steps:[],selection:"next",currentStep:"",optionChange:null},fc:0,ea:null,_create:function(){var a=this.options;this._super();this.fc=a.steps.length;this.Aj=(this.Rg="rtl"===this.xc())?"margin-right":"margin-left";this.Nh=this.Rg?"right":"left";var b=e("\x3cdiv class\x3d'oj-train-bar'\x3e\x3c/div\x3e");this.Bj=
this.element.width()<107*(this.fc-1)+72?(this.element.width()-72)/(this.fc-1):107;this.Yq=(this.element.width()-this.Bj*(this.fc-1)-72)/2;this.Te=e("\x3cul\x3e").attr({"aria-label":"Train Component"}).css({margin:"0",padding:"0"});1<this.fc&&b.css({"margin-top":"7px",width:(this.fc-1)*this.Bj+"px"}).css(this.Aj,36+this.Yq+"px").css(this.Nh,0);b.appendTo(this.element);this.GA=e("\x3cdiv class\x3d'oj-train-bar-overlay'\x3e\x3c/div\x3e");this.GA.appendTo(this.element);this.SN();this.pe=this.rJ(a.currentStep);
for(b=0;b<this.fc;b++){var c=e("\x3cli\x3e").attr({id:this.ea[b][1]}).css({"list-style-type":"none",position:"absolute"}).css(this.Aj,this.Yq+this.Bj*b+"px").css(this.Nh,0);this.Te.append(c);b==this.pe+1&&"next"==a.selection&&(this.ea[b][2]="on");this.$k(b);this.ry(b);this.Zk(b);this.qy(b)}this.rC();this.element.addClass("oj-train oj-component oj-component-content oj-corner-all")},rC:function(){this.GA.css({"margin-top":"7px",width:(this.pe===this.fc-1?(this.fc-1)*this.Bj:this.Bj*this.pe+53.5*(this.Bj/
107))+"px"}).css(this.Aj,this.Yq+36+"px").css(this.Nh,0);this.Te.appendTo(this.element)},SN:function(){var a=this.options;this.ea=[];for(var b=0;b<this.fc;b++){var c=a.steps[b];this.ea[b]=Array(5);this.ea[b][2]=a.selection&&"next"!=a.selection?a.selection:"off";this.ea[b][3]="unvisited";for(var e in c)"name"===e?this.ea[b][0]=c[e]:"id"===e?this.ea[b][1]=c[e]:"selection"===e?this.ea[b][2]=c[e]:"state"===e?this.ea[b][3]=c[e]:"messageType"===e&&(this.ea[b][4]=c[e])}},Zk:function(a){var b=e("\x3cdiv/\x3e"),
c=e("\x3cspan/\x3e"),f=this,h="";if(this.ea[a]){var g=this.ea[a][3];this.pe===a?(b.addClass("oj-train-button-current"),h=". This is the current step."):"visited"===g?(b.addClass("oj-train-button-visited"),h=". This step has been visited."):"unvisited"===g?(b.addClass("oj-train-button-unvisited"),h=". This step has not been visited yet."):b.addClass("oj-train-button-disabled");"disabled"===this.ea[a][3]||null!=this.options.disabled&&this.options.disabled||"on"!==this.ea[a][2]||(this._hoverable(b),
b.bind("click"+this.eventNamespace,function(){var a=f.options.currentStep;f.options.currentStep=this.parentNode.id;f.Qe("currentStep",a,this.parentNode.id,!0)}));b.css({"margin-top":"4px",width:"12px",height:"12px"}).css(this.Aj,"29px").css(this.Nh,0);g=this.Te.children().eq(a).children();3<=g.length?(g[2].remove(),b.insertAfter(g[1])):this.Te.children().eq(a).append(b);c.text(h);c.css("display","none");this.Te.children().eq(a).find("a").append(c)}},qy:function(a){var b=e("\x3cdiv/\x3e"),c=e("\x3cspan/\x3e"),
f="",h=this;if(this.ea[a]){var g=this.ea[a][4];"complete"===g?(b.addClass("oj-train-icon-complete"),f=" Complete"):"info"===g?(b.addClass("oj-train-icon-info"),f=" Info"):"error"===g?(b.addClass("oj-train-icon-error"),f=" Error"):"warning"===g&&(b.addClass("oj-train-icon-warning"),f=" Warning");var k=this.Te.children().eq(a).children();4<=k.length&&k[3].remove();"disabled"===this.ea[a][3]||null!=this.options.disabled&&this.options.disabled||"on"!==this.ea[a][2]||(this._hoverable(b),b.bind("click"+
this.eventNamespace,function(){var a=h.options.currentStep;h.options.currentStep=this.parentNode.id;h.Qe("currentStep",a,this.parentNode.id,!0)}));null!=g&&"none"!=g&&(b.css({"margin-top":"9px",height:"9px",width:"9px"}).css(this.Aj,"34px").css(this.Nh,0),c.text(f),c.css("display","none"),this.Te.children().eq(a).find("a").append(c),this.Te.children().eq(a).append(b))}},Qe:function(a,b,c,e){this._trigger("optionChange",e,{option:a,previousValue:b,value:c,optionMetadata:{writeback:e?"shouldWrite":
"shouldNotWrite"}})},ry:function(a){var b=e("\x3cdiv/\x3e");this.ea[a]&&(a<=this.pe?b.addClass("oj-train-stepBackground-overlay"):b.addClass("oj-train-stepBackground"),b.css(this.Aj,"25px").css(this.Nh,0),a=this.Te.children().eq(a).children(),1<a.length&&a[1].remove(),b.insertAfter(a[0]))},$k:function(a){var b=this;if(this.ea[a]){var c=e("\x3ca\x3e"+this.ea[a][0]+"\x3c/a\x3e");c.addClass("oj-train-label");c.css("margin-bottom","7px");c.css(this.Nh,0);a===this.pe?c.addClass("oj-selected"):"visited"===
this.ea[a][3]?c.addClass("oj-visited"):"disabled"===this.ea[a][3]&&c.addClass("oj-disabled");"on"!==this.ea[a][2]||null!=this.options.disabled&&this.options.disabled||(c.attr("href","#"),this._hoverable(c),c.bind("click keydown"+this.eventNamespace,function(a){if(13==a.keyCode||"click"==a.type)a=b.options.currentStep,b.options.currentStep=this.parentNode.id,b.Qe("currentStep",a,this.parentNode.id,!0)}));var f=this.Te.children().eq(a).children();1<=f.length&&f[0].remove();this.Te.children().eq(a).prepend(c)}},
rJ:function(a){for(var b=0;b<this.fc;b++)if(this.ea[b]&&this.ea[b][1]===a)return b;return 0},getStepName:function(a){for(var b=0;b<this.fc;b++)if(this.ea[b]&&this.ea[b][1]===a)return this.ea[b][0];return null},getStepId:function(a){for(var b=0;b<this.fc;b++)if(this.ea[b]&&this.ea[b][0]===a)return this.ea[b][1];return null},select:function(a){for(var b=0;b<this.fc;b++)if(this.ea[b]&&this.ea[b][1]===a){"next"===this.options.selection&&b+1<this.fc&&(this.ea[b+1][2]="on",this.$k(b+1),this.Zk(b+1));this.ea[b][3]=
"current";this.pe=b;this.options.currentStep=a;this.$k(b);this.Zk(b);this.rC();break}for(b=0;b<this.fc;b++)this.ry(b)},deselect:function(a,b,c,e){for(var h=0;h<this.fc;h++)if(this.ea[h]&&this.ea[h][1]===a){b?this.ea[h][2]=b:this.ea[h][2]="off";c?this.ea[h][3]=c:this.ea[h][3]="visited";e?this.ea[h][4]=e:this.ea[h][4]="none";this.pe=-1;"next"===this.options.selection&&h+1<this.fc&&(this.ea[h+1][2]="off",this.$k(h+1),this.Zk(h+1));this.$k(h);this.Zk(h);this.qy(h);break}},nextSelectableStep:function(){for(var a=
this.pe;a<this.fc;a++)if(a+1<this.fc&&this.ea[a+1]&&"on"===this.ea[a+1][2])return this.ea[a+1][1];return this.ea[this.pe][1]},previousSelectableStep:function(){for(var a=this.pe;0<=a;a--)if(this.ea[a-1]&&"on"===this.ea[a-1][2])return this.ea[a-1][1];return this.ea[this.pe][1]}})})()});
//# sourceMappingURL=oj-modular.map