define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(b,e){b.ha=function(a){a=a||{};this.Mm=a.root;this.TO=a.childCollectionCallback;this.kk=a.parseMetadata;this.Ji=null;this.qk="none";this.ic={};b.ha.j.constructor.call(this)};o_("CollectionTreeDataSource",b.ha,b);b.ha.prototype.kk=function(a){return{key:a.idAttribute+"\x3d"+a.id}};b.a.ga(b.ha,b.cc,"oj.CollectionTreeDataSource");b.ha.prototype.Init=function(){b.ha.j.Init.call(this)};b.a.c("CollectionTreeDataSource.prototype.Init",
{Init:b.ha.prototype.Init});b.ha.prototype.ye=function(a){var b=this.ic[a];if(b&&0<b.length)return b.length;this.Yt(a,{success:function(a){return a.length}});return-1};b.a.c("CollectionTreeDataSource.prototype.getChildCount",{ye:b.ha.prototype.ye});b.ha.prototype.Yt=function(a,b){this.vd(a,null,{success:function(a){b.success(a.ba)},error:b.error})};b.a.c("CollectionTreeDataSource.prototype.getChildCollection",{Yt:b.ha.prototype.Yt});b.ha.prototype.vd=function(a,b,c){b=b||{};var e=b.start?b.start:
0,h=b.count?b.count:-1;if(null===a)this.uk(null,e,h,c,null);else{var g=this;this.Yr(this.Mm,a,0).done(function(b){b?(b=g.Xm(b.gd),g.uk(b,e,h,c,a)):c&&c.error&&c.error(a)})}};b.a.c("CollectionTreeDataSource.prototype.fetchChildren",{vd:b.ha.prototype.vd});b.ha.prototype.aF=function(a,b,c){var e=0;c&&c.at&&(e=c.at);a=this.Vn(this,"insert",e,this.xo(b),this.HA(a));this.handleEvent("insert",a)};b.ha.prototype.bF=function(a,b,c){var e=0;c&&c.index&&(e=c.index);this.$M(a);a=this.Vn(this,"delete",e,this.xo(b),
null);this.handleEvent("delete",a)};b.ha.prototype.cF=function(a){var b=this.nJ(a),c=null,e=null;b&&(c=b.index,e=this.xo(b.ba));a=this.Vn(this,"update",c,e,this.HA(a));this.handleEvent("update",a)};b.ha.prototype.ME=function(a){a=this.Vn(this,"refresh",null,this.xo(a),null);this.handleEvent("refresh",a)};b.ha.prototype.HA=function(a){var d=[];d.push(a.attributes);var c={};c.idAttribute=a.idAttribute;a=new b.Z(d,c);a.fetch();return a};b.ha.prototype.xo=function(a){var d=[],c=null;do c=this.SJ(a),null!==
c&&(c!==b.ha.ov&&d.unshift(c),a=this.oJ(c));while(null!=c);return d};b.ha.ov="%!@ROOT%#@!";b.ha.prototype.oo=function(a){var d=a instanceof b.i?this.kk(a).key:a;return a?d:b.ha.ov};b.ha.prototype.Iw=function(a){return this.ic[this.oo(a)]};b.ha.prototype.AB=function(a,d){d.on(b.N.q.ADD,this.aF,this);d.on(b.N.q.REMOVE,this.bF,this);d.on(b.N.q.CHANGE,this.cF,this);d.on(b.N.q.SYNC,this.ME,this);this.ic[this.oo(a)]=d};b.ha.prototype.$M=function(a){a=this.oo(a);for(var b in this.ic)if(this.ic.hasOwnProperty(b)&&
b===a){this.ic[a].off(null,null,this);delete this.ic[a];break}};b.ha.prototype.IL=function(a,b){for(var c=b.length,e=0;e<c;e++){var h=this.oo(b.at(e));if(a===h)return!0}return!1};b.ha.prototype.nJ=function(a){for(var b in this.ic)if(this.ic.hasOwnProperty(b))for(var c=this.ic[b],e=0;e<c.length;e++)if(c.at(e)===a)return{index:e,ba:c};return null};b.ha.prototype.oJ=function(a){for(var b in this.ic)if(this.ic.hasOwnProperty(b)){var c=this.ic[b];if(this.IL(a,c))return c}return null};b.ha.prototype.SJ=
function(a){for(var b in this.ic)if(this.ic.hasOwnProperty(b)&&this.ic[b]===a)return b;return null};b.ha.prototype.Xm=function(a){var b=!0,c=this.Iw(a);c||(b=!1,c=this.TO(this.Mm,a),null!=c&&(this.Yw(c),this.AB(a,c)));return{ba:c,Ht:b}};b.ha.prototype.Vn=function(a,b,c,e,h){return{source:a,operation:b,index:c,parent:e,data:h}};b.ha.prototype.uk=function(a,b,c,e,h){var g=this;null===a&&((a=this.Iw(null))?a={ba:a,Ht:!0}:(a={ba:g.Mm,Ht:!1},g.AB(null,this.Mm)));a&&g.wy(a,function(a){e.success&&e.success(g.MJ(a,
h,b,c))},e.error)};b.ha.prototype.MJ=function(a,d,c,e){return new b.tc(d,a,this,c,e)};b.ha.prototype.xN=function(a,b){function c(a,b,d){a<b.length?b.at(a,{deferred:!0}).done(function(e){if(e){var n=h.kk(e);if(d===n.key)return f.resolve(e),f}a++;c(a,b,d)}):f.resolve(null)}var f=e.Deferred(),h=this;c(0,a,b);return f};b.ha.prototype.Yr=function(a,b,c){var f=e.Deferred(),h=this;this.xN(a,b).done(function(e){function k(e,g){if(e<l){var h=g.Xm(a.at(e));h.ba?g.wy(h,function(a){g.Yr(a,b,c+1).done(function(a){a?
f.resolve(a):(e++,k(e,g))})},null):(e++,k(e,g))}else f.resolve(null)}if(e)return f.resolve({gd:e,depth:c}),f;var l=a.length;k(0,h)});return f.promise()};b.ha.prototype.wy=function(a,b,c){a.Ht?b(a.ba):(this.Ji&&"none"!==this.Ji&&(a.ba.we=this.Ji,a.ba.Su=this.qk),0<a.ba.length?b(a.ba):a.ba.fetch({success:function(a){b(a)},error:c}))};b.ha.prototype.hg=function(a,b){var c=this;null===a?this.uk(null,0,-1,{success:function(a){a.ev({success:function(){b.success&&b.success(a)}})}},null):this.Yr(this.Mm,
a,0).done(function(e){e&&(e=c.Xm(e.gd),c.uk(e,0,-1,{success:function(a){a.ev({success:function(){b.success&&b.success(a)}})}},a))})};b.a.c("CollectionTreeDataSource.prototype.fetchDescendents",{hg:b.ha.prototype.hg});b.ha.prototype.sort=function(a,b){var c=a.key,e=a.direction,h=!1;c!==this.Ji&&(this.Ji=c,h=!0);e!==this.qk&&(this.qk=e,h=!0);if(h){"none"===this.qk&&(this.ic={});for(var g in this.ic)this.ic.hasOwnProperty(g)&&this.Yw(this.ic[g])}b&&b.success&&b.success()};b.a.c("CollectionTreeDataSource.prototype.sort",
{sort:b.ha.prototype.sort});b.ha.prototype.Yw=function(a){a.comparator=this.Ji;a.sortDirection="ascending"===this.qk?1:-1;a.sort()};b.ha.prototype.jm=function(){return{key:this.Ji,direction:this.qk}};b.a.c("CollectionTreeDataSource.prototype.getSortCriteria",{jm:b.ha.prototype.jm});b.ha.prototype.move=function(){b.f.V()};b.a.c("CollectionTreeDataSource.prototype.move",{move:b.ha.prototype.move});b.ha.prototype.Hm=o_d("invalid");b.a.c("CollectionTreeDataSource.prototype.moveOK",{Hm:b.ha.prototype.Hm});
b.ha.prototype.getCapability=function(a){return"sort"===a?"default":"move"===a?"none":"batchFetch"===a||"fetchDescendants"===a?"disable":null};b.a.c("CollectionTreeDataSource.prototype.getCapability",{getCapability:b.ha.prototype.getCapability});b.tc=function(a,b,c,e,h){this.uQ=a;this.ba=b;this.Mt=[];this.Rm=c;this.start=e<b.length?e:b.length-1;this.count=-1===h?b.length:Math.min(b.length,h)};o_("CollectionNodeSet",b.tc,b);b.tc.prototype.ev=function(a){this.yy(this).done(function(){a.success&&a.success()})};
b.tc.prototype.yy=function(a){function b(e){e<f?a.SE(e,{success:function(c){null!==c?a.yy(c).done(function(){b(e+1)}):b(e+1)}}):c.resolve()}var c=e.Deferred(),f=a.W();b(0);return c.promise()};b.tc.prototype.SE=function(a,b){var c=this.ba.at(a);if(this.Rm.kk(c).leaf)this.Mt[a]=null,b.success(null);else{var e=this.Rm.Xm(c),c=this.Rm.kk(c).key,h=this;this.Rm.uk(e,0,-1,{success:function(c){h.Mt[a]=c;b.success(c)}},c)}};b.tc.prototype.getParent=o_c("uQ");b.a.c("CollectionNodeSet.prototype.getParent",{getParent:b.tc.prototype.getParent});
b.tc.prototype.Ba=o_c("start");b.a.c("CollectionNodeSet.prototype.getStart",{Ba:b.tc.prototype.Ba});b.tc.prototype.W=o_c("count");b.a.c("CollectionNodeSet.prototype.getCount",{W:b.tc.prototype.W});b.tc.prototype.getData=function(a){this.br(a);return this.ba.at(a).attributes};b.a.c("CollectionNodeSet.prototype.getData",{getData:b.tc.prototype.getData});b.tc.prototype.br=function(a){if(a<this.start||a>this.start+this.count)throw"Out of range";};b.tc.prototype.getMetadata=function(a){this.br(a);var b=
{};a=this.ba.at(a);a=this.Rm.kk(a);b.key=a.key;b.leaf=a.leaf;b.depth=a.depth;return b};b.a.c("CollectionNodeSet.prototype.getMetadata",{getMetadata:b.tc.prototype.getMetadata});b.tc.prototype.bd=function(a){this.br(a);return this.Mt[a]};b.a.c("CollectionNodeSet.prototype.getChildNodeSet",{bd:b.tc.prototype.bd})});
//# sourceMappingURL=oj-modular.map