define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,e){(function(){b.ta("oj.ojTrain",e.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{steps:[],selection:"next",currentStep:"",optionChange:null},ec:0,ea:null,_create:function(){var a=this.options;this._super();this.ec=a.steps.length;this.sj=(this.Ng="rtl"===this.xc())?"margin-right":"margin-left";this.Gh=this.Ng?"right":"left";var b=e("\x3cdiv class\x3d'oj-train-bar'\x3e\x3c/div\x3e");this.tj=
this.element.width()<107*(this.ec-1)+72?(this.element.width()-72)/(this.ec-1):107;this.Oq=(this.element.width()-this.tj*(this.ec-1)-72)/2;this.Te=e("\x3cul\x3e").attr({"aria-label":"Train Component"}).css({margin:"0",padding:"0"});1<this.ec&&b.css({"margin-top":"7px",width:(this.ec-1)*this.tj+"px"}).css(this.sj,36+this.Oq+"px").css(this.Gh,0);b.appendTo(this.element);this.tA=e("\x3cdiv class\x3d'oj-train-bar-overlay'\x3e\x3c/div\x3e");this.tA.appendTo(this.element);this.wN();this.me=this.ZI(a.currentStep);
for(b=0;b<this.ec;b++){var c=e("\x3cli\x3e").attr({id:this.ea[b][1]}).css({"list-style-type":"none",position:"absolute"}).css(this.sj,this.Oq+this.tj*b+"px").css(this.Gh,0);this.Te.append(c);b==this.me+1&&"next"==a.selection&&(this.ea[b][2]="on");this.Ok(b);this.dy(b);this.Nk(b);this.by(b)}this.fC();this.element.addClass("oj-train oj-component oj-component-content oj-corner-all")},fC:function(){this.tA.css({"margin-top":"7px",width:(this.me===this.ec-1?(this.ec-1)*this.tj:this.tj*this.me+53.5*(this.tj/
107))+"px"}).css(this.sj,this.Oq+36+"px").css(this.Gh,0);this.Te.appendTo(this.element)},wN:function(){var a=this.options;this.ea=[];for(var b=0;b<this.ec;b++){var c=a.steps[b];this.ea[b]=Array(5);this.ea[b][2]=a.selection&&"next"!=a.selection?a.selection:"off";this.ea[b][3]="unvisited";for(var e in c)"name"===e?this.ea[b][0]=c[e]:"id"===e?this.ea[b][1]=c[e]:"selection"===e?this.ea[b][2]=c[e]:"state"===e?this.ea[b][3]=c[e]:"messageType"===e&&(this.ea[b][4]=c[e])}},Nk:function(a){var b=e("\x3cdiv/\x3e"),
c=e("\x3cspan/\x3e"),f=this,h="";if(this.ea[a]){var g=this.ea[a][3];this.me===a?(b.addClass("oj-train-button-current"),h=". This is the current step."):"visited"===g?(b.addClass("oj-train-button-visited"),h=". This step has been visited."):"unvisited"===g?(b.addClass("oj-train-button-unvisited"),h=". This step has not been visited yet."):b.addClass("oj-train-button-disabled");"disabled"===this.ea[a][3]||null!=this.options.disabled&&this.options.disabled||"on"!==this.ea[a][2]||(this._hoverable(b),
b.bind("click"+this.eventNamespace,function(){var a=f.options.currentStep;f.options.currentStep=this.parentNode.id;f.Qe("currentStep",a,this.parentNode.id,!0)}));b.css({"margin-top":"4px",width:"12px",height:"12px"}).css(this.sj,"29px").css(this.Gh,0);g=this.Te.children().eq(a).children();3<=g.length?(g[2].remove(),b.insertAfter(g[1])):this.Te.children().eq(a).append(b);c.text(h);c.css("display","none");this.Te.children().eq(a).find("a").append(c)}},by:function(a){var b=e("\x3cdiv/\x3e"),c=e("\x3cspan/\x3e"),
f="",h=this;if(this.ea[a]){var g=this.ea[a][4];"complete"===g?(b.addClass("oj-train-icon-complete"),f=" Complete"):"info"===g?(b.addClass("oj-train-icon-info"),f=" Info"):"error"===g?(b.addClass("oj-train-icon-error"),f=" Error"):"warning"===g&&(b.addClass("oj-train-icon-warning"),f=" Warning");var k=this.Te.children().eq(a).children();4<=k.length&&k[3].remove();"disabled"===this.ea[a][3]||null!=this.options.disabled&&this.options.disabled||"on"!==this.ea[a][2]||(this._hoverable(b),b.bind("click"+
this.eventNamespace,function(){var a=h.options.currentStep;h.options.currentStep=this.parentNode.id;h.Qe("currentStep",a,this.parentNode.id,!0)}));null!=g&&"none"!=g&&(b.css({"margin-top":"9px",height:"9px",width:"9px"}).css(this.sj,"34px").css(this.Gh,0),c.text(f),c.css("display","none"),this.Te.children().eq(a).find("a").append(c),this.Te.children().eq(a).append(b))}},Qe:function(a,b,c,e){this._trigger("optionChange",e,{option:a,previousValue:b,value:c,optionMetadata:{writeback:e?"shouldWrite":
"shouldNotWrite"}})},dy:function(a){var b=e("\x3cdiv/\x3e");this.ea[a]&&(a<=this.me?b.addClass("oj-train-stepBackground-overlay"):b.addClass("oj-train-stepBackground"),b.css(this.sj,"25px").css(this.Gh,0),a=this.Te.children().eq(a).children(),1<a.length&&a[1].remove(),b.insertAfter(a[0]))},Ok:function(a){var b=this;if(this.ea[a]){var c=e("\x3ca\x3e"+this.ea[a][0]+"\x3c/a\x3e");c.addClass("oj-train-label");c.css("margin-bottom","7px");c.css(this.Gh,0);a===this.me?c.addClass("oj-selected"):"visited"===
this.ea[a][3]?c.addClass("oj-visited"):"disabled"===this.ea[a][3]&&c.addClass("oj-disabled");"on"!==this.ea[a][2]||null!=this.options.disabled&&this.options.disabled||(c.attr("href","#"),this._hoverable(c),c.bind("click keydown"+this.eventNamespace,function(a){if(13==a.keyCode||"click"==a.type)a=b.options.currentStep,b.options.currentStep=this.parentNode.id,b.Qe("currentStep",a,this.parentNode.id,!0)}));var f=this.Te.children().eq(a).children();1<=f.length&&f[0].remove();this.Te.children().eq(a).prepend(c)}},
ZI:function(a){for(var b=0;b<this.ec;b++)if(this.ea[b]&&this.ea[b][1]===a)return b;return 0},getStepName:function(a){for(var b=0;b<this.ec;b++)if(this.ea[b]&&this.ea[b][1]===a)return this.ea[b][0];return null},getStepId:function(a){for(var b=0;b<this.ec;b++)if(this.ea[b]&&this.ea[b][0]===a)return this.ea[b][1];return null},select:function(a){for(var b=0;b<this.ec;b++)if(this.ea[b]&&this.ea[b][1]===a){"next"===this.options.selection&&b+1<this.ec&&(this.ea[b+1][2]="on",this.Ok(b+1),this.Nk(b+1));this.ea[b][3]=
"current";this.me=b;this.options.currentStep=a;this.Ok(b);this.Nk(b);this.fC();break}for(b=0;b<this.ec;b++)this.dy(b)},deselect:function(a,b,c,e){for(var h=0;h<this.ec;h++)if(this.ea[h]&&this.ea[h][1]===a){b?this.ea[h][2]=b:this.ea[h][2]="off";c?this.ea[h][3]=c:this.ea[h][3]="visited";e?this.ea[h][4]=e:this.ea[h][4]="none";this.me=-1;"next"===this.options.selection&&h+1<this.ec&&(this.ea[h+1][2]="off",this.Ok(h+1),this.Nk(h+1));this.Ok(h);this.Nk(h);this.by(h);break}},nextSelectableStep:function(){for(var a=
this.me;a<this.ec;a++)if(a+1<this.ec&&this.ea[a+1]&&"on"===this.ea[a+1][2])return this.ea[a+1][1];return this.ea[this.me][1]},previousSelectableStep:function(){for(var a=this.me;0<=a;a--)if(this.ea[a-1]&&"on"===this.ea[a-1][2])return this.ea[a-1][1];return this.ea[this.me][1]}})})()});
//# sourceMappingURL=oj-modular.map