define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,e){function d(a,b){this.WJ=b;this.RK=a;this.uG="/"}a.jd=function(a){this.h(a)};o_("AttributeGroupHandler",a.jd,a);a.a.aa(a.jd,a.a,"oj.AttributeGroupHandler");a.jd.prototype.h=function(b){a.jd.j.h.call(this);this.Ak=b?b:{};this.Lj={};this.no=0;this.bm=this.ml();for(var d in this.Ak)b=this.bm.indexOf(this.Ak[d]),-1!==b&&this.bm.splice(b,1)};a.jd.prototype.ml=function(){return[]};a.a.b("AttributeGroupHandler.prototype.getValueRamp",{ml:a.jd.prototype.ml});
a.jd.prototype.xo=function(a){if(this.Ak[a])return this.Ak[a];this.Lj[a]||(this.Lj[a]=this.bm[this.no],this.no==this.bm.length-1?this.no=0:this.no++);return this.Lj[a]};a.a.b("AttributeGroupHandler.prototype.getValue",{xo:a.jd.prototype.xo});a.jd.prototype.kB=function(){var a=[],b;for(b in this.Lj)a.push({category:b,value:this.Lj[b]});return a};a.a.b("AttributeGroupHandler.prototype.geCategoryAssignments",{kB:a.jd.prototype.kB});a.jd.prototype.PA=function(a,b){this.Ak[a]=b};a.a.b("AttributeGroupHandler.prototype.addMatchRule",
{PA:a.jd.prototype.PA});var b={CSS_TEXT_PROPERTIES:function(a,d){var e={};a&&(a.hasClass("oj-gaugeMetricLabel")&&a.hasClass(a.parentNode,"oj-ledGauge")&&(e["font-size"]=!0,e.color=!0),a.hasClass(a,"oj-chartSliceLabel")&&(e.color=!0));return b.Cy(a,d,!1,e)},CSS_BACKGROUND_PROPERTIES:function(a,d){return b.Cy(a,d,!0,{})},CSS_URL:function(a){return b.VJ(a)},bu:"rgb(254, 0, 254)",cu:"Times",du:"1px",fu:"1",eu:"normal",sM:function(a,b){return a.css(b)},VJ:function(a){return(a=a.css("content"))&&-1!==a.indexOf("url(")?
a.slice(a.indexOf("url(")+4,a.length-1).replace(/"/g,""):a},iF:function(a){var b="";a.css("border-top-color")&&(b+="border-color: "+a.css("border-top-color")+";");a.css("border-width")&&(a.css("border-style")&&"none"!=a.css("border-style"))&&(b+="border-width: "+a.css("border-width")+";");a.css("background-color")&&(b+="background-color: "+a.css("background-color")+";");return b},mF:function(a,d){var e="",g=a.css("font-family");g&&g!==b.cu&&(e+="font-family: "+g.replace(/"/g,"'")+";");(g=a.css("font-size"))&&
(g!==b.du&&!d["font-size"])&&(e+="font-size: "+g+";");(g=a.css("font-weight"))&&g!==b.fu&&(e+="font-weight: "+g+";");(g=a.css("color"))&&(g!==b.bu&&!d.color)&&(e+="color: "+g+";");(g=a.css("font-style"))&&g!==b.eu&&(e+="font-style: "+g+";");return e},Cy:function(a,b,d,e){e||(e={});if(!a)return b;var l;b&&(l=a.attr("style"),a.attr("style",l+b));b="";!0!==d&&(b+=this.mF(a,e));!1!==d&&(b+=this.iF(a));l&&a.attr("style",l);return b}};a.ma("oj.dvtBaseComponent",e.oj.baseComponent,{lr:[],Dv:[],BL:"ar cs da de el es fi fr hu it iw ja ko nl no pl pt pt_BR ro ru sk sv th tr zh_CN zh_TW".split(" "),
_create:function(){this.Pm=new DvtContext(this.element[0]);this.Pm.setReadingDirection(this._GetReadingDirection());this.element.attr("tabIndex",0);this.yb=this.ve(this.Pm,this.Ha,this);this.Pm.getStage().addChild(this.yb);this.jK(this.ni());this.Ty();this.Nn();this.PE();this.Ee();a.sa.Zk(this.element[0],e.proxy(this.Bn,this))},PE:function(){var a=e(document.createElement("div"));a.attr("style","display:none;");a.text(JSON.stringify(this.options));this.element.append(a)},cf:function(){return["oj-dvtbase"]},
ni:function(){return{}},jK:function(a){for(var d=this.cf(),h=this.element.attr("class"),g="",l=0;l<d.length;l++)g=g+d[l]+" ";h&&(g+=h);this.element.attr("class",g);d=e(document.createElement("div"));d.attr("style","display:none;");this.element.append(d);d.css("font-family",b.cu);d.css("font-size",b.du);d.css("color",b.bu);d.css("font-weight",b.fu);d.css("font-style",b.eu);for(var k in a)h=e(document.createElement("div")),h.addClass(k),d.append(h),this.iK(h,a[k])},iK:function(a,b){if(b instanceof Array)for(var d=
0;d<b.length;d++)this.Jz(a,b[d]);else this.Jz(a,b)},Jz:function(a,e){var h=new d(this.options,e.path),g;e.property&&(g=(g=b[e.property])?g(a,h.xo()):b.sM(a,e.property));null==g||"string"==typeof g&&""==g.replace(/^\s+/g,"")||h.FN(g)},nk:function(){return{"oj-ojDvtCommon.labelClearSelection":"DvtUtilBundle.CLEAR_SELECTION","oj-ojDvtCommon.labelMonthShortJanuary":"DvtUtilBundle.MONTH_SHORT_JANUARY","oj-ojDvtCommon.labelMonthShortFebruary":"DvtUtilBundle.MONTH_SHORT_FEBRUARY","oj-ojDvtCommon.labelMonthShortMarch":"DvtUtilBundle.MONTH_SHORT_MARCH",
"oj-ojDvtCommon.labelMonthShortApril":"DvtUtilBundle.MONTH_SHORT_APRIL","oj-ojDvtCommon.labelMonthShortMay":"DvtUtilBundle.MONTH_SHORT_MAY","oj-ojDvtCommon.labelMonthShortJune":"DvtUtilBundle.MONTH_SHORT_JUNE","oj-ojDvtCommon.labelMonthShortJuly":"DvtUtilBundle.MONTH_SHORT_JULY","oj-ojDvtCommon.labelMonthShortAugust":"DvtUtilBundle.MONTH_SHORT_AUGUST","oj-ojDvtCommon.labelMonthShortSeptember":"DvtUtilBundle.MONTH_SHORT_SEPTEMBER","oj-ojDvtCommon.labelMonthShortOctober":"DvtUtilBundle.MONTH_SHORT_OCTOBER",
"oj-ojDvtCommon.labelMonthShortNovember":"DvtUtilBundle.MONTH_SHORT_NOVEMBER","oj-ojDvtCommon.labelMonthShortDecember":"DvtUtilBundle.MONTH_SHORT_DECEMBER","oj-ojDvtCommon.labelScalingSuffixThousand":"DvtUtilBundle.SCALING_SUFFIX_THOUSAND","oj-ojDvtCommon.labelScalingSuffixMillion":"DvtUtilBundle.SCALING_SUFFIX_MILLION","oj-ojDvtCommon.labelScalingSuffixBillion":"DvtUtilBundle.SCALING_SUFFIX_BILLION","oj-ojDvtCommon.labelScalingSuffixTrillion":"DvtUtilBundle.SCALING_SUFFIX_TRILLION","oj-ojDvtCommon.labelScalingSuffixQuadrillion":"DvtUtilBundle.SCALING_SUFFIX_QUADRILLION"}},
Ty:function(){var b=this.nk(),d={},e;for(e in b){var g=b[e],l=a.F.Bs(e);d[g]=l}DvtBundle.addLocalizedStrings(d)},_destroy:function(){this.element.children().remove()},_setOptions:function(a){this._superApply(arguments);this.Ee()},ve:o_d(null),Ha:function(a){if((a&&a.getType?a.getType():null)==DvtActiveElementChangeEvent.TYPE)a=a.getId(),this.element.attr("aria-activedescendant",a);else return null},Bn:function(){var a=this.element.width(),b=this.element.height();5<=Math.abs(a-this.cs)+Math.abs(b-
this.$q)&&(this.yb.render(null,a,b),this.cs=a,this.$q=b)},Nn:o_a(),vJ:function(b){var d=a.Ka.ud();if(0===d.indexOf("en"))this.ty(b+".js");else{for(var e=d.split("_"),d=[],g=0;g<e.length;g++){for(var l="",k=0;k<g+1;k++)0!=k&&(l+="_"),l+=e[k];d.push(l)}for(e=d.length-1;0<=e;e++)-1!==this.BL.indexOf(d[e])&&this.ty(b+"_"+d[e]+".js")}},ty:function(b){if(!this.lr[b]){var d=a.Ka.Mh(b),h=this,g=this.lr;e.getScript(d,function(){g[b]=!0;h.Ee()})}},Ee:function(){for(var a=0;a<this.Dv.length;a++)if(!this.lr[this.Dv[a]])return;
this.cs=this.element.width();this.$q=this.element.height();this.yb.render(this.options,this.cs,this.$q)},refresh:function(){this.Pm.setReadingDirection(this._GetReadingDirection());this.Ty();this.Ee()},getNodeBySubId:function(a){var b;this.yb&&this.yb.getAutomation&&(b=this.yb.getAutomation());return b?b.nP(a):null}});a.Bj=function(a){this.h(a)};o_("ShapeAttributeGroupHandler",a.Bj,a);a.a.aa(a.Bj,a.jd,"oj.ShapeAttributeGroupHandler");a.Bj.Hm="square circle diamond plus triangleDown triangleUp human".split(" ");
a.Bj.prototype.ml=function(){return a.Bj.Hm.slice()};a.Xh=function(b){this.Hm=[];var d=e(document.createElement("div"));d.attr("style","display:none;");d.attr("id","attrGps");e(document.body).append(d);for(var h=0;h<a.Xh.qA.length;h++){var g=e(document.createElement("div"));g.addClass(a.Xh.qA[h]);d.append(g);this.Hm.push(g.css("color"))}d.remove();this.h(b)};o_("ColorAttributeGroupHandler",a.Xh,a);a.a.aa(a.Xh,a.jd,"oj.ColorAttributeGroupHandler");a.Xh.qA="oj-dvt-category-index1 oj-dvt-category-index2 oj-dvt-category-index3 oj-dvt-category-index4 oj-dvt-category-index5 oj-dvt-category-index6 oj-dvt-category-index7 oj-dvt-category-index8 oj-dvt-category-index9 oj-dvt-category-index10 oj-dvt-category-index11 oj-dvt-category-index12".split(" ");
a.Xh.prototype.ml=function(){return this.Hm.slice()};d.prototype.OK=function(a,b,d,e){for(var l={};a&&-1<b.indexOf(d);){var k=b.substring(0,b.indexOf(d));e&&void 0===a[k]&&(a[k]={});a=a[k];b=b.substring(b.indexOf(d)+1,b.length)}a&&(l.object=a,l.parameter=b);return l};d.prototype.Iz=function(a){void 0===this.zk&&(a=this.OK(this.RK,this.WJ,this.uG,a),this.zk=a.object,this.tr=a.parameter)};d.prototype.xo=function(){this.Iz(!1);return void 0===this.zk?void 0:this.zk[this.tr]};d.prototype.FN=function(a){this.Iz(!0);
this.zk[this.tr]!==a&&(this.zk[this.tr]=a)}});
//# sourceMappingURL=oj-modular.map