define(["ojs/ojcore","jquery","ojs/ojmodel","ojs/ojdatacollection-common","ojs/ojtable"],function(a){a.Pa=function(e,d){a.Pa._init(this,e,d,null)};o_("ModelRow",a.Pa,a);a.a.aa(a.Pa,a.La,"ModelRow.ModelRow");a.Pa.prototype.h=function(){a.La.j.h.call(this)};a.Pa.prototype.attributes={};a.a.b("ModelRow.prototype.attributes",{attributes:a.Pa.prototype.attributes});a.Pa.prototype.id=null;a.a.b("ModelRow.prototype.id",{id:a.Pa.prototype.id});a.Pa.prototype.Kd=null;a.a.b("ModelRow.prototype.idAttribute",
{Kd:a.Pa.prototype.Kd});a.Pa._init=function(a,d,b,c){var f=null;a.h();a.wh=d;a.id=d.id;a.Kd=d.Kd;a.attributes=d.attributes;b=b||{};for(f in c)c.hasOwnProperty(f)&&(a[f]=c[f]);a.context=b.context};a.Pa.prototype.clone=function(){return this.wh.clone()};a.a.b("ModelRow.prototype.clone",{clone:a.Pa.prototype.clone});a.Pa.prototype.get=function(a){return this.wh.get(a)};a.a.b("ModelRow.prototype.get",{get:a.Pa.prototype.get});a.Pa.prototype.zs=o_c("wh");a.a.b("ModelRow.prototype.getModel",{zs:a.Pa.prototype.zs});
a.Pa.prototype.set=function(a,d,b){return this.wh.set(a,d,b)};a.a.b("ModelRow.prototype.set",{set:a.Pa.prototype.set});a.Pa.prototype.keys=function(){return this.wh.keys()};a.a.b("ModelRow.prototype.keys",{keys:a.Pa.prototype.keys});a.Pa.prototype.re=function(){return this.wh.re()};a.a.b("ModelRow.prototype.values",{re:a.Pa.prototype.re});a.Pa.prototype.Cc=function(){return this.wh.Cc()};a.a.b("ModelRow.prototype.pairs",{Cc:a.Pa.prototype.Cc});a.ba=function(e,d){a.ba._init(this,e,d,null)};o_("CollectionRowSet",
a.ba,a);a.ba.prototype.oe=1;a.a.b("CollectionRowSet.prototype.sortDirection",{oe:a.ba.prototype.oe});a.ba.prototype.ee=null;a.a.b("CollectionRowSet.prototype.comparator",{ee:a.ba.prototype.ee});a.ba.prototype.Se=!0;a.a.b("CollectionRowSet.prototype.sortSupported",{Se:a.ba.prototype.Se});a.a.aa(a.ba,a.l,"CollectionRowSet.CollectionRowSet");a.ba.prototype.h=function(){a.ba.j.h.call(this)};a.ba._init=function(a,d,b,c){var f;a.mb=[];a.K=0;a.h();if(c)for(f in c)c.hasOwnProperty(f)&&(a[f]=c[f]);a.ab=d;
a.rp()};a.ba.prototype.at=function(e,d){var b=this.ab.at(e,d);return null!=b?new a.Pa(b):null};a.a.b("CollectionRowSet.prototype.at",{at:a.ba.prototype.at});a.ba.prototype.fetch=function(a){if(this.Jp.call(this)){this.Pr.call(this);a=a||{};var d=this,b=null!=a.startIndex?!0:!1,c=this.K;this.K=b?a.startIndex:0;var f=0<a.pageSize?a.pageSize:-1,h=this.ab.clone();b?this.ab.Ko(this.K,f).done(function(){var a=d.Qv(h,d.ab,c,d.K,f);d.rp.call(d);d.Tn.call(d,a,h);d.ye.call(d,!0)}):this.ab.fetch({success:function(a){a=
d.Qv(h,a,c,d.K,f);d.rp.call(d);d.Tn.call(d,a,h);d.ye.call(d,!0)}})}};a.a.b("CollectionRowSet.prototype.fetch",{fetch:a.ba.prototype.fetch});a.ba.prototype.get=function(e,d){return new a.Pa(this.ab.get(e,d))};a.a.b("CollectionRowSet.prototype.get",{get:a.ba.prototype.get});a.ba.prototype.Ne=o_c("ab");a.a.b("CollectionRowSet.prototype.getCollection",{Ne:a.ba.prototype.Ne});a.ba.prototype.hasMore=function(){return this.ab.hasMore};a.a.b("CollectionRowSet.prototype.hasMore",{hasMore:a.ba.prototype.hasMore});
a.ba.prototype.indexOf=function(a,d){return this.ab.indexOf(a.zs(),d)};a.a.b("CollectionRowSet.prototype.indexOf",{indexOf:a.ba.prototype.indexOf});a.ba.prototype.ob=function(){return this.ab.ob()};a.a.b("CollectionRowSet.prototype.isEmpty",{ob:a.ba.prototype.ob});a.ba.prototype.size=function(){return this.ab.size()};a.a.b("CollectionRowSet.prototype.size",{size:a.ba.prototype.size});a.ba.prototype.sort=function(){this.ab.comparator=this.comparator;return this.ab.sort(null)};a.a.b("CollectionRowSet.prototype.sort",
{sort:a.ba.prototype.sort});a.ba.prototype.totalSize=function(){return this.ab.Kl};a.ba.prototype.rp=function(){var e=this;this.ab.on(a.H.q.ADD,function(d){a.ba.j.Ha.call(e,a.l.q.ADD,{rowIdx:e.ab.indexOf(d),row:new a.Pa(d)})});this.ab.on(a.H.q.REMOVE,function(d){a.ba.j.Ha.call(e,a.l.q.REMOVE,{rowIdx:e.ab.indexOf(d),row:new a.Pa(d)})});this.ab.on(a.H.q.RESET,function(d){a.ba.j.Ha.call(e,a.l.q.RESET,d)});this.ab.on(a.H.q.SORT,function(d){a.ba.j.Ha.call(e,a.l.q.SORT,d)});this.ab.on(a.H.q.CHANGE,function(d){a.ba.j.Ha.call(e,
a.l.q.CHANGE,{rowIdx:e.ab.indexOf(d),row:new a.Pa(d)})});this.ab.on(a.H.q.DESTROY,function(d){a.ba.j.Ha.call(e,a.l.q.DESTROY,d)});this.ab.on(a.H.q.SYNC,function(d){a.ba.j.Ha.call(e,a.l.q.SYNC,d)});this.ab.on(a.H.q.ERROR,function(d){a.ba.j.Ha.call(e,a.l.q.ERROR,d);e.ye.call(e,!1)})};a.ba.prototype.Qv=function(e,d,b,c,f){var h=[];if(0<d.size()){var g=0;e.each(function(b){b=e.indexOf(b);b<c?(h[g]={rowIdx:b,status:a.l.xb.bg},g++):0<f&&b>=c+f&&(h[g]={rowIdx:b,status:a.l.xb.bg},g++)});d.each(function(l){var k=
d.indexOf(l);if(0<f&&k>=c&&k<c+f||0>f){var n=e.size();if(k<b||k>n-1)h[g]={rowIdx:k,status:a.l.xb.Zh},g++;else{var n=l.keys(),m=e.at(k),p=!1,q;for(q=0;q<n.length;q++)if(l.get(n[q]).toString()!=m.get(n[q]).toString()){h[g]={rowIdx:k,status:a.l.xb.ym};p=!0;g++;break}p||(h[g]={rowIdx:k,status:a.l.xb.sm},g++)}}})}else g=0,e.each(function(b){h[g]={rowIdx:e.indexOf(b),status:a.l.xb.bg};g++});return h};a.ba.prototype.Tn=function(e,d){var b=!0,c;for(c=0;c<e.length;c++)if(e[c].status!=a.l.xb.sm){b=!1;break}if(b)this.ye.call(this,
!1);else{b=!0;for(c=0;c<e.length;c++)if(e[c].status!=a.l.xb.Zh){b=!1;break}if(b)this.ye.call(this,!0);else{for(c=0;c<e.length;c++)b=e[c].rowIdx,e[c].status==a.l.xb.Zh?a.ba.j.Ha.call(this,a.l.q.ADD,{rowIdx:b,row:this.ab.at(b)}):e[c].status==a.l.xb.bg?a.ba.j.Ha.call(this,a.l.q.REMOVE,{rowIdx:b,row:d.at(b)}):e[c].status==a.l.xb.ym&&a.ba.j.Ha.call(this,a.l.q.CHANGE,{rowIdx:b,row:this.ab.at(b)});this.ye.call(this,!1)}}};a.ba.prototype.Jp=function(){return!this.wk};a.ba.prototype.Pr=function(){this.wk=
!0;a.ba.j.Ha.call(this,a.l.q.REQUEST,null)};a.ba.prototype.ye=function(e){this.wk=!1;a.ba.j.Ha.call(this,a.l.q.SYNC,e)};a.sb=function(e,d){if(!(e instanceof a.g)){var b=a.F.k("oj-ojTable.dataInvalidType.summary"),c=a.F.k("oj-ojTable.dataInvalidType.detail");throw new a.t(b,c,a.t.xa.ERROR);}a.sb.j.constructor.call(this,e,d);this.Y=new a.ba(e,this.options);this.vp();this.h();if(null!=d&&("enabled"==d.startFetch||null==d.startFetch)||null==d){var f=this;setTimeout(function(){f.fetch({startFetch:"enabled"})},
0)}};o_("CollectionTableDataSource",a.sb,a);a.a.aa(a.sb,a.ia,"oj.CollectionTableDataSource");a.sb.prototype.h=function(){a.sb.j.h.call(this)};a.a.b("CollectionTableDataSource.prototype.Init",{h:a.sb.prototype.h});a.sb.prototype.at=function(a){return this.Y.at(a)};a.a.b("CollectionTableDataSource.prototype.at",{at:a.sb.prototype.at});a.sb.prototype.fetch=function(e){e=e||{};null!=e.startIndex&&a.sb.j.startIndex.call(this,e.startIndex);"enabled"==e.startFetch?(this.Y.ob()||"undefined"===typeof this.Y.size())&&
this.Y.fetch(e):this.Y.fetch(e)};a.a.b("CollectionTableDataSource.prototype.fetch",{fetch:a.sb.prototype.fetch});a.sb.prototype.get=function(a){return this.Y.get(a)};a.a.b("CollectionTableDataSource.prototype.get",{get:a.sb.prototype.get});a.sb.prototype.hasMore=function(){return null!=this.Y?this.Y.hasMore():!1};a.a.b("CollectionTableDataSource.prototype.hasMore",{hasMore:a.sb.prototype.hasMore});a.sb.prototype.indexOf=function(a){return this.Y.indexOf(a)};a.a.b("CollectionTableDataSource.prototype.indexOf",
{indexOf:a.sb.prototype.indexOf});a.sb.prototype.size=function(){return this.Y.size()};a.a.b("CollectionTableDataSource.prototype.size",{size:a.sb.prototype.size});a.sb.prototype.sort=function(a,d){this.Y.comparator=a;this.Y.sort(d)};a.a.b("CollectionTableDataSource.prototype.sort",{sort:a.sb.prototype.sort});a.sb.prototype.totalSize=function(){return this.Y.totalSize()};a.a.b("CollectionTableDataSource.prototype.totalSize",{totalSize:a.sb.prototype.totalSize});a.sb.prototype.vp=function(){var e=
this;this.Y.on(a.l.q.ADD,function(d){a.ia.j.handleEvent.call(e,a.l.q.ADD,d)});this.Y.on(a.l.q.REMOVE,function(d){a.ia.j.handleEvent.call(e,a.l.q.REMOVE,d)});this.Y.on(a.l.q.RESET,function(d){a.ia.j.handleEvent.call(e,a.l.q.RESET,d)});this.Y.on(a.l.q.SORT,function(d){a.ia.j.handleEvent.call(e,a.l.q.SORT,d)});this.Y.on(a.l.q.CHANGE,function(d){a.ia.j.handleEvent.call(e,a.l.q.CHANGE,d)});this.Y.on(a.l.q.DESTROY,function(d){a.ia.j.handleEvent.call(e,a.l.q.DESTROY,d)});this.Y.on(a.l.q.SYNC,function(d){a.ia.j.handleEvent.call(e,
a.l.q.SYNC,d)});this.Y.on(a.l.q.ERROR,function(d){a.ia.j.handleEvent.call(e,a.l.q.ERROR,d)})}});
//# sourceMappingURL=oj-modular.map